Added CTIX Connector v1.0.0 for XSOAR Marketplace (Partner ID: cyware-238)
demisto/content pull request #10062
Opened 2020-11-19 19:10 UTC by gladipero

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-11-19 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=10062) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=10062) before we can accept your contribution.<br/><hr/>**gladipero** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=10062) it.</sub>

2020-11-22 20:36 UTC, esharf requested changes
please fix also the errors in the validations and lints.

2020-11-22 20:36 UTC, esharf commented on Packs/CTIX/Integrations/CTIX/CTIX_test.py
> +    from CTIX import Client, ip_details_command
unit tests should contain a given-when-then section.
e.g.
Given
\- 6.7.8.9
When
\- collecting data for an existing indicator
Then
\- ensure the return data contains ...

2020-11-22 20:36 UTC, esharf commented on Packs/CTIX/Integrations/CTIX/CTIX.py
> +        if enhanced == "True":
```suggestion
        if argToBool(enhanced):
```

2020-11-22 20:36 UTC, esharf commented on Packs/CTIX/Integrations/CTIX/CTIX.py
> +        if enhanced == "True":
```suggestion
        if argToBool(enhanced):
```

2020-11-22 20:36 UTC, esharf commented on Packs/CTIX/Integrations/CTIX/CTIX.py
> +        if enhanced == "True":
```suggestion
        if argToBool(enhanced):
```

2020-11-22 20:36 UTC, esharf commented on Packs/CTIX/Integrations/CTIX/CTIX.py
> +        if enhanced == "True":
```suggestion
        if argToBool(enhanced):
```

2020-11-22 20:36 UTC, esharf commented on Packs/CTIX/Integrations/CTIX/CTIX.yml
> +script:
please add the proxy and trust any certificate params. (Required also in the demisto-sdk validates.

2020-12-01 17:10 UTC, gladipero commented
Closing this PR as will be opening via the corporate account due to CLA issues.

2020-12-01 17:10 UTC, closed without merging

2020-12-03 17:46 UTC, bakatzir commented
opened in: https://github.com/demisto/content/pull/10251