XSOAR [CSPi184] Aria packet intelligence update with latest REST API
demisto/content pull request #10061
Opened 2020-11-19 18:37 UTC by stang-aria

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This update using the latest REST API of ARIA PacketIntelligence. Update the existing Integration ARIAPacketIntelligence.
Use RCS arguments to select different SIA.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details: minimum SDS version 1.0.9
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation

2020-11-20 15:12 UTC, stang-aria commented
There are two possible issues for Run Validations from CI/CD testing. I have a problem to commit the ARIAPacketIntelligence.yml file because the demisto-sdk has a pre-check and give me this error messages. Our latest updates will break the backward compatibility, is there anyway to skip this?
`================= Running validation on modified files =================

Validating Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.yml as integration
Validating scheme for Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.yml
Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.yml: [BC104] - Possible backwards compatibility break, You've changed the name of a command or its arg in the file, please undo, the command was:
aria-block-conversation
`
And the failure of parsing the README.md, seems like it is a existing CI/CD issue I have met before

2020-11-22 08:38 UTC, bakatzir commented on Packs/ARIAPacketIntelligence/pack_metadata.json
> +    "support": "xsoar",
```suggestion
    "support": "partner",
```

2020-11-22 08:45 UTC, DeanArbel commented on Packs/ARIAPacketIntelligence/pack_metadata.json
> +    "useCases": ["Incident Response", "Threat Intelligence Management"],
```suggestion
    "useCases": ["Incident Response", "Threat Intelligence Management"],
    "certification": "certified",
```

2020-11-22 13:32 UTC, DeanArbel requested changes
Awesome work on this pull request!
- I see you provided a test playbook, but I see it's not configured in `conf.json`. Is it possible to receive a license so it could be tested in the content build?
- See the rest of my comments.

2020-11-22 13:32 UTC, DeanArbel commented on Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/README.md
> +>| Name: convBlock<br/>Definition: 192.168.0.1/32 @ 390 & 192.168.10.23/32 @ 389 <> TCP : DROP, END<br/>RCS: PIdevice@all | command_state: Success<br/>timestamp: 1601688609 | {'FQN': '<sds_cluster_0>
Please use <br/> and not <br> in README.md

2020-11-22 13:35 UTC, DeanArbel commented on Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.yml
> +  dockerimage: demisto/python3:3.8.6.12176
```suggestion
  dockerimage: demisto/python3:3.8.6.13358
```

2020-11-22 13:43 UTC, DeanArbel commented
> There are two possible issues for Run Validations from CI/CD testing. I have a problem to commit the ARIAPacketIntelligence.yml file because the demisto-sdk has a pre-check and give me this error messages. Our latest updates will break the backward compatibility, is there anyway to skip this?

@stang-aria If you believe this is not a break of backward compatibility, or that the changes are required, then please push it without a pre-check, and comment about it. If needed, we'll force merge the PR. We might need to add a warning to the release notes of this change detailing in what way backward compatibility was broken.

> And the failure of parsing the README.md, seems like it is a existing CI/CD issue I have met before

Feel free to ignore this error.

2020-11-28 22:11 UTC, stang-aria commented
@DeanArbel Thanks very much for your review. I pushed my changes without pre-commit by removing the hooks to skip the demisto-sdk validation. Is there any better ways to do this? How to add a warning to the release notes of this change detailing in what way backward compatibility was broken? The pack_metadata.json and the doc-string/comments should be resolved.

2020-12-01 18:18 UTC, stang-aria commented
@DeanArbel right now there is only a CI/CD issue in README.md and I think that can be ignored. Just let me know if you have any more comments here and when can you make the push. Very appreciate!

2020-12-06 08:55 UTC, DeanArbel requested changes
@stang-aria The ci errors you're experiencing are related to the way the `md` file is parsed. It tries to translate the table HTML elements to the appropriate HTML representation.
In this case, it sees `<>` as an HTML element, and fails to find a closure to this element.

Since this is not actually an HTML element, you should add escape characters to the brackets - see the suggestions below.

2020-12-06 08:55 UTC, DeanArbel commented on Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/README.md
> +>| Name: convBlock<br/>Definition: 192.168.0.1/32 @ 390 & 192.168.10.23/32 @ 389 <> TCP : DROP, END<br/>RCS: PIdevice@all | command_state: Success<br/>timestamp: 1601688609 | {'FQN': '<sds_cluster_0>
Please add an escape character to the `<>` characters.
```suggestion
>| Name: convBlock<br/>Definition: 192.168.0.1/32 @ 390 & 192.168.10.23/32 @ 389 \<\> TCP : DROP, END<br/>RCS: PIdevice@all | command_state: Success<br/>timestamp: 1601688609 | {'FQN': '<sds_cluster_0>.<sds_node_sia12>.<sds_component_PacketIntelligence>.<sds_uuid_07023d45-d4a0-4204-949d-86ce009fd172>', 'IPAddress': '192.168.0.100', 'Model': 'sia-lx2160', 'OS': 'GNU/Linux', 'Processor': 'sia-lx2160', 'trid': '230e10c2-0dea-c12f-8929-092130038061', 'instance_number': '0', 'completion': True},<br/>{'FQN': '<sds_cluster_0>.<sds_node_sia32>.<sds_component_PacketIntelligence>.<sds_uuid_590c49ce-1286-481b-ae07-f4192130e7af>', 'IPAddress': '192.168.0.101', 'Model': 'sia-lx2160', 'OS': 'GNU/Linux', 'Processor': 'sia-lx2160', 'trid': '04972eb4-45b2-a877-12f2-4fcc7638f6c1', 'instance_number': '0', 'completion': True} |
```

2020-12-06 08:55 UTC, DeanArbel commented on Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/README.md
> +>| Name: convRecord<br/>Definition: 192.168.0.1/32 @ 390 & 192.168.10.23/32 @ 389 <> TCP : REDIRECT-VLAN A 1234, ALERT email 2 4 one-shot 1, END<br/>RCS: PIdevice@all | command_state: Success<br/>tim
Please add an escape character to the <> characters.
```suggestion
>| Name: convRecord<br/>Definition: 192.168.0.1/32 @ 390 & 192.168.10.23/32 @ 389 \<\> TCP : REDIRECT-VLAN A 1234, ALERT email 2 4 one-shot 1, END<br/>RCS: PIdevice@all | command_state: Success<br/>timestamp: 1601688621 | {'FQN': '<sds_cluster_0>.<sds_node_sia32>.<sds_component_PacketIntelligence>.<sds_uuid_590c49ce-1286-481b-ae07-f4192130e7af>', 'IPAddress': '192.168.0.101', 'Model': 'sia-lx2160', 'OS': 'GNU/Linux', 'Processor': 'sia-lx2160', 'trid': '0fbc758b-ab0d-95f4-9955-56c96089fa98', 'instance_number': '0', 'completion': True},<br/>{'FQN': '<sds_cluster_0>.<sds_node_sia12>.<sds_component_PacketIntelligence>.<sds_uuid_07023d45-d4a0-4204-949d-86ce009fd172>', 'IPAddress': '192.168.0.100', 'Model': 'sia-lx2160', 'OS': 'GNU/Linux', 'Processor': 'sia-lx2160', 'trid': 'ab63e403-4f3a-1f3c-6005-c01d249eb185', 'instance_number': '0', 'completion': True} |
```

2020-12-06 08:55 UTC, DeanArbel commented on Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/README.md
> +>| Name: convAlert<br/>Definition: 192.168.0.1/32 @ 390 & 192.168.10.23/32 @ 389 <> TCP : ALERT email 2 4 re-trigger-count 1000, END<br/>RCS: null | command_state: Success<br/>timestamp: 1601688638 |
Please add an escape character to the <> characters.
```suggestion
>| Name: convAlert<br/>Definition: 192.168.0.1/32 @ 390 & 192.168.10.23/32 @ 389 \<\> TCP : ALERT email 2 4 re-trigger-count 1000, END<br/>RCS: null | command_state: Success<br/>timestamp: 1601688638 | {'FQN': '<sds_cluster_0>.<sds_node_sia32>.<sds_component_PacketIntelligence>.<sds_uuid_590c49ce-1286-481b-ae07-f4192130e7af>', 'IPAddress': '192.168.0.101', 'Model': 'sia-lx2160', 'OS': 'GNU/Linux', 'Processor': 'sia-lx2160', 'trid': '92573cdb-9e81-b408-1417-6668cddae433', 'instance_number': '0', 'completion': True},<br/>{'FQN': '<sds_cluster_0>.<sds_node_sia12>.<sds_component_PacketIntelligence>.<sds_uuid_07023d45-d4a0-4204-949d-86ce009fd172>', 'IPAddress': '192.168.0.100', 'Model': 'sia-lx2160', 'OS': 'GNU/Linux', 'Processor': 'sia-lx2160', 'trid': '48808901-91b2-5284-d1a3-39cb5fcb1add', 'instance_number': '0', 'completion': True} |
```

2020-12-07 02:46 UTC, stang-aria commented
@DeanArbel Thanks for your comments. Fixed for this issue.

2020-12-07 07:28 UTC, DeanArbel approved these changes

2020-12-07 07:31 UTC, merged