Added new Common Scripts
demisto/content pull request #10067
Opened 2020-11-20 15:32 UTC by fvigo

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added 5 new Common Scripts (used in the Expanse Pack but generic enough to be reused)

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

Co-Author: @jtschichold

2020-11-26 08:07 UTC, esharf requested changes

2020-11-26 08:07 UTC, esharf commented on Packs/CommonScripts/Scripts/AddKeyToList/AddKeyToList_test.py
> +from AddKeyToList import add_key_to_list_command
unit tests should contain given-when-then comment to describe the unit test scenario.
\-Given
    \<some input>
\- When
    \<some state>
Relevant also for all the unit tests files.
\- Then
    \<ensure some behviour>

2020-11-27 20:51 UTC, fvigo commented
@esharf thanks for the review. changes applied, please recheck.

2020-11-30 10:25 UTC, esharf approved these changes
@fvigo please fix the conflict and we are ready to merge.

2020-11-30 14:45 UTC, fvigo commented
@esharf done

2020-11-30 15:18 UTC, merged