Tanium bug fixed
demisto/content pull request #10134
Opened 2020-11-25 13:24 UTC by moishce

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30907

## Description
 handle properly the '=', ';' characters wen input into "parameters".

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-11-25 14:06 UTC, ShahafBenYakir reviewed
Not sure I understand the idea here (also ran and got the same results as before). Just use `param.split('=',1)` instead of `param.split('=')`

2020-11-25 17:27 UTC, yaakovi requested changes
add a unit test specific for this function.
see it fails for the original code and passes with the updated cde

2020-11-26 09:26 UTC, ShahafBenYakir commented on Packs/Tanium/ReleaseNotes/1_0_4.md
> +- Upgraded the Docker image to demisto/python3:3.8.6.13358.
```suggestion
- Fixed an issue where parameters were not handled properly if contained '=' or ';' characters,
- Upgraded the Docker image to demisto/python3:3.8.6.13358.
```

2020-11-26 09:26 UTC, ShahafBenYakir commented on Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
>          return parameter_conditions
Let's reverse the list again (to correspond to the previous order)

2020-11-26 09:26 UTC, ShahafBenYakir commented on Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
>      def parse_action_parameters(self, parameters):
Add doc string and type hints

2020-11-26 09:26 UTC, ShahafBenYakir commented on Packs/Tanium/Integrations/Tanium_v2/Tanium_v2_test.py
> +def test_parse_action_parameters(parameters, accepted_result):
Add given when then with cases

2020-11-26 17:20 UTC, ShahafBenYakir commented on Packs/Tanium/Integrations/Tanium_v2/Tanium_v2_test.py
> +        - validate that everything is extracted properly even if there is within the value "=" or ";"
```suggestion
    Given
        A string representing a key=value list separated by ';'
    When
        - When calling the "parse_action_parameters" function to extract it to a dictionary
    Then
        - validate that everything is extracted properly even if there is within the value "=" or ";"
```

2020-11-26 17:20 UTC, ShahafBenYakir commented on Packs/Tanium/Integrations/Tanium_v2/Tanium_v2_test.py
> +        - validate that everything is extracted properly even if there is within the value "=" or ";"
Let's add cases in the Given and Then

2020-11-26 17:55 UTC, ShahafBenYakir approved these changes

2020-11-26 18:47 UTC, yaakovi approved these changes

2020-11-26 21:47 UTC, merged