CheckPointFirewall_v2 - update output prefix
demisto/content pull request #10137
Opened 2020-11-25 15:19 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/content/pull/9774

## Description
update output prefix in the command `checkpoint-package-list` from `CheckPoint.Packages` to `CheckPoint.Package`

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-12-01 13:41 UTC, glicht commented on Packs/CheckpointFirewall/ReleaseNotes/2_0_4.md
> +- Updated the ***checkpoint-package-list*** command outputs.
Add a Breaking Change comment:
```suggestion
- **Breaking Change**: Updated the ***checkpoint-package-list*** command outputs. Changed output prefix from: `CheckPoint.Packages` to `CheckPoint.Package`.
```

2020-12-02 09:43 UTC, yaakovi approved these changes

2020-12-02 12:20 UTC, amshamah419 requested changes
Regenerate the docs/readme to reflect the change to context paths.

2020-12-02 12:28 UTC, amshamah419 approved these changes
Thanks @adi88d , docs look good.

2020-12-02 12:41 UTC, merged