Email Communication Pack Enhancement
demisto/content pull request #10222
Opened 2020-12-02 10:26 UTC by darkushin

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30662

## Description
Adding a unique ID to the email subject.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2020-12-06 18:03 UTC, yuvalbenshalom requested changes
see my comments

2020-12-06 18:03 UTC, yuvalbenshalom commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
>          return_error(f"The PreprocessEmail script has encountered an error:\n {e} \nA new incidents was created.")
this whole handling is strange.
we are catching a family if problems where the cases we do not find the current incident(if it is new) should be much more narrow. then we log it as an error that was encountered where it include the flow that is expected and not an error at all.

2020-12-08 12:42 UTC, altmannyarden commented on Packs/EmailCommunication/IncidentFields/incidentfield-emailcodegenerator.json
> +    "cliName": "emailcodegenerator",
it's not an ID (massage ID nor thread ID). Maybe we could change it emailgeneratedcode

2020-12-16 16:09 UTC, yuvalbenshalom commented on Packs/EmailCommunication/ReleaseNotes/1_3_2.md
> +- To avoid performance issues, limited the time to look for related incidents to 2 months.
- `**Breaking Change** To avoid performance issues, limited the time to look for related incidents to 2 months.`

2020-12-16 16:14 UTC, yuvalbenshalom requested changes
looks good.
please see my comments/additions

2020-12-16 16:14 UTC, yuvalbenshalom commented on Packs/EmailCommunication/ReleaseNotes/1_3_2.md
> +- To avoid performance issues, limited the time to look for related incidents to 2 months.
change to:
```
**Breaking Change** To avoid performance issues, limited the time to look for related incidents to 2 months.
```

2020-12-16 16:14 UTC, yuvalbenshalom commented on Packs/EmailCommunication/Scripts/PreprocessEmail/README.md
> +If you wish to extend this period, you can make a copy of the script and change the `QUERY_TIME` constant in line #12 to the desired period.
and configure the new script to be the pre-processing script of the incident type `Email Communication`.

2020-12-16 17:23 UTC, yuvalbenshalom approved these changes

2020-12-21 16:35 UTC, yuvalbenshalom requested changes
see my comments to the last fix.
also, what is the case when the list dont exist? this is the common one, it should be inn debug.
the others cases should be errors.

2020-12-21 16:35 UTC, yuvalbenshalom commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +                      f'{user_defined_time[0].get("Contents")}.\nUsing the default query time - 60 days')
if you got an error here, you may not have an array in `user_defined_time`. and there for have an exception when doing `user_defined_time[0]`

2020-12-21 16:35 UTC, yuvalbenshalom commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +        demisto.debug('Invalid input for number of days to query. Input should be a number only, representing the '
lets note the name of the list.

2020-12-22 13:01 UTC, amshamah419 reviewed
If you remove the changelog file for the incident field, is it failing validations? If so, please open a dev-bug. If not, let's go ahead and remove it since all changes should be documented in only the release notes.

2020-12-22 13:21 UTC, darkushin commented on Packs/EmailCommunication/IncidentFields/incidentfield-emailgeneratedcode_CHANGELOG.md
> +## [Unreleased]
Removed, it's not failing validations.

2020-12-22 13:21 UTC, darkushin commented on Packs/EmailCommunication/ReleaseNotes/1_3_2.md
> +- **incidentfield-emailgeneratedcode_CHANGELOG.md**
removed

2020-12-22 14:16 UTC, yuvalbenshalom approved these changes

2020-12-22 14:17 UTC, merged

2020-12-22 16:41 UTC, omercnet commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +                                                         "timeField": "modified", "Contents": "id,status"})[0]
GetIncidentsByQuery doesn't have a "Contents" prameter