Slack - add filtered_tags parameter
demisto/content pull request #10240
Opened 2020-12-02 16:48 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/20175

## Description
Added **filtered_tags** parameter to filter the messages sending from Demisto by tags.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-12-06 09:57 UTC, liorblob requested changes
Nice, please add unit tests

2020-12-06 09:57 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack.py
> +    if message_type == MIRROR_TYPE:
Place it under the `if` in line 1328

2020-12-06 09:57 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack.py
> +        if tags and not entry_tags:
`entry_tags` will never be there in versions under 6.1. We need to explain it properly in the parameter description

2020-12-06 09:57 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack.yml
> +- display: Comma separated list of tags To filter the messages sent from demisto.
Only supported in 6.1 and above. @yaakovi How do we want to handle this?

2020-12-06 09:57 UTC, liorblob commented on Packs/Slack/ReleaseNotes/1_3_8.md
> +- Added **filtered_tags** parameter to filter the messages sending from Demisto by tags.
Only supported in 6.1 and above.

2020-12-07 10:12 UTC, liorblob approved these changes
Looks good, minor changes.
Verify descriptions/RN with tech docs

2020-12-07 10:12 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack_test.py
> +    from Slack import slack_send
no need for this import

2020-12-07 10:12 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack_test.py
> +    slack_send()
```suggestion
    Slack.slack_send()
```

2020-12-07 10:12 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack_test.py
> +    from Slack import slack_send
Same

2020-12-07 10:12 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack_test.py
> +    from Slack import slack_send
Same

2020-12-07 10:12 UTC, liorblob commented on Packs/Slack/Integrations/Slack/Slack.yml
> +- display: Comma separated list of tags To filter the messages sent from demisto. Only supported in Demisto V6.1 and above.
Might be too much info here, we can split with `additionalInfo`.

2020-12-07 13:25 UTC, liorblob approved these changes

2020-12-07 13:41 UTC, adi88d commented
@amshamah419 please review the `Slack.yml` and `1_3_8.md` files

2020-12-09 11:23 UTC, merged