Cortex XDR endpoints health check
demisto/content pull request #10520
Opened 2020-12-21 14:58 UTC by EliorKedar

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/31417

## Description
This playbook will query disconnected/lost Cortex XDR endpoints with a provided last seen time range playbook input.
The playbook will also generate a CSV report, including a detailed list of the unhealthy endpoints, and send the report to the provided email addresses.
This playbook also includes an incident type with a dedicated layout to visualize the collected data.

## Screenshots
![Cortex_XDR_endpoints_health_check](https://user-images.githubusercontent.com/60568193/102789974-83870800-43ad-11eb-9a2c-88ad5dcfb173.png)

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-12-27 07:40 UTC, ShirleyDenkberg commented
@michalgold Doc review completed.

2021-01-12 22:41 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints.yml
> +      name: Was an disconnected endpoint found?
@ShirleyDenkberg should this be "an" or "a"?

2021-01-12 22:58 UTC, David-BMS requested changes
@EliorKedar I got two emails
![image](https://user-images.githubusercontent.com/51712181/104384532-4e984c00-553a-11eb-94b1-b73945f4588d.png)
The one from EWS also contained an extra file
![image](https://user-images.githubusercontent.com/51712181/104384596-666fd000-553a-11eb-8dd8-880707b014d5.png)

2021-01-12 22:58 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints.yml
> +              simple: LOST
Is LOST the only relevant status here?

2021-01-12 22:58 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints.yml
> +        simple: Disconnected XDR endpoints.csv
Consider adding a date to the file name to make it easier for the user.

2021-01-12 22:58 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints.yml
> +  A Job to periodically query disconnected Cortex XDR endpoints with a provided last seen time range playbook input.
Provide a link for setting up a job documentation

2021-01-12 22:58 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints_README.md
> +A Job to periodically query disconnected Cortex XDR endpoints with a provided last seen time range playbook input.
Provide a link for job documentation.

2021-01-12 22:58 UTC, David-BMS commented on Packs/CortexXDR/IncidentTypes/incidenttype-Cortex_XDR_Disconnected_endpoints.json
> +    "layout": "294c4eca-caf4-429d-8277-56676b7bee9d",
fix id.

2021-01-12 22:58 UTC, David-BMS commented on Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Disconnected_endpoints.json
> +    "id": "294c4eca-caf4-429d-8277-56676b7bee9d",
fix id.

2021-01-13 21:20 UTC, EliorKedar commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints.yml
> +              simple: LOST
yes

2021-01-13 21:22 UTC, EliorKedar commented
> @EliorKedar I got two emails
> ![image](https://user-images.githubusercontent.com/51712181/104384532-4e984c00-553a-11eb-94b1-b73945f4588d.png)
> The one from EWS also contained an extra file
> ![image](https://user-images.githubusercontent.com/51712181/104384596-666fd000-553a-11eb-8dd8-880707b014d5.png)

You getting 2 emails because both Gmail and EWS are enabled.
The EWS extra file and bad formatting is due to  a bug in exchange version 2016

2021-01-14 08:13 UTC, David-BMS approved these changes

2021-01-14 08:50 UTC, merged