Add IntSightsV2 pack
demisto/content pull request #10549
Opened 2020-12-22 20:23 UTC by Constantine19

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-12-22 20:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=10549) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=10549) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=10549) it.</sub>

2020-12-23 16:18 UTC, DeanArbel reviewed
@Constantine19 Thank you very much for your contribution!
I'm sure our users will love an IntSights supported integration.

Please note my review is incomplete, as @guykeller will complete it.
Feel free to address some of these comments, but I suggest waiting a bit for his review.

2021-01-05 16:31 UTC, guykeller requested changes

2021-01-05 16:31 UTC, guykeller commented on Packs/IntSightsV2/Integrations/IntSightsV2/IntSightsV2.py
> +def hash_identifier(hash_val):
I suggest using `auto_detect_indicator_type` from `commonServerPython` instead of this function

2021-01-11 21:10 UTC, Constantine19 commented
Hi @DeanArbel, @guykeller ,

Appreciate the comments and suggestions. The file `IntSightsV2.py` was developed back in the days by Demisto. I just added one extra feature to it due to a customer request.
Unfortunately, I'm going to have to close this PR and address your suggestions in the future as we update the app to a new generation. For now, I will edit the existing pack with that new feature. Thanks again!

2021-01-11 21:10 UTC, closed without merging