Archer v2 fixed argument and rm parameter
demisto/content pull request #10691
Opened 2020-12-30 22:51 UTC by moishce

## Status
- [x] Ready

## Related Issues
https://github.com/demisto/etc/issues/32208

2020-12-31 07:50 UTC, jochman requested changes
need to force it, but it's fine.

2020-12-31 07:50 UTC, jochman approved these changes

2020-12-31 08:24 UTC, ShahafBenYakir commented on Packs/ArcherRSA/ReleaseNotes/1_1_8.md
> +##### RSA Archer v2
Add a breaking changes comment for the removed param fetch_filter

2021-01-03 12:34 UTC, moishce commented
Need force merge because we removed a parameter that was added by mistake to the YML file.

2021-01-03 12:37 UTC, merged