Intel 471 feed
demisto/content pull request #10714
Opened 2021-01-03 14:32 UTC by JasBeilin

## Status
- [x] In Progress

## Related Issues
fixes: https://github.com/demisto/etc/issues/25106

## Description
Adding Malware feed and actor feed

## Minimum version of Demisto
- [X] 5.5.0

## Does it break backward compatibility?
   - [X] No

## Must have
- [X] Tests
- [ ] Documentation

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
> +
```suggestion
```

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
> +    return FEED_URL + url_suffix.strip('&')
```suggestion
    return f'{FEED_URL}{url_suffix.strip('&')}'
```

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
> +    Paginf is done using
?
```suggestion
    Paginf is done using
```

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.py
> +    return FEED_URL + url_suffix.strip('&')
```suggestion
    return f'{FEED_URL}{url_suffix.strip('&')}'
```

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
> +- additionalinfo: 'Long unix time. Search indicators with activity range overlapping given time (including). Object fields: activity.first and activity.last. Empty indicates unbounded'
add an example.

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
> +- additionalinfo: 'Long unix time. Search indicators with activity range overlapping given time (including). Object fields: activity.first and activity.last. Empty indicates unbounded'
add an example.

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
> +  type: 8
these 2 should be at the bottom

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
> +  type: 8
these 2 should be at the bottom

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
> +- additionalinfo: 'Long unix time. Search indicators with activity range overlapping given time (including). Object fields: activity.first and activity.last. Empty indicates unbounded'
add an example.

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
> +- additionalinfo: 'Long unix time. Search indicators with activity range overlapping given time (including). Object fields: activity.first and activity.last. Empty indicates unbounded'
add an example.

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
> +    name: intel471-get-indicators
we do not want the same cmd to be in 2 different integrations. please rename to `intel471(-)actors-get-indicators`

2021-01-04 09:29 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
> +    name: intel471-get-indicators
we do not want the same cmd to be in 2 different integrations. please rename to `intel471(-)malware-get-indicators`

2021-01-04 13:41 UTC, JasBeilin commented on Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
> +            handle_indicator_function(client, item, feed_config, service_name, indicator_type, indicator_field,
its the name of the function given in the cofiguration. I can make the default one "private"

2021-01-14 15:07 UTC, ShirleyDenkberg commented
@bakatzir  Doc review completed.

2021-01-17 12:07 UTC, bakatzir commented
Waiting on default reputation and reliability of both feeds prior to the merge.

2021-01-25 07:40 UTC, bakatzir commented on Packs/FeedAWS/ReleaseNotes/1_1_1.md
> +Infrastructure improvements.
```suggestion
- Internal code improvements.
```

2021-01-25 07:40 UTC, bakatzir commented on Packs/FeedFastly/ReleaseNotes/1_1_1.md
> +Infrastructure improvements.
```suggestion
- Internal code improvements.
```

2021-01-25 07:42 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors_test.py
> +
```suggestion
```

2021-01-25 07:42 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Actors/README.md
> +This integration was integrated and tested with version xx of Intel471 Actors Feed
```suggestion
```

2021-01-25 07:43 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware_test.py
> +# import demistomock as demisto
```suggestion
```

2021-01-25 07:43 UTC, bakatzir commented on Packs/FeedIntel471/Integrations/Intel471Malware/README.md
> +This integration was integrated and tested with version xx of Intel471 Malware Feed
```suggestion
```

2021-01-25 07:44 UTC, bakatzir commented on Packs/FeedIntel471/pack_metadata.json
> +    "description": "This pack fetches indicators from intel471",
Let's try to give a more detailed desc

2021-01-25 07:44 UTC, bakatzir commented on Packs/FeedJSON/ReleaseNotes/1_1_1.md
> +Infrastructure improvements.
```suggestion
- Internal code improvements.
```

2021-01-25 07:45 UTC, bakatzir commented on Packs/iDefense/ReleaseNotes/3_0_1.md
> +Infrastructure improvements.
- Internal code improvements.

2021-01-25 07:45 UTC, bakatzir commented on Packs/iDefense/ReleaseNotes/3_0_1.md
> +Infrastructure improvements.
- Internal code improvements.

2021-01-25 07:45 UTC, bakatzir requested changes
Please tend to all of the unresolved comments.

2021-01-25 08:46 UTC, bakatzir commented
Fails only on the update of the APIMODULE fromversion as expected:
```
Validating backwards compatibility for Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.yml
Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.yml: [ST103] - You've added fromversion to an existing file in the system, this is not allowed, please undo.
```
force merging.

2021-01-25 08:46 UTC, bakatzir approved these changes

2021-01-25 08:46 UTC, merged