Cortex XDR Device Control Violations
demisto/content pull request #10719
Opened 2021-01-03 18:55 UTC by EliorKedar

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/31327
## Description
Cortex XDR device control violations - added as part of a new API endpoint.
 - playbook for fetching DC violations.
 - Response playbook  DC violations.
 - 
## Screenshots
![Cortex_XDR_device_control_violations](https://user-images.githubusercontent.com/60568193/103486346-e0e77400-4e05-11eb-8dbf-a0a1d907916f.png)
![JOB_-_Cortex_XDR_query_endpoint_device_control_violations](https://user-images.githubusercontent.com/60568193/103486365-f9578e80-4e05-11eb-8d86-fe24394fcc72.png)

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x ] Documentation

2021-01-06 12:34 UTC, David-BMS requested changes
@EliorKedar Update the playbook images they still have typo's

2021-01-06 12:34 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_README.md
> +* PANW - Hunting and threat detection by indicator type V2
Looks like the Readme still has the old name

2021-01-06 12:34 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_device_control_violations.yml
> +          "x": 447.5,
Line between task 5 and 6 dont look good

2021-01-06 22:28 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_device_control_violations_README.md
> +![Cortex XDR device control violations](Insert the link to your image here)
Update link to image

2021-01-06 22:28 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/playbook-JOB_-_Cortex_XDR_query_endpoint_device_control_violations_README.md
> +![JOB - Cortex XDR query endpoint device control violations](Insert the link to your image here)
Update link to image

2021-01-06 22:28 UTC, David-BMS commented on Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v3_README.md
> +![Cortex XDR incident handling v3](Insert the link to your image here)
Update link to new image

2021-01-07 07:58 UTC, ShirleyDenkberg commented
@David-BMS @michalgold Doc review completed

2021-01-07 09:09 UTC, David-BMS approved these changes
@EliorKedar Please update the readme images for all 3 playbooks and add the link and description to configure the job. Besides that approved.

2021-01-07 09:31 UTC, David-BMS commented on Packs/CortexXDR/Layouts/layoutscontainer-Cotrex_XDR_Device_Control_Violations.json
> +                "name": "XDR Device Control Violations",
@EliorKedar Also please move the layout here
![image](https://user-images.githubusercontent.com/51712181/103876080-e1209180-50db-11eb-9195-8e3e765093f3.png)

2021-01-07 10:00 UTC, ShirleyDenkberg commented
@David-BMS @michalgold Added the Active Directory Query v2 integration to the list of integrations needed in the playbook-Cortex_XDR_device_control_violations_README.  
Doc review completed.

2021-01-10 14:50 UTC, merged