Shift management and handover
demisto/content pull request #10750
Opened 2021-01-05 15:10 UTC by evisochek

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28569

## Description
Shift management and shift handover are crucial processes of SOC team management.
This pack's purpose is Provide a single interface for all those essential elements in one place in order to prevent loss of data in the shift handover process. 

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [x ] Documentation

2021-01-14 10:50 UTC, ShirleyDenkberg commented
@David-BMS @evisochek Doc review completed.

2021-01-17 18:11 UTC, ShirleyDenkberg commented
@Itay4 @glicht @teizenman Doc review completed.

2021-01-17 20:51 UTC, David-BMS requested changes

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/IncidentTypes/incidenttype-Shift_handover.json
> +	"packID": "27061f91-5a0b-4156-8aeb-c6c28ef1570a",
Is this relevant?

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Layouts/layoutscontainer-shift_handover.json
> +    "id": "c6610ca1-32e1-49b2-84c9-239d7e3b405d",
Change ID

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Layouts/layoutscontainer-shift_handover.json
> +                "fields": [
Clean non relevant fields.

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Assign_Active_Incidents_to_Next_Shift_V2.yml
> +id: Assign Active Incidents to Next Shift_V2
Remove _ from name

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Assign_Active_Incidents_to_Next_Shift_V2.yml
> +name: Assign Active Incidents to Next Shift_V2
Same

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Assign_Active_Incidents_to_Next_Shift_V2.yml
> +  \ the query and no users on call. \n\nSearch results are the default 100 incidents\
Is the 100 incident still valid?

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Set_a_Shift_handover_meeting.yml
> +id: Set a Shift handover meeting
Name is Set? consider changing to Set Up

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Set_a_Shift_handover_meeting.yml
> +name: Set a Shift handover meeting
Same

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      name: Assign Active Incidents to Next Shift_V2
Remove _

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      playbookName: Assign Active Incidents to Next Shift_V2
Remove _

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      name: Set a Shift handover meeting
If name changes update

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      playbookName: Set a Shift handover meeting
Same

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +    simple: 'status:active  -category:job '
Leave out the incident type for shift handover

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover_README.md
> +* Assign Active Incidents to Next Shift_V2
Remove _

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/README.md
> +This pack's purpose is Provide a single interface for all those essential elements in one place in order to prevent loss of data in the shift handover process.
Upper case P in provided not needed.

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/ReleaseNotes/1_1_5.md
> +- **Shift manager briefing **
Fix markdown

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/ReleaseNotes/1_1_5.md
> +Search results are the default 100 incidents returned by the query.
Is this still relevant?

2021-01-17 20:51 UTC, David-BMS commented on Packs/ShiftManagement/pack_metadata.json
>      "email": "",
Add
Dependencies
Keywords
Tags
Categories

2021-01-18 09:19 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Assign_Active_Incidents_to_Next_Shift_V2.yml
> +      description: commands.local.cmd.get.users
@ShirleyDenkberg this is a server default description and not the correct description.

2021-01-18 09:20 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      description: commands.local.cmd.close.inv
@ShirleyDenkberg this is a server default description and not the correct description.

2021-01-18 09:20 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      description: commands.local.cmd.set.incident
@ShirleyDenkberg this is a server default description and not the correct description.

2021-01-18 09:20 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      description: commands.local.cmd.set.incident
@ShirleyDenkberg this is a server default description and not the correct description.

2021-01-26 11:26 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Assign_Active_Incidents_to_Next_Shift_V2.yml
> +    simple: 'status:active  -category:job '
make sure to exclude the shift handover type

2021-01-26 11:46 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      name: Set up a Shift handover meeting
Validate skip works

2021-01-26 11:48 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +      description: "This playbook reassigns Active Incidents to the current users\
There should be a link to the Job configuration article.

2021-01-26 11:49 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover.yml
> +- key: IncidentSearchQuery
If input is not needed remove it

2021-01-26 11:52 UTC, David-BMS commented on Packs/ShiftManagement/Playbooks/Shift_handover_README.md
> +| IncidentSearchQuery | Query for the incidents to reassign.  Incidents need to be active. The playbook will not reassign pending incidents.  | status:active  -category:job  | Optional |
Update accordingly.

2021-01-26 11:53 UTC, David-BMS approved these changes
We saw an issue with the OOO widget please review

Need to add playbook images to readmes

Make sure to test skip branch for meeting subplaybook

2021-01-26 15:17 UTC, evisochek commented
We saw an issue with the OOO widget please review - Fixed by @adi88d 

Need to add playbook images to readmes - Done.

Make sure to test skip branch for meeting subplaybook - Done.

2021-01-27 15:48 UTC, merged