Add Reliability to DBotScore Class
demisto/content pull request #10837
Opened 2021-01-11 15:41 UTC by Bargenish

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Description
Added the reliability argument to the DBotScore class to support the Source reliability option in XSOAR.

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-01-11 21:05 UTC, anara123 requested changes
add unit test

2021-01-11 21:05 UTC, anara123 approved these changes

2021-01-11 21:39 UTC, glicht requested changes

2021-01-11 21:39 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +        :type reliability: ``str``
This should be an enum. There are a fixed set of allowed values.

2021-01-11 21:44 UTC, glicht commented
> add unit test

Please also add a playbook test. It is important we have a good test end-to-end.

2021-01-14 23:53 UTC, yaakovi approved these changes
looks good to me

2021-01-14 23:53 UTC, yaakovi commented on Packs/Base/TestPlaybooks/playbook-Test-CreateDBotScore-With-Reliability.yml
> +        simple: ip
should be domain

2021-01-14 23:53 UTC, yaakovi commented on Packs/Base/TestPlaybooks/playbook-Test-CreateDBotScore-With-Reliability.yml
> +        simple: ip
should be domain

2021-01-15 10:07 UTC, glicht submitted a review, later dismissed

2021-01-15 10:07 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +    THIRD_PT_ENRICHMENT = 'A+ - 3rd party enrichment'
Can we change the naming of these constants to: A_PLUS, A, B, ...

2021-01-15 10:07 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +    @classmethod
Small remark: It is better practice to use staticmethod in such cases.

2021-01-20 11:11 UTC, yaakovi approved these changes

2021-01-20 11:11 UTC, merged