fixing SplunkPy to use custom ssl cert file if existing
demisto/content pull request #10844
Opened 2021-01-12 04:55 UTC by esharf

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/32649

## Description
adding the `SSL_CERT_FILE` and `CERT_FILE` to the verify step if existing.

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2021-01-14 15:00 UTC, glicht requested changes

2021-01-14 15:00 UTC, glicht commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
> +                                 verify=VERIFY_CERTIFICATE if not CUSTOM_CERT else CUSTOM_CERT)
This shouldn't be needed. requests picks up the certificate automatically.

2021-01-14 15:00 UTC, glicht commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
> +                                 verify=VERIFY_CERTIFICATE if not CUSTOM_CERT else CUSTOM_CERT)
Also for the other places that requests is used.

2021-01-18 12:43 UTC, esharf commented
this PR is not relevant the changes should not affect anything.

2021-01-18 12:43 UTC, closed without merging