ShiftManagment enhancements
demisto/content pull request #10874
Opened 2021-01-13 17:07 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/28569
https://github.com/demisto/etc/issues/32707
https://github.com/demisto/etc/issues/32366
https://github.com/demisto/etc/issues/32076
https://github.com/demisto/etc/issues/32639
https://github.com/demisto/etc/issues/32156

## Description
- Added the new argument *listname*  to GetUsersOnCall script.

Added to ShiftManagment pack the scripts:
- CreateChannelWrapper
- AssignToNextShiftOOO
- TimeToNextShift
- AssignAnalystToIncidentOOO
- ManageOOOusers
- OutOfOfficeListCleanup
- GetUsersOOO

Added to ShiftManagment pack the widgets:
- UsersOOO
- ShiftTimeLeft

## Screenshots
### UsersOOO widget:
<img src="https://user-images.githubusercontent.com/46249224/104484705-44c22780-55d2-11eb-96c1-bf8a43f46620.png" width="400" />

### ShiftTimeLeft widget:
<img src="https://user-images.githubusercontent.com/46249224/104484428-f876e780-55d1-11eb-9780-f45890b6e6d6.png" width="300" />

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-01-20 08:04 UTC, yaakovi requested changes
the README file (`Packs/ShiftManagement/Scripts/CreateChannelWrapper/README.md`) is empty.
remove it or generate the docs

2021-01-21 09:42 UTC, ShirleyDenkberg commented
@yaakovi Doc review completed.

2021-01-21 13:25 UTC, adi88d commented on Packs/ShiftManagement/Scripts/OutOfOfficeListCleanup/OutOfOfficeListCleanup.py
> +        list_name = f"OOO {list_name}"
Its by design, I added it to the description too

2021-01-23 15:41 UTC, yaakovi commented on Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/AssignAnalystToIncidentOOO.py
> +    assign_all = False if demisto.args().get('assignAll') == 'false' else True
use `argToBoolean`

2021-01-23 15:41 UTC, yaakovi commented on Packs/ShiftManagement/Scripts/GetUsersOOO/GetUsersOOO.py
> +    demisto.results({
why aren't you using `CommandResults`?
```suggestion
    return_results({
```

2021-01-23 15:41 UTC, yaakovi commented on Packs/ShiftManagement/Scripts/ManageOOOusers/ManageOOOusers.py
> +    if not ooo_list or ooo_list == [] or ooo_list == "":
```suggestion
    if not ooo_list:
```

2021-01-24 08:53 UTC, ShirleyDenkberg commented
@yaakovi Doc review completed.

2021-01-24 13:05 UTC, yaakovi approved these changes
nice work

2021-01-24 13:11 UTC, merged