Contrib/cds google chronicle detection
demisto/content pull request #11006
Opened 2021-01-21 11:23 UTC by crestdatasystems

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
A new feature of Detection Alert is introduced

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-01-24 18:43 UTC, ChanochShayner reviewed
Great job!!
I added some small comments,
Feel free to ask any question you have.

2021-01-25 06:27 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_0.md
> +- Maps incoming Chronicle incident fields. (Available from Cortex XSOAR 5.0.0).
Yes, it was a typo, we have updated it to 6.0.0.

2021-01-25 06:28 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_0.md
> +- Classifies Chronicle incidents (Available from Cortex XSOAR 5.0.0).
Yes, it was a typo, we have updated it to 6.0.0.

2021-01-25 06:29 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_0.md
> +#### Incident Types
Yes, we have added them in the latest commit.

2021-01-25 14:46 UTC, ChanochShayner commented
Demo was held today with @crestdatasystems,
It was great!!
There are small changes that need to be made, and after that, the PR is ready for merge.

2021-01-31 20:57 UTC, guykeller requested changes

2021-02-01 10:07 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/.secrets-ignore
> +'21a03d1fa2ce7e342534447e947a94b9f9f0ccfc57e96e86ca56a0074b646852',
yes @guykeller, these hashes are used in pytest mock.

2021-02-04 08:00 UTC, guykeller approved these changes

2021-02-04 15:29 UTC, merged