Creates MITRE ATT&CK indicators When fetching STIX Reports
demisto/content pull request #11183
Opened 2021-01-31 18:36 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/32328

## Description
- creates MITRE ATT&CK indicators When fetching STIX Reports
- added Course Of Action indicator field
- added Additional Details tab to MITRE ATT&CK layout with Courses of Action table

## Screenshots
Paste here any images that will help the reviewer
![image](https://user-images.githubusercontent.com/46249224/106394184-f3a09900-6403-11eb-993a-01a6bafe7eb7.png)

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [X] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-02-17 08:21 UTC, teizenman requested changes
1. I think that it would be better to break the huge `parse_reports_relationships` function into smaller functions.
2. Add more UTs to test the new logic.

2021-02-17 08:21 UTC, teizenman commented on Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
> +            if relationship_product in ('Cortex XDR Prevent', 'DNS Security', 'XSOAR'):
Create a constant for this list, it would be easier to modify it afterward if needed

2021-02-17 08:21 UTC, teizenman commented on Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
> +            if relationship_product in ('URL Filtering', 'NGFW', 'Wildfire', 'Threat Prevention'):
Same here

2021-02-17 08:21 UTC, teizenman commented on Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
>          A list of processed reports.
Add the new list that's being returned

2021-02-18 02:18 UTC, yaakovi reviewed
@michalgold @mayagoldb please review the layout
@adi88d please update the layout of 5.5 as well

2021-02-18 02:18 UTC, yaakovi commented on Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
> +            if relationship_product in (COURSE_OF_ACTION_U42):
```suggestion
            if relationship_product in COURSE_OF_ACTION_U42:
```

2021-02-18 02:18 UTC, yaakovi commented on Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
> +            if relationship_product in (COURSE_OF_ACTION_BP):
```suggestion
            if relationship_product in COURSE_OF_ACTION_BP:
```

2021-02-24 10:17 UTC, mayagoldb approved these changes

2021-03-02 12:03 UTC, ShirleyDenkberg commented
@yaakovi @mayagoldb @michalgold @teizenman Doc review completed.

2021-03-07 10:19 UTC, teizenman approved these changes

2021-03-07 10:20 UTC, merged