Contribution of Additional Tenable_io Commands - 020821
demisto/content pull request #11329
Opened 2021-02-08 16:18 UTC by rod-castillo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-07 09:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=11329) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=11329) before we can accept your contribution.<br/>**7** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: rod-castillo<br/>:white_check_mark: barchen1<br/>:white_check_mark: yuvalbenshalom<br/>:white_check_mark: guykeller<br/>:white_check_mark: guyfreund<br/>:white_check_mark: glicht<br/>:white_check_mark: mdrobniu<br/>:x: darkushin<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=11329) it.</sub>

2021-03-14 11:27 UTC, ShirleyDenkberg commented
@barchen1 @guykeller 
The following files were edited:
- integration yml
- Release Notes
- Integration README
The description file had no information.  I spoke with Rod and suggested that there be information on how to obtain the API key and the Secret key. 
There was no Pack README file to add content to.

2021-03-16 09:32 UTC, guykeller requested changes
A more general question - did we verify we don't get any duplicates after the fix?

2021-03-16 13:19 UTC, barchen1 commented on Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
> +    return True
@rod-castillo wanted to have an input validation to make sure that scan_id is a number

2021-03-16 15:32 UTC, guykeller approved these changes
Last few comments and we're done from my side
Just have a last look to make sure you're confident about merging

2021-03-16 15:32 UTC, guykeller commented on Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
> +    return not (scan_id == "" or scan_id.isalpha())
@barchen1 If you want to verify this is a number, `isalpha()` won't work, you need `isdigit()`
![image](https://user-images.githubusercontent.com/33782301/111335898-6cd71100-867d-11eb-891d-bf9fbc691cef.png)

2021-03-16 15:32 UTC, guykeller commented on Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
> +    return not (scan_id == "" or scan_id.isalpha())
```suggestion
    return not (scan_id == "" or not scan_id.isdigit())
```

2021-03-21 08:33 UTC, barchen1 approved these changes

2021-03-21 08:36 UTC, merged