Trigger Test Upload
demisto/content pull request #11529
Opened 2021-02-22 13:27 UTC by Bargenish

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-02-24 08:29 UTC, guyfreund requested changes
Looking good! 👏 , few notes:
1. Please output the `GCS_MARKET_BUCKET` & `SLACK_CHANNEL` values when we output the build params (in your branch in `config.yml` it should be line 240)

2021-02-24 08:50 UTC, Bargenish commented
@guyfreund done
<img width="462" alt="Screen Shot 2021-02-24 at 10 50 14" src="https://user-images.githubusercontent.com/21142167/108974421-226e0000-768e-11eb-8147-28fe06a01bad.png">

2021-02-25 08:19 UTC, Bargenish commented on .circleci/config.yml
> +              STORAGE_BATH_PATH="upload-flow/builds/$CIRCLE_BRANCH/$CREATE_INSTANCES_JOB_NUMBER/content/packs"
Should be `storage base path` (copied the name from the path branch).
The path to which upload the content to.

2021-02-25 08:35 UTC, guyfreund commented on Tests/Marketplace/copy_and_upload_packs.py
>          GCPConfig.STORAGE_BASE_PATH = production_base_path
This is fine, we can change the value in line 308 to `content/packs` just to avoid confusion.

2021-02-25 09:54 UTC, yaakovi approved these changes

2021-02-25 10:04 UTC, guyfreund approved these changes

2021-02-25 10:27 UTC, merged