Respond master
demisto/content pull request #11531
Opened 2021-02-22 15:50 UTC by dannomayernotabot

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-02-22 15:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=11531) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=11531) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=11531) it.</sub>

2021-02-22 16:31 UTC, teizenman commented
Hi @dannomayernotabot 
Please fill the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

2021-03-01 16:17 UTC, teizenman requested changes
1. Please fill in the readme file for the integration.
2. Some of the arguments' descriptions in the commands are not that descriptive, I would suggest changing them.
3. Please make the test_data files fake, remove any data that could be close to real data.

2021-03-01 16:17 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.py
> +        'name': args['tenant_id'] + ': ' + formatted_incident['incidentId'],
`tenant_id` is not a required argument, this access can fail.

2021-03-01 16:17 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.py
> +            return_results(get_remote_data_command(rest_client, demisto.args()))
This commands does not appear in the yml file.

2021-03-01 16:17 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst_description.md
> +- Here you should explain how to configure the instance in Demisto
```suggestion
```

2021-03-01 16:17 UTC, teizenman commented on Packs/Respond/pack_metadata.json
> +    "githubUser": []
It is highly recommended to add a github user for notifications.

2021-03-01 16:17 UTC, teizenman commented on Packs/Respond/pack_metadata.json
> +    "email": "",
You will need to provide an email.

2021-03-05 16:01 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/CHANGELOG.md
> +-
You can remove this file altogether

2021-03-10 18:25 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.py
> +    accounts = deduped_accounts
I didn't realize it's a dict.

2021-04-06 18:21 UTC, mchasepan commented
Slacked w Danno; he'll hope to work on this in the next week or two.

2021-04-06 19:32 UTC, phetmanyttk approved these changes

2021-05-06 14:40 UTC, teizenman requested changes
Make sure that the test data doesn't hold any sensitive data.

2021-05-06 14:40 UTC, teizenman commented on Packs/Respond/IncidentFields/incidentfield-Accounts.json
> +    "fromVersion": "5.0.0"
```suggestion
    "fromVersion": "6.0.0"
```

2021-05-06 14:40 UTC, teizenman commented on Packs/Respond/IncidentFields/incidentfield-Asset_Criticality.json
> +    "fromVersion": "5.0.0"
```suggestion
    "fromVersion": "6.0.0"
```

Please fix it in all relevant places.

2021-05-06 14:40 UTC, teizenman commented on Packs/Respond/IncidentFields/incidentfield-URL.json
> +    "cliName": "url",
Please add a prefix to *all* custom incident fields.
You should use something like `respond-<cli_name>`.

2021-05-06 14:40 UTC, teizenman commented on Packs/Respond/IncidentFields/incidentfield-URL.json
> +    "id": "incident_url",
The same goes here - add a dedicated prefix to *all* IDs.

2021-05-06 14:40 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.py
> +        # print(raw_incidents)
Please delete every comment that is not needed.

2021-05-06 14:40 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.py
> +    demisto.debug('in remote data 2')
Are we sure we want to keep it?

2021-05-06 14:40 UTC, teizenman commented on Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.py
> +        elif demisto.command() == 'mad-close-incident':
The integration is called RespondAnalyst, are we sure that we want the prefix to be `mad`?

2021-06-02 13:43 UTC, teizenman approved these changes

2021-06-02 13:47 UTC, merged