Vt v3
demisto/content pull request #11602
Opened 2021-02-28 17:31 UTC by jochman

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/20671

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation 

## TODO:
- [ ] Tests
- [ ] Test Playbook

2021-03-08 16:39 UTC, Itay4 requested changes
looks good overall 👍 
1. i am concerned with the size of some of the commands outputs, lets discuss about that
2. we should return an error entry if the resource is not found, and need to return dbotscore `0` for it
![image](https://user-images.githubusercontent.com/31018228/110323696-a4124600-801d-11eb-95fb-3e9d3f33d016.png)
3. please make sure all commands are tested in the test playbook

2021-03-09 09:37 UTC, jochman commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
> +    deprecated: true
should they stay there for bc?

2021-03-09 10:10 UTC, jochman commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
> +        f'{INTEGRATION_ENTRY_CONTEXT}.{object_type}Comments',
@Arsenikr WDYT?

2021-03-09 14:12 UTC, Arsenikr commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
> +        f'{INTEGRATION_ENTRY_CONTEXT}.{object_type}Comments',
@Itay4 @jochman I think that it will be easier to find the comments by the specific type

2021-03-09 23:01 UTC, jochman commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
> +        f'{INTEGRATION_ENTRY_CONTEXT}.{object_type}Comments',
I thought about it, to the user it'll be much easier to search by the ID (the indicator sent to get its comment).
Anyway, the API itself returns the indicator type (ip_address, file, domain or URL), so one source of truth sounds to me much better.

2021-03-16 13:00 UTC, jochman commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
> +      isArray: false
The api does not supports it

2021-03-21 12:57 UTC, bakatzir commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
> +configuration:
@jochman Please remember to add the reliability param as described here https://github.com/demisto/etc/issues/29347
and use it in the DBotScore classes(DBotScoreReliability).
you can approach @JasBeilin for further info.

2021-03-24 08:56 UTC, JasBeilin requested changes
Let me know if you need help with adding the reliability parameter to both YML and the integration code.

2021-03-24 14:28 UTC, ShirleyDenkberg commented
@@Arsenikra, @bakatzir, @JasBeilin, @Itay4 
Doc review is completed. 
There was no pack README file.  I created a pack README and sent it to @jochman. It should be added to this PR.

2021-03-24 15:08 UTC, JasBeilin commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
> +  defaultvalue: A - Completely reliable
```suggestion
  defaultvalue: C - Fairly reliable
```

2021-04-01 16:09 UTC, Itay4 commented on Packs/VirusTotal/Integrations/VirusTotalV3/README.md
> +
```suggestion
## Commands
```

2021-04-01 16:10 UTC, Itay4 commented on Packs/VirusTotal/Integrations/VirusTotalV3/README.md
> +### file
something is off with the commands docs.. you have `file` 5 times

2021-04-01 16:29 UTC, Itay4 commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
> +      isArray: false
we still need to support it

2021-04-01 16:31 UTC, Itay4 commented on Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_description.md
> +Your API key carries all your privileges, so keep it secure and don't share it with anyone.
please add here what needs to be set for the username password from versions before 6.1

2021-04-07 11:33 UTC, Itay4 commented on Packs/VirusTotal/Integrations/VirusTotalV3/README.md
> +The integration was integrated and tested with version v3 API of VirusTotal (API v3)
```suggestion
The integration was integrated and tested with API v3 of VirusTotal.
```

2021-04-07 11:40 UTC, Itay4 approved these changes
make sure we dont have `VirusTotal V3` anywhere (e.g. readme, playbook names, etc..) and use `VirusTotal (API v3)`

2021-04-07 20:03 UTC, JasmineGranot approved these changes

2021-04-08 06:07 UTC, JasBeilin approved these changes

2021-04-08 08:28 UTC, merged