Contrib/concentric ai -> Playbook enhancement.
demisto/content pull request #11630
Opened 2021-03-02 13:37 UTC by shams-concentricai

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR hopes to improve performance and enhance the playbook of the existing integration.

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [X ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [X] Tests
- [ ] Documentation

2021-03-02 13:43 UTC, shams-concentricai commented
Hi Team 

I am hoping to get this resolves soon ,please let me know if anything else is required. 
Also i have some doubts , would love to clarify some of em with you.

2021-03-04 10:05 UTC, shams-concentricai commented
Hi @teizenman can you help me with the circleci validations , it's claiming that something is wrong with my release notes but not mentioning what exactly !

2021-03-05 19:07 UTC, shams-concentricai commented
Hi @teizenman  , could you please review this ?

2021-03-06 13:30 UTC, teizenman requested changes
Please do not delete the content of the 1_1_0.md file.
You should just update the new RN file 1_2_0.md.

2021-03-06 13:30 UTC, teizenman commented on Packs/ConcentricAI/ReleaseNotes/1_2_0.md
> +- **ConcentricAI Security Event**- Updated the Docker image to: *demisto/python3:3.9.1.15759*.
Those items were not changed, please remove them from the RN file.

2021-03-06 14:38 UTC, teizenman commented
> Please do not delete the content of the 1_1_0.md file.
> You should just update the new RN file 1_2_0.md.

@shams-concentricai Please note this comment as well.

2021-03-08 07:51 UTC, shams-concentricai commented
@teizenman the checks are passing now , could you please approve ?

2021-03-08 08:55 UTC, teizenman requested changes

2021-03-08 08:55 UTC, teizenman commented on Packs/ConcentricAI/ReleaseNotes/1_2_0.md
> +     ,user details of the owner along with summaryReport of the incident.
```suggestion
- The Playbook now enables one to fetch all file details, file sharing permissions, user details of the owner along with summaryReport of the incident.
```

I guess that the new line was made by mistake: 
![image](https://user-images.githubusercontent.com/50326704/110297956-aa43fa80-7ffc-11eb-9940-fd3b7f13e56a.png)

2021-03-08 08:56 UTC, teizenman commented
@shams-concentricai 
I will merge it after you will push the fix for the RN.

2021-03-08 10:48 UTC, teizenman approved these changes

2021-03-08 10:50 UTC, merged