Reliability cybertotal indicator
demisto/content pull request #11634
Opened 2021-03-02 17:29 UTC by JasBeilin

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: https://github.com/demisto/etc/issues/29347

## Description
Added reliability to cybertotal pack. PR will fail as the new parameter in YML file is a must. Should be further discussed in the demo.

## Screenshots
Reliability can be seen in the indicator's layout:
![image](https://user-images.githubusercontent.com/71636766/109688422-eb678500-7b8c-11eb-9d01-44f6ce9dbf41.png)

It cannot be seen while at indicator's screen. Is this working as designed? Aggregated should not take the only one if only one source reliability?

![image](https://user-images.githubusercontent.com/71636766/109688234-bc511380-7b8c-11eb-9ed9-da548961e8ad.png)

## Minimum version of Demisto
- [x] 5.0.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details: The new integrationReliability parameter is a must. 

## Must have
- [x] Tests
- [x] Documentation

2021-03-03 01:21 UTC, Archibald7 approved these changes

2021-03-03 08:02 UTC, roysagi requested changes

2021-03-03 08:02 UTC, roysagi commented on Packs/CyberTotal/ReleaseNotes/1_0_4.md
> +- Added reliability parameter
```suggestion
- Added support for the *Source Reliability* integration parameter.
```

2021-03-03 08:02 UTC, roysagi commented on Packs/Base/ReleaseNotes/1_7_19.md
> +- Internal code improvements
```suggestion
- Maintenance and stability enhancements.
```

2021-03-06 19:56 UTC, bakatzir commented on Packs/CyberTotal/Integrations/CyberTotal/CyberTotal_test.py
> +    response = ip_reputation_command(client, args, 10, reliability='C - Fairly reliable')[0]
please consider validating the `DBotScoreReliability` object content

2021-03-12 06:15 UTC, bakatzir commented
Can we close this PR? @JasBeilin

2021-04-04 12:52 UTC, closed without merging