MS Graph Handle 404 Response
demisto/content pull request #11640
Opened 2021-03-03 10:03 UTC by darkushin

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/34324

## Description
Added 404 error handling to the MicrosoftApiModule.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests

2021-03-03 13:40 UTC, yuvalbenshalom requested changes
looks good. see my comments.

2021-03-03 13:40 UTC, yuvalbenshalom commented on Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
> +                error_message = 'Page Not Found - 404 Response'
```suggestion
                error_message = 'Not Found - 404 Response'
```
in this case it is not a page

2021-03-03 13:40 UTC, yuvalbenshalom commented on Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
> +    """Exception raised for 404 - Page Not Found errors.
```suggestion
    """Exception raised for 404 - Not Found errors.
```

2021-03-03 14:54 UTC, darkushin commented
@amshamah419 Please review the release notes. Please review only [RN 1](https://github.com/demisto/content/pull/11640/files#diff-25a469500140cd4084a2d0cca5db774a5e13c046da6e8bae1eb6aae38432839c) and [RN 2](https://github.com/demisto/content/pull/11640/files#diff-ddbe8ab21df77e49c922d1013d015ba51aff5f0c7aef3cf20977f257927623d3) as the rest are identical.

2021-03-03 15:21 UTC, amshamah419 commented on Packs/AzureKubernetesServices/ReleaseNotes/1_0_1.md
> +- Updated **MicrosoftApiModule** to handle ***404 - Page Not Found*** response.
```suggestion
- Updated **MicrosoftApiModule** to handle a ***404 - Page Not Found*** response.
```

2021-03-04 08:51 UTC, yuvalbenshalom approved these changes

2021-03-04 08:52 UTC, merged