SplunkPy Basic Auth
demisto/content pull request #11651
Opened 2021-03-04 09:30 UTC by amshamah419

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/34169

## Description
Authentication fails behind a load balancer since the connection is authenticated for specific servers. Added the basic=true flag to ensure auth with every request.

2021-03-04 10:28 UTC, glicht requested changes
Need to take also care of: `splunk_edit_notable_event_command` which does direct http calls.

2021-03-04 10:34 UTC, ShahafBenYakir commented
@guyfreund FYI

2021-03-04 10:39 UTC, amshamah419 commented
@glicht If this works for the customer we can implement it. This is a known issue for Splunk cloud users due to the load balancer not passing the auth session to the different servers. This is more or less a patch solution until something official from Splunk comes out. If this doesn't work, it would require a redesign of the auth session and we _really_ would need to evaluate if we want to do that.

2021-03-17 14:49 UTC, guyfreund commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
> +        'basic': True
If you set it to basic at all cases we wouldn't be able to use `auth token`:

<img src=https://user-images.githubusercontent.com/53565845/111486910-91e08800-8740-11eb-881c-5ec74ba0fd2a.png width=500>

In what cases do we need a basic auth?

2021-06-19 20:31 UTC, glicht commented
@amshamah419 I think we can close this one. Seems that auth token fixed the issue.

2021-06-20 05:43 UTC, closed without merging