Crowd Strike Falcon X - bug with uploading file
demisto/content pull request #11675
Opened 2021-03-07 09:05 UTC by ohaim1008

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-17 16:11 UTC, yuvalbenshalom requested changes
see my comments

2021-03-17 16:11 UTC, yuvalbenshalom commented on Packs/CrowdStrikeFalconX/ReleaseNotes/1_1_1.md
> +- Fix an issue with where *cs-fx-upload-file* didn't uploaded exe and dll files correctly.
```suggestion
- Fix an issue where **cs-fx-upload-file** failed to upload .exe and .dll files correctly.
```

2021-03-17 16:11 UTC, yuvalbenshalom commented on Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
> +        return self._http_request("POST", url_suffix, data=open(file_path, 'rb'))
where do you close the file?

2021-03-17 17:04 UTC, yuvalbenshalom approved these changes

2021-03-18 08:16 UTC, amshamah419 commented on Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
> +Please pay attention that there are 2 ways to upload a file to the sandbox.
```suggestion
There are 2 ways to upload a file to the sandbox.
```

2021-03-18 08:16 UTC, amshamah419 commented on Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
> +1. Using ***cs-fx-upload-file*** command with **submit_file=yes**.
```suggestion
1. Using the ***cs-fx-upload-file*** command with **submit_file=yes**.
```

2021-03-18 08:16 UTC, amshamah419 commented on Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
> +2. Using ***cs-fx-upload-file*** command and afterwards the ***cs-fx-submit-uploaded-file command***,
```suggestion
2. Using the ***cs-fx-upload-file*** command and afterwards the ***cs-fx-submit-uploaded-file command***, 
```

2021-03-18 08:16 UTC, amshamah419 commented on Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
> +For more information look at the commands documentation.
```suggestion
For more information review the documentation for the commands.
```

2021-03-18 08:16 UTC, amshamah419 commented on Packs/CrowdStrikeFalconX/ReleaseNotes/1_1_1.md
> +- Fix an issue where **cs-fx-upload-file** failed to upload .exe and .dll files correctly.
```suggestion
- Fix an issue where ***cs-fx-upload-file*** failed to upload `.exe` and `.dll` files correctly.
```

2021-03-18 09:35 UTC, merged