Jira V2 - fixed command jira-get-id-by-attribute to return only active users
demisto/content pull request #11677
Opened 2021-03-07 11:15 UTC by abaumgarten

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/34485

## Description
- Fixed an issue where the command **jira-get-id-by-attribute** returned a list of active and inactive users. Now, the new endpoint returns a list of only active users.
The customer's issue probably caused by a long list of inactive users and then the specific active user was not found. 

the new endpoint docs: 
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-user-search/#api-rest-api-3-user-picker-get

## Minimum version of Demisto
- [x] 5.0.0

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-03-07 11:20 UTC, Bargenish approved these changes

2021-03-07 11:20 UTC, Bargenish commented on Packs/Jira/Integrations/JiraV2/JiraV2.py
> +    https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-user-search/#api-rest-api-3-user-picker-get
no need to change. you're still using the user/search endpoint and not the picker one.

2021-03-07 11:32 UTC, amshamah419 commented on Packs/Jira/ReleaseNotes/1_2_13.md
> +- Fixed an issue where the command **jira-get-id-by-attribute** returned a list of active and inactive users. Now, the new endpoint returns a list of only active users.
```suggestion
- Fixed an issue where the **jira-get-id-by-attribute** command would return a list of active and inactive users. Now, the new endpoint returns only a list of active users.
```

2021-03-07 11:47 UTC, yuvalbenshalom requested changes
@abaumgarten see my comment here https://github.com/demisto/etc/issues/34485#issuecomment-792263955

I do not understand what is the difference between the endpoints

2021-03-07 11:50 UTC, abaumgarten commented
> @abaumgarten see my comment here [demisto/etc#34485 (comment)](https://github.com/demisto/etc/issues/34485#issuecomment-792263955)
> 
> I do not understand what is the difference between the endpoints

The old one:
![image](https://user-images.githubusercontent.com/71635916/110238756-06027b00-7f4c-11eb-82e7-6e4e042a663a.png)

The new one:
![image](https://user-images.githubusercontent.com/71635916/110238769-1adf0e80-7f4c-11eb-87f4-e855602e2dcb.png)

Please see my comment in the issue

2021-03-15 09:58 UTC, yuvalbenshalom approved these changes

2021-03-15 10:20 UTC, merged