Logpoint playbook
demisto/content pull request #11729
Opened 2021-03-10 08:07 UTC by Plugins-at-LogPoint

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-10 09:33 UTC, teizenman requested changes

2021-03-10 09:33 UTC, teizenman commented on Packs/LogPoint_SIEM_Integration/ReleaseNotes/1_1_0.md
> +- Added test playbooks' entry in *Test/conf.json*
```suggestion
```

2021-03-10 09:33 UTC, teizenman commented on Packs/LogPoint_SIEM_Integration/ReleaseNotes/1_1_0.md
> +- Updated the Docker image to: *demisto/python3:3.9.2.17246*.
```suggestion
```

2021-03-10 09:52 UTC, Plugins-at-LogPoint commented on Packs/LogPoint_SIEM_Integration/ReleaseNotes/1_1_0.md
> +- Updated the Docker image to: *demisto/python3:3.9.2.17246*.
This change request has been addressed.

2021-03-14 07:19 UTC, teizenman commented
@Plugins-at-LogPoint 
I would like to set up a demo to go through the new playbook.
I have sent an email for the scheduling of it, please respond.

2021-03-19 15:57 UTC, Plugins-at-LogPoint commented
@teizenman,

We have updated the PR with recent changes. The playbook seems to be ready. Please go ahead with the merging process.

Thanks.

2021-03-21 07:41 UTC, teizenman approved these changes

2021-03-21 07:41 UTC, merged