Error msgs in QRadar_v2
demisto/content pull request #11772
Opened 2021-03-11 18:51 UTC by barchen1

## Status
- [x] In Progress
- [ ] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/34627

## Description
Fixed an issue where the integration returned None instead of displaying the error message.
Removed LOG uses from the integration

## Screenshots
<img width="1210" alt="Screen Shot 2021-03-11 at 20 43 41" src="https://user-images.githubusercontent.com/54398957/110838117-c2d93c80-82aa-11eb-9bfd-bc1e26f7f4e8.png">

<img width="1332" alt="Screen Shot 2021-03-11 at 20 41 45" src="https://user-images.githubusercontent.com/54398957/110837923-84dc1880-82aa-11eb-909f-2b00a1409086.png">

## Minimum version of Demisto
- [x] 6.0.0

## Does it break backward compatibility?
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2021-03-12 16:15 UTC, yuvalbenshalom requested changes
looks like this PR is dropping some meaningful logs that may still be needed.
There should be a better way to handle the error without deleting logs.

2021-03-12 17:55 UTC, DeanArbel requested changes
@yuvalbenshalom It's possible to replace this with `print_debug_msg()` with `lock=true`. Do note she just removed the HTTP method + URL log.  I advised @barchen1 to drop the logs, as I feel that given our existing logging and debugging tools, these logs will create a lot of unnecessary clutter in the logs during normal runs.

2021-03-12 17:55 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
>              raise DemistoException("Got unexpected response from QRadar")
```suggestion
            raise DemistoException(f"Got unexpected response from QRadar. Raw response: {res.text}")
```

2021-03-13 10:38 UTC, yuvalbenshalom commented
> @yuvalbenshalom It's possible to replace this with `print_debug_msg()` with `lock=true`. Do note @barchen1 just removed the HTTP method + URL log. I advised @barchen1 to drop the log, as I feel that given our existing logging and debugging tools, this log will create a lot of unnecessary clutter in the logs during normal runs.

Ok so this is fine.

2021-03-14 08:33 UTC, amshamah419 commented on Packs/QRadar/ReleaseNotes/1_2_12.md
> +- Fixed an issue where the integration returned None instead of displaying the error message.
```suggestion
- Fixed an issue where the integration would return None instead of displaying an error message.
```

2021-03-14 10:02 UTC, DeanArbel approved these changes
Nice job :+1:

2021-03-14 10:02 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
> +        error = f"Error has occurred in the QRadar Integration: {str(e)}, \n {traceback.format_exc()}"
```suggestion
        error = f"Error has occurred in the QRadar Integration: {str(e)}\n{traceback.format_exc()}"
```

2021-03-14 11:16 UTC, yuvalbenshalom approved these changes

2021-03-14 11:31 UTC, merged