CortexXDR adding an option to retrieve file without specify the os type
demisto/content pull request #11781
Opened 2021-03-13 19:13 UTC by orhovy

Due to Github issues opening this PR for Orel Haim.
For any Q please reach out to her.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/34265

## Description
Adding an option to retrieve file without specify the os type.

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

@EliorKedar @michalgold FYI.

2021-03-14 07:31 UTC, bakatzir requested changes
Please also test the case where `Error: Endpoint {endpoint_id} was not found`

2021-03-14 07:31 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +    def generate_files_dict_with_specific_os(self, windows: list, linux: list, macos: list):
```suggestion
    def generate_files_dict_with_specific_os(self, windows: list, linux: list, macos: list) -> Dict[str, list] :
```

2021-03-14 07:31 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +        # there are 2 options, either the paths are given with separation to a specific os ire without
```suggestion
        # there are 2 options, either the paths are given with separation to a specific os or without
```

2021-03-14 07:31 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +            endpoint = self.get_endpoints(endpoint_id_list=[endpoint_id])
```suggestion
            endpoints = self.get_endpoints(endpoint_id_list=[endpoint_id])
```

2021-03-14 07:31 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +            endpoint = endpoint[0]
```suggestion
            endpoint = endpoints[0] if isinstance(endpoints, list) else endpoints
```

2021-03-15 10:32 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +        in the list is related to the first endpoint and so on.
an e.g would be great here.

2021-03-15 10:33 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +        in the list is related to the first endpoint and so on.
```suggestion
        in the list is related to the first endpoint and so on, e.g: "C:\Users\demisto\Desktop\CortexXSOAR.txt".
```

2021-03-15 10:34 UTC, bakatzir approved these changes
Looks good. @daryakoval please have a look as well as you've added this functionality recently.

2021-03-15 20:31 UTC, daryakoval approved these changes

2021-03-24 13:15 UTC, merged