UrlScan - add reliability
demisto/content pull request #11804
Opened 2021-03-14 16:09 UTC by yaakovpraisler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: demisto/etc#29347

## Description
Added reliability

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-17 13:14 UTC, JasBeilin commented on Packs/UrlScan/Integrations/UrlScan/UrlScan.py
> +reliability = demisto.params().get('integrationReliability')
Lets move this to main and use params =  demisto.params()

2021-03-17 13:16 UTC, JasBeilin commented
Lets take another look at the tests and see if we can work something out. If not, we will add a picture of the instance with the change.

2021-03-22 14:03 UTC, yaakovpraisler commented
Does not have tests.
![image](https://user-images.githubusercontent.com/59408745/112001407-9e415800-8b27-11eb-8486-35fe8e1c1c54.png)
![image](https://user-images.githubusercontent.com/59408745/112001945-13ad2880-8b28-11eb-9831-58b00d19ec1c.png)

2021-04-01 06:57 UTC, bakatzir requested changes
Please make sure to actually test the reliability in the UT

2021-04-01 06:57 UTC, bakatzir commented on Packs/UrlScan/Integrations/UrlScan/UrlScan.py
> +    def __init__(self, api_key='', threshold=None, use_ssl=False, reliability='C - Fairly reliable'):
please use the enum for reliability

2021-04-01 06:57 UTC, bakatzir commented on Packs/UrlScan/Integrations/UrlScan/UrlScan.py
> +    reliability = params.get('integrationReliability')
```suggestion
    reliability = params.get('integrationReliability', DBotScoreReliability.C)
```

2021-04-01 07:47 UTC, yaakovpraisler commented on Packs/UrlScan/Integrations/UrlScan/UrlScan.py
> +    def __init__(self, api_key='', threshold=None, use_ssl=False, reliability='C - Fairly reliable'):
done.

2021-04-01 07:47 UTC, yaakovpraisler commented on Packs/UrlScan/Integrations/UrlScan/UrlScan.py
> +    reliability = params.get('integrationReliability')
done.

2021-04-01 12:57 UTC, bakatzir approved these changes

2021-04-01 16:49 UTC, merged