Urlhaus add reliability
demisto/content pull request #11810
Opened 2021-03-15 10:42 UTC by yaakovpraisler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: demisto/etc#29347

## Description
Added reliability

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-17 13:22 UTC, JasBeilin commented
Add changes to the readme.
Lets take another look on the testing, if not lets add a picture of the integration's instance with the change.

2021-04-05 06:57 UTC, bakatzir requested changes

2021-04-05 06:57 UTC, bakatzir commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +        }
please separate args from params.

2021-04-05 06:57 UTC, bakatzir commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +            os.environ.pop('https_proxy', None)
you can use `handle_proxy` instead.

2021-04-05 06:57 UTC, bakatzir commented on Packs/URLHaus/Integrations/URLHaus/URLHaus_test.py
> +def test_reliability_in_dbot(mocker):
please use when/given/then

2021-04-05 10:19 UTC, yaakovpraisler commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +        }
done.

2021-04-05 10:19 UTC, yaakovpraisler commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +            os.environ.pop('https_proxy', None)
done.

2021-04-05 10:19 UTC, yaakovpraisler commented on Packs/URLHaus/Integrations/URLHaus/URLHaus_test.py
> +def test_reliability_in_dbot(mocker):
done.

2021-04-05 10:54 UTC, bakatzir approved these changes

2021-04-05 11:28 UTC, merged