Maltiverse - add reliability
demisto/content pull request #11877
Opened 2021-03-21 06:52 UTC by yaakovpraisler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: demisto/etc#29347

## Description
Added reliability

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-25 11:42 UTC, JasBeilin requested changes

2021-03-25 11:42 UTC, JasBeilin commented on Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.py
> +    def __init__(self, url: str, use_ssl: bool, use_proxy: bool, auth_token=None, reliability='C - Fairly reliable'):
```suggestion
    def __init__(self, url: str, use_ssl: bool, use_proxy: bool, auth_token=None, reliability='DBotScoreReliability.C'):
```

2021-03-25 15:57 UTC, JasBeilin commented on Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.py
> +    def __init__(self, url: str, use_ssl: bool, use_proxy: bool, auth_token=None, reliability='DBotScoreReliability.C'):
```suggestion
    def __init__(self, url: str, use_ssl: bool, use_proxy: bool, auth_token=None, reliability=DBotScoreReliability.C):
```

2021-03-29 08:32 UTC, bakatzir approved these changes
Good work.

2021-03-29 08:33 UTC, merged