Microsoft CAS/first commit before unit-test and test with UI
demisto/content pull request #11932
Opened 2021-03-23 21:27 UTC by obenacot

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/33998

## Description
Added the required functionality. 
Not Finshied - 
1. Before major testing in microsoft API
2. code review by Shai.
3. Unit testing.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-13 12:02 UTC, yaakovi requested changes
update the integration README with the new commands and the deprecation of the old commands

2021-05-13 12:02 UTC, yaakovi commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
> +      test or other authorized suspicious action
improve the description

2021-05-13 12:02 UTC, yaakovi commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
> +      description: A custom filter by which to filter the returned files. If you pass
* note that we expect a JSON value here
* add an example

2021-05-13 12:02 UTC, yaakovi commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
> +      - ' Too many similar alerts'
```suggestion
      - Too many similar alerts
```

2021-06-10 09:32 UTC, obenacot commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
> +    Deprecated by args_to_filter_close_alerts.
Function has 4 usages, all by deprecated functions.

2021-06-13 19:45 UTC, closed without merging

2021-06-13 19:46 UTC, obenacot commented
Somehow 697 commits from master (instead of 17) has been inserted to the PR. 
Creating a new PR instead: