Fix the issue with the pack name invalid
demisto/content pull request #11941
Opened 2021-03-24 11:48 UTC by MosheEichler

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/demisto-sdk/pull/1171

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-03-24 12:17 UTC, konraduh commented
Hi. Please undo the change in mnemonicMDR. mnemonic is our brand name. Thank you. 
Please see https://www.mnemonic.no

2021-03-24 12:22 UTC, konraduh requested changes
Revert change from mnemonic to Mnemonic as mnemonic is the correct styling.

2021-03-24 16:02 UTC, reutshal approved these changes

2021-03-31 06:13 UTC, yaakovi approved these changes

2021-04-04 06:57 UTC, merged