Added GitHub-get-file-content command
demisto/content pull request #12138
Opened 2021-04-08 14:23 UTC by teizenman

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
None

## Description
Added GitHub-get-file-content command
Re-created Readme.md

## Minimum version of Demisto
- [X] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

2021-04-08 14:25 UTC, teizenman commented
@ShirleyDenkberg @kirbles19 
I created a new readme file so everything stayed the same except for the new command, so no need to go over everything.

2021-04-10 09:01 UTC, yaakovi requested changes

2021-04-10 09:01 UTC, yaakovi commented on Packs/GitHub/Integrations/GitHub/GitHub.py
> +        readable_output = f'File {file_path} successfully fetched.'
either way, you are creating a War-Room entry, what does it matter?
I expected an option to return the file as a file entry

2021-04-11 08:59 UTC, ShirleyDenkberg commented
@reutshal @yaakovi @teizenman Doc review completed.  No changes to yml or integration readme.  I created a pack readme and sent it to Timor to upload to this PR.

2021-04-12 16:00 UTC, yaakovi approved these changes

2021-04-13 13:53 UTC, merged