Email campaign context key
demisto/content pull request #12258
Opened 2021-04-20 06:31 UTC by ilappe

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-04-20 12:06 UTC, teizenman requested changes

2021-04-20 12:06 UTC, teizenman commented on Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py
> +def test_context_populated_with_required_keys_happy_path(mocker, expected_in_context, not_expected_in_context):
Add the Given-When-Then annotation of docstring

2021-04-20 12:06 UTC, teizenman commented on Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py
> +                assert context_incident[k] is not None and original_incident[k] == context_incident[k]
I don't get these assertions, improve this code to be more readable.

2021-04-21 06:23 UTC, teizenman requested changes

2021-04-21 06:23 UTC, teizenman commented on Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
>              additional_context_fields=fields_to_display))
It should look like:
```
    context = add_context_key(
        create_context_for_campaign_details(
            campaign_found=True,
            incidents_df=incidents_df,
            additional_context_fields=fields_to_display,
        )
    )
```

2021-04-21 06:23 UTC, teizenman commented on Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py
> +            assert field not in context_incident, 'the field "{}" should not be stored in context'.format(field)
You can use the f-string here instead:
https://realpython.com/python-f-strings/

2021-04-25 06:47 UTC, teizenman approved these changes
Change the warning message and you're good to go

2021-04-25 06:47 UTC, teizenman commented on Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
> +                      'settings of the incident field you are trying to search '
```suggestion
                      'settings of the incident field you are trying to search.'
```

2021-05-02 07:08 UTC, teizenman approved these changes

2021-05-10 13:03 UTC, ShirleyDenkberg commented
@teizenman @lperryp Doc review completed.

2021-05-12 09:42 UTC, merged