Xpanse - Adding new VM playbook
demisto/content pull request #12288
Opened 2021-04-20 21:47 UTC by andrew-paloalto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Adding a new playbook that allows for vuln lookups via Tenable.io for IPs/Domains

## Screenshots
N/A

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2021-04-21 13:22 UTC, dantavori requested changes
looks good to me, see my note below and please re-generate the release notes to also include the update in the integration (otherwise it won't pass the validation step in the build).
Let's talk on Slack to schedule a demo.

@EliorKedar FYI

2021-04-21 13:22 UTC, dantavori commented on Packs/ExpanseV2/Playbooks/playbook-Expanse_VM_Enrich_README.md
> +| N - Does not find Vulnerability | Manual VM scan | Initiates a task for the user to kick of a manual VM scan of the identified asset | N/A |
These are not actual playbook inputs and outputs, right? If so, let's describe this content at the description above. 
```suggestion
## Playbook Inputs
---
There are no inputs for this playbook.

## Playbook Outputs
---
There are no outputs for this playbook.
```

2021-04-26 15:51 UTC, EliorKedar approved these changes

2021-04-26 15:57 UTC, dantavori commented
@andrew-paloalto since version 1.3.0 of this pack is already on master you have a conflict, and you need to:
1. Remove the current release notes file from your branch (copy the content for later)
2. Pull from origin/master
3. run `demisto-sdk update-release-notes` again - it will generate the `1_4_0.md` file and will bump the pack version in the metadata to 1.4.0
4. paste the content of your original RN file.

We can merge the PR when this is fixed.

2021-04-26 16:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=12288) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=12288) before we can accept your contribution.<br/>**5** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: andrew-expanse<br/>:white_check_mark: Noy-Maimon<br/>:white_check_mark: andrew-paloalto<br/>:white_check_mark: avidan-H<br/>:white_check_mark: daryakoval<br/>:x: gal-berger<br/>:x: MosheEichler<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=12288) it.</sub>

2021-04-26 16:41 UTC, andrew-expanse commented
Hey @dantavori, the merge from master looks a bit ugly, but the version for ExpanseV2 has been bumped to 1.4.0 and I've added new release notes and bumped the UA header in the integration.

2021-04-27 09:13 UTC, dantavori approved these changes

2021-04-27 09:14 UTC, merged