Enhanced to evaluate values with custom condition expressions.
demisto/content pull request #12303
Opened 2021-04-21 15:26 UTC by spearmin10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Enhanced to evaluate values with custom condition expressions.

The capability has initially been requested as a new script `If-Then-Else-Ex`.
However it has been decided to update it in the pull request (https://github.com/demisto/content/pull/11909), then I've enhanced the current `If-Then-Else`.

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-04-27 11:12 UTC, dantavori commented
@spearmin10 please reach me on Slack (Dan Tavori) to schedule a quick call about your enhancement.

2021-04-27 17:01 UTC, dantavori commented
Had a conversation with @spearmin10 and we decided to keep the current PR with the enhancement. In addition, we decided to add the lhs, op, rhs arguments as implemented in the original PR (https://github.com/demisto/content/pull/11909).

2021-04-28 12:15 UTC, spearmin10 reviewed
Reverted 1_3_36.md

2021-04-29 09:34 UTC, spearmin10 commented
@dantavori Please review the update.

2021-05-05 15:27 UTC, spearmin10 commented
@dantavori I've updated, please review again.

2021-05-09 19:28 UTC, dantavori requested changes
Looks good, we are close to finish. See my small notes, make the last fixes and resolve the conflicts (update the pack version again after you pull from the base branch). We can merge it tomorrow.
Regarding the renaming of `condition` argument, I meant to change it to `op` only if its pre-defined values are the optional operators (and not the whole conditions), but let's keep them the way they are and change it back to `condition`. Sorry for the misunderstanding.

2021-05-09 19:28 UTC, dantavori commented on Packs/CommonScripts/ReleaseNotes/1_3_41.md
> +  - Enhanced to evaluate values with custom condition expressions
```suggestion
  - Enhanced to evaluate values with custom condition expressions.
```

2021-05-10 02:04 UTC, spearmin10 commented on Packs/CommonScripts/Scripts/IfThenElse/IfThenElse.js
> +    }
The check is evaluated one time for a condition and an exception is also raised one time for it.

2021-05-10 02:09 UTC, spearmin10 commented on Packs/CommonScripts/Scripts/IfThenElse/IfThenElse.yml
> +  description: 'Option flags (comma separated list): available options are `case_insensitive`,
Available options are listed in the description as below. Could you let me know what the "valid types" means?

Option flags (comma separated list): available options are `case_insensitive`, `regex_dot_all`, `regex_multiline`, `regex_full_match`, `input_data_type:then=<type>`, `input_data_type:else=<type>`, `input_data_type:lhs=<type>` and `input_data_type:rhs=<type>`.

2021-05-11 08:30 UTC, dantavori commented on Packs/CommonScripts/Scripts/IfThenElse/IfThenElse.yml
> +  description: 'Option flags (comma separated list): available options are `case_insensitive`,
I meant, write in the description of the argument what are the types: json, value or raw.

2021-05-11 10:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=12303) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=12303) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: spearmin10<br/>:white_check_mark: orhovy<br/>:white_check_mark: jochman<br/>:white_check_mark: content-bot<br/>:x: tallieber<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=12303) it.</sub>

2021-05-11 16:15 UTC, roysagi commented on Packs/CommonScripts/ReleaseNotes/1_3_41.md
> -
Please revert this change - we do not delete existing release notes files

2021-05-14 08:36 UTC, spearmin10 commented
@dantavori  @roysagi I've updated the description to your review comments.

2021-05-14 12:48 UTC, dantavori approved these changes

2021-05-14 12:48 UTC, merged