F5 silverline v1 - new integration
demisto/content pull request #12348
Opened 2021-04-25 12:10 UTC by abaumgarten

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/20672

## Description
A new integration - F5 Silverline. 
includes:
3 commands:
1. **f5-silverline-ip-objects-list**
2. **f5-silverline-ip-object-add**
3. **f5-silverline-ip-object-delete**
**test-module**
* TPB
* UTs
* README

Fetch incidents: with Syslog - still in design and development.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-05-25 12:14 UTC, guykeller requested changes

2021-05-25 12:37 UTC, abaumgarten commented on Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
> +def define_body_for_add_ip_command(list_target, mask, ip_address, duration, note, tags):
Done

2021-05-25 12:37 UTC, abaumgarten commented on Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
> +    is_paging = False
Done, changed to `is_paging_required`

2021-05-25 12:37 UTC, abaumgarten commented on Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
> +        is_paging = True
Done

2021-05-25 12:37 UTC, abaumgarten commented on Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
> +                         "get all the IP objects that exist."
Done

2021-05-25 12:39 UTC, abaumgarten commented
@kirbles19 assign you as this is a new integration that requires docs review. thanks!

2021-05-31 10:12 UTC, ShirleyDenkberg commented
@guykeller Doc review completed.

2021-06-13 10:01 UTC, guykeller reviewed
pending paging demo

2021-06-13 11:40 UTC, abaumgarten commented on Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
> +        mask = cidr_range[1]
done

2021-06-13 11:40 UTC, abaumgarten commented on Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
> +    Note: Human readable appears only if the HTTP request did not fail and the object id exists.
An error will be rasied. I added it to the doc string.

2021-06-13 11:40 UTC, abaumgarten commented on Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
> +    if is_object_id_exist(client, object_id, list_type):
I think that there is a misunderstanding here.
The API does not return an error when we try to delete an object whose ID does not exist. So to check so, I first check if the id exists and id yes, delete it. If the ID does not exist, the function `get_ip_objects_by_ids` will raise an error and the delete operation will not happen. 
 I did not understand the question about the number of objects, sorry.

2021-06-13 12:16 UTC, abaumgarten commented
![Uploading image.png…]()

2021-06-14 11:47 UTC, guykeller approved these changes

2021-06-14 11:47 UTC, merged