Qradar long running test module bug
demisto/content pull request #12373
Opened 2021-04-26 13:05 UTC by Noy-Maimon

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/36113

## Description
The test module was failing when the `limit` was `None` and the `longRunning` was `True`, due to the fact that the query in the test module was still sending the word 'limit' in the query yet with no value.

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-04-26 13:08 UTC, DeanArbel requested changes
I'm not sure we want to allow this feature. Please schedule a meeting with me and @David-BMS

2021-04-26 14:30 UTC, Noy-Maimon commented
@roysagi Hi, can you please check the error message in the .py file, the `additionalinfo` field in the .yml file, and the RN file? Thanks :)

2021-04-26 14:41 UTC, DeanArbel approved these changes
Nice, please make sure QRadar v3 handles this case as well.

2021-04-27 07:38 UTC, reutshal approved these changes

2021-04-28 10:23 UTC, roysagi commented on Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
> +                                   ' using the "Max number of events per incident" parameter.')
```suggestion
                                   ' by using the "Max number of events per incident" parameter.')
```

2021-04-29 07:07 UTC, merged