Flash point refactor common indicator and relationships supprort
demisto/content pull request #12384
Opened 2021-04-26 18:22 UTC by orhovy

refactored the IP/Domain/URL/File enrichment commands to use commandResults and Common indicators.
Added support for creating relationships from the 4 enrichment commands.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/35558e

## Description
refactored the IP/Domain/URL/File enrichment commands to use commandResults and Common indicators.
Added support for creating relationships from the 4 enrichment commands.
added context outputs to yml
added context outputs to README file

## Screenshots
Some screen shots from testing:

https://user-images.githubusercontent.com/58938354/116131639-4de48980-a6d5-11eb-8687-8f148b08ae28.mov

<img width="535" alt="Screen Shot 2021-04-26 at 16 09 08" src="https://user-images.githubusercontent.com/58938354/116131693-60f75980-a6d5-11eb-90e3-9f3297d517cc.png">
<img width="545" alt="Screen Shot 2021-04-26 at 20 22 44" src="https://user-images.githubusercontent.com/58938354/116131749-72d8fc80-a6d5-11eb-82a3-c9fb39792f3e.png">

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-04-28 09:31 UTC, yuvalbenshalom requested changes
looks good.
see my comments

2021-04-28 09:31 UTC, yuvalbenshalom commented on Packs/Flashpoint/Integrations/Flashpoint/Flashpoint.yml
>        description: The comment that was provided when the indicator was observed.
please add the checkbox to control relationships creation

2021-04-29 08:40 UTC, orhovy commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +            self._source_reliability = ''
Yes, but we do not want to add by ourserlfs as its a partners integration.
Its not mandatory on server side so there is no problem with that

2021-04-29 10:47 UTC, yuvalbenshalom approved these changes

2021-04-29 14:06 UTC, merged