Sumo Logic Cloud SIEM integration
demisto/content pull request #12383
Opened 2021-04-26 17:37 UTC by matslofva

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Sumo Logic Cloud SIEM integration

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No(?)

## Must have
- [ ] Tests
- [x] Documentation

2021-04-26 17:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=12383) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=12383) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=12383) it.</sub>

2021-04-26 20:12 UTC, marcellarichmond commented
@mchasepan

2021-05-04 00:53 UTC, sangsoojun88 commented on Packs/SumoLogic_Cloud_SIEM/pack_metadata.json
> +    "description": "Cloud SIEM with SOC analytics and automation.",
-> " Sumo Logic Cloud SIEM provides threat detection and incident response for modern IT environments. This content pack will allow you to apply automation to perform actual SOC analyst workflows.  Using this content pack you will be able to fetch Incidents via Insights, update status of an Insight, add items to match list, add Threat Intel Indicators to Threat Intel Sources, and so on."

2021-05-20 11:53 UTC, dantavori requested changes
The script file looks very good, however we have some more stuff to fix - see my notes.
In addition, add a unittest for every command, including fetch incidents - see [Jask UT](https://github1s.com/demisto/content/blob/master/Packs/Jask/Integrations/Jask/Jask_test.py) for reference.
* after you fix the yml file, please regenerate the readme file of the integration (using demisto-sdk generate-docs).

Once we fix these issues we can proceed to a demo.

2021-05-20 16:09 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/SumoLogic_Cloud_SIEM.yml
> +commonfields:
Thanks, that should have been part of my last commit but wasn't for some reason. Updated.

2021-05-20 20:07 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/SumoLogic_Cloud_SIEM.py
> +        return add_to_query(q) + '{}:NOW-24h..NOW'.format(timefield)
Ah predefined values for that arg should have been part of a previous commit to add `output` to the yml... Fixed.

2021-05-20 20:35 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/SumoLogic_Cloud_SIEM.py
> +    insight = insight_signal_to_readable(resp_json['data'])
Correct - when the response status is ok (200) it is guaranteed to have `data` for most endpoints. A search that returns no results will also contain `data`:  `{'data': {'hasNextPage': False, 'objects': [], 'total': 0}, 'errors': []}`. I'll move `.get('data')` into the Client to be safe anyway.

2021-05-20 23:53 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/ReleaseNotes/1_0_0.md
> +#### Integrations
done

2021-05-20 23:53 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/SumoLogic_Cloud_SIEM.py
> +    q = 'timestamp:>{}'.format(latest_created_time)
done

2021-05-20 23:54 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/SumoLogic_Cloud_SIEM.py
> +        message = 'ok'
done

2021-05-20 23:54 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/SumoLogic_Cloud_SIEM.py
> +    insight = insight_signal_to_readable(resp_json['data'])
done

2021-05-20 23:54 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/SumoLogic_Cloud_SIEM.py
> +    insight_id = args.get('insight-id')
done

2021-05-20 23:54 UTC, matslofva commented on Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogic_Cloud_SIEM/README.md
> +| b50fd570-341b-576d-85b5-8b5cd17c0aee | IP Address Scan - Internal | 1.2.3.4 | LEGACY-S00050 | A scan of IP addresses | 3 | Discovery | 2021-04-22T04:08:13.514000 | RULE | _mitreAttackTactic:TA0007,
done

2021-05-25 19:04 UTC, dantavori approved these changes
great work!

2021-05-25 19:04 UTC, merged