AWS API Module
demisto/content pull request #12423
Opened 2021-04-28 13:43 UTC by tallieber

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/32958

## Description
Generic infra for all AWS integrations. Add timeout and retries parameters to integration configuration

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-06 07:01 UTC, bakatzir requested changes
I haven't seen to much of error handling, did you check that?
also, are we adding UT to check that upon giving the wrongs creds / non existent region / etc we are producing a meaningful error?

2021-05-06 07:01 UTC, bakatzir commented on Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
> +    def aws_session(self, service, region=None, role_arn=None, role_session_name=None, role_session_duration=None,
add type annotations.
also - all of theses args override the class props if given? let's add docstrings and explain that.

2021-05-13 13:28 UTC, amshamah419 commented on Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.yml
> +dockerimage: demisto/boto3:2.0.0.19445
Isn't this a python2 image?

2021-05-13 14:15 UTC, bakatzir commented on Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.yml
> +dockerimage: demisto/boto3:2.0.0.19445
yes, as 4/8 integrations are in py2.

2021-05-13 14:17 UTC, bakatzir approved these changes

2021-05-13 14:17 UTC, bakatzir commented on Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
> +                    )
```suggestion
                    client = boto3.client(
                        service_name=service,
                        region_name=region if region else self.aws_default_region,
                        aws_access_key_id=sts_response['Credentials']['AccessKeyId'],
                        aws_secret_access_key=sts_response['Credentials']['SecretAccessKey'],
                        aws_session_token=sts_response['Credentials']['SessionToken'],
                        verify=self.verify_certificate,
                        config=self.config
                    )
```

2021-05-13 14:17 UTC, bakatzir commented on Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
> +                )
```suggestion
                client = boto3.client(
                    service_name=service,
                    region_name=region if region else self.aws_default_region,
                    aws_access_key_id=self.aws_access_key_id,
                    aws_secret_access_key=self.aws_secret_access_key,
                    verify=self.verify_certificate,
                    config=self.config
                )
            else:
                client = boto3.client(
                    service_name=service,
                    region_name=self.aws_default_region,
                    aws_access_key_id=self.aws_access_key_id,
                    aws_secret_access_key=self.aws_secret_access_key,
                    verify=self.verify_certificate,
                    config=self.config
                )
```

2021-05-18 08:06 UTC, merged