[WIP] PolySwarm V2 Update
demisto/content pull request #12424
Opened 2021-04-28 14:36 UTC by JavierBotella

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [ ] Documentation

2021-04-28 15:10 UTC, mchasepan commented
@JavierBotella I thought you said you'd also add the README.md into this PR? Can you please do so?

2021-04-28 15:45 UTC, JavierBotella commented
> @JavierBotella I thought you said you'd also add the README.md into this PR? Can you please do so?

Yes, on it. We have spoken that in Slack already, sorry about it.

It's WIP PR for the devs to review in the meanwhile. 

Thanks you @mchasepan

2021-04-29 13:48 UTC, JavierBotella commented
> @JavierBotella I thought you said you'd also add the README.md into this PR? Can you please do so?

Added! @mchasepan

2021-05-04 12:38 UTC, Noy-Maimon requested changes

2021-05-10 15:37 UTC, JavierBotella commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm.py
> +    def url_reputation(self,
done at https://github.com/demisto/content/pull/12424/commits/f1f2e757a9e6dfe964cebe58ce9cd3a996baaf0d

2021-05-10 15:37 UTC, JavierBotella commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm.py
> +    def file_reputation(self,
done at https://github.com/demisto/content/pull/12424/commits/f1f2e757a9e6dfe964cebe58ce9cd3a996baaf0d

2021-05-18 17:10 UTC, JavierBotella commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm.py
> +    def file_reputation(self,
and this one https://github.com/demisto/content/pull/12424/commits/7321b5af25f0adb707812346a82fa6b520f2f06c

2021-05-18 17:14 UTC, JavierBotella commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm.py
> +        contxt['Artifact'] = artifact
Dbotscore with PolyScore implemented at https://github.com/demisto/content/pull/12424/commits/6e31daa1d0345011bc799aa98bfcc0bbf8d0b144

2021-05-19 12:25 UTC, Noy-Maimon requested changes

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  outputs:
```suggestion
```

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +    - contextPath: PolySwarm.Artifact/
```suggestion
    - contextPath: PolySwarm.Artifact
```

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  display: PolySwarm community
```suggestion
  display: PolySwarm V2
```

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  name: polyswarm_community
```suggestion
  name: Polyswarm V2
```

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +      isArray: false
```suggestion
      isArray: true
```

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +      isArray: false
```suggestion
      isArray: true
```

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +      isArray: false
```suggestion
      isArray: true
```

2021-05-19 12:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +      isArray: false
```suggestion
      isArray: true
```

2021-05-19 16:16 UTC, Noy-Maimon requested changes

2021-05-19 16:16 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  name: PolySwarm_v2 Community
```suggestion
  name: PolySwarm_v2
```

2021-05-20 08:46 UTC, Noy-Maimon approved these changes

2021-05-24 12:51 UTC, Noy-Maimon requested changes

2021-05-24 12:51 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  type: 0
```suggestion
  type: 0
  description: the segment of PolySwarm's marketplace to query on.
```

2021-05-24 12:54 UTC, Noy-Maimon commented
@roysagi Hi, we added a _description.md file to the PR (all of the other filles were already approved). Can you please have a look at it? Thanks

2021-05-24 13:43 UTC, Noy-Maimon requested changes

2021-05-24 13:43 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  display: PolySwarm_v2 Community
```suggestion
  display: PolySwarm v2 Community
```

2021-05-24 13:43 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  display: PolySwarm_v2 Community
This is needed for passing our validations before merging

2021-05-24 14:25 UTC, Noy-Maimon requested changes

2021-05-24 14:25 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2_test.py
> +from PolySwarm import PolyswarmConnector
```suggestion
from PolySwarm_v2 import PolyswarmConnector
```

2021-05-24 15:12 UTC, Noy-Maimon requested changes

2021-05-24 15:12 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.py
> +        elif float(polyscore) >= 0.7:
```suggestion
        else:  # polyscore is >= 0.7
```

2021-05-24 15:12 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.py
> +            indicator=indicator,
```suggestion
            indicator=indicator, # type: ignore
```

2021-05-24 15:12 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.py
> +                            results: dict,
```suggestion
                            results: list,
```

2021-05-24 15:12 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.py
> +                                       dbot_score=dbot_score)
```suggestion
                                       dbot_score=dbot_score)  # type: ignore
```

2021-05-24 15:12 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.py
> +                                          dbot_score=dbot_score)
```suggestion
                                          dbot_score=dbot_score)  # type: ignore
```

2021-05-24 15:33 UTC, Noy-Maimon requested changes

2021-05-24 15:33 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.py
> +            indicator=indicator, # type: ignore
```suggestion
            indicator=indicator,  # type: ignore
```

2021-05-24 16:12 UTC, Noy-Maimon requested changes

2021-05-24 16:12 UTC, Noy-Maimon commented on Packs/PolySwarm/Integrations/PolySwarm_v2/PolySwarm_v2.yml
> +  description: the segment of PolySwarm's marketplace to query on.
```suggestion
  additionalinfo: the segment of PolySwarm's marketplace to query on.
```

2021-05-25 09:48 UTC, Noy-Maimon commented
@amshamah419  Hi, we added a _description.md file to the PR (all of the other filles were already approved). Can you please have a look at it? Thanks

2021-05-25 14:32 UTC, Noy-Maimon approved these changes

2021-05-25 14:32 UTC, merged