HPE Aruba clearpass v1
demisto/content pull request #12540
Opened 2021-05-04 15:36 UTC by abaumgarten

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/6683

## Description
A new integration - HPE Arube Clearpass
includes:
8 commands:

1. **aruba-clearpass-endpoints-list**
2. **aruba-clearpass-endpoint-update**
3. **aruba-clearpass-attributes-list**
4. **aruba-clearpass-attribute-create**
5. **aruba-clearpass-attribute-update**
6. **aruba-clearpass-attribute-delete**
7. **aruba-clearpass-active-sessions-list**
8. **aruba-clearpass-active-session-disconnect**
test-module
TPB
UTs
README

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-05-06 15:48 UTC, guykeller requested changes
Let's do the self CR we discussed

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +        outputs_prefix='HPEArubaClearpass.endpoints.list',
why `.list`?
same everywhere else

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +def endpoints_response_to_dict(response: dict) -> dict:
but it is already a dict

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +    request_body.update({"attributes": attributes_values}) if attributes else None
as discussed

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +    mandatory = args.get('mandatory', False)
 Is it a string or a boolean?
Same goes for other places

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +        outputs_prefix='HPEArubaClearpass.sessions.disconnect',
Why under disconnect? Shouldn't we just update the sessions path that the session has disconnected?

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass_test.py
> +def test_get_endpoints_list_command(mocker):
General note - I'm more interested in testing Pythonic logic than the commands. Testing helper methods is more indicative and helpful IMO

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/README.md
> +This README contains the full documentation for your integration.
let's update this, and add command examples too

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/pack_metadata.json
> +    "description": "change it",
change it indeed

2021-05-06 15:48 UTC, guykeller commented on Packs/HPEArubaClearpass/pack_metadata.json
> +    "keywords": []
let's add

2021-05-12 10:47 UTC, guykeller approved these changes
last few notes.
Also, let's schedule a demo with Anar, Guy and Yuval before merging

2021-05-12 10:47 UTC, guykeller commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +                del item['_links']  # useless information, won't be displayed
we have a function for that, don't we?

2021-05-12 11:50 UTC, abaumgarten commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +def delete_redundant_data(res: Dict[str, Any]):
Added

2021-05-12 11:50 UTC, abaumgarten commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +        pass
Done

2021-05-12 11:50 UTC, abaumgarten commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +                del item['_links']  # useless information, won't be displayed
You right, done.

2021-05-12 11:50 UTC, abaumgarten commented on Packs/HPEArubaClearpass/Integrations/HPEArubaClearpass/HPEArubaClearpass.py
> +    1. allowed_value is available only when data_type is List.
The api docs are private (need user and password). I added the suffix of the link.

2021-05-12 12:17 UTC, abaumgarten commented
@kirbles19 assign you as this is a new integration that requires docs review. thanks!

2021-05-13 12:43 UTC, ShirleyDenkberg commented
@guykeller Doc review completed.

2021-05-19 14:55 UTC, guykeller approved these changes
Pending customer verification

2021-06-10 09:09 UTC, merged