Jamf v2
demisto/content pull request #12739
Opened 2021-05-18 15:52 UTC by barchen1

## Status
- [x] In Progress
- [] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/36155

## Description
Jamf v2 integration
includes: 10 commands:

1. **jamf-computers-get**
2. **jamf-get-computer-subset**
3. **jamf-computer-lock**
4. **jamf-computer-erase**
5. **jamf-get-users**
6. **jamf-get-mobile-devices**
7. **jamf-get-mobile-device-subset**
8. **jamf-get-computers-by-application**
9. **jamf-mobile-device-lost-mode**
10. **jamf-mobile-device-erase**
test-module
TPB
UTs
README

note:
The following commands were not tested (as we don't data for it):
 **jamf-mobile-device-lost-mode**
 **jamf-mobile-device-erase**

## Minimum version of Cortex XSOAR
- [x] 5.5.0

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-05-23 16:22 UTC, guykeller requested changes

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +    return response[page * limit:(page + 1) * limit]
This should be split into several variables with readable names, it's too complex and bug-prone

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +        limit = MAX_PAGE_SIZE
let's make this a one line if

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +            devices_sizes.append({device.get('disk'): device.get('size')})
can you explain this logic?

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +        mobile_dev_response = response.get('mobile_device').get('general')
What does `mobile_dev_response` stand for?

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +            'Sum of computers': computers_len
The word `sum` does not fit here IMO.
Perhaps `Total computers` or something like that

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +        computers_len = len(version.get('computers'))
IMO the word `len` should not be in this name

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +        if client.get_computers_request():
Don't we want to check that something returns?

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +    if not user_id and not name and not email:
You can use `any()`

2021-05-23 16:22 UTC, guykeller commented on Packs/jamf/Integrations/jamf_v2/jamf_v2.py
> +def pagination(response, limit, page):
Out of all the functions, in my opinion this one deserves a docstring the most.
In general, helper functions need docstrings more than command functions do

2021-05-23 16:26 UTC, guykeller commented
Great job!!

Some general notes:
1. Some of my notes apply generally to all the code - try to implement them everywhere
2. Naming, descriptions, etc are important IMO, let's give them special attention
3. The builds seem to be failing

2021-05-25 04:36 UTC, tomer-pan commented on Packs/jamf/Integrations/jamf_v2/README.md
> +This integration was integrated and tested with version 10.28.0-t1615386406 of jamf v2
@barchen1 I think we can change it to:
`This integration was integrated and tested with version 10.28.0 of Jamf Pro`

2021-05-25 04:38 UTC, tomer-pan commented on Packs/jamf/Integrations/jamf_v2/jamf_v2_description.md
> +The login password of the above username
Nothing else is needed.

2021-05-25 14:15 UTC, guykeller commented on Packs/jamf/Integrations/integration-jamf.yml
> +description: Deprecated. Use Jamf v2 instead. Jamf device management. Please note, this integration is currently only compatible with the Jamf V1 API.
Yes

2021-06-13 08:14 UTC, guykeller approved these changes
Do one final swipe on readability. Overall looks good

2021-06-13 08:14 UTC, guykeller commented on Packs/jamf/Integrations/jamfV2/jamfV2.py
> +def paging_outputs_dict(total_results, page_size, current_page):
This function's name could be improved in my opinion

2021-06-13 08:14 UTC, guykeller commented on Packs/jamf/Integrations/jamfV2/jamfV2.py
> +    """
Let's add a 1-2 lines explanation for what's going on here

2021-06-13 09:14 UTC, barchen1 commented
@ShirleyDenkberg Can you please review the PR docs ?

2021-06-20 08:05 UTC, ShirleyDenkberg commented
@tomer-pan @guykeller Doc review completed.  @barchen1 Integration README needs to be regenerated.

2021-07-20 13:28 UTC, guykeller approved these changes

2021-07-20 14:45 UTC, merged