Bug/VMRay/Fixed: viewing all threat-indicators for a sampleID instead…
demisto/content pull request #12733
Opened 2021-05-18 13:54 UTC by obenacot

… of viewing the first one.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-23 06:58 UTC, yaakovi requested changes
* update the PR's description
* update release notes

2021-05-25 16:39 UTC, obenacot commented
Closed due to PR Duplicaty

2021-06-03 03:41 UTC, yaakovi reviewed
fill in the PR description

2021-06-03 03:41 UTC, yaakovi commented on Packs/VMRay/Integrations/VMRay/VMRay.py
> +            headers=['AnalysisID', 'Category', 'Classification', 'ID', 'Operation'],
```suggestion
            headers=['ID', 'AnalysisID', 'Category', 'Classification', 'Operation'],
```

2021-06-03 03:41 UTC, yaakovi commented on Packs/VMRay/ReleaseNotes/1_0_2.md
> +- Enable mocking
```suggestion
- Fixed an issue where only the first indicator was shown in the War-Room entry for the ***vmray-get-threat-indicators*** command. 
```

2021-06-03 07:46 UTC, amshamah419 commented on Packs/VMRay/ReleaseNotes/1_0_2.md
> +- Enable mocking
👍

2021-06-05 20:58 UTC, yaakovi approved these changes

2021-06-05 20:58 UTC, merged