RF Feed bug
demisto/content pull request #12736
Opened 2021-05-18 15:01 UTC by ChanochShayner

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/37032

## Description
Because we read the file in batches to not overload the docker, only on the first reading of the CSV file we have the headers of the file, so we did a fetch each time only on the first 2000.
fixed.

## Screenshots
![image](https://user-images.githubusercontent.com/57212002/118675059-fbdde200-b802-11eb-8606-4a3ed759e046.png)
![image](https://user-images.githubusercontent.com/57212002/118675181-10ba7580-b803-11eb-8ffc-bda598388441.png)

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-20 09:29 UTC, guykeller requested changes

2021-05-20 09:29 UTC, guykeller commented on Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
> +            yield csv.DictReader(feed_batch, fieldnames=["Name", "Risk", "RiskString", "EvidenceDetails"])
as discussed

2021-05-20 12:48 UTC, ChanochShayner commented on Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
> +            yield csv.DictReader(feed_batch, fieldnames=["Name", "Risk", "RiskString", "EvidenceDetails"])
done

2021-05-23 08:27 UTC, reutshal approved these changes

2021-05-23 09:05 UTC, amshamah419 commented on Packs/FeedRecordedFuture/ReleaseNotes/1_0_9.md
> +- Fixed an issue where fetch indicators command does not fetch all the indicators.
```suggestion
- Fixed an issue where the ***fetch-indicators*** command would not fetch all the indicators.
```

2021-05-23 09:56 UTC, guykeller approved these changes

2021-05-23 10:15 UTC, merged