Splunk notable
demisto/content pull request #12760
Opened 2021-05-19 21:41 UTC by David-BMS

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30035

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-19 21:43 UTC, David-BMS commented
@kirbles19 Please assist as this has to be merged ASAP

2021-05-23 06:59 UTC, guyfreund requested changes
Nice 👏 , few notes:
- Remove the `Packs/CommonTypes/ReleaseNotes/2_9_4.md` file
- Remove the `Packs/SplunkPy/Scripts/SplunkShowDrilldown/README.md` file
- Remove the `Packs/SplunkPy/Scripts/SplunkShowAsset/README.md` file
- Remove the `Packs/SplunkPy/Scripts/SplunkShowIdentity/README.md` file
- Please run sdk format on all files in this PR

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Classifiers/classifier-Splunk_-_Notable_Generic_Incoming_Mapper.json
> +    "id": "2f7f9005-b1c2-43c3-8bcd-defbe69ec048",
```suggestion
    "id": "Splunk - Notable Generic Incoming Mapper",
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Classifiers/classifier-Splunk_-_Notable_Generic_Outgoing_Mapper.json
> +    "id": "561b72e1-68b3-426f-89b2-7555afecf1d2",
```suggestion
    "id": "Splunk - Notable Generic Outgoing Mapper",
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/ReleaseNotes/2_1_0.md
> +- **Notable - ID**
all successful fields should be gathered together

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            drilldown_results_str = custom_fields.get('assettable', {})
```suggestion
            asset_results_str = custom_fields.get('assettable', {})
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +        # print(events)
```suggestion
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            drilldown_results = json.loads(drilldown_results_str)
```suggestion
            asset_results = json.loads(drilldown_results_str)
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +        # print(events)
```suggestion
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +    trace = ''
```suggestion
```
Please remove all handling of the trace var.

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +    trace = ''
```suggestion
```
Please remove all handling of the trace var.

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +        pass
```suggestion
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +        pass
```suggestion
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +    trace = ''
```suggestion
```
Please remove all handling of the trace var.

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +        # print(events)
```suggestion
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            drilldown_results_str = custom_fields.get('identitytable', {})
```suggestion
            identity_results_str = custom_fields.get('identitytable', {})
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            drilldown_results = json.loads(drilldown_results_str)
```suggestion
            identity_results = json.loads(drilldown_results_str)
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +        pass
```suggestion
```

2021-05-23 06:59 UTC, guyfreund commented on Packs/SplunkPy/pack_metadata.json
> +        "display_name": "Identity"
Please fix indentation

2021-05-23 08:57 UTC, guyfreund requested changes

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +        trace += '1'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +        if not drilldown_results:
```suggestion
        if not asset_results:
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            trace += '2'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +        if isinstance(drilldown_results, list):
```suggestion
        if isinstance(asset_results, list):
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            for event in drilldown_results:
```suggestion
            for event in asset_results:
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            trace += '3'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +                    trace += '4'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +                    trace += '5'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            trace += '6'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            trace += '7'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +            markdown = tableToMarkdown("", drilldown_results)
```suggestion
            markdown = tableToMarkdown("", asset_results)
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
> +        trace += '9'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +        trace += '1'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +            trace += '2'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +            trace += '3'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +                    trace += '4'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +                    trace += '5'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +            trace += '6'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +            trace += '7'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +        trace += '9'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +        if not drilldown_results:
```suggestion
        if not identity_results:
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +        if isinstance(drilldown_results, list):
```suggestion
        if isinstance(identity_results, list):
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            for event in drilldown_results:
```suggestion
            for event in identity_results:
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            markdown = tableToMarkdown("", drilldown_results)
```suggestion
            markdown = tableToMarkdown("", identity_results)
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +        trace += '1'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            trace += '2'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            trace += '3'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +                    trace += '4'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +                    trace += '5'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            trace += '6'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +            trace += '7'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
> +        trace += '9'
```suggestion
```

2021-05-23 08:57 UTC, guyfreund commented on Packs/SplunkPy/pack_metadata.json
> +
Please fix the indentation of the identity pack

2021-05-23 09:00 UTC, guyfreund requested changes
Regarding https://app.circleci.com/pipelines/github/demisto/content/87459/workflows/cc5dd501-18ec-4dfb-8c08-2b86112920e0/jobs/361854

Whenever `return_error` is used please raise an exception and wrap the main with `try-except` block and then use `return_error`

2021-05-23 10:44 UTC, guyfreund requested changes
The 3 `Show` scripts are a duplicate of code.
We can have just one script `SplunkShowResults` which will get as an argument the key in context to be queried (notabledrilldown, assettable or identitytable).

2021-05-23 12:51 UTC, David-BMS commented
@michalgold Please review its ready for merge

2021-05-23 14:50 UTC, David-BMS commented
> The 3 `Show` scripts are a duplicate of code.
> We can have just one script `SplunkShowResults` which will get as an argument the key in context to be queried (notabledrilldown, assettable or identitytable).

Added as enhancement here
https://github.com/demisto/etc/issues/37197

Right now will be merged as is

2021-05-23 15:30 UTC, michalgold commented on Packs/SplunkPy/Layouts/layoutscontainer-Splunk_Notable_Generic.json
> +                        "description": "‘True’ indicates enrichment was successful, even if there were no results found.",
‘True’ indicates enrichment was successful, even if there were no results found. 
See Assets, Identities and Drilldown tabs for details.

2021-05-23 15:32 UTC, michalgold commented on Packs/CommonTypes/IncidentFields/incidentfield-Occurred_Time.json
> +    "cliName": "occurredtime",
why create new field and not use "Occurred"?

2021-05-23 17:54 UTC, michalgold approved these changes

2021-05-24 07:08 UTC, guyfreund submitted a review, later dismissed

2021-05-24 18:51 UTC, merged