Google Chronicle Backstory Enhancement
demisto/content pull request #12845
Opened 2021-05-25 12:37 UTC by crestdatasystems

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added simple_backoff_rules dictionary to track retry attempts for 429 and 500 error and if 400 or 404 error occurs for detection of any rule , it will be skipped. Added 'gcb-list-rules' command.

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-05-25 14:32 UTC, adi88d commented
@crestdatasystems please register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA) before we proceed with the review.

2021-05-30 08:15 UTC, adi88d commented
@crestdatasystems please register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA) before we proceed with the review.

2021-06-09 16:57 UTC, crestdatasystems commented
@adi88d Let us know if there are any changes that need to be done.

2021-06-10 13:21 UTC, adi88d commented on Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_1.md
> +- Added simple_backoff_rules dictionary to track retry attempts for 429 and 500 error and if 400 or 404 error occurs for detection of any rule , it will be skipped. Added 'gcb-list-rules' command.
```suggestion
- Added simple_backoff_rules dictionary to track retry attempts for 429 and 500 error and if 400 or 404 error occurs for detection of any rule.
- Added the ***gcb-list-rules*** command.
```

2021-06-10 13:23 UTC, adi88d commented on Packs/GoogleChronicleBackstory/ReleaseNotes/2_0_1.md
> +- Updated the Docker image to demisto/python3:3.9.1.15759.
```suggestion
- Updated the Docker image to demisto/python3:3.9.5.20070.
```

please change this for all the scripts you updated the docker

2021-06-14 13:21 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/IncidentFields/incidentfield-Chronicle_Rule_Name.json
> +    "useAsKpi": true,
@adi88d  This was a new request from the client, this change enables graphing functionality.

2021-06-14 13:29 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
> +BACKSTORY_API_V2_URL = 'https://{}backstory.googleapis.com/v2'
@adi88d we only created a global variable

2021-06-14 13:34 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
> +                if attempts < 60:
@adi88d We're retrying an API call for 429 and 500 HTTP status errors. In attempts would get increment in each fetch-incident execution, which is 1min. The number of attempts as 60 was decided by us and the customer.

2021-06-14 13:42 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
>  def get_max_fetch_detections(client_obj, start_time, end_time, max_fetch, detection_incidents, detection_to_pull,
@adi88d we can add an explanation for this method and while statement method.

2021-06-15 12:44 UTC, adi88d commented on Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
> +        }
When you updated this block you break the indent of the code -please fix that

2021-06-15 12:49 UTC, adi88d commented on Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
> +                if attempts < 60:
Please use a global variable for the attempts number

2021-06-15 12:49 UTC, adi88d commented on Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
>  def get_max_fetch_detections(client_obj, start_time, end_time, max_fetch, detection_incidents, detection_to_pull,
@crestdatasystems Please do

2021-06-15 12:56 UTC, adi88d requested changes
@crestdatasystems
Please fix the code indent in your python file and make sure the test are passed successfully
and update the docker images for the scripts to `3.9.5.21272` don't forget to update the release notes after.

2021-06-16 04:17 UTC, crestdatasystems commented
@adi88d we're done with the changes you suggested.

2021-06-17 07:03 UTC, adi88d requested changes
@crestdatasystems We want to schedule a demo for your contribution, please share with us your availability for the next week,
Thanks

2021-06-17 11:53 UTC, crestdatasystems commented on Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py
> +    live_rule = args.get('live_rule', '').lower()
@adi88d argToBoolean raises a Value Error if the argument is null or empty as **live_rule** is not a required argument.
So we decided to continue with the existing logic only

2021-06-21 11:09 UTC, crestdatasystems commented
@adi88d Recorded Demo 

https://user-images.githubusercontent.com/60967033/122752988-3a0d6c00-d2af-11eb-8c98-3f62ba2cdf41.mp4

2021-06-23 13:24 UTC, merged