summary and indicator - canvas is still not working
demisto/content pull request #12875
Opened 2021-05-26 16:22 UTC by iyeshaya

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/36991

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-27 12:12 UTC, roysagi approved these changes
Looks good - please see my comment below

2021-05-27 12:12 UTC, roysagi commented on Packs/CommonTypes/IncidentFields/incidentfield-EmailCampaignCanvas.json
> +    "fromVersion": "5.5.0"
Let's make sure with @idovandijk on which version these additions are made.

2021-05-27 12:18 UTC, idovandijk commented on Packs/CommonTypes/IncidentFields/incidentfield-EmailCampaignCanvas.json
> +    "fromVersion": "5.5.0"
6.0.0

2021-05-27 12:19 UTC, idovandijk requested changes
Please let me see the final result before merging

2021-05-30 15:52 UTC, idovandijk approved these changes
Itay changed the way summary is displayed, looks great. Also tested on the server and works fine

2021-05-30 18:50 UTC, merged