Replace demisto to Cortex XSOAR
demisto/content pull request #12882
Opened 2021-05-27 08:12 UTC by yaakovpraisler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Replace demisto to Cortex XSOAR

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-28 07:59 UTC, yaakovi commented on Packs/Malwarebytes/Integrations/Malwarebytes/README.md
> +2.	 Create a Cortex XSOAR incident upon Malwarebytes Suspicious Acitivty detections.
```suggestion
2.	Create a Cortex XSOAR incident upon a Malwarebytes Suspicious Activity detections.
```

2021-05-28 07:59 UTC, yaakovi commented on Packs/MongoDB/.pack-ignore
> +https://docs.mongodb.com
should this be in the `.secret-ignore` file? please remove from here

2021-05-28 07:59 UTC, yaakovi commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_15.md
> +- Updated the Docker image to: *demisto/crypto:1.0.0.19032*.
???

2021-05-28 10:14 UTC, yaakovpraisler commented on Packs/Malwarebytes/Integrations/Malwarebytes/README.md
> +2.	 Create a Cortex XSOAR incident upon Malwarebytes Suspicious Acitivty detections.
done

2021-05-28 10:14 UTC, yaakovpraisler commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_15.md
> +- Updated the Docker image to: *demisto/crypto:1.0.0.19032*.
done

2021-05-30 14:47 UTC, roysagi requested changes

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which should be inserted in the integration instance configuration's corresponding fields.
revert this

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which needs to be added to the integration instance configuration's corresponding fields.
revert these changes

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which should be inserted in the integration instance configuration's corresponding fields.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_description.md
> +After authorizing the Cortex XSOAR app, you receive an ID, Token, and Key, all of which need to be entered to the corresponding fields when configuring the integration instance.
revert these changes

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which needs to be added to the integration instance configuration's corresponding fields.
revert these changes

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which should be inserted in the integration instance configuration's corresponding fields.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which should be inserted in the integration instance configuration's corresponding fields.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which should be inserted in the integration instance configuration's corresponding fields.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +### Create the Cortex XSOAR Bot in Microsoft Teams
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +  - **Short name**: Cortex XSOAR Bot
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +  - **Long description**: Cortex XSOAR Bot is the mechanism that enables messaging team members and channels, executing Cortex XSOAR commands directly from Teams, and mirroring investigation data bet
```suggestion
  - **Long description**: Demisto Bot is the mechanism that enables messaging team members and channels, executing Cortex XSOAR commands directly from Teams, and mirroring investigation data between Cortex XSOAR and Microsoft Teams
```

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +  - In the **Name** field, enter *Cortex XSOAR Bot*.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +13. In the **Messaging endpoints** section, enter the URL to which messages will be sent (to the Cortex XSOAR Bot).
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +### Grant the Cortex XSOAR Bot Permissions in Microsoft Graph
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +2. Search for and click **Cortex XSOAR Bot**.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +5. Verify that all permissions were added, and click **Grant admin consent for Cortex XSOAR**.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +### Add the Cortex XSOAR Bot to a Team
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +2. Search for **Cortex XSOAR Bot** and click the Cortex XSOAR Bot widget.
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +| direction | The mirroring direction. Can be "FromXSOAR", "ToXSOAR", or "Both". | Optional |
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +For example, in order to check the reputation of the IP address 8.8.8.8, run the following: `@XSOAR Bot !ip ip=8.8.8.8`
revert this change

2021-05-30 14:47 UTC, roysagi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +## Download Cortex XSOAR Bot
revert this change

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which should be inserted in the integration instance configuration's corresponding fields.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which needs to be added to the integration instance configuration's corresponding fields.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_description.md
> +After authorizing the Cortex XSOAR app, you receive an ID, Token, and Key, all of which need to be entered to the corresponding fields when configuring the integration instance.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which needs to be added to the integration instance configuration's corresponding fields.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_description.md
> +After authorizing the Cortex XSOAR app, you will get an ID, Token, and Key, which should be inserted in the integration instance configuration's corresponding fields.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +## Download Cortex XSOAR Bot
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +For example, in order to check the reputation of the IP address 8.8.8.8, run the following: `@XSOAR Bot !ip ip=8.8.8.8`
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +| direction | The mirroring direction. Can be "FromXSOAR", "ToXSOAR", or "Both". | Optional |
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +2. Search for **Cortex XSOAR Bot** and click the Cortex XSOAR Bot widget.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +### Add the Cortex XSOAR Bot to a Team
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +5. Verify that all permissions were added, and click **Grant admin consent for Cortex XSOAR**.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +2. Search for and click **Cortex XSOAR Bot**.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +### Grant the Cortex XSOAR Bot Permissions in Microsoft Graph
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +13. In the **Messaging endpoints** section, enter the URL to which messages will be sent (to the Cortex XSOAR Bot).
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +  - In the **Name** field, enter *Cortex XSOAR Bot*.
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +  - **Long description**: Cortex XSOAR Bot is the mechanism that enables messaging team members and channels, executing Cortex XSOAR commands directly from Teams, and mirroring investigation data bet
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +  - **Short name**: Cortex XSOAR Bot
done.

2021-05-30 17:50 UTC, yaakovpraisler commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +### Create the Cortex XSOAR Bot in Microsoft Teams
done.

2021-05-31 15:01 UTC, roysagi approved these changes

2021-05-31 19:44 UTC, merged