test
demisto/content pull request #12920
Opened 2021-05-30 10:52 UTC by Shellyber

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-05-31 14:42 UTC, Shellyber commented
https://console.cloud.google.com/storage/browser/marketplace-ci-build/content/builds/compress-files/211d65e9-1c42-4d3d-a1f0-5f29a70cb353/content;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=core&forceOnObjectsSortingFiltering=false

Example for the latest run.
See the index.json, corepacks.json and id_set.json.
The file size is lowered significantly.

2021-06-01 08:00 UTC, guyfreund requested changes
Very Nice Work! 👏

2021-06-01 08:06 UTC, Shellyber commented on Tests/Marketplace/upload_packs.py
> -
I'll to it after handling the private. If I'll do it know, private will fail

2021-06-01 14:48 UTC, Shellyber commented on Tests/Marketplace/upload_packs.py
> +        json.dump(core_packs_data, corepacks_file, indent=4)
Reverted this change since the `json_write` uses json.dumps and not dump

2021-06-02 14:18 UTC, Shellyber commented
@guyfreund Please review.
Last upload test run: https://console.cloud.google.com/storage/browser/marketplace-ci-build/content/builds/compress-files/43e3a76a-79f2-4115-8d02-1b15a572d36a/content?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

2021-06-02 14:49 UTC, guyfreund reviewed
please attach the build run

2021-06-03 07:11 UTC, Shellyber commented
@guyfreund Latest build run: https://app.circleci.com/pipelines/github/demisto/content/90447/workflows/43e3a76a-79f2-4115-8d02-1b15a572d36a

2021-06-06 11:21 UTC, Shellyber commented
This is the private commit bucket - https://console.cloud.google.com/storage/browser/marketplace-ci-build-private/content/builds/compress-private-files/3994/content?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

See the size of the id_set.

2021-06-06 11:21 UTC, Shellyber commented
@guykeller FYI
Removed the `upload_id_set` command. We are now using `gsutil` to compress the size.

2021-06-06 13:59 UTC, guyfreund approved these changes
🥇

2021-06-06 14:21 UTC, merged