Carbon black rewrite
demisto/content pull request #12967
Opened 2021-06-01 13:36 UTC by MosheEichler

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28188

## Description
Added in the readme file some differences between v1 & v2  of the carbon black endpoint standard integration

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-06 08:24 UTC, reutshal requested changes

2021-06-06 08:24 UTC, reutshal commented on Packs/CarbonBlackDefense/Integrations/CarbonBlackEndpointStandard/README.md
> +* Layout.
```suggestion
An incident type, classifier and mapper were added.
```

2021-06-06 08:24 UTC, reutshal commented on Packs/CarbonBlackDefense/ReleaseNotes/2_0_1.md
> +##### Carbon Black Endpoint Standard v2
Revert this change, no need to change old RN

2021-06-06 08:24 UTC, reutshal commented on Packs/CarbonBlackDefense/ReleaseNotes/2_0_2.md
> +- Added the differences between the two versions in the README file.
```suggestion
- Maintenance and stability enhancements.
```

2021-06-06 08:26 UTC, reutshal commented
@ShirleyDenkberg Can you please review the changes added to the README file? 
Thanks 🙏

2021-06-06 12:11 UTC, yaakovi commented on Packs/CarbonBlackDefense/Integrations/CarbonBlackEndpointStandard/README.md
> +The new integration supports new commands:
is there a difference in the old commands? did we change inputs/outputs?
did we stop supporting specific commands (if so, why?)

2021-06-13 10:16 UTC, ShirleyDenkberg commented
@yaakovi @reutshal I edited the README file as we discussed.

2021-06-15 10:15 UTC, reutshal approved these changes

2021-06-15 10:20 UTC, merged