Trend Micro Deep Security Integration
demisto/content pull request #13018
Opened 2021-06-03 20:41 UTC by RazOmry

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Trend Micro Deep Security is a system that provides a runtime security solution for endpoints and workloads in the cloud.

The Deep Security API enables you to automate operational tasks, thereby increasing the productivity of your value stream and improving the security services that you support:
- Configure policies and protect computers.
- Discover vulnerabilities and patch them.
- Perform routine maintenance tasks.
- And more!

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-06-20 14:56 UTC, Noy-Maimon requested changes
Thank you for your contribution! 
I requested a few minor changes to match our conventions, please have a look.

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +        return self._http_request(method="GET", url_suffix="/computers", params=params)["computers"]
```suggestion
        return self._http_request(method="GET", url_suffix="/computers", params=params).get("computers")
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +                                  params={"overrides": overrides})["assignedRuleIDs"]
```suggestion
                                  params={"overrides": overrides}).get("assignedRuleIDs")
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +                                  params={"overrides": overrides}, json_data={"rule_ids": rule_ids})["assignedRuleIDs"]
```suggestion
                                  params={"overrides": overrides}, json_data={"rule_ids": rule_ids}).get("assignedRuleIDs")
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +        return self._http_request(method="GET", url_suffix="/computergroups")["computerGroups"]
```suggestion
        return self._http_request(method="GET", url_suffix="/computergroups").get("computerGroups")
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +        return self._http_request(method="GET", url_suffix="/firewallrules")["firewallRules"]
```suggestion
        return self._http_request(method="GET", url_suffix="/firewallrules").get("firewallRules")
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +    markdown = tableToMarkdown(f"Details for the new computer {response['hostName']}", response, removeNull=True,
```suggestion
    markdown = tableToMarkdown(f"Details for the new computer {response.get('hostName')}", response, removeNull=True,
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +    markdown = tableToMarkdown(f"Details for the computer {response['hostName']}", response, removeNull=True,
```suggestion
    markdown = tableToMarkdown(f"Details for the computer {response.get('hostName')}", response, removeNull=True,
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +    markdown = tableToMarkdown(f"Details for the computer {response['hostName']}", response, removeNull=True,
```suggestion
    markdown = tableToMarkdown(f"Details for the computer {response.get('hostName')}", response, removeNull=True,
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +    response = {k: v["value"] for k, v in client.list_default_policy_settings().items()}
```suggestion
    response = {k: v.get("value") for k, v in client.list_default_policy_settings().items()}
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +    client = Client(params["server_url"], params["api_secret"], use_ssl, use_proxy)
```suggestion
    client = Client(params.get("server_url"), params("api_secret"), use_ssl, use_proxy)
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +            command_function = commands[command]
```suggestion
            command_function = commands.get(command)
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +        error_message = f"Error in API call [{e.response.status_code}]\n{e.response.json()['message']}"
```suggestion
        error_message = f"Error in API call [{e.response.status_code}]\n{e.response.json().get('message')}"
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.yml
> +fromversion: 5.0.0
```suggestion
fromversion: 6.0.0
```

2021-06-20 14:56 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/TestPlaybooks/playbook-TrendMicroDeepSecurity-Test.yml
> +fromversion: 5.0.0
```suggestion
fromversion: 6.0.0
```

2021-06-20 15:26 UTC, Noy-Maimon commented
@kirbles19 @ShirleyDenkberg Hi hi, can you please go over the .yml, description and readme files? Thanks

2021-06-21 19:39 UTC, RazOmry commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.yml
> +      isArray: true
Hey! 😃 
I call to `argToList` inside the `convert_arg` function. The `convert_arg` function converts the arguments from XSOAR (strings) to their real types (one of them is list). 😄

2021-06-23 12:58 UTC, Noy-Maimon requested changes

2021-06-23 12:58 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +    return_error(error_message)
```suggestion
```

2021-06-23 12:58 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +        error_message = f"Error in API call [{e.response.status_code}]\n{e.response.json().get('message')}"
```suggestion
        error_message = f"Error in API call [{e.response.status_code}]\n{e.response.json().get('message')}"
        return_error(error_message)
```

2021-06-23 12:58 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +        error_message = f"Failed to execute {demisto.command()} command.\nError:\n{e}"
```suggestion
        error_message = f"Failed to execute {demisto.command()} command.\nError:\n{e}"
        return_error(error_message)
```

2021-06-23 12:58 UTC, Noy-Maimon commented on Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
> +        error_message = f"{INVALID_URL_ERROR}\nError:\n{e}"
```suggestion
        error_message = f"{INVALID_URL_ERROR}\nError:\n{e}"
        return_error(error_message)
```

2021-06-23 13:48 UTC, Noy-Maimon commented
@RazOmry Please see the suggested changes as discussed via slack.
Once they are committed, let's schedule a demo. Please let me know when are you available.
Thanks!

2021-06-27 07:37 UTC, ShirleyDenkberg commented
@Noy-Maimon Doc review completed.  Since I did not have permission to edit the files directly in this PR, I sent the edited files to you by Slack.  Please replace the files in this PR.  The Integration README needs to be regenerated.

2021-07-04 15:35 UTC, merged