Add microsoft cas new command
demisto/content pull request #13195
Opened 2021-06-13 19:47 UTC by obenacot

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-13 19:51 UTC, obenacot commented
Substitute the closed PR #11932

2021-06-20 04:24 UTC, yaakovi requested changes
fix your commits, you still have extra changed files

2021-07-04 05:51 UTC, bakatzir commented on Packs/MicrosoftCloudAppSecurity/pack_metadata.json
> +    "currentVersion": "1.0.20",
should be a minor change, not a revision.

2021-07-04 06:26 UTC, bakatzir reviewed
Very nicely covered code.

2021-07-04 06:26 UTC, bakatzir commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
> +    request_data['contactEmail'] = contact_email
I believe this block should be located inside `elif alert_ids:`, so the `custom_filter` argument will truly override all other args

2021-07-04 06:26 UTC, bakatzir commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
> +        alerts, str(fetch_start_time), last_run)
since you changed here already, let's add a log line with the next_run info for future bugs.

2021-07-04 06:26 UTC, bakatzir commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
> +def close_benign_command(client: Client, args: dict):
```suggestion
def close_benign_command(client: Client, args: dict) -> CommandResults:
```

2021-07-04 06:26 UTC, bakatzir commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
> +def close_false_positive_command(client: Client, args: dict):
```suggestion
def close_false_positive_command(client: Client, args: dict) -> CommandResults:
```

2021-07-04 06:26 UTC, bakatzir commented on Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
> +def close_true_positive_command(client: Client, args: dict):
```suggestion
def close_true_positive_command(client: Client, args: dict) -> CommandResults:
```

2021-07-05 10:10 UTC, bakatzir approved these changes

2021-07-07 08:06 UTC, ShirleyDenkberg commented
@yaakovi @bakatzir Doc review completed.  @obenacot Need to re-generate the integration README.

2021-07-13 18:59 UTC, yaakovi approved these changes

2021-07-13 19:00 UTC, bakatzir approved these changes
please have a quick look if some of the cmds, e.g `cas-alert-close` might need special permissions. if so please list them in the docs.

2021-07-13 20:50 UTC, yaakovi commented
> please have a quick look if some of the cmds, e.g `cas-alert-close` might need special permissions. if so please list them in the docs.

not that I've seen

2021-07-13 21:42 UTC, merged