Addition of custom user agent.
demisto/content pull request #13281
Opened 2021-06-17 08:28 UTC by rhallick

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-18 09:22 UTC, rhallick commented
Hi there - just wondering if I need to do anything more in order to get this progressed please?  Thank you.

2021-06-20 09:42 UTC, Bargenish requested changes
@rhallick Thank you for you contribution.

Please see my notes below, I gave an example to the change that need to get done in all the feeds in the `Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py` file.

2021-06-20 09:42 UTC, Bargenish commented on Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.py
> +    + ' - ' + CONTENT_PACK + ' - ' + INTEGRATION
```suggestion
USER_AGENT = f'XSOAR/{DEMISTO_VERSION["version"]}.{DEMISTO_VERSION["buildNumber"]} - {CONTENT_PACK} - {INTEGRATION}'
```

2021-06-20 09:42 UTC, Bargenish commented on Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.py
> +    + ' - ' + CONTENT_PACK + ' - ' + INTEGRATION
```suggestion
USER_AGENT = f'XSOAR/{DEMISTO_VERSION["version"]}.{DEMISTO_VERSION["buildNumber"]} - {CONTENT_PACK} - {INTEGRATION}'
```

2021-06-20 09:42 UTC, Bargenish commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
> +    + ' - ' + CONTENT_PACK + ' - ' + INTEGRATION
```suggestion
USER_AGENT = f'XSOAR/{DEMISTO_VERSION["version"]}.{DEMISTO_VERSION["buildNumber"]} - {CONTENT_PACK} - {INTEGRATION}'
```

2021-06-20 09:42 UTC, Bargenish commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
> +    request_headers = {'user-agent': USER_AGENT}
Let's remove this line and define the `headers` as a parameter in the main function  and pass it to the feed_main function instead.
And in the main function #L166
```python
params['headers'] = {'user-agent': USER_AGENT}

```
_**Relevant for all the feeds**_

2021-06-20 09:42 UTC, Bargenish commented on Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
> +            headers=request_headers,
```suggestion
            headers=client.headers,
```

2021-06-23 07:06 UTC, Bargenish approved these changes

2021-06-23 07:06 UTC, merged