First commit
demisto/content pull request #13297
Opened 2021-06-18 15:36 UTC by dco9

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
First version of Covalence integrations.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-06-18 15:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=13297) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=13297) before we can accept your contribution.<br/><hr/>**dco** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=13297) it.</sub>

2021-06-20 06:16 UTC, adi88d commented
@dco9 Please register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA) before we proceed with the review.

2021-06-20 15:14 UTC, adi88d requested changes
@dco9 Thank you for your contribution, few notes:
- Please add human readable to all the commands
- remove all the secrets from the code(look in the secrets section here: https://app.circleci.com/pipelines/github/demisto/content/94932/workflows/307a4ba6-d50b-4fe1-bf30-d8fa31dbcc14/jobs/386593)
- make sure all the unitises are passed(https://app.circleci.com/pipelines/github/demisto/content/94932/workflows/307a4ba6-d50b-4fe1-bf30-d8fa31dbcc14/jobs/386592)
- code must pass linters, execute[ lint command](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/lint/README.md)
- update the commands outputs - use[ json-to-outputs command](https://github.com/demisto/demisto-sdk/tree/master/demisto_sdk/commands/json_to_outputs), some outputs paths are wrong(for example `Covalence.Sensors..listeningInterfaces`)
- update outputs descriptions(for example `description: T` is not enough)
- Logo should match the requirements (120x50 px PNG, transparent background, <10kB in Size)

see my other comments below

2021-06-22 15:24 UTC, dco9 commented on Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.py
> +                return_results('nok')
When the password is incorrect, an exception is raised:

![image](https://user-images.githubusercontent.com/86100764/122952950-57dcde80-d34c-11eb-9386-bf909d5b80f6.png)

2021-06-22 15:25 UTC, dco9 commented on Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.py
> +    details = demisto.args().get('details', 'false')
When running tests, I get:

`
NameError: name 'argToBoolean' is not defined
`

What am I doing wrong ?

2021-06-23 10:37 UTC, adi88d commented on Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.py
> +    details = demisto.args().get('details', 'false')
add `from CommonServerPython import *` to the imports section

2021-07-07 08:32 UTC, dco9 commented
Closing to solve git username issue, see PR #13577

2021-07-07 08:32 UTC, closed without merging