Marketplace services - Add  filter/transformer tags
demisto/content pull request #13303
Opened 2021-06-20 08:31 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/36557

## Description
- Added `TRANSFORMER` and `FILTER` tags to the class `PackTags`.
- Added `_is_transformer` and `_is_filter` properties to the class `Pack`.
- Update `_collect_pack_tags` and `collect_content_items` methods in order to add the filter/transformer tags to the pack if a the pack contains a filter/transformer script.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-29 08:01 UTC, guyfreund requested changes
Looks good, just one main note 💪

2021-06-29 08:01 UTC, guyfreund commented on Tests/Marketplace/marketplace_services.py
> +        tags |= {PackTags.FILTER} if self._is_filter else set()
```suggestion
        tags |= {PackTags.TRANSFORMER} if self._contains_transformer else set()
        tags |= {PackTags.FILTER} if self._contains_filter else set()
```

2021-06-30 12:03 UTC, adi88d commented
@guyfreund I added the properties `contains_filter` and `contains_transformer` to the Pack class

2021-06-30 12:04 UTC, guyfreund requested changes
Please run testing-upload and attach a successful run (make sure you see the new tag for new/modified and existing packs that contains transformer/filter and the tags for both)

2021-06-30 12:04 UTC, guyfreund requested changes

2021-06-30 12:04 UTC, guyfreund commented on Tests/Marketplace/marketplace_services.py
> +
```suggestion
```
no need

2021-07-01 14:31 UTC, adi88d commented
@guyfreund you can see the upload flow [here](https://app.circleci.com/pipelines/github/demisto/content/97777/workflows/2965af11-2c95-40f2-a099-0c93df3558a7/jobs/391893)

2021-07-01 14:35 UTC, guyfreund commented
> @guyfreund you can see the upload flow [here](https://app.circleci.com/pipelines/github/demisto/content/97777/workflows/2965af11-2c95-40f2-a099-0c93df3558a7/jobs/391893)

your upload is failing + you still have the getters in the pr

2021-07-04 07:50 UTC, yaakovi approved these changes
update the link to the build

2021-07-04 08:02 UTC, adi88d commented
testing upload flow link is [here](https://app.circleci.com/pipelines/github/demisto/content/98034/workflows/7f89cf65-91ba-4877-a7ec-92a89af7bfbb)

2021-07-04 08:09 UTC, guyfreund approved these changes
NICE
![image](https://user-images.githubusercontent.com/53565845/124378094-44b8ff80-dcb8-11eb-89d2-a9c136362342.png)

2021-07-04 08:47 UTC, merged