Fixing SplunkPy fetch
demisto/content pull request #13319
Opened 2021-06-21 11:19 UTC by guykeller

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/35102
fixes: https://github.com/demisto/etc/issues/35805
fixes: https://github.com/demisto/etc/issues/34582
fixes: https://github.com/demisto/etc/issues/34529

## Description
Adding a look behind for the occurrence time + a deduping mechanism based on internally-defined and user-defined fields, to prevent missing events while not generating duplicate events.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-22 15:03 UTC, yuvalbenshalom requested changes
see my comments

2021-06-23 13:28 UTC, guykeller commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
> +name: SplunkPy_post_conflicts
will change prior to merge

2021-06-24 08:04 UTC, yuvalbenshalom approved these changes
Approved from my side. pending final review after fixes for the enrichment will be made.

2021-07-09 08:32 UTC, guykeller commented
Adding `docs-approved` since the RN was taken from a fix by @amshamah419 in another PR

2021-07-11 06:29 UTC, Itay4 commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
> +  additionalinfo: The fetch time range will be at least of the size specified here.
please add here to something like "change only if instructed by support"

2021-07-11 06:29 UTC, Itay4 commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
> +    together are a unique identifier for the events you with to fetch
```suggestion
    together are a unique identifier for the events you with to fetch.
```

2021-07-11 06:29 UTC, Itay4 commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
> +- display: Extensive logging (for debugging purposes)
add `Advanced: ` prefix to all displays

2021-07-11 06:29 UTC, Itay4 commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
> +        demisto.info(message)
```suggestion
        demisto.debug(message)
```

2021-07-11 06:29 UTC, Itay4 commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
> +            extensive_log('SplunkPy - Dropped incident {} due to duplication.'.format(incident_id))
add `[SplunkPy]` prefix to all logs

2021-07-11 08:06 UTC, Itay4 commented on Packs/ExpanseV2/Playbooks/playbook-Expanse_Attribution.yml
> +                        simple: SplunkPyPreRelease
why is this change?

2021-07-11 08:23 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/README.md
> +| enabled_enrichments | The possible types of enrichment are: Drilldown, Asset, and Identity | False |
the new params are missing here

2021-07-11 08:25 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.yml
> +display: SplunkPyPreRelease
```suggestion
display: SplunkPy Prerelease (Beta)
```

2021-07-11 08:25 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.yml
> +display: SplunkPyPreRelease
add beta flag to this integration

2021-07-11 08:26 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.yml
> +- display: 'Advanced (change only if advised bby support): Fetch backwards window for the events occurrence time'
```suggestion
- display: 'Advanced (change only if advised by support): Fetch backwards window for the events occurrence time'
```

2021-07-11 08:27 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.yml
> +- display: Extensive logging (for debugging purposes) - Please use this option unless advised otherwise.
```suggestion
- display: Advanced: Extensive logging (for debugging purposes)
```

2021-07-11 08:27 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.yml
> +- display: Unique ID fields
```suggestion
- display: Advanced: Unique ID fields
```

2021-07-11 08:28 UTC, Itay4 commented on Packs/SplunkPyPreRelease/README.md
> +This pack is a pre -release version of the SplunkPy pack.
```suggestion
This pack is a pre-release version of the SplunkPy pack.
```

2021-07-11 08:28 UTC, Itay4 commented on Packs/SplunkPyPreRelease/pack_metadata.json
> +    "name": "SplunkPy_pre_release",
```suggestion
    "name": "SplunkPy Prerelease",
```

2021-07-11 08:29 UTC, Itay4 commented on Packs/SplunkPyPreRelease/pack_metadata.json
> +    "description": "Run queries on Splunk servers.",
please add short note to the desc about the prelease

2021-07-11 08:30 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease_description.md
> +## SplunkPy
please add note here about the prelease

2021-07-11 08:30 UTC, Itay4 commented on Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.yml
> +defaultclassifier: SplunkPyPreRelease
are there such classifier and mapper

2021-07-12 15:56 UTC, yuvalbenshalom approved these changes

2021-07-20 06:39 UTC, merged