Add compromised/breached collection.
demisto/content pull request #13396
Opened 2021-06-25 12:41 UTC by EvgeniyMeteliza

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Add compromised/breached to the list of available commands and to the fetch incidents command and all stuff tied to the new incident type

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-06-25 15:41 UTC, marcellarichmond commented
@mchasepan

2021-06-29 13:39 UTC, Bargenish requested changes
@EvgeniyMeteliza Thank you for your contribution.

2021-06-29 13:39 UTC, Bargenish commented on Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.py
> +            main_table_data, additional_tables = result, []
```suggestion
                del result["updateTime"]
            main_table_data, additional_tables = result, []
```

2021-06-29 15:51 UTC, EvgeniyMeteliza commented on Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_1_0.md
> +- Added **GIB Data Breach** to classifier.
Done

2021-06-29 15:51 UTC, EvgeniyMeteliza commented on Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_1_0.md
> +- Added layout for **GIB Data Breach**.
Done

2021-06-29 15:51 UTC, EvgeniyMeteliza commented on Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_1_0.md
> +- Added **GIB Data Breach** to mapper.
Done

2021-06-29 15:52 UTC, EvgeniyMeteliza commented on Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_1_0.md
> +- Added new search by id command for compromised/breached collection.
Done

2021-06-29 15:53 UTC, EvgeniyMeteliza commented on Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIBTIA/GroupIBTIA.py
> +            main_table_data, additional_tables = result, []
Done

2021-06-30 12:36 UTC, Bargenish approved these changes

2021-07-08 11:48 UTC, Bargenish commented
There's an issue with the API.
Will merge the PR once I'll get an update from @EvgeniyMeteliza

2021-07-08 15:24 UTC, merged