Add dockerimage1
demisto/content pull request #13414
Opened 2021-06-27 11:15 UTC by MosheEichler

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Add dockerimage to integratoin/script YML files, This is the first PR out of a few

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-07-06 10:49 UTC, reutshal requested changes
Please fix RN in DBotSuggestClassifierMapping

2021-07-06 10:49 UTC, reutshal commented on Packs/Slack/pack_metadata.json
> +        "Active_Directory_Query": {
Please revert this change

2021-07-06 11:21 UTC, reutshal approved these changes

2021-07-11 13:46 UTC, MosheEichler commented
This PR has been closed because he is merged in https://github.com/demisto/content/pull/13425

2021-07-11 13:46 UTC, closed without merging