New Azure Storage Playbooks
demisto/content pull request #13473
Opened 2021-06-29 19:06 UTC by toddm92

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
New Prisma Cloud Azure Storage Playbooks

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2021-06-29 19:59 UTC, toddm92 commented
@mayagoldb ..last two Azure (Storage) playbooks.

2021-07-01 12:05 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Updated On**
```suggestion
- **Subscription Updated On** - Added **Azure Storage Misconfiguration** incident to **Subscription Updated On** Associated types.
```

2021-07-01 12:06 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Description**
```suggestion
- **Subscription Description** - Added **Azure Storage Misconfiguration** incident to **Subscription Description** Associated types.
```

2021-07-01 12:07 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Resource API Name**
```suggestion
- **Resource API Name** - Added **Azure Storage Misconfiguration** incident to **Resource API Name** Associated types.
```

2021-07-01 12:07 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Created On**
```suggestion
- **Subscription Created On** - Added **Azure Storage Misconfiguration** incident to **Subscription Created On** Associated types.
```

2021-07-01 12:08 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Updated By**
```suggestion
- **Subscription Updated By** - Added **Azure Storage Misconfiguration** incident to **Subscription Updated By** Associated types.
```

2021-07-01 12:08 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Prisma Cloud Status**
- **Prisma Cloud Status** - Added **Azure Storage Misconfiguration** incident to **Prisma Cloud Status** Associated types.

2021-07-01 12:09 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Created By**
```suggestion
- **Subscription Created By** - Added **Azure Storage Misconfiguration** incident to **Subscription Created By** Associated types.
```

2021-07-01 12:09 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Prisma Cloud Time**
```suggestion
- **Prisma Cloud Time** - Added **Azure Storage Misconfiguration** incident to **Prisma Cloud Time** Associated types.
```
```

2021-07-01 12:11 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **VPC ID**
```suggestion
- **VPC ID** - Added **Azure Storage Misconfiguration** incident to **VPC ID** Associated types.
```

2021-07-01 12:11 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Prisma Cloud ID**
```suggestion
- **Prisma Cloud ID** - Added **Azure Storage Misconfiguration** incident to **Prisma Cloud ID** Associated types.
```

2021-07-01 12:11 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Type**
```suggestion
- **Subscription Type** - Added **Azure Storage Misconfiguration** incident to **Subscription Type** Associated types.
```

2021-07-01 12:11 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Resource Cloud Type**
```suggestion
- **Resource Cloud Type** - Added **Azure Storage Misconfiguration** incident to **Resource Cloud Type** Associated types.
```

2021-07-01 12:12 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Name**
```suggestion
- **Subscription Name** - Added **Azure Storage Misconfiguration** incident to **Subscription Name** Associated types.
```

2021-07-01 12:12 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **RRN**
```suggestion
- **Subscription Assigned By** - Added **Azure Storage Misconfiguration** incident to **Subscription Assigned By** Associated types.
```

2021-07-01 12:13 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription Assigned By**
```suggestion
- **Subscription Assigned By** - Added **Azure Storage Misconfiguration** incident to **Subscription Assigned By** Associated types.
```

2021-07-01 12:13 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Subscription ID**
```suggestion
- **Subscription ID** - Added **Azure Storage Misconfiguration** incident to **Subscription ID** Associated types.
```

2021-07-01 12:14 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Prisma Cloud Reason**
```suggestion
- **Prisma Cloud Reason** - Added **Azure Storage Misconfiguration** incident to **Prisma Cloud Reason** Associated types.
```

2021-07-01 12:14 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Prisma Cloud Rules**
```suggestion
- **Prisma Cloud Rules** - Added **Azure Storage Misconfiguration** incident to **Prisma Cloud Rules** Associated types.
```

2021-07-01 12:18 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- **Azure Storage Misconfiguration**
```suggestion
- **Azure Storage Misconfiguration** - New incident type.
```

2021-07-01 12:20 UTC, tomneeman151293 commented on Packs/PrismaCloud/ReleaseNotes/1_8_0.md
> +- Updated for new Azure Storage playbooks
```suggestion
- New layout for Azure Storage Misconfiguration Incident.
```

2021-07-01 12:26 UTC, tomneeman151293 requested changes
Thanks for the contribution! Added a few requested changes in the release notes. If you could go over them.
Also, the Layout file you added is available from 6.0.0 and above, I will add a layout supporting versions below 6.0.0 to your branch as the playbook is supported from 5.0.0

2021-07-01 14:20 UTC, tomneeman151293 commented on Packs/PrismaCloud/Layouts/layoutscontainer-Azure_Storage_Misconfiguration.json
> +    "id": "Azure Storage Misconfiguration Incident",
```suggestion
    "id": "Azure Storage Misconfiguration",
```
ID of layout should equal to the incident type it is related to

2021-07-01 14:21 UTC, tomneeman151293 commented on Packs/PrismaCloud/Layouts/layoutscontainer-Azure_Storage_Misconfiguration.json
> +    "name": "Azure Storage Misconfiguration Incident",
```suggestion
    "name": "Azure Storage Misconfiguration",
```

2021-07-01 14:22 UTC, tomneeman151293 requested changes
Changes to layout container to match the new incident type added, also here is the zip of layout file support below 6.0.0. Please extract this zip and and add the file to layouts directory.
[layout-detailsV2-Azure_Storage_Misconfiguration.json.zip](https://github.com/demisto/content/files/6748828/layout-detailsV2-Azure_Storage_Misconfiguration.json.zip)

2021-07-09 00:55 UTC, toddm92 commented
@tomneeman151293 suggestions resolved.  Thx.

2021-07-09 01:04 UTC, toddm92 commented
@tomneeman151293 new layout file added

2021-07-11 08:31 UTC, tomneeman151293 requested changes
Thanks! Looks great!
Added a small fix for the newly added layout (my bad) to fix validation failure.
Please commit and re-run to see if validation passes

2021-07-11 08:31 UTC, tomneeman151293 commented on Packs/PrismaCloud/Layouts/layout-detailsV2-Azure_Storage_Misconfiguration.json
> +  "fromVersion": "4.1.0",
This should fix the validation failure
```suggestion
  "fromVersion": "5.0.0",
```

2021-07-11 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=13473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=13473) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: toddm92<br/>:x: tomneeman151293<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=13473) it.</sub>

2021-07-12 18:27 UTC, toddm92 commented
> Thanks! Looks great!
> Added a small fix for the newly added layout (my bad) to fix validation failure.
> Please commit and re-run to see if validation passes

@tomneeman151293  done.

2021-07-13 07:33 UTC, tomneeman151293 commented
@mayagoldb I am done with the review from my side, waiting for your side as well

2021-07-22 16:06 UTC, toddm92 commented
@tomneeman151293 I believe @mayagoldb is out of the office until the end of July.  If we need two reviewers, I guess we'll have to wait.  Otherwise, we can push this one thru.

2021-07-22 16:42 UTC, tomneeman151293 commented
@Michal-Vardi @Shellyber Any way we can push this forward?

2021-08-03 12:24 UTC, mayagoldb approved these changes

2021-08-03 13:44 UTC, tomneeman151293 approved these changes

2021-08-03 14:02 UTC, merged