Update rn issue
demisto/content pull request #13512
Opened 2021-07-04 10:40 UTC by MosheEichler

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-07-04 21:14 UTC, yaakovi requested changes
* update RN files
* check the docker images again, they seem incorrect

2021-07-04 21:14 UTC, yaakovi commented on Packs/Accessdata/ReleaseNotes/1_0_3.md
> +- %%UPDATE_RN%%
```suggestion
```

2021-07-04 21:14 UTC, yaakovi commented on Packs/Accessdata/ReleaseNotes/1_0_3.md
> +- %%UPDATE_RN%%
is this the correct version?
```suggestion
- Updated the Docker image to: *demisto/python2:1.2.3.123*.
```

2021-07-04 21:14 UTC, yaakovi commented on Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
> +  dockerimage: demisto/ldap:1.0.0.19
doesn't seem right

2021-07-04 21:14 UTC, yaakovi commented on Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.yml
> +dockerimage: demisto/python3:3.9.5.200
doesn't seem right

2021-07-05 06:47 UTC, MosheEichler commented
It's not real PR It's fake PR to reproduce the bug in https://github.com/demisto/etc/issues/38630

2021-07-06 07:03 UTC, closed without merging