Archer v2 bug
demisto/content pull request #13533
Opened 2021-07-05 22:32 UTC by merit-maita

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/37752

## Description
added a parameter as an api endpoint for archer v2.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-07-06 05:24 UTC, bakatzir commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
> +  name: ApiEndpoint
name field can be snakified, to follow python conventions.

2021-07-06 05:24 UTC, bakatzir commented on Packs/ArcherRSA/ReleaseNotes/1_1_19.md
> +- Added an API Endpoint as a parameter, with the name API Endpoint.
```suggestion
- Fixed an issue of hard coded API endpoints in the code by adding a new *API Endpoint* parameter to the integration.
```

2021-07-08 07:24 UTC, yaakovi requested changes

2021-07-08 07:24 UTC, yaakovi commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
> +  type: 0
* move it up to be right after the `Server URL` parameter (as they belong together).
* change the default value to `rsaarcher/api`
* in the code, make sure it doesn't create a duplicate in the URL (`<base URL>/rsaarcher/rsaarcher/api`)
* remove the `rsaarcher` suffix from the `Server URL` example.

2021-07-08 07:24 UTC, yaakovi commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
> +API_ENDPOINT = demisto.params().get('api_endpoint', 'api')
* move to the main.
* use the following implementation of default value:
`params.get('api_endpoint') or 'rsaarcher/api'`

2021-07-08 07:24 UTC, yaakovi commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
> +            res = self._http_request('POST', f'/{API_ENDPOINT}/core/security/login', json_data=body)
add the API endpoint to the base URL in the main function instead of applying it each time

2021-08-22 08:14 UTC, yaakovi approved these changes

2021-08-22 08:15 UTC, merged