Fetch playbook
demisto/content pull request #13639
Opened 2021-07-11 15:09 UTC by daryakoval

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
demisto/etc#34585

## Description
Added playbook and script.

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation

2021-07-18 15:20 UTC, daryakoval commented
Please see the following explanation [here](https://github.com/demisto/etc/issues/34585#issuecomment-878271297).

![image](https://user-images.githubusercontent.com/72339940/126072334-234d0aa9-8cc2-4131-b8c6-7e49c2c5d1b7.png)
 
First lets delete context and `get indicator field to search` using demisto rest api, in order to get searchfield, sourcebrand fields.

Then `Set indicators search query` just set context key: searchQuery, value : sourceBrands:"${serverConfig.response.sysConf.sourcebrand}" (it is the key from server_keys). 

Now we can start checking if feed already fetched indicators. `VerifyEnoughIndicators` and `Check If Indicators exsist` takes care of it.  If fetch didn't happened yet, we will use GenericPolling: 
![image](https://user-images.githubusercontent.com/72339940/126072510-0b93f821-0c62-4708-9664-ab42899fa1f1.png)


![image](https://user-images.githubusercontent.com/72339940/126072590-89f6a0b8-f3ca-4eb1-bbfe-5911eb1b07a0.png)

Now we use `findIndicators` to get all indicators. 
Then I wrote script in order to check if all fields that we asked are mapped in all Indicators that were fetched. It happends using script `VerifyContextFieldsList` at step named: `Check If Fields Exists`.

After all this, we can check Integration Health using script `VerifyIntegrationHealth` that I wrote too, it checks if there were some errors during the fetch.

2021-07-18 15:43 UTC, ShahafBenYakir reviewed
Initial brief review

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyContextFieldsList/VerifyContextFieldsList.py
> +    fields_to_search_array = [field.strip() for field in fields_to_search.split(',')]
```suggestion
    fields_to_search = args.get(argToList('fields_to_search', ''))
    context = args.get('context', '{}')
```

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyContextFieldsList/VerifyContextFieldsList.py
> +        raise ValueError('context not specified')
This is redundant as you set the input as required

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyContextFieldsList/VerifyContextFieldsList.yml
> +name: VerifyContextFieldsList
I think the name should be VerifyObjectFieldsList as the script alone has no relation to context.

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyContextFieldsList/VerifyContextFieldsList.yml
> +- name: context
```suggestion
- name: object
```

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyEnoughIncidents/VerifyEnoughIncidents.py
> +    demisto.info('hi')
```suggestion
    args = demisto.args()
    query = args.get('query')
    size = int(args.get('size'))
```

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyEnoughIncidents/VerifyEnoughIncidents.py
> +    raw_result = demisto.executeCommand("SearchIncidentsV2", {"query": query,
Need to check for failure here

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyEnoughIncidents/VerifyEnoughIncidents.py
> +    incidents_len = len(raw_result[0].get("Contents", [""])[0].get("Contents", {}).get("data"))
```suggestion
    incidents_len = len(raw_result[0].get("Contents", [{}])[0].get("Contents", {}).get("data"))
```

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyEnoughIncidents/VerifyEnoughIncidents.yml
> +  id: VerifyEnoughIncidents
Don't see this being used anywhere what do I miss?

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.py
> +''' ENTRY POINT '''
```suggestion
```

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.py
> +
This is required

```suggestion
    integration_name = args.get('integration_name')
```

2021-07-18 15:43 UTC, ShahafBenYakir commented on Packs/DeveloperTools/ReleaseNotes/1_1_8.md
> +- Receive fields and context. Verifies that these field exists in context. (Available from Cortex XSOAR 6.0.0).
```suggestion
- Check integration for existing errors (Available from Cortex XSOAR 6.0.0).
##### New: VerifyEnoughIncidents
- Check whether a given query returns enough incidents. (Available from Cortex XSOAR 6.0.0).
##### New: VerifyContextFieldsList
- Verify that a given object includes all the given fields. (Available from Cortex XSOAR 6.0.0).
```

2021-08-01 17:28 UTC, dantavori requested changes
very nice 👍🏽 see my comments.

2021-08-01 17:28 UTC, dantavori commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.yml
> +- contextPath: IntegrationHealth.isHealth
```suggestion
- contextPath: IntegrationHealth.isHealthy
```

2021-08-01 17:28 UTC, dantavori commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.yml
> +  description: 'Integration name to check is health'
```suggestion
  description: 'Integration name to check its health status.'
```

2021-08-01 17:28 UTC, dantavori commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.yml
> +comment: 'Check integration for existing errors.'
```suggestion
comment: 'Checks for existing errors in a given integration.'
```

2021-08-01 17:28 UTC, dantavori commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.yml
> +  description: 'Checks if the given integration got errors.'
```suggestion
  description: 'Determines the health status of the integration.'
```

2021-08-01 17:28 UTC, dantavori commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.yml
> +  description: 'Checks if the given integration finished it fetch.'
```suggestion
  description: 'Determines whether the fetch-indicators command was ended.'
```

2021-08-01 17:28 UTC, dantavori commented on Packs/DeveloperTools/Scripts/VerifyIntegrationHealth/VerifyIntegrationHealth.py
> +    health_dict = raw_result[0]["Contents"]["response"]["health"]
please wrap this with error handling: use `is_error()` and `get_error()` CSP functions (also in other uses of executeCommand in the PR).

2021-08-02 11:14 UTC, daryakoval commented on Packs/DeveloperTools/Scripts/VerifyObjectFieldsList/VerifyObjectFieldsList.py
> +            check_components(components, new_context)
dt will check if we have at least one indicator that has such field. My script will check that all indicators has such field.

2021-08-02 15:11 UTC, daryakoval commented
@dantavori @ShahafBenYakir  
Run Fetch Indicators Test Playbook for 3 different feeds, how can I add integration names to each test? It will be easier to distinguish different feeds.
![image](https://user-images.githubusercontent.com/72339940/127883410-d7867c89-ccbe-45aa-9ba5-ce3ad62f9d31.png)

2021-08-03 14:10 UTC, dantavori reviewed
presenting the integrations names in the build is possible but it will require some infra changes, not required for now but we can talk about it.
we can make a short call to go over the leftovers, and let's also schedule a demo for tomorrow.

2021-08-04 15:59 UTC, dantavori approved these changes
awesome

2021-08-18 08:40 UTC, ShirleyDenkberg commented
@dantavori @ShahafBenYakir Doc review completed.  
@daryakoval There is no README for the VerifyObjectFieldsList script.  Was that an oversight?

2021-08-22 11:47 UTC, merged