add docker image8
demisto/content pull request #13677
Opened 2021-07-13 11:44 UTC by MosheEichler

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-07-13 15:18 UTC, reutshal approved these changes

2021-07-14 12:12 UTC, reutshal requested changes

2021-07-14 12:12 UTC, reutshal commented on Packs/CommonScripts/Scripts/ParseEmailFiles/test_data/email_with_special_char_bytes.eml
> +x-dg-rorf: ?�I��?�Hէ�c�[?4
Please revert this change

2021-07-14 12:12 UTC, reutshal commented on Packs/ExpanseV2/ReleaseNotes/1_7_2.md
> +Minor edit in the README file regarding playbook inputs.
Is this your change?

2021-07-14 12:36 UTC, MosheEichler commented on Packs/ExpanseV2/ReleaseNotes/1_7_2.md
> +Minor edit in the README file regarding playbook inputs.
No. I fixed it

2021-07-14 14:03 UTC, merged