add arcusteam pack
demisto/content pull request #13823
Opened 2021-07-22 15:10 UTC by ElishaArcusTeam

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
This is the first pull request for ArcusTeam

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2021-07-22 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=13823) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=13823) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=13823) it.</sub>

2021-07-25 07:01 UTC, Shellyber commented
@ElishaArcusTeam Thank you for your contribution. Please sign the CLA and submit the contribution form, So I can start reviewing the PR.

2021-07-25 15:10 UTC, ElishaArcusTeam commented
We got a problem related to the import of the following modules in the ```ArcusTeam.py``` file.
If the use the file with the following imports
```python
from CommonServerPython import *  # noqa: F401
import demistomock as demisto  # noqa: F401
```
The code fails to run on our local XSOAR machine with the following error:
 ```
 Error from ArcusTeam is : Script failed to run: 
Error: [Traceback (most recent call last):
   
   File "<string>", line 5, in <module>
 ModuleNotFoundError: No module named 'CommonServerPython'
] (2604) (2603)
```
If we remove the lines, the integration works fine on our local XSOAR machine but the ```ci/circleci: Run Unit Testing And Lint ``` fails on the linter with the following message
```
...
Found 27 errors in 1 file (checked 1 source file)


###############
 Pylint errors 
###############

ArcusTeam
************* Module ArcusTeam
/devwork/ArcusTeam.py:18:13: E0602 Client: Undefined variable 'BaseClient'
/devwork/ArcusTeam.py:32:16: E0602 deviceToMarkdown: Undefined variable 'tableToMarkdown'
/devwork/ArcusTeam.py:63:10: E0602 arcusteam_get_devices: Undefined variable 'urljoin'
/devwork/ArcusTeam.py:75:11: E0602 arcusteam_get_devices: Undefined variable 'CommandResults'
...
```
For now the code in the PR doesn't include the imports

2021-07-26 06:51 UTC, tomneeman151293 commented
@ElishaArcusTeam How do you upload the integration to your local machine?

2021-07-27 15:34 UTC, tomneeman151293 commented
Is this PR ready for review? @ElishaArcusTeam

2021-08-01 08:13 UTC, georgemusayev commented
Hello Tom,
Elisha is on vacation for the week, can we postpone the review to next week?

2021-08-02 12:21 UTC, mchasepan commented on Packs/ArcusTeam/README.md
> +Use ArcusTeam's discovery and insights to imporve your organization secuirty posture
Would you like to add a link to your site? Or your sales team?

2021-08-04 09:15 UTC, ElishaArcusTeam commented
> Is this PR ready for review? @ElishaArcusTeam

The PR is ready.

2021-08-09 09:17 UTC, tomneeman151293 requested changes
Great! 
I really recommend using the client class and performing the HTTP calls with it and not just initializing it for no purpose.
Currently, your code does not handle verify or proxy. Using HTTP calls through Client class (and initializing Base Client) 
Please refer to docs, or handle proxy/verify parameters
https://xsoar.pan.dev/docs/integrations/code-conventions#client-class

See my other changes as well

2021-08-09 09:17 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +        "returnFields": str(args.get("return_fields")).split(','),
```suggestion
        "returnFields": returnFields,
```

2021-08-09 09:17 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +    returnFields = str(args.get("return_fields")).split(',')
Please add default value to the args.get like other required arguments

2021-08-09 09:17 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +    url = urljoin(demisto.params()["url"], "/api/v10/auth/login_apikey")
If you decide to keep it here, please change to authentication_url for easier reading

2021-08-09 09:17 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +    base_url = urljoin(demisto.params()["url"], "/api/v10/xsoar")
Changing to real default value
```suggestion
    base_url = urljoin(demisto.params()["url"], "https://web.prod.arcusteam.com")
```

2021-08-31 08:36 UTC, ElishaArcusTeam commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.yml
> +      defaultValue: cve,risk
This is our default and most important field. We prefer to show the basic fields so the user won't get confused.

2021-08-31 08:36 UTC, ElishaArcusTeam commented on Packs/ArcusTeam/README.md
> +Use ArcusTeam's discovery and insights to imporve your organization secuirty posture
There is a link in line 9

2021-08-31 09:02 UTC, ElishaArcusTeam commented on Packs/ArcusTeam/Integrations/ArcusTeam/README.md
> +| ArcusTeamVulnerabilities.results.url | string | CVE url |
We changed the output to show more. We are not showing everything because its a lot and not relevant for most users

2021-08-31 11:33 UTC, tomneeman151293 commented
@ElishaArcusTeam Waiting for your message to see when the PR is ready for re-review

2021-08-31 12:30 UTC, mchasepan commented on Packs/ArcusTeam/README.md
> +## What Does this pack do?
```suggestion
## What does this pack do?
```

2021-08-31 12:30 UTC, mchasepan commented on Packs/ArcusTeam/README.md
> +Use ArcusTeam's discovery and insights to imporve your organization secuirty posture
```suggestion
Use ArcusTeam's discovery and insights to improve your organization security posture
```

2021-08-31 12:30 UTC, mchasepan commented on Packs/ArcusTeam/pack_metadata.json
> +    "description": "This Pack for ArcusTeam's DeviceTotal Platform predict helps to identify and manage vevulnerabilities found on IoT devices",
```suggestion
    "description": "ArcusTeam's DeviceTotal Platform helps to identify and manage vulnerabilities found on IoT devices",
```

2021-09-01 06:54 UTC, tomneeman151293 requested changes
Looks great! added some small changes (just need to make sure the logic i did of moving authentication to client class did not break anything), after that we will schedule a quick demo to see the integration

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/README.md
> +    |  The client ID | The client ID from ArcusTeam dashboard | True |
```suggestion
    |  The client ID | The client ID from ArcusTeam dashboard | True |
    | Trust any certificate (not secure) |  | False |
    | Use system proxy settings |  | False |
```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +    }
Deleting, moved inside client class
```suggestion
```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +            base_url=base_url, verify=verify_certificate, headers=headers, proxy=proxy
```suggestion
            base_url=base_url, verify=verify_certificate, proxy=proxy, authentication_url=authentication_url,
            client_id=client_id, api_key=api_key
```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +    returnFields = str(args.get("return_fields", ['risk', 'cve'])).split(',')
```suggestion
    returnFields = str(args.get("return_fields", 'risk,cve')).split(',')
```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +
move authentication function inside client class
```suggestion
    def get_authentication_token(self, authentication_url: str, headers: Dict, payload: Dict):
        return self._http_request(
            method='POST',
            full_url=authentication_url,
            headers=headers,
            data=payload
        )

```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.py
> +
Call authentication during client init. To make sure proxy/insecure are used for request of authentication
```suggestion

    def __init__(self, base_url: str, verify: bool, proxy: bool, authentication_url: str, client_id: str, api_key: str):
        super().__init__(base_url=base_url, verify=verify, proxy=proxy)
        payload = {
            "apiKey": api_key,
            "clientID": client_id,
        }
        headers = {"Accept": "application/json", "Content-Type": "application/json"}
        authentication_response = self.get_authentication_token(authentication_url, headers, payload)
        access_token = authentication_response["access_token"]
        headers["Authorization"] = "Bearer " + access_token
        self.headers = headers

```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/ArcusTeam.yml
> +  additionalinfo: The client ID from ArcusTeam dashboard
Adding insecure and proxy params
```suggestion
  additionalinfo: The client ID from ArcusTeam dashboard
- display: Trust any certificate (not secure)
  name: insecure
  type: 8
  required: false
- display: Use system proxy settings
  name: proxy
  type: 8
  required: false
```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/README.md
> +| ArcusTeamDevices.devices.categories | string |  Device categories |
```suggestion
| ArcusTeamDevices.devices.categories | Unknown |  Device categories | 
```

2021-09-01 06:54 UTC, tomneeman151293 commented on Packs/ArcusTeam/Integrations/ArcusTeam/README.md
> +| page_size | Page size [1,100]. Default is 10. | Optional |
```suggestion
| page_size | Page size. Minimum page size is 1, maximum is 100. Default is 10. | Optional |
```

2021-09-01 13:22 UTC, tomneeman151293 commented
Great! reaching you guys to schedule a quick demo

2021-09-12 11:24 UTC, tomneeman151293 approved these changes
Thanks a lot guys!

2021-09-12 11:49 UTC, merged