Edgescan adding vulnerability annotation
demisto/content pull request #13880
Opened 2021-07-28 09:45 UTC by mdrobniu

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
This change is introducing a new command for adding annotations into vulnerabilities

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [x] 6.2.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [x] Documentation

2021-07-29 09:18 UTC, tomneeman151293 commented
@mdrobniu Is this ready for review?

2021-07-29 09:22 UTC, mdrobniu commented
@tomneeman151293 Yes please.

2021-07-29 09:23 UTC, tomneeman151293 requested changes
Looks great! small change requested in RN to follow our RN conventions if possible.
Also, could you please add the command example to the README file of the integration?

2021-07-29 09:23 UTC, tomneeman151293 commented on Packs/Edgescan/ReleaseNotes/1_0_3.md
> +- New command for adding annotations into vulnerabilities
```suggestion
- Added the **edgescan-vulnerabilities-add-annotation** command for adding annotations into vulnerabilities.
```

2021-08-09 06:59 UTC, mdrobniu commented
@tomneeman151293 Hey. I'm back from holiday. 

Can you please reenable write permissions for the repo? I know I was denied after PR to this repo and I'm unable now to push the changes here? 

Thanks

2021-08-09 09:02 UTC, tomneeman151293 commented
@mdrobniu Hey, I hope you have enjoyed your vacation. Unfortunately, due to a change in the policy of repository permissions, I can't give you permissions to that. Could you please open the PR via contribution flow.

2021-08-09 09:04 UTC, mdrobniu commented
@tomneeman151293 
Ok I'll do. Please close this PR.

2021-08-09 09:22 UTC, closed without merging