Added several commands to Darktrace integration
demisto/content pull request #13905
Opened 2021-07-30 07:16 UTC by simmyno

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Adding some more commands the the Darktrace integration, seeing as it currently supports a limited amount of API calls. These have been tested in our own integration in a forked integration, and works fine. 

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-07-30 07:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=13905) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=13905) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=13905) it.</sub>

2021-08-03 08:29 UTC, yaakovpraisler requested changes
Looking good. Thanks for the contribution!
Please see my comments -

1. Please update the README file with your new commands.
2. Please bump the version and add release notes - https://xsoar.pan.dev/docs/documentation/release-notes.
3. I also saw that all the other commands have unit tests, so please add tests to the commands you added as well.

2021-08-11 16:14 UTC, yaakovpraisler commented
Hi @simmyno - What's the status here?

2021-08-13 09:14 UTC, simmyno reviewed
Still in progress, have been a bit busy with other projects. Will update what is needed

2021-08-13 09:16 UTC, simmyno commented
@yaakovpraisler Also not very familiar with how Github is setup in pull request, but will figure it out eventually

2021-08-13 10:00 UTC, yaakovpraisler commented
@simmyno It's okay. Let me know when you finish.
Also I saw that the last commits were made by another GitHub account, so you'll have to sign in the CLA from that account, as you can see [above](https://github.com/demisto/content/pull/13905#issuecomment-889684831).

2021-08-24 12:54 UTC, yaakovpraisler commented on Packs/Darktrace/Integrations/Darktrace/README.md
> +| Darktrace.Model | Dictionary | Details of the component |
```suggestion
| Darktrace.Component | Dictionary | Details of the component |
```

2021-08-24 12:54 UTC, yaakovpraisler commented on Packs/Darktrace/Integrations/Darktrace/README.md
> +| Darktrace.ModelBreach.breach_details | Dictionary | Details of the model breach |
```suggestion
| Darktrace.ModelBreach| Dictionary | Details of the model breach |
```

2021-08-24 15:18 UTC, yaakovpraisler approved these changes
Good job with the tests! - I've added a few more individual comments, please fix them and we're done.

2021-08-24 15:18 UTC, yaakovpraisler commented on Packs/Darktrace/Integrations/Darktrace/Darktrace.yml
> +      type: Unknown
Please fill in the description and add the type of the returned value. Also in the following outputs.

2021-08-24 15:18 UTC, yaakovpraisler commented on Packs/Darktrace/Integrations/Darktrace/Darktrace_test.py
> +    """
Seems this is taken from another test. Please edit these docs (also on the following).

2021-08-25 13:22 UTC, yaakovpraisler approved these changes

2021-08-25 14:27 UTC, merged