Abnormal security
demisto/content pull request #13935
Opened 2021-08-02 09:50 UTC by dschuan

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Update Abnormal Security Content Pack to V1.1.0

##### Updates
- Abuse Mailbox Information commands added
- Case Analysis Command added
- Genome/Employee Information command added
- Commands to retrieve threat/abuse mailbox logs in csv format added
- Enable optional subtenancy input when accessing threats, cases and abuse mailbox endpoints

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [x] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-08-08 10:18 UTC, Shellyber requested changes
Great job on this contribution!
Please see my comments. 

Also let's schedule a demo for the new commands.

2021-08-08 10:18 UTC, Shellyber commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/README.md
> +```!abnormal-security-get-abnormal-case case_id=12805```
```suggestion
```!abnormal-security-get-abnormal-case case_id=1234```
```

2021-08-09 11:12 UTC, dschuan commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/test_data/test_download_data_from_threat_log_in_csv_format.csv
> +2021-07-20 20:14:32+00:00,'Kevin Lau',abc@def.com,[LIKELY PHISHING] does this go to junk,,,,,Email Account Takeover,Internal Compromised Email Account,None / Others,Text,Auto-Remediated to Junk
it is provided in our mock data so it is cleared for use as an example :)

2021-08-09 11:18 UTC, dschuan commented
@Shellyber thanks for the suggestions. Will make the changes and arrange a meeting with you separately.

2021-08-16 11:22 UTC, Shellyber requested changes
Great job!
After the demo, please add `removeNull` to the `tableToMarkdown` function. 
and see my comments.

I'm will wait for your update regarding the `filter` argument.

2021-08-16 11:22 UTC, Shellyber commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
> +        outputs_key_field='',
```suggestion
        outputs_key_field='campaignId',
```

2021-08-16 11:22 UTC, Shellyber commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
> +        outputs_prefix='AbnormalSecurity.AbuseCampaigns',
```suggestion
        outputs_prefix='AbnormalSecurity.AbuseCampaign',
```

2021-08-16 11:22 UTC, Shellyber commented on Packs/AbnormalSecurity/ReleaseNotes/1_1_0.md
> +  - Features Added
As discussed, Let's remove the commands examples and leave only the commands.
For example:
- Abuse Mailbox Information commands:
  - abnormal-security-list-abuse-mailbox-campaigns
  - abnormal-security-get-abuse-mailbox-campaign

2021-08-18 11:44 UTC, dschuan commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/command_examples
> +!abnormal-security-download-threat-log-csv filter="receivedTime gte 2020-12-01T01:01:01Z"
@Shellyber I'd input the filter wrongly during the demo (omitted the `receivedTime`) field. So we are good to go on the filter

2021-08-18 11:59 UTC, dschuan commented
@Shellyber all changes complete on my end :) please let me know if there are any further changes recommended, thanks!

2021-08-19 07:57 UTC, Shellyber reviewed
@dschuan Looks good!
See my last comments

2021-08-19 07:57 UTC, Shellyber commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.yml
> +      - contextPath: AbnormalSecurity.AbuseCampaignDetails.campaignId
Seems that after the changes, you didn't update the yml outputs.
Please fix according to the new one.

2021-08-19 07:57 UTC, Shellyber commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
> +    response = client.get_employee_identity_analysis_genome_data_request(email_address)
Let's add to the response also the email_address (which is unique)
And then update the `outputs_key_field` in the command results with it.

2021-08-19 07:57 UTC, Shellyber commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
> +        outputs_key_field='',
```suggestion
        outputs_key_field='email',
```

2021-08-19 11:53 UTC, dschuan commented
@Shellyber thanks for the catch :) The suggestions have been implemented

2021-08-22 07:30 UTC, Shellyber commented on Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
>          outputs_key_field='',
```suggestion
        outputs_key_field='email',
```

2021-08-22 11:37 UTC, Shellyber commented
@dschuan Please fix the conflict. and then we can merge

2021-08-23 07:06 UTC, Shellyber approved these changes

2021-08-23 07:07 UTC, merged