Slackv3 HotFix for SocketMode concurrency bug.
demisto/content pull request #14008
Opened 2021-08-05 08:35 UTC by amshamah419

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/39986
fixes: https://github.com/demisto/etc/issues/39925

## Description
Long-running was not utilizing a lock for the demisto calls. This PR implements the CommonServer function to handle the lock acquisition and releasing of the demisto object. There are some changes to the threading to enable the locking to work.

Additionally, some scopes were missing as identified by some customers. Those have been verified and added to the App Manifest.

2021-08-05 08:49 UTC, amshamah419 commented on Packs/Slack/Integrations/SlackV3/SlackV3.py
> +            check_for_unanswered_questions(integration_context)
Reducing calls to `demisto.getIntegrationContext()` and passing them between the two. Every time a `demisto` object is called, we lock and unlock the resource so to reduce the need, I'm limiting the number of calls.

2021-08-05 10:04 UTC, amshamah419 commented on Packs/Slack/Integrations/SlackV3/SlackV3.py
> +        loop.close()
Wrap in try-catch to catch loop exception

2021-08-16 06:38 UTC, yuvalbenshalom requested changes
see my comments, 
let's have a short talk so I will be able to better understand the changes.

2021-08-16 06:38 UTC, yuvalbenshalom commented on Packs/Slack/ReleaseNotes/2_1_3.md
> +- Improved the App Manifest to contain more OAuth scopes for functionality.
probably needs an update

2021-08-16 06:38 UTC, yuvalbenshalom commented on Packs/Slack/Integrations/SlackV3/SlackV3.py
> +        await client.send_socket_mode_response(response)
I think line 1015-1019 should all be under the scope of `if req:`

2021-08-16 06:38 UTC, yuvalbenshalom commented on Packs/Slack/Integrations/SlackV3/SlackV3.py
> +        # Instead we use a custom session.
let's talk about this.

2021-08-16 06:38 UTC, yuvalbenshalom commented on Packs/Slack/Integrations/SlackV3/SlackV3.py
> +    Slack's Socket listener by default pipes messages via stdout. This is an attempt to capture those
it works?

2021-08-18 07:46 UTC, yuvalbenshalom approved these changes

2021-08-18 08:36 UTC, merged