[Bug] CrowdStrike Falcon - we are not passing incident type to the classifier into raw json
demisto/content pull request #14310
Opened 2021-08-15 11:26 UTC by daryakoval

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/40369

## Description
Added incident type to each incident

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-08-15 11:57 UTC, daryakoval commented
Test fails [here](https://app.circleci.com/pipelines/github/demisto/content/107512/workflows/f54447aa-ecf7-4550-86f5-76e5223d6115/jobs/411640).

2021-08-16 10:55 UTC, ShahafBenYakir commented on Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_20.md
> +- Fixed a bug where `CrowdStrike Falcon Detection` and `CrowdStrike Falcon Incident` incident types were not set correctly.
```suggestion
- Fixed a bug where `CrowdStrike Falcon Detection` and `CrowdStrike Falcon Incident` incident types were not classified correctly.
```

2021-08-16 10:56 UTC, daryakoval commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
> +            Old getLastRun which holds `first_behavior_time` and `last_detection_id`
previous

2021-08-16 11:05 UTC, dantavori requested changes

2021-08-17 06:48 UTC, roysagi commented on Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_20.md
> +- Fixed an issue in ***fetch-incidents*** command where the *incident_type* field was not returned to the raw incident data.
```suggestion
- Fixed an issue in the ***fetch-incidents*** command where the *incident_type* field was not in raw incident data.
```

2021-08-17 08:25 UTC, ShahafBenYakir approved these changes

2021-08-17 09:02 UTC, dantavori approved these changes

2021-08-17 09:02 UTC, merged