MITRE v2 Feed - Some fixes
demisto/content pull request #14423
Opened 2021-08-19 09:45 UTC by ChanochShayner

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Add TPB, Add docs to get indicator command.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-08-21 22:05 UTC, ChanochShayner commented
TPB task for the specific problem -
![image](https://user-images.githubusercontent.com/57212002/130335904-9ed14f33-da36-4e14-9eee-4ef921ab0c5c.png)

2021-08-22 12:14 UTC, yuvalbenshalom approved these changes

2021-08-22 12:14 UTC, yuvalbenshalom commented on Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/README.md
> +
please add also attack pattern documentation

2021-08-22 12:15 UTC, yuvalbenshalom requested changes
see my comment

2021-08-23 08:58 UTC, bakatzir commented on Packs/FeedMitreAttackv2/ReleaseNotes/1_0_5.md
> +- Downgrade the Docker image to: *demisto/taxii2:1.0.0.21842* to fix an issue where the commands ***attack-pattern*** ***mitre-get-indicator-name*** does not work properly.
```suggestion
- Downgraded the Docker image to: *demisto/taxii2:1.0.0.21842* to fix an issue where the commands ***attack-pattern***, ***mitre-get-indicator-name*** did not work properly.
```

2021-08-23 08:59 UTC, bakatzir reviewed
commented on the RN

2021-08-23 11:11 UTC, merged