SentinelOne V2
demisto/content pull request #14431
Opened 2021-08-19 13:05 UTC by devang-metron

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
1. Fixed argument issue in following commands:
    - sentinelone-reactivate-site
    - sentinelone-create-white-list-item
2. Updated docker image version

## Minimum version of Cortex XSOAR
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2021-08-19 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=14431) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=14431) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=14431) it.</sub>

2021-08-22 14:44 UTC, guykeller commented
@devang-metron 
Hi there! thanks for contributing.

Some notes:
1. I'd love to set a short talk and discuss these changes - what would be the best way to reach you?
2. It seems that the changes you've made are breaking backwards compatibility, is that on purpose? can you explain why it's necessary?

2021-08-23 05:54 UTC, guykeller requested changes
It seems that the changes you've made are breaking backwards compatibility, is that on purpose? can you explain why it's necessary?

2021-08-23 06:29 UTC, devang-metron commented
@guykeller

> I'd love to set a short talk and discuss these changes - what would be the best way to reach you?

I am available for a call in mornings EST time (7am - noon EST) and at devang(Demisto DFIR community).

> It seems that the changes you've made are breaking backwards compatibility, is that on purpose? can you explain why it's necessary?

Yes the changes are done on purpose.
For `sentinelone-reactivate-site`:
  - we need to send data which will include expiration or the unlimited flag.

For `sentinelone-create-white-list-item`:
  - we need to send both group_ids and site_ids. otherwise api call fails.

2021-09-01 10:07 UTC, guykeller approved these changes

2021-09-01 10:08 UTC, merged