Feed no update tag
demisto/content pull request #14460
Opened 2021-08-22 13:23 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-08-23 09:47 UTC, glicht commented on Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
> +    if response.status_code == 304:
This logic should be done before saving integration context. When 304 is returned server may respond  with empty etag.

2021-08-23 09:48 UTC, glicht requested changes
Missing use of `If-Modified-Since` when `Last-Modified` is used. see: https://httpwg.org/specs/rfc7232.html#header.if-modified-since

2021-08-23 09:53 UTC, glicht requested changes
@yaakovi the whole `noupdate` logic depends on the server version. I don't see where this is taken into account.

2021-10-17 11:05 UTC, glicht commented
@yaakovi @adi88d what is the status here?

2021-10-17 14:38 UTC, adi88d commented
@glicht @yaakovi The pR is ready and waiting for review
I invited you for a demo on Wednesday 20.10.21

2021-11-01 06:19 UTC, merged

2021-11-01 12:42 UTC, tomneeman151293 commented
Need to see why tests of BitcoinAbuse weren't collected for this PR. as they're failing since then