[Bug] Maltiverse returns error when file command has no proccess_list
demisto/content pull request #14517
Opened 2021-08-24 14:22 UTC by daryakoval

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/40678

## Description
Maltiverse returned an error: 
!file file="b47265100eb91e2e3bd82fb9d4d43baa9597bb50a3e88a8362f4e5e789c23a8f" threshold="5" using="Maltiverse_instance_1"(Maltiverse)
Reason
Failed to execute file command. Error: 'process_list'
![Uploading image.png…]()

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-08-24 14:34 UTC, daryakoval commented
Failed test [here](https://app.circleci.com/pipelines/github/demisto/content/109564/workflows/e3582cee-4e3a-4be0-bd67-c2182ddf1852/jobs/416193).

2021-08-24 16:21 UTC, amshamah419 commented on Packs/Maltiverse/ReleaseNotes/1_0_7.md
> +- Fixed an issue where the **file** command failed.
```suggestion
- Fixed an issue where the **file** command would fail when some fields were missing from the data returned by Multiverse.
```

2021-08-24 17:51 UTC, dantavori requested changes
nice, minor fix and we can merge

2021-08-24 17:51 UTC, dantavori commented on Packs/Maltiverse/Integrations/Maltiverse/Maltiverse_test.py
> +def test_file_no_process_list(requests_mock):
please add a docstring with given-when-then
```suggestion
def test_file_command__missing_process_list_field_in_response(requests_mock):
```

2021-08-29 08:48 UTC, daryakoval commented on Packs/Maltiverse/Integrations/Maltiverse/Maltiverse_test.py
> +def test_file_no_process_list(requests_mock):
done

2021-08-29 18:51 UTC, dantavori approved these changes

2021-08-31 07:56 UTC, merged