add xdr-get-endpoints-by-status command
demisto/content pull request #14527
Opened 2021-08-25 07:10 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/39923

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-09-14 07:15 UTC, yaakovi requested changes

2021-09-14 07:15 UTC, yaakovi commented on Packs/CortexXDR/.pack-ignore
> +ignore=BC103
you can't ignore those

2021-09-14 07:15 UTC, yaakovi commented on Packs/CortexXDR/ReleaseNotes/3_0_27.md
> +- Updated the Docker image to: *demisto/python3:3.9.6.24019*.
```suggestion
#### Scripts
##### XDRDisconnectedEndpoints
- Uses the ***xdr-get-endpoints-by-status*** command to get the disconnected endpoint count.
- Updated the Docker image to: *demisto/python3:3.9.6.24019*.

##### XDRConnectedEndpoints
- Uses the ***xdr-get-endpoints-by-status*** command to get the connected endpoint count.
- Updated the Docker image to: *demisto/python3:3.9.6.24019*.
```

2021-09-14 07:15 UTC, yaakovi commented on Packs/CortexXDR/Scripts/XDRConnectedEndpoints/XDRConnectedEndpoints.yml
> -- name: limit
why did you remove the limit? please restore

2021-09-14 07:15 UTC, yaakovi commented on Packs/CortexXDR/Scripts/XDRDisconnectedEndpoints/XDRDisconnectedEndpoints.py
> +        return_error(f'Failed to execute XDRConnectedEndpoints. Error: {str(ex)}')
revert

2021-09-14 07:15 UTC, yaakovi commented on Packs/CortexXDR/Scripts/XDRDisconnectedEndpoints/XDRDisconnectedEndpoints.yml
> -- name: limit
same here

2021-09-14 07:15 UTC, yaakovi commented on Packs/CortexXDR/pack_metadata.json
> +    "currentVersion": "3.0.27",
switch to minor version

2021-09-26 13:05 UTC, ShirleyDenkberg commented
@yaakovi Doc review completed.

2021-09-26 14:43 UTC, yaakovi approved these changes

2021-09-26 14:43 UTC, yaakovi commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +>connected endpoins count: 4
```suggestion
>connected endpoints count: 4
```

2021-09-26 14:43 UTC, yaakovi commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +        readable_output=f'{status} endpoins count: {endpoints_count}',
```suggestion
        readable_output=f'{status} endpoints count: {endpoints_count}',
```

2021-09-26 21:20 UTC, merged