Pack adoption
demisto/content pull request #14593
Opened 2021-08-30 18:27 UTC by rosenbet

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-08-30 18:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=14593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=14593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=14593) it.</sub>

2021-08-30 18:46 UTC, marcellarichmond commented
@mchasepan

2021-08-31 09:03 UTC, amshamah419 commented on Packs/AttivoBotsink/ReleaseNotes/1_0_3.md
> +- Note: Support for this pack will be moving to the partner around 12/1/2021
```suggestion
- Note: Support for this pack will be moving to the partner around December 1, 2021
```

2021-08-31 09:48 UTC, barchen1 requested changes
@rosenbet Please sign the `Contributor License Agreement` so we can merge this PR.
https://github.com/demisto/content/pull/14593#issuecomment-908581789
Thanks.

2021-09-05 06:44 UTC, barchen1 approved these changes

2021-09-05 06:45 UTC, merged