Added new phishing campaign dynamic section scripts
demisto/content pull request #14648
Opened 2021-09-01 20:10 UTC by yaakovpraisler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/40396

## Description
Added new campaign showing scripts for dynamic sections in phishing campaign layout.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation

2021-09-09 12:48 UTC, dantavori requested changes
looks great! most of my notes are docs notes.

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/PerformActionOnCampaignIncidents/PerformActionOnCampaignIncidents.py
> +        action = get_custom_field(ACTION_ON_CAMPAIGN_FIELD_NAME)
as we spoke - use an argument to determine the similarity type (high/low)

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/GetCampaignLowerSimilarityIncidentsIdsAsOptions/GetCampaignLowerSimilarityIncidentsIdsAsOptions.yml
> +  Select field.
```suggestion
comment: Gets the IDs of incidents with lower similarity. Used to fill the optional values of the multi-select "Phishing Campaign Select Campaign Lower Similarity Incidents" incident field.
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/GetCampaignLowerSimilarityIncidentsIdsAsOptions/GetCampaignLowerSimilarityIncidentsIdsAsOptions_test.py
> +        Validate the
please complete the docstring

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/GetCampaignLowerSimilarityIncidentsIdsAsOptions/GetCampaignLowerSimilarityIncidentsIdsAsOptions_test.py
> +    except SystemExit:
```suggestion
    try:
        GetCampaignLowerSimilarityIncidentsIdsAsOptions.main()
        assert False
    except SystemExit:
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred.py
> +                                   "No last incident occurred found. </div></div>"
```suggestion
                                   "N/A</div></div>"
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/ShowCampaignLastIncidentOccurred/ShowCampaignLastIncidentOccurred.yml
> +comment: Displays the date of the last campaign incident occurred.
```suggestion
comment: Displays the occurrence date of the last campaign incident.
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients.yml
> +comment: Displays the phishing campaign recipients email addreses and their amount.
```suggestion
comment: Displays the phishing campaign recipients email addresses and their amount.
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/Scripts/ShowCampaignSenders/ShowCampaignSenders.yml
> +comment: Displays the phishing campaign senders email addreses and their amount.
```suggestion
comment: Displays the phishing campaign senders email addresses and their amount.
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/ReleaseNotes/3_0_2.md
> +- Displays the date of the last campaign incident occurred. (Available from Cortex XSOAR 5.5.0).
```suggestion
- Displays the occurrence date of the last campaign incident. (Available from Cortex XSOAR 5.5.0).
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/ReleaseNotes/3_0_2.md
> +- Displays the phishing campaign recipients email addreses and their amount. (Available from Cortex XSOAR 5.5.0).
```suggestion
- Displays the phishing campaign recipients email addresses and their amount. (Available from Cortex XSOAR 5.5.0).
```

2021-09-09 12:48 UTC, dantavori commented on Packs/Campaign/ReleaseNotes/3_0_2.md
> +- Displays the phishing campaign senders email addreses and their amount. (Available from Cortex XSOAR 5.5.0).
```suggestion
- Displays the phishing campaign senders email addresses and their amount. (Available from Cortex XSOAR 5.5.0).
```

2021-09-09 12:55 UTC, dantavori commented
P.S: please add readmes to all of the scripts

2021-09-14 14:00 UTC, dantavori approved these changes

2021-09-30 10:38 UTC, tschanfeld commented
minor edits

2021-09-30 18:14 UTC, merged