Xdr isolation and un-isolation warning on disconnected endpoint
demisto/content pull request #14751
Opened 2021-09-05 09:22 UTC by abaumgarten

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: link to the issue

## Description
Added a new argument for both isolation and un-isolation actions in order to know if the user wants to get back an error if the endpoint is disconnected. The default is an error. Otherwise, a warning will be returned. 

## Screenshots
Paste here any images that will help the reviewer

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-09-05 10:30 UTC, abaumgarten commented
I will re-generate the readme file after docs review

2021-09-09 08:00 UTC, bakatzir reviewed
please consider renaming the arg to the suggested. I did not review the code.

2021-09-09 08:00 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      name: disconnected_endpoint_should_return_error
```suggestion
      name: suppress_disconnected_endpoint_error
```

2021-09-09 08:00 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: Whether return an error when trying to isolate a disconnected endpoint.
```suggestion
      description: Whether to return an error when trying to isolate a disconnected endpoint.
```

2021-09-09 08:00 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      name: disconnected_endpoint_should_return_error
```suggestion
      name: suppress_disconnected_endpoint_error
```

2021-09-09 08:00 UTC, bakatzir commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: Whether return an error when trying to unisolate a disconnected
```suggestion
      description: Whether to return an error when trying to unisolate a disconnected
```

2021-09-09 08:00 UTC, bakatzir commented on Packs/CortexXDR/ReleaseNotes/3_0_28.md
> +- Added an argument for the **xdr-isolate-endpoint** and **xdr-unisolate-endpoint** commands whether or not to return an error when the endpoint is disconnected.
```suggestion
- Added the *suppress_disconnected_endpoint_error* argument for the ***xdr-isolate-endpoint*** and the ***xdr-unisolate-endpoint*** commands which dictates whether to return an error when the endpoint is disconnected.
```

2021-09-19 09:09 UTC, abaumgarten commented
@yuvalbenshalom can you review this, please?

2021-09-30 07:27 UTC, yuvalbenshalom requested changes
see my comments

2021-09-30 07:27 UTC, yuvalbenshalom commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      defaultValue: 'True'
```suggestion
      defaultValue: 'true'
```

2021-09-30 07:27 UTC, yuvalbenshalom commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      defaultValue: 'True'
```suggestion
      defaultValue: 'true'
```

2021-09-30 07:27 UTC, yuvalbenshalom commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +    disconnected_should_return_error = argToBoolean(args.get('suppress_disconnected_endpoint_error', True))
```suggestion
    disconnected_should_return_error = not argToBoolean(args.get('suppress_disconnected_endpoint_error', False))
```
while it is correct that if `suppress_disconnected_endpoint_error` does not exist, then `disconnected_should_return_error` should be true, 
if `uppress_disconnected_endpoint_error` exists, `disconnected_should_return_error` should get the opposite value of it.

2021-09-30 07:27 UTC, yuvalbenshalom commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +    disconnected_should_return_error = argToBoolean(args.get('suppress_disconnected_endpoint_error', True))
```suggestion
    disconnected_should_return_error = not argToBoolean(args.get('suppress_disconnected_endpoint_error', False))
```

2021-09-30 09:46 UTC, abaumgarten commented
@yuvalbenshalom @bakatzir I think we might have a misunderstanding here.
@bakatzir requested to change the new argument name to `suppress_disconnected_endpoint_error`, but then the description is incorrect. When sets to True, an error shouldn’t be raised, When sets to False an error should be raised (the default behaviour).
Then, @yuvalbenshalom's review does not hold after this change, please correct me if I am wrong. Maybe it is worth changing the argument name? 
thanks

2021-09-30 11:41 UTC, yuvalbenshalom approved these changes

2021-09-30 15:48 UTC, merged