Bitsight/adds guard against no status code
demisto/content pull request #14810
Opened 2021-09-09 18:50 UTC by sethborden

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Updates the BitSight test module to better handle cases where a 200 response isn't received from BitSight servers.

## Screenshots
N/A

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-09-13 09:37 UTC, tallieber commented
Hey @sethborden, what was happen when the status code wasn't 200, what was the behaviour?  Where this code acts differently with status code that is not 200? (I DM you also on slack)

2021-09-29 07:20 UTC, tallieber requested changes

2021-09-29 07:20 UTC, tallieber commented on Packs/BitSight/Integrations/BitSightForSecurityPerformanceManagement/BitSightForSecurityPerformanceManagement.py
> +    requested_guid = demisto.params()["guid"]
Better use .get()

2021-09-29 07:20 UTC, tallieber commented on Packs/BitSight/Integrations/BitSightForSecurityPerformanceManagement/BitSightForSecurityPerformanceManagement.py
> +    requested_guid = demisto.params()["guid"]
```suggestion
    available_guids = {c.get("guid", "") for c in res["companies"]}
    requested_guid = demisto.params().get("guid", "")
```

2021-10-04 14:30 UTC, sethborden commented
@tallieber here's the video of the the non-working version of the code along with the working version of the code. In order to update the code I cloned the existing version of the BitSight code into a BitSight Development integration, but didn't commit those changes.  These changes should update the "production" version of the code.

https://user-images.githubusercontent.com/3753337/135869828-5b935a60-006f-490e-a6b2-db146ff2e804.mov

2021-10-05 08:30 UTC, tallieber commented
Hey @sethborden thank you for the video!

In order to fix the branching issue, you need to pull and merge master into your working branch, we cannot accept changes into the master branch.

2021-10-20 14:54 UTC, merged