List used dockers images
demisto/content pull request #14831
Opened 2021-09-12 08:25 UTC by wghammas

introduce ListUsedDockersImages - New script that list all used dockers images by Integrations and/or automations

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-09-12 13:13 UTC, anara123 requested changes

2021-09-12 13:13 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.py
> +                dockers[conf[INTEGRATION_ID]] = docker_image
check if you can index integration display name and not the integration id.
in case of automation, it should be name

2021-09-12 13:13 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/README.md
> +List all dockers images that are in used by the installed Integration and/or Automations.
```suggestion
List all dockers images that are used by the installed Integration and/or Automations. 
```

2021-09-12 13:13 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/README.md
> +Table that list all dockers images that are in used by installed Integration and/or Automations
add here an example of output

2021-09-12 14:19 UTC, wghammas commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.py
> +    active_integration_instances = demisto.internalHttpRequest(POST_COMMAND, "%s" % SETTING_INTEGRATION_SEARCH,
I did not change all the constants only SETTING_INTEGRATION_SEARCH and SETTING_AUTOMATION_SEARCH

2021-09-14 18:06 UTC, anara123 approved these changes

2021-09-14 18:06 UTC, anara123 commented
@yaron-libman please review

2021-10-12 12:20 UTC, okaufman34 commented
@anara123 Doc review completed

2023-07-24 09:18 UTC, closed without merging