Azure ad graph test playbook
demisto/content pull request #14832
Opened 2021-09-12 08:51 UTC by tkatzir

## Contributing to Cortex XSOAR Content

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Related: https://github.com/demisto/etc/issues/39512

## Description
Add Incidents Fetch Test playbook

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2021-09-12 14:30 UTC, daryakoval requested changes
Please unskip test. (The test is skipped in conf.json - [here](https://github.com/demisto/content/blob/master/Tests/conf.json#L4605)

In addition please add to content-test-conf, to `Azure Active Directory Identity Protection` params 'isFetch': true.

2021-09-12 14:55 UTC, tkatzir commented
> Please unskip test. (The test is skipped in conf.json - [here](https://github.com/demisto/content/blob/master/Tests/conf.json#L4605) )
> 
> In addition please add to content-test-conf, to `Azure Active Directory Identity Protection` params 'isFetch': true.

Done:
https://github.com/demisto/content/pull/14832/commits/24e73cf4340859d1c0a626ec10618e7f01db6c29
https://github.com/demisto/content-test-conf/pull/1336/commits/f8f07250698a240c50966c2f56cc7821195a7167

2021-09-12 15:20 UTC, daryakoval approved these changes

2021-10-05 13:26 UTC, amshamah419 commented on Packs/AzureActiveDirectory/ReleaseNotes/1_1_2.md
> +- Solved an issue where fetch incidents didnm't work due to time zone mismatches.
```suggestion
- Fixed an issue where ***fetch-incidents** would fail due to mismatching time zones.
```

2021-10-06 06:32 UTC, merged