introduce ListUsedDockersImages - New script that list all used docke…
demisto/content pull request #14853
Opened 2021-09-12 20:16 UTC by wissamg

introduce ListUsedDockersImages - New script that list all used dockers images by Integrations and/or automations

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-09-12 21:31 UTC, anara123 requested changes

2021-09-12 21:31 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.py
> +                                                               REQUEST_INTEGRATION_SEARCH_BODY)
@wissamg please replace the const with the body dictionary for better readability.

2021-09-12 21:31 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.py
> +            outputs_prefix='Docker Image',
```suggestion
            outputs_prefix='UsedDockerImages',
```

2021-09-12 21:31 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.yml
> +  type: String
this is not the updated context outputs.
You can use the new `demisto-sdk generate-context` command to generate the context outputs here.

2021-09-12 21:31 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.py
> +            readable_output=md)
return also `raw_response=result_dict`

2021-09-12 21:31 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.py
> +            outputs_key_field='Docker Image',
We don't return fields with space/special chars in them to the context, so it should be DockerImage without spaces.
But it also means you have to either to create similar array but with a bit different keys, or changes the keys to not contain spaces and special chars in them, like `Images`

2021-09-12 21:31 UTC, anara123 commented on Packs/CommonScripts/Scripts/ListUsedDockersImages/ListUsedDockersImages.py
> +
it makes more sense also adding test playbook to this script, because it calls different xsoar apis.

2021-09-13 18:36 UTC, wissamg commented
@yaron-libman  Hi,
 This is Wissam from the content team can you review this script for me please.

Thanks a lot

2021-09-14 06:34 UTC, ShirleyDenkberg commented
@anara123 Doc review completed.

2021-09-14 08:07 UTC, wghammas approved these changes

2021-09-14 12:48 UTC, ShirleyDenkberg commented
@anara123 @wghammas Full doc review completed.  BTW, the ID and the name is ListUsedDockersImages.  It really should be ListUsedDockerImages (without the s at the end of Docker).  Up to you if you want to change it.

2021-09-14 13:23 UTC, wissamg commented
> @anara123 @wghammas Full doc review completed. BTW, the ID and the name is ListUsedDockersImages. It really should be ListUsedDockerImages (without the s at the end of Docker). Up to you if you want to change it.

Thanks a lot @ShirleyDenkberg, thanks a lot for the help and the effort I will fix this immediately

2021-09-19 07:57 UTC, anara123 approved these changes

2021-09-19 08:03 UTC, merged