add defaults
demisto/content pull request #14863
Opened 2021-09-13 07:50 UTC by melkabetz

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-09-13 11:05 UTC, barchen1 requested changes
Thank you for your contribution!
Please create RN file for your changes, you can take a look here: https://xsoar.pan.dev/docs/documentation/release-notes

Let me know if you need help

2021-09-13 11:05 UTC, barchen1 commented on Packs/Ironscales/Integrations/Ironscales/Ironscales.yml
> +defaultvalue: Ironscales
Why did you add `defaultvalue`?
You can remove it

2021-09-23 08:10 UTC, barchen1 requested changes
1. Please fix the validation issues here: https://app.circleci.com/pipelines/github/demisto/content/116873/workflows/5b3d0c5d-c8c2-4485-b826-64fbda73cd05/jobs/428071

2. The script should be in this path(need to add a folder with the script name under Scripts folder)
`Packs/Ironscales/Scripts/IronscalesEmailFieldTrigger/IronscalesEmailFieldTrigger.yml`
3. Please add a readme file for the script and unitest file (`README.md`, `IronscalesEmailFieldTrigger_test.py`)
4. Please add a new release-notes file and update the `pack_metadata` file accordingly.

Let me know if you need help

2021-09-23 08:10 UTC, barchen1 commented on Packs/Ironscales/Scripts/IronscalesEmailFieldTrigger.yml
> +  version: 26
```suggestion
  version: -1
```

2021-09-23 11:10 UTC, barchen1 requested changes

2021-09-23 11:10 UTC, barchen1 commented on Packs/Ironscales/Integrations/Ironscales/Ironscales.yml
> +  display: Maximum number of incidents to fetch every time
```suggestion
  display: Maximum number of incidents per fetch
```

2021-09-23 11:10 UTC, barchen1 commented on Packs/Ironscales/Scripts/IronscalesEmailFieldTrigger/README.md
> +
Please add some short data about the script.

2021-09-23 11:10 UTC, barchen1 commented on Packs/Ironscales/ReleaseNotes/1_1_0.md
> +- %%UPDATE_RN%%
Please add a note about the changes you made in the yml file.

2021-09-23 12:41 UTC, bakatzir commented on Packs/Ironscales/ReleaseNotes/1_1_0.md
> +
```suggestion

#### Incident Fields
- **Ironscales-Choose-Classification**

#### Incident Types
- **Ironscales**

#### Integrations
##### Ironscales
- Fixed a typo in the context output of the ***ironscales-classify-incident*** command.
- Added a default mapper to the integration.
- Updated the Docker image to: *demisto/python3:3.9.7.24076*.

#### Scripts
##### New: IronscalesEmailFieldTrigger
- Automatically changes email field when choosing a classification.

```

2021-09-23 13:26 UTC, barchen1 approved these changes

2021-09-23 19:16 UTC, bakatzir approved these changes
failing on the change of the context path that was misspelled. merging.
```
Packs/Ironscales/Integrations/Ironscales/Ironscales.yml: [BC102] - Possible backwards compatibility break, You've changed the context in the file,please undo. the command is:
ironscales-classify-incident
```

2021-09-23 19:16 UTC, merged