Taxii 2 enhancement to fetch stix objects other than indicators
demisto/content pull request #15180
Opened 2021-10-04 16:14 UTC by merit-maita

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: 

## Description
Taxii 2 enhancement to fetch stix objects other than indicators.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-10-13 14:17 UTC, DeanArbel commented on Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
> +    filter_args = {}
You can remove the init of `filter_args` since we no longer filter `indicator`.

2021-10-13 14:39 UTC, DeanArbel commented on Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
> +                "tags": [tag for tag in list(self.tags)],
Why not just return `list(self.tags)`?

2021-10-17 10:37 UTC, bakatzir commented on Packs/FeedTAXII/ReleaseNotes/1_0_13.md
> +- Updated docker image to *demisto/taxii2:1.0.0.23423*.
```suggestion
- Added support to fetch non indicator stix objects, e.g, attack pattern, tool.
- Added relationships ingestion between objects.
- Added certificate authentication.
- Updated the Docker image to: *demisto/taxii2:1.0.0.23423*.
```

2021-10-17 10:37 UTC, bakatzir commented on Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
> +        # indicators = self.extract_indicators_from_envelope_and_parse(envelope, limit)
rm?

2021-10-20 06:51 UTC, Bargenish requested changes
Nice work!
* Please add unit-tests to the functions youv'e added in the API module.
* Add to the TPB a flow of getting only one indicator type and add a screenshot of it.
* Add a screenshot of a relationship that was created in the system (as we haven't seen one in the demo)


see my comment below.

2021-10-20 06:51 UTC, Bargenish commented on Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
> +            "rawJSON": report_obj
```suggestion
            "rawJSON": report_obj,
```

2021-10-20 06:51 UTC, Bargenish commented on Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
> +                'firstseenbysource': relationships_object.get('created')
```suggestion
                'firstseenbysource': relationships_object.get('created'),
```

2021-11-02 12:31 UTC, Bargenish approved these changes
Good work.

2021-11-02 12:31 UTC, Bargenish commented on Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
> +            raise DemistoException('You can not configure either certificate or key, both should be provided.')
```suggestion
            raise DemistoException('Both certificate and key should be provided or neither should be.')
```

2021-11-03 09:50 UTC, DeanArbel approved these changes
Amazing job!

2021-11-03 22:48 UTC, merged