New Webscraper Automation Script
demisto/content pull request #15211
Opened 2021-10-06 12:24 UTC by ayman-m

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
An Automation script to scrap web pages

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [x ] Documentation

2021-10-06 12:45 UTC, ayman-m commented
I am going to submit another PR of the new container image referenced here

2021-10-06 13:55 UTC, daryakoval commented
@ayman-m  Hi, We have docker image [bs4](https://github.com/demisto/dockerfiles/tree/master/docker/bs4), that uses lxml and beautifulSoup libraries. Maybe it is possible to use it instead?

2021-10-07 08:09 UTC, daryakoval commented on Packs/WebScraper/Scripts/WebScraper/WebScraper.py
> +import xmltodict
Ok, you are right. Please see my comments at [docker pr](https://github.com/demisto/dockerfiles/pull/6323#pullrequestreview-773576422).

2021-10-10 09:57 UTC, daryakoval requested changes

2021-10-10 09:57 UTC, daryakoval commented on Packs/WebScraper/Scripts/WebScraper/WebScraper.py
> +        outputs_key_field='',
Every time that someone will execute this script, all context data related to `WebScraper` will be replaced. Is it ok?

2021-10-10 09:57 UTC, daryakoval commented on Packs/WebScraper/Tests/id_set.json
> +{
What is this file? 
If was uploaded by mistake please remove.

2021-10-12 13:21 UTC, ayman-m commented on Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
> +dockerimage: aymanam/scraper:latest
@daryakoval I tested the new image, it works fine

2021-10-13 08:59 UTC, daryakoval commented on Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
> +dockerimage: aymanam/scraper:latest
Please use new docer image: `demisto/bs4-py3:1.0.0.24176`

2021-10-13 14:13 UTC, daryakoval commented
@ayman-m Let's schedule a demo session.

2021-10-13 14:40 UTC, daryakoval approved these changes

2021-10-13 14:41 UTC, merged