upload MalwareBazaar
demisto/content pull request #15224
Opened 2021-10-07 09:06 UTC by eyalpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/40594

## Description
MalwareBazaar integration

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-10-10 15:47 UTC, dantavori requested changes
great job!
1. Test playbook failed to me on malware-comment-add's `Verify Outputs` task - please review
2. getting this when I try to run a command from my localhost (even though "trust any certificate" is checked):
   ![image](https://user-images.githubusercontent.com/38749041/136703103-3bdbbe51-3350-4a42-a5b8-253f53d05cb6.png)
3. Go over the validation errors in the build.

see my other notes, and please schedule a demo (including me, Anar, Guy, Shahaf and Meital).

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.yml
> +      type: Unknown
please go over the "unknown" types and if strings, update accordingly

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.yml
> +    description: Download (fetch) malware samples from MalwareBazaar. Any malware
```suggestion
    description: Download malware samples from MalwareBazaar. Any malware
```
fetch is a "reserved word" in XSOAR, we use it only in fetch incidents/indicators

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.yml
> +      type: String
```suggestion
```
`File` context path is for `file` commands

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_description.md
> +obtain intel based of file hash, tag, signature, file type, etc.
```suggestion
MalwareBazaar offers API to download malware samples, comment malware samples and obtain intel based of file hash, tag, signature, file type, etc.
```

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
> +import CommonServerPython
```suggestion
from CommonServerPython import Common
```

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
> +    indicator: CommonServerPython.Common.File = result.indicator
```suggestion
    indicator: Common.File = result.indicator
```

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
> +        - creating a CommanResult containing DbotScore and relationship
```suggestion
        - Make sure a CommandResult containing DbotScore with a BAD score and a relationship is returned.
```
also let's check the relationship

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
> +            - Return file reputation for each file
```suggestion
            - Make sure a file reputation for each file is returned.
```

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
> +            - return a list of malware samples
```suggestion
            - Make sure a list of malware samples is returned.
```

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
> +            - Display a success message or raise exception when it fails
```suggestion
            - Make sure a success message is returned.
```
also let's check the case it fails when no API key is provided.

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar_test.py
> +        - Raising an error
```suggestion
        - Make sure an error is raised.
```

2021-10-10 15:47 UTC, dantavori commented on Packs/MalwareBazaar/Integrations/MalwareBazaar/README.md
> +
why did you remove the line specifies the product version?

2021-11-07 13:52 UTC, ShirleyDenkberg commented
@eyalpalo I edited the yml file.  Therefore, please regenerate the integration README.  I also added content for the pack README.  
@dantavori Doc review completed.

2021-11-09 14:21 UTC, merged