ReversingLabs basic playbooks
demisto/content pull request #15267
Opened 2021-10-11 10:51 UTC by ivukovicRL

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added 4 playbooks, fixed minor bug

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-10-11 13:53 UTC, daryakoval commented
@ivukovicRL Please fill the [Contribution Registration form](https://forms.gle/XDfxU4E61ZwEESSMA).

2021-10-12 12:03 UTC, ivukovicRL commented
> @ivukovicRL Please see my comments [here](https://github.com/demisto/content/pull/15267#pullrequestreview-776173712).
> 
> After you apply all my changes lets schedule a demo session.

Hi, thanks for the review! Sure for the demo, is sometimes tomorrow 08-17(CET) ok for you?

2021-10-12 12:42 UTC, daryakoval requested changes

2021-10-12 12:42 UTC, daryakoval commented on Packs/ReversingLabs_A1000/pack_metadata.json
> +    "created": "2020-10-08T00:00:00Z",
Why you changing the creation date?

2021-10-12 12:42 UTC, daryakoval commented on Packs/ReversingLabs_TitaniumScale/pack_metadata.json
> +    "created": "2021-10-08T00:00:00Z",
Same here, why this change is required?

2021-10-12 12:42 UTC, daryakoval commented on Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
> +  "created": "2020-10-08T00:00:00Z",
Please do not change creation date.

2021-10-13 11:50 UTC, evisochek commented on Packs/ReversingLabs_TitaniumScale/Playbooks/Detonate_File_-_ReversingLabs_TitaniumScale.yml
> +fromversion: 5.0.0
If there is no prevention, Please update to 6.0.0

2021-10-13 11:51 UTC, evisochek commented on Packs/ReversingLabs_Titanium_Cloud/Playbooks/File_Reputation_-_ReversingLabs_TitaniumCloud.yml
> +fromversion: 5.0.0
If there is no prevention, Please update to 6.0.0

2021-10-13 13:40 UTC, evisochek commented on Packs/ReversingLabs_TitaniumScale/Playbooks/Detonate_File_-_ReversingLabs_TitaniumScale.yml
> +- No tests (auto formatted)
I think that those playbooks are related to the integration, I think that we should remove them.

2021-10-13 14:10 UTC, daryakoval commented on Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.py
> +        markdown = f"{markdown}\n {sources_table}"
Please update Integration README with new human readable output for this command..

2021-10-13 14:54 UTC, daryakoval approved these changes

2021-10-13 14:54 UTC, merged