Aws iam
demisto/content pull request #15400
Opened 2021-10-20 14:31 UTC by eyalpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/40873

## Description
AWS IAM integration enhancements. Four commands added.

## Minimum version of Cortex XSOAR
- [ ] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-03 15:14 UTC, dantavori requested changes

2021-11-03 15:14 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
> +      type: Unknown
```suggestion
      type: String
```

2021-11-03 15:14 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS_IAM_test.py
> +def test_list_user_policies(mocker, args, res):
please add docstrings to all test functions ("given, when, then")

2021-11-03 15:14 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS_IAM_test.py
> +from CommonServerPython import tableToMarkdown, pascalToSpace
```suggestion
```

2021-11-03 15:14 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS_IAM_test.py
> +    assert contents.get('HumanReadable') == human_readable
```suggestion
    assert 'AWS IAM Policies for user test' in contents.get('HumanReadable')
```

2021-11-03 15:14 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS_IAM_test.py
> +    assert contents.get('HumanReadable') == human_readable
same here

2021-11-03 15:14 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS_IAM_test.py
> +    assert contents.get('EntryContext') == ec
same here

2021-11-03 15:14 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS_IAM_test.py
> +          'AWS.IAM.Users(val.UserName === \'{}\').InlinePoliciesMarker'.format('test'): response.get('Marker')}
you are pretty much providing the same code lines as the function you are testing, no need to do all of this. Just check if the mock data exists in the response.

2021-11-04 09:33 UTC, eyalpalo commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.py
> +    page_size = arg_to_number(str(args.get("page_size"))) if "page_size" in args else None
The reason I used casting to str is the fact that the args returning from the get function are of type unicode and not str or int. arg_to_number fails if the args is not of type str or int.

2021-11-04 09:39 UTC, eyalpalo commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.py
> +        'MaxItems': limit
Marker only marks the first object from which to start the response. if the user uses limit and marker I used the MaxItems to return only limit items starting the marker.

2021-11-15 10:38 UTC, dantavori reviewed
looks good to me, will approve after the demo

2021-11-22 15:16 UTC, dantavori approved these changes

2021-11-25 10:39 UTC, dantavori approved these changes

2021-11-25 10:39 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
> +      description: Number of results to display. Default value is 50.
```suggestion
      description: Number of results to display.
      defaultValue: '50'
```

2021-11-25 10:39 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
> +      description: Number of results to display. Default value is 50.
```suggestion
      description: Number of results to display.
      defaultValue: '50'
```

2021-11-25 10:39 UTC, dantavori commented on Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml
> +      description: Number of results to display. Default value is 50.
```suggestion
      description: Number of results to display.
      defaultValue: '50'
```

2021-11-25 13:45 UTC, merged