Lenel IAM
demisto/content pull request #15425
Opened 2021-10-21 17:12 UTC by dansterenson

Lenel IAM integration

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/38910

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-11-11 14:11 UTC, dansterenson commented
@dantavori Ready for review.

2021-11-29 17:44 UTC, dantavori requested changes
sorry for the late response (we recently reduced the high effort on IAM)
approving docs since it's based on the template.

2021-11-29 17:44 UTC, dantavori commented on Packs/Lenel/Integrations/LenelIAM/LenelIAM.yml
> +  defaultvalue: f71524e0-2b15-42b8-bb3d-34403695d417
```suggestion
```

2021-11-29 17:44 UTC, dantavori commented on Packs/Lenel/Integrations/LenelIAM/LenelIAM.yml
> +name: LenelIAM
```suggestion
display: Lenel IAM
name: Lenel IAM
```

2021-11-29 17:44 UTC, dantavori commented on Packs/Lenel/Integrations/LenelIAM/LenelIAM.yml
> +description: An Identity and Access Management integration template.
```suggestion
description: Integrate with Lenel services to perform Identity Lifecycle Management
  operations.
```

2021-11-29 17:44 UTC, dantavori commented on Packs/Lenel/Integrations/LenelIAM/README.md
> +An Identity and Access Management integration template.
```suggestion
Integrate with Lenel services to perform Identity Lifecycle Management operations.
```

2021-11-29 17:44 UTC, dantavori commented on Packs/Lenel/Integrations/LenelIAM/README.md
> +#### Human Readable Output
please add outputs (also in other commands)

2021-11-29 17:44 UTC, dantavori commented on Packs/Lenel/pack_metadata.json
> +    "description": "LS OpenAccess service that can be used to manage",
```suggestion
    "description": "Integrate with Lenel services to perform Identity Lifecycle Management operations.",
```

2022-04-03 13:05 UTC, closed without merging