support for setting custom User Agent added
demisto/content pull request #15487
Opened 2021-10-26 14:49 UTC by rozie

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added support for setting custom User Agent for whole integration (defined by API key) and for single requests.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-01 07:56 UTC, ShacharKidor commented
Hi @rozie , we appreciate your effort on contributing to the XSOAR marketplace. Due to excessive amount of contributions in our queue, it may take us a bit more time than usual to review this pull request, we appreciate your patience.

2021-11-08 14:07 UTC, ShacharKidor requested changes
Good Job!
@rozie - Thank you for contributing. 

In order to complete your contribution, It would be great if you'll update the README.md file of the integration with the new argument. 
The sections that should be updated are: 
* Configuration section at the beginning of the readme file. 
* The following commands: 'urlscan-submit' and 'url'.

Apologies again for the delay in review, please let me know if you need any help.

2021-11-08 15:47 UTC, rozie commented
Hi,
no problem with delay. :)
README.md updated. Let me know if this is enough.

2021-11-08 15:53 UTC, ShacharKidor commented
> Hi, no problem with delay. :) README.md updated. Let me know if this is enough.

@rozie - Hi thank you :) saw your updates.
You missed the 'Configure urlscan.io on Cortex XSOAR section' of the readme file - Please add the new parameter to there as well.

2021-11-08 16:47 UTC, rozie commented
Done. :)

2021-11-09 10:36 UTC, ShacharKidor commented
> Done. :)

@rozie - great!
Are you available for a quick demo before merging PR? Let's schedule

In addition - Please add Release notes describing the change you added, by using the demisto-sdk update-release-notes command.
For more information see [release-notes](https://xsoar.pan.dev/docs/documentation/release-notesl)

Please let me know if you need any help :)

2021-11-11 17:35 UTC, ShacharKidor commented
@rozie - You can also grant me permissions to your branch and I'll add the Release notes for you. 
Please see [inviting-collaborators-to-a-personal-repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-u[…]-repositories/inviting-collaborators-to-a-personal-repository)

2021-11-14 07:14 UTC, rozie commented
@ShacharKidor Trying to reach you at Slack. I'm having a little problem with adding Release notes myself and I'd like to solve it for the future.

2021-11-14 09:00 UTC, ShacharKidor commented
> @ShacharKidor Trying to reach you at Slack. I'm having a little problem with adding Release notes myself and I'd like to solve it for the future.

I'll be happy to help - Let's schedule a zoom meeting.

2021-11-15 07:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=15487) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=15487) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rozie<br/>:x: cWVwcG8gc3R5bGUg<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=15487) it.</sub>

2021-11-15 10:18 UTC, ShacharKidor requested changes

2021-11-15 10:18 UTC, ShacharKidor commented on Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
> +      description: User agent to perform request
```suggestion
    - default: false
      isArray: false
      name: useragent
      description: User agent to perform request
      required: false
      secret: false
```
I added it just to keep the structure of the existing arguments

2021-11-15 10:18 UTC, ShacharKidor commented on Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
> +      description: User agent to perform request
```suggestion
    - default: false
      isArray: false
      name: useragent
      description: User agent to perform request
      required: false
      secret: false
```
I added it just to keep the structure of the existing arguments

2021-11-15 10:18 UTC, ShacharKidor commented on Packs/UrlScan/ReleaseNotes/1_1_13.md
> +- Support for setting custom User Agent added
```suggestion
- Added a **useragent** parameter which enables setting a custom user agent used during scans with the integration.
- Added a **useragent** argument to ***urlscan-submit*** and ***url*** commands, which enables setting a custom user agent for scans which are performed using those commands. 
```

2021-11-15 12:23 UTC, ShacharKidor approved these changes

2021-11-15 12:24 UTC, merged