Added C2 Attribution Commands
demisto/content pull request #15481
Opened 2021-10-26 09:00 UTC by RamboV

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-01 07:21 UTC, ShacharKidor commented
Hi @RamboV , we appreciate your effort on contributing to the XSOAR marketplace. Due to excessive amount of contributions in our queue, it may take us a bit more time than usual to review this pull request, we appreciate your patience.

In the meanwhile:
Please fill in the contribution form -
> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @ShacharKidor will know he can start review the proposed changes.

2021-11-08 18:43 UTC, ShacharKidor requested changes
Great Work!
@RamboV - Thank you for contributing. 

In order to complete your contribution: 
1. Please see my minor comments below. 
2. It would be great if you'll add the new command (get-c2attribution-records-by-indicator) to the test-playbook (Playbook-HYASInsight-Test.yml) as well. 

Please let me know if you need any help.

2021-11-08 18:43 UTC, ShacharKidor commented on Packs/HYASInsight/Integrations/HYASInsight/README.md
>  ```!hyas-get-whois-records-by-indicator indicator_type="domain" indicator_value="domain.net" limit="3"```
I'm not sure why the context example and Human Readable Output of 'hyas-get-whois-records-by-indicator' command was removed. was it on purpose?

2021-11-08 18:43 UTC, ShacharKidor commented on Packs/HYASInsight/Integrations/HYASInsight/README.md
> +| HYAS.HASH-IP.ips | Unknown | Associated IPS  for the provided MD5 value |
```suggestion
| HYAS.HASH-IP.ips | Unknown | Associated IPS for the provided MD5 value | 
```

2021-11-08 18:43 UTC, ShacharKidor commented on Packs/HYASInsight/Integrations/HYASInsight/README.md
> +>**No entries.**
Would be better to provide an example with existing Human Readable Output entries.

2021-11-08 18:43 UTC, ShacharKidor commented on Packs/HYASInsight/Integrations/HYASInsight/README.md
> +>**No entries.**
Would be better to provide an example with existing Human Readable Output entries.

2021-11-08 18:43 UTC, ShacharKidor commented on Packs/HYASInsight/ReleaseNotes/1_0_3.md
> +- Added C2 Attribution Command.
```suggestion
- Added the ***hyas-get-c2attribution-records-by-indicator*** Command.
```

2021-11-08 18:43 UTC, ShacharKidor commented on Packs/HYASInsight/ReleaseNotes/1_0_3.md
> +##### HYAS Insight
I recommend that you add a section that describes the changes you made related to WHOIS commands (URL and endpoint updates).

2021-11-08 18:43 UTC, ShacharKidor commented on Packs/HYASInsight/pack_metadata.json
> +    "description": "Use the HYAS Insight integration to interactively lookup PassiveDNS, DynamicDNS, WHOIS, Malware and C2 Information – either as playbook tasks or through API calls in the War Room.
```suggestion
    "description": "Use the HYAS Insight integration to interactively lookup PassiveDNS, DynamicDNS, WHOIS, Malware and C2 Attribution Information – either as playbook tasks or through API calls in the War Room.",
```

2021-11-09 10:27 UTC, RamboV commented
> Great Work! @RamboV - Thank you for contributing.
> 
> In order to complete your contribution:
> 
> 1. Please see my minor comments below.
> 2. It would be great if you'll add the new command (get-c2attribution-records-by-indicator) to the test-playbook (Playbook-HYASInsight-Test.yml) as well.
> 
> Please let me know if you need any help.

Hi @ShacharKidor , Thanks for the Feedback.
I have attended to the changes according to your suggestions, please review and provide your feedback.

1. The "get-c2attribution-records-by-indicator" command has already been integrated into the test-playbook.
2. Modified the code change for the limit parameter as suggested in the HyasInsight.py file.
3. Added "outputs_key_field" value as suggested.
4. Added context example and Human Readable Output for 'hyas-get-whois-records-by-indicator'.
5. Removed space for "Associated IPS  for the provided MD5 value" string in the Readme
6. Added context example and Human Readable Output for both "hyas-get-associated-ips-by-hash" and "hyas-get-associated-domains-by-hash" commands
7. Modified "ReleaseNotes/1_0_3.md" as suggested

2021-11-09 13:35 UTC, ShacharKidor commented
@RamboV - Thank you for your updates. 
One last change - please run the **demisto-sdk fromat** command on the integration's test-playbook you edited, and push the test-playbook again with the changes applied by format command.
For more information please see: [demisto-sdk format](https://xsoar.pan.dev/docs/concepts/demisto-sdk#format)

2021-11-09 14:00 UTC, RamboV commented
> @RamboV - Thank you for your updates. One last change - please run the **demisto-sdk fromat** command on the integration's test-playbook you edited, and push the test-playbook again with the changes applied by format command. For more information please see: [demisto-sdk format](https://xsoar.pan.dev/docs/concepts/demisto-sdk#format)

Hi @ShacharKidor ,
Ran the command as suggested, please review.
Thanks.

2021-11-09 15:10 UTC, ShacharKidor commented
> Hi @ShacharKidor ,
> Ran the command as suggested, please review.
> Thanks.

@RamboV - Great! let's schedule a demo. 
I sent you an invitation for a zoom meeting via email, for tomorrow at noon.
Let me know if this is a good time for you.

2021-11-09 15:12 UTC, RamboV commented
> > Hi @ShacharKidor ,
> > Ran the command as suggested, please review.
> > Thanks.
> 
> @RamboV - Great! let's schedule a demo. I sent you an invitation for a zoom meeting via email, for tomorrow at noon. Let me know if this is a good time for you.

@ShacharKidor Sure that works. Accepted the invitation.

2021-11-10 10:18 UTC, ShacharKidor approved these changes

2021-11-10 10:18 UTC, merged