Update README.md
demisto/content pull request #15551
Opened 2021-10-28 20:09 UTC by nericksen

The example seems to contain a field that is no longer relevant/available for updating custom fields

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-01 08:04 UTC, ShacharKidor commented
Hi @nericksen, we appreciate your effort on contributing to the XSOAR marketplace. Due to excessive amount of contributions in our queue, it may take us a bit more time than usual to review this pull request, we appreciate your patience.

2021-11-07 16:20 UTC, ShacharKidor requested changes
Hi @nericksen, 
Thank you for contributing!

I sent you a message on slack to discuss the change you added.

2021-11-07 16:20 UTC, ShacharKidor commented on Packs/Jira/Integrations/JiraV2/README.md
>  ##### Command Example
Not sure why this change is needed? Can you please explain?

2021-11-07 16:38 UTC, ShacharKidor commented on Packs/Jira/Integrations/JiraV2/README.md
> +```!jira-edit-issue issueId=DEM-4921 issueJson={"fields":{"customfield_100": "testing3"}}```
```suggestion
```!jira-edit-issue issueId=DEM-4921 issueJson=`{"fields":{"description":"testing3"}}````
```

2021-11-08 21:01 UTC, nericksen commented
@ShacharKidor ShacharKidor as discussed offline, changes have now been pushed. Let me know if anything else is needed. Thanks again for the feedback!

2021-11-09 11:03 UTC, ShacharKidor commented
> @ShacharKidor ShacharKidor as discussed offline, changes have now been pushed. Let me know if anything else is needed. Thanks again for the feedback!

@nericksen - Thank you for pushing the changes, I'll merge your PR.

2021-11-09 11:03 UTC, ShacharKidor approved these changes

2021-11-09 11:10 UTC, merged