BaseClient class - fixed a bug when choosing xml as resp_type
demisto/content pull request #15588
Opened 2021-11-02 10:06 UTC by 18AX

_http_request function is using ET.parse() (which take a file as parameter and not a string) instead of using ET.fromstring().

2021-11-02 10:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=15588) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=15588) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=15588) it.</sub>

2021-11-04 08:16 UTC, iyeshaya requested changes
Please add release notes as requested in [here](https://app.circleci.com/pipelines/github/demisto/content/123834/workflows/8e7993fe-0eed-424c-aa03-23192b6405d2/jobs/441487).

2021-11-04 10:01 UTC, 18AX commented
> Please add release notes as requested in [here](https://app.circleci.com/pipelines/github/demisto/content/123834/workflows/8e7993fe-0eed-424c-aa03-23192b6405d2/jobs/441487).

It's done

2021-11-07 10:25 UTC, iyeshaya requested changes

2021-11-07 10:25 UTC, iyeshaya commented on Packs/Base/ReleaseNotes/1_14_1.md
> +    - Fixed a bug in BaseClient class when choosing xml as resp_type which raised a python exception.
```suggestion
- Fixed a bug in BaseClient class when choosing xml as resp_type which raised a python exception.
```

2021-11-08 10:40 UTC, iyeshaya approved these changes

2021-11-08 10:43 UTC, merged