Jira Add Authentication
demisto/content pull request #15618
Opened 2021-11-04 09:00 UTC by JasBeilin

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/42472

## Description
Added authentication using PAT

## Does it break backward compatibility?

   - [x] No

## Must have
- [x] Documentation

2021-11-04 11:30 UTC, yuvalbenshalom requested changes
see my comments

2021-11-04 11:30 UTC, yuvalbenshalom commented on Packs/Jira/Integrations/JiraV2/JiraV2_description.md
> +To use Private Access Token, follow [this tutorial](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) to get Access Tokens. Authorizing using PAT requires Acce
```suggestion
To use Private Access Token, follow [this tutorial](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) to get Access Tokens. Authorizing using PAT requires Access Token only.
Insert the generated token in the Access Token field.
```

2021-11-04 11:30 UTC, yuvalbenshalom commented on Packs/Jira/Integrations/JiraV2/JiraV2.py
> +        HEADERS.update({'Authorization': f'Bearer {access_token}'})
```suggestion
        #Personal Access Token Authentication
        HEADERS.update({'Authorization': f'Bearer {access_token}'})
```

2021-11-04 13:49 UTC, yuvalbenshalom approved these changes

2021-11-07 20:19 UTC, anara123 commented on Packs/Jira/Integrations/JiraV2/JiraV2.py
> +        # Personal Access Token Authentication
please add unit test

2021-11-10 07:35 UTC, JasBeilin commented
@amshamah419 , can you please review the docs and make sure it's clear?

2021-11-10 11:42 UTC, amshamah419 reviewed
See docs changes

2021-11-10 11:42 UTC, amshamah419 commented on Packs/Jira/Integrations/JiraV2/JiraV2.yml
> +  additionalinfo: If other required field are not provided (both Access Token and Private Key), will be ignored.
```suggestion
  additionalinfo: Will be ignored if other required fields are not provided (for example both the Access Token and the Private Key).
```

2021-11-10 11:42 UTC, amshamah419 commented on Packs/Jira/Integrations/JiraV2/JiraV2_description.md
> +To use Private Access Token, follow [this tutorial](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) to get Access Tokens. Authorizing using PAT requires Acce
```suggestion
To use a Private Access Token, please follow [this tutorial](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) to obtain your Access Tokens. Authorizing using a PAT requires the Access Token only.
```

2021-11-10 11:42 UTC, amshamah419 commented on Packs/Jira/Integrations/JiraV2/JiraV2_description.md
> +Insert the generated token in the Access Token field.
```suggestion
Insert the generated token in the `Access Token` field.
```

2021-11-10 11:42 UTC, amshamah419 commented on Packs/Jira/Integrations/JiraV2/README.md
> +    | Consumer key (OAuth 1.0) | If other required field are not provided (both Access Token and Private Key), will be ignored. | False |
```suggestion
    | Consumer key (OAuth 1.0) | Will be ignored if other required fields are not provided (for example both the Access Token and the Private Key). | False |
```

2021-11-10 11:42 UTC, amshamah419 commented on Packs/Jira/ReleaseNotes/1_3_9.md
> +- Added *Personal Access Token* Authentication method.
```suggestion
- Added the *Personal Access Token* Authentication method.
```

2021-11-10 16:17 UTC, merged