Syslog rewrite
demisto/content pull request #15716
Opened 2021-11-11 07:27 UTC by tomneeman151293

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-16 08:33 UTC, tomneeman151293 commented
Validations are failing on:
- Missing TPB - the integration only implements long-running-execution so I didnt implement one
- using dev docker image - after this PR will be approved, i will merge my dockerfile PR https://github.com/demisto/dockerfiles/pull/6358, and those validations will pass

2021-11-21 11:33 UTC, dantavori requested changes
🥇

2021-11-21 11:33 UTC, dantavori commented on Packs/Syslog/Integrations/Syslogv2/Syslogv2.py
> +            fetch_samples()
when exactly is this happening? let's document and briefly explain the sampling logic

2021-11-21 11:33 UTC, dantavori commented on Packs/Syslog/Integrations/Syslogv2/Syslogv2.py
> +    return {k: transfer_type_to_str_type(v) for k, v in get_type_hints(SyslogMessageExtract).items()}
nice impl, but better to provide the field description in the values of the dict, or which is used in which format. you can do it hard-coded.

2021-11-21 13:08 UTC, tomneeman151293 commented on Packs/Syslog/Integrations/Syslogv2/Syslogv2_description.md
> +- If no message regex is given. Incident will be created for each received Syslog message.
yeah, shouldn't be any issue, as the only problem is where the long-running needs to be configured on a single IP (in load balancing the IP might change so the server might not listen to the port in the expected IP

2021-11-22 08:18 UTC, tomneeman151293 commented on Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
> +  - RFC3164
https://stackoverflow.com/questions/69985784/syslog-rfc5424-vs-rfc6587

2021-11-22 08:19 UTC, tomneeman151293 commented on Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
> +  dockerimage: devdemisto/syslog:1.0.0.24366
leaving it as dev until dockerfiles pr is merged

2021-11-22 08:22 UTC, tomneeman151293 commented on Packs/Syslog/Integrations/Syslogv2/Syslogv2.py
> +    incident_type: Optional[str] = params.get('incident_type')
i will delete

2021-11-23 13:52 UTC, dantavori reviewed
will approve after the demo.
try to think how we can test it in a TPB

2021-11-23 13:52 UTC, dantavori commented on Packs/Syslog/Integrations/Syslogv2/Syslogv2_description.md
> +- Select the **Log Format** used by the Syslog server.
```suggestion
```

2021-11-29 08:43 UTC, tomneeman151293 commented
@dantavori Updated docker image to prod image

2021-11-29 16:01 UTC, dantavori approved these changes
looks good 👍 please open an issue about the test playbook as we discussed

2021-11-30 07:33 UTC, tomneeman151293 commented
@dantavori  https://github.com/demisto/etc/issues/44245

2021-11-30 09:21 UTC, tomneeman151293 commented
@Itay4 need to force merge as we dont have a TPB for this integration.

2021-12-09 09:44 UTC, tomneeman151293 commented
@Itay4 Force merge is required. Validation is failing on missing TPB. A separate issue was created to find a dedicated instance to syslog TPB to be developed in the future

demisto/etc#44245

2021-12-13 15:23 UTC, Itay4 commented
merging due to the above

2021-12-13 15:24 UTC, merged