Cisco threat grid
demisto/content pull request #15806
Opened 2021-11-16 14:31 UTC by eyalpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/40156)

## Description
Created relationships using EntityRelationship, changed pack name to _Cisco Secure Malware Analytics_.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-18 15:06 UTC, dantavori requested changes

2021-11-23 11:28 UTC, dantavori approved these changes

2021-11-23 11:28 UTC, dantavori commented on Packs/ThreatGrid/ReleaseNotes/1_2_9.md
> +- Added **Create relationships** checkbox to integration params.
```suggestion
- Added relations of *sample_sha1* and *sample_md5* indicator types to the domain.
- Added the *Create relationships* boolean parameter.
- Updated the docker image to *demisto/python3:3.9.8.24399*.
```

2021-11-23 15:02 UTC, Itay4 commented
build fails on skipped test due to missing instance
merging

2021-11-23 15:02 UTC, merged