Mattermost ask user command fix
demisto/content pull request #15914
Opened 2021-11-22 16:58 UTC by dansterenson

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://github.com/demisto/content/pull/15752)

## Description
We replaced the 'mattermost-send' command in Mattermost (server integration) which is deprecated with the 'send-notification' command. The 'send-notification' command was checked with @ali-sawyer and seems to work fine.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2021-11-22 16:59 UTC, dansterenson commented on Packs/Mattermost/Scripts/script-MattermostAskUser.yml
> +      'ignoreAddURL': 'true',
This is not a mistake, it should be ignoreAddURL instead of IgnoreAddURL

2021-11-23 11:07 UTC, dantavori requested changes
1. Is this considered breaking changes? if so, please use the -bc flag for the update-release-notes command.
2. Please update the change in the readme file as well.

2021-11-23 11:07 UTC, dantavori commented on Packs/Mattermost/Scripts/MattermostAskUser/MattermostAskUser.yml
> +name: MattermostAskUserTest
don't forget to remove the "test" suffix

2021-11-23 11:07 UTC, dantavori commented on Packs/Mattermost/ReleaseNotes/1_0_3.md
> +- changed script to use ***send-notification*** command instead of the deprecated ***mattermost-send*** command.
```suggestion
- Updated the script to use the ***send-notification*** command instead of the deprecated ***mattermost-send*** command.
```

2021-11-24 08:08 UTC, dantavori approved these changes
nice
need to force merge (no TPB)

2021-11-24 08:08 UTC, dantavori commented on Packs/Mattermost/ReleaseNotes/1_0_3.md
> +##### New: MattermostAskUser
```suggestion
##### MattermostAskUser
```

2021-11-28 11:36 UTC, merged