Email communication notes bug
demisto/content pull request #15975
Opened 2021-11-24 15:52 UTC by yucohen

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/43291

## Description
Changed attachment check so it wont happen for every note.

## Screenshots
![image](https://user-images.githubusercontent.com/86777474/143271284-15b258cd-2fda-4b71-9ad9-cfd118543fc5.png)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-24 18:03 UTC, reutshal requested changes
Nice

2021-11-24 18:03 UTC, reutshal commented on Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
> +            reply_body += f'Attachments: {attachment_names}\n\n'
Lets save this as a string and add it to the reply_body where the old attachments were added so we will keep the same order.

2021-11-25 09:30 UTC, Bargenish requested changes

2021-11-25 09:30 UTC, Bargenish commented on Packs/EmailCommunication/ReleaseNotes/1_4_2.md
> +- Fixed an issue where attachments in the layout where being attached to each one of the notes.
```suggestion
- Fixed an issue where attachments in the layout were being attached to each one of the notes. 
```

2021-11-25 09:30 UTC, Bargenish commented on Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
> +def test_get_reply_body(mocker, notes, attachments, expected_results):
Please dd `Given When Then`
Also, you have only one case here so using `parametrize` is redundant, let's add a case where no attachments were added as well.

2021-12-07 14:00 UTC, closed without merging