Add away users functionality shift management
demisto/content pull request #15982
Opened 2021-11-25 08:39 UTC by tomneeman151293

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-11-28 07:58 UTC, tomneeman151293 commented
Validations are failing on missing TPB for other scripts
for the script I added, GetAwayUsers, There is no way for me to update Away status automatically, so it cannot be tested as well.

see
https://github.com/demisto/etc/issues/44224

2021-11-29 17:00 UTC, dantavori requested changes
very nice, please check it also on a 6.2 server to make sure nothing is broken.
regarding the validation errors, got it, we will force merge this PR

2021-12-02 12:15 UTC, bakatzir reviewed
I would love to see a short demo of this, if possible. this should not affect/delay the review and merge process.

2021-12-05 11:20 UTC, tomneeman151293 commented on Packs/ShiftManagement/Scripts/AssignToNextShiftOOO/AssignToNextShiftOOO.yml
> +runas: DBotRole
I had a validation failure, thats why I added it. I can investigate further if you want

2021-12-08 07:57 UTC, tomneeman151293 commented on Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall_test.py
> +AWAY_USERS = [{'Type': 1, 'Contents': [{'username': 'batman'}]}]
Fixed

2021-12-14 13:36 UTC, tomneeman151293 commented
@dantavori Anything needed here from my side apart from @bakatzir quick demo later on?

2021-12-14 13:41 UTC, dantavori approved these changes

2021-12-14 13:41 UTC, dantavori commented on Packs/ShiftManagement/Scripts/GetAwayUsers/README.md
> +| CortexXSOAR.AwayUsers.email | Away user email. | Unknown |
please regenerate readme

2021-12-26 11:11 UTC, tomneeman151293 commented
Had a short demo with @bakatzir , Approve whenever you can :)

2021-12-26 11:22 UTC, bakatzir approved these changes
Please review briefly the widgets using the changed scripts(In the `ShiftManagement` pack) and make sure they look OK after the changes, before merging.

2021-12-26 13:12 UTC, tomneeman151293 commented
@Itay4 
Can we force merge this?
failed validation
Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/AssignAnalystToIncidentOOO.yml - [CJ105]
Due to a small addition i made to this script.

2021-12-26 13:35 UTC, Itay4 commented
> @Itay4 Can we force merge this? failed validation Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/AssignAnalystToIncidentOOO.yml - [CJ105] Due to a small addition i made to this script.

as discussed, lets add unit test please

2021-12-26 14:06 UTC, tomneeman151293 commented
@Itay4 Unit tests added, 80% coverage

2021-12-26 14:48 UTC, merged