Email communication image bug
demisto/content pull request #16045
Opened 2021-11-30 15:19 UTC by yucohen

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/43288

## Description
Inline images were not shown in email HTML layout. I changed the attachment handling in MSGraphMail, changed displayEmailHtml and also added attachment handling in preProcessEmail

## Screenshots
![image](https://user-images.githubusercontent.com/86777474/144074733-43ce1ef0-28fb-48ce-937e-5cf0de954448.png)
![image](https://user-images.githubusercontent.com/86777474/144074772-312a5131-2656-432e-9225-e959f86a17db.png)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation

2021-12-07 10:50 UTC, Bargenish requested changes
Nice work

* Add an RN and bump version for the `MicrosoftGraphListener` pack.
* Add a comment in the PreprocessEmail script in the  `get_attachments_using_instance` that attachments are downloaded by default when emails are fetched using the graph integrations.
* Add tests to the PreProcessEmail changes

2021-12-07 13:31 UTC, reutshal approved these changes
Nice job 🚀

2021-12-07 13:31 UTC, reutshal commented on Packs/MicrosoftGraphListener/ReleaseNotes/1_0_21.md
> +- Fixed an issue where inline images were not getting into attachments list.
Lets be more specific here - please mention the scope when this happens -command/use case

2021-12-07 13:31 UTC, reutshal commented on Packs/MicrosoftGraphMail/ReleaseNotes/1_1_4.md
> +- Fixed an issue where inline images were not getting into attachments list.
same here

2021-12-08 12:09 UTC, Bargenish approved these changes

2021-12-09 08:25 UTC, merged