Fix remedy on demand fetch error
demisto/content pull request #16160
Opened 2021-12-06 10:10 UTC by MosheEichler

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/43926

## Description
Fixed the query of fetch incidents

2021-12-06 11:52 UTC, reutshal approved these changes

2021-12-13 13:12 UTC, amshamah419 commented on Packs/Remedy-On-Demand/ReleaseNotes/1_0_3.md
> +- Fixed an issue with the query of ***fetch-incidents***.
```suggestion
- Fixed an issue where the query of the ***fetch-incidents*** command was not formatted correctly.
```

2021-12-16 09:24 UTC, reutshal commented
@MosheEichler When was the call scheduled? we are waiting on this or we are sure about the fix?

2021-12-16 10:45 UTC, MosheEichler commented
We are sure about the fix (as the customerד mentioned in the [issue](https://github.com/demisto/etc/issues/43926#issuecomment-985834668) that the fetch works now)
But we are waiting for a call with the customers about duplicates in fetch incidents (could be related to the fix)
So let's wait with the merge of this pr untill call with the customers

2021-12-23 09:34 UTC, reutshal requested changes

2021-12-23 09:34 UTC, reutshal commented on Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
> +    logDebug("This is the lastrun value before starting to fetch: "+lastRun.value);
```suggestion
    logDebug("Last run value before starting to fetch: "+lastRun.value);
```

2021-12-23 09:34 UTC, reutshal commented on Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
> +    logDebug("it's the time now after the fetch, it's saved for the next fetch: "+now);
```suggestion
    logDebug("Last run is set to: "+now);
```

2021-12-23 09:34 UTC, reutshal commented on Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
> +    var url = baseUrl + '/api/arsys/v1/entry/HPD:IncidentInterface/' + '?q=' + query;
Why did we remove the encoding to the query?

2022-01-06 09:21 UTC, reutshal approved these changes

2022-01-06 09:21 UTC, reutshal commented on Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
> +    logDebug("This is the URL with the query for fetching the incidents: "+url);
```suggestion
    logDebug("This is the URL with the query for fetching the incidents: " + url);
```

2022-01-06 09:21 UTC, reutshal commented on Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
> +    logDebug("Last run value before starting to fetch: "+lastRun.value);
```suggestion
    logDebug("Last run value before starting to fetch: " + lastRun.value);
```

2022-01-06 09:21 UTC, reutshal commented on Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
> +    logDebug("Last run is set to: "+now);
```suggestion
    logDebug("Last run is set to: " + now);
```

2022-01-06 10:39 UTC, merged