Azure key vault integration fix microsft api module
demisto/content pull request #16251
Opened 2021-12-09 09:23 UTC by OfekMQmasters

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-12-13 10:08 UTC, Bargenish reviewed
nice work
See my comments below

@guykeller need to add an alternative auth method (using device-code/add a XSOAR application).

2021-12-13 10:08 UTC, Bargenish commented on Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
> +            data['resource'] = resource if resource else self.resource  # type: ignore
```suggestion
            data['resource'] = resource or self.resource  # type: ignore
```

2021-12-13 10:08 UTC, Bargenish commented on Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
> +            if self.multi_resource:
Please add a unit test

2021-12-14 10:49 UTC, OfekMQmasters commented on Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
> +            data['resource'] = resource if resource else self.resource  # type: ignore
Done.

2021-12-14 10:49 UTC, OfekMQmasters commented on Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
> +            if self.multi_resource:
Added.

2021-12-14 10:53 UTC, OfekMQmasters commented
1. I made the requested changes and added the relevant unit test. 
2. Regarding the device flow - in the first demo with Arseny and Meital we decided not to use the device flow as 
authorization in this integration, since the integration uses multiple scopes - https://vault.azure.net ( for keys, secrets and certificates commands) and https://management.azure.com for Key Vault commands, but the authorization with device flow can use only one of them. @Bargenish @guykeller

2021-12-19 11:35 UTC, bakatzir commented
related: https://github.com/demisto/etc/issues/36247

2022-01-16 16:00 UTC, guykeller requested changes

2022-01-17 07:31 UTC, OfekMQmasters commented on Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.py
> +        # fetch_credentials(client,[''],[''],'xsoar-test-vault/test-sec-1')
Here we verify:
1. That the client has access token for each resource.
2. Making an API request for listing key vaults (validating that a request does work).
In second thought, the first point should be enough. In addition, the commented out line should be deleted.
Let me know if anything else is missing and if do you approve my suggestion here.

2022-01-18 13:10 UTC, guykeller approved these changes

2022-01-18 13:10 UTC, merged