Qradar create query and hunting
demisto/content pull request #16266
Opened 2021-12-09 12:57 UTC by David-BMS

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/42493

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-12-14 13:23 UTC, ShirleyDenkberg commented
@michalgold Doc review completed.

2022-07-04 12:03 UTC, idovandijk commented on Packs/QRadar/ReleaseNotes/2_2_1.md
> +- This playbook is used to to sort the QRadar search results to display the IP addresses, assets and usernames that the search provided. In addition results allow to to differentiate between internal
fix "to to" (mistake appears twice)

2022-07-04 12:19 UTC, idovandijk requested changes
* `QRadar Build Query and Search` - this playbook seems good :)
* `QRadar Get Hunting Results` - Fix logical issue, also uses "qradar-get-assets" which is deprecated
* Update playbook image + readme and fix
* Fix RN comment
* Fix fromversion to 6.2

2022-07-05 13:52 UTC, idovandijk approved these changes
Add documentation to `base_field_match` to say that it makes one of the optional fields mandatory, other than this - good to go :)

2022-07-07 14:58 UTC, merged