CVE Search v2 - Fixed an issue where cvss score is null
demisto/content pull request #16412
Opened 2021-12-16 09:08 UTC by ChanochShayner

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/44839

## Description
Fixed an issue where the cvss score is null.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2021-12-28 16:39 UTC, guykeller approved these changes
Please see my note

2021-12-28 16:39 UTC, guykeller commented on Packs/CVESearch/Integrations/CVESearchV2/CVESearchV2.py
> +        'CVSS': cvss if cvss else 'N\\A',
```suggestion
        'CVSS': cvss or 'N\\A',
```

2021-12-28 16:41 UTC, guykeller requested changes

2021-12-28 16:41 UTC, guykeller commented on Packs/CVESearch/ReleaseNotes/1_0_11.md
> +- Fixed an issue where the CVSS score is null.
```suggestion
- Fixed an issue where a null CVSS score was handled poorly.
```

2021-12-29 07:47 UTC, ChanochShayner commented on Packs/CVESearch/Integrations/CVESearchV2/CVESearchV2.py
> +        'CVSS': cvss if cvss else 'N\\A',
done

2021-12-29 07:47 UTC, ChanochShayner commented on Packs/CVESearch/ReleaseNotes/1_0_11.md
> +- Fixed an issue where the CVSS score is null.
done

2021-12-30 11:25 UTC, guykeller approved these changes

2021-12-30 11:26 UTC, guykeller commented
@ChanochShayner You can ignore the RN test. Approved by me.

2021-12-30 11:58 UTC, merged