BaseClient - support setting baseclient http read timeout via env var
demisto/content pull request #16500
Opened 2021-12-19 16:36 UTC by Itay4

## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/37569

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests

2021-12-19 20:18 UTC, anara123 approved these changes

2021-12-20 06:37 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +                    timeout=(10, timeout),
I would leave this as it was instead of hardcoding the 10. It will lead to edge cases.

2021-12-20 06:38 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +            self.timeout = float(os.environ.get('REQUESTS_TIMEOUT.' + get_integration_name(), '')[:-1] or os.environ.get('REQUESTS_TIMEOUT', '')[:-1] or self.REQUESTS_TIMEOUT)  # noqa: E501
Add the timeout to the constructor too, so integrations that implement a param for controlling timeout can pass this in.

2021-12-20 06:40 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +                          params=None, data=None, files=None, timeout=REQUESTS_TIMEOUT, resp_type='json', ok_codes=None,
Set to None by default. If it is None, then use self.timeout. That way integration can override the value for specific cases.

2021-12-20 06:46 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +            self.timeout = float(os.environ.get('REQUESTS_TIMEOUT.' + get_integration_name(), '')[:-1] or os.environ.get('REQUESTS_TIMEOUT', '')[:-1] or self.REQUESTS_TIMEOUT)  # noqa: E501
Small cleanup use `os.getenv` so it is consistent with our other code sections that lookup env vars.

2021-12-20 06:49 UTC, glicht requested changes

2021-12-20 06:49 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +            self.timeout = float(os.environ.get('REQUESTS_TIMEOUT.' + get_integration_name(), '')[:-1] or os.environ.get('REQUESTS_TIMEOUT', '')[:-1] or self.REQUESTS_TIMEOUT)  # noqa: E501
Also, not clear why you have `[:-1]`? It is removing the last char

2021-12-20 07:04 UTC, glicht commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +            self.timeout = float(os.environ.get('REQUESTS_TIMEOUT.' + get_integration_name(), '')[:-1] or os.environ.get('REQUESTS_TIMEOUT', '')[:-1] or self.REQUESTS_TIMEOUT)  # noqa: E501
We should also support scripts that may use the client. So maybe modify `get_integration_name` or create a new function that works with scripts. For scripts we need: `context.ScriptName`

2021-12-22 00:11 UTC, glicht approved these changes

2021-12-28 18:32 UTC, Itay4 commented
lint fails on `context deadline exceeded` 

lint on base pack passed:
```
#########
 Summary 
#########
Packages: 26
Packages PASS: 26
```

2021-12-28 18:32 UTC, merged