adopt vmray pack
demisto/content pull request #16556
Opened 2021-12-21 13:11 UTC by jthom-vmray

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Adopt VMRay pack.

## Minimum version of Cortex XSOAR
- [x ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [x ] Tests
- [x ] Documentation

2021-12-21 13:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=16556) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=16556) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=16556) it.</sub>

2021-12-21 17:07 UTC, mchasepan commented on Packs/VMRay/pack_metadata.json
>      "author": "Cortex XSOAR",
```suggestion
    "author": "VMRay",
```

2021-12-21 17:07 UTC, mchasepan commented on Packs/VMRay/pack_metadata.json
>      "name": "VMRay",
Do you want to call the pack `VMRay Analyzer`?

2021-12-21 17:07 UTC, mchasepan commented on Packs/VMRay/README.md
> +*Note: Support for this pack moved to the Partner on December, 21, 2021. Please contact the Partner directly via the support link on the right.*
This readme should have detailed content in it on pack value and your company (similar to the paid packs), please sync w Zac on your side for details.

2021-12-26 15:13 UTC, kgal-pan commented
@jthom-vmray - Please address build failure requesting to add an author image to `Packs/VMRay/Author_image.png`. See the [docs](https://xsoar.pan.dev/docs/packs/packs-format#author_imagepng) about the requirements of this image.

Also, please [sign the CLA agreement](https://cla-assistant.io/demisto/content?pullRequest=16556) as well and address @mchasepan's suggestions.

2022-01-05 16:19 UTC, kgal-pan commented on Packs/VMRay/README.md
> -*Note: Support for this pack will be moving to the partner around Oct 15, 2021.*
Add 
*Note: Support for this pack moved to the Partner on December, 21, 2021. Please contact the Partner directly via the support link on the right.*

2022-01-05 16:33 UTC, ostolero requested changes
Hey Thank you for making @mchasepan changes! Only two small changes that need your attention and then we can merge. :)

2022-01-05 16:33 UTC, ostolero commented on Packs/VMRay/ReleaseNotes/1_1_5.md
> +*Note: Support for this pack moved to the Partner on December, 21, 2021. Please contact the Partner directly via the support link on the right.*
Make this a bit clearer and shorter, full line can show in the readme as @kgal-pan suggested :)
```suggestion
- Support moved to partner on December 21, 2021
```

2022-01-06 08:34 UTC, ostolero approved these changes
Great! let's merge

2022-01-06 08:35 UTC, merged