fixed issue with v2 api not on user search
demisto/content pull request #16667
Opened 2021-12-27 14:16 UTC by giordyb

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Just a couple of changes to fix the issue on the *search_user* and *get_account_id_from_attribute* functions where the REST APIs used on the On-Prem version of Jira (Jira Server) differs from the one used in the cloud (v2 vs v3)
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X ] No

## Must have
- [ ] Tests
- [ ] Documentation

2021-12-27 14:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=16667) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=16667) before we can accept your contribution.<br/><hr/>**Giordano Bianchi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=16667) it.</sub>

2021-12-27 14:19 UTC, bakatzir commented
@yuvalbenshalom FYI for the on-prem/cloud API disparity, please consider reviewing.

2021-12-27 14:29 UTC, dorschw commented
Hi @giordyb, thanks for your contribution,
Please [sign the SLA](https://github.com/demisto/content/pull/16667#issuecomment-1001589510), and [add a unit test](https://xsoar.pan.dev/docs/integrations/code-conventions#unit-tests) for the change you applied in `jira_v2_test.py`.

2021-12-27 14:30 UTC, dorschw commented on Packs/Jira/ReleaseNotes/1_4_5.md
> +- %%UPDATE_RN%%
Please describe the change here, you can find more information [here](https://xsoar.pan.dev/docs/documentation/release-notes)

2021-12-27 15:29 UTC, giordyb commented
> Hi @giordyb, thanks for your contribution, Please [sign the SLA](https://github.com/demisto/content/pull/16667#issuecomment-1001589510), and [add a unit test](https://xsoar.pan.dev/docs/integrations/code-conventions#unit-tests) for the change you applied in `jira_v2_test.py`.

@dorschw I don't see any existing unit tests for the 2 functions I made changes to.

2021-12-27 16:50 UTC, dorschw commented
> > Hi @giordyb, thanks for your contribution, Please [sign the SLA](https://github.com/demisto/content/pull/16667#issuecomment-1001589510), and [add a unit test](https://xsoar.pan.dev/docs/integrations/code-conventions#unit-tests) for the change you applied in `jira_v2_test.py`.
> 
> @dorschw I don't see any existing unit tests for the 2 functions I made changes to.

You're right, thanks.

2021-12-28 09:29 UTC, giordyb commented
@dorschw FYI I made a mistake where my original commits got pushed with a different email address, that's why you see 2 committers. 
I thought I corrected the issue with a re-commit but it still shows the wrong committer. I already accepted the licensing agreement with the correct email address please let me know if this works for you or if you want me to re-submit.

2021-12-29 11:15 UTC, dorschw commented
> @dorschw FYI I made a mistake where my original commits got pushed with a different email address, that's why you see 2 committers. I thought I corrected the issue with a re-commit but it still shows the wrong committer. I already accepted the licensing agreement with the correct email address please let me know if this works for you or if you want me to re-submit.

thanks for the update, don't worry about it, we'll take care of it.

2021-12-30 17:40 UTC, yuvalbenshalom requested changes
@giordyb following our slack conversation, please remove the parameter `jira_v2_api` and instead add an argument "JIRAv2API" to `ira-get-id-by-attribute` and use it instead.
make this argument false by default.

2022-01-03 06:40 UTC, yuvalbenshalom approved these changes
approving the fix
@dorschw / @DeanArbel please see description and release notes if they need a some editing.

2022-01-03 07:23 UTC, DeanArbel commented
@yaron-libman Please assign someone from the technical writers team to review the new argument: `is_jirav2api`.
We should also add these changes to the pack `Readme.md` (if you have issues doing so, please update me, and I'll assist with it).

2022-01-03 07:36 UTC, DeanArbel requested changes
Thank you very much for this contribution. The PR is almost ready, and is mostly pending our technical writers team review.

Please note that you'll need to revert some changes you've committed to the integration parameters. I have collected the changes with a suggestion below.

2022-01-03 07:36 UTC, DeanArbel commented on Packs/Jira/Integrations/JiraV2/JiraV2.yml
> +- defaultvalue: "true"
Please revert - you can change to `false`.
```suggestion
- defaultvalue: "false"
```

2022-01-03 07:36 UTC, DeanArbel commented on Packs/Jira/Integrations/JiraV2/JiraV2.yml
> +  defaultvalue: "true"
Please revert - you can change it to `false`.

```suggestion
  defaultvalue: "false"
```

2022-01-03 07:36 UTC, DeanArbel commented on Packs/Jira/Integrations/JiraV2/JiraV2.yml
> +  defaultvalue: "true"
Please revert - you can change it to `false`.
```suggestion
  defaultvalue: "false"
```

2022-01-03 07:36 UTC, DeanArbel commented on Packs/Jira/Integrations/JiraV2/JiraV2.yml
> +  defaultvalue: "true"
Please revert - you can change it to `false`.
```suggestion
  defaultvalue: "false"
```

2022-01-03 17:28 UTC, giordyb commented
@DeanArbel I went ahead and reverted the changes to JiraV2.yaml and added only the changes necessary.

2022-01-04 12:42 UTC, julieschwartz18 commented
@DeanArbel - Doc review complete.

2022-01-05 11:21 UTC, DeanArbel approved these changes

2022-01-05 11:23 UTC, DeanArbel commented
@giordyb I have approved the PR, and will assist you in updating the readme.
The update to the pack should be available by tomorrow.

Thank you very much for your contribution!

2022-01-05 11:24 UTC, merged