Trigger contrib build
demisto/content pull request #16690
Opened 2021-12-28 17:00 UTC by merit-maita

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added the command gitlab-trigger-contribution-build to trigger a  contribution build in gitlab. 

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-03 10:43 UTC, yaakovi commented on Packs/DevSecOps/Integrations/GitLab/GitLab.py
> +    # M6RGF0YVZhdWx0Ojc5NjU1N2RmLTg5YzQtNGQ5Yi04YmNlLTljNTMwZWU1NjVjYTpSZWNvcmRJbmRleDo1OklzVHJ1bmNhdGVk
remove

2022-01-03 10:50 UTC, yaakovi requested changes
only looked at the integration changes

2022-01-03 10:50 UTC, yaakovi commented on Packs/DevSecOps/Integrations/GitLab/GitLab.py
> +            'gitlab-trigger-contribution-build': gitlab_trigger_contribution_build_command
```suggestion
            'gitlab-trigger-contribution-build': gitlab_trigger_contribution_build_command,
```

2022-01-03 10:50 UTC, yaakovi commented on Packs/DevSecOps/Integrations/GitLab/GitLab.py
> +    def trigger_contrib_build(self, base_branch: str, contrib_branch: str, pr_number: int, token: str):
no need to pass the token here, it is already part of the Client object

2022-01-03 10:50 UTC, yaakovi commented on Packs/DevSecOps/Integrations/GitLab/GitLab.py
> +        return self._http_request('post', url_suffix='projects/2596/trigger/pipeline', data=data, headers=headers)
the project ID should be an argument

2022-01-03 10:50 UTC, yaakovi commented on Packs/DevSecOps/Integrations/GitLab/GitLab.py
> +            'variables[CI_PIPELINE_SOURCE]': 'contrib'
both argument names and values should be configurable by the integration arguments

2022-01-17 07:42 UTC, yaakovi commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +    name: gitlab-trigger-build
```suggestion
    name: gitlab-trigger-pipeline
```

2022-01-17 07:42 UTC, yaakovi commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +  dockerimage: demisto/python3:3.10.1.25933
revert to 3.9

2022-01-17 07:42 UTC, yaakovi commented on Packs/DevSecOps/ReleaseNotes/1_0_7.md
> +- Added the command **gitlab-trigger-contribution-build** to trigger a contribution build in Gitlab.
```suggestion
- Added the ***gitlab-trigger-pipeline*** command to trigger a pipeline in Gitlab.
```

2022-01-18 11:03 UTC, merit-maita commented on Packs/DevSecOps/Integrations/GitLab/GitLab.py
> +    trigger_token = params.get('trigger_token', '')
the api_token is the private api key generated by user, the trigger token, is one specific token for triggering builds in giltab.
they have 2 different values.

2022-01-24 14:36 UTC, yaakovi approved these changes
please schedule a 15 minutes demo

2022-01-24 14:36 UTC, yaakovi commented on Packs/DevSecOps/ReleaseNotes/1_0_7.md
> +- Updated the Docker image to: *demisto/python3:3.9.9.25564*.
update to actual image

2022-02-03 12:50 UTC, yaakovi approved these changes

2022-02-03 12:50 UTC, yaakovi commented on Packs/GitHub/Integrations/GitHub/GitHub.py
> +        'GitHub.Comment(val.IssueNumber === obj.IssueNumber && val.ID === obj.ID)': ec_object
```suggestion
        'GitHub.Comment(val.IssueNumber === obj.IssueNumber && val.ID === obj.ID)': ec_object,
```

2022-02-03 12:50 UTC, yaakovi commented on Packs/GitHub/Integrations/GitHub/GitHub.py
> +    suffix = ISSUE_SUFFIX + f'/comments/{comment_id}'
```suggestion
    suffix = f'{ISSUE_SUFFIX}/comments/{comment_id}'
```

2022-02-03 12:50 UTC, yaakovi commented on Packs/GitHub/Integrations/GitHub/GitHub.py
> +    suffix = ISSUE_SUFFIX + f'/comments/{comment_id}'
```suggestion
    suffix = f'{ISSUE_SUFFIX}/comments/{comment_id}'
```

2022-02-06 09:01 UTC, merged