Update Active_Directory_-_Get_User_Manager_Email_README.md
demisto/content pull request #16841
Opened 2022-01-04 11:19 UTC by tschanfeld

changed from ## to ### for items listed under dependencies

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-04 11:41 UTC, barchen1 requested changes

2022-01-04 11:41 UTC, barchen1 commented on Packs/Active_Directory_Query/Playbooks/Active_Directory_-_Get_User_Manager_Email_README.md
> +#3# Sub-playbooks
```suggestion
### Sub-playbooks
```

2022-01-06 08:32 UTC, barchen1 approved these changes

2022-01-06 08:33 UTC, tschanfeld reviewed
oops, typo. thanks for catching that.

2022-04-25 10:57 UTC, tschanfeld commented
@barchen1 looks like this got stuck, can you assist?

2022-04-25 11:16 UTC, barchen1 commented
Your changes is already in the file
Closing this PR.

2022-04-25 11:16 UTC, closed without merging