Phishingv3 minor bugs fix
demisto/content pull request #16863
Opened 2022-01-04 17:29 UTC by tomer-pan

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR will fix 2 issues:
1) in the Process Email - Generic v2 task on the main v3 playbook, there was a hardcoded value of "True" for the "GetOriginalEmail" input. This can cause errors for customers with no permissions.
2) The "InternalRange" input wasn't being used in the "Entity Enrichment - Phishing v2" task.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-04 17:33 UTC, idovandijk commented on Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
> -      GetOriginalEmail:
We want to get that value from the phishing playbook inputs though

2022-01-04 17:34 UTC, idovandijk requested changes
see comment

2022-01-04 19:57 UTC, David-BMS approved these changes

2022-01-05 08:16 UTC, abaumgarten approved these changes
Secrets check passed locally

2022-01-05 16:13 UTC, merged