runas DBotRole
demisto/content pull request #16968
Opened 2022-01-09 15:08 UTC by yguezpa

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/40683#issuecomment-1008311156)

## Description
Changing runas to DBotRole in order to use extractIndicators

2022-01-09 17:03 UTC, yguezpa commented
@DeanArbel It gives me an error for the DBotRole. Can you skip this ?

2022-01-10 07:12 UTC, DeanArbel requested changes

2022-01-10 07:12 UTC, DeanArbel commented on Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
> +runas: DBotRole
@yonahzuck We don't support DBotRole in content items, please remove this.

2022-01-10 08:42 UTC, erezh31 approved these changes

2022-01-10 09:35 UTC, ShirleyDenkberg commented
@erezh31 @tomer-pan @DeanArbel Doc review completed.

2022-01-10 10:04 UTC, merged