for testing
demisto/content pull request #17019
Opened 2022-01-11 09:53 UTC by MosheEichler

For testing

2022-01-16 10:45 UTC, MosheEichler commented on Packs/Whois/Integrations/Whois/Whois.py
> +        raise Exception("Please provide a valid value for the Source Reliability parameter1111.")
This is just for testing to run demisto-sdk lint on some package...

2022-01-23 15:00 UTC, reutshal requested changes
The "add_pr_comment" looks very similar to the "_add_pr_comment" in demisto-sdk.
Why not just import it and use it here?

2022-01-24 08:19 UTC, MosheEichler commented
> The "add_pr_comment" looks very similar to the "_add_pr_comment" in demisto-sdk. Why not just import it and use it here?

The function is a part of the `test-content` command (and we can't call it directly) And calling the command it's also impossible because we need some value's that is available just from the next jobs for example which test is skipped

2022-01-24 09:11 UTC, MosheEichler commented on Tests/scripts/add_pr_comment.py
> +            print('Add pull request comment failed: There is more then one open pull request for branch {branch_name}.')
No. to be hounest I'm not sure how to check it, how to create two PR's for the same branch.

2022-01-26 08:31 UTC, reutshal requested changes

2022-01-26 14:52 UTC, reutshal requested changes

2022-01-26 14:52 UTC, reutshal commented on Packs/Whois/Integrations/Whois/Whois.py
> +    aThis integration is built using the joepie91 "Whois" module. For more information regarding this package please see
Please revert

2022-01-26 14:52 UTC, reutshal commented on Tests/scripts/add_pr_comment.py
> +    logging_manager = ParallelLoggingManager('Run_Tests.log')
This should be a new logger, Run_Tests is not relevant to this flow

2022-01-26 14:52 UTC, reutshal commented on dev-requirements-py3.txt
> +git+https://github.com/demisto/demisto-sdk.git@479d81cb135db9df14fde2134eb7cec78954c644
Don't forget to revert after the testing

2022-01-30 09:35 UTC, reutshal commented on .gitlab/ci/global.yml
> +          echo "Adding coverage comment to the pr"
```suggestion
          echo "Adding unit tests coverage comment to the pr"
```

2022-01-30 09:40 UTC, reutshal commented on Tests/scripts/add_pr_comment.py
> +    _add_pr_comment(COVERAGE_REPORT_COMMENT + COVERAGE_LINK, logging_manager)
```suggestion
JOB_ID = os.environ.get("CI_JOB_ID")
COVERAGE_LINK = f'https://xsoar.docs.pan.run/-/content/-/jobs/{JOB_ID}/artifacts/artifacts/coverage_report/html/' \
                f'index.html'
COVERAGE_REPORT_COMMENT = f'Link to the unit tests coverage report: \n {COVERAGE_LINK}'


if __name__ == "__main__":
    logging_manager = ParallelLoggingManager('UT_coverage_report.log')
    _add_pr_comment(COVERAGE_REPORT_COMMENT, logging_manager)
```

2022-01-30 09:40 UTC, reutshal requested changes
Lets change this and I think we are ready to merge

2022-01-30 10:25 UTC, MosheEichler commented
Waiting for demisto-sdk version 1.5.9

2022-01-30 10:44 UTC, esharf commented on .gitlab/ci/global.yml
> +          python3 ./Tests/scripts/add_pr_comment.py
```suggestion
            demisto-sdk coverage-analyze -i $ARTIFACTS_FOLDER/coverage_report/.coverage --report-dir $ARTIFACTS_FOLDER/coverage_report --report-type html,xml --previous-coverage-report-url https://storage.googleapis.com/marketplace-dist-dev/code-coverage-reports/coverage-min.json
              echo "Adding unit tests coverage comment to the pr"
              python3 ./Tests/scripts/add_pr_comment.py

          fi
```

2022-01-30 11:06 UTC, esharf approved these changes
LGTM

2022-02-03 17:00 UTC, reutshal approved these changes

2022-02-03 23:27 UTC, merged