Adopt cybereason pack
demisto/content pull request #17032
Opened 2022-01-11 15:46 UTC by suraj-metron

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-11 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=17032) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=17032) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=17032) it.</sub>

2022-01-11 17:41 UTC, mchasepan requested changes
Waiting on Ishai from Cybereason to complete partner paperwork prior to merge.

2022-01-17 08:50 UTC, eyalpalo commented
@suraj-metron any update?

2022-01-17 09:16 UTC, suraj-metron commented
@eyalpalo Cybereason is in process of completing the partner paperwork. We will mark this Draft PR as 'Ready to Merge' after the paperwork is completed.

2022-01-27 09:34 UTC, eyalpalo approved these changes

2022-03-28 07:23 UTC, eyalpalo approved these changes

2022-03-28 15:46 UTC, mchasepan requested changes

2022-03-28 15:46 UTC, mchasepan commented on Packs/Cybereason/ReleaseNotes/1_0_19.md
> +Note: Support for this pack will be moving to the partner around April 11th, 2022
```suggestion
Note: Support for this pack will be moving to the partner around May 15th, 2022
```

2022-03-29 12:15 UTC, mchasepan approved these changes

2022-03-29 15:52 UTC, merged