New Integration with Camlytics
demisto/content pull request #17046
Opened 2022-01-12 11:08 UTC by ayman-m

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
A new integration with Camlytics, a surveillance analysis system.

## Minimum version of Cortex XSOAR
- [x ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [ ] Tests
- [x ] Documentation

2022-01-12 14:53 UTC, merit-maita commented
Hello @ayman-m
can you please fell the [registration form](https://forms.gle/XDfxU4E61ZwEESSMA) so we can go ahead with the review?
thanks

2022-01-15 19:35 UTC, merit-maita commented on Packs/Camlytics/Integrations/Camlytics/Camlytics.py
> +        return_error(str(e))
```suggestion
        return_error(f'Failed to execute {command} command.\nError:\n{str(e)}')
```

2022-01-15 19:39 UTC, merit-maita commented on Packs/Camlytics/Integrations/Camlytics/Camlytics.py
> +            'camlytics-get-events': events_command,
```suggestion
            'camlytics-get-channels': get_channels_command,
            'camlytics-get-events-totals-by-rule': get_events_totals_by_rule_command,
            'camlytics-get-events-totals-by-type': get_events_totals_by_type_command,
            'camlytics-get-events': get_events_command,
```

2022-01-15 19:40 UTC, merit-maita commented on Packs/Camlytics/Integrations/Camlytics/Camlytics.py
> +def channels_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```suggestion
def get_channels_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```

2022-01-15 19:41 UTC, merit-maita commented on Packs/Camlytics/Integrations/Camlytics/Camlytics.py
> +def eventstotalsrule_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```suggestion
def get_events_totals_by_rule_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```

2022-01-15 19:42 UTC, merit-maita commented on Packs/Camlytics/Integrations/Camlytics/Camlytics.py
> +def eventstotalstype_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```suggestion
def get_events_totals_by_type_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```

2022-01-15 19:43 UTC, merit-maita commented on Packs/Camlytics/Integrations/Camlytics/Camlytics.py
> +def events_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```suggestion
def get_events_command(client: Client, args: Dict[str, Any]) -> CommandResults:
```

2022-01-15 19:55 UTC, merit-maita requested changes
Thank you for your great effort!

2022-01-17 09:55 UTC, ayman-m commented
> Thank you for your great effort!

Thank you, I pushed another commit now

2022-01-17 20:47 UTC, merit-maita commented
@ayman-m Thank you for the hard work!
i'd like to schedule a demo with you, please let me know when it suits you.

2022-01-19 21:27 UTC, merit-maita approved these changes
Thank you Ayman, very good job
one last step before merging,  the validation check fails because of a lint error with mypy.
that was solved. please pull from master and push again.

2022-01-20 05:20 UTC, ayman-m commented
> Thank you Ayman, very good job one last step before merging, the validation check fails because of a lint error with mypy. that was solved. please pull from master and push again.

Thanks Merit for your time during the session, I have pulled from the master and pushed again, the branch is now in sync

2022-01-20 07:34 UTC, merit-maita commented
> > Thank you Ayman, very good job one last step before merging, the validation check fails because of a lint error with mypy. that was solved. please pull from master and push again.
> 
> Thanks Merit for your time during the session, I have pulled from the master and pushed again, the branch is now in sync

you're most welcome!
i see that lint fails overa different error, please take a look and fix it.

2022-01-24 06:18 UTC, ayman-m commented
> > > Thank you Ayman, very good job one last step before merging, the validation check fails because of a lint error with mypy. that was solved. please pull from master and push again.
> > 
> > 
> > Thanks Merit for your time during the session, I have pulled from the master and pushed again, the branch is now in sync
> 
> you're most welcome! i see that lint fails overa different error, please take a look and fix it.

Hi @merit-maita , I fixed it

2022-01-24 14:29 UTC, merged