Reduce images 04
demisto/content pull request #17064
Opened 2022-01-12 16:51 UTC by agamm

…stener, MongoDB

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
related: https://github.com/demisto/content/pull/17059

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-12 17:42 UTC, yuvalbenshalom requested changes
see my comments

2022-01-12 17:42 UTC, yuvalbenshalom commented on Packs/ImpossibleTraveler/ReleaseNotes/1_2_5.md
> +- Updated the Docker image to: *demisto/py3-tools:0.0.1.25751*.
the release note should state the script/integration that was updated, as the playbook itself was not updated.
see ` FetchIndicatorsFromFile/ReleaseNotes/1_0_5.md` in your PR as a good example.

2022-01-12 17:42 UTC, yuvalbenshalom commented on Packs/Intezer/ReleaseNotes/1_2_6.md
> +- Updated the Docker image to: *demisto/py3-tools:0.0.1.25751*.
```suggestion
- Updated the Docker image to: *demisto/py3-tools:0.0.1.25751*.
#### Integrations
##### IntezerV2
- Updated the Docker image to: *demisto/py3-tools:0.0.1.25751*.
```

2022-01-12 17:42 UTC, yuvalbenshalom commented on Packs/JARM/Integrations/JARM/JARM.yml
> +  dockerimage: demisto/py3-tools:0.0.1.25751
missing release notes

2022-01-13 11:28 UTC, agamm commented on Packs/JARM/Integrations/JARM/JARM.yml
> +  dockerimage: demisto/py3-tools:0.0.1.25751
Added, there were none before.

2022-01-13 11:31 UTC, agamm commented
@yuvalbenshalom done.

2022-01-16 07:38 UTC, yuvalbenshalom requested changes

2022-01-16 07:38 UTC, yuvalbenshalom commented on Packs/Intezer/ReleaseNotes/1_2_6.md
> +##### IntezerV2
```suggestion
##### Intezer v2
```
my bad

2022-01-16 07:39 UTC, yuvalbenshalom commented
please take a look at the unit tests and the test playbooks failures.

2022-01-19 19:17 UTC, yuvalbenshalom approved these changes

2022-01-19 19:17 UTC, merged