CreateEDLInstance
demisto/content pull request #17107
Opened 2022-01-14 16:39 UTC by nericksen

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This automation allows for creating an EDL instance on XSOAR.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-16 11:14 UTC, eyalpalo requested changes
Hi @nericksen, nice script!
Please see the attached comments.

2022-01-16 11:14 UTC, eyalpalo commented on Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.py
> +existing_port_list = demisto.executeCommand('getList', {'listName': edl_port_list_name})[0]['Contents'].split(',')
It is recommended to use dict ״get״ method instead of []. Not mandatory.

2022-01-16 11:14 UTC, eyalpalo commented on Packs/CreateEDLInstance/Scripts/CreateEDLInstance/README.md
> +| Tags |  |
Please add Description for Tags.

2022-01-18 15:33 UTC, nericksen commented on Packs/CreateEDLInstance/Scripts/CreateEDLInstance/README.md
> +| Tags |  |
Done!

2022-01-18 15:34 UTC, nericksen commented on Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.py
> +demisto.results(f"EDL: {edl_instance_name} created on port: {random_port}")
done!

2022-01-19 09:46 UTC, eyalpalo approved these changes

2022-01-19 09:48 UTC, merged