#3482 [Demisto] release a new plugin
demisto/content pull request #17115
Opened 2022-01-16 09:17 UTC by SepioSystems

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-16 09:22 UTC, SepioSystems commented
Release a new plug-in version to fix lost events using eventid instead of timestamp

2022-01-17 12:45 UTC, ilaner requested changes
Please pull from origin/master and add release notes

2022-01-17 13:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=17115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=17115) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: SepioSystems<br/>:white_check_mark: amshamah419<br/>:white_check_mark: dorschw<br/>:white_check_mark: iyeshaya<br/>:white_check_mark: Itay4<br/>:x: MLainer1<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=17115) it.</sub>

2022-01-18 09:30 UTC, ilaner requested changes
Please update release notes, update the `pack-metadata.json`

2022-01-18 09:30 UTC, ilaner commented on Packs/Sepio/ReleaseNotes/SeprioPrimeAPI_FromEventId.md
> +Sepio Prime API Test Playbook with all the integration supported commands
In this folder supposed to be the release notes file, not the readme. It should be named by the version of the pack (for instance, `1_0_6.md`) and should include a list of changes.
Take an example from the other files in this folder.

2022-01-23 15:16 UTC, merged