Wrapper script panorama
demisto/content pull request #17130
Opened 2022-01-16 19:23 UTC by daryakoval

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/45613)

## Description
wrapper script for panorama-security-policy-match command

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-01-18 12:01 UTC, dantavori requested changes

2022-01-18 12:01 UTC, dantavori commented on Packs/PAN-OS/Scripts/PanoramaSecurityPolicyMatchWrapper/test_data/basescript-dummy.json
> +{
remove if unused

2022-01-18 12:01 UTC, dantavori commented on Packs/PAN-OS/Scripts/PanoramaSecurityPolicyMatchWrapper/PanoramaSecurityPolicyMatchWrapper.yml
> +- basescript
did we add this by design?

2022-01-18 12:01 UTC, dantavori commented on Packs/PAN-OS/Scripts/PanoramaSecurityPolicyMatchWrapper/PanoramaSecurityPolicyMatchWrapper.yml
> +timeout: '0'
why 0?

2022-01-19 08:54 UTC, dantavori approved these changes

2022-01-20 12:48 UTC, ShirleyDenkberg commented
@dantavori Doc review completed.

2022-01-20 13:38 UTC, merged