Arnarayanan contrib xsoar utils
demisto/content pull request #17225
Opened 2022-01-20 15:17 UTC by arnarayanan

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-23 14:59 UTC, ilaner requested changes

2022-01-23 14:59 UTC, ilaner commented on Packs/Xsoar_Utils/Integrations/XsoarUtils/XsoarUtils.py
> +        except:
```suggestion
        except Exception:
```

2022-01-24 11:38 UTC, arnarayanan reviewed
completed the suggested changes

2022-01-26 15:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=17225) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=17225) before we can accept your contribution.<br/>**8** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: content-bot<br/>:white_check_mark: yaakovi<br/>:white_check_mark: ChanochShayner<br/>:white_check_mark: darkushin<br/>:white_check_mark: Shellyber<br/>:white_check_mark: xsoar-bot<br/>:white_check_mark: arnarayanan<br/>:white_check_mark: ilaner<br/>:x: ilappe<br/>:x: Ni-Knight<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=17225) it.</sub>

2022-01-26 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=17225) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=17225) before we can accept your contribution.<br/>**8** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: xsoar-bot<br/>:white_check_mark: ilaner<br/>:white_check_mark: content-bot<br/>:white_check_mark: yaakovi<br/>:white_check_mark: ChanochShayner<br/>:white_check_mark: arnarayanan<br/>:white_check_mark: darkushin<br/>:white_check_mark: Shellyber<br/>:x: ilappe<br/>:x: Ni-Knight<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=17225) it.</sub>

2022-02-01 15:21 UTC, ilaner approved these changes
Great job

2022-02-01 15:22 UTC, merged