Add note on required input for RTR `put` command
demisto/content pull request #17243
Opened 2022-01-22 04:49 UTC by ali-sawyer

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Added note that `cs-falcon-run-command` `scope=admin` is required for an RTR `put` command. This seems to be a common use case and I have seen this question from clients a few times. Not sure the best place to put this note; feel free to move it to a different part of the page. Maybe start a FAQ or Troubleshooting section?

## Screenshots
N/A

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-23 07:51 UTC, eyalpalo requested changes

2022-01-23 07:51 UTC, eyalpalo commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
> +| scope | The scope for which to run the command. Possible values are: "read", "write", and "admin". Default is "read". (NOTE: To run the CrowdStrike RTR `put` command, it is nessary to pass `scope=a
```suggestion
| scope | The scope for which to run the command. Possible values are: "read", "write", and "admin". Default is "read". (NOTE: In order to run the CrowdStrike RTR `put` command, it is necessary to pass `scope=admin`.) | Optional | 
```

2022-01-23 18:36 UTC, ali-sawyer commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
> +| scope | The scope for which to run the command. Possible values are: "read", "write", and "admin". Default is "read". (NOTE: To run the CrowdStrike RTR `put` command, it is nessary to pass `scope=a
Much better, thank you.

2022-01-24 07:50 UTC, eyalpalo approved these changes

2022-01-24 07:50 UTC, merged