FireEye HX V2
demisto/content pull request #17292
Opened 2022-01-24 14:35 UTC by israelpoli

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/37161)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-25 07:54 UTC, JasBeilin requested changes

2022-01-25 07:54 UTC, JasBeilin commented on Packs/FireEyeHX/Integrations/FireEyeHX_V2/FireEyeHX_v2_test.py
> +"""Base Integration for Cortex XSOAR - Unit Tests file
You can remove these "base Integration comments"

2022-01-25 07:54 UTC, JasBeilin commented on Packs/FireEyeHX/Integrations/FireEyeHX_V2/FireEyeHX_v2_test.py
> +UPSERT_COMMAND_DATA_BAD_CASES=[
could you please add for each case an explanation on what is the case?

2022-01-25 07:54 UTC, JasBeilin commented on Packs/FireEyeHX/Integrations/FireEyeHX_V2/FireEyeHX_v2_test.py
> +    client = ""#Client(base_url='some_mock_url', verify=False)
if the Client object is not needed you can remove it.

2022-01-25 07:54 UTC, JasBeilin commented on Packs/FireEyeHX/Integrations/FireEyeHX_V2/FireEyeHX_v2.yml
> +    description: Get information on a host associated with an agent.
I think you are missing a - before this line

2022-02-16 10:08 UTC, DeanArbel requested changes
Amazing effort. There's still a lot to do, please go over my comments.

2022-02-16 10:08 UTC, DeanArbel commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
> +        reported_at = alerts[-1].get("reported_at") if alerts else None
This section is duplicate code, you could unite it with the code in the `if` clause above by extracting it from the `if/else` clauses.

2022-02-16 10:08 UTC, DeanArbel commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
> +            next_run_in_seconds=60,
Didn't the design suggest to make this editable via an arg?

2022-02-16 10:08 UTC, DeanArbel commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
> +    password = params.get("userName").get('password')
Please use python conventions for naming (snake_case)

2022-02-16 10:08 UTC, DeanArbel commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml
> +- No tests (auto formatted)
Didn't you add a test playbook?

2022-02-16 10:08 UTC, DeanArbel commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/README.md
> +For more information see the [integration documentation](https://xsoar.pan.dev/docs/integrations/integration-docs).
Please generate a readme with the demisto-sdk command.

2022-02-16 10:08 UTC, DeanArbel commented on Packs/FireEyeHX/ReleaseNotes/2_0_0.md
> +FireEye Endpoint Security (HX) v2 (formerly known as FireEye HX)
Please add the new commands that were added.

2022-02-22 07:12 UTC, israelpoli commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
> +            params['os.platform'] = os_platform
I'm not sure about that, because those keys have a dot in the middle

2022-02-22 07:13 UTC, israelpoli commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
> +        event_type_parsed=re.sub("([a-z])([A-Z])", "\g<1> \g<2>", event_type).title(),
If you can check if I did it right

2022-02-22 07:15 UTC, israelpoli commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
> +    fetch_limit = int(args.get('max_fetch') or '50')
I did not understand it

2022-02-22 11:57 UTC, DeanArbel commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py
> +            params['os.platform'] = os_platform
Good point :)

2022-02-22 14:30 UTC, DeanArbel commented on Packs/FireEyeHX/Integrations/FireEyeHXv2/README.md
> +There is no context output for this command.
Did you run the generater readme with command examples? If not please do. Consult with Jasmine on how to do it.

2022-02-28 16:42 UTC, richardbluestone approved these changes
Made a few changes to the yml, and Md files.

2022-03-03 07:26 UTC, DeanArbel approved these changes

2022-03-06 14:03 UTC, merged