X fields and Aliases
demisto/content pull request #17316
Opened 2022-01-25 23:57 UTC by David-BMS

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-26 09:59 UTC, reutshal requested changes

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Agent_IDs.json
> +      ]
Missing Agents_ID in the list

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Appliance_IDs.json
> +          "cliName": "applianceid",
Add "marketplace xsoar" to the field

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Appliance_Names.json
> +          "cliName": "appliancename",
Add "marketplaces xsoar" to the field @

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Application_Sub_Category_Name.json
> +    "cliName": "applicationcategoryname",
fix cliName, description, id

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Country_Names.json
> +	  "x2_fields": "action_country",
fix indentation

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Email_Subjects.json
> +          "cliName": "emailsubject",
Add xsoar marketplace

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Event_Type_Names.json
> +          "cliName": "eventtype",
Add xsoar marketplace to the field

2022-01-26 09:59 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Process_names.json
> +    "fromVersion": "5.5.0",
Add x2_fields

2022-01-26 10:02 UTC, reutshal commented on Packs/CommonTypes/IncidentFields/incidentfield-Agent_IDs.json
> +        },
remove

2022-01-26 10:10 UTC, reutshal approved these changes

2022-01-30 08:35 UTC, reutshal commented
@David-BMS Can we close this?

2022-01-30 08:50 UTC, David-BMS commented
@reutshal I'm using it for something else now
I'll close it soon

2022-02-09 07:08 UTC, David-BMS commented
Closing due to multiple changes since

2022-02-09 07:08 UTC, closed without merging