Lastline csv bug - draft
demisto/content pull request #17325
Opened 2022-01-26 10:16 UTC by yucohen

this is a draft to a potential fix to lastline.
since we have no credentials, I wasn't able to test the changes. waiting for the customer to response and schedule a call in order to test the changes.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-06 21:42 UTC, yaakovi approved these changes

2022-02-07 14:19 UTC, yucohen commented
@jrosenpanw hi
Can someone please have a look?
thanks

2022-02-09 06:33 UTC, yucohen commented
@ShirleyDenkberg Hi 
can someone please have a look?
thanks

2022-02-09 08:11 UTC, ShirleyDenkberg commented
@yaakovi Doc review completed.

2022-02-09 17:41 UTC, yaakovi requested changes

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/ReleaseNotes/1_0_10.md
> +- Fixed an issue where the **lastline-upload-file** command failed when given a CSV file.
```suggestion
- Fixed an issue where the ***lastline-upload-file*** command failed when given a CSV file.
```

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
> +                                                     'password': 'password'}}])
No need to use `parametrize` here.

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
> +def test_csvs_handles_correctly(mocker, params):
Improve function name.
The name should include the name of the unit it tests (command/function) and the use case.

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
> +        Given:
```suggestion
    Given:
```

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
> +        - Validating that handle_csv is being called
Check that there was a call to the login API.

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
> +    mocker.patch.object(demisto, 'getFilePath', return_value={'id': id, 'path': 'test/test.txt', 'name': 'test.csv'})
```suggestion
    mocker.patch.object(demisto, 'getFilePath', return_value={'id': id, 'path': 'test/test.csv', 'name': 'test.csv'})
```

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
> +    mocker.patch.object(os.path, 'splitext', return_value=['test', '.csv'])
Redundant

2022-02-09 17:41 UTC, yaakovi commented on Packs/Lastline/Integrations/Lastline_v2/Lastline_v2_test.py
> +    mocker.patch.object(client, 'handle_csv', return_value={})
Mock the requests instead and check the login endpoint was called.

2022-02-14 09:35 UTC, merged