Core Alert Fields
demisto/content pull request #17344
Opened 2022-01-27 12:11 UTC by tomer-pan

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Creating Core Alert Fields pack with new 18 fields.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-27 13:16 UTC, reutshal requested changes
Please add all aliases fields to marketplace xsoar only

2022-01-27 13:16 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
> +    "description": "Action taken by the alert sensor, either Detected or Prevented with action status displayed in parenthesis. Options are: Detected, Detected (Allowed The Session), Detected (Downlo
Looks super long to me, @michalgold WDYT?

2022-01-27 13:16 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-File_SHA256.json
> +          "cliName": "sha256",
Add: "marketplaces - xsoar" to the field

2022-01-27 13:16 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-User_name.json
> +	"x2_fields": "actor_effective_username"ת
```suggestion
	"x2_fields": "actor_effective_username",
```

2022-01-27 13:21 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
> +    "description": "Action taken by the alert sensor, either Detected or Prevented with action status displayed in parenthesis. Options are: Detected, Detected (Allowed The Session), Detected (Downlo
```suggestion
    "description": "Action taken by the alert sensor, either Detected or Prevented with action status displayed in parenthesis. Options are: Detected, Detected (Allowed The Session), Detected (Download), Detected (Forward), Detected (Post Detected), Detected (Prompt Allow), Detected (Raised An Alert), Detected (Reported), Detected (Scanned), Detected (Sinkhole), Detected (Syncookie Sent), Detected (Wildfire Upload Failure), Detected (Wildfire Upload Success), Detected (Wildfire Upload Skip), Detected (XDR Managed Threat Hunting), Prevented (Block), Prevented (Blocked), Prevented (Block-Override), Prevented (Blocked The URL), Prevented (Blocked The IP), Prevented (Continue), Prevented (Denied The Session), Prevented (Dropped All Packets), Prevented (Dropped The Session), Prevented (Dropped The Session And Sent a TCP Reset), Prevented (Dropped The Packet), Prevented (Override), Prevented (Override-Lockout), Prevented (Post Detected), Prevented (Prompt Block), Prevented (Random-Drop), Prevented (Silently Dropped The Session With An ICMP Unreachable Message To The Host Or Application), Prevented (Terminated The Session And Sent a TCP Reset To Both Sides Of The Connection), Prevented (Terminated The Session And Sent a TCP Reset To The Client), Prevented (Terminated The Session And Sent a TCP Reset To The Server).",
```

2022-01-27 13:45 UTC, reutshal requested changes

2022-01-27 13:45 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-Initiated_By.json
> +          "cliName": "processname",
Add xsoar marketplace

2022-01-27 13:45 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-Initiator_path.json
> +          "cliName": "processpath",
Add xsoar marketplace

2022-01-27 13:45 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-Local_Port.json
> +        "cliName": "srcports",
Add xsoar marketplace and remove aliases

2022-01-27 13:45 UTC, reutshal commented on Packs/CoreAlertFields/IncidentFields/incidentfield-Remote_Port.json
> +          "cliName": "dstports",
remove aliases and xsoar only

2022-01-27 13:50 UTC, reutshal approved these changes

2022-01-31 12:31 UTC, merged

2022-02-01 05:54 UTC, esharf commented
@tomer-pan @reutshal 
```
[2022-02-01 00:33:52] - [MainThread] - [ERROR] - Failed in formatting Malware pack metadata. Additional Info: New mandatory dependencies ['CoreAlertFields'] were found in the core pack Malware
Traceback (most recent call last):
  File "/builds/xsoar/content/Tests/Marketplace/marketplace_services.py", line 1914, in format_metadata
    self.set_pack_dependencies(packs_dependencies_mapping)
  File "/builds/xsoar/content/Tests/Marketplace/marketplace_services.py", line 2010, in set_pack_dependencies
    raise Exception(f'New mandatory dependencies {mandatory_dependencies} were '
Exception: New mandatory dependencies ['CoreAlertFields'] were found in the core pack Malware
```
nightly is failing because of this error.
can you check it?

2022-02-01 07:35 UTC, tomer-pan commented
> @tomer-pan @reutshal
> 
> ```
> [2022-02-01 00:33:52] - [MainThread] - [ERROR] - Failed in formatting Malware pack metadata. Additional Info: New mandatory dependencies ['CoreAlertFields'] were found in the core pack Malware
> Traceback (most recent call last):
>   File "/builds/xsoar/content/Tests/Marketplace/marketplace_services.py", line 1914, in format_metadata
>     self.set_pack_dependencies(packs_dependencies_mapping)
>   File "/builds/xsoar/content/Tests/Marketplace/marketplace_services.py", line 2010, in set_pack_dependencies
>     raise Exception(f'New mandatory dependencies {mandatory_dependencies} were '
> Exception: New mandatory dependencies ['CoreAlertFields'] were found in the core pack Malware
> ```
> 
> nightly is failing because of this error. can you check it?

@reutshal I believe it's related to the same thing we were talking about where the sdk should add the dependencies to the metadata of the packs with the fields that their aliases are in the new fields in the Core Alert Fields pack.