Aburt-salesforce-indicators-improvements
demisto/content pull request #17364
Opened 2022-01-28 12:11 UTC by aburt-demisto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
NA

## Description
This update uses get integration_context commands to better manage the volume of data returned. The integration will now firstly use the last modified date of the indicator in the initial and now subsequent pull to ensure that not every indicator (using the query) is returned every time.

## Screenshots
NA

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-01-30 09:59 UTC, eyalpalo requested changes

2022-01-30 09:59 UTC, eyalpalo commented on Packs/SalesforceIndicators/ReleaseNotes/1_0_5.md
> +- Changed the initial query to pull from last modified date rather than created date
Please add
```
 - Updated the Docker image to: *demisto/python3:3.10.1.25933*.
```

2022-01-31 08:58 UTC, aburt-demisto commented on Packs/SalesforceIndicators/ReleaseNotes/1_0_5.md
> +- Changed the initial query to pull from last modified date rather than created date
Done

2022-01-31 09:35 UTC, eyalpalo approved these changes

2022-01-31 09:39 UTC, merged