Bug Cylance - return array entry as DBot type
demisto/content pull request #17411
Opened 2022-02-01 13:22 UTC by MLainer1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/46204#issuecomment-1025106238

## Description
return array entry as DBot type

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-01 15:16 UTC, jochman requested changes
Cool.

2022-02-01 15:16 UTC, jochman commented on Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.py
> -    ec = {
get back the file. (You can use `Common.File`)

2022-02-02 10:18 UTC, jochman approved these changes
Nice. 🏞️

2022-02-02 12:29 UTC, avidan-H commented on Packs/Cylance_Protect/ReleaseNotes/1_0_9.md
> +- Fixed an issue where multiple DBotScore objects of different indicators returned at once.
```suggestion
- Fixed an issue where multiple indicators returned DBotScore objects simultaneously.
```

2022-02-06 15:03 UTC, jochman requested changes

2022-02-06 15:03 UTC, jochman commented on Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.py
> +    headers = {  # pragma: no cover
Change the headers to one call, maybe push it into `api_call`

2022-02-07 07:50 UTC, jochman approved these changes
🌻

2022-02-07 07:54 UTC, merged