UrlHaus enchantment
demisto/content pull request #17467
Opened 2022-02-03 08:06 UTC by AradCarmi

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-06 17:07 UTC, dantavori requested changes
amazing work! see my notes.
in addition:
1. please use typing - e.g.  change `def domain_calculate_score(blacklist):` to `def domain_calculate_score(blacklist: List[str]) -> Tuple[int, str]:`.
2. In each reputation command you have a bit different convention/standard (e.g. in domain/file you don't use DBotScore object and the outputs_key_field, etc). Let's stick into one convention in all three commands (I suggest the convention in the URL command which is the most updated one).

2022-02-07 11:53 UTC, AradCarmi commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +        tags.append(urlhaus_data.get('Threat'))
I've already asked her and she told me to keep it under URL.Tags .

2022-02-07 12:37 UTC, AradCarmi commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +        relationships.append(EntityRelationship(
Each file should have a signature so I guess the answer is yes.

2022-02-08 12:06 UTC, meital-aizen commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +            bl_status.split('_')[-1] if bl_status.startswith('abused') else ''
@dantavori After consulting, we decided that for tags that start with `abuse`, we can just save it as is (no need to remove any words).

2022-02-09 14:56 UTC, dantavori requested changes
awesome 👏 
1. in addition to the new comments, see 2 comments that I unresolved from the previous CR.
2. please attach to the PR a screenshot of a passing run of the test playbook
3. we will need to add a support for providing multiple values in a reputation command (let's discuss this)
4. please schedule a demo for next week (invite Meital too)

2022-02-09 14:56 UTC, dantavori commented on Packs/URLHaus/Integrations/URLHaus/README.md
> -    "URLhaus": {
now it's too little information :(
what I meant previously was that you should edit this manually and remove some of the output, so it won't be too long for the reader (but they still might want to see an informative example).

2022-02-10 10:18 UTC, AradCarmi commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +            void.
Didn't understand the suggestion.

2022-02-10 13:33 UTC, dantavori commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +            void.
no need to provide "Returns:" when nothing is returned.

2022-02-13 10:10 UTC, AradCarmi commented
> awesome 👏
> 
> 1. in addition to the new comments, see the comment that I unresolved from the previous CR.
> 2. please attach to the PR a screenshot of a passing run of the test playbook
> 3. we will need to add a support for providing multiple values in a reputation command (let's discuss this)
> 4. please schedule a demo for next week (invite Meital too)

2022-02-15 11:41 UTC, dantavori requested changes
almost there!
see my last minor notes. in addition: please change in the yml in every reputation command the `isArray` value from `false` to `true` (e.g. in line 72 for url command).
explanation is here: https://xsoar.pan.dev/docs/integrations/code-conventions#ioc-reputation-commands

2022-02-15 11:41 UTC, dantavori commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +            bl_status if bl_status.startswith('abused') else ''
why did we resolve this?

2022-02-15 11:41 UTC, dantavori commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +    return Common.DBotScore.GOOD, "There is no information about Domain in the blacklist"
why did you resolve?

2022-02-15 11:41 UTC, dantavori commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +    for url in urls.split(','):
```suggestion
    for url in argToList(urls):
```
url arg might already be a list given to the argument from the context:
`!url url=${Path.to.URLs}`
argToList() handles this. please change in other commands too.

2022-02-15 13:15 UTC, AradCarmi commented on Packs/URLHaus/Integrations/URLHaus/URLHaus.py
> +    return Common.DBotScore.GOOD, "There is no information about Domain in the blacklist"
The design document defines that in any other case the DBot Score should be benign.

2022-02-15 16:43 UTC, ShirleyDenkberg commented
@meital-aizen @dantavori Doc review completed.

2022-02-17 15:36 UTC, merged