First commit
demisto/content pull request #17511
Opened 2022-02-06 12:59 UTC by AradCarmi

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-16 17:40 UTC, dantavori requested changes
looks great! let's try it out tomorrow before the demo.

2022-02-16 17:40 UTC, dantavori commented on Packs/DeveloperTools/Scripts/GetRange/GetRange.yml
> +  description: 'List'
```suggestion
  description: 'The list to transform.'
```

2022-02-16 17:40 UTC, dantavori commented on Packs/DeveloperTools/Scripts/GetRange/GetRange.yml
> +comment: 'Get a range of indexes from a list.'
```suggestion
comment: 'Gets specified indexes of a list.'
```

2022-02-16 17:40 UTC, dantavori commented on Packs/DeveloperTools/Scripts/GetRange/GetRange.yml
> +  description: 'Comma separated list of indexes to slice by (0,1-3,6-7,...,etc).'
```suggestion
  description: 'A comma-separated list of indexes or ranges of to retrieve (e.g., 0,1-3,6-7).'
```

2022-02-16 17:40 UTC, dantavori commented on Packs/DeveloperTools/ReleaseNotes/1_2_15.md
> +- Updated the Docker image to: *demisto/python3:3.10.1.25933*
```suggestion
- Gets specified indexes of a list. (Available from Cortex XSOAR 5.5.0)
```

2022-02-16 17:40 UTC, dantavori commented on Packs/DeveloperTools/Scripts/GetRange/README.md
> +Get a range of indexes from a list.
don't forget to regenerate. In addition, let's add an example.

2022-02-17 07:39 UTC, AradCarmi commented on Packs/DeveloperTools/Scripts/GetRange/GetRange_test.py
> +        main()
I just called main method to cover as much as possible. But I understood from now on I would act that way.

2022-02-17 17:38 UTC, dantavori approved these changes

2022-02-20 09:33 UTC, merged