Integration contribution for SpyCloud ATO
demisto/content pull request #17604
Opened 2022-02-10 15:21 UTC by nheijmans

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Contributing xsoar integration for SpyCloud API ATO

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-02-11 11:50 UTC, nheijmans commented
@ilaner hi 👋🏻 ! The validation error https://app.circleci.com/pipelines/github/demisto/content/144715/workflows/547aadc3-7284-4d1b-96d8-0578f8a2e0a8/jobs/481797?invite=true#step-108-58 here is unclear to me. Could you help identify what the check wants from us :) ?

2022-05-17 11:10 UTC, Noy-Maimon commented
> @ilaner hi 👋🏻 ! The validation error https://app.circleci.com/pipelines/github/demisto/content/144715/workflows/547aadc3-7284-4d1b-96d8-0578f8a2e0a8/jobs/481797?invite=true#step-108-58 here is unclear to me. Could you help identify what the check wants from us :) ?

Hi @nheijmans, so sorry for the late reply. Thank you for your contribution. I had a look at the error you specified and it seems to be like a temporary issue. can you please try pushing the branch again? this way the build will be triggered again, and we can see if this error reoccures. Thanks!

2022-05-19 13:44 UTC, Noy-Maimon requested changes
Looks great!
Please note my comments and change where needed.

2022-05-19 13:44 UTC, Noy-Maimon commented on Packs/SpyCloudPack/Integrations/SpyCloud/SpyCloud.py
> +def test_mod():
```suggestion
def test_module():
```

2022-05-19 13:44 UTC, Noy-Maimon commented on Packs/SpyCloudPack/README.md
> +**Make sure to whitelist your outbound IP address XSOAR uses to connect**
```suggestion
```

When the pack is only of an integration (as in this case), we can use only the integration readme (no need for duplicate).

2022-05-19 14:10 UTC, Noy-Maimon commented on Packs/SpyCloudPack/README.md
> +**Make sure to whitelist your outbound IP address XSOAR uses to connect**
Please modify the Pack readme to meet our standards:
https://xsoar.pan.dev/docs/documentation/pack-docs#readme-structure

2022-05-19 14:12 UTC, Noy-Maimon commented on Packs/SpyCloudPack/Integrations/SpyCloud/README.md
> +**Make sure to whitelist your outbound IP address XSOAR uses to connect**
Please modify the **Integration** readme to meet our standards:
https://xsoar.pan.dev/docs/documentation/readme_file

2022-05-20 09:00 UTC, nheijmans reviewed
Thanks for those additional changes! Tested and seems to work for me

2022-05-24 15:00 UTC, Noy-Maimon commented
@nheijmans Hi, here's what you have left:
1. to solve the secrets issue - add this email to the .secrets-ignore file: john.doe@hotmail.com
2. modify the Pack README (as mentioned in the comment on the README file [here](https://github.com/demisto/content/pull/17604/files/e6a844ede9ef723c9412b40cff5e16008ccb1050#diff-99ff0b77ee7043888c956ce13a21572904b4dc0834c1e0fa8f164b2ad77daf35))
3. merge your forked repo from our content master and then merge it to your branch. let me know if you need assistance with that.

2022-05-24 20:10 UTC, nheijmans commented
> 2\. here

@Noy-Maimon I've pushed the secret ignore change
On 2, I'm not sure what you mean, the docs have been generated with demisto-sdk generate-docs, they are the standard as documented

On 3, yes please give a hand with this :) I'm not entirely sure whats required here

2022-05-26 10:18 UTC, Noy-Maimon commented
> > 2. here
> 
> @Noy-Maimon I've pushed the secret ignore change On 2, I'm not sure what you mean, the docs have been generated with demisto-sdk generate-docs, they are the standard as documented
> 
> On 3, yes please give a hand with this :) I'm not entirely sure whats required here

You are talking about the Integration README (Packs/SpyCloudPack/Integrations/SpyCloud/README.md), I was referring to the **pack** readme (Packs/SpyCloudPack/README.md). 

Each pack readme should contain:

- A short paragraph connecting real-life situations to the pack use cases.
- A "What does this pack do?" section, explaining point-by-point the capabilities of the pack or the main playbook of the pack.
- (Optional): a sentence or two detailing the contents of the pack.
See more information [here](https://xsoar.pan.dev/docs/documentation/pack-docs#readme-structure).

2022-05-26 13:19 UTC, merged