Replaced Demisto name
demisto/content pull request #17638
Opened 2022-02-13 16:42 UTC by dansterenson

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-03-22 21:22 UTC, anara123 commented on Packs/DemistoLocking/Integrations/CoreLock/DemistoLock.js
> +        integrationContext = getVersionedIntegrationContext(sync);
this integration is already packagified. 
Merge from master

2022-03-22 21:22 UTC, anara123 commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
> +  - name: core-api-multipart
Merge from master.

2022-08-31 16:34 UTC, ShahafBenYakir commented
@dansterenson @yaakovi @anara123 Is this waiting for another issue?

2022-08-31 16:36 UTC, dansterenson commented
@ShahafBenYakir  I think it is waiting for @anara123 to review the changes.

2022-08-31 19:10 UTC, anara123 requested changes

2022-09-04 17:01 UTC, dansterenson commented on Packs/CommonScripts/Scripts/ProvidesCommand/ProvidesCommand.yml
> +  - demisto-api-get
The script is used both for XSOAR and XSIAM and implemented in both of them. It should work in both of them, I just deleted the "using" integration.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/38375556/188324926-41c4ae62-2f59-4bb8-96c3-1db0c23bd1ea.png">

2022-09-04 18:22 UTC, anara123 approved these changes

2022-09-08 21:17 UTC, merged