FIxed bug where SQL returns 0 results
demisto/content pull request #17651
Opened 2022-02-14 11:29 UTC by aburt-demisto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/46679

## Description
Sets a variables default value that otherwise produces an error on 9 results returned.

## Screenshots
NA

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-14 15:44 UTC, yuvalbenshalom requested changes
hi @aburt-demisto,
please bump the version of the pack and add a release note file for the fix.

2022-02-14 17:40 UTC, aburt-demisto commented
@yuvalbenshalom bumped release notes.

2022-02-15 05:46 UTC, yuvalbenshalom approved these changes

2022-02-15 06:18 UTC, yuvalbenshalom commented on Packs/SecurityTrails/ReleaseNotes/1_1_1.md
> +- Updated the code to deal with an error when no results are returned using the SQL query function (securitytrails-sql-query)
```suggestion
- Fixed an issue where **securitytrails-sql-query** failed when the query returned an empty result.
```

2022-02-15 06:19 UTC, merged