Bug Jira - Get issue with attachment wrong url
demisto/content pull request #17670
Opened 2022-02-15 09:07 UTC by MLainer1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/46579

## Description
Wrong url when trying to get attachment of an issue when calling command get-issue
<img width="812" alt="image" src="https://user-images.githubusercontent.com/93524335/154028885-32c3de54-fdf1-4edf-a032-d41c1d599b80.png">
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/93524335/154029077-fba16330-c250-47d3-9124-aa2d865823f7.png">

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-15 16:18 UTC, jochman commented on Packs/Jira/Integrations/JiraV2/JiraV2_test.py
> +    get_issue("VIK-267", get_attachments="true")  # the command will fail if not doing a request with the proper url
```suggestion
    assert get_issue("VIK-267", get_attachments="true"), 'There was a request to the wrong url'
```

Much clearer when fails.

2022-02-15 16:19 UTC, jochman commented on Packs/Jira/Integrations/JiraV2/JiraV2_test.py
> +def test_get_issue_attachment_url(mocker, requests_mock):
Call the function in a describable name.

2022-02-16 10:24 UTC, ShacharKidor approved these changes

2022-02-17 09:56 UTC, avidan-H requested changes

2022-02-17 09:56 UTC, avidan-H commented on Packs/Jira/Integrations/JiraV2/test_data/raw_response.py
> +                   "timeZone": "Asia"
Be consistent with your quotation marks. They should either all be single quotes or double quotes - not a mixture of the two. The 'soon-to-be' official recommendation (it hasn't yet been added to the development conventions in the development docs yet) is to use single quotes.

2022-02-17 09:56 UTC, avidan-H commented on Packs/Jira/Integrations/JiraV2/test_data/raw_response.py
> +               }
This bracket's placement is misformatted.

2022-02-17 09:56 UTC, avidan-H commented on Packs/Jira/ReleaseNotes/1_4_8.md
> +- Fixed an issue where calling the command **get-issue** with *getAttachments="true"* returned an error.
```suggestion
- Fixed an issue where calling the **get-issue** command with *getAttachments="true"* caused an error.
```

2022-02-17 10:32 UTC, avidan-H requested changes

2022-02-17 10:32 UTC, avidan-H commented on Packs/Jira/Integrations/JiraV2/test_data/raw_response.py
> +            'timeZone': 'Asia'
Looks like some of this info is real(ish)... make sure to use fake information.

2022-02-20 09:55 UTC, avidan-H approved these changes

2022-02-20 11:46 UTC, merged