Update readme and metadata text
demisto/content pull request #17712
Opened 2022-02-16 16:19 UTC by L-Tan

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR updates the text copy in readme and metadata in the Penfield.AI marketplace offering to provide additional information and to reflect the requirement from PenfieldAI's marketing team.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-16 16:40 UTC, mchasepan requested changes
Reviewing this content with Rachel at Penfield.

2022-02-17 19:23 UTC, L-Tan commented
> Reviewing this content with Rachel at Penfield.

Thanks a lot @mchasepan and sorry about the poorly written text copy from our end. Our marketing team has updated the text copy and I've updated this PR accordingly. Please take a look again. Thank you so much!

2022-02-17 19:26 UTC, mchasepan approved these changes
Looks much better!

2022-02-20 06:14 UTC, yucohen approved these changes

2022-02-20 06:14 UTC, merged