Bug - Azure Sentinel fetch incidents - incidents do not get fetched by xsoar
demisto/content pull request #17783
Opened 2022-02-20 16:28 UTC by MLainer1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/46408

## Description
A bug where seemingly random incidents are not digested by fetch-incidents command

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-02-27 08:18 UTC, jochman commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
> +    demisto.debug(f"is_fetch_incidents:{is_fetch_incidents}, first_fetch:{first_fetch}")
```suggestion
    demisto.debug(f"{is_fetch_incidents=}, {first_fetch=}")
```
Sweet sweet python 3.8 syntax sugaring

2022-02-27 08:18 UTC, jochman commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
> +    demisto.debug(f"last fetch time is: {last_fetch_time}, last fetch ids are:{last_fetch_ids}")
```suggestion
    demisto.debug(f"{last_fetch_time=}, {last_fetch_ids=}")
```
Sweet sweet python 3.8 syntax sugaring

2022-02-27 08:18 UTC, jochman commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
> +        if incident.get('ID') not in last_fetch_ids and incident_severity >= min_severity and last_incident_number != incident.get('IncidentNumber'):
I think we might want to break it down into two functions -> by id order and by time order. Here we have two different flows combined, and it isn't apparent.

2022-02-27 14:00 UTC, jochman reviewed
looks fine. Please note the (redundant) extralogic with ids.

2022-03-07 14:41 UTC, dantavori requested changes
please apply the changes today so we can release this to customers asap

2022-03-07 14:41 UTC, dantavori commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
> +                  '$orderby': args.get('$orderby', ''),
```suggestion
                  '$orderby': args.get('orderby', 'properties/createdTimeUtc asc'),
```

2022-03-07 14:41 UTC, dantavori commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
> +        params = {'$filter': args.get('$filter', ''),
```suggestion
        params = {
            '$filter': args.get('filter', ''),
```
please stick to [pep8 style conventions](https://www.python.org/dev/peps/pep-0008/#indentation) (also verify your other changes)

2022-03-07 14:41 UTC, dantavori commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
> +                    '$orderby': 'properties/createdTimeUtc asc'}
```suggestion
    command_args = {'filter': f'properties/createdTimeUtc ge {latest_created_time_str}',
                    'orderby': 'properties/createdTimeUtc asc'}
```

2022-03-07 14:41 UTC, dantavori commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
> +        An array of incidents, and a latest created time.
```suggestion
        (tuple): 1. The LastRun object updated with the last run details.
                 2. An array of incidents.
```

2022-03-07 16:30 UTC, dantavori approved these changes
great, before merging make sure it works properly in your env

2022-03-07 19:49 UTC, merged