New command core-get-dynamic-analysis
demisto/content pull request #17859
Opened 2022-02-24 19:49 UTC by bziser

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/46915

## Description
New command core-get-dynamic-analysis

2022-02-24 20:40 UTC, bziser commented
Checked with @altmannyarden  on the env that the command is working.

2022-02-27 06:34 UTC, yuvalbenshalom requested changes
looks good.

2022-02-27 06:34 UTC, yuvalbenshalom commented on Packs/Core/ReleaseNotes/1_0_2.md
> +- Added new command: core-get-dynamic-analysis
pleas
```suggestion
- Added the ***core-get-dynamic-analysis*** command, that returns the dynamic analysis of an alert.
```

2022-02-27 11:27 UTC, yuvalbenshalom approved these changes

2022-02-27 12:07 UTC, merged