[TaegisXDR] Major version update
demisto/content pull request #17865
Opened 2022-02-25 13:53 UTC by rreed42

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This update includes:

* Added support for "Fetch Incidents"
* Added support for bypassing certificate verification
* Replaced the "Service URL" input with "Taegis Environment"
* Added 2 new commands (taegis-execute-playbook and taegis-fetch-playbook-execution)
* Updated 2 existing commands (taegis-fetch-investigation-alerts and taegis-fetch-investigation)

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [x] Yes
       - This replaces the previous "Service URL" with "Environment" in the integration configuration which will break on upgrade. The previous "Service URL" was utilized prior to our release of multiple environments. Unfortunately, this meant that links back to the non-US1 environments did not function as there were no mappings to the other 2 environments. This change asks less of the customer/user while ensuring the correct API and portal URLs.
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation

2022-02-28 07:07 UTC, yucohen commented
@rreed42 Looks great! Lets set up a quick demo

2022-03-02 13:08 UTC, rreed42 commented
> @rreed42 Looks great! Lets set up a quick demo

@yucohen Sure thing. Can you email me at rreed@secureworks.com and we can set up a quick time?

2022-03-08 15:43 UTC, yucohen requested changes
@rreed42 Great work!
Please address the changes (dont forget to make sure the fetch works properly after) and than we can merge this

2022-03-08 15:43 UTC, yucohen commented on Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
>          else:
```suggestion
        elif command == "fetch-incidents":
            fetch_incidents(client, environment, max_fetch)
        else:
```

2022-03-08 15:43 UTC, yucohen commented on Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
>      PARAMS = demisto.params()
```suggestion
    PARAMS = demisto.params()
    max_fetch = PARAMS.get('max_fetch')
```

2022-03-08 15:43 UTC, yucohen commented on Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
> +def fetch_incidents(client: Client, env: str, args=None):
```suggestion
def fetch_incidents(client: Client, env: str, page_size: int):
```

2022-03-08 15:43 UTC, yucohen commented on Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
> +    page_size = args.get("max_fetch", 200)
```suggestion
```

2022-03-08 15:43 UTC, yucohen commented on Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
> +        raise ValueError(f"Error when fetching investigations: {result['errors'][0]['message']}")
```suggestion
        raise DemistoException(f"Error when fetching investigations: {result['errors'][0]['message']}")
```

2022-03-08 15:43 UTC, yucohen commented on Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
> +        variables["createdAfter"] = start_time
```suggestion
    variables["createdAfter"] = start_time
```

2022-03-08 15:43 UTC, yucohen commented on Packs/SecureWorks/Integrations/TaegisXDR/TaegisXDR.py
> +        variables["createdAfter"] = start_time
when we dont have the "last_run", then the start time should be this set (so we wont get older incidents)

2022-03-10 08:08 UTC, yucohen approved these changes

2022-03-10 08:08 UTC, merged