Vectra fetch incident sort fix
demisto/content pull request #17895
Opened 2022-02-28 15:29 UTC by barchen1

## Status
- [x] In Progress
- [ ] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/38684

## Description
Added a fix for the fetch incidents command - Added the `order_field` to the fetch params so the incidents will be sorted by `last_timestamp` field. 

## Does it break backward compatibility?
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2022-02-28 15:56 UTC, barchen1 commented
@guykeller SDK-validate failed cause `The integration Vectra v2 is currently in skipped`.

2022-03-01 16:05 UTC, guykeller requested changes

2022-03-01 16:05 UTC, guykeller commented on Packs/Vectra/Integrations/Vectra_v2/Vectra_v2.py
> +        demisto.debug(f'\n\nparams: {params}\n\n')
If we want to leave this here let's remove the newline chars and write a better message

2022-03-01 16:05 UTC, guykeller commented on Packs/Vectra/Integrations/Vectra_v2/Vectra_v2.py
> +
intentional?

2022-03-06 14:24 UTC, guykeller approved these changes

2022-03-06 14:52 UTC, guykeller commented
@yuvalbenshalom Can we please force merge? I'm accountable.
The integration needs to stay skipped.

2022-03-07 08:41 UTC, merged