Symantec DLP v2
demisto/content pull request #18100
Opened 2022-03-14 12:39 UTC by barchen1

## Status
- [x] In Progress
- [ ] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/25659

## Description
Symantec DLP v2

## Screenshots
![Screen Shot 2022-03-14 at 12 47 47](https://user-images.githubusercontent.com/54398957/158173433-f1b74854-9f91-4f36-a295-248603092d86.png)
![Screen Shot 2022-03-14 at 14 35 11](https://user-images.githubusercontent.com/54398957/158173452-282c74f3-f799-495b-80ba-e27921d593e6.png)
![Screen Shot 2022-03-14 at 14 35 36](https://user-images.githubusercontent.com/54398957/158173455-b0777a36-e145-4bc3-bbbe-b8aace34e009.png)
![Screen Shot 2022-03-14 at 14 37 49](https://user-images.githubusercontent.com/54398957/158173801-dd53c91a-0e6e-4931-a6ab-93dd51890c95.png)

## Minimum version of Cortex XSOAR
- [x] 6.0.0

## Must have
- [x] Tests
- [x] Documentation

2022-03-20 05:27 UTC, guykeller requested changes

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    Builds the custom_attributes_list that the user wants to update.
let's enhance the docstring here

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    limit = arg_to_number(args.get('limit', 50))
How big can the number of results be, in theory?

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +
No space between the if and the else please, it's one block

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    return ''
Can that final return statement ever happen or is it unreachable code?

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    incidents_data_list = client.get_incidents_request(creation_date=last_update_time, status_id=incident_status_id,
Let's improve the variable's name

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +        incident_types = [INCIDENT_TYPE_MAPPING[incident_type] for incident_type in incident_types]
let's add an empty line after each if block

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    if incidents_data_list:
Why is this line necessary? can `incidents_data_list` be `None` or just empty?

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +            if is_incident_already_fetched_in_previous_fetch(last_update_time, incident_creation_time, last_incident_id,
When and why would that happen?

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    from Symantec DLP and uploads them to Cortex XSOAR server.
Add a more detailed explanation about how the fetch works and why.
For example, why we might have already fetched incidents found more than once.
Non trivial knowledge that can't be reflected in the code should be recorded in the docstring

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    Create incident details dict for each incident pulled from the fetch
Document the 401 issue in the docstring with a detailed explanation

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +                                                       incident_type=incident_type)
We see these 3 lines in more than one location, let's convert them to an external function called `get_full_incident_details` or some better name, with a suitable docstring

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +            incident_details = get_details_unauthorized_incident(incident)
else?

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    """
1. remove the docstring please
2. Let's make sure we also check the validity of params in the test module

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +                last_incident_id = incident_id
Why do we need both the time and the ID if we only compare the ID?
Let's discuss this logic as a whole flow

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
> +    should run the command `symantec-dlp-list-incident-status`
let's discuss

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
> +  - High
No `additionalinfo`?

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
> +      description: Get incidents with creation date later than specified. Support
```suggestion
      description: The earliest time from which to get incidents. Supports
```

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2_test.py
> +def test_fetch_incidents__single(requests_mock):
Why the double underscore in the name, here and everywhere?

2022-03-20 05:27 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2_test.py
> +def test_fetch_incidents__last_run_no_fetch(requests_mock):
Let's discuss the test cases for the fetch mechanism

2022-03-28 08:09 UTC, barchen1 commented
@jrosenpanw Can you please go over the docs files?
Thanks!

2022-03-31 06:11 UTC, guykeller requested changes

2022-03-31 06:11 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    return ''
We said we'll remove this

2022-03-31 06:11 UTC, guykeller commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2_test.py
> +def test_fetch_incidents__single(requests_mock):
change it please

2022-03-31 08:46 UTC, richardbluestone commented
I've approved the docs. I couldn't edit this one (only view) but it looks ok.
![image](https://user-images.githubusercontent.com/53567272/161015047-af44fa40-8353-4e08-a40d-4efd7f8d9fca.png)

2022-04-04 07:10 UTC, barchen1 commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    if last_run and last_run.get('last_incident_creation_time'):
no, changed

2022-04-05 11:55 UTC, barchen1 commented
@guykeller @meital-aizen I changed the fetch-incidents function because of the issue we talked about. (Incident's ID and creation date are not synchronised)
I added a note about it in the README file as well.
Let me know if there is anything you would like me to add/change.

2022-04-10 08:44 UTC, barchen1 commented on Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
> +    return last_update_time and last_update_time >= incident_creation_date
our assumption is that incidents are not created at the exact time (even if it's one millisecond difference).
@meital-aizen FYI

2022-04-10 09:03 UTC, guykeller approved these changes

2022-04-10 09:08 UTC, barchen1 commented
@yuvalbenshalom We will need a force merge here - error on SDK-validate
![Screen Shot 2022-04-10 at 12 08 01](https://user-images.githubusercontent.com/54398957/162611073-7140903b-11c9-4772-b3f7-e293bcf242fd.png)

FYI @dorschw

2022-04-11 07:11 UTC, merged