Di davidr patch 1
demisto/content pull request #18253
Opened 2022-03-22 15:44 UTC by DI-davidr

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
The current integration package of DeepInstinct (DI) only runs on an unsupported version of the DI platform.  This PR allow this package to work with currently supported versions of DI.  This current package needs to replace the current DeepInstinct integration package currently available in the marketplace.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [x ] Yes
       - Further details: There is no backward compatibility with current version in the marketplace.  The current integration package of DeepInstinct (DI) only runs on an unsupported version of the DI platform.  This PR allow this package to work with currently supported versions of DI
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-03-22 21:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=18253) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=18253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=18253) it.</sub>

2022-03-28 09:42 UTC, yucohen requested changes
Great work! please address my comments, and change the yml as discussed in slack

2022-03-29 21:57 UTC, DI-davidr commented
Hi @yucohen,

I think I made and submitted the changes you requested (I’m still new to the Github process) with respect to the duplicate comment fields.  The Limit argument and sort features are already included in the API response, so we didn’t feel a need to add them at this time.

With regard to the latest Docker image how do I know when this has been updated, or how can I ensure it stays current?

Deep Regards,

David Ramirez
Professional Services Engineer, DEEP INSTINCT
M             +1.916.743.5946 

***@***.***

Read<https://www.gartner.com/reviews/market/endpoint-protection-platforms/vendor/deep-instinct/product/deep-instinct> our reviews on Gartner Peer Insights.
Subscribe<https://www.deepinstinct.com/blog/> to the Deep Instinct Blog.

From: yucohen ***@***.***>
Sent: Monday, March 28, 2022 2:43 AM
To: demisto/content ***@***.***>
Cc: David Ramirez ***@***.***>; Mention ***@***.***>
Subject: Re: [demisto/content] Di davidr patch 1 (PR #18253)


@yucohen requested changes on this pull request.

Great work! please address my comments, and change the yml as discussed in slack

________________________________

In Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.py<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23discussion_r835893732&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C637840573678599337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8VzboRpOXrGGg1nNTwwsY0TnCHihYSt2IyEKo8k6SlA%3D&reserved=0>:

> +        """

+         test module

+        """

please add this to the test_module() method and remove from main

________________________________

In Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.py<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23discussion_r835897925&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C637840573678599337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3xbghOfYdhe6VUz4OfS72KgwgiyDXogmcbYw1yqEUTs%3D&reserved=0>:

> +        """

+        Get device by id

+        """

we can remove this, as it is already in the method. relevant for all other as well

________________________________

In Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.py<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23discussion_r835916899&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C637840573678599337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nd8BnFoEaSK6ZBsups2WCiZyQRq8xLg8DyW5Yk4vn2M%3D&reserved=0>:

> +    """

+    event_ids_input = demisto.args().get('event_ids')

+    event_ids = [int(num) for num in event_ids_input.split(",")]

+    http_request('POST', '/events/actions/close', json={"ids": event_ids})

+    demisto.results('ok')

+

+

+def fetch_incidents():

+    incidents = []

+    last_id = demisto.params().get('first_fetch_id')

+

+    last_run = demisto.getLastRun()

+    if last_run and last_run.get('last_id') is not None:

+        last_id = last_run.get('last_id')

+

+    events = http_request('GET', '/events?after_event_id=' + str(last_id))

is this list sorted? if not, we can miss some events..

________________________________

In Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.py<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23discussion_r835917091&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C637840573678599337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BOcURpROMEftVdSuylY7q0Gdvz7DpUVJ86MSqnbTmes%3D&reserved=0>:

> +        """

+        get_specific_device()

+

+    if demisto.command() == 'deepinstinct-get-events':

+        """

+        Get events

+        """

+        get_events()

+

+    if demisto.command() == 'deepinstinct-get-suspicious-events':

+        """

+        Get events

+        """

+        get_suspicious_events()

+

+    if demisto.command() == 'deepinstinct-get-all-groups':

consider adding limit argument to this command

________________________________

In Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.py<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23discussion_r835917101&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C637840573678599337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e53sv1gdPG4de2X4JY6fKxRdlVuVxMWCHB5oIM4LrzU%3D&reserved=0>:

> +        """

+        get_events()

+

+    if demisto.command() == 'deepinstinct-get-suspicious-events':

+        """

+        Get events

+        """

+        get_suspicious_events()

+

+    if demisto.command() == 'deepinstinct-get-all-groups':

+        """

+        Get all groups

+        """

+        get_all_groups()

+

+    if demisto.command() == 'deepinstinct-get-all-policies':

consider adding limit argument to this command

________________________________

In Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.py<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23discussion_r835917144&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C637840573678758122%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=klE%2Bgzroaq52mwIR2IME00HQPlZcIcFyvdJnj2yGi2M%3D&reserved=0>:

> +

+def main():

+    # Commands

+    if demisto.command() == 'test-module':

+        """

+         test module

+        """

+        test_module()

+

+    if demisto.command() == 'deepinstinct-get-device':

+        """

+        Get device by id

+        """

+        get_specific_device()

+

+    if demisto.command() == 'deepinstinct-get-events':

consider adding limit argument to this command

________________________________

In Packs/DeepInstinct/Integrations/DeepInstinct-3x/DeepInstinct.yml<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23discussion_r835919050&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C637840573678758122%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SRPE1i6nMjx4cYvidTWRyJqogd0KrL6%2F8k2yS2NLVaQ%3D&reserved=0>:

> +  - name: deepinstinct-remove-device

+    arguments:

+    - name: device_id

+      required: true

+    description: uninstall D-Client

+  - name: deepinstinct-upload-logs

+    arguments:

+    - name: device_id

+      required: true

+    description: upload logs from D-Client

+  - name: deepinstinct-remote-file-upload

+    arguments:

+    - name: event_id

+      required: true

+    description: upload file from Event Id

+  dockerimage: demisto/python3:3.9.9.25564

why not use the latest docker image?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdemisto%2Fcontent%2Fpull%2F18253%23pullrequestreview-922439399&data=04%7C01%7Cdavid.ramirez%40deepinstinct.com%7Cbd595cc84ebb4b25ea3308da109f4f62%7Cd1509054f881493e9d8ee69932e4e865%7C0%7C0%7C63784057367 [...]

2022-05-15 07:59 UTC, yucohen approved these changes

2022-05-15 07:59 UTC, merged