Rasterize update selenium to version 4
demisto/content pull request #18275
Opened 2022-03-24 06:28 UTC by MosheEichler

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/47423

## Description
Updated to selenium 4

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-03-24 06:39 UTC, MosheEichler commented on Packs/rasterize/Integrations/rasterize/rasterize.yml
> +  dockerimage: devdemisto/chromium:1.0.0.27660
This is not the correct one. I'll change it once the docker pr will be merged, and we will get the correct docker image.

2022-03-27 05:06 UTC, yaakovi requested changes
update docker image

2022-04-03 04:55 UTC, yaakovi approved these changes

2022-04-03 06:54 UTC, glicht commented
@MosheEichler there is a newer version of the docker: demisto/chromium:1.0.0.27948 

@wissamg FYI

2022-04-10 07:26 UTC, closed without merging