Initial commit
demisto/content pull request #18339
Opened 2022-03-29 11:11 UTC by PSayenka

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Initial BMC Discovery Integration PR

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [x ] Tests
- [ x] Documentation

2022-03-29 11:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=18339) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=18339) before we can accept your contribution.<br/><hr/>**psayenka** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=18339) it.</sub>

2022-04-11 06:25 UTC, yaakovi reviewed
very nice work!
see my comments

2022-04-11 06:25 UTC, yaakovi commented on package-lock.json
>    "version": "1.0.0",
restore this file

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/README.md
> +BMC Discovery is a SaaS-based, cloud-native discovery and dependency modeling system that provides instant visibility into hardware, software, and service dependencies across multi-cloud, hybrid, and
* Use line 1 as the pack description.
* Move line 2 to the integration README.md file.

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.yml
> +  display: Use system proxy settings
```suggestion
- display: Use system proxy settings
```

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.yml
> +  display: Trust any certificate (not secure)
```suggestion
- display: Trust any certificate (not secure)
```

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.yml
> +description: BMC Discovery Integration
use the description you have in the README

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.yml
> +  #    type: Boolean
Remove if not needed

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.py
> +        ranges = list(args.get('ranges', '').split(','))
You can use `argToList` instead.

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.py
> +            raise e
```suggestion
            raise
```

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.py
> +            output['data'].append(result)
you can use `remove_nulls_from_dictionary`.

2022-04-11 06:25 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.py
> +        demisto.error(traceback.format_exc())
```suggestion
        demisto.error(fix_traceback_line_numbers(traceback.format_exc()))
```

2022-04-11 06:32 UTC, yaakovi requested changes

2022-04-11 06:32 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.yml
> +fromversion: 6.0.0
```suggestion
fromversion: 6.1.0
```

2022-04-11 06:32 UTC, yaakovi commented on Packs/BMCDiscovery/TestPlaybooks/BMC_Discovery_-_Test.yml
> +fromversion: 6.0.0
```suggestion
fromversion: 6.1.0
```

2022-04-12 10:43 UTC, PSayenka commented on package-lock.json
>    "version": "1.0.0",
Thank you! Will do.

2022-04-18 09:24 UTC, yaakovi approved these changes

2022-04-18 09:24 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.yml
> +name: bmcdiscovery
```suggestion
name: BMC Discovery
```

2022-04-18 09:24 UTC, yaakovi commented on Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery.yml
> +  id: bmcdiscovery
```suggestion
  id: BMC Discovery
```

2022-04-21 11:12 UTC, merged