New netskope
demisto/content pull request #18355
Opened 2022-03-29 22:30 UTC by RazOmry

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation

2022-04-24 16:11 UTC, yaakovi commented on Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.py
> +    outputs = sum((client['attributes'].get('users') for client in response['data']), [])
Nice use of sum 😎

2022-04-25 06:52 UTC, tomer-pan commented on Packs/Netskope/IncidentFields/incidentfield-Netskope_Action.json
> +{
@RazOmry Please use the common field "Action" instead creating a new one.

2022-04-25 06:53 UTC, tomer-pan commented on Packs/Netskope/IncidentFields/incidentfield-Netskope_Event_Type.json
> +{
@RazOmry Please use the common field "Event Type" instead creating a new one.

2022-04-27 10:56 UTC, idovandijk commented on Packs/Netskope/IncidentFields/incidentfield-Netskope_Access_Method.json
> +        "Netskope Qurantine"
Might want to fix typo here - Quarantine

2022-04-27 10:58 UTC, idovandijk commented on Packs/Netskope/IncidentFields/incidentfield-Netskope_Quarantine_File_ID.json
> +        "Netskope Qurantine"
Fix typo - Quarantine

2022-04-27 10:58 UTC, idovandijk commented on Packs/Netskope/IncidentFields/incidentfield-Netskope_Quarantine_Policy.json
> +        "Netskope Qurantine"
Same typo

2022-04-27 10:58 UTC, idovandijk commented on Packs/Netskope/IncidentFields/incidentfield-Netskope_Quarantine_Profile.json
> +        "Netskope Qurantine"
same

2022-04-27 10:58 UTC, idovandijk commented on Packs/Netskope/IncidentFields/incidentfield-Netskope_Quarantine_Profile_ID.json
> +        "Netskope Qurantine"
same

2022-04-27 10:59 UTC, idovandijk commented on Packs/Netskope/Classifiers/classifier-NetSkope_Classifier.json
> +        "quarantine": "Netskope Qurantine",
Not sure if intentional - should be Quarantine I assume

2022-04-27 11:00 UTC, idovandijk commented on Packs/Netskope/Classifiers/classifier-NetSkope_Mapper.json
> +        "Netskope Qurantine": {
same

2022-04-27 11:02 UTC, idovandijk requested changes
Not sure if that is a trailing error but there are multiple references to "Qurantine" type instead of "Quarantine", please double check where needed

2022-04-27 20:28 UTC, RazOmry commented on Packs/Netskope/Integrations/NetskopeAPIv1/NetskopeAPIv1.py
> +            event['incident_type'] = event_type
No. The goal of this loop is to add `event_id` and `incident_type` keys into the existing event. It is not a new object, just modifying the existing one.

2022-04-28 08:52 UTC, idovandijk reviewed
From my side this is good to go. @yaakovi if you're also done feel free to approve

2022-04-28 21:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=18355) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=18355) before we can accept your contribution.<br/>**5** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: RazOmry<br/>:white_check_mark: daryakoval<br/>:white_check_mark: content-bot<br/>:white_check_mark: abaumgarten<br/>:white_check_mark: MosheEichler<br/>:x: AradCarmi<br/>:x: rshunim<br/>:x: ssokolovich<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=18355) it.</sub>

2022-05-01 14:02 UTC, DanilVil commented on Packs/Netskope/Integrations/NetskopeAPIv1/README.md
> +Update file hash list with the values provided.
@RazOmry We need to state that the update action will rewrite the existing values in the list and doesn't add to them.

2022-05-01 14:04 UTC, DanilVil requested changes
ן

2022-05-01 14:04 UTC, DanilVil commented on Packs/Netskope/Integrations/NetskopeAPIv1/README.md
> +`netskope-url-list-update`
@RazOmry We need to state that the update action will rewrite the existing values in the list and doesn't add to them.

2022-05-01 14:04 UTC, DanilVil commented on Packs/Netskope/Integrations/NetskopeAPIv1/README.md
> +### netskope-file-hash-list-update
@RazOmry We need to state that the update action will rewrite the existing values in the list and doesn't add to them.

2022-05-12 06:07 UTC, merged