Fix same data diff format bug
demisto/content pull request #18444
Opened 2022-04-05 10:47 UTC by YuvHayun

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [47531]https://github.com/demisto/etc/issues/47531

## Description
At last, Only added a beta label to IP-API and reformatted the *Location* key for **Ipstack** IP indicator.

## Does it break backward compatibility?
   - [X] Yes
       - Further details:
       the *Location* key for **Ipstack** IP indicator will now be in the format of `latitude:longitude` instead of 
      `latitude,longitude`.
   - [ ] No

2022-04-07 00:59 UTC, mwareman commented on Packs/IP-API/Integrations/IPAPI/IPAPI.yml
> +  This service is not following context standards, hence not recommended to use.
Why is this placed in my code?

2022-04-07 00:59 UTC, mwareman commented on Packs/IP-API/Integrations/IPAPI/IPAPI.yml
> +display: IP-API (beta)
This is NOT BETA - please revert.

2022-04-07 00:59 UTC, mwareman commented on Packs/IP-API/ReleaseNotes/1_0_2.md
> +- Beta. it is not following context standards, hence not recommended to use.
Not BETA. Why was this added to my code?

2022-04-07 01:00 UTC, mwareman commented on Packs/IP-API/ReleaseNotes/1_0_2.md
> +##### IP-API (beta)
Not BETA - Please revert

2022-04-07 01:03 UTC, mwareman requested changes
The changes to IPSTACK do NOT require any changes to IP-API. Please revert changes commenting that the code is BETA (it's not) and not conforming to the output of another unrelated integration.

Thank you.

2022-04-11 09:01 UTC, ShahafBenYakir approved these changes
Very nice! 
See my small comments

2022-04-11 09:01 UTC, ShahafBenYakir commented on Packs/Ipstack/ReleaseNotes/1_0_6.md
> +- Added *integrationReliability* integration parameter for the DbotScore calculations.
```suggestion
- Added *Source Reliability* integration parameter for the DbotScore calculations.
```

2022-04-11 10:00 UTC, YuvHayun commented on Tests/known_words.txt
> +C
it did

2022-04-11 10:53 UTC, YuvHayun commented
@ShahafBenYakir  I need force merge on this PR.

2022-04-11 12:02 UTC, merged