Update module health in qradar
demisto/content pull request #18593
Opened 2022-04-14 12:59 UTC by ilaner

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/47974

## Description
Adding a log to `demisto.updateModuleHealth`
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation 

FYI, @tkatzir @DeanArbel

2022-04-17 10:15 UTC, tkatzir requested changes

2022-04-17 10:15 UTC, tkatzir commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> +            demisto.updateModuleHealth(f'Error occurred during long running loop: {e}')
Use the same message (with the Exception) in both `demisto.updateModuleHealth` and `demisto.error`

2022-04-19 14:33 UTC, DeanArbel approved these changes

2022-04-19 14:34 UTC, DeanArbel commented on Packs/QRadar/ReleaseNotes/2_1_36.md
> +- Added the error message to `updateModuleHealth` when long runing is failing.
```suggestion
- Added an error message that will be displayed via `updateModuleHealth` when **fetch-incidents** is failing.
```

2022-04-20 19:06 UTC, tkatzir approved these changes

2022-04-25 19:15 UTC, merged