added File enrichment
demisto/content pull request #18614
Opened 2022-04-17 11:16 UTC by k1r10n

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: only docker image updated

## Description
Add a new command + update docs

## Screenshots
<img width="923" alt="xsoar-rst-pack-1 1 0" src="https://user-images.githubusercontent.com/20074222/163712035-d8f6ad55-d4e9-485d-bbfa-7aaaa52f46b1.png">

## Minimum version of Cortex XSOAR
- [ X ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ X ] Yes
       - Further details:
   - [ ] No

## Must have
- [ X ] Tests
- [ X ] Documentation

2022-04-17 11:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=18614) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=18614) before we can accept your contribution.<br/><hr/>**kirion** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=18614) it.</sub>

2022-04-20 12:06 UTC, k1r10n commented
Hi @MLainer1, please advise me if anything else is needed to be updated

2022-04-20 14:01 UTC, MLainer1 requested changes
Good work!
I'm not sure if the data from the test data is real or not, make sure to mock it so you won't have secrets in the pack.

2022-04-22 11:03 UTC, k1r10n commented on Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI.py
> +                     'Last Seen': time.strftime('%Y-%m-%d', time.localtime(int(indicator.get('lseen', '')))),
fixed int() and mocked the data

2022-04-27 11:28 UTC, k1r10n commented
thanks @MLainer1. Anything else to be updated from our side?

2022-04-27 11:33 UTC, MLainer1 commented
> thanks @MLainer1. Anything else to be updated from our side?

No, let's schedule a demo, I'll send you a message

2022-05-10 08:39 UTC, tomer-pan commented
Hi @k1r10n 
Per our last demo, I remember we agreed on 2 changes:
1) Use the `IsIntegrationAvailable` automation for checking if the instance is active.
2) Change the "File Enrichment" playbook input to accept hashes and not a file object.

I also told you that I will check whether it's possible to check all of the inputs with one task and seems like you can use the `SetIfEmprty` transformer in order to choose the first supplied value.
So for example if you have sha256/sha1/md5 as playbook inputs, you would first check if either of them exist:
![image](https://user-images.githubusercontent.com/81556849/167586467-a9e5ff57-f3d2-4d39-bb32-2c8a5b5fa1d7.png)

And then you would run the "file" command with either one of them which exist:
![image](https://user-images.githubusercontent.com/81556849/167586572-0106b051-fee6-4856-b040-9c0553f35254.png)

2022-05-10 11:32 UTC, k1r10n commented
Thank you for the update. Incorporated `IsIntegrationAvailable` function and `SetIfEmpty` as suggested. However, I kept File as input and then checking for md5/sha25/sha1 existence 


![image](https://user-images.githubusercontent.com/20074222/167618174-595a30e0-5257-4e64-933a-11adc4cdc9e0.png)
![image](https://user-images.githubusercontent.com/20074222/167618197-f96bcdf5-d73f-40e5-8749-78b6eef6d46f.png)

![image](https://user-images.githubusercontent.com/20074222/167617810-16f1d88a-df8c-4ba9-a337-64cb0f584e64.png)

2022-05-10 12:03 UTC, k1r10n commented
As it is designed to be working as a subplaybook, it should be easier to invoke it and pass File to the input rather than creating a complex input definition to pass all possible hash types: md5, sha1, sha256

2022-05-10 12:25 UTC, tomer-pan commented
> As it is designed to be working as a subplaybook, it should be easier to invoke it and pass File to the input rather than creating a complex input definition to pass all possible hash types: md5, sha1, sha256

Oh okay, I just saw that you are referring to the hashes through the "File" object. Im not sure it's the best idea since it is limiting (if no File object exist, it will not run although you might have hashes in other keys/objects in the context in some scenarios) but this is your call.

2022-05-10 12:27 UTC, k1r10n commented
yes, please see the first step, it checks File object existence as well

2022-05-10 12:41 UTC, tomer-pan approved these changes

2022-05-10 21:11 UTC, k1r10n commented
@MLainer1 Yes, please, merge it. The other scenario is covered by the default "File Enrichment - File reputation" playbook which accepts hashes as an input and uses the 'FileReputation' automation script that covers the case mentioned by @tomer-pan 

Thank you for your support!

2022-05-10 22:00 UTC, MLainer1 approved these changes

2022-05-10 22:00 UTC, merged