feat(intezer): add url analysis support
demisto/content pull request #18612
Opened 2022-04-17 10:04 UTC by davidt99

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Add support for URL analysis in Intezer

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Documentation

2022-04-17 13:46 UTC, davidt99 commented
@yaakovi the build passes now, would like your review :pray:

2022-04-18 15:14 UTC, davidt99 commented
@MLainer1 would appreciate your review :pray:

2022-04-20 07:09 UTC, davidt99 commented
@MLainer1 ping

2022-04-20 09:41 UTC, MLainer1 commented
> @MLainer1 ping

I'm on it.

2022-04-20 11:49 UTC, MLainer1 requested changes
Great work :), let's schedule a demo for next week

2022-04-20 11:49 UTC, MLainer1 commented on Packs/Intezer/Integrations/IntezerV2/IntezerV2.py
> +    md = tableToMarkdown('Analysis Report', intezer_result, url_keys=('analysis_url',))
```suggestion
    md = tableToMarkdown('Analysis Report', intezer_result, url_keys=('analysis_url'))
```

2022-04-24 11:00 UTC, davidt99 commented
@MLainer1 sure, email me :)

2022-04-24 11:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=18612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=18612) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: content-bot<br/>:white_check_mark: davidt99<br/>:white_check_mark: MosheEichler<br/>:x: DinaMeylakh<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=18612) it.</sub>

2022-04-28 06:51 UTC, MLainer1 approved these changes

2022-04-28 06:53 UTC, merged