Failed jobs notifier
demisto/content pull request #18623
Opened 2022-04-17 13:48 UTC by Noy-Maimon

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

Added the `dmst-build` channel to also receive notifications for failed jobs that are sent to `dmst-content-team`.

2022-04-17 16:00 UTC, tkatzir requested changes
Looks good.
Why is the `Packs/Alexa/ReleaseNotes/2_0_9.md` file in this PR?

2022-04-18 06:37 UTC, Noy-Maimon commented
> Looks good. Why is the `Packs/Alexa/ReleaseNotes/2_0_9.md` file in this PR?

For testing purposes (these changes causes the pack to fail).

2022-04-18 07:27 UTC, yaakovi approved these changes

2022-04-18 07:27 UTC, yaakovi commented on Tests/scripts/gitlab_slack_notifier.py
> +        }
```suggestion
            'attachments': slack_msg_data,
        },
```

2022-04-18 15:16 UTC, merged