Contrib/CDS Flashpoint Add Headers
demisto/content pull request #18651
Opened 2022-04-19 04:43 UTC by crestdatasystems

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
1. Add headers in the requests to the API.
2. Resolve the non-highlighting keyword in the layout issue.
3. Update script as per latest linting standards.
4. Replace integration image with a one with dimension 120x50.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-05-01 13:44 UTC, MLainer1 requested changes
Good work :), Let's schedule a short demo

2022-05-02 08:42 UTC, crestdatasystems commented on Packs/Flashpoint/Integrations/Flashpoint/Flashpoint.py
> +            args[arg] = args[arg].strip()
Yes, arg is a dictionary. Great suggestion, we should do this.

2022-05-03 15:23 UTC, MLainer1 commented
We'll schedule a demo after the new changes will be pushed and reviewed

2022-05-16 17:11 UTC, ShacharKidor requested changes
Hi, 
I added a little suggestion. 

Please let me know when you will be done adding your additional changes.

2022-05-23 07:53 UTC, crestdatasystems commented on Packs/Flashpoint/Integrations/Flashpoint/Flashpoint.py
> +    limit = args.get('limit', 10)
Invalid values for the argument limit are handled on the API side. The error message shown is more verbose than the one we get from arg_to_number. Considering that, and the updated standard of having less validation on the XSOAR side, shall we make this change?
![image](https://user-images.githubusercontent.com/60967033/169770396-5a518e08-e394-4719-a395-cf417b5c2468.png)

2022-05-23 10:42 UTC, crestdatasystems commented on Packs/Flashpoint/Integrations/Flashpoint/Flashpoint.py
> +    limit = args.get('limit', 10)
The API will have takes limit as a query parameter which will not differentiate between an integer and a string. Therefore, it is not necessary for us to convert the value into a python integer (we would do it if the limit is passed in the body or perform any validation).

2022-05-25 18:38 UTC, ShacharKidor approved these changes
Hi @crestdatasystems,
Great Job!

Let's have a demo - I can schedule it for tomorrow (Thursday) or for Sunday at 17:00 PM (Israel local time), which option do you prefer?

2022-05-26 08:44 UTC, ShacharKidor commented
A Demo was scheduled for Monday (30.05) at 16:00 pm (Israel local time).

2022-05-30 08:04 UTC, crestdatasystems commented on Packs/Flashpoint/ReleaseNotes/1_3_2.md
> +- Introduced the third type of ip (ip-dst|port) in ip command query and human-readable deeplink.
Okay, will add that.

2022-05-30 13:46 UTC, MLainer1 approved these changes

2022-05-31 07:18 UTC, merged