Azure log analytics client credentials
demisto/content pull request #18717
Opened 2022-04-24 23:02 UTC by merit-maita

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/46718

## Description
added client credentials flow.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-05-03 07:39 UTC, bakatzir commented
Adding Shirley, as this is a popular pack in MP, we want to revamp the pack readme.

2022-05-09 21:01 UTC, yaakovi requested changes
this is breaking changes, let discuss it

2022-06-07 11:44 UTC, yucohen approved these changes

2022-06-14 16:41 UTC, yaakovi approved these changes

2022-06-14 16:41 UTC, merged

2022-06-14 16:41 UTC, yaakovi commented
validation failed on BC checks