draft pr - ews mail sender crash
demisto/content pull request #18784
Opened 2022-04-27 07:32 UTC by YuvHayun

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [#48170](https://github.com/demisto/etc/issues/48170)

## Description
I reproduced the bug, I believe it occur because extracting the addresses using `split(",")`

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

2022-04-27 08:52 UTC, ShahafBenYakir commented on Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.py
> +    return list(filter(None, addresses_str.split(",")))
Let's add logs printing of the address_str before the return so in case the fix will not solve the issue you have better logs

2022-05-29 13:46 UTC, ShahafBenYakir requested changes
We are missing a test that reproduces the issue no?

2022-05-29 14:10 UTC, YuvHayun commented
> We are missing a test that reproduces the issue no?

I added a test related to the fix

2022-05-29 16:46 UTC, ShahafBenYakir commented on Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender_test.py
> +        to and subject arguments to send an email.
```suggestion
        a 'subject' which is 'test' and 'to' which is 'test@gmail.com,' (ending with a comma),
```

2022-05-29 16:47 UTC, ShahafBenYakir approved these changes

2022-06-02 07:26 UTC, merged