OTRS bug fix
demisto/content pull request #18877
Opened 2022-05-02 14:21 UTC by dansterenson

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://github.com/demisto/etc/issues/47529)

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-05-03 08:25 UTC, adi88d requested changes
nice!

2022-05-03 08:25 UTC, adi88d commented on Packs/OTRS/Integrations/OTRS/OTRS.py
> +USE_LEGACY_SESSIONS = params.get('use_legacy_sessions', False)
```suggestion
USE_LEGACY_SESSIONS = argToBoolean(args.get('use_legacy_sessions', False))
```
```suggestion
USE_LEGACY_SESSIONS = params.get('use_legacy_sessions', False)
```

2022-05-03 08:25 UTC, adi88d commented on Packs/OTRS/Integrations/OTRS/OTRS.py
> +USE_LEGACY_SESSIONS = params.get('use_legacy_sessions', False)
```suggestion
USE_LEGACY_SESSIONS = argToBoolean(args.get('use_legacy_sessions', False))
```

2022-05-03 08:25 UTC, adi88d commented on Packs/OTRS/Integrations/OTRS/OTRS.py
> +USE_LEGACY_SESSIONS = params.get('use_legacy_sessions', False)
```suggestion
USE_LEGACY_SESSIONS = argToBoolean(args.get('use_legacy_sessions', False))
```

2022-05-03 10:48 UTC, adi88d approved these changes

2022-05-03 13:59 UTC, ShirleyDenkberg commented
@adi88d @yaakovi Doc review completed.

2022-05-03 14:51 UTC, merged

2022-05-08 08:51 UTC, ShirleyDenkberg commented
@adi88d @yaakovi I cannot edit the files.  
Here are the changes that are needed:
In the yml file, line 57, V8 should be v8.  (I think the v is always lower case).
Same comment for line 4 of the md file.

2022-05-08 08:53 UTC, dansterenson commented
@ShirleyDenkberg The PR was merged already since the doc review was completed. In order to add changes to the file we need to open a new PR.

2022-05-08 10:02 UTC, ShirleyDenkberg commented
@dansterenson OK.  The change is insignificant.  No reason to open another PR.