feat: change videos key to list
demisto/content pull request #18987
Opened 2022-05-11 13:53 UTC by jochman

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Changed videos key from str to list.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-05-11 19:15 UTC, MosheEichler requested changes
please see @ShahafBenYakir 's comment https://github.com/demisto/content/pull/18772#issuecomment-1124107439

2022-05-12 06:17 UTC, dorschw commented on Tests/Marketplace/marketplace_services.py
> +            Metadata.VIDEOS: list(self.user_metadata.get(Metadata.VIDEOS, '') or []),
```suggestion
            Metadata.VIDEOS: self.user_metadata.get(Metadata.VIDEOS, [])),
```

2022-05-12 06:18 UTC, dorschw approved these changes

2022-05-12 06:24 UTC, yaakovi approved these changes

2022-05-12 08:25 UTC, ShahafBenYakir commented
Once this is merged we'll need to run upload on all packs, as there are packs on production with invalid `""`values.
FYI @Noy-Maimon

2022-05-12 08:34 UTC, MosheEichler approved these changes

2022-05-12 08:37 UTC, merged