Added PcapConvert, PcapExtractStreams and PcapFileExtractStreams.
demisto/content pull request #19017
Opened 2022-05-13 09:13 UTC by spearmin10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[fixes: link to the issue](https://github.com/demisto/content/pull/18650#issuecomment-1123867462)

## Description
Added PcapConvert, PcapExtractStreams and PcapFileExtractStreams.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-05-17 14:29 UTC, JasBeilin reviewed
Thank you for your contribution!
Please remove the pipfile as we are looking at the docker image and do not use the pipfile.

2022-05-19 14:26 UTC, JasBeilin requested changes

2022-05-19 14:26 UTC, JasBeilin commented on Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams_test.py
> +    from PcapExtractStreams import main
Please add given-when-then doc string

2022-05-19 14:26 UTC, JasBeilin commented on Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams_test.py
> +            print(json.dumps(results))
Please remove printing

2022-05-20 04:18 UTC, spearmin10 commented on Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams.py
> +            sys.stderr = devnull
pyshark sometimes crashes and writes error messages when parsing incorrect pcap.  In that case, this kind of results returns even when excepting and dismissing the errors. 

![image](https://user-images.githubusercontent.com/54964121/169448477-08ba34c3-3a0b-4659-8aa5-e3dac7c04de9.png)

The code prevents it and make expected results (null) like this:
![image](https://user-images.githubusercontent.com/54964121/169449480-28311aa2-430a-4dd3-b3d0-57532065768f.png)

2022-05-20 05:12 UTC, spearmin10 commented
@JasBeilin Updated test scripts following to your comments. Please review again.

2022-05-23 10:38 UTC, JasBeilin approved these changes

2022-05-23 12:12 UTC, ShirleyDenkberg commented
@JasBeilin Doc review completed.

2022-05-23 13:33 UTC, merged