Azure update 2
demisto/content pull request #19016
Opened 2022-05-13 08:29 UTC by ayman-m

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [ x] Ready
- [ ] In Hold - (Reason for hold)

## Description
- Added a command to get network interface details.
- Added a command to get public ip address details.
- Added a command to create a new network interface.

## Minimum version of Cortex XSOAR
- [x ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [ x] Tests
- [x ] Documentation

2022-05-13 08:30 UTC, ayman-m commented
Hi @bziser , the same PR as #18303 , I just added the test functions

2022-05-15 08:37 UTC, bziser commented
@ayman-m Looks good. Please merge from master

2022-05-16 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=19016) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19016) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: JudahSchwartz<br/>:white_check_mark: daryakoval<br/>:white_check_mark: ayman-m<br/>:white_check_mark: content-bot<br/>:x: AradCarmi<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=19016) it.</sub>

2022-05-16 09:20 UTC, ayman-m commented
> @ayman-m Looks good. Please merge from master

Thank you, I did merge from master

2022-05-18 10:42 UTC, ayman-m commented on Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
> +        nic['properties']['networkSecurityGroup']['id'] = private_ip_address
You are 100% correct :), will commit that

2022-05-18 15:05 UTC, ShacharKidor requested changes
Hi @ayman-m, 
Please see 2 more little comments - below.
In addition, I'll ask our technical writers to review the documentation you added. 

Can we schedule a Demo for tomorrow?

2022-05-18 15:05 UTC, ShacharKidor commented on Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
> +                 f"{vnet_name}/subnets/{subnet_name}"
it could also be one long f-string wrapped with parenthesis - like in the second comment.

2022-05-18 15:17 UTC, ShacharKidor commented
@ayman-m  - As we discussed, a Demo was scheduled for tomorrow.

2022-05-19 07:16 UTC, ShacharKidor approved these changes

2022-05-22 09:06 UTC, ShirleyDenkberg commented
@ayman-m I do not have permissions to edit the files so I sent the edited yml file to you in Slack.  Please add it to the PR and address the following issues:

- In the yml file, I have the following questions:
   - Line 470 - 471 (nic_name) There seems to be something missing from the description:
     The name of the network interface you want to view the details o
      
   - Line 699 Not sure what the second sentence is for.
     Creates a virtual machine network interface. the specified OS image.

- In the RN, line 4, ip should be written as IP.

- The Readme file should be regenerated after you make the two corrections I listed above.

2022-05-22 09:07 UTC, ShirleyDenkberg commented
@ShacharKidor I reviewed the docs.  Since I don't have permission to edit the files, I sent the edited yml file to Ayman by Slack and sent him the comments above.

2022-05-23 11:27 UTC, merged