CTIX V3 app for xsoar
demisto/content pull request #19060
Opened 2022-05-16 17:49 UTC by gladipero

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-05-16 17:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=19060) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19060) before we can accept your contribution.<br/><hr/>**Amar Shishodia** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=19060) it.</sub>

2022-05-23 18:07 UTC, cywaredev commented
@edik24 @ShahafBenYakir @JasBeilin Have signed the CLA using both mine and the cywaredev account, Not sure what I am missing here, any help will be appreciated.

2022-05-24 14:16 UTC, JasBeilin requested changes
Thank you for contributing! I have provided you with some feedback below:

1. Deleting pipfile and pipfile.lock is advised, as it is not being used.
2. In order to avoid confusing users, the command names should begin with integration names and include ‘-’ instead of ‘_’.
If you're using `get_indicator_details`, you should use `ctix-get-indicator-details`.
3. In cases where no results are returned, it is advisable to handle them gracefully. *get_lookup_threat_data_command*, for example, should return 'No results were found' as readable_output. If not, customers might think the data was not loaded correctly.

2022-05-25 14:48 UTC, JasBeilin requested changes
Please note that validation and unitests are failing. 
If you need help with addressing these issue, feel free to reach us.

2022-05-25 14:48 UTC, JasBeilin commented on Packs/Tests/id_set.json
> +{
Please remove this file from your changes.

2022-05-25 14:48 UTC, JasBeilin commented on Packs/CTIX/Tests/id_set.json
> +{
Please remove this file from your changes.

2022-05-25 17:21 UTC, cywaredev commented
@JasBeilin @Noy-Maimon @edik24 All changes requested are done, could you please verify. Also not sure how to get that CLA step done as I have already signed using both the cywaredev as well as gladipero github accounts.

2022-05-26 12:15 UTC, Noy-Maimon commented
@cywaredev Great work, please note that the first two comment here still needs to be changed https://github.com/demisto/content/pull/19060#pullrequestreview-984668566

2022-05-26 12:36 UTC, cywaredev commented
Hey @Noy-Maimon Thanks for pointing it out, the change is done now.

2022-05-26 13:05 UTC, cywaredev commented
@Noy-Maimon It's done, let me know if any more changes need to be done. Thanks!

2022-05-26 13:14 UTC, Noy-Maimon commented
@cywaredev Are you sure you pulled the changes from our master to? as in, the repo your main repo was forked from. I checked out your branch and it seems it is still not updated.

2022-05-26 13:26 UTC, cywaredev commented
<img width="1254" alt="Screenshot 2022-05-26 at 6 53 26 PM" src="https://user-images.githubusercontent.com/75426846/170496383-f60d4198-b93f-4e65-90e8-2beed0eb3253.png">
@Noy-Maimon Can you check? Github shows no commits to be pulled from demisto master.

2022-05-26 13:39 UTC, Noy-Maimon commented
I checked out your branch and i can see that it is not updated - the file .gitlab/ci/bucket-upload.yml was modified today and those changes are not there (and those changes are a part of what's blocking the build). I can push those changes for you but i need editing permissions for your branch. If you could please supply that for my user, I will solve that for you.

2022-05-26 13:41 UTC, Noy-Maimon commented
> 

@cywaredev By the way, regarding the CLA, the user Amar Shishodia should sign the [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19060) form.

2022-05-27 08:30 UTC, cywaredev commented
<img width="1781" alt="Screenshot 2022-05-27 at 1 57 02 PM" src="https://user-images.githubusercontent.com/75426846/170661617-a7c1a516-60ed-40cf-8b37-7b3550fdd661.png">
@Noy-Maimon I have accepted using the Amar Shishodia github but CLA is not detecting the same.
Also the file of gitlab is now synced to be the one last updated 21 hours ago and should unblock your pipelines now.

2022-05-27 14:49 UTC, cywaredev commented
@Noy-Maimon @JasBeilin I found the issue with the CLA to solve this created a new PR with exact same code here. Request you to proceed in that PR.
https://github.com/demisto/content/pull/19233

2022-05-29 09:32 UTC, closed without merging