Added FileCreateAndUploadPy
demisto/content pull request #19114
Opened 2022-05-19 11:00 UTC by spearmin10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Added a new FileCreateAndUpload to create a file from a base64 encoded value.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-05-23 10:25 UTC, ilappe requested changes
Thanks for your contribution!
please see the review comments

in addition 
please fix the conflict in the release note file and pack version (as there is a newer version)

2022-05-23 10:25 UTC, ilappe commented on Packs/CommonScripts/Scripts/FileCreateAndUploadPy/FileCreateAndUploadPy.py
> +            raise ValueError(f'Invalid data encoding name: {data_encoding}')
```suggestion
        if data_encoding == 'base64':
            data = base64.b64decode(data)
        elif data_encoding != 'raw':
            raise ValueError(f'Invalid data encoding name: {data_encoding}')
```

2022-05-23 10:34 UTC, spearmin10 commented on Packs/CommonScripts/Scripts/FileCreateAndUploadPy/FileCreateAndUploadPy.py
> +        if entdy_id:
@ilappe The validation logic is correct because the script is compatible with `FileCreateAndUpload`, so the validation logic is same as it.

2022-05-23 10:45 UTC, spearmin10 commented on Packs/CommonScripts/Scripts/FileCreateAndUploadPy/FileCreateAndUploadPy.yml
> +name: FileCreateAndUploadPy
@ilappe Done.

2022-05-23 10:45 UTC, spearmin10 commented on Packs/CommonScripts/Scripts/FileCreateAndUploadPy/FileCreateAndUploadPy.py
> +            raise ValueError(f'Invalid data encoding name: {data_encoding}')
@ilappe Done.

2022-05-23 10:45 UTC, spearmin10 commented on Packs/CommonScripts/Scripts/FileCreateAndUploadPy/FileCreateAndUploadPy.py
> +        demisto.results(fileResult(filename, data))  # noqa
@ilappe Done.

2022-05-23 10:45 UTC, spearmin10 commented on Packs/CommonScripts/Scripts/FileCreateAndUploadPy/FileCreateAndUploadPy.py
> +                demisto.results(res)  # noqa
@ilappe Done.

2022-05-24 09:27 UTC, ilappe approved these changes
@spearmin10 
Thanks for your contribution!

move it for doc review

2022-05-24 09:39 UTC, ShirleyDenkberg commented
@ilappe  Doc review completed.

2022-05-24 10:44 UTC, merged