Enhance an feature of `if-then-else` to make expressions
demisto/content pull request #19122
Opened 2022-05-20 06:35 UTC by spearmin10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Added a new parameter which is `lhs` to enhance `if-then-else` to make expressions.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-05-22 15:23 UTC, ShacharKidor requested changes
Hi @spearmin10, 
nice job!

I added a few suggestions. 
In addition, I'll be happy to have a short demo to better understand the new parameter that was added. 

I'm available for every question :)

2022-05-22 15:23 UTC, ShacharKidor commented on Packs/ExtFilter/Scripts/ExtFilter/README.md
> +| lhs | expressions | (Optional) The value used on the left hand side instead of using the current element. |
Not sure I understood what the 'lhs' does ... Can you provide a more detailed or clearer explanation?

 In addition, you can change line 8048 with the following:
 | --- | --- | --- |
 that will create an MD table (you can change that in many places in the readme file if you like).

2022-05-22 15:23 UTC, ShacharKidor commented on Packs/ExtFilter/ReleaseNotes/1_1_11.md
> +  - Enhance an feature of `if-then-else` to make expressions
Maybe write about the 'lhs' and the functionality that was added

2022-05-24 08:42 UTC, ShacharKidor commented on Packs/ExtFilter/ReleaseNotes/1_1_11.md
> +  - Enhance an feature of `if-then-else` to make expressions
- Added the **lhs** parameter to the  **if-then-else** in order to make expressions  (explain here)

2022-05-24 08:56 UTC, ShacharKidor commented
Hi @spearmin10, 
As discussed in the Demo, please correct the ReleaseNote and the README files according to my suggestions, and let me know when you are done. 

I'm available for any question :)

2022-05-24 09:22 UTC, spearmin10 commented
@ShacharKidor OK, I've updated them.

2022-05-25 08:44 UTC, ShacharKidor approved these changes
Well done!

2022-05-25 13:36 UTC, merged