Adding two new commands to the Okta_v2 Integration
demisto/content pull request #19130
Opened 2022-05-20 22:51 UTC by jdplant

okta-create-group
okta-assign-group-to-app

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Adding two new commands to the Okta_v2 Integration

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-05-20 22:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=19130) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19130) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=19130) it.</sub>

2022-05-23 07:17 UTC, JasBeilin requested changes
Thank you for your contribution.
Please remove the package-lock.json file and check my comments.
Also, a release notes file is missing, and the validation of the files failed. Let me know if you need help in solving it.

2022-05-23 13:55 UTC, jdplant commented
> Thank you for your contribution. Please remove the package-lock.json file and check my comments. Also, a release notes file is missing, and the validation of the files failed. Let me know if you need help in solving it.

Ok will do!  I had thought it passed validation in the SDK but will make the recommended updates and run again.

2022-05-23 19:18 UTC, jdplant commented on Packs/Okta/Integrations/Okta_v2/Okta_v2.py
> +        raw_response
Hey Jas, this Okta integration is using deprecated return_outputs format which I don't believe accepts commandresults class as an argument.  I stuck with the same structure for outputs as the other commands for consistency and to minimize changes to the overall integration.

2022-05-23 19:18 UTC, jdplant commented on Packs/Okta/Integrations/Okta_v2/Okta_v2.py
> +        'OktaGroup(val.ID && val.ID === obj.ID)': createContext(group_context)
This Okta integration is using deprecated return_outputs format which I don't believe accepts commandresults class as an argument.  I stuck with the same structure for outputs as the other commands for consistency and to minimize changes to the overall integration.

2022-05-23 19:19 UTC, jdplant commented on Packs/Okta/Integrations/Okta_v2/Okta_v2.py
> +        raise Exception("You must supply a group name")
Actually this isn't even needed since this is a required argument for the command to run.  I removed it altogether.

2022-05-23 20:53 UTC, jdplant commented
Hey @JasBeilin I removed the package lock file, added release notes, and updated some syntax.

2022-05-25 13:57 UTC, merged