Prisma pb update
demisto/content pull request #19189
Opened 2022-05-25 07:28 UTC by ayman-m

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
- Added a new classification rule for the prisma policy: "AWS Security Group allows all traffic on SSH port (22)" with ID: "617b9138-584b-4e8e-ad15-7fbabafbed1a"
- Fixed the "Account Name" mapping under the "AWS EC2 Instance Misconfiguration" incident type
- Updated the playbook to investigate the "AWS Security Group allows all traffic on SSH port (22)" alerts
- Updated the playbook to investigate the "AWS Security Group allows all traffic on SSH port (22)" alerts

## Minimum version of Cortex XSOAR
- [ x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [ x] Documentation

2022-05-25 14:20 UTC, ShacharKidor requested changes
Hi @ayman-m, 
Thank you for contributing!

I asked for one little change in the release notes, please try to adjust them.
I'll assign @idovandijk for a review as well.

 I'm available for every question here or via slack :)

2022-05-25 14:20 UTC, ShacharKidor commented on Packs/PrismaCloud/ReleaseNotes/2_0_10.md
> +- Updated the playbook to investigate the "AWS Security Group allows all traffic on SSH port (22)" alerts
We have a new validation for the release notes that checks that every section starts with one of the following prefixes: 

```RN_TEMPLATES = {
    # prefixes
    'Added support for',
    'Added the',
    'Fixed an issue',
    'Improved implementation',
    'Updated the Docker image to',
    'You can now',
    'Deprecated. ',
    'Deprecated the ',

    # full line
    'Documentation and metadata improvements.',
}

BANNED_TEMPLATES = {
    'maintenance and stability enhancements.',
    'stability and maintenance enhancements.',
}
```


Can you please edit your release notes in accordance with this new validation?

2022-05-26 08:27 UTC, ShacharKidor approved these changes
@ayman-m - Great job !! :)

2022-05-26 08:27 UTC, ShacharKidor commented on Packs/PrismaCloud/ReleaseNotes/2_0_10.md
> +- **Prisma Cloud - Classifier**
```suggestion
#### Prisma Cloud - Classifier
```

2022-05-29 07:17 UTC, ShirleyDenkberg commented
@ShacharKidor @idovandijk Doc review completed.

2022-05-29 07:38 UTC, ShacharKidor commented on Packs/PrismaCloud/ReleaseNotes/2_0_10.md
> +Fixed an issue with the "Account Name" mapping under the "AWS EC2 Instance Misconfiguration" incident type.
```suggestion
#### Classifiers
##### Prisma Cloud - Classifier
Added the new classification rule: "617b9138-584b-4e8e-ad15-7fbabafbed1a" to classify the prisma policy: "AWS Security Group allows all traffic on SSH port (22)" alerts as "AWS EC2 Instance Misconfiguration" incidents.

#### Mappers
##### Prisma Cloud - Incoming Mapper
Fixed an issue with the "Account Name" mapping under the "AWS EC2 Instance Misconfiguration" incident type.
```

2022-05-29 13:32 UTC, idovandijk commented
Hi, unfortunately I will need a few more days to review this PR. I apologize for the delay, and thanks for waiting.

2022-05-30 14:10 UTC, idovandijk requested changes
Thank you @ayman-m for this contribution!
After reviewing your work, I'm happy to say that you've incorporated the changes pretty well!
You've only left me with 4 points to ask that you please address:

1. I see that the mapping for Account Name for the `AWS IAM Policy Misconfigureation` incident type remains `resource.accountname`. So: are you sure your change to `resource.account` is correct, and if so could you please also fix that one?
![image](https://user-images.githubusercontent.com/43602124/170956385-af243cb5-6adc-4478-85f2-c990234c6a8e.png)

2. In `Prisma Cloud Remediation - AWS EC2 Instance Misconfiguration`, please use the `IsIntegrationAvailable` to check if the integration is enabled - that's our best practice and it available for use since XSOAR 5.0.0
3. Same as 2 for `Prisma Cloud Remediation - AWS EC2 Security Group Misconfiguration`
4. In `Prisma Cloud Remediation - AWS EC2 Security Group Misconfiguration`, task 30 `Revoke the 22 ingress rule`, you are stopping on errors, so you would not get to task 31 unless manually proceeded by the user. Please change that to be like the rest: 
![image](https://user-images.githubusercontent.com/43602124/170998520-9b87b768-e166-4829-99b1-32736e09a2b7.png)

Also I would really like to see an incident actually running with this just to ensure that it all runs smoothly. Could we schedule a short demo?
Thanks again

2022-06-13 08:58 UTC, merged