added support for synapse optic REST API via use_optic
demisto/content pull request #19205
Opened 2022-05-25 21:12 UTC by bertdg

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [https://github.com/demisto/content/issues/19204](https://github.com/demisto/content/issues/19204)

## Description
Version 1.0.1 of the Synapse content pack does not support Vertex Synapse Optic. The login url needs to be updated.
I've added an integration option called use_optic and updated the code and release notes

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
No change from v1.0.1 of Synapse integration

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-05-25 21:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=19205) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19205) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=19205) it.</sub>

2022-05-26 21:41 UTC, bertdg commented
FYI I've reviewed the CircleCI output and all of those warnings are from the current/published/certified version of this integration v1.0.1. If there is any way my PR which adds a feature to login to current versions of synapse on top of the already approved/certified integration (which is failing on the CircleCI checks). Thanks for your consideration of this request.

2022-05-31 19:32 UTC, ShacharKidor commented
Hi @bertdg, 
Thank you for contributing!

I apologize for the delay in responding to your PR, I'll publish my review in a few days.
Thanks for waiting :)

2022-06-02 20:17 UTC, ShacharKidor requested changes
Hi @bertdg , 
Thank you for contributing!

**In order to complete your contribution:** 
1. I added 2 little comments - please review them. 

2. Please updated the docker image in the integration YML to: 1.0.0.24037 - it will solve the build's failure. 

3. Let's schedule a short demo - please let me when would be a good time for you. 

Feel free to contact me with any questions :)

2022-06-02 20:17 UTC, ShacharKidor commented on Packs/Synapse/ReleaseNotes/1_0_2.md
> +- Added configuration option (use_optic) to support Vertex Synapse Optic
```suggestion
- Added the configuration parameter **Use Synapse Optic** to support Vertex Synapse Optic.
```

2022-06-02 20:17 UTC, ShacharKidor commented on Packs/Synapse/Integrations/Synapse/Synapse.yml
> +  type: 8
Worth adding the 'additionalinfo' description for the 'use_optic' config parameter - similar to the description in all the other parameters.

2022-06-02 20:22 UTC, ShacharKidor commented
> FYI I've reviewed the CircleCI output and all of those warnings are from the current/published/certified version of this integration v1.0.1. If there is any way my PR which adds a feature to login to current versions of synapse on top of the already approved/certified integration (which is failing on the CircleCI checks). Thanks for your consideration of this request.

@bertdg - about that, I'm not sure I understood your question. Can I find you on slack?

2022-06-28 16:11 UTC, ShacharKidor approved these changes

2022-06-30 13:57 UTC, merged