Crowdstrike falcon x
demisto/content pull request #19264
Opened 2022-05-29 17:58 UTC by merit-maita

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/47218

## Description
added args to cs-fx-upload-file command.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-14 17:17 UTC, yaakovi requested changes
update the detonation playbooks as well

2022-06-14 17:17 UTC, yaakovi commented on Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
> +        system_time: str = ""
```suggestion
        system_time: str = "",
```

2022-06-15 09:28 UTC, ShirleyDenkberg commented
@yaakovi Doc review completed.

2022-06-21 11:49 UTC, yaakovi commented on Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File.yml
> +      system_time: {}
should be exposed as playbook inputs

2022-06-29 22:38 UTC, yaakovi approved these changes

2022-06-29 22:38 UTC, yaakovi commented on Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File.yml
> +  description: ""
add descriptions to all inputs

2022-06-29 22:38 UTC, yaakovi commented on Packs/CrowdStrikeFalconX/Playbooks/Detonate_File_-_CrowdStrike_Falcon_X.yml
> +      system_time: {}
same as the other playbook (need to be exposed as playbook inputs)

2022-07-05 09:43 UTC, merged