Little fix for the description of Server URL parameter.
demisto/content pull request #19384
Opened 2022-06-03 07:34 UTC by jieliau

If you check the code below:

URL = demisto.params()['server'][:-1] if demisto.params()['server'].endswith('/') else demisto.params()['server']
URL = URL.replace('http://', '').replace('https://', '')
SERVER, PORT = URL.rsplit(":", 1)

We will use rsplit to get SERVER and PORT from URL. But the original description of URL will let customers put ip or hostname only and get the following error message: Script failed to run: Error: [Traceback (most recent call last): File "<string>", line 35, in <module> ValueError: need more than 1 value to unpack ] (2604) (2603)

The customers without programming capability will have no idea how to solve it.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-06 08:18 UTC, ilappe commented
@ShirleyDenkberg please review the doc change
Thanks

2022-06-06 10:27 UTC, ShirleyDenkberg commented
@ilappe Doc review completed.

2022-06-06 10:56 UTC, ilappe requested changes
Thanks for contributing!
please add release notes and update the pack_metadata.json file 
you can do it via the sdk command
`demisto-sdk update-release-notes -i Packs/IBMResilientSystems -u documentation`

2022-06-06 10:58 UTC, ilappe requested changes
Please update the release notes & pack_metadata.json
you can do it via the sdk command
`demisto-sdk update-release-notes -i Packs/IBMResilientSystems -u documentation`

2022-06-07 02:47 UTC, jieliau commented
> Please update the release notes & pack_metadata.json you can do it via the sdk command `demisto-sdk update-release-notes -i Packs/IBMResilientSystems -u documentation`

@ilappe Done and push it already. Thanks.

2022-06-07 07:24 UTC, ilappe approved these changes

2022-06-07 07:24 UTC, merged