MySQL Enterprise Pack Readme Update
demisto/content pull request #19398
Opened 2022-06-06 08:45 UTC by avidan-H

## Status
- [x] Ready

## Description
Adds a description for configuring non-integration event collectors.

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests - N/A
- [x] Documentation

2022-06-06 18:14 UTC, tkatzir requested changes

2022-06-06 18:14 UTC, tkatzir commented on Packs/MySQLEnterprise/README.md
> +1. Broker VM - You will need to use the information described [here](https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-pro-admin/broker-vm/set-up-broker-vm/configure-your-broker-vm).
```suggestion
1. Broker VM - You will need to use the information described [here](https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-pro-admin/broker-vm/set-up-broker-vm/configure-your-broker-vm).\
```

2022-06-06 18:14 UTC, tkatzir commented on Packs/MySQLEnterprise/README.md
> +You can configure the specific vendor and product for this instance, by going to the Settings -> Configuration -> Data Broker -> Broker VMs. Right-Click, and select Syslog Collector -> Configure.
```suggestion
You can configure the specific vendor and product for this instance, by going to the Settings -> Configuration -> Data Broker -> Broker VMs. Right-Click, and select Syslog Collector -> Configure.\
```

2022-06-06 18:14 UTC, tkatzir commented on Packs/MySQLEnterprise/README.md
> +2. XDRC (XDR Collector) - You will need to use the information described [here](https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-pro-admin/cortex-xdr-collectors/xdr-collector-datasets#i
```suggestion
1. XDRC (XDR Collector) - You will need to use the information described [here](https://docs.paloaltonetworks.com/cortex/cortex-xdr/cortex-xdr-pro-admin/cortex-xdr-collectors/xdr-collector-datasets#id7f0fcd4d-b019-4959-a43a-40b03db8a8b2).\
```

2022-06-06 18:14 UTC, tkatzir commented on Packs/MySQLEnterprise/README.md
> +You can configure the vendor and product by replacing [vendor]_[product]_raw with mysql_enterprise_raw.
```suggestion
You can configure the vendor and product by replacing [vendor]_[product]_raw with mysql_enterprise_raw.\
```

2022-06-07 11:57 UTC, avidan-H commented
Adding the `docs-approved` label since the README text is taken directly from the template.

2022-06-07 11:58 UTC, tkatzir approved these changes

2022-06-07 12:07 UTC, merged