[Automox] Fix for vulnerability file upload command
demisto/content pull request #19394
Opened 2022-06-06 04:34 UTC by ax-jmiller

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Description
Fixed an issue where the `reports_source` argument for the `!automox-vulnerability-sync-file-upload` command was not being sent in the payload of the request, resulting in a default value for the parameter.

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-06 17:17 UTC, ShacharKidor requested changes
Hi @ax-jmiller, 
Thank you for contributing!

**In order to complete your contribution:**
1. Please see my comments below. 
2. Let's schedule a short demo - please let me know when would be a good time for you. 

I'm available for any questions here or via slack :)

2022-06-06 17:17 UTC, ShacharKidor commented on Packs/Automox/Integrations/Automox/Automox.py
> +            params=payload,
Can you please explain why did you change that from data to params?

2022-06-06 20:00 UTC, ax-jmiller commented on Packs/Automox/Integrations/Automox/Automox.py
> +        "source": report_source,
This was an error of the original code, and this update fixes it to be the correct parameter name in the request. I maintained the command's argument as "reports_source" for backwards compatibility.

2022-06-07 09:10 UTC, ShacharKidor approved these changes

2022-06-08 15:09 UTC, ShacharKidor approved these changes

2022-06-08 15:12 UTC, merged