ServiceNowV2 - Rollbacked the removal of the 'sn_si_incident' ticket type
demisto/content pull request #19400
Opened 2022-06-06 09:49 UTC by bziser

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
contribution: https://github.com/demisto/content/pull/18087

## Description
Fixes an issue where the 'sn_si_incident' ticket type was accidentally removed by a contributor.

2022-06-06 10:02 UTC, dorschw requested changes

2022-06-06 10:02 UTC, dorschw commented on Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
> +        "sc_task", "sc_req_item" or "sn_si_incident". Default is "incident".
please fix in all other places where it was removed (search for `Ticket type. Can be "incident"`, there are 6) as well

2022-06-06 12:26 UTC, dorschw approved these changes

2022-06-08 15:32 UTC, merged

2022-06-08 15:32 UTC, yaakovi commented
failed on SNow license