Ne xdr prevent only mode
demisto/content pull request #19412
Opened 2022-06-06 15:50 UTC by nericksen

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-07 13:22 UTC, JasBeilin commented
Hi @nericksen.
Could you please provide some context to this change? Why is it needed?

2022-06-07 13:28 UTC, nericksen commented
When dealing with a Prevent only XDR tenant the integration will not work without this fix

2022-06-08 10:51 UTC, JasBeilin requested changes
Thank you for contributing!
Please check my comments so we can move forward :)

2022-06-09 14:10 UTC, nericksen commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +  additionalinfo: 'Select when the XDR tenant is prevent only'
Updated thanks! Let me know if anything else is needed

2022-06-13 06:13 UTC, JasBeilin approved these changes

2022-06-13 06:16 UTC, merged