Reversing labs a1000v2 action update
demisto/content pull request #19438
Opened 2022-06-07 11:43 UTC by ivukovicRL

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added the localOnly parameter to get_classification action - when True action retrieves only local classification data for the sample, without falling back to querying TitaniumCloud.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-06-08 10:38 UTC, ivukovicRL commented
Hi @JasBeilin We have an error on cirleci tests. 

`Possible backwards compatibility break, Your updates to this file contains changes to a name or an argument of an existing command(s).
Please undo you changes to the following command(s):
reversinglabs-a1000-get-classification`

It is not really a breaking change it is only a new parameter extracted. Action was using default value for this parameter before. Any advice on how we can fix this?

2022-06-08 14:45 UTC, Noy-Maimon requested changes
Thank you for your contribution! Looks great.
Please note my comment.

2022-06-08 14:45 UTC, Noy-Maimon commented on Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.yml
> +      required: true
```suggestion
      required: false
```

2022-06-08 14:46 UTC, Noy-Maimon commented
> Hi @JasBeilin We have an error on cirleci tests.
> 
> `Possible backwards compatibility break, Your updates to this file contains changes to a name or an argument of an existing command(s). Please undo you changes to the following command(s): reversinglabs-a1000-get-classification`
> 
> It is not really a breaking change it is only a new parameter extracted. Action was using default value for this parameter before. Any advice on how we can fix this?

Hi, this is due to the new argument being set as mandatory (required: true).
I added a comment for fixing that, and that should fix the circleCI failure.

2022-06-09 07:09 UTC, Noy-Maimon commented on Packs/ReversingLabs_A1000/ReleaseNotes/2_0_4.md
> +Added the *localOnly* parameter to the **reversinglabs-a1000-get-classification** command that allows retrieving only local classification data for the sample, without falling back to querying Titani
@amshamah419  Hi, can you please verify this RN? thanks

2022-06-09 07:54 UTC, Noy-Maimon approved these changes

2022-06-09 07:54 UTC, merged

2022-06-09 08:46 UTC, ivukovicRL commented
@Noy-Maimon Thanks for help :)

2022-06-09 08:48 UTC, Noy-Maimon commented
> @Noy-Maimon Thanks for help :)

You're welcome! thank you for your contribution.