Aburt-MitreCaldera
demisto/content pull request #19482
Opened 2022-06-09 16:47 UTC by aburt-demisto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
NA

## Description
New pack fro MITRE's Caldera platform API. Includes custom incident type, fields, layout and PB (as well as the integration).

## Screenshots

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [x] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-21 14:27 UTC, idovandijk reviewed
Thanks for the contribution, honored to review your work Adam :]
Everything looks good here, just 2 questions:
1. Why is the field Caldera Operation Auto Close a single select and not a Boolean? I assume because Booleans have False as default and you did not want that, correct?
2. What is the goal in having the playbook? On one hand we're creating an incident and changing its name in XSOAR but on the other hand we don't have additional logic and we just create an operation in Caldera, so I wonder if the playbook is necessary.
Also can we schedule a short demo ~15-20 min to see an incident and how creating a new operation works?

2022-06-27 11:18 UTC, ilappe requested changes
Hi @aburt-demisto 
thanks for contribution!
as always - amazing and clear work!!

please see my review comments..
in addition

- Please add `fromversion` to all the scripts

2022-06-27 11:18 UTC, ilappe requested changes
Hi @aburt-demisto 
thanks for contribution!
as always - amazing and clear work!!

please see my review comments..
in addition

- Please add `fromversion` to all the scripts

2022-06-28 11:41 UTC, aburt-demisto commented on Packs/MitreCaldera/Integrations/MitreCaldera/MitreCaldera.py
> +    goals = json.loads(args.get('goals', []))
It will be an empty list

2022-06-28 20:16 UTC, ilappe commented
Hi @aburt-demisto 
thanks for your fixes

i see there is another comments that aren't resolved (may be it was hidden 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/79846863/176276644-e2f166cf-0734-4323-9b2e-7f4c8b0d53b3.png">)

so let me know when you finish with it 
thanks!

2022-07-03 09:48 UTC, ilappe requested changes
Thanks for your fixes !
please see small remain comments 

in addition there is [validation error](https://app.circleci.com/pipelines/github/demisto/content/173687/workflows/4ee5d2ab-62cf-43b3-8cea-68f0d9217234/jobs/537246?invite=true#step-102-7)
so please merge from master

2022-07-03 09:48 UTC, ilappe commented on Packs/MitreCaldera/Integrations/MitreCaldera/MitreCaldera.py
> +        outputs_key_field='name',
Thanks for your fix in the yml file 
but still, the key defined in the yml are now `MitreCaldera.Name`
while from the code - the key will be under `MitreCaldera.Config.name`

2022-07-03 09:48 UTC, ilappe commented on Packs/MitreCaldera/Integrations/MitreCaldera/README.md
> +| relationship_unique | . | Optional |
There is about 178 descriptions that are just `| . |`
if the description are not required - just leave them empty

2022-07-03 09:48 UTC, ilappe commented on Packs/MitreCaldera/Integrations/MitreCaldera/MitreCaldera.py
> +    fact_limit_count = arg_to_number(args.get('fact_limit_count'), 0)
should this be ?
```suggestion
    fact_limit_count = arg_to_number(args.get('fact_limit_count', 0))
```

2022-07-03 09:48 UTC, ilappe commented on Packs/MitreCaldera/Integrations/MitreCaldera/MitreCaldera.py
> +        readable_outputs=f"Schedule with ID {schedule_id} deleted successfully."
```suggestion
        readable_output=f"Schedule with ID {schedule_id} deleted successfully."
```

2022-07-03 09:48 UTC, ilappe commented on Packs/MitreCaldera/Integrations/MitreCaldera/MitreCaldera.py
> +    return_results(command_results)
```suggestion
    return command_results
```
as this will used in the `return_results` in the `main`

2022-07-04 08:12 UTC, aburt-demisto commented
@ilappe I think have addressed them all now.

2022-07-05 12:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=19482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19482) before we can accept your contribution.<br/>**7** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: aburt-demisto<br/>:white_check_mark: content-bot<br/>:white_check_mark: ilaner<br/>:white_check_mark: dansterenson<br/>:white_check_mark: idovandijk<br/>:white_check_mark: merit-maita<br/>:white_check_mark: YuvHayun<br/>:x: tomer-pan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=19482) it.</sub>

2022-07-10 07:54 UTC, idovandijk commented
> Thanks for the contribution, honored to review your work Adam :] Everything looks good here, just 2 questions:
> 
> 1. Why is the field Caldera Operation Auto Close a single select and not a Boolean? I assume because Booleans have False as default and you did not want that, correct?
> 2. What is the goal in having the playbook? On one hand we're creating an incident and changing its name in XSOAR but on the other hand we don't have additional logic and we just create an operation in Caldera, so I wonder if the playbook is necessary.
>    Also can we schedule a short demo ~15-20 min to see an incident and how creating a new operation works?

Hi @aburt-demisto, following up here:
I already got the answer for point 2, from our call I understand that it's a complicated process. Regarding point 1 still need a clarification. Also when scheduling a demo please invite @michalgold as well.

2022-07-12 08:53 UTC, ilappe commented
Demo scheduled for 12/7

2022-07-12 12:32 UTC, idovandijk approved these changes
Awesome job

2022-07-13 07:06 UTC, ilappe commented
@aburt-demisto 
thanks for the very good demo!
let me know when you finish with the implementation 
thanks!

2022-07-19 13:17 UTC, ilappe approved these changes

2022-07-19 19:46 UTC, merged