XDR file retrieve logic fix
demisto/content pull request #19481
Opened 2022-06-09 15:00 UTC by yucohen

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/CIAC-2919
Fixing the bug in the readme: https://jira-hq.paloaltonetworks.local/browse/XSUP-13223

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-16 13:18 UTC, dansterenson requested changes

2022-06-16 13:21 UTC, bziser commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> -    | First fetch timestamp (&lt;number&gt; &lt;time unit&gt;, e.g., 12 hours, 7 days)__
Fix to this bug: https://jira-hq.paloaltonetworks.local/browse/XSUP-13223

2022-06-16 17:58 UTC, bziser commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +            elif status == 'COMPLETED_SUCCESSFULLY':
It is coming from `action_status_get_command` which is used in the polling. 
The value `COMPLETED_SUCCESSFULLY` is used for knowing whether we want to continue to the `'xdr-retrieve-file-details'` command.

2022-06-20 11:58 UTC, bziser commented on Packs/CortexXDR/ReleaseNotes/4_6_4.md
> +##### Palo Alto Networks Cortex XDR - Investigation and Response
Please add that you changed also the integration README

2022-06-20 12:00 UTC, bziser approved these changes
From my side, it seems to be good.
Great work :)
Waiting for @dansterenson's review.

2022-06-20 12:22 UTC, dansterenson approved these changes
Good job

2022-07-03 15:11 UTC, merged