Removing private packs handling in xsiam upload
demisto/content pull request #19519
Opened 2022-06-13 05:51 UTC by moishce

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-19 18:38 UTC, ShahafBenYakir reviewed
@moishce What about removing the logic from the cleanup function?
@Noy-Maimon anything else we might have missed? This looks a bit too simple.

2022-06-19 18:38 UTC, ShahafBenYakir commented on Tests/Marketplace/upload_packs.py
> +        # taking care of private packs
```suggestion
```

2022-06-19 18:40 UTC, ShahafBenYakir requested changes
@moishce What about removing the logic from the cleanup function?
@Noy-Maimon anything else we might have missed? This looks a bit too simple.

2022-06-23 06:16 UTC, moishce commented
@Noy-Maimon [a valid test upload](https://code.pan.run/xsoar/content/-/pipelines/3093058)

2022-06-23 08:05 UTC, ShahafBenYakir commented
@Noy-Maimon @moishce what about this?
>@moishce What about removing the logic from the cleanup function?

2022-06-23 09:16 UTC, moishce commented
@ShahafBenYakir on the cleanup function it’s already implemented

2022-06-27 09:08 UTC, ShahafBenYakir approved these changes

2022-06-27 09:11 UTC, Noy-Maimon approved these changes

2023-04-27 05:48 UTC, closed without merging