Fortigate update
demisto/content pull request #19539
Opened 2022-06-13 13:47 UTC by ayman-m

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
- Fixed an issue with authentication in case of Fortigate authentication disclaimer configured.
- Added the "fortigate-create-address" command to create a new address object.
- Added the "fortigate-delete-address" command to delete an existing address object.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [x ] Documentation

2022-08-01 07:28 UTC, MosheEichler requested changes
HI [ayman-m](https://github.com/ayman-m),
You did a fantastic job :)

Please see my comments
In addition, the build fails please update from master.
Ant let me know when you are done.

Thanks!

2022-08-01 07:28 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/FortiGate.py
> +    fqdn = demisto.args().get('fqdn', '')
```suggestion
    args = demisto.args()
    address_name = args.get('name', '')
    address = args.get('address', '')
    mask = args.get('mask', '')
    fqdn = args.get('fqdn', '')
```

2022-08-01 07:28 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/FortiGate.py
> +        })
```suggestion
        address_dict = {
            'Name': address_name,
            'IPAddress': address
        }
        contents.append(address_dict)
        address_context.append(address_dict)
```

2022-08-01 07:28 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/FortiGate.py
> +        })
```suggestion
        fqdn_dict = {
            'Name': address_name,
            'FQDN': fqdn
        }
        contents.append(fqdn_dict)
        address_context.append(fqdn_dict)
```

2022-08-01 07:28 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/FortiGate.py
> +        }
```suggestion
    if address:
        subnet = address + " " + mask
        payload = {
            'name': address_name,
            'subnet': subnet
        }
```

2022-08-01 07:28 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/FortiGate.py
> +    })
```suggestion
    address_dict = {
        'Name': name,
        'Deleted': True
    }
    contents.append(address_dict)
    address_context.append(address_dict)
```

2022-08-01 07:32 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/README.md
> +<h3 >19. Create an address object</h3>
Please add a link to this command in the beginning of the file (lines 44)
![Screen Shot 2022-08-01 at 10 30 52](https://user-images.githubusercontent.com/78307768/182096410-d9c409cd-6040-4b94-a913-32213afe99eb.png)

2022-08-01 07:41 UTC, MosheEichler requested changes
and few more commanets....

2022-08-01 07:41 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/README.md
> +<h5>Human Readable Output</h5>
What is the human readable output?

2022-08-01 07:41 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/README.md
> +<h5>Human Readable Output</h5>
What is the human readable output?

2022-08-01 07:41 UTC, MosheEichler commented on Packs/FortiGate/Integrations/FortiGate/README.md
> +<td style="width: 402px;">The address mask,example: 255.255.255.0 , Default is 255.255.255.255</td>
```suggestion
<td style="width: 402px;">The address mask, example: 255.255.255.0 , Default is 255.255.255.255</td>
```

2022-08-10 15:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=19539) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19539) before we can accept your contribution.<br/>**13** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: content-bot<br/>:white_check_mark: GuyAfik<br/>:white_check_mark: yaakovpraisler<br/>:white_check_mark: ilaner<br/>:white_check_mark: yaakovi<br/>:white_check_mark: MLainer1<br/>:white_check_mark: dansterenson<br/>:white_check_mark: MosheEichler<br/>:white_check_mark: dorschw<br/>:white_check_mark: ShahafBenYakir<br/>:white_check_mark: israelpoli<br/>:white_check_mark: eyalpalo<br/>:white_check_mark: ayman-m<br/>:x: nkanon<br/>:x: guytamir10<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=19539) it.</sub>

2022-08-10 16:02 UTC, ayman-m commented
> HI [ayman-m](https://github.com/ayman-m), You did a fantastic job :)
> 
> Please see my comments In addition, the build fails please update from master. Ant let me know when you are done.
> 
> Thanks!

Hi @MosheEichler , thanks for taking the time reviewing this PR, I have pushed  new commits after reviewing your comments,  I have also  updated from master

2022-08-11 08:33 UTC, MosheEichler commented
Hi @ayman-m
I think a lot of files that don't belong were accidentally put into PR.
Please take a look

2022-08-11 10:16 UTC, ayman-m commented
> Hi @ayman-m I think a lot of files that don't belong were accidentally put into PR. Please take a look

It looks like something  went wrong while updating  from  master,  will  close this  PR and open a  new one

2022-08-11 10:19 UTC, closed without merging