Xdr   correlation rules
demisto/content pull request #19634
Opened 2022-06-20 07:31 UTC by MosheEichler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-882

## Description
Added 2 new commands
* get contributing alerts
* replace featured fields

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-22 11:12 UTC, dansterenson requested changes
Good job, see my comments

2022-06-22 11:12 UTC, dansterenson commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +        )
Don't we want to throw an error if we get `{"err_code": STATUS_CODE, "err_msg": GENERAL_MESSAGE, "err_extra": EXTRA_DATA}`? I would suggest to check whether we got `true` and if so return the commandResults as you did, else, I would throw an error with the relevant message.

2022-06-22 11:13 UTC, dansterenson commented
@ShirleyDenkberg Can you please go over the PR's docs

2022-06-22 12:33 UTC, ShirleyDenkberg commented
@dansteren @yaakovi Doc review completed.

2022-06-22 14:16 UTC, MosheEichler commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
> +    assert response.outputs[0].get('alertID') == args.get('alert_ids').strip('[]')
@dansterenson I left it that way because using argToList convert it to an int and but it is a string.

2022-06-23 09:31 UTC, dansterenson approved these changes

2022-06-26 05:26 UTC, yaakovi approved these changes

2022-06-26 05:26 UTC, yaakovi commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +            raise DemistoException(err)
Why do you need the `try-except` wrapping?

2022-06-29 09:04 UTC, merged