Updated JiraV2 integration to combine issueJson with the transition a…
demisto/content pull request #19734
Opened 2022-06-24 23:44 UTC by MWEJ

…nd status, instead of doing it before. This makes it possible to fill out the resolution field while doing a transition to closed status

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Updated integration to combine issueJson with the transition and status, instead of doing it before. This makes it possible to fill out the resolution field while doing a transition to closed status

## Screenshots
![image](https://user-images.githubusercontent.com/2354407/175748925-4e6e089e-1c32-40ee-87ec-8238b4c81c27.png)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [X ] Yes
       - Further details:
   - [ ] No

## Must have
- [X ] Tests
- [X ] Documentation

2022-06-27 08:42 UTC, Noy-Maimon requested changes
Hi, thank you for your contribution - looks great. please note my comments, and please sign the [contribution form](https://forms.gle/XDfxU4E61ZwEESSMA).
Also, let's schedule a demo for this change.

2022-06-27 08:42 UTC, Noy-Maimon commented on Packs/Jira/Integrations/JiraV2/JiraV2.py
> +    if issue is None:
```suggestion
    if not issue:
```

2022-06-27 08:42 UTC, Noy-Maimon commented on Packs/Jira/ReleaseNotes/2_0_5.md
> +- Updated integration to combine issueJson with the transition and status, instead of doing it before. This makes it possible to fill out the resolution field while doing a transition to closed statu
```suggestion
- You can now fill modify the resolution field while transitioning a status to closed.
```

2022-07-03 13:29 UTC, Noy-Maimon commented
@MWEJ Hi, any updates?

2022-07-06 19:42 UTC, MWEJ commented
> @MWEJ Hi, any updates?

Sorry, I wasn't aware that I had to accept the suggestions. I believe I already signed the contributor form, so is there anything else I need to do?

2022-07-07 09:31 UTC, Noy-Maimon commented
@MWEJ Thanks for signing the form, can you please merge for master? this is holding the builds from passing
thanks!

2022-07-07 10:58 UTC, Noy-Maimon approved these changes

2022-07-07 10:58 UTC, merged