Docker Engine API improvements
demisto/content pull request #19747
Opened 2022-06-26 10:35 UTC by SergeBakharev

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
I've made a number of improvements and bugfixes to the Docker Engine API integration:
1. Improved the documentation
    Previously incomplete Docker configuration instructions were provided in the description.md. I found them to be a copy from the Docker online documentation, and thus have replaced the incomplete instructions with a summary and a reference to the appropriate Docker article
2. Fixed breaking bugs
    Previously the required parameters client_cert and client_key were stored as encrypted (type:8). This is not appropriate since key control characters required for the cert PEM format are stripped from the values when saved this way. I have changed them to the long text parameter (12) type as per other similar integrations that store cert data (eg. Kafka and FeedTAXII)
3. Enhanced Certificate Validation Functionality
    The options for cert validation were insufficient for anyone using this integration with a self-hosted CA (the default in most instanced). Thus I have added an additional optional parameter for the CA cert which if provided is used for validating the Docker Server connection.
4. Registry Authentication Functionality
    It is desirable to interact with container registries (dockerhub or other) using this integration however capabilities of a anonymous user are increasingly becoming more limited. I have added the capability to authenticate with a registry.
5. Added Commands
    A number of commands I require were incomplete, thus i've completed their implementation:
      - docker-container-delete
      - docker-image-delete
      - docker-image-create
      - docker-image-push
      - docker-image-tag

## Minimum version of Cortex XSOAR
- [x] 6.0.0

I've tested on my local 6.8 lab environment, but I don't see anything that would prevent the integration from functioning on a 6.0.0 XSOAR.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests - N/A: Community supported package
- [x] Documentation

2022-06-29 07:55 UTC, ilappe commented
Hi @SergeBakharev ,
Thank you for contributing!
Apologies for the delay in reviewing your PR, the team will review your code as soon as possible.

Thanks again.

2022-07-07 10:56 UTC, AradCarmi requested changes
Hey @SergeBakharev, 
Excellent work!
See my suggestions below.

2022-07-11 10:05 UTC, SergeBakharev commented on Packs/DevSecOps/ReleaseNotes/1_1_0.md
> +
I actually haven't made any changes to the existing commands, just ran the demisto-sdk formater which has cleaned up the descriptions

2022-07-12 10:40 UTC, AradCarmi approved these changes

2022-07-12 10:44 UTC, merged