Mc afee m vision integration
demisto/content pull request #19785
Opened 2022-06-27 20:07 UTC by MosheEichler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-1964

## Description
Added a new pack with an integration to McAfee MVISION

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-06-29 06:10 UTC, yaakovi requested changes
very nice work

2022-06-29 06:10 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB_test.py
> +def test_incident_query_command(mocker):
add docstrings to all unit tests (when - given - then)

2022-06-29 06:10 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB.yml
> +  display: Your server URL
```suggestion
  display: Base URL (e.g., https://www.myshn.net)
```

2022-06-29 06:10 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB.yml
> +      description: ""
update all descriptions, try using [demisto-sdk generate-outputs --ai](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/generate_outputs/README.md#generate-outputs)

2022-06-29 06:10 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB.py
> +    credentials = demisto.params().get('credentials', {})
```suggestion
    params = demisto.params()
    base_url = urljoin(params['url'].removesuffix('/'), '/shnapi/rest')
    verify_certificate = not params.get('insecure', False)
    credentials = params.get('credentials', {})
```

2022-06-29 06:10 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB.py
> +        demisto.debug(f'This is the output: {readable_dict}')
?

2022-06-29 06:10 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB.py
> +            raise e
```suggestion
            raise
```

2022-07-04 07:00 UTC, yaakovi reviewed
nice work

2022-07-04 07:00 UTC, yaakovi commented on Packs/CommonTypes/ReleaseNotes/3_2_38.md
> +- Added the following incident fields to be associated with the McAfee MVision CASB Alert and McAfee MVision CASB Threat incident types.
```suggestion
- Added the following incident fields to be associated with the *McAfee MVision CASB Alert* and *McAfee MVision CASB Threat* incident types.
```

2022-07-04 07:00 UTC, yaakovi commented on Packs/Malware/ReleaseNotes/1_4_2.md
> +- **Malware Name**
you didn't change the field

2022-07-04 07:00 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB_description.md
> +UserName and Password
redundant

2022-07-04 07:00 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB_description.md
> +The base url for example https://www.myshn.net
redundant

2022-07-05 11:13 UTC, MosheEichler commented
The pre isn't done yet because we are waiting for more credentials to implement the anomaly command.
[Jira](https://jira-hq.paloaltonetworks.local/browse/CRTX-52848) tiket

2022-07-05 11:14 UTC, ShirleyDenkberg commented
@michalgold @altmannyarden @yaakovi @idovandijk Doc review completed.

2022-07-13 05:48 UTC, yaakovi commented on Packs/McAfeeMVisionCASB/Integrations/McAfeeMVisionCASB/McAfeeMVisionCASB.yml
> +      description: ""
yes

2022-07-13 06:50 UTC, yaakovi approved these changes
* merge the two mappers
* set the classifier and mapper as defaults in the integration yml

2022-08-30 06:47 UTC, MosheEichler commented
@mchasepan
Hi. Yes the pr is ready will be merged after the build will succeed.

2022-08-31 13:11 UTC, mchasepan commented on Packs/SkyhighSecurity/pack_metadata.json
> +    "name": "Skyhigh Security",
```suggestion
    "name": "Skyhigh Security SSE",
```

2022-08-31 13:11 UTC, mchasepan commented on Packs/SkyhighSecurity/pack_metadata.json
> +    "description": "Skyhigh Security is a cloud-based, multi-tenant service that enables Cloud Discovery and Risk Monitoring, Cloud Usage Analytics, Cloud Access and Control.\n",
```suggestion
    "description": "Skyhigh Security is a cloud-based, multi-tenant service that enables Cloud Discovery and Risk Monitoring, Cloud Usage Analytics, Cloud Access and Control.",
```

2022-09-11 12:29 UTC, merged