Cloudflare waf integration v101
demisto/content pull request #19791
Opened 2022-06-28 07:56 UTC by TalGumi

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Upgrade to version 1.0.1

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [x ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ x] Tests
- [x ] Documentation

2022-06-30 11:58 UTC, Noy-Maimon commented
@TalGumi Sorry for the delay with this review, one of our developers will handle it soon, thanks!

2022-07-05 10:48 UTC, JudahSchwartz requested changes
Very nice PR! Some minor comments here, and we need to re-sync with master.
Thank you!

2022-07-05 10:48 UTC, JudahSchwartz commented on Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.py
> +    def cloudflare_waf_ip_list_item_list_request(self, list_id: str, item: list = None, cursors: str = None) -> Dict[str, Any]:
please fix this docstring, the parameters arent matching up

2022-07-05 10:48 UTC, JudahSchwartz commented on Packs/CloudflareWAF/ReleaseNotes/1_0_0.md
> +- Cloudflare WAF integration allows customers to manage firewall rules, filters, and IP-lists. It also allows to retrieve zones list for each account. (Available from Cortex XSOAR 6.2.0).
Please switch the notes here to be what was added in this PR only

2022-07-05 10:48 UTC, JudahSchwartz commented on Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.py
> +    while dict_safe_get(ip_list, ['result_info', 'cursors', 'after']):
nice loop

2022-07-06 10:08 UTC, TalGumi commented on Packs/CloudflareWAF/Integrations/CloudflareWAF/CloudflareWAF.py
> +    while dict_safe_get(ip_list, ['result_info', 'cursors', 'after']):
Thanks!

2022-07-07 10:25 UTC, JudahSchwartz reviewed
please note the following error in the build
 `unittests coverage should reach at least 75.88 currently 72.93`

2022-07-07 13:35 UTC, JudahSchwartz approved these changes

2022-07-07 13:35 UTC, merged