Feat(Cortex XSOAR/content): Add SEKOIA.IO integration
demisto/content pull request #19928
Opened 2022-07-06 14:48 UTC by PierrickV

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-07-06 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=19928) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=19928) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=19928) it.</sub>

2022-07-10 07:57 UTC, ShahafBenYakir commented
Relevant docker PR: https://github.com/demisto/dockerfiles/pull/8125

2022-07-11 10:31 UTC, MosheEichler commented
@PierrickV It seems that unrelated files were accidentally entered. Please fix it

2022-07-12 06:16 UTC, MosheEichler requested changes
Hi @PierrickV.
You did an Excellent Job!! :)

Please check the following notes.
And let me know when you are done.

Thank you.

2022-07-12 06:16 UTC, MosheEichler commented on Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py
> +    # Read every items of the reponse
```suggestion
    # Read every items of the response
```

2022-07-18 12:57 UTC, PierrickV commented on Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/command_examples
> +!GetObservable value="eicar@sekoia.io" type="email-addr"
ok

2022-07-18 14:06 UTC, PierrickV commented on Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py
> +            hashes["sha256"] = object_hash.split("=")[1].strip(" ").strip("'")
Yes !

2022-07-19 07:34 UTC, MosheEichler reviewed
Perfect!

Please remove this file
Packs/SEKOIAIntelligenceCenter/pack_metadata.json.lock.
And go over the few final comments.

Thanks again you did an amazing job :)

2022-07-19 07:34 UTC, MosheEichler commented on Packs/SEKOIAIntelligenceCenter/.secrets-ignore
> +eicar@sekoia.io
```suggestion
```
Please remove.
And all duplicates.

2022-07-19 07:34 UTC, MosheEichler commented on Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/README.md
> +This integration was integrated and tested with version 2.20220712 of SEKOIAIntelligenceCenter
```suggestion
This integration was integrated and tested with version 2.20220712 of SEKOIA Intelligence Center
```

2022-07-19 08:38 UTC, PierrickV commented on Packs/SEKOIAIntelligenceCenter/.secrets-ignore
> +eicar@sekoia.io
Fixed, sorry for this mistake :smile:

2022-07-19 10:39 UTC, MosheEichler approved these changes
Nice work

2022-07-20 11:10 UTC, merged