Insert to context not in threads
demisto/content pull request #19971
Opened 2022-07-10 11:10 UTC by ilaner

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-07-10 15:34 UTC, tkatzir commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> +                         offense_start_time: str = None
```suggestion
                         offense_start_time: str = None,
```

2022-07-10 15:37 UTC, tkatzir commented on Packs/QRadar/ReleaseNotes/2_2_2.md
> +- Fixed an issue which the QRadar integration context resets when trying to update from long running threads.
```suggestion
- Fixed an issue in which the QRadar integration context resets when trying to update from long running threads.
```

2022-07-11 17:20 UTC, DeanArbel requested changes
Good job, see my comments below.
For changes in context, don't forget to update the yml and readme as well.

2022-07-11 17:20 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> +                                         offense_id)
Please make this a `kwargs` call - it should make it easier to read (the nice variable names do make it easy, but it can be better 😃).

2022-07-11 17:20 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> +            'polling': True,
Is it possible to run this command without `polling`? If not please remove the arg.

2022-07-11 17:20 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> +        return qradar_search_results_get_command(client, args)
It might be better to change the context output key to make it easier to differentiate this from other searches

2022-07-11 17:20 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> +    except Exception as e:
Please add a note here about why we're continuing the polling for all failures.

2022-07-12 12:44 UTC, ilaner commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> +            offenses = [offense for offense, _ in offenses_with_success]
We use it after the loop

2022-07-12 14:18 UTC, DeanArbel reviewed
See my comments below.

2022-07-12 14:18 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
> +    name: qradar-get-events-polling
Let's rename this command. Please contact @David-BMS about naming.

2022-07-12 14:18 UTC, DeanArbel commented on Packs/QRadar/ReleaseNotes/2_2_3.md
> +- Updated the Docker image to: *demisto/python3:3.10.5.31928*.
```suggestion
- Added a new command **qradar-get-events-polling**. Get QRadar events in a single command.
- Fixed an issue where multiple events search failures in a single fetch would reset the existing integration context.
- Changed the START in the search query when fetching an offense's events to the *offense start time*. This change was done to improve fetch performance.
- Updated the Docker image to: *demisto/python3:3.10.5.31928*.
```

2022-07-13 14:05 UTC, DeanArbel commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
> +  - arguments:
Continuing my previous comment please make sure to update the descriptions here as well.

2022-07-13 18:11 UTC, merged