Extract indicators playbook bug fix
demisto/content pull request #19977
Opened 2022-07-10 13:55 UTC by yucohen

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-13923)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-07-13 11:12 UTC, idovandijk requested changes
Hi @yucohen, I reviewed the changes, good job! I still have some comments that require fixing though:
1. I see that you've added the exclusion of the `xlsm` extension from the extraction command, but not from the conditional task that comes before that:
![image](https://user-images.githubusercontent.com/43602124/178718604-66a3d6b3-59ed-42b7-b7a3-ac3c1c4a8f8f.png)

This would result in a situation where a file is detected and then not extracted, but we actually don't want to detect those are Word files at all.

2. You've changes the playbook to run in **quiet mode** which would defeat the purpose of the playbook, as auto-extract and auto-enrich are required in the extraction tasks. Please revert the change.
3. Please remove all the irrelevant test playbooks, looks like many were added due to the old SDK bug that added lots of irrelevant test. We should only keep ` Extract Indicators From File - Generic v2 - Test`.
4. Please update the ` Extract Indicators From File - Generic v2 - Test` test playbook to also test with an XLSM file, preferably the same file that the customer is using. In the test I noticed that we *are* able to convert XLSM files to PDF files and then extract indicators from them. So it would be good to have a check which ensures that XLSM files **are** actually parsed but without failing the playbook.

2022-07-14 06:00 UTC, yucohen commented
@idovandijk Thanks! I made all the changes
also asked for the file from the CS, waiting to reply

2022-08-04 08:26 UTC, yaakovi approved these changes

2022-08-04 10:22 UTC, idovandijk approved these changes

2022-08-04 10:26 UTC, merged