Binalyze air
demisto/content pull request #20025
Opened 2022-07-13 05:24 UTC by binalyze-murat

## Status
- [] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
No fix is available at this time. 

## Description
This is the first commit of Binalyze AIR integration.
## Screenshots

## Minimum version of Cortex XSOAR
- [x ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-07-13 05:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=20025) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=20025) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=20025) it.</sub>

2022-07-14 11:26 UTC, AradCarmi requested changes
Hey Murat,
You did a great job!
I didn't finish reviewing all the files, only the py file, I will let you view my notes and suggestions, and accordingly, you can change the other files. Let me know when you are finished and we keep moving forward in order to merge the PR.
Again, thanks for the contribution!

2022-07-14 13:10 UTC, binalyze-murat commented on Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR.py
> +
this is done as well

2022-07-17 11:15 UTC, AradCarmi requested changes
Hey Murat, Nicely done! 
These are the last changes before we merge the PR. Please view my notes and resolve each one, if you are not sure just add a comment with the question or send a message via Slack. The Unit Test looks great (see my note there) if the coverage will not raise we will ignore this validation, so don't worry 🙃

2022-07-17 11:15 UTC, AradCarmi commented on Packs/Binalyze/Integrations/BinalyzeAIR/test_data/acquire.json
> +{
Seems it has never been used.

2022-07-17 11:15 UTC, AradCarmi commented on Packs/Binalyze/Integrations/BinalyzeAIR/test_data/isolate.json
> +{
Seems it has never been used.

2022-07-17 11:15 UTC, AradCarmi commented on Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR_test.py
> +    assert expected_mocked_command_result
The tests overall seem good, my only suggestion is to use the `client.test_conectivity` in the test_connection_* tests. 
(You just asserted that the expected_mocked_command_result is not None which is always true)

2022-07-18 11:23 UTC, AradCarmi commented
There are still some suggestions that you didn't resolve.

2022-07-23 19:07 UTC, binalyze-murat commented on Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR.py
> +            return_results(test_connection(client))
I changed the code as base_url will be called from Client class. I think this fix is not needed anymore.

2022-07-23 19:10 UTC, binalyze-murat commented on Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR.yml
> +    description: Isolate an endpoint
> In general, I recommend removing the success, statusCode, and errors.

done

2022-07-23 20:30 UTC, binalyze-murat commented on Packs/Binalyze/Integrations/BinalyzeAIR/BinalyzeAIR.yml
> +    description: Isolate an endpoint
> Also please add a dot as suggested to all of the outputs.
done

2022-07-23 20:30 UTC, binalyze-murat commented on Packs/Binalyze/Integrations/BinalyzeAIR/README.md
> +## Binalyze AIR Integration
done

2022-07-23 20:31 UTC, binalyze-murat commented on Packs/Binalyze/Integrations/BinalyzeAIR/test_data/acquire.json
> +{
done, deleted.

2022-07-31 08:18 UTC, AradCarmi approved these changes

2022-07-31 08:18 UTC, merged