Rasterize - override the meta tag
demisto/content pull request #20056
Opened 2022-07-14 09:20 UTC by ilappe

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14264

## Description
Due to charset koi8-r defined in html 
the parse HTML was wrong
solution: override `meta` tag with one contain `charset="UTF-8" `

2022-07-17 05:04 UTC, yaakovi commented on Packs/rasterize/ReleaseNotes/1_2_1.md
> +Fixed an issue in ***rasterize-email*** where the html parsed incorrect due to not UTF-8 charset.
```suggestion
Fixed an issue in ***rasterize-email*** where the HTML parsed incorrectly due to not UTF-8 charset.
```

2022-07-17 05:04 UTC, yaakovi commented on Packs/rasterize/Integrations/rasterize/rasterize.py
> +    html_body = html_body.replace('<meta ', '<meta charset="UTF-8" ')
What if the `meta` tag already contains `charset`? 
use regex to avoid conflicts

2022-07-18 21:48 UTC, glicht requested changes

2022-07-18 21:48 UTC, glicht commented on Packs/rasterize/Integrations/rasterize/rasterize.py
> +    html_body = html_body.replace(charsets[0], 'UTF-8') if charsets else html_body
This is dangerous. You may be replacing the charset[0] string in other places in the html_body and not only in the meta tag. You should probably be using `re.sub` with the group option to replace only the matched group.

2022-07-20 07:58 UTC, glicht commented on Packs/rasterize/ReleaseNotes/1_2_1.md
> +Fixed an issue in ***rasterize-email*** where the HTML parsed incorrectly due to not UTF-8 charset.
```suggestion
Fixed an issue in ***rasterize-email*** where some HTML inputs that contain a meta charset tag with non UTF-8 charsets were displayed incorrectly.
```

2022-07-20 08:00 UTC, yaakovi approved these changes

2022-07-20 10:40 UTC, merged