mapper,beta deprication, and proxy removed
demisto/content pull request #20055
Opened 2022-07-14 09:14 UTC by eyalpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-1844)

## Description
Made changes in pop3 integration to remove it from beta version.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-08-31 16:57 UTC, dantavori requested changes
looks good, see notes below

2022-08-31 16:57 UTC, dantavori commented on Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3.py
> +
```suggestion
```
in CSP already

2022-08-31 16:57 UTC, dantavori commented on Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3.yml
> +  id: MailListener - POP3
not sure we can modify integration id and names. if not - change only display and we'll live with that

2022-09-05 06:26 UTC, dantavori approved these changes

2022-09-05 06:28 UTC, dantavori commented on Packs/MailListener_-_POP3/Integrations/MailListener_POP3/README.md
> +## Overview
how was this generated? it doesn't look like the regular one

2022-09-05 06:28 UTC, dantavori commented on Packs/MailListener_-_POP3/ReleaseNotes/2_0_0.md
> +- Added **Incoming mapper** to map incoming emails to **Phishing** incident type.
```suggestion
- Added a default *incoming mapper* for mapping incoming emails to the *Phishing* incident type.
```

2022-09-07 11:11 UTC, eyalpalo commented
@ShahafBenYakir Force merge is needed here. Due to the reason we removed one of the integration parameters, which caused one of the validations to fail.

2022-09-07 11:50 UTC, merged