Msopof contrib microsoft defender advanced threat protection - machine offboard
demisto/content pull request #20054
Opened 2022-07-14 06:58 UTC by msopof

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-07-14 07:07 UTC, msopof commented
@israelpoli Hi, can you look at https://app.circleci.com/pipelines/github/demisto/content/176385/workflows/741121a9-e4da-48ff-903c-882af82d4294/jobs/542105

And tell what is exactly wrong with file and how to fix it?

2022-07-15 08:50 UTC, msopof commented
Any update regarding the secret test fail?

2022-07-17 20:19 UTC, israelpoli requested changes
Hi @msopof...
Thank you for your contributions.

**Note** -> you have a `content` folder at branch, please delete it.
Please see my comments below.

Thanks

2022-07-17 20:19 UTC, israelpoli commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +    headers = ['ID', 'Type', 'Requestor', 'RequestorComment', 'Status', 'MachineID', 'ComputerDNSName']
Please add a validate if the arguments were indeed provided

```suggestion
    if not args.get('machine_id') or not args.get('comment'):
        raise ValueError("something")
    headers = ['ID', 'Type', 'Requestor', 'RequestorComment', 'Status', 'MachineID', 'ComputerDNSName']
```

2022-07-17 20:19 UTC, israelpoli commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
> +| MicrosoftATP.MachineAction.troubleshootInfo | String | Troubleshooting information.                               |
After you change the keys of the outputs in the `yml` file, please also change the `REDME` file

2022-07-17 20:19 UTC, israelpoli commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_11_6.md
> +-  1.9.1
Please remove this line.

2022-07-17 20:19 UTC, israelpoli commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_9_0.md
Please restore the file to its previous state

2022-07-18 11:13 UTC, msopof commented
@israelpoli Finally all test passed. Can you approve changes?

2022-07-18 12:02 UTC, israelpoli commented
Hi @msopof 

Please run:
1. `git checkout origin/master ./Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_9_0.md`
2. `git checkout origin/master ./Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/Pipfile`
3. `git checkout origin/master ./Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/Pipfile.lock`


**Commit and Push**

2022-07-18 12:14 UTC, msopof commented
@israelpoli Done.

2022-07-18 22:56 UTC, israelpoli approved these changes
Thanks for your contribution.

Good job

2022-07-18 22:57 UTC, merged