Palo alto network operations pack
demisto/content pull request #20093
Opened 2022-07-18 06:29 UTC by adambaumeister

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
@GuyAfik @tomer-pan 
This is the entire content pack that comprises PAN-OS Network operations. It includes the following use cases;

 - Firewall/Panorama Upgrades
 - System Snapshotting and comparisons
 - Configuration Hygiene Checks

This pack includes a large set of supporting scripts, besides the playbooks, types, fields, and layouts. 

This content was exported using the marketplace "contribute" button and then converted into the preferred directory structure. Because of this there are likely UUID and other such issues present, but it should still be a valid content pack either way.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [X] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [X] Documentation

2022-07-20 05:52 UTC, MosheEichler requested changes
Hi @PierrickV.
You did an Excellent Job!! :)

Please add unit tests for all scripts.
And please see the above comments.
And let me know when you are done.

Thank you.

2022-07-20 05:52 UTC, MosheEichler commented on Packs/PAN_OS_Network_Operations/Scripts/CountActiveVisibilityHygieneIssues/CountActiveVisibilityHygieneIssues.py
> +    demisto.results(count)
```suggestion
if "currentUser" not in demisto.args():
    demisto.results(count)
```

2022-07-20 05:52 UTC, MosheEichler commented on Packs/PAN_OS_Network_Operations/Scripts/CountActiveVisibilityHygieneIssues/CountActiveVisibilityHygieneIssues.py
> +# If demisto.args() isn't empty, then this is being invoked as a widget script, in which case simply return the count.
> If demisto.args() isn't empty
Is this not always empty? from the YML file it looks there are no args.

2022-07-20 05:52 UTC, MosheEichler commented on Packs/PAN_OS_Network_Operations/Scripts/CountFixedVisibilityHygieneIssues/CountFixedVisibilityHygieneIssues.py
> +    demisto.results(count)
See the previous comments.

2022-07-23 23:36 UTC, adambaumeister commented
Heya Team,

Gonna close this one as I'm going to split this into a couple of different packs instead.

2022-07-23 23:36 UTC, closed without merging