Mimecast playbook
demisto/content pull request #20116
Opened 2022-07-19 13:28 UTC by ayman-m

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
##### New: Mimecast - Block Sender Email
- A playbook to block sender email address using Mimecast integration. (Available from Cortex XSOAR 6.2.0).
##### New: Mimecast - Block Sender Domain
- A playbook to block sender domain name using Mimecast integration. (Available from Cortex XSOAR 6.2.0).

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [x ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x] No

## Must have
- [ ] Tests
- [x ] Documentation

2022-07-20 05:54 UTC, MosheEichler approved these changes

2022-07-27 11:19 UTC, idovandijk requested changes
Hi @ayman-m, pleased to review your content again. Excellent job.
Some questions from me:
1. Can we always assume that the `query_source` is "cloud"? Seems like it should be a playbook input. Please add it and add into the input description that the options are "cloud" or "ldap'.
2. Please change the playbooks to be non-quiet mode, I hate this feature so much, and I hate it being the default now. It's mostly good for TIM playbooks.
3. Please validate the inputs before proceeding with the block process, in both playbooks.
4. It would be highly appreciated if you could incorporate these playbooks into our generic Block playbooks (Block Email - Generic, etc).

Let me know once you're done, and keep rocking!

2022-07-29 04:25 UTC, ayman-m commented
> Hi @ayman-m, pleased to review your content again. Excellent job. Some questions from me:
> 
>     1. Can we always assume that the `query_source` is "cloud"? Seems like it should be a playbook input. Please add it and add into the input description that the options are "cloud" or "ldap'.
> 
>     2. Please change the playbooks to be non-quiet mode, I hate this feature so much, and I hate it being the default now. It's mostly good for TIM playbooks.
> 
>     3. Please validate the inputs before proceeding with the block process, in both playbooks.
> 
>     4. It would be highly appreciated if you could incorporate these playbooks into our generic Block playbooks (Block Email - Generic, etc).
> 
> 
> Let me know once you're done, and keep rocking!

Hi @idovandijk , thank you for taking the time reviewing this PR, I have pushed couple of comments based on your review findings

2022-08-02 11:00 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic.yml
> +      name: Symantec - Block Email
Since `Block Email - Generic` is from 5.0, changing the name of a subplaybook tasks is not supported, need to revert this

2022-08-02 11:03 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic.yml
>      skipunavailable: false
should be true

2022-08-02 11:03 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_Email_-_Generic.yml
>      skipunavailable: false
Should also be true. If someone uses the generic playbook and doesn't have one of the packs of the subplaybooks it will cause it to fail for them

2022-08-10 08:00 UTC, ayman-m commented
> Please see my comments

@idovandijk I have  pushed  new  commits based  on  your comments, I  have  also  updated  the release notes

2022-08-11 08:52 UTC, MosheEichler commented
Hi @ayman-m lokks the same problem as [here](https://github.com/demisto/content/pull/19539)

2022-08-11 10:16 UTC, ayman-m commented
> Hi @ayman-m lokks the same problem as [here](https://github.com/demisto/content/pull/19539)

It looks like something  went wrong while updating  from  master,  will  close this  PR and open a  new one

2022-08-11 10:28 UTC, closed without merging