New version for solving authentication problem
demisto/content pull request #20222
Opened 2022-07-25 15:54 UTC by rshunim

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-13510)

## Description
New docker image, and a small change - 'autologin' was replaced to 'basic' when user use username and password

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-07-26 06:59 UTC, yuvalbenshalom requested changes
1. please add release notes and bump version.
2. add the same update to splunkPy-pre release integration.

2022-07-26 07:36 UTC, ilappe commented
@rshunim 
can you please add here link to Splunk SDK documentation that mention the "basic" attribute in the splunklib.client?

2022-07-26 08:40 UTC, ilappe commented
discussion about the `basic=true `
https://github.com/splunk/splunk-sdk-python/issues/219#issuecomment-611478090

2022-07-26 08:42 UTC, ilappe approved these changes

2022-07-26 08:43 UTC, rshunim commented
> @rshunim can you please add here link to Splunk SDK documentation that mention the "basic" attribute in the splunklib.client?
https://github.com/splunk/splunk-sdk-python/issues/219#issuecomment-611478090

2022-07-26 09:19 UTC, yuvalbenshalom requested changes
added a line to state the fix in the release notes.

2022-07-26 09:19 UTC, yuvalbenshalom commented on Packs/SplunkPy/ReleaseNotes/2_4_5.md
> +- Updated the Docker image to: *demisto/splunksdk:1.0.0.32388*.
```suggestion
- Fixed an issue where the integration authentication failed intermediately.
- Updated the Docker image to: *demisto/splunksdk:1.0.0.32388*.
```

2022-07-26 09:19 UTC, yuvalbenshalom commented on Packs/SplunkPyPreRelease/ReleaseNotes/1_0_12.md
> +- Updated the Docker image to: *demisto/splunksdk:1.0.0.32388*.
```suggestion
- Fixed an issue where the integration authentication failed intermediately.
- Updated the Docker image to: *demisto/splunksdk:1.0.0.32388*.
```

2022-08-02 08:56 UTC, yuvalbenshalom approved these changes

2022-08-02 09:00 UTC, merged