[Anomali] - Added new command and enhance reputation commands
demisto/content pull request #20242
Opened 2022-07-26 13:48 UTC by MLainer1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3269)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-08-03 13:57 UTC, dantavori requested changes

2022-08-03 13:57 UTC, dantavori commented on Packs/Anomali_ThreatStream/ReleaseNotes/2_0_13.md
> +- Added the new argument **threat_model_association** to the reputation commands.
```suggestion
- Added a new command: ***threatstream-search-intelligence***.
- Added the ***threat_model_association*** argument to the ***ip***, ***file***, ***domain*** and ***url*** reputation commands.
```

2022-08-03 13:57 UTC, dantavori commented on Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
> +def parse_intelligence_list(intelligence_list):
no need to parse the response

2022-08-03 13:57 UTC, dantavori commented on Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
> +
as we talked
```suggestion
```

2022-08-03 13:57 UTC, dantavori commented on Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py
> +    page_size = kwargs['page_size'] = int(kwargs.get('page_size', 0))
don't pass these args

2022-08-07 11:25 UTC, dantavori approved these changes

2022-08-07 18:05 UTC, ShirleyDenkberg commented
@MLainer1 Please regenerate the README file.
@dantavori Doc review completed.

2022-08-08 20:21 UTC, merged