MSGraphUser  restore a recently deleted user
demisto/content pull request #20304
Opened 2022-07-29 10:36 UTC by sudkumar1

Added a `msgraph-user-restore-user`  to restore a recently deleted  user

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: #17418

## Description
Added a msgraph-user-restore-user command to restore the recently deleted user.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

2022-08-02 07:45 UTC, israelpoli requested changes
Hi @sudkumar1 
Thank you for your contribution

Please see my comments below
I will review the readme file later today.

Thanks

2022-08-02 07:45 UTC, israelpoli commented on Packs/MicrosoftGraphUser/ReleaseNotes/1_5_0.md
> +- Added the ***msgraph-user-restore-user*** command which restore the user from recently delted user.
```suggestion
- Added the ***msgraph-user-restore-user*** command which restore the user from recently deleted user.
```

2022-08-02 07:45 UTC, israelpoli commented on Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
> +          description: Object ID of the delted user that needs to be restored
```suggestion
          description: Object ID of the deleted user that needs to be restored
```

2022-08-02 07:45 UTC, israelpoli commented on Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py
> +
Please remove this empty line

2022-09-28 12:37 UTC, bakatzir commented
Hey team, what is the status of this PR?

2022-09-29 06:23 UTC, sudkumar1 commented
hi @israelpoli  I have committed  the suggested changes, please let me know if  any other changes are required

2022-11-22 08:43 UTC, israelpoli commented
Hi @sudkumar1 

Sorry for the long delay, this PR eluded me,
can you please merge from master so I continue from here?

Thanx

2023-05-01 15:06 UTC, israelpoli commented
Closed due to inactivity.

2023-05-01 15:06 UTC, closed without merging