Slack reply broadcast
demisto/content pull request #20301
Opened 2022-07-28 20:24 UTC by MWEJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added support for the reply_broadcast parameter as listed on https://api.slack.com/methods/chat.postMessage

## Screenshots
Emulates the use of the following checkbox in the Slack client
![image](https://user-images.githubusercontent.com/2354407/181630397-98f07e51-092a-4bb3-997b-a837707a0c04.png)

## Minimum version of Cortex XSOAR
- [x] 5.5.0
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ X] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-08-03 11:43 UTC, AradCarmi requested changes
Hey @MWEJ,
Excellent job! 🚀
See my suggestions below and let me know when you are available for a short demo. Thanks again for the contribution! 💯

2022-08-03 11:43 UTC, AradCarmi commented on Packs/Slack/Integrations/SlackV3/SlackV3.py
> +    reply_broadcast = args.get('reply_broadcast')
The cast is required as the input type is a string.
```suggestion
    reply_broadcast = argToBoolean(args.get('reply_broadcast'))
```

2022-08-03 11:43 UTC, AradCarmi commented on Packs/Slack/ReleaseNotes/3_0_3.md
> +- Added support for the reply_broadcast parameter to the send-notification command
```suggestion
- Added support for the *reply_broadcast* parameter to the **send-notification** command.
```

2022-08-03 14:34 UTC, MWEJ commented
> Hey @MWEJ, Excellent job! 🚀 See my suggestions below and let me know when you are available for a short demo. Thanks again for the contribution! 💯

I'm available most of the time today (working US PDT hours), but it's a rather simple functionality that doesn't need much explanation

2022-08-03 14:49 UTC, AradCarmi commented
I cannot meet today if you can prepare a short video explaining the changes and display the broadcast it will be enough.

2022-08-04 09:13 UTC, AradCarmi commented
I'm summing up the notes that need to be resolved in order to merge our PR:
1. Please pull from origin/master.
2. Please bump the current release note version (to 3_0_4), by running:
`demisto-sdk update-release-notes -i Packs/Slack -u revision`
3. Please fix the` Run Unit Testing And Lint `errors regarding some broken Unit-Tests caused by the change.
Thanks again,
Arad

2022-08-17 08:03 UTC, AradCarmi commented
Hey @MWEJ, 
Any update regarding my suggestions?
Thanks!

2022-08-31 08:41 UTC, AradCarmi commented
Hey @MWEJ, 
I tried to reach out and didn't get a response.
Please feel free to re-open the PR.
Thanks!

2022-08-31 08:41 UTC, closed without merging