Fix AWS-GuardDuty not respecting the region parameter
demisto/content pull request #20417
Opened 2022-08-05 17:57 UTC by ANT1OFF

## Status
- [ ] In Progress
- [ X ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: AWS-GuardDuty not respecting the region parameter

## Description
Currently the AWSClient used by this integration has its region configured to always be the default region. This change overrides the default region if the region parameter is supplied.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ X ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-08-10 10:42 UTC, israelpoli requested changes
Hi @ANT1OFF 
Thank you for your contribution

please see my comment below
In addition, 
Run `demisto-sdk update-release-notes -i ~/Packs/AWS-GuardDuty` in terminal, for creating RN file, and add there a note for your changes.

you can look at in [here](https://xsoar.pan.dev/docs/documentation/release-notes), how RN file should be.

2022-08-10 10:42 UTC, israelpoli commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +        aws_default_region = demisto.args().get('region')
It is better to leave the meaning of the variable name as it is.

Therefore, in lines 556-557 add like this:
```
region = demisto.args().get('region')
client = aws_client.aws_session(service=SERVICE, region=region)
```

2022-08-10 13:02 UTC, israelpoli commented
@ANT1OFF 
Did you notice my comment about the RN file?

2022-08-11 07:29 UTC, ANT1OFF commented
@israelpoli done.

2022-08-11 10:08 UTC, israelpoli approved these changes
@ANT1OFF
 
Thanks a lot

2022-08-11 10:09 UTC, merged