📝 Microsoft Teams - add important notes to README
demisto/content pull request #20484
Opened 2022-08-09 17:26 UTC by Itay4

added some important notes about the messaging endpoint and certificate

@yaakovi @avidan-H FYI

2022-08-09 17:52 UTC, yaakovi requested changes
add tests

2022-08-16 07:28 UTC, avidan-H commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> + - The messaging endpoint must be either the URL of the Cortex XSOAR server, including the configured port, or the proxy that redirects the messages received from Teams to the Cortex XSOAR server.
```suggestion
 - The messaging endpoint must be one of the following:
 	- the URL of the Cortex XSOAR server, including the configured port
 	- the Cortex XSOAR rerouting URL that you've defined for your Microsoft Teams instance (see the [Using Cortex XSOAR rerouting](#1-using-cortex-xsoar-rerouting) section for more details)
 	- or a proxy that redirects the messages received from Teams to the Cortex XSOAR server (see the [Using NGINX as reverse proxy](#2-using-nginx-as-reverse-proxy) section for more details)
```

2022-08-22 12:48 UTC, yaakovi commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> + In order to verify which certificate is used, run the following (replace <MESSAGING-ENDPOINT> with the messaging endpoint):
```suggestion
 In order to verify which certificate is used, run the following (replace \<MESSAGING-ENDPOINT> with the messaging endpoint):
```

2022-08-23 07:28 UTC, yaakovi approved these changes

2022-08-23 07:29 UTC, merged