Mimecast
demisto/content pull request #20535
Opened 2022-08-14 08:36 UTC by eyalpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/projects/CIAC/issues/CIAC-1389?filter=myopenissues)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-08-22 09:27 UTC, dantavori requested changes
lmk when to review the yml.
I'll complete the review (mainly for the tests) after the demo.

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +        policy_id = policy_id
```suggestion
```

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +    for arg, value in list(policy_obj.items()):
```suggestion
    for arg, value in policy_obj.items():
```
I guess 2to3 added this, I think it's redundant

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +        url = url
remove this if

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +        comment = comment
same

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +    demisto.results('here')
```suggestion
```

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +    readable_output = tableToMarkdown('Message Summery', t=summery_list,
```suggestion
    readable_output = tableToMarkdown('Message Summary', t=summery_list,
```

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +            readable_output += f'Hold message with id {message.get("id")} rejection failed.\n'
why not fail the command in this case? when will it be false?

2022-08-22 09:27 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +        readable_output = 'Message release has failed.'
same here

2022-09-04 07:58 UTC, dantavori approved these changes
Looks great, see last comments from my side.
please review the README: parameters and mimecast-reject-held-message sections are broken.
Please assign docs team to go over the yml file and then regenerate the readme.

2022-09-04 07:58 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
> +    incident['rawJSON'] = json.dumps(held_message)
let's add dbotMirrorId as described here https://xsoar.pan.dev/docs/integrations/fetching-incidents#fetch-history

2022-09-04 07:58 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
> +      description: "An array of Mimecast secure ids: Ids are extracted from command : mimecast-list-held-message"
```suggestion
      description: "A comma-separated list of Mimecast secure ids: Ids are extracted from command : mimecast-list-held-message"
```

2022-09-04 07:58 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
> +      description: An array of routes to filter by. Possible values are internal, outbound and inbound.
```suggestion
      description: A comma-separated list of routes to filter by. Possible values are internal, outbound and inbound.
```
let's check if `Possible values are internal, outbound and inbound.` is not auto genetated in the UI

2022-09-04 07:58 UTC, dantavori commented on Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
> +      description: The Mimecast ID of the message to load. This is returned by the /api/message-finder/search endpoint. (mimecast-search-message command)
```suggestion
      description: A comma-separated list of the Mimecast IDs of the messages to load. This is returned by the /api/message-finder/search endpoint. (mimecast-search-message command)
```

2022-09-04 11:31 UTC, eyalpalo commented
@ShirleyDenkberg Can you have a look at the yaml file for doc review?

2022-09-07 09:35 UTC, ShirleyDenkberg commented
@eyalpalo I reviewed the yml file and have the following questions:
Line 136, is there a spelling mistake?  What is fomr?  What is this supposed to say?
 description: Search in specific dates only (default is all mails **fomr**)
Lines 846 and 847 - is default **all** or **malicious**? The description and defaultValue do not match.
      defaultValue: **malicious**
      description: Filters logs by scan result, default is **all**
Lines 2280 - 2284  Is the display name **from envelope** or **from header**?  The context path says from header.
   - contextPath: Mimecast.HeldMessage.**fromHeader**.displayableName
      description: The display name of the sender (**From envelope**).
      type: String
    - contextPath: Mimecast.HeldMessage.**fromHeader**.emailAddress
      description: The email address of the sender (**From envelope**).
Line 2427 Don't understand this description.  Do you need to enter the attachment or are you supposed to indicate (true/false) if there is an attachment? (In the latter case, the description should be **Whether there is an attachment in the message.**)
name: attachments
      description: The presence of an attachment in the message.

When these issues are resolved (updated) the readme needs to be regenerated.

2022-09-07 09:35 UTC, ShirleyDenkberg commented
@dantavori Doc review completed.

2022-09-11 14:11 UTC, merged