iboss - Add policy layer list management
demisto/content pull request #20667
Opened 2022-08-21 15:19 UTC by mvforgione

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
- Add policy later list manage (remove/add entries)
- Add reliability config parameter

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2022-08-23 01:25 UTC, mvforgione commented
@yaakovi will you be performing the demisto/pull-check "Awaiting documentation review" step or is there something else I must do to kick that off?

2022-08-25 11:11 UTC, yaakovi requested changes
Revert the changes in the `package-lock.json` file

2022-08-25 13:52 UTC, mvforgione commented on Packs/Iboss/Integrations/Iboss/Iboss.py
> +        command_results.append(CommandResults(
@yaakovi originally the result output was patterned around other partner solutions that used similar methodology. This is also the same output format as the pre-existing list modification methods. Is it better to update these new methods with the table view?

2022-08-26 01:18 UTC, mvforgione commented
> Revert the changes in the `package-lock.json` file

@yaakovi just so I understand, the package-lock.json file change is upping the current version to 1.0.3. Is that not appropriate given that is the current version for this PR?

2022-08-29 18:16 UTC, yaakovi commented
> > Revert the changes in the `package-lock.json` file
> 
> @yaakovi just so I understand, the package-lock.json file change is upping the current version to 1.0.3. Is that not appropriate given that is the current version for this PR?

Need to revert the `package-lock.json` changes, not the `pack_metadata.json`.
* pack_metadata.json - the metadata of the pack including the pack version.
* package-lock.json - build related version of node packages

2022-08-29 18:20 UTC, yaakovi commented on Packs/Iboss/Integrations/Iboss/Iboss.py
> +        command_results.append(CommandResults(
I think a single table has better visibility over many tables. With the overhead between tables, you will get less data on the screen.
Also, the user can expand a single entry in a new tab for complete visibility.

2022-08-29 18:22 UTC, yaakovi reviewed
see my responses on the previous comments

2022-09-06 02:39 UTC, mvforgione commented
> see my responses on the previous comments

comments addressed

2022-09-06 02:40 UTC, mvforgione commented on Packs/Iboss/Integrations/Iboss/Iboss.py
> +        command_results.append(CommandResults(
Table views added for results for policy layer lists

2022-09-07 18:41 UTC, mvforgione commented
@yaakovi can you let me know what time you will be able to review the changes? I will perform a merge from upstream master at that time (currently I'm continuously performing this operation)

2022-09-08 14:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=20667) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=20667) before we can accept your contribution.<br/>**16** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: merit-maita<br/>:white_check_mark: mvforgione<br/>:white_check_mark: DeanArbel<br/>:white_check_mark: dorschw<br/>:white_check_mark: MLainer1<br/>:white_check_mark: GuyAfik<br/>:white_check_mark: YuvHayun<br/>:white_check_mark: eyalpalo<br/>:white_check_mark: Shellyber<br/>:white_check_mark: amshamah419<br/>:white_check_mark: yaakovi<br/>:white_check_mark: daryakoval<br/>:white_check_mark: ShacharKidor<br/>:white_check_mark: yucohen<br/>:white_check_mark: adi88d<br/>:white_check_mark: dansterenson<br/>:x: mmhw<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=20667) it.</sub>

2022-09-12 16:56 UTC, merged