Jwilkes nmap 08232022
demisto/content pull request #20758
Opened 2022-08-24 14:51 UTC by johnnywilkes

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
We were creating playbook for NMAP scans for a project and decided to make them modular enough to share with all.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [X] Documentation

2022-08-24 14:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=20758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=20758) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Johnathan Wilkes<br/>:x: johnnywilkes<br/><hr/>**Johnathan Wilkes** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=20758) it.</sub>

2022-08-24 16:06 UTC, johnnywilkes commented
@ShacharKidor , @bakatzir said to work with you on PRs.  This is the first of many so feedback is welcome!

CC: @andrew-paloalto

2022-08-25 12:12 UTC, ShacharKidor requested changes
Hi @johnnywilkes, 
Thank you for your contribution! looks great. 

I added 3 little fixes to the Release note and pack metadata files - please commit them. 

@idovandijk - Please review the 2 new playbooks. 

I'm available here or via slack for any questions. 

Thanks again :)

2022-08-25 12:12 UTC, ShacharKidor commented on Packs/Nmap/ReleaseNotes/1_1_0.md
> +- Added the "NMAP - Single Port Scan" playbook to conduct a single port NMAP scan.
```suggestion
- Added the **NMAP - Single Port Scan** playbook to conduct a single port NMAP scan.
```

2022-08-25 12:12 UTC, ShacharKidor commented on Packs/Nmap/ReleaseNotes/1_1_0.md
> +- Added the "NMAP - Banner Check" to conduct a single port NMAP scan and check regular expression against banner.
```suggestion
- Added the **NMAP - Banner Check"** to conduct a single port NMAP scan and check regular expression against the banner.
```

2022-08-25 12:12 UTC, ShacharKidor commented on Packs/Nmap/pack_metadata.json
> +        "CommonScripts"
Please remove that. 
```suggestion
```

2022-08-25 13:17 UTC, johnnywilkes commented
@ShacharKidor, thank you for the quick review!  I have commited your suggestions.

2022-08-28 10:42 UTC, ShirleyDenkberg commented
@johnnywilkes I created a pack readme for the NMAP content pack. I sent it to you via Slack. Please add to this PR. This content will appear in Marketplace. Feel free to edit the content if you want.
@ShacharKidor @idovandijk Doc review completed.

2022-08-29 13:04 UTC, johnnywilkes commented
@ShirleyDenkberg , I have added the README file

2022-08-29 15:07 UTC, idovandijk requested changes
Hi @johnnywilkes, thank you for this contribution. I really like your playbooks and have to say your work is very clean, so there is not much to change here. 

I do have to point out what I think is a logical flaw.
It looks like in the banner matching playbook you output the same results as in the port scan, but what is interesting is whether the banner matched the regex.
![image](https://user-images.githubusercontent.com/43602124/187232647-955f4368-81c9-46ca-9e48-eac36887a336.png)

Also a suggestion - since both subplaybooks check different things, I would suggest that you change the output to be something like `NmapPortScanResult` and `NmapBannerCheckResult` so if both are used as subplaybooks, their results would still be distinguishable.

If you think I am mistaken please let me know why. Otherwise please make the changes/fixes and let me know once you're done.
Thanks again!

2022-08-29 15:28 UTC, johnnywilkes commented
@idovandijk , thanks for looking this over.  the reason for these playbooks for us was to determine if a ASM issue was still present.  This could be something like:
- Is RDP port open?
- Is SSH port open and banner matches insecure OpenSSH version?

Therefore, I thought the the result should be either: yes the issue is still observable, no the issue isn't observable or inconclusive.

I don't mind changing `ScanResult` to `NmapPortScanResult` or `NmapBannerCheckResult` but that would also result in more logic added to its parent playbook.

2022-08-29 15:56 UTC, idovandijk commented
> 

I see, that makes more sense now. If the use-case is as you said then it would make sense to keep the current outputs I believe. However, I don't see the parent playbook as part of this PR. Were you planning to contribute that playbook? Seeing it could give better context of how these 2 are meant to be used in your case. I'm not sure if it's clear enough for the banner matching playbook (simply returns Open if the regex matches)

2022-08-29 16:11 UTC, johnnywilkes commented
@idovandijk , because these playbooks are modular we talked to @bakatzir about adding the Nmap content back.  The parent is less modular and more specific to ASM so we will add the the ASM content pack at a later time.  I thought I had some decent explanation:
![image](https://user-images.githubusercontent.com/32227961/187245925-3dbd02b4-dc52-4a61-ad09-e34a25d93011.png)
![image](https://user-images.githubusercontent.com/32227961/187245954-41d1eb00-df38-4162-8b6f-3a8c7cfff142.png)

Any suggested changes to make it more clear?

2022-08-30 07:32 UTC, idovandijk commented
> @idovandijk , because these playbooks are modular we talked to @bakatzir about adding the Nmap content back. The parent is less modular and more specific to ASM so we will add the the ASM content pack at a later time. I thought I had some decent explanation: ![image](https://user-images.githubusercontent.com/32227961/187245925-3dbd02b4-dc52-4a61-ad09-e34a25d93011.png) ![image](https://user-images.githubusercontent.com/32227961/187245954-41d1eb00-df38-4162-8b6f-3a8c7cfff142.png)
> 
> Any suggested changes to make it more clear?

I missed that description, thanks :)

2022-08-30 07:32 UTC, idovandijk approved these changes
Great job

2022-08-30 11:56 UTC, ShacharKidor approved these changes
@johnnywilkes  Great Job!

2022-08-30 11:56 UTC, merged