Keeper integration
demisto/content pull request #20786
Opened 2022-08-26 16:51 UTC by idimov-keeper

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Initial commit for a new integration - Keeper Secrets Manager
Related docker image in [PR#8448](https://github.com/demisto/dockerfiles/pull/8448)

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-08-26 16:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=20786) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=20786) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=20786) it.</sub>

2022-08-28 12:01 UTC, kgal-pan commented
@JasBeilin - Please review and approve https://github.com/demisto/dockerfiles/pull/8448 before reviewing this one.

2022-08-30 10:25 UTC, kgal-pan commented on Packs/KeeperSecretsManager/Integrations/KeeperSecretsManager/KeeperSecretsManager.yml
> +  dockerimage: demisto/keeper-ksm:latest
```suggestion
  dockerimage: demisto/keeper-ksm:1.0.0.33394
```

2022-08-31 15:08 UTC, kgal-pan commented
https://github.com/demisto/content/pull/20875 blocking [UT build](https://app.circleci.com/pipelines/github/demisto/content/186914/workflows/e8711195-bb48-4f7f-9718-63b06012c848/jobs/561304?invite=true#step-108-19)

2022-09-01 09:15 UTC, idovandijk commented
If any playbooks are added to this PR please reassign me to review, for now I'm unassigning :)

2022-09-01 09:20 UTC, kgal-pan commented
> #20875 blocking [UT build](https://app.circleci.com/pipelines/github/demisto/content/186914/workflows/e8711195-bb48-4f7f-9718-63b06012c848/jobs/561304?invite=true#step-108-19)

@idimov-keeper - Please sync with `master`.

2022-09-04 08:28 UTC, JasBeilin requested changes
Thank you for this contribution!
Please see my comment below.

2022-09-14 18:01 UTC, kgal-pan commented on Packs/KeeperSecretsManager/Integrations/KeeperSecretsManager/KeeperSecretsManager.py
> +def main() -> None:
Please add to increase coverage and [overcome build failure](https://app.circleci.com/pipelines/github/demisto/content/191887/workflows/2a73ea46-3107-4b7f-8f54-231d68186492/jobs/570866/steps?invite=true#step-108-14).

```suggestion
def main() -> None:   # pragma: no cover
```

2022-09-14 18:02 UTC, kgal-pan commented on Packs/KeeperSecretsManager/Integrations/KeeperSecretsManager/KeeperSecretsManager.py
> +    credentials = demisto.params()['credentials']
```suggestion
    credentials = demisto.params().get('credentials')
```

2022-09-15 05:48 UTC, JasBeilin approved these changes

2022-09-15 05:48 UTC, merged