Exterro1.0
demisto/content pull request #20849
Opened 2022-08-30 11:48 UTC by sriram7797

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
New pull request to merge Exterro/AccessData Pack into the demisto/content reposiotry. With the Exterro FTK Connect automation platform, users can now leverage Cortex XSOARs security orchestration and automation capabilities to trigger the immediate capture and preservation of endpoint evidence by FTK Enterprise, FTK Central, or FTK Lab.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-08-30 12:08 UTC, kgal-pan commented
@JasBeilin - Please review https://github.com/demisto/dockerfiles/pull/8473. It's the cause of the [UT failure](https://app.circleci.com/pipelines/github/demisto/content/186826/workflows/c8348658-a7ea-4d07-a511-5be8c100b92d/jobs/561086).

2022-08-31 14:37 UTC, YuvHayun requested changes
Hi @sriram7797, thx for your contribution!
I left small change requests here and in the docker PR as well.
Also, I tagged @idovandijk to review your playbooks.

2022-09-01 01:45 UTC, sriram7797 commented
> Hi @sriram7797, thx for your contribution! I left small change requests here and in the docker PR as well. Also, I tagged @idovandijk to review your playbooks.

@YuvHayun i have updated the branch with suggested changes.. Can you please tell me exactly what changes required in the Dockerfile PR? (https://github.com/demisto/dockerfiles/pull/8473)

2022-09-01 07:21 UTC, YuvHayun requested changes
Hey @sriram7797!
I left some minor comments to fix.
I approved the docker file pr and I'll merge them both when we're done with this pr.
Thank you!

2022-09-01 07:21 UTC, YuvHayun commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +  dockerimage: demisto/accessdata:1.1.0.32812
```suggestion
  dockerimage: devdemisto/accessdata:1.1.0.33490
```

2022-09-01 07:39 UTC, sriram7797 commented
> Hey @sriram7797! I left some minor comments to fix. I approved the docker file pr and I'll merge them both when we're done with this pr. Thank you!

@YuvHayun Thanks. I have updated branch with suggested changes.

2022-09-01 08:26 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +  dockerimage: devdemisto/accessdata:1.1.0.33490
```suggestion
  dockerimage: demisto/accessdata:1.1.0.33589
```

2022-09-01 08:26 UTC, YuvHayun commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +  dockerimage: devdemisto/accessdata:1.1.0.33490
```suggestion
  dockerimage: demisto/accessdata:1.1.0.33589
```

2022-09-01 09:10 UTC, idovandijk requested changes
Thank you for the contribution @sriram7797!
As someone who has been using your products I'm really happy to see content coming from Exterro, and hoping to see your API grow and the integration with XSOAR evolving more and more. The possibilities would be endless.

Regarding your PR, there are some things that I need to be clarified before we can continue.
The playbook `Exterro FTK: Initiate Memory Dump Collection` has one task, but the playbook and the task have no inputs.
Also looks like the `exterro-ftk-trigger-workflow` command needs to a schedule task to poll the workflow status - for that we use Generic Polling. Are you familiar with Generic Polling in XSOAR?
Additionally, the files have `fromversion` field of 5.0 instead of 6.5. Please use the Demisto SDK to `format` the files.

2022-09-01 10:05 UTC, sriram7797 commented
> idovandijk

Automation ID is the required input from user. Should it be received from playbook input and mapped to Automation ID field? Can't we directly input it to the Automation ID field? Other params are optional & used based on the use case for which task is used. i am not familiar with Generic polling in XSOAR.

**Sample use case:**
Playbook should be triggered based on the incident type and incident field can be mapped to the task fields (like Target IPs field of the task can be mapped to IP Address field from the incident)

2022-09-01 10:52 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: The Id of the automation workflow.
Should this not be the workflow ID?

```suggestion
    - name: workflow_id
      required: true
      type: number
      description: The Id of the automation workflow.
```

2022-09-01 10:52 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: The name of the case.
```suggestion
    - name: case_name
      required: false
      description: The name of the case.
```

2022-09-01 10:53 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: Value of caseids.
```suggestion
    - name: case_ids
      required: false
      description: Value of caseids.
```

2022-09-01 10:53 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: The filepath of the evidence.
```suggestion
    - name: evidence_path
      required: false
      description: The filepath of the evidence.
```

2022-09-01 10:53 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: Targetips for the collection
```suggestion
    - name: target_ips
      required: false
      description: Target IPs for the collection
```

2022-09-01 10:54 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: The filepath of the search and tag .
```suggestion
    - name: search_tag_path
      required: false
      description: The filepath of the search and tag
```

2022-09-01 10:59 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: The path to export files.
```suggestion
    - name: export_path
      required: false
      description: The path to export files.
```

2022-09-02 09:42 UTC, sriram7797 commented
@kgal-pan Any specific reason that we need to convert to lower case? current field names are validated against task in xsoar (dev environment). If i make change here, then i need to make another PR for docker. is that needed?

2022-09-04 08:41 UTC, kgal-pan commented
> @kgal-pan Any specific reason that we need to convert to lower case?

The reason is that the arguments are required to be in snake case standard. This is mentioned in [Command Arguments](https://xsoar.pan.dev/docs/integrations/yaml-file#command-arguments) and [Contribution Design](https://xsoar.pan.dev/docs/tutorials/tut-design#command-arguments):

![image](https://user-images.githubusercontent.com/85439776/188305104-6d6df64f-379e-44fa-af1b-a43420af4093.png)

One of the reasons is that the auto-completion of arguments in CLI breaks when there's a space in the argument.

2022-09-05 07:46 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: Value of caseids.
@sriram7797 

> Is this expected to be a comma-separated list of case IDs? If yes, use [isArray: true](https://xsoar.pan.dev/docs/integrations/yaml-file#command-arguments) and parse the argument using [argToList](https://xsoar.pan.dev/docs/reference/api/common-server-python#argtolist)

2022-09-05 07:47 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +      description: Targetips for the collection
@sriram7797 - 

> Is this expected to be a comma-separated list of case IDs? If yes, use [isArray: true](https://xsoar.pan.dev/docs/integrations/yaml-file#command-arguments) and parse the argument using [argToList](https://xsoar.pan.dev/docs/reference/api/common-server-python#argtolist)

2022-09-05 07:49 UTC, kgal-pan commented
> @kgal-pan Updated task name with snake case.

Thanks. See comments https://github.com/demisto/content/pull/20849#discussion_r962590262 and https://github.com/demisto/content/pull/20849#discussion_r962589998. These weren't addressed yet.

2022-09-05 12:10 UTC, sriram7797 commented
@kgal-pan yml file updated with isArray: true field for case_ids and target_ips

2022-09-07 06:15 UTC, sriram7797 commented
@kgal-pan isArray:true and argToList changes are addressed, playbook is removed from branch. Please process the docker PR (https://github.com/demisto/dockerfiles/pull/8534) to pass unit test.

2022-09-11 09:26 UTC, kgal-pan commented on Packs/Exterro/Integrations/Exterro/Exterro.yml
> +  dockerimage: demisto/accessdata:1.1.0.33672
```suggestion
  dockerimage: demisto/accessdata:1.1.0.33872
```

2022-09-11 09:28 UTC, kgal-pan commented
@YuvHayun - Feel free to start the review

2022-09-11 11:08 UTC, YuvHayun commented
> @YuvHayun - Feel free to start the review

I've done mine before and it seems like there weren't any big changes.
I approve it from my side, just waiting for @sriram7797 to change the docker image so I can run instance tests.

2022-09-11 14:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=20849) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=20849) before we can accept your contribution.<br/>**12** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: sriram7797<br/>:white_check_mark: adi88d<br/>:white_check_mark: yucohen<br/>:white_check_mark: MosheEichler<br/>:white_check_mark: eyalpalo<br/>:white_check_mark: yaakovi<br/>:white_check_mark: GuyAfik<br/>:white_check_mark: omerKarkKatz<br/>:white_check_mark: content-bot<br/>:white_check_mark: YuvHayun<br/>:white_check_mark: daryakoval<br/>:white_check_mark: AradCarmi<br/>:x: DinaMeylakh<br/>:x: MichaelYochpaz<br/>:x: michal-dagan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=20849) it.</sub>

2022-09-11 15:03 UTC, sriram7797 commented
@kgal-pan @YuvHayun  Updated docker image. Please review.

2022-09-11 15:26 UTC, YuvHayun commented on Packs/Exterro/Integrations/Exterro/Exterro.py
> +def main():
```suggestion
def main():  # pragma: no cover
```
I see the build is failing due to low coverage percentage (you need at least 70 %).
Please add this comment to the main function and add tests for the **_test_module** function.

That's all from my side.

2022-09-12 06:17 UTC, YuvHayun commented on Packs/Exterro/Integrations/Exterro/Exterro.py
> +def _test_module(client):
```suggestion
def _test_module(client):  # pragma: no cover
```

2022-09-12 07:43 UTC, kgal-pan approved these changes

2022-09-12 07:45 UTC, merged