Adding generate_alert to create/update indicator.
demisto/content pull request #20855
Opened 2022-08-30 15:27 UTC by ANT1OFF

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Adding generate_alert as an option to the create/update indicator in security center command. Setting the default to True to keep the same behaviour as before. This is primarily useful when using the command to add indicators as allowed.

Adding the generate_alert command to the false positive playbook and setting it to default to false.

## Screenshots
![image](https://user-images.githubusercontent.com/32440065/187477512-ed4eb731-3b50-4e63-9d1e-a6fccf9c1bb6.png)
![image](https://user-images.githubusercontent.com/32440065/187477610-1a5ef5cf-ffd6-4a55-a5d7-1d69e3a8836a.png)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

2022-08-30 15:46 UTC, ANT1OFF commented
The changes made to the playbook are minimal to get it working and not generate future alerts on allowed indicators. The input configuration should probably be propagated to the other MDE I&R playbooks. Alternatively, the False Positive playbook could prompt the user to select whether to generate an alert when a given indicator is added to as allowed.  @ssokolovich any thoughts on what approach would be best?

2022-08-31 10:46 UTC, YuvHayun requested changes
Hi @ANT1OFF, thx for your contribution!
I added a small fix request.
Also:
1. Please add release notes, you can refer to [this guide](https://xsoar.pan.dev/docs/documentation/release-notes).
2. I requested @idovandijk to review the playbook changes so wait for further instructions.

Feel free to contact me if you have any questions.
I'm available here and on slack.

2022-08-31 10:46 UTC, YuvHayun commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +    generate_alert = args.get('generate_alert', True)
```suggestion
    generate_alert = argToBoolean(args.get('generate_alert', True))
```

2022-08-31 11:39 UTC, YuvHayun requested changes
@ANT1OFF thx for the quick reply!
small fix regarding the RN.

2022-08-31 11:39 UTC, YuvHayun commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_12_3.md
> +- Updated the playbook to set false positive indicators not to generate an alert by default.
```suggestion
- Improved implementation of the playbook to set false positive indicators not to generate an alert by default.
```

2022-08-31 11:39 UTC, YuvHayun commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_12_3.md
> +- Adding the option to disable the generate alert flag when adding an indicator to Microsoft Security Center. Primarily useful when setting indicators to allow.
```suggestion
- Added the option to disable the generate alert flag when adding an indicator to Microsoft Security Center. Primarily useful when setting indicators to allow.
```

2022-08-31 11:43 UTC, YuvHayun commented
@ANT1OFF thx again for the quick reply!
Let's wait for Ido's review.

2022-08-31 12:23 UTC, ssokolovich commented
@ANT1OFF - Awesome enhancement! 
As for your question, I think we should give that as an option through the data collection task and not the input (note that you haven't added this input to the PB inputs).
Should look like this ( so we can give the decision to the analyst and not something more hardcoded such as PB input):
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/88268646/187677089-5e70afb0-9de7-471a-9104-bebf8f515878.png">
In this way, the default is always false (to avoid mistakes) - and the input was always provided to the user.  Let me know your thoughts on this :)

2022-08-31 12:33 UTC, ANT1OFF commented
@ssokolovich agreed the second option would be best :)

2022-09-07 09:46 UTC, ssokolovich commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_False_Positive_Incident_Handling_README.md
> +| GenerateAlert | Whether an alert should be created for future occurrences of the indicator. | False | Optional |
@YuvHayun - no need for this input.

2022-09-12 09:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=20855) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=20855) before we can accept your contribution.<br/>**4** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: ANT1OFF<br/>:white_check_mark: YuvHayun<br/>:white_check_mark: content-bot<br/>:white_check_mark: MLainer1<br/>:x: MichaelYochpaz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=20855) it.</sub>

2022-09-13 09:37 UTC, YuvHayun approved these changes

2022-09-13 09:37 UTC, merged