Contrib/CDS Cofense Intelligencev2 111
demisto/content pull request #20877
Opened 2022-08-31 13:07 UTC by crestdatasystems

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
- Updated the Docker image to: *demisto/python3:3.10.6.33415*.
- **Note**: Updated the following commands to match the exact indicator to be searched for.
    - ***url***
    - ***domain***

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

2022-08-31 17:12 UTC, kgal-pan commented
[UT build failure](https://app.circleci.com/pipelines/github/demisto/content/187153/workflows/f99b01d3-4ea8-4054-a68b-731eb2ee78f0/jobs/561722?invite=true#step-108-19) blocked by https://github.com/demisto/content/pull/20875.

2022-09-01 08:31 UTC, kgal-pan commented
@crestdatasystems - Please fill out [the contribution form](https://forms.gle/XDfxU4E61ZwEESSMA) so we can start review.

2022-09-01 09:20 UTC, kgal-pan commented
> [UT build failure](https://app.circleci.com/pipelines/github/demisto/content/187153/workflows/f99b01d3-4ea8-4054-a68b-731eb2ee78f0/jobs/561722?invite=true#step-108-19) blocked by #20875.

@crestdatasystems - Please sync with `master`.

2022-09-02 07:15 UTC, crestdatasystems commented
@kgal-pan this is under progress and we want final approval from the client so please keep this on hold for a few days.

2022-09-03 09:28 UTC, YuvHayun commented
> @kgal-pan this is under progress and we want final approval from the client so please keep this on hold for a few days.

No problem, please let us know when it's ready.

2022-09-11 15:22 UTC, YuvHayun commented
@crestdatasystems how's it going?
Let me know if you need any help.

2022-09-13 11:17 UTC, crestdatasystems commented
> @crestdatasystems how's it going? Let me know if you need any help.

We get final approval from the client, so @YuvHayun can start review this PR

2022-09-14 05:42 UTC, YuvHayun requested changes
Hi @crestdatasystems, thank you for your contribution.
Please see my comments below.

2022-09-14 05:42 UTC, YuvHayun commented on Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.py
> +    block_type: str = BLOCK_TYPE_MAPPING[command]
```suggestion
    block_type: str = BLOCK_TYPE_MAPPING.get(command)
```

2022-09-14 05:42 UTC, YuvHayun commented on Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.py
> +    block_type = BLOCK_TYPE_MAPPING["ip"]
```suggestion
    block_type = BLOCK_TYPE_MAPPING.get("ip")
```

2022-09-14 06:04 UTC, crestdatasystems commented on Packs/CofenseIntelligenceV2/.secrets-ignore
>  45.116.166.177
Yes, there are no secrets in the code. In addition, to ensure that we have executed the `demisto-sdk secrets` command,

2022-09-14 06:04 UTC, crestdatasystems commented on Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.py
> +    block_type: str = BLOCK_TYPE_MAPPING[command]
Okay we will do this change

2022-09-14 06:04 UTC, crestdatasystems commented on Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.py
> +    block_type = BLOCK_TYPE_MAPPING["ip"]
Okay we will do this change

2022-09-14 06:40 UTC, crestdatasystems commented
> requested

Addressed the suggested changes

2022-09-14 06:57 UTC, YuvHayun commented on Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.py
> +    block_type: str = BLOCK_TYPE_MAPPING.get(command)
```suggestion
    block_type: str = BLOCK_TYPE_MAPPING.get(command, "")
```
This should fix the current Mypy problem.

2022-09-14 09:10 UTC, YuvHayun approved these changes

2022-09-14 09:11 UTC, merged