[Carbon Black Enterprise Response] New pack Carbon Black Common Fields for Unique ID field
demisto/content pull request #20897
Opened 2022-09-01 12:21 UTC by ennozdd

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/content/pull/19834

## Description
Unique ID is needed to update the alerts. With this PR Carbon Black EDR Unique ID is created and mapped

https://developer.carbonblack.com/reference/enterprise-response/5.1/rest-api/#updateresolve-alerts

Edit: On my latest PR I was asked to create another pack. See https://github.com/demisto/content/pull/19834

## Screenshots
![image](https://user-images.githubusercontent.com/49711791/187911207-cb87d8a4-654f-4fa2-b148-3da4b549fdef.png)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-09-04 06:19 UTC, JasBeilin requested changes
Hi, thank you for this contribution!
Before we start the review, could you please explain why you added a whole new pack for the new incident field? It can be added to the pack itself (carbon_Black_Enterprise_Response) instead.

2022-09-05 14:09 UTC, idovandijk approved these changes
nice job!

2022-09-05 14:48 UTC, JasBeilin requested changes
Great job.
One thing to fix - No release note entry was found for the mapper "Carbon Black EDR Mapper" in the Carbon_Black_Enterprise_Response pack. Please add it.

2022-09-18 07:43 UTC, JasBeilin requested changes
Looks good, lets change the docker image to a production one and merge :)

2022-09-18 07:43 UTC, JasBeilin commented on .circleci/config.yml
> -      - image: devdemisto/content-build:3.0.0.33772  # disable-secrets-detection
Why are we using devdemisto docker image?

2022-09-19 05:59 UTC, JasBeilin approved these changes

2022-09-19 06:01 UTC, merged