2to3CuckooSandbox
demisto/content pull request #20971
Opened 2022-09-06 09:53 UTC by JudahSchwartz

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-09-06 11:40 UTC, tkatzir commented on Packs/CuckooSandbox/Scripts/CuckooDetonateFile/CuckooDetonateFile.py
> +res = demisto.executeCommand("cuckoo-create-task-from-file", demisto.args())
Put the "meat" of the script in a `main` method

2022-09-06 11:48 UTC, tkatzir requested changes
Looks good. Some minor comments

2022-09-06 14:14 UTC, yaakovi requested changes

2022-09-06 14:14 UTC, yaakovi commented on Packs/CuckooSandbox/ReleaseNotes/1_1_2.md
> +####Deprecated the following scripts
follow the release notes guidelines

2022-09-06 14:25 UTC, JudahSchwartz commented on Packs/CuckooSandbox/ReleaseNotes/1_1_2.md
> +####Deprecated the following scripts
done

2022-09-06 17:42 UTC, yaakovi approved these changes
Specify in the README the script is deprecated.

2022-09-06 17:42 UTC, yaakovi commented on Packs/CuckooSandbox/Scripts/CuckooTaskStatus/CuckooTaskStatus.yml
> +comment: Deprecated. Use the 'cuckoo-view-task' command instead.
relevant for all
```suggestion
comment: Deprecated. Use the 'cuckoo-view-task' command instead.
deprecated: true
```

2022-09-06 17:42 UTC, yaakovi commented on Packs/CuckooSandbox/ReleaseNotes/1_1_2.md
> +Updated the Docker image to: *demisto/python3:3.10.6.33415*.
relevant for all
```suggestion
#### CuckooTaskStatus
- Deprecated. Use the 'cuckoo-view-task' command instead.
- Updated the Docker image to: *demisto/python3:3.10.6.33415*.
```

2022-09-11 12:34 UTC, yaakovi approved these changes

2022-09-11 12:35 UTC, tkatzir approved these changes

2022-09-12 06:53 UTC, merged