ATDDetonate change to py3
demisto/content pull request #21058
Opened 2022-09-07 11:48 UTC by ostolero

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-09-11 12:02 UTC, tkatzir requested changes

2022-09-11 12:02 UTC, tkatzir commented on Packs/McAfee_Advanced_Threat_Defense/Scripts/ATDDetonate/ATDDetonate.py
> +                            'Could not retrieve results from ATD (may be due to timeout). last status = {0}'.format(status)})
```suggestion
                            f'Could not retrieve results from ATD (may be due to timeout). last status = {status}'})
```

2022-09-11 12:02 UTC, tkatzir commented on Packs/McAfee_Advanced_Threat_Defense/Scripts/ATDDetonate/ATDDetonate.py
> +                        "Contents": 'ATD: Failed to detonate source, exit status = {0}'.format(status)})
```suggestion
                        f"Contents": 'ATD: Failed to detonate source, exit status = {status}'})
```

2022-09-12 07:04 UTC, tkatzir approved these changes

2022-09-12 09:28 UTC, ostolero commented
Validation fails becaus sleep mechanism used in the script. we won't change it so a force merge is needed.

2022-09-13 13:20 UTC, merged