Migrate SendEmailToManager to Python 3
demisto/content pull request #21112
Opened 2022-09-08 13:02 UTC by MichaelYochpaz

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Migrate SendEmailToManager script from Python 2 to Python 3

2022-09-21 08:40 UTC, bziser reviewed
Good job!

2022-10-03 12:59 UTC, tkatzir requested changes
Looks good. Some minor comments.

2022-10-03 13:49 UTC, MichaelYochpaz commented on Packs/Active_Directory_Query/Scripts/SendEmailToManager/SendEmailToManager.py
> +    if not (type(response == list and type(response[0].get('Contents')) == list
Nice catch, fixed in https://github.com/demisto/content/pull/21112/commits/76355952a356bb48633951518ace7e4d9cbb6783

2022-10-06 08:21 UTC, tkatzir approved these changes

2022-10-06 08:32 UTC, merged