Fix: Updated Urlscan blacklisted error message
demisto/content pull request #21138
Opened 2022-09-09 18:46 UTC by vector-sec

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
The blacklisted URL error message that the Urlscan API returns is different than what the XSOAR integration is expecting. This caused the `continue_on_blacklisted_urls` argument to not have the desired effect of avoiding an error being returned to the war room. This update to the XSOAR integration restores the functionality of the `continue_on_blacklisted_urls` argument.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-09-11 10:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=21138) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=21138) before we can accept your contribution.<br/>**7** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: adi88d<br/>:white_check_mark: vector-sec<br/>:white_check_mark: yucohen<br/>:white_check_mark: MosheEichler<br/>:white_check_mark: eyalpalo<br/>:white_check_mark: YuvHayun<br/>:white_check_mark: GuyAfik<br/>:x: DinaMeylakh<br/>:x: MichaelYochpaz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=21138) it.</sub>

2022-09-11 12:10 UTC, YuvHayun commented
Hey @vector-sec, thx for your contribution.
few small fixes:
- Please change the docker image mentioned in the yml file, the new docker image should be: 3.10.6.33415
- Please add RN, you can do it by using the command `demisto-sdk update-release-notes -i Packs/<pack name>`
- Please fix the failing unit test, my guess it's just a trailing white space or something like that.


Let me know if you have any question.

2022-09-12 13:04 UTC, vector-sec commented
@YuvHayun I believe I've handled the docker image update and the failing unit test. For release notes I get this response from demisto-sdk when running the command

```
You are using demisto-sdk 1.7.4.
Starting to update release notes.

[WARNING]: General: [BA107] - Running on master branch while using git is ill advised.
run: 'git checkout -b NEW_BRANCH_NAME' and rerun the command.

Either no changes were found in UrlScan pack or the changes found should not be documented in the release notes file.
If relevant changes were made, please commit the changes and rerun the command.
```

2022-09-12 14:47 UTC, YuvHayun commented
> Either no changes were found in UrlScan pack or the changes found should not be documented in the release notes file.
> If relevant changes were made, please commit the changes and rerun the command.

seems like you're working from master branch which you shouldn't do so.
I'll update the RN in the internal PR, let's just fix the unit test - we should validate the error msg.

2022-09-12 14:47 UTC, YuvHayun requested changes

2022-09-12 14:47 UTC, YuvHayun commented on Packs/UrlScan/Integrations/UrlScan/UrlScan_test.py
> -        assert response[0].get('error_string') == 'The submitted domain is on our blacklist, we will not scan it.'
I think deleting this is not the solution, try to find out was is actually printed in `response[0].get('error_string')` and add it as the expected result.

2022-09-13 06:19 UTC, YuvHayun commented
Hey @vector-sec.
I fixed the unit test issue - I do think it's necessary to make sure the right error msg is the one returned to the user.
Also, I added release notes to document the docker changes.

2022-09-13 06:26 UTC, YuvHayun approved these changes

2022-09-13 08:42 UTC, YuvHayun commented
@vector-sec merging this pr, thx for your contribution.

2022-09-13 08:42 UTC, merged