Adding new integration -  Aws Secrets Manager
demisto/content pull request #21149
Opened 2022-09-11 11:04 UTC by ishaish103

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-2104

## Description
Aws Secrets manager integration

## Must have
- [ ] Tests
- [ ] Documentation

2022-09-11 14:43 UTC, DeanArbel requested changes

2022-09-11 14:43 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +    return_results(CommandResults(
Please add `outputs_key_field`.

2022-09-11 14:43 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +    return_results(CommandResults(
Please add `outputs_key_field`.

2022-09-11 14:43 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +def aws_secrets_manager_secret_delete_command(client: AWSClient, args: Dict[str, Any]) -> CommandResults:
This returns `None`.

2022-09-11 14:43 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +def aws_secrets_manager_secret_restore_command(client: AWSClient, args: Dict[str, Any]) -> CommandResults:
This returns `None`.

2022-09-11 14:43 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +        return_error('secret_id is mandatory inorder to run this command!')
Please replace this with a raise.

2022-09-11 14:43 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +            demisto.debug(f"Could not fetch credentials: {args.get('secret_id')}. Error: {e}")
I believe in this case it's better to raise this as an error, as the user won't see this error.
@yuvalbenshalom wdyt?

2022-09-11 14:43 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +        readable_output=human_readable
Please add `outputs_key_field`.

2022-09-12 08:47 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +            return_error('Delete command cannot be executed with both args: delete_immediately and days_of_recovery')
done

2022-09-12 08:48 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +        kwargs['ForceDeleteWithoutRecovery'] = args.get('delete_immediately', False) == True
done

2022-09-12 08:48 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +        return_error('secret_id is mandatory inorder to run this command!')
done

2022-09-12 08:48 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +    return_results(CommandResults(
done

2022-09-12 08:48 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +    return_results(CommandResults(
done

2022-09-12 08:48 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +def aws_secrets_manager_secret_delete_command(client: AWSClient, args: Dict[str, Any]) -> CommandResults:
done

2022-09-12 08:48 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +def aws_secrets_manager_secret_restore_command(client: AWSClient, args: Dict[str, Any]) -> CommandResults:
done

2022-09-12 08:48 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +        return_error('secret_id is mandatory inorder to run this command!')
done

2022-09-12 08:49 UTC, ishaish103 commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +        readable_output=human_readable
done

2022-09-20 12:13 UTC, ShirleyDenkberg commented
@ishaish103 
- Need descriptions for all outputs in the yml file.
- Need to see the generated README file.
- I created content for the pack README.
Please ping me when the descriptions and README are added so that I can review them.

2022-09-28 10:54 UTC, ShirleyDenkberg commented
@ishaish103 Please generate an integration README file.
@DeanArbel @yuvalbenshalom

2022-10-20 08:31 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +                LOG(f'({creds_dict[cred_key]}) has no keys supporting the format')
Please replace this with `demisto.info` - `LOG` has been deprecated.

2022-10-20 08:31 UTC, DeanArbel commented on Packs/Aws-SecretsManager/Integrations/AwsSecretsManager/AwsSecretsManager.py
> +            return_error(f'theres is a problem parsing ({creds_dict[cred_key]}) secret value, {e}')
Please replace this with a raise - `return_error` is expected to run in `main` only.

2022-10-23 15:03 UTC, DeanArbel approved these changes
Great job

2022-10-23 17:17 UTC, merged