Gmail to python 3
demisto/content pull request #21181
Opened 2022-09-12 15:16 UTC by sapirshuker

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [CIAC-3782](https://jira-hq.paloaltonetworks.local/browse/CIAC-3782)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-10-13 09:09 UTC, Shellyber requested changes
Great job! 👍 
Few general notes: 
1. Regarding the test and the input_data file - for short examples (for example user_id_test or title) please move it to the unittest file itself. Only long and full responses should be in the test_data file, the rest in the unittest file
2. Update the release notes - write the changes made in the PR (without the tests) moving to python3 and fixing the bug

2022-10-13 09:16 UTC, sapirshuker commented on Packs/Gmail/Integrations/Gmail/Gmail.py
> -def organization_format(org_list):
it does not have any use in the integration

2022-10-13 09:53 UTC, sapirshuker commented on Packs/Gmail/ReleaseNotes/1_2_0.md
> +- add unit test emails_to_entry, mailboxes_to_entry, filters_to_entry, sent_mail_to_entry,
it was deleted in the last commit

2022-10-18 06:56 UTC, Shellyber reviewed
Nice job! 
Last notes! Also don't forget to fix the build

2022-10-18 06:56 UTC, Shellyber commented on Packs/Gmail/ReleaseNotes/1_2_0.md
> +- Fixed an issue with ***search all mailboxes***, which printed mailboxes without any results for the query.
```suggestion
- Fixed an issue with ***search all mailboxes*** command, which printed mailboxes without any results for the query.
```

2022-10-18 06:56 UTC, Shellyber commented on Packs/Gmail/Integrations/Gmail/Gmail_test.py
> +title_sent_mail_to_entry = 'Email sent:'
Use this directly in the parametrize section (below)
No need to declare it here and then use it
Same goes for all

2022-10-18 06:56 UTC, Shellyber commented on Packs/Gmail/Integrations/Gmail/Gmail_test.py
> +mailbox_test_filters_to_entry = '111111111111111111111'
Let's shorten the example here (and in the test_data)

2022-10-19 08:25 UTC, Shellyber commented on Tests/conf.json
> +        "get_original_email_-_gmail_-_test" : "Uses a deprecated playbook called get_original_email_-_gmail",
Need to remove this

2022-10-19 13:12 UTC, Shellyber approved these changes
Great job. See my last comments before merge

2022-10-19 13:12 UTC, Shellyber commented on Packs/Gmail/Integrations/Gmail/Gmail.py
> +        outputs_key_field=['ID']
```suggestion
        outputs_key_field='ID'
```

2022-10-19 13:12 UTC, Shellyber commented on Packs/Gmail/Integrations/Gmail/Gmail.py
> +        outputs_key_field=['ID']
```suggestion
        outputs_key_field='ID'
```

2022-10-19 16:37 UTC, merged