[Microsoft ATP] enhancement - adding query_batch argument to command
demisto/content pull request #21259
Opened 2022-09-15 10:25 UTC by MLainer1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3869)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-09-19 13:17 UTC, dantavori requested changes

2022-09-19 13:17 UTC, dantavori commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
> +            "query": "query #1",	// Mandatory
let's remove the comments here and describe below which field is mandatory or not.

2022-09-19 13:17 UTC, dantavori commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
> +        A JSON array of queries, limited to 10 queries. Must be passed if query argument is empty. Example for input:
```suggestion
        A JSON array of queries, limited to 10 queries. Cannot be provided with the query argument. Example for input:
```

2022-09-19 13:17 UTC, dantavori commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +    outputs = []
```suggestion
    outputs: List[Dict[str, Any]] = []
```

2022-09-19 13:17 UTC, dantavori commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +            outputs = results  # type: ignore
```suggestion
            outputs = results
```

2022-09-19 13:17 UTC, dantavori commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
> +      description: If stated along with query, then the response should be saved in context under the Result.name path.
let's think how to rephrase this so the user will understand how it's stored

2022-09-21 08:24 UTC, MLainer1 commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +            outputs = results  # type: ignore
Doesn’t really work

2022-09-28 18:19 UTC, ShirleyDenkberg commented
@dantavori Doc review completed.

2022-09-29 09:59 UTC, dantavori approved these changes

2022-09-29 10:13 UTC, merged