Cofense Vision 100 release
demisto/content pull request #21551
Opened 2022-09-29 10:33 UTC by crestdatasystems

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-10-18 14:40 UTC, idovandijk requested changes
Thank you for waiting for my review. While Dor is reviewing your code, I reviewed your playbooks.
Excellent job! I'm really happy to have another contribution for an email security product.
Let me add my comments below:

### Message Quarantine - Cofense Vision
Very good job with the inputs and the thoroughly explained descriptions, this allows more customizability for the end user.
1. Please also add outputs for the playbook to make it possible for other playbooks using it as a subplaybook to know what search results were found.
2. I assume that the search does not complete instantaneously. If so, the `cofense-message-search-results-get` command might give incomplete results. Correct? If not familiar with your code, but if I'm correct then you should make sure your code implements **polling.** If you haven't already implemented polling, you can ask @dorschw for assistance with that as he is reviewing your code. He will gladly help.
3. What if the search yields no results? Then the `Set` command would fail. I see that you've overcome that by using a fallback for an empty string. We have a script exactly for that case - please use `SetAndHandleEmpty` which would not fail if no value is empty.
4. Suggestion (up to you to decide if you want to implement it): allow getting message content and quarantining the message to be automatic through a playbook input.
5. Suggestion: I noticed that some of the command arguments require comma-separated lists. It would be wise to support list inputs as well.

### Add IOCs - Cofense Vision
Nice.

Also are you sure you need both scripts? Why is there a dict of lists in the response from Cofense?
Kindly go over my comments and make fixes where needed or let me know if there's any question or concern.

Finally could we schedule a short demo? Dor may want to see outputs from the integration commands and I would like to see incidents showing the playbook execution. After the fixes of course.
Thanks again for your time and effort with this PR.

2022-10-24 09:36 UTC, idovandijk commented
@crestdatasystems what time-zone are you in?

2022-10-25 05:30 UTC, crestdatasystems commented
> e are you in? >> we are in Indian Time Zone (IST)

2022-10-25 12:33 UTC, crestdatasystems commented
> @crestdatasystems what time-zone are you in?

We are in Indian Standard Time Zone (IST) UTC+5.30 , You can schedule the demo on Thursday/Friday or Monday, as Dor has asked to change a few things.

2022-10-30 12:13 UTC, idovandijk commented
> > @crestdatasystems what time-zone are you in?
> 
> We are in Indian Standard Time Zone (IST) UTC+5.30 , You can schedule the demo on Thursday/Friday or Monday, as Dor has asked to change a few things.

I've sent a Zoom invite via email for tomorrow (Monday). Please let me know if that time works for you. Thank you.

2022-11-02 08:15 UTC, dorschw commented on Packs/CofenseVision/Integrations/CofenseVision/CofenseVision.py
> +        if property_name[0].lower() + property_name[1:] not in SUPPORTED_SORT[command]:
```suggestion
        if (property_name[0].lower() + property_name[1:]) not in SUPPORTED_SORT[command]:
```

2022-11-02 09:32 UTC, dorschw approved these changes

2022-11-02 09:41 UTC, merged