Added padding to encoded string
demisto/content pull request #21559
Opened 2022-09-29 18:23 UTC by anas-yousef

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3916)

## Description
To add padding when decoding a Base64 encoded string.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-10-03 08:44 UTC, DeanArbel commented on Packs/CommonScripts/Scripts/Base64Decode/Base64Decode.py
> +    return f'{value}{"="*((MULTIPLIER - value_length % MULTIPLIER) % MULTIPLIER)}'
Please wrap the % operation with ()

2022-10-06 06:15 UTC, DeanArbel approved these changes

2022-10-12 12:39 UTC, JasBeilin requested changes

2022-10-12 12:39 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/Base64Decode/Base64Decode.py
>      return res, outputs
Please use commandResult with outputs and human readable according to need.

2022-10-13 06:40 UTC, JasBeilin approved these changes
Great job!

2022-10-13 07:29 UTC, merged