Agent configurations
demisto/content pull request #21552
Opened 2022-09-29 11:51 UTC by guytamir10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-10-02 09:02 UTC, yaakovi commented on Packs/MicrosoftADFS/AgentConfigs/MicrosoftADFS/MicrosoftADFS.yml
> +  processors:
```suggestion
    processors:
```

2022-10-02 09:24 UTC, guytamir10 commented on Packs/MicrosoftADFS/AgentConfigs/MicrosoftADFS/MicrosoftADFS.yml
> +  processors:
thanks

2022-10-02 10:17 UTC, evisochek commented on Packs/MicrosoftWSUS/AgentConfigs/MicrosoftWSUS/MicrosoftWSUS.yml
> +  module: iis
Do WSUS need to use IIS module?

2022-10-02 10:25 UTC, evisochek requested changes

2022-10-02 10:25 UTC, evisochek commented on Packs/MicrosoftWSUS/AgentConfigs/MicrosoftWSUS/MicrosoftWSUS.yml
> +  module: iis
```
filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - C:\Program Files\Update Services\LogFiles\Change.log
    - C:\Program Files\Update Services\LogFiles\SoftwareDistribution.log
  processors:
    - add_fields:
        fields:
          vendor: msft
          product: WSUS
```

2022-10-02 11:06 UTC, limorf commented on Packs/Tableau/AgentConfigs/Tableau/Tableau.yml
> +    enabled: true
invalid yaml

2022-10-30 15:43 UTC, bziser approved these changes

2022-10-31 06:42 UTC, evisochek approved these changes

2022-10-31 13:05 UTC, merged