ReversingLabs TitaniumCloud 2.0.4
demisto/content pull request #21651
Opened 2022-10-10 21:03 UTC by MislavReversingLabs

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Minor changes.
Simply implemented the existing User-Agent string into the objects of the ReversingLabsTitatinumCloudv2.py script.
The rest of the changes are just version bumps so the in-code version strings match the versions displayed in the pack_metadata.json files.
Code-wise everything stays the same.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-10-13 07:19 UTC, dorschw commented
Hi @MislavReversingLabs, thank you for the contribution!

Reviewing this PR will be slightly delayed as we are in the midst of the local holiday season. We'll have a look as soon as we're back at work.

2022-10-21 15:57 UTC, MislavReversingLabs commented
@dorschw Hi. When can we expect this PR to be reviewed? Thanks!

2022-10-23 12:20 UTC, dorschw requested changes
Nice job, please accept the suggested changes into the release notes, and we'll be ready to merge.

2022-10-23 12:20 UTC, dorschw commented on Packs/ReversingLabs_A1000/ReleaseNotes/2_0_6.md
> +- Just updated the in-code version string to 2.0.6
```suggestion
- Just updated the in-code version string to 2.0.6
- Updated Docker image to demisto/reversinglabs-sdk-py3:2.0.0.34140.
```

2022-10-23 12:20 UTC, dorschw commented on Packs/ReversingLabs_TitaniumScale/ReleaseNotes/1_0_2.md
> +- Just updated the in-code version string to 1.0.2
```suggestion
- Just updated the in-code version string to 1.0.2 
- Updated Docker image to demisto/reversinglabs-sdk-py3:2.0.0.34140.
```

2022-10-23 12:20 UTC, dorschw commented on Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_0_4.md
> +- Implemented the use of the ReversingLabs User-Agent string.
```suggestion
- Implemented the use of the ReversingLabs User-Agent string.
- Updated Docker image to demisto/reversinglabs-sdk-py3:2.0.0.34140.
```

2022-10-24 16:20 UTC, MislavReversingLabs commented
@dorschw why is the build failing now after I accepted your release notes changes?

2022-10-25 11:44 UTC, dorschw commented
Seems like an internal CI issue, we're looking into it, sorry for the inconvenience.

2022-10-25 12:17 UTC, dorschw commented
Please pull from `demisto/master` into this branch

2022-10-26 10:56 UTC, MislavReversingLabs commented
@dorschw can you check the PR now and approve it?

2022-10-26 11:02 UTC, dorschw approved these changes

2022-10-26 11:02 UTC, merged