Add new command for querying API KEY quota usage
demisto/content pull request #21652
Opened 2022-10-11 06:14 UTC by Bala-SecneurX

* Add new command to get API KEY quota usage details

Signed-off-by: Bala Manoharan <bala@secneurx.com>

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [x] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x ] No

## Must have
- [x] Tests
- [x ] Documentation

2022-10-13 07:19 UTC, dorschw commented
Hi @Bala-SecneurX, thank you for the contribution!

Reviewing this PR will be slightly delayed as we are in the midst of the local holiday season. We'll have a look as soon as we're back at work.

2022-10-19 07:42 UTC, esharf requested changes
Good job.
please add the new command to the `command_examples` file

2022-10-19 17:31 UTC, Bala-SecneurX commented on Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.py
> +                demisto.results(fileContent)
@esharf We wanted to give the option to download the complete report JSON file to the user.

2022-10-20 02:48 UTC, Bala-SecneurX commented on Packs/SecneurXAnalysis/ReleaseNotes/1_0_1.md
> +- Adding new command for API key quota usage details.
Agreed.

2022-10-20 09:43 UTC, esharf commented on Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.py
> +                demisto.results(fileContent)
So please use `return_results` instead of `demisto.results`.

2022-10-20 09:46 UTC, Bala-SecneurX commented
Thanks will update

Regards,
Bala
________________________________
From: eli sharf ***@***.***>
Sent: Thursday, October 20, 2022 3:13:36 PM
To: demisto/content ***@***.***>
Cc: Bala-SecneurX ***@***.***>; Mention ***@***.***>
Subject: Re: [demisto/content] Add new command for querying API KEY quota usage (PR #21652)


@esharf commented on this pull request.

________________________________

In Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.py<https://github.com/demisto/content/pull/21652#discussion_r1000401678>:

> +                reportFileName = taskUuid + reportExtn
+                fileContent = fileResult(reportFileName, response)
+                demisto.results(fileContent)


So please use return_results instead of demisto.results.

—
Reply to this email directly, view it on GitHub<https://github.com/demisto/content/pull/21652#discussion_r1000401678>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZOOSHUQNOHMMB73MIYDQYLWEEH4RANCNFSM6AAAAAARB55SEU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-29 11:00 UTC, Bala-SecneurX commented
@esharf I have updated all the review comments. Sorry for the delay had some issues with our cortex licensing.
Pls review the changes and provide your feedback.

2022-11-10 12:35 UTC, Bala-SecneurX commented
@esharf Could you please review this PR

2022-11-21 19:37 UTC, esharf approved these changes

2022-11-21 19:38 UTC, merged