Deprecate old gitlab
demisto/content pull request #21695
Opened 2022-10-12 15:30 UTC by maimorag

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [X] Ready

## Related Issues
fixes: link to the issue

## Description
deprecate GitLab integration. 

## Does it break backward compatibility?
   - [X] No

2022-10-12 15:50 UTC, Shellyber reviewed
Looks good.
Let's change the pack version to 1.1.1 (and the release notes file name to match)

2022-10-20 11:43 UTC, Shellyber requested changes

2022-10-20 11:43 UTC, Shellyber commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +  version: 1.1.1
revert this

2022-10-20 11:43 UTC, Shellyber commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +description: Deprecated. Use GitLab Pack instead.
```suggestion
description: Deprecated. Use GitLab v2 in GitLab Pack instead.
```

2022-10-20 11:43 UTC, Shellyber commented on Packs/GitLab/Integrations/GitLab/1_d0445cb2-f325-4894-83e1-93ac42293504
> +I am a file.
Remove this

2022-10-20 11:44 UTC, Shellyber commented
Also don't forget to change the pack version (in the pack_metadata file) and the release notes file name accordingly

2022-10-23 14:19 UTC, maimorag commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +  version: 1.1.1
done

2022-10-23 14:23 UTC, maimorag commented on Packs/GitLab/Integrations/GitLab/1_d0445cb2-f325-4894-83e1-93ac42293504
> +I am a file.
ok

2022-10-23 14:36 UTC, maimorag commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +  version: 1.1.1
ok ok

2022-10-23 14:36 UTC, maimorag commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +description: Deprecated. Use GitLab Pack instead.
done

2022-11-03 13:24 UTC, Shellyber reviewed
Good.
This PR will be merged only after the GitLab v2 is merged,

2022-11-03 13:24 UTC, Shellyber commented on Packs/DevSecOps/ReleaseNotes/1_1_1.md
> +- Deprecated. Use GitLab v2 Pack instead.
```suggestion
- Deprecated. Use GitLab v2 in GitLab Pack instead.
```

2022-11-03 13:24 UTC, Shellyber commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +description: Deprecated. Use GitLab v2 Pack instead.
```suggestion
description: Deprecated. Use GitLab v2 in GitLab Pack instead.
```

2022-11-03 17:20 UTC, maimorag commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +description: Deprecated. Use GitLab v2 Pack instead.
done

2022-11-03 17:20 UTC, maimorag commented on Packs/DevSecOps/ReleaseNotes/1_1_1.md
> +- Deprecated. Use GitLab v2 Pack instead.
done

2022-11-09 15:48 UTC, Shellyber approved these changes

2022-11-10 12:27 UTC, merged