Add get-device-login-history command to CS Falcon integration
demisto/content pull request #21732
Opened 2022-10-15 22:23 UTC by ali-sawyer

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Add new command to the CrowdStrike Falcon integration – `cs-falcon-get-device-login-history` – to get recent user login history for a given device.

## Screenshots
![Screen Shot 2022-10-15 at 4 22 39 PM](https://user-images.githubusercontent.com/91506078/196009785-f355abbb-feec-4322-b905-a27b2488ca96.png)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-11-07 18:50 UTC, esharf requested changes

2022-11-07 18:50 UTC, esharf commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    resources = response.get('resources')
```suggestion
    resources = response.get('resources', [])
```

2022-11-07 18:50 UTC, esharf commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +        for login in resource.get('recent_logins'):
```suggestion
        for login in resource.get('recent_logins', []):
```

2022-11-07 18:50 UTC, esharf commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
> +display: CrowdstrikeFalcon
```suggestion
display: Crowdstrike Falcon
```

2022-11-07 18:50 UTC, esharf commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
> +```!cs-falcon-get-detections-for-incident incident_id=`inc:0bde2c4645294245aca522971ccc44c4:1a1eb17d1f9e4d82a9e8ba73d1095593```
nice catch

2022-11-07 18:50 UTC, esharf commented on Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
> +        simple: c1a4575cd124419db5ed3c1e8ddc2c04
you should add some method to get this id from the integration (so this playbook will work in every environment, not just in yours).

2022-11-28 12:05 UTC, esharf commented
@ali-sawyer did you managed to get any progress here? (if you need any help I’m available in [DFIR](https://dfircommunity.slack.com/team/UQWL4FQJ0))

2022-12-04 12:52 UTC, esharf approved these changes
will handle the comments here internally

2022-12-04 12:52 UTC, merged

2022-12-05 07:27 UTC, esharf commented
@ali-sawyer i still need you to complete the [form](https://forms.gle/XDfxU4E61ZwEESSMA) please LMK once you are done with that.

2022-12-05 15:53 UTC, ali-sawyer commented
@esharf done. I have been very busy with client work over the past couple months, so thank you very much for taking care of the changes and getting this merged!