Fix release notes in marketplace
demisto/content pull request #21741
Opened 2022-10-18 09:01 UTC by yaakovpraisler

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Fix release notes in marketplace.

2022-10-23 07:42 UTC, yaakovpraisler commented
Failed test: https://app.circleci.com/pipelines/github/demisto/content/199509/workflows/087536ae-6c8f-4d55-8fa5-fae495eac9a3/jobs/584554

2022-10-23 10:56 UTC, yaakovpraisler commented
Successful upload: https://code.pan.run/xsoar/content/-/pipelines/3900378

2022-10-25 09:33 UTC, dantavori requested changes
looks good to me, @Noy-Maimon can you please go over this too?

2022-10-25 09:33 UTC, dantavori commented on Tests/Marketplace/marketplace_services.py
> +            for display_name, rn_entry in release_notes[rn_header].items():
```suggestion
            for content_item_display_name, content_item_rn_notes in content_type_rn_entries.items():
```

2022-10-25 09:33 UTC, dantavori commented on Tests/Marketplace/marketplace_services.py
> +                if display_name != '[special_msg]' and not get_id_set_entity_by_display_name(
```suggestion
                if display_name != '[special_msg]' and not is_content_item_in_id_set(
```

2022-10-25 09:33 UTC, dantavori commented on Packs/CommonTypes/ReleaseNotes/3_3_22.md
> +- **Key Value**
did we make the changes on these RN files on purpose?

2022-10-30 10:52 UTC, yaakovpraisler commented on Tests/Marketplace/marketplace_services.py
> -                modified_files_data,
done

2022-10-30 10:52 UTC, yaakovpraisler commented on Tests/Marketplace/marketplace_services.py
> +        for rn_header in release_notes:
Done all comments

2022-10-30 16:10 UTC, yaakovpraisler commented
Successafull upload where release notes are generated correctly on XSOAR and on marketplacev2.
https://code.pan.run/xsoar/content/-/pipelines/3941518

2022-10-31 08:14 UTC, dantavori approved these changes

2022-11-03 12:52 UTC, merged