Teams docs
demisto/content pull request #21793
Opened 2022-10-19 13:35 UTC by merit-maita

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-10-31 12:13 UTC, tkatzir requested changes
Good. Need to remove debug code, and have the Tech Writers check the English text.

2022-10-31 12:13 UTC, tkatzir commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
> +    # demisto.debug(f"integration context is: {integration_context}")
Needed?

2022-10-31 12:13 UTC, tkatzir commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
> +    # demisto.debug(f"open_id_metadata from integration context is: {open_id_metadata}")
Needed?

2022-10-31 12:13 UTC, tkatzir commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
> +    # demisto.debug(f"unverified headers are: {unverified_headers}")
Needed?

2022-10-31 12:13 UTC, tkatzir commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
> +    # demisto.debug(f"now key object is: {key_object}")
Needed?

2022-10-31 12:13 UTC, tkatzir commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
> +    # demisto.debug(f"keys are: {keys}")
Needed?

2022-10-31 12:13 UTC, tkatzir commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
> +    # demisto.debug(f"first key_object is: {key_object}")
Needed?

2022-10-31 12:13 UTC, tkatzir commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
> +#### Creating the Demisto Bot for Production environment using Microsoft Azure Portal
Needs to be reviewed by Tech Writers

2022-11-03 08:41 UTC, ShirleyDenkberg commented
@tkatzir Doc review completed.

2022-11-03 11:01 UTC, tkatzir approved these changes
Great!

2022-11-03 12:12 UTC, merged