Changed inputs of the playbook and the inputs of "Block File - Generi…
demisto/content pull request #21827
Opened 2022-10-23 11:33 UTC by TalNos

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-2781

## Description
Fixed the inputs of the playbook and "Block File - Generic v2" sub-playbook so only malicious hashes will be blocked by default.  

## Screenshots
![Block_Indicators_-_Generic_v2](https://user-images.githubusercontent.com/112805149/197389752-7f117314-adaa-4040-b6ea-a2ce8acd93cf.png)

2022-10-23 14:28 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v2.yml
> -toversion: 5.4.9
The `toversion` should stay the same. Congratulations on finding a new SDK bug!
Please open a Jira ticket about this. If a playbook that already exists in content has a `toversion`, the SDK should keep it.

2022-10-23 14:29 UTC, idovandijk commented on Packs/CommonPlaybooks/ReleaseNotes/2_3_7.md
> +##### Block Indicators - Generic v2
Add the v3 playbook as well

2022-10-23 14:29 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v2_README.md
> +![Block Indicators - Generic v2](../doc_files/Block_Indicators_-_Generic_v2.png)
nice job

2022-10-23 14:31 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v2_README.md
> -This playbook blocks malicious indicators through all integrations that are enabled, using the following sub-playbooks:
Good job updating this, let's also add the README of the v3

2022-10-23 14:33 UTC, idovandijk requested changes
Excellent job Tal!
Please see my comments. Also, because this playbook is a very popular one, and changes are very sensitive, let's use the opportunity to update the test playbook.
You can take the test playbook YML from the CommonPlaybooks pack under the TestPlaybooks folder. Upload it to your server and create an incident with malicious MD5 / SHA256, then run the playbook on that incident, and then verify that the the malicious hashes are passed to the playbook inputs to be blocked.

2022-10-25 11:29 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml
>      simple: Demisto Remediation - Malicious URLs
`Block URL - Generic v2` is using "XSOAR Remediation - Malicious URLs". Please change the input for `Block Indicators - Generic v3` to be "XSOAR Remediation - Malicious URLs" and then in `Block URL - Generic v2` use the input. This way we fix it to use the input while preserving backward compatibility

2022-10-25 11:31 UTC, idovandijk requested changes
small change

2022-10-25 12:02 UTC, idovandijk approved these changes
Looks good, well done

2022-11-02 11:26 UTC, ShirleyDenkberg commented
@idovandijk Doc review (RN only) completed.

2022-11-02 14:05 UTC, merged