ParseWordDoc - read Urls
demisto/content pull request #21907
Opened 2022-10-27 14:31 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-12-04 13:50 UTC, DeanArbel requested changes
Looks good, but please expand the tests.

2022-12-04 13:50 UTC, DeanArbel commented on Packs/CommonScripts/ReleaseNotes/1_10_17.md
> +- The script is now extracting urls from the document.
```suggestion
- The script is now extracting URLs from the document.
```

2022-12-04 13:50 UTC, DeanArbel commented on Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc_test.py
> +def test_extract_urls_xml():
Please add a test where no URLs are available.
Please also test extract_urls_docx.

2022-12-05 14:59 UTC, adi88d commented on Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc_test.py
> +def test_extract_urls_xml():
done

2022-12-06 18:02 UTC, merged