Cicd playbook bitbucket
demisto/content pull request #22069
Opened 2022-11-06 15:40 UTC by RotemAmit

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2223)

## Description
Adding the Bitbucket integration to the CI/CD playbook 

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-11-10 10:51 UTC, Shellyber requested changes
Please Run Format on the playbooks, there are a lot of fields that need to be fixed.

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Generic_README.md
> +* Bitbucket
Let's add here GitHub as well

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/Playbooks/playbook-Pull_Request_Creation_-_Generic_README.md
> +| GitIntegration | Which version control integration to use. | bitbucket | Required |
Let's keep the default GitHub

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/ReleaseNotes/1_1_5.md
> +##### New: CommitFilesBitbucket
This script should be different than Github? 
Is there different functionality?

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/ReleaseNotes/1_1_5.md
> +- Updated the script SuggestBranchName to be generic.
```suggestion
- Updated the script SuggestBranchName to support both GitHub and BitBucket.
```

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/Scripts/SuggestBranchName/SuggestBranchName.py
> +        command_get_branch = demisto.getArg('command_get_branch')
```suggestion
        command_get_branch = demisto.getArg('use_command')
```

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/Scripts/SuggestBranchName/SuggestBranchName.yml
> +  name: command_get_branch
```suggestion
  name: use_command
```

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/Scripts/SuggestBranchName/SuggestBranchName.yml
> +  description: The name of the pack.
Fix the description for the argument

2022-11-10 10:51 UTC, Shellyber commented on Packs/ContentManagement/Scripts/SuggestBranchName/README.md
> +| command_get_branch | The name of the pack. |
Fix this according to YML

2022-11-14 12:46 UTC, Shellyber reviewed
Nice Job!

2022-11-14 12:46 UTC, Shellyber commented on Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.py
> +    else:
Let's just add a comment that the else is for BitBucket

2022-11-14 12:46 UTC, Shellyber commented on Packs/ContentManagement/Scripts/CommitFiles/README.md
> +* Pull Request Creation - Github
This is used also in BitBucket, let's update as well

2022-11-14 12:46 UTC, Shellyber commented on Packs/ContentManagement/Scripts/SuggestBranchName/README.md
> +| use_command | Which command to use. |
Let's add to the description the command we support, for readability

2022-11-14 13:20 UTC, RotemAmit commented on Packs/ContentManagement/Scripts/SuggestBranchName/SuggestBranchName.yml
> +  - GitHub-get-branch
yes

2022-11-15 10:12 UTC, Shellyber approved these changes
Nice job.
Just fix my last comment

2022-11-15 10:12 UTC, Shellyber commented on Packs/ContentManagement/ReleaseNotes/1_1_5.md
> +- Updated the script SuggestBranchName to be generic.
remove this.

2022-11-20 12:50 UTC, RotemAmit commented
The test coverage right now is 34.11%, but @maimorag will add more tests to the Gitlub part on the script CommitFiles.py.
 The docker image tag is not the latest numeric tag because it is not working with the latest tag, I opened an issue about that https://jira-hq.paloaltonetworks.local/browse/CIAC-4633 .

2022-12-04 10:19 UTC, Shellyber approved these changes

2022-12-05 10:36 UTC, merged