Jira query add description
demisto/content pull request #22089
Opened 2022-11-07 14:02 UTC by thefrieddan1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-2149

## Description
Add field description to output of the command jira-issue-query. in order to support the JIRA-AHA mirror
## Screenshots
Paste here any images that will help the reviewer

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-11-07 14:11 UTC, JasBeilin reviewed
Looks good, make sure to add release notes.

2022-11-07 14:11 UTC, JasBeilin commented on Packs/Jira/Integrations/JiraV2/JiraV2.yml
> +      description: The ticket project description.
```suggestion
      description: The ticket description.
```

2022-11-08 16:00 UTC, tkatzir commented on Packs/Jira/ReleaseNotes/2_0_17.md
> +- Added a field description to command jira-issue-query output.
```suggestion
- Added the field **description** to command **jira-issue-query output**.
```

2022-11-08 16:24 UTC, JasBeilin requested changes

2022-11-08 16:24 UTC, JasBeilin commented on Packs/Jira/Integrations/JiraV2/JiraV2.py
> +requests.packages.urllib3.disable_warnings()   # type: ignore[attr-defined]
change to urllib3

2022-11-08 17:19 UTC, thefrieddan1 commented on Packs/Jira/ReleaseNotes/2_0_17.md
> +- Added a field description to command jira-issue-query output.
done.

2022-11-08 17:19 UTC, thefrieddan1 commented on Packs/Jira/Integrations/JiraV2/JiraV2.py
> +requests.packages.urllib3.disable_warnings()   # type: ignore[attr-defined]
done.

2022-11-08 17:21 UTC, ShahafBenYakir commented on Packs/Jira/ReleaseNotes/2_0_17.md
> +- Added the field **description** to the **jira-issue-query** command output.
```suggestion
- Added the field **description** to the ***jira-issue-query*** command output.
```

2022-11-08 17:21 UTC, ShahafBenYakir approved these changes

2022-11-08 17:26 UTC, JasBeilin approved these changes

2022-11-08 18:56 UTC, merged