Add crowdstrike lookback option
demisto/content pull request #22148
Opened 2022-11-10 11:50 UTC by ilaner

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4511?filter=-1&jql=assignee%20%3D%20currentUser()%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20summary%20ASC%2C%20updated%20DESC)

## Description
Add lookback otption to crowdstrike fetch incidents
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-11-15 13:11 UTC, ilaner commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    last_run = demisto.getLastRun()
add handle_last_run to check conditions for migration

2022-11-15 13:12 UTC, ilaner commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    demisto.debug("CrowdstrikeFalconMsg: Starting fetch incidents")
add configuration to fetch

2022-11-15 13:13 UTC, ilaner commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    demisto.debug("CrowdstrikeFalconMsg: Starting fetch incidents")
print lastrun in debug

2022-11-16 07:41 UTC, yuvalbenshalom requested changes
looks good. see my comments and please implement the changes in your comments.

2022-11-16 07:41 UTC, yuvalbenshalom commented on Packs/Base/ReleaseNotes/1_31_33.md
> +
remove the file changes.

2022-11-16 07:41 UTC, yuvalbenshalom commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +import pytz
remove the file changes

2022-11-16 07:41 UTC, yuvalbenshalom commented on Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_10.md
> +- This version requires **Base** pack version `1.31.33`
```suggestion
```

2022-11-17 13:14 UTC, yuvalbenshalom approved these changes

2022-11-20 12:42 UTC, merged