[AWS Guard Duty] Rewrite
demisto/content pull request #22284
Opened 2022-11-16 10:23 UTC by michal-dagan

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-1616)

## Description
redesign the fetch to use last_fetch
complement the fetch with classifier, mapper, layouts.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation

2022-11-22 10:54 UTC, bziser requested changes
Looks good :) 
Adding you some comments

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
>  def create_detector(client: boto3.client, args: dict):
Please add return type to the function declaration

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +def get_pagination_args(args: dict):
Return type :)

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +    page = arg_to_number(args['page']) if args.get('page') else None
```suggestion
    page = arg_to_number(args.get('page'))
```
if `arg_to_number` gets None it will return None

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +        raise Exception('page argument must be greater than 0')
```suggestion
        raise DemistoException('page argument must be greater than 0')
```

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +    page_size = arg_to_number(args['page_size']) if args.get('page_size') else MAX_RESULTS_RESPONSE
```suggestion
    page_size = arg_to_number(args.get('page_size',MAX_RESULTS_RESPONSE))
```

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +        raise Exception(f'page_size argument must be between 1 to {MAX_RESULTS_RESPONSE}')
```suggestion
        raise DemistoException(f'page_size argument must be between 1 to {MAX_RESULTS_RESPONSE}')
```

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +def parse_finding(finding: dict):
Please add return type and a short docstring about what the function does as you did in `get_pagination_args`

2022-11-22 10:54 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +def severity_mapping(severity: Optional[int]):
If we are getting `severity = None` we want to return `demisto_severity = None`?

2022-11-22 15:57 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +def time_to_unix_epoch(date_time: datetime):
Add return type

2022-11-22 15:57 UTC, bziser commented on Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py
> +                                                  first_fetch_time=first_fetch_time, is_archive=is_archive)
```suggestion
            next_run, incidents = fetch_incidents(client=client, aws_gd_severity=aws_gd_severity, last_run=demisto.getLastRun(),
                                                  fetch_limit=fetch_limit,  # type: ignore
                                                  first_fetch_time=first_fetch_time, is_archive=is_archive)
```

2022-11-22 15:57 UTC, bziser commented on Packs/AWS-GuardDuty/ReleaseNotes/1_3_4.md
> +- Added the following arguments to the ***aws-gd-list-findings***, ***aws-gd-list-detectors***, ***aws-gd-list-threatintel-sets***, ***aws-gd-list-ip-sets*** commands.
```suggestion
- Added the following arguments to the ***aws-gd-list-findings***, ***aws-gd-list-detectors***, ***aws-gd-list-threatintel-sets***, ***aws-gd-list-ip-sets*** commands:
```

2022-11-22 15:57 UTC, bziser commented on Packs/AWS-GuardDuty/ReleaseNotes/1_3_4.md
> +- Added the following arguments to the ***aws-gd-create-detector***, ***aws-gd-update-detector*** commands.
```suggestion
- Added the following arguments to the ***aws-gd-create-detector***, ***aws-gd-update-detector*** commands:
```

2022-11-23 12:48 UTC, ShirleyDenkberg commented
@bziser Doc review completed.

2022-11-23 13:37 UTC, bziser approved these changes

2022-11-24 05:49 UTC, merged