qualysV2 enhancement
demisto/content pull request #22415
Opened 2022-11-22 08:17 UTC by samuelFain

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3616

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-11-30 12:41 UTC, JasBeilin requested changes
Great Job :)

2022-11-30 12:41 UTC, JasBeilin commented on Packs/qualys/Integrations/Qualysv2/README.md
>  #### Context Output
Make sure to add readme updates for the updated (not new) commands

2022-12-13 12:00 UTC, ShirleyDenkberg commented
@samuelFain Please regenerate the Readme file.

@JasBeilin Doc review completed.

2022-12-14 07:42 UTC, JasBeilin approved these changes

2022-12-14 07:42 UTC, merged