Armorblox enhancement for more commands
demisto/content pull request #22456
Opened 2022-11-24 05:58 UTC by SamhithaTatipalli

2022-11-24 10:18 UTC, SamhithaTatipalli commented
Hi @ostolero,

This PR is about code enhancement of existing pack Armorblox. We have added methods to support fetching an incident by its id, incident analysis, senders, actions, mail body and policies, update the Docker image and expose them as commands. 

Regards,
Samhitha.

2022-11-24 10:27 UTC, ostolero commented
Hi @SamhithaTatipalli , thank you for the contribution, and great to see that your build is already green!
I have some other contributions to handle, so I might delay a bit more with this review.
I'll be sure to update here as soon as I'm done.
Thanks again!

2022-11-24 10:30 UTC, SamhithaTatipalli commented
Sure, thanks @ostolero!

2022-11-27 15:49 UTC, ostolero requested changes
Hi @SamhithaTatipalli , the code looks great! the main things to fix are related to xsoar requirements more then code logic.
Note these changes-
1. All the commends are missing context info (both in yml and in the code) added comment it the python file with more info.
2. When you add the context info please update the readme again with the sdk method [generate-docs](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/generate_docs/README.md) using a `command_exmaple` file to generate outputs.
3. Please add rn to describe your changes, this can be done with our [update-rn](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/update_release_notes/README.md) sdk command.
I'm here for any questions\clarifications or if you need help with any of the comments.
Thanks!

2022-11-27 15:50 UTC, ostolero commented on Packs/Armorblox/Integrations/Armorblox/Armorblox.py
>      return incidents
The `fetch_incidents` code looks way better! the reason for these changes is the client method that allowed to simplify this method?
I don't see you consider the `max_fetch` parameter, return only `max_fetch` results to load balance the system.

2022-12-25 08:54 UTC, ostolero commented
Hi @SamhithaTatipalli , this pr has been quiet for a while, as I understand you are waiting for the client to proceed.
I'm closing this for now but open it when you get back to it and we can proceed. tnx!

2022-12-25 08:54 UTC, closed without merging