Neosec Pack
demisto/content pull request #22561
Opened 2022-11-29 10:51 UTC by gala-neosec

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-11-29 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=22561) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=22561) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: arsenyk-neosec<br/>:x: gala-neosec<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=22561) it.</sub>

2022-12-04 09:58 UTC, ostolero requested changes
Hi , everything looks really good! see my few changes.
I'm adding one of our security team member to go over the incident field, type, classifier and layout.
If you have any questions feel free to contact me here or through slack. tnx!

2022-12-04 09:58 UTC, ostolero commented on Packs/Neosec/Integrations/Neosec/Neosec.py
> +
return a proper response to the user to indicate if the action was successful. something like -
```
    res = client.patch_alert(alert_id, alert_status)
    if res.status == 200:
        return_results("Alert {alert_id} updated successfully")
    else:
        return_error(f"Error updating alert {alert_id} - {res.content}")
```

2022-12-04 09:58 UTC, ostolero commented on Packs/Neosec/pack_metadata.json
> +    "support": "community",
I see you registered as a partner, change this to 
`"support": "partner",`

2022-12-13 14:20 UTC, efelmandar commented
@gala-neosec Hi and thank you for your contribution, I've finished reviewing the pack's content and would like if we could schedule a demo to demonstrate the use of the integration and content, please let us know your available time slots? @ostolero FYI

2022-12-22 14:47 UTC, ostolero requested changes
Hi @gala-neosec , Thank you for a great demo! learned a lot about your product and the integration seems to work perfectly.
Regarding the few points raised in the demo-
1. See my two comments in the yml file regarding mandatory params and multi value argument.
2.After looking into it, `proxy` and `insecure` support are a recommendation not a requirement, you can see an example in HelloWorld integration if you want to add them.
3. Add the extra fields to the mapper as we discussed @efelmandar will look an example of a grid mapper.
Thank you, let me know if you have any questions :)

2022-12-22 14:47 UTC, ostolero commented on Packs/Neosec/Integrations/Neosec/Neosec.yml
> +  additionalinfo: ""
Add the `required: true` field to both

2022-12-22 14:47 UTC, ostolero commented on Packs/Neosec/Integrations/Neosec/Neosec.yml
> +      - Closed
I see you had the intention to have this as a predefined argument, I think adding this field will fix the issue and show the options in XSOAR
`auto: PREDEFINED`

2022-12-25 13:51 UTC, arsenyk-neosec commented
> 

@efelmandar don't forget to send grid field example

2023-01-02 10:39 UTC, efelmandar commented
@arsenyk-neosec I've sent you an email last week with the documentation and example of how to use grid field, did you get it? 
if you need additional info/help with this please let me know

2023-01-02 14:28 UTC, arsenyk-neosec commented
> @arsenyk-neosec I've sent you an email last week with the documentation and example of how to use grid field, did you get it? if you need additional info/help with this please let me know

Thanks for the example. @gala-neosec haven't got to it yet. we will reach out when we will finish the fixes

2023-01-08 17:22 UTC, ostolero approved these changes
Hi @gala-neosec , changes look great! will just ask @efelmandar to have a final look and we can merge :)

2023-01-09 10:03 UTC, arsenyk-neosec commented
> @gala-neosec I went over the changes and it looks excellent and we're ready to merge, @ostolero FYI

@ostolero what are the next steps?

2023-01-09 10:07 UTC, merged