Ay google workspace admin
demisto/content pull request #22584
Opened 2022-11-30 10:20 UTC by anas-yousef

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-2026

## Description
The Google Workspace Admin integration gives the user to options to view all mobile and chromeOS devices in the organization, and also perform remote actions on them.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

2022-11-30 16:09 UTC, JasBeilin requested changes
1. Ask for image for the pack.
2. remove pipfile & pipfile.lock
3. add pack readme
4. change unitest according to the new code changes. -> make sure to check helper function seperatly, and make sure the CommandResult testing contains the call arguments and not the content of the commandResult itself wherever you have logic.

2022-11-30 16:09 UTC, JasBeilin commented on Packs/GoogleWorkspaceAdmin/Integrations/GoogleWorkspaceAdmin/GoogleWorkspaceAdmin_test.py
> +    return Client(base_url=BASE_URL, verify=False, proxy=False, customer_id='id', service_account_json={})
```suggestion
    return Client(base_url='https://example.com/', verify=False, proxy=False, customer_id='id', service_account_json={})
```

2022-12-01 08:54 UTC, DanilVil commented on Packs/GoogleWorkspaceAdmin/Integrations/GoogleWorkspaceAdmin/GoogleWorkspaceAdmin.yml
> +            - FULL
If it returns the same then it is a bug. I haven't tested it, @OmriItzhak did you?

2022-12-04 11:20 UTC, anas-yousef commented on Packs/GoogleWorkspaceAdmin/Integrations/GoogleWorkspaceAdmin/GoogleWorkspaceAdmin_description.md
> +5. The necessary privileges: Admin console privileges => Services => Mobile Device Management => Manage Devices and Settings.
It does not work with ChromeOS only privileges, apparently the Mobile Device Management => Manage Devices and Settings privileges is enough for both mobile and ChromeOS devices.

2023-01-02 19:36 UTC, closed without merging