Remove download test json
demisto/content pull request #22603
Opened 2022-11-30 23:23 UTC by gal-forer

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
replace json file for the. secretes
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-12-05 07:05 UTC, esharf submitted a review, later dismissed

2022-12-05 07:05 UTC, esharf commented on Tests/scripts/download_demisto_conf.sh
> +python3 ./Tests/scripts/add_secret_file_to_build.py $SECRET_CONF_PATH
Let’s move it to different step (it shouldn’t be a part of this script anymore)

2022-12-05 09:25 UTC, gal-forer commented on Tests/scripts/utils/GoogleSecretManagerModule.py
> +                    pass
Yes I didn't know how to

2022-12-06 17:50 UTC, tkatzir reviewed
Good progress!
Some comments.

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/add_secret_file_to_build.py
> +    print(f'******************conf file location: {json_path_file}')
Also, remove all the *'s before merging.
```suggestion
    print(f'****************** conf file location: {json_path_file}')
```

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/add_secret_file_to_build.py
> +    print(f'json_path_file: {json_path_file}')
```suggestion
    print(f'{json_path_file=}')
```

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/add_secret_file_to_build.py
> +    parser.add_argument('-pid', '--gsm_project_id', help='The project id for the GSM.')
Maybe rename it to `gpid`? `pid` is a widely used standard for `process id`.

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/add_secret_file_to_build.py
> +    parser.add_argument('-p', '--password', help='Path to file with XSIAM Servers api keys.')
Is `password` the best name for this parameter?...

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/add_secret_file_to_build.py
> +                              "For more information go to: "
```suggestion
                              "For more information see: "
```

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/add_secret_file_to_build.py
> +    print('##################################')
Remove before merging.

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/download_demisto_conf.sh
> +echo "^^^^^^^^^^^^^^^^^^: " $SECRET_CONF_PATH
Make it cleaner before merging.

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/utils/GoogleSecretManagerModule.py
> +            f = open(credentials_file_path, "w")
Change to `with ...`

2022-12-06 17:50 UTC, tkatzir commented on Tests/scripts/utils/GoogleSecretManagerModule.py
> +                os.remove(credentials_file_path)
Good to put it in the `finally` block! :-)

2022-12-11 14:33 UTC, tkatzir reviewed
Good progress!
Some comments.

2022-12-11 14:33 UTC, tkatzir commented on Tests/scripts/add_secret_file_to_build.py
> +                        help=("Path to gcloud service account, is for circleCI usage. "
```suggestion
                        help=("Path to gcloud service account, for circleCI usage. "
```

2022-12-11 14:33 UTC, tkatzir commented on Tests/scripts/utils/GoogleSecretManagerModule.py
> +            print(f'______________________{secret.name}______________________')
```suggestion
            print(f'______________________ {secret.name} ______________________')
```

2022-12-13 07:46 UTC, gal-forer commented on Tests/scripts/utils/GoogleSecretManagerModule.py
> +            logging.error(f'Secret json is malformed for: {secret_id}, got error: {e}')
I've added the version to the log

2022-12-19 16:56 UTC, DeanArbel requested changes

2022-12-19 16:56 UTC, DeanArbel commented on .gitlab/ci/bucket-upload.yml
> +    - echo "b2"
Please remove
```suggestion
```

2022-12-19 16:56 UTC, DeanArbel commented on .gitlab/ci/bucket-upload.yml
> +    - echo "b1"
Please remove
```suggestion
```

2022-12-19 16:56 UTC, DeanArbel commented on .gitlab/ci/global.yml
> +  - echo "global"
Please remove
```suggestion
```

2022-12-19 16:56 UTC, DeanArbel commented on Packs/Bitbucket/Integrations/Bitbucket/Bitbucket.py
> +    return CommandResults(readable_output='The comment was created successfullyTTTTTTTTT',
Please clean this
```suggestion
    return CommandResults(readable_output='The comment was created successfully',
```

2022-12-19 16:56 UTC, DeanArbel commented on Packs/FeedURLhaus/Integrations/FeedURLhaus/FeedURLhaus.py
> +        return_error(f'Failed toKKK execute {demisto.command()} command. Error: {str(e)}')
Please clean
```suggestion
        return_error(f'Failed to execute {demisto.command()} command. Error: {str(e)}')
```

2022-12-19 16:56 UTC, DeanArbel commented on Tests/scripts/add_secrets_file_to_build.py
> +    parser.add_argument('-a', '--ar', help='Test.')
What does this argument do?

2022-12-19 22:05 UTC, gal-forer commented on Tests/scripts/add_secrets_file_to_build.py
> +    parser.add_argument('-a', '--ar', help='Test.')
I removed it

2022-12-19 23:15 UTC, DeanArbel approved these changes
Nicely done

2022-12-26 10:31 UTC, merged