MSDE vulnerability module
demisto/content pull request #22653
Opened 2022-12-04 14:40 UTC by sapirshuker

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3930

## Description
Added 7 new commands.

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

2022-12-05 14:45 UTC, Shellyber requested changes
Nice work!

2022-12-05 14:45 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +def create_filters_conjunction(filters_arg_list: list[str], name: str) -> str:
Add test to this function

2022-12-05 14:45 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +def create_filters_disjunctions(filters_arg_list: list[str]) -> str:
Same here - add test

2022-12-05 14:45 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +def create_filter(args_and_name_list: list[tuple[list[str], str]]) -> str:
add test

2022-12-05 14:45 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +    limit = int(args.get('limit', 50))
use arg_to_number as well

2022-12-05 14:45 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +                query = f"{query}{name} eq '{list_item}' or "
Let's add a debug log to those functions - see what's the query

2022-12-05 14:45 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +    published_on = args.get('published_on', '')
Regarding all the timestamps args - create a helper function that gets the argument and transforms it to ISO format

2022-12-05 15:11 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +        """Retrieve a list of device references that has this software installed.
Fix the description

2022-12-11 09:02 UTC, sapirshuker commented
@esharf XSIAM Server qa failed

> $ section_end "Build Parameters"
[2022-12-11T08:53:31.685] section end
$ [[ "create instances done" = $(cat "$ARTIFACTS_FOLDER/create_instances_done.txt" 2> /dev/null) ]] || (echo "this is a known issue with GitLab pipline please mention @esharf in your PR" && exit 1)
this is a known issue with GitLab pipline please mention @esharf in your PR
Uploading artifacts for failed job
00:01
Uploading artifacts...

https://code.pan.run/xsoar/content/-/jobs/19342329

2022-12-13 10:15 UTC, Shellyber reviewed
Nice work. 
Don't forget to fix the things we talked about in our demo

2022-12-13 10:15 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +def add_backslash_infront_of_underscore_list(markdown_data: Optional[list[dict]]) -> list[dict]:
Why do we have 2 functions that does the same? 
Why not use add_backslash_infront_of_underscore for both?

2022-12-13 10:15 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +        demisto.debug(query)
```suggestion
        demisto.debug(f'Filter conjunction query results: {query} ')
```

2022-12-13 10:15 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +        demisto.debug(query)
```suggestion
        demisto.debug(f'Filter disjunctions query results: {query} ')
```

2022-12-13 10:33 UTC, sapirshuker commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +def add_backslash_infront_of_underscore_list(markdown_data: Optional[list[dict]]) -> list[dict]:
deleted one

2022-12-14 09:20 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +        demisto.debug(vulnerabilities_response_value)
Please remove these debug logs - they are not necessary

2022-12-14 09:20 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
>      demisto.debug(vulnerabilities_response_value)
demisto.debug(f'Vulnerabilities Response {vulnerabilities_response_value}, with length of {len(vulnerabilities_response_value)}')

2022-12-14 09:20 UTC, Shellyber commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
> +        demisto.debug(len(list_vulnerabilities_response_value))
Why do we need these logs?

2022-12-18 10:58 UTC, Shellyber approved these changes

2022-12-19 11:30 UTC, ShirleyDenkberg commented
@Shellyber Doc review completed.

2022-12-21 07:25 UTC, merged