Generic SQL fetch-incidents
demisto/content pull request #22944
Opened 2022-12-11 11:45 UTC by rshunim

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-921)

## Description
Add support for fetch incidents (Generic SQL integration)

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-01-09 15:20 UTC, yuvalbenshalom requested changes
see my comments

2023-01-10 09:35 UTC, rshunim commented on Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
> +
it's not mine

2023-01-10 09:37 UTC, rshunim commented on Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
> +
In general I'll add a few unit tests for the de duplication

2023-01-17 11:40 UTC, yuvalbenshalom approved these changes

2023-01-19 15:04 UTC, ShirleyDenkberg commented
@yuvalbenshalom Doc review completed.

2023-01-24 06:59 UTC, merged