Netbox event collector
demisto/content pull request #22977
Opened 2022-12-12 08:12 UTC by mmhw

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3347)

## Description
A new pack with an Event Collector

## Minimum version of Cortex XSIAM
- [x] 6.8.0

## Must have
- [x] Tests
- [x] Documentation

2022-12-12 10:14 UTC, bziser requested changes
Great work, These is my initial review :)

2022-12-12 10:14 UTC, bziser commented on Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.py
> +def get_events(client: Client, limit: int):
```suggestion
def get_events_command(client: Client, limit: int):
```
Please add return type

2022-12-12 10:14 UTC, bziser commented on Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.py
> +def test_module(client: Client) -> str:
```suggestion
def test_module_command(client: Client) -> str:
```

2022-12-12 10:14 UTC, bziser commented on Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.py
> +            ordering: boll, if is True this will return the data starting with the oldest, otherwise, the opposite.
```suggestion
            ordering: bool, The oldest data will be returned if is True, otherwise the opposite.
```

2022-12-12 10:14 UTC, bziser commented on Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.py
> +    def search_events(self, url_suffix, limit=DEFAULT_LIMIT, prev_id=0, ordering=''):
Add typing

2022-12-12 10:14 UTC, bziser commented on Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.py
> +        All the parameters are passed directly to the API as HTTP POST parameters in the request
```suggestion
        Searches for NetBox alerts using the '/<log_type>' API endpoint for log_type in LOG_TYPES.
```

2022-12-12 19:05 UTC, bziser commented on Packs/NetBox/pack_metadata.json
> +    ]
```suggestion
    "marketplaces": [
        "marketplacev2"
    ]
```

2022-12-12 19:07 UTC, bziser commented on Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector_test.py
> +def test_get_events_command(requests_mock):
Please add "Given, When, Then.."

2022-12-18 08:40 UTC, bziser commented
@mmhw  From my side, it looks great
Let's wait for @ShirleyDenkberg Docs review :)

2022-12-18 11:00 UTC, ShirleyDenkberg commented
@bziser Doc review completed.

2022-12-18 17:25 UTC, mmhw commented on Packs/NetBox/README.md
> +THis pack contains an integration to collect events automatically from NetBox.
This

2022-12-21 08:56 UTC, bziser approved these changes
Great job! 👏

2022-12-21 09:37 UTC, merged