changes
demisto/content pull request #23014
Opened 2022-12-13 12:15 UTC by merit-maita

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2022-12-18 13:43 UTC, DeanArbel requested changes
Looks good, a couple of notes.

2022-12-18 13:43 UTC, DeanArbel commented on Tests/Marketplace/marketplace_constants.py
> +    Data_SOURCE = "Data Source"
Preferably, it should be `DATA_SOURCE`

2022-12-18 13:43 UTC, DeanArbel commented on Tests/Marketplace/marketplace_services.py
> +    def marketplaces(self, value):
Where is this `setter` used?

2022-12-18 13:43 UTC, DeanArbel commented on Tests/Marketplace/marketplace_services.py
> +                    self._is_data_source = False
This flag handling is a bit long, Please extract it to a new boolean function such as: `is_data_source_pack` and save the result back to `self._is_data_source`.

2022-12-18 19:22 UTC, DeanArbel commented on Tests/Marketplace/marketplace_services.py
> +            self.is_data_source_pack(yaml_content)
This name isn't good.
The intent is to have a `bool` function so this part will be functional - i.e. the boolean flag `_is_data_source` should be updated by the result of the function.
The other flag `_single_integration` can be handled outside of the new function for a straight forward implementation.
i.e.
```
self._is_data_source = self.is_data_source_pack(yaml_content)
if not yaml_content.get('deprecated', False):
    self._single_integration = False

2022-12-19 05:57 UTC, DeanArbel approved these changes
Good job

2022-12-19 06:50 UTC, yaakovpraisler reviewed
Looks good! Just a small constant fix.
Did you ran a test upload and verified that the tag was added to all the packs you removed the tag from? if so, please attach here a link to the build

2022-12-19 06:50 UTC, yaakovpraisler commented on Tests/Marketplace/marketplace_constants.py
> +    Data_SOURCE = "Data_Source"
```suggestion
    DATA_SOURCE = "Data Source"
```

2022-12-19 06:50 UTC, yaakovpraisler commented on Tests/Marketplace/marketplace_services.py
> +        tags |= {f"marketplacev2:{PackTags.Data_SOURCE}"} if self._is_data_source else set()
```suggestion
        tags |= {f"marketplacev2:{PackTags.DATA_SOURCE}"} if self._is_data_source else set()
```

2022-12-19 07:34 UTC, merit-maita commented
> Looks good! Just a small constant fix. Did you ran a test upload and verified that the tag was added to all the packs you removed the tag from? if so, please attach here a link to the build

here's a link to [test upload flow](https://code.pan.run/xsoar/content/-/pipelines/4241572).
we can see for example that, pack OnboradingIntegration does not originally have the tag data source, but since it fits the criteria, in the test flow, the tag was added.
while AWS GuardDuty, previously has the tag, and not its removed

2022-12-19 13:27 UTC, merged