SMIME stderr bug fix
demisto/content pull request #23230
Opened 2022-12-22 13:33 UTC by dansterenson

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-19569)

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2022-12-26 12:55 UTC, ShahafBenYakir commented on Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.py
> +    print("TEST")
Is this for testing? Why are we importing this twice?

2022-12-26 12:55 UTC, ShahafBenYakir commented on Packs/SMIME_Messaging/ReleaseNotes/1_0_6.md
> +Fixed an issue where unwanted messages from external python libraries were printed to screen.
```suggestion
Fixed an issue where unrelated messages from external python libraries were printed to the screen.
```

2022-12-29 10:40 UTC, ostolero requested changes
Hi Dan, Please add the `EWS Mail Sender Test 3` TPB under the integrations yml `tests` section.
As it is configured in conf.json it should run here as well.
Also this is a nightly test so let's make sure it passes in build before merging. 
Let me know if you need any help with the TPB, tnx

2023-01-05 09:54 UTC, ostolero reviewed
Looks great! did you get a chance to check if a unit test could be added to detect this issue in the future?

2023-01-08 14:56 UTC, ostolero approved these changes
Looks great 👍

2023-01-08 15:26 UTC, merged