ResolveShortenedURL Enhancement
demisto/content pull request #23385
Opened 2022-12-29 11:12 UTC by MichaelYochpaz

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [Jira Link](https://jira-hq.paloaltonetworks.local/browse/CIAC-2161)

## Description
Add support to resolve links that are recursively shortened, additional unshortening services, and self unshortening by following redirects.

## Screenshots
Paste here any images that will help the reviewer

2023-01-03 13:49 UTC, ShirleyDenkberg commented
@bziser Doc review completed.

2023-01-04 09:52 UTC, julieschwartz18 commented
Doc review complete for the README.md file. @MichaelYochpaz - please review and confirm.

2023-01-05 10:56 UTC, bziser commented on Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
> +    default_redirect_limit: int = 0  # Default value to use if `redirect_limit` is None
Please put the defaults at the top of the file in capital letters
And change `default_redirect_limit` to `str`

2023-01-05 10:56 UTC, bziser commented on Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
> +        session_verify = not argToBoolean(demisto.args().get("insecure", "False"))
```suggestion
        session_verify = not argToBoolean(args.get("insecure", "False"))
```

2023-01-05 10:56 UTC, bziser commented on Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
> +                         "It is possible that the unshortening process was not fully completed.\n\n"
```suggestion
    error_message = "There was an error while attempting to unshorten the final URL in the redirect chain.\n" \
                         "It is possible that the unshortening process was not fully completed.\n\n"
```
Why do we need to explicit the type here? It's string and we don't change the type after this

2023-01-05 10:56 UTC, bziser commented on Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
> +        original_url: str = url
Why the typing is needed?

2023-01-05 12:55 UTC, MichaelYochpaz commented on Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
> +        original_url: str = url
```suggestion
        encountered_error = False
        original_url = url
```

2023-01-05 13:22 UTC, bziser commented on Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py
> +DEFAULT_SERVICE = "unshorten.me"  # Default service to use if `redirect_limit` is not specified.
```suggestion
DEFAULT_SERVICE = "unshorten.me"  # Default service to use if `service` is not specified.

```
I don't think we need this comment at all, it prtty obvious from the name of it

2023-01-08 09:38 UTC, DeanArbel requested changes
Looks good. Excellent usage of `test classes` to scope relevant tests.
See my notes below.

2023-01-08 13:21 UTC, MichaelYochpaz commented
@DeanArbel I'm resolving the loop-related issues after our Slack discussion

2023-01-08 13:53 UTC, DeanArbel approved these changes
Good job

2023-01-08 14:16 UTC, bziser approved these changes

2023-01-08 14:32 UTC, merged