Add epp malop v2.0.1
demisto/content pull request #23476
Opened 2023-01-02 13:51 UTC by suraj-metron

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-01-02 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=23476) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=23476) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: suraj-metron<br/>:x: shabina-metron<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=23476) it.</sub>

2023-01-05 09:14 UTC, ilaner requested changes
Great job!
Please see the comments and try to reach the necessary coverage in unit tests

2023-01-05 09:14 UTC, ilaner commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +IS_EPP_ENABLED = demisto.params().get('enable_epp_poll', False)
```suggestion
IS_EPP_ENABLED = argToBool(demisto.params().get('enable_epp_poll', False))
```

2023-01-05 09:14 UTC, ilaner commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +        if malops.get('edr') is False:
```suggestion
        if not malops.get('edr'):
```

2023-01-05 09:14 UTC, ilaner commented on Packs/Cybereason/Integrations/Cybereason/Cybereason.py
> +    if guid_string == "":
```suggestion
    if not guid_string:
```

2023-01-05 11:15 UTC, suraj-metron commented
Thank you @ilaner for your suggestions, we will review and add those.
Also, we will update the Unit test to cover the required percentage of code.

2023-01-09 11:56 UTC, ilaner approved these changes

2023-01-09 11:56 UTC, ilaner commented
Great job!

2023-01-09 11:56 UTC, merged