Added get_tenant_info-command
demisto/content pull request #23509
Opened 2023-01-03 10:07 UTC by yilmazdincer

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-01-03 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=23509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=23509) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=23509) it.</sub>

2023-01-03 11:54 UTC, adi88d commented
Hi @yilmazdincer Thank you for your contribution!
please register your contribution by filling the contribution registration form in - https://forms.gle/XDfxU4E61ZwEESSMA

2023-01-04 15:33 UTC, adi88d requested changes
Please see my comments below:
- You added the command `xdr-get-tenant-info` to the `CortexXDRIR.py` file only, please update the `CortexXDRIR.yml` too with this command.
- After update the yml file you can update the `README.md` file with the new command - use `demisto-sdk generate-docs` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#generate-docs.
- Update `command_examples` file.
- Please bump the version of the pack in the pack_metadata.json file and add notes describing your changes to a new Release Notes file. 
To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

2023-01-04 15:36 UTC, adi88d commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +            json_data={'request_data': request_data},
no need to create request_data if its empty dict, remove it and change line 383 to:

```
            json_data={'request_data': request_data},
```

2023-01-05 13:18 UTC, yilmazdincer commented
> Please see my comments below:
> 
> * You added the command `xdr-get-tenant-info` to the `CortexXDRIR.py` file only, please update the `CortexXDRIR.yml` too with this command.
> * After update the yml file you can update the `README.md` file with the new command - use `demisto-sdk generate-docs` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#generate-docs.
> * Update `command_examples` file.
> * Please bump the version of the pack in the pack_metadata.json file and add notes describing your changes to a new Release Notes file.
>   To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

2023-01-05 14:38 UTC, adi88d requested changes
Great Job!
- Please add outputs to the `xdr-get-tenant-info` command, you can use [generate-outputs](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/generate_outputs/README.md) from the SDK.
- Update the README.md file only with `xdr-get-tenant-info` command part.
- Remove the Pipfile

2023-01-05 14:40 UTC, adi88d commented on Packs/CortexXDR/ReleaseNotes/4_9_15.md
> +- Added a new command 'xdr-get-tenant-info'
```suggestion
- Added the ***xdr-get-tenant-info*** command.
- Updated the Docker image to: *demisto/python3:3.10.9.42476*.
```

2023-01-05 14:55 UTC, adi88d commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +    return tenant_info
```suggestion
    readable_output = tableToMarkdown(
        'Tenant Information', tenant_info, headerTransform=pascalToSpace, removeNull=True, is_auto_json_transform=True
    )
    return CommandResults(
        readable_output=readable_output,
        outputs_prefix=f'{INTEGRATION_CONTEXT_BRAND}.TenantInformation',
        outputs=tenant_info,
        raw_response=tenant_info
    )
```

2023-01-09 09:57 UTC, adi88d approved these changes
Great!

2023-01-09 10:07 UTC, merged

2023-01-10 08:38 UTC, adi88d commented
@yilmazdincer i'm sorry in advance, we have some internal issues with the contribution process so your pull request release will be delay