Generic sql bug mssql driver
demisto/content pull request #23797
Opened 2023-01-12 13:19 UTC by rshunim

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20180 https://jira-hq.paloaltonetworks.local/browse/CIAC-5068

## Description
This fix should resolve a connection error of 'Microsoft SQL Server  - MS ODBC Driver'.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-01-12 18:56 UTC, esharf approved these changes
looks good

2023-01-12 18:56 UTC, esharf commented on Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
> +                f'Unexpected error: {str(err)} \nquery: {demisto.args().get("query")} \n{traceback.format_exc()}')
```suggestion
                f'Unexpected error: {str(err)} \nquery: {demisto.args().get("query")}')
```
the `return_error` method already takes care about it

2023-01-12 18:56 UTC, esharf commented on Packs/GenericSQL/ReleaseNotes/1_0_13.md
> +- Fixed an issue with 'Microsoft SQL Server  - MS ODBC Driver' had connection error.
```suggestion
- Fixed an issue with 'Microsoft SQL Server - MS ODBC Driver' had connection error.
```

2023-01-15 07:32 UTC, yuvalbenshalom reviewed
see my comment, and also check the build.

2023-01-15 07:32 UTC, yuvalbenshalom commented on Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
> +        if type(err).__name__ == 'OperationalError':
how do you know this is the only case that you will get error named "OperationalError" seems to me that this is can be a family of different errors.
maybe it is better to check if e substring in the error message matches? like if you have 'certificate' or something like this?(need to check the original error.

in any case, you should print the error content in the end and not to hide it.

2023-01-15 09:17 UTC, esharf approved these changes

2023-01-17 07:17 UTC, esharf approved these changes
great work

2023-01-17 11:36 UTC, yuvalbenshalom requested changes

2023-01-17 11:36 UTC, yuvalbenshalom commented on Packs/GenericSQL/ReleaseNotes/1_0_13.md
> +- Fixed an issue with 'Microsoft SQL Server - MS ODBC Driver' had connection error.
```suggestion
- Fixed an issue where the integration failed to connect to Microsoft SQL Server.
```

2023-01-17 11:37 UTC, merged