Check Point Dome9 - fix fetch incidents
demisto/content pull request #23912
Opened 2023-01-18 08:18 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-19349)

## Description
- Fixed an issue where the integration fetching duplicate incidents.
- Changed the type of the *API key secret* and the *API key ID* parameters to `Encrypted`.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-01-29 16:01 UTC, DeanArbel commented on Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9.yml
> +  type: 9
Good job prioritizing this, but please check with @mmhw on how to do this.
This change isn't as simple as just switching the param type.

2023-01-29 16:01 UTC, DeanArbel commented on Packs/CheckPointDome9/ReleaseNotes/1_0_3.md
> +- Fixed an issue where the integration fetching duplicate incidents.
```suggestion
- Fixed an issue where the integration fetched duplicate incidents.
```

2023-01-30 11:25 UTC, mmhw requested changes

2023-01-30 11:25 UTC, mmhw commented on Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9.py
> +    key_secret = key_secret or api_key_secret_cred
```suggestion
    key_id = api_key_id_cred or key_id
    key_secret = api_key_secret_cred or key_secret
```

2023-01-30 11:25 UTC, mmhw commented on Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9.yml
>    type: 0
```suggestion
  type: 0
  hidden: true
```

2023-01-30 11:25 UTC, mmhw commented on Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9.yml
>    type: 0
```suggestion
  type: 0
  hidden: true
```

2023-01-30 11:26 UTC, mmhw commented on Packs/CheckPointDome9/Integrations/CheckPointDome9/CheckPointDome9.py
> +    key_secret = key_secret or api_key_secret_cred
To be able to update an existing instance with new credentials

2023-01-30 12:28 UTC, mmhw reviewed
For me it's good

2023-01-31 11:48 UTC, DeanArbel approved these changes

2023-01-31 11:49 UTC, merged