init
demisto/content pull request #23916
Opened 2023-01-18 10:48 UTC by RosenbergYehuda

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-01-29 17:04 UTC, JasBeilin requested changes
Great job, see my comments and make sure to have tech review.

2023-01-29 17:04 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_test.py
> +    assert test_module(client=client) == '404'
redundant :)

2023-01-29 17:04 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_test.py
> +def test_fetch_indicators_command(mocker):
lets use parametrize for different cases

2023-01-31 11:20 UTC, ShirleyDenkberg commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
> +description: Use the Cisco WebEx Feed integration to fetch indicators from WeBex.
Shouldn't this be 
Use the Cisco WebEx Feed integration to fetch indicators from WebEx.
or should it be Webex?  When I looked it up on line, the E is not uppercase.

2023-01-31 11:22 UTC, ShirleyDenkberg commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
> +      description: The indicator type. Can be "CIDR", "DOMAIN", or "Both".
no reason to list the possible values.  When generating the README, the values automatically appear. 
So this should be: The indicator type.

2023-01-31 11:23 UTC, ShirleyDenkberg commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_description.md
> +The Cisco WebEx Feed integration fetches IP addresses and domains used by WebEx.
Again, I think It should be Webex.  No uppercase E.
The Cisco WebEx Feed integration fetches IP addresses and domains used by Webex.

2023-01-31 11:23 UTC, ShirleyDenkberg commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/README.md
> +Use the Cisco WebEx Feed integration to fetch indicators from WeBex.
Use the Cisco WebEx Feed integration to fetch indicators from Webex.

2023-01-31 11:37 UTC, ShirleyDenkberg commented on Packs/CiscoWebExFeed/README.md
> +### Acknowledgements
This section should be removed.

2023-01-31 11:37 UTC, ShirleyDenkberg commented on Packs/CiscoWebExFeed/README.md
> +`Cisco WebEx Feed` integration -  Fetches indicators from the Cisco WebEx website within Cortex XSOAR.
Should be ....the Cisco Webex website....

2023-01-31 11:38 UTC, ShirleyDenkberg commented on Packs/CiscoWebExFeed/README.md
> +- Fetches indicators from the Cisco WebEx Feed according to the applied filters.
no bullet when there is only one item.

2023-01-31 11:41 UTC, ShirleyDenkberg commented
@RosenbergYehuda See my comments.
@JasBeilin @ostolero Doc review completed.

2023-02-02 07:27 UTC, JasBeilin requested changes
Good job, a few more changes so we can move forward.

2023-02-02 07:27 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
> +    # skip the last line as it is not a domain
Instead of writing what it is not, lets write what it is.

2023-02-02 07:27 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
> +        indicators = clean_res.get(CIDR)[:limit] + clean_res.get(DOMAIN)[:limit]  # type: ignore
```suggestion
        indicators = clean_res.get(CIDR)[:limit] + clean_res.get(DOMAIN)[:limit] 
```

2023-02-02 07:27 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
> +    for indicator in clean_res.get(CIDR) + clean_res.get(DOMAIN):   # type: ignore
```suggestion
    for indicator in clean_res.get(CIDR) + clean_res.get(DOMAIN):  
```

2023-02-02 07:27 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
> +  id: Cisco WebEx Feed Dev
Remove please

2023-02-02 07:27 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed_test.py
> +FETCH_INDICATORS_INPUT_3 = {'CIDR': ['ipmock1', 'ipmock2']}
Where are these being used?

2023-02-02 07:27 UTC, JasBeilin commented on Tests/conf.json
> +        },
Did you add the required instance configuration?

2023-02-05 13:47 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
> -        data.append([ele for ele in cols if ele])  # Get rid of empty values
Why do you remove the comment?

2023-02-05 13:50 UTC, JasBeilin commented on Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
> +    for line in data[0]:
What happens if data is empty list? Why not give a readable error?

2023-02-05 15:16 UTC, JasBeilin approved these changes

2023-02-06 08:48 UTC, merged