Fixed the incorrect README
demisto/content pull request #23929
Opened 2023-01-19 06:11 UTC by spearmin10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Fixed the incorrect README. It was described on the `SetWithTemplate`.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-01-24 09:52 UTC, gal-forer requested changes

2023-01-24 09:52 UTC, gal-forer commented on Packs/FiltersAndTransformers/Scripts/ConcatFormat/README.md
> +The transformer concatenates prefix and suffix which supports DT expressions to the string.
Hi, thanks for the donation, why did you reduced the description of the script ? The old one was more extensive, can you please elaborate or use the old one ?

2023-01-24 09:52 UTC, gal-forer commented on Packs/FiltersAndTransformers/Scripts/ConcatFormat/README.md
> +| **Argument Name** | **Value** | **Note** |
Can you please add the missing fields ? There are no value or note for some of the fields

2023-01-24 09:52 UTC, gal-forer commented on Packs/FiltersAndTransformers/Scripts/ConcatFormat/README.md
> +| **Argument Name** | **Value** | **Note** |
Can you please add the missing fields ? There are no value or note for some of the fields

2023-01-25 07:43 UTC, spearmin10 commented
@gal-forer The old one is the different README. so please don't compare with it.
The old one is the README for `SetWithTemplate`.
I've contributed `ConcatFormat` with `SetWithTemplate` before, but I've mistaken to copy the README for the script.
The README of the PR is the original one for it.

https://github.com/demisto/content/blob/c095f4b31d9c37788999e480a51c51889bcdbd35/Packs/CommonScripts/Scripts/SetWithTemplate/README.md

2023-01-29 09:24 UTC, gal-forer commented
> @gal-forer The old one is the different README. so please don't compare with it. The old one is the README for `SetWithTemplate`. I've contributed `ConcatFormat` with `SetWithTemplate` before, but I've mistaken to copy the README for the script. The README of the PR is the original one for it.
> 
> https://github.com/demisto/content/blob/c095f4b31d9c37788999e480a51c51889bcdbd35/Packs/CommonScripts/Scripts/SetWithTemplate/README.md

Ok, but can you please add values for the examples @spearmin10

2023-01-31 09:17 UTC, spearmin10 commented
@gal-forer OK, I've updated it.

2023-01-31 09:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=23929) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=23929) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: content-bot<br/>:white_check_mark: YuvHayun<br/>:white_check_mark: spearmin10<br/>:white_check_mark: dorschw<br/>:white_check_mark: rshunim<br/>:x: tomer-pan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=23929) it.</sub>

2023-01-31 09:33 UTC, gal-forer approved these changes

2023-01-31 09:33 UTC, merged