Azure managed identities
demisto/content pull request #23951
Opened 2023-01-19 15:25 UTC by ilappe

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-1008

## Description
Support the Azure Managed Identities in. our Azure/MS integrations

## Must have
- [x] Tests
- [x] Documentation

2023-02-01 13:01 UTC, DeanArbel reviewed
@ilappe please setup a demo meeting with me and @yucohen - let's do a live CR.

2023-02-01 13:01 UTC, DeanArbel commented on Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
> +    return 'ok'
@yucohen wdyt about this change?

2023-02-01 13:01 UTC, DeanArbel commented on Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
> +            return_outputs('```✅ Success!```')
@yucohen same here

2023-02-02 08:34 UTC, julieschwartz18 commented on Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_description.md
>  ### Self deployed configuration
```suggestion
### Self-Deployed configuration
```

2023-02-02 08:34 UTC, julieschwartz18 commented on Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_description.md
> +   1. Go to [Azure Portal](https://portal.azure.com/) -> **Managed Identities**
```suggestion
   1. Go to [Azure Portal](https://portal.azure.com/) -> **Managed Identities**.
```

2023-02-02 08:34 UTC, julieschwartz18 commented on Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_description.md
> +   2. Select your User Assigned Managed Identity -> copy the Client ID -> put it in the **Azure Managed Identities Client ID** field in the instance settings.
```suggestion
   2. Select your User Assigned Managed Identity -> copy the Client ID -> paste it in the **Azure Managed Identities Client ID** field in the instance settings.
```

2023-02-02 08:35 UTC, julieschwartz18 commented on Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser_description.md
> +For information about Azure Managed Identities see [Managed identities for Azure resources](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview)
```suggestion
For information, see [Managed identities for Azure resources](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview).
```

2023-02-02 08:46 UTC, julieschwartz18 commented on Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity_description.md
> +   1. Go to [Azure Portal](https://portal.azure.com/) -> **Managed Identities**
```suggestion
   1. Go to [Azure Portal](https://portal.azure.com/) -> **Managed Identities**.
```

2023-02-02 08:57 UTC, julieschwartz18 commented on Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity_description.md
> +   2. Select your User Assigned Managed Identity -> copy the Client ID -> put it in the **Azure Managed Identities Client ID** field in the instance settings.
```suggestion
   2. Select your User Assigned Managed Identity -> copy the Client ID -> paste it in the **Azure Managed Identities Client ID** field in the instance settings.
```

2023-02-02 08:57 UTC, julieschwartz18 commented on Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity_description.md
> +For information about Azure Managed Identities see [Managed identities for Azure resources](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview)
```suggestion
For more information, see [Managed identities for Azure resources](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview)
```

2023-02-02 08:59 UTC, julieschwartz18 commented on Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/README.md
> +    | Azure Managed Identities Client ID | The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM. | False |
```suggestion
    | Azure Managed Identities Client ID | The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM. | False |
```

2023-02-02 09:01 UTC, julieschwartz18 commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_description.md
>  1. *Client Credentials Flow* (Recommended).
```suggestion
1. Client Credentials Flow (recommended).
```

2023-02-02 09:01 UTC, julieschwartz18 commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_description.md
>  2. *Device Code Flow*.
```suggestion
2. Device Code Flow.
```

2023-02-02 09:02 UTC, julieschwartz18 commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_description.md
> +3. *Azure Managed Identities*.
```suggestion
3. Azure Managed Identities
```

2023-02-02 09:03 UTC, julieschwartz18 commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_description.md
> +   - Select *Azure Managed Identities* in *Authentication Type* drop-down list and leave the **Azure Managed Identities Client ID** field empty.
```suggestion
   - In the **Authentication Type** drop-down list, select **Azure Managed Identities**  and leave the **Azure Managed Identities Client ID** field empty.
```

2023-02-02 09:05 UTC, julieschwartz18 requested changes

2023-02-02 09:05 UTC, julieschwartz18 commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_description.md
> +   3. Select *Azure Managed Identities* in **Authentication Type** drop-down list.
```suggestion
   3. In the **Authentication Type** drop-down list, select **Azure Managed Identities**.
```

2023-02-02 09:08 UTC, julieschwartz18 commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement_description.md
> +For information about Azure Managed Identities see [Managed identities for Azure resources](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview)
```suggestion
For more information, see [Managed identities for Azure resources](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview).
```

2023-02-02 09:10 UTC, julieschwartz18 commented on Packs/AzureFirewall/Integrations/AzureFirewall/AzureFirewall.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:10 UTC, julieschwartz18 commented on Packs/AzureKeyVault/Integrations/AzureKeyVault/AzureKeyVault.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:11 UTC, julieschwartz18 commented on Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.yml
> +- additionalinfo: Type of authentication - could be Authorization Code Flow (recommended), Device Code Flow or Azure Managed Identities.
```suggestion
- additionalinfo: Type of authentication - can be Authorization Code Flow (recommended), Device Code Flow, or Azure Managed Identities.
```

2023-02-02 09:11 UTC, julieschwartz18 commented on Packs/AzureKubernetesServices/Integrations/AzureKubernetesServices/AzureKubernetesServices.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:12 UTC, julieschwartz18 commented on Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:12 UTC, julieschwartz18 commented on Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/AzureNetworkSecurityGroups.yml
> +  additionalinfo: Type of authentication - could be Authorization Code flow (recommended), Device Code flow or Azure Managed Identities.
```suggestion
  additionalinfo: Type of authentication - can be Authorization Code Flow (recommended), Device Code Flow or Azure Managed Identities.
```

2023-02-02 09:13 UTC, julieschwartz18 commented on Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/AzureNetworkSecurityGroups.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:13 UTC, julieschwartz18 commented on Packs/AzureRiskyUsers/Integrations/AzureRiskyUsers/AzureRiskyUsers.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:14 UTC, julieschwartz18 commented on Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.yml
> +- additionalinfo: Type of authentication - could be Authorization Code Flow (recommended), Device Code Flow or Azure Managed Identities.
```suggestion
- additionalinfo: Type of authentication - can be Authorization Code Flow (recommended), Device Code Flow, or Azure Managed Identities.
```

2023-02-02 09:14 UTC, julieschwartz18 commented on Packs/AzureSQLManagement/Integrations/AzureSQLManagement/AzureSQLManagement.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:15 UTC, julieschwartz18 commented on Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:15 UTC, julieschwartz18 commented on Packs/AzureStorage/Integrations/AzureStorage/AzureStorage.yml
> +  additionalinfo: Type of authentication - could be Authorization Code flow (recommended), Device Code Flow or Azure Managed Identities.
```suggestion
  additionalinfo: Type of authentication - can be Authorization Code Flow (recommended), Device Code Flow, or Azure Managed Identities.
```

2023-02-02 09:16 UTC, julieschwartz18 commented on Packs/AzureStorage/Integrations/AzureStorage/AzureStorage.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:17 UTC, julieschwartz18 commented on Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:17 UTC, julieschwartz18 commented on Packs/AzureStorageQueue/Integrations/AzureStorageQueue/AzureStorageQueue.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:18 UTC, julieschwartz18 commented on Packs/AzureStorageTable/Integrations/AzureStorageTable/AzureStorageTable.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:18 UTC, julieschwartz18 commented on Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.yml
> +- additionalinfo: Type of authentication - could be Authorization Code Flow (recommended), Device Code Flow or Azure Managed Identities.
```suggestion
- additionalinfo: Type of authentication - can be Authorization Code Flow (recommended), Device Code Flow, or Azure Managed Identities.
```

2023-02-02 09:19 UTC, julieschwartz18 commented on Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:19 UTC, julieschwartz18 commented on Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:20 UTC, julieschwartz18 commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:20 UTC, julieschwartz18 commented on Packs/MicrosoftGraphApplications/Integrations/MicrosoftGraphApplications/MicrosoftGraphApplications.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:21 UTC, julieschwartz18 commented on Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:22 UTC, julieschwartz18 commented on Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:23 UTC, julieschwartz18 commented on Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:24 UTC, julieschwartz18 commented on Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:24 UTC, julieschwartz18 commented on Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:25 UTC, julieschwartz18 commented on Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:25 UTC, julieschwartz18 commented on Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:26 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:26 UTC, julieschwartz18 commented on Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:27 UTC, julieschwartz18 commented on Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 09:28 UTC, julieschwartz18 commented on Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/MicrosoftTeamsManagement.yml
> +- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```suggestion
- additionalinfo: The Managed Identities client id for authentication - relevant only if the integration is running on Azure VM.
```
```suggestion
- additionalinfo: The Managed Identities client ID for authentication - relevant only if the integration is running on Azure VM.
```

2023-02-02 13:14 UTC, ilappe commented on Packs/ApiModules/Scripts/MicrosoftAzureStorageApiModule/MicrosoftAzureStorageApiModule.py
> +
align with MicrosoftApiModule

2023-02-02 13:28 UTC, ilappe commented on Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/AzureLogAnalytics.py
> +            return_outputs('```✅ Success!```')
check to replace with return_results

2023-02-02 13:31 UTC, DeanArbel approved these changes
Impressive work. Very well done!

2023-02-06 20:49 UTC, ilappe commented
@DeanArbel 
force merge please....
the fail in code.pan.run aren't relevant to this PR

2023-02-06 21:14 UTC, merged