Run zero
demisto/content pull request #24023
Opened 2023-01-23 09:26 UTC by thefrieddan1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4810
https://jira-hq.paloaltonetworks.local/browse/CIAC-4458

## Description
Added support RunZero 2 integrations  RunZeroEventCollector for XSIAM, 
RunZero for XSOAR.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

2023-01-26 12:57 UTC, DeanArbel requested changes

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +# from typing import Dict, Any
Please remove 
```suggestion
```

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector.py
> +DATE_FORMAT = '%Y-%m-%dT%H:%M:%SZ'
You're not using this, please remove
```suggestion
```

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +DATE_FORMAT = '%Y-%m-%dT%H:%M:%SZ'  # ISO8601 format with UTC, default in XSOAR
You're not using this, please remove
```suggestion
```

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +            return_results(result)
just wrap the result with `return_results()` - no need for it to be a 2 liner.
The same goes for all the rest of the commands.
```suggestion
            return_results(test_module(client))
```

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +        url_suffix = f'/org/assets/bulk/delete?asset_ids={asset_ids}'
when using url args it's better to use the `params` arg for `_http_request`, i.e. to provide a `{arg_key: arg_val}` dict.

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +        url_suffix = f'/org/assets{search_str}' if search_str else '/org/assets'
If you work with `params` dict containing the `search query` you can remove this line, as it won't be added to the search if `params` is empty.

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +    # min RTT = 0, MAX_RTT = 1_000_000
perhapse use a [doctest](https://docs.python.org/3/library/doctest.html)?

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +        search_string = f'?search={args.get("search")}'
Since using several types simultaneously is incompatible - please raise an error if more than one is provided.

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +    if type(raw) is list:
The common way to do this is via the built-in [isinstance](https://docs.python.org/3/library/functions.html#isinstance) function.
```suggestion
    if isinstance(raw, list):
```

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +def asset_search(client: Client, args: dict) -> CommandResults:
Please add the `_command` suffix to this function name, and to the rest of the command functions.

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +                del item_raw['attributes']
please use `pop('attributes', None)` as it'll work even when `attributes` is missing.
Same comment for the rest of deletes like this.
```suggestion
                item_raw.pop('attributes', None)
```

2023-01-26 12:57 UTC, DeanArbel commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +    tagsList = argToList(args['tags'])
the naming convention for python is `snake_case`.

2023-01-29 14:44 UTC, thefrieddan1 commented on Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector.py
> +    assert isinstance(first_fetch_epoch_time, int)
Not sure how to implement it.

2023-01-29 14:44 UTC, thefrieddan1 commented on Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector.py
> +            raise e
Not sure how to implement it.

2023-01-29 15:12 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Asset outlier.
Is this description correct?

2023-01-29 15:12 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Asset outlier.
Is this description correct?

2023-01-29 15:13 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Asset outlier.
Is this description correct?

2023-01-29 15:13 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Asset outlier.
Is this description correct?

2023-01-29 15:14 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Service outlier.
Is this description correct?

2023-01-29 15:14 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Service outlier.
Is this description correct?

2023-01-29 15:14 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Service outlier.
Is this description correct?

2023-01-29 15:14 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Service outlier.
Is this description correct?

2023-01-29 15:14 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Service outlier.
Is this description correct?

2023-01-29 15:15 UTC, ShirleyDenkberg commented on Packs/RunZero/Integrations/RunZero/RunZero.yml
> +      description: Service hostname.
Is this description correct?

2023-01-30 16:07 UTC, DeanArbel requested changes
There were a couple of notes of mine from the previous CR that weren't handled.
Please go over all comments.

2023-01-30 19:48 UTC, thefrieddan1 commented on Packs/RunZero/README.md
> +- Fetches RunZero events.
not sure if this is how its supposed to be.

2023-01-30 20:55 UTC, thefrieddan1 commented on Packs/RunZero/Integrations/RunZero/RunZero.py
> +        raw_response=raw,
Copied raw to outputs. Removed from outputs.

2023-01-31 08:02 UTC, thefrieddan1 commented on Packs/RunZero/Integrations/RunZeroEventCollector/RunZeroEventCollector_description.md
> +
Meital replied that quota request is not required.

2023-01-31 12:14 UTC, DeanArbel approved these changes
Very well done. Good job

2023-01-31 12:14 UTC, DeanArbel commented on Packs/RunZero/.secrets-ignore
> +hmac-sha1\\thmac-sha1-etm@openssh.com\\thmac-sha2-256\\thmac-sha2-256-etm@opensshcom\\thmac-sha2-512\\thmac-sha2-512-etm@openssh.com\\tumac-128-etm@openssh.com\\tumac-128@openssh.com
Please remove these emails from the PR

2023-01-31 17:31 UTC, merged