update package
demisto/content pull request #24301
Opened 2023-02-02 12:30 UTC by JudahSchwartz

demisto-sdk nightly https://code.pan.run/xsoar/content/-/pipelines/4599774
Content nightly https://code.pan.run/xsoar/content/-/pipelines/4599773
Private https://github.com/demisto/content-private/pull/652

gold branch https://code.pan.run/xsoar/content-internal-dist/-/merge_requests/219
run: https://code.pan.run/xsoar/content-internal-dist/-/pipelines/4600958

2023-02-08 16:39 UTC, ShahafBenYakir approved these changes

2023-02-09 07:58 UTC, ShahafBenYakir approved these changes

2023-02-12 11:39 UTC, dorschw commented on Packs/CrowdStrikeFalconSandbox/pack_metadata.json
> +    "currentVersion": "2.0.6",
?

2023-02-12 11:40 UTC, JudahSchwartz commented on Packs/CrowdStrikeFalconSandbox/pack_metadata.json
> +    "currentVersion": "2.0.6",
accident. removed

2023-02-12 11:41 UTC, dorschw requested changes
Please replace the PR body with links to all nightly runs.

2023-02-12 11:44 UTC, JudahSchwartz commented
@dorschw done

2023-02-12 11:45 UTC, JudahSchwartz commented
Poetry (version 1.2.0)
.circleci/config.yml is up to date!
poetry.lock is part of the branch changes, proceeding
pyproject.toml is part of the branch changes, proceeding
=== sourcing /tmp/.bash_env-63e8d02be0a87026ed3700d9-0-build ===
Checking if pyproject.toml is consistent with poetry.lock
Creating virtualenv content in /home/circleci/project/.venv

The lock file is not compatible with the current version of Poetry.
Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command

@dorschw looks like i'll need a second to fix this. @ilaner didnt we already fix this?

2023-02-12 13:10 UTC, dorschw commented
> @dorschw done

please add for gold & private

2023-02-12 15:43 UTC, JudahSchwartz commented on Tests/scripts/validate.sh
> +npm list --json
```suggestion
```

2023-02-13 07:48 UTC, JudahSchwartz commented
upgrading mdx causes more packs to fail validation, but looks like rightfully so

![image](https://user-images.githubusercontent.com/24831617/218399934-e17910cb-ac83-4000-93d2-d1e1b886140e.png)
https://xsoar.pan.dev/docs/reference/integrations/virus-total---premium-api-v3

2023-02-13 08:16 UTC, JudahSchwartz commented
im downgrading mdx for now to see if thats the only reason for the failures. If it is i'll open an issue to upgrade it so it doesnt need to be done in this pr

2023-02-14 07:32 UTC, merged