[ASM] - Cortex ASM pack updated with Azure content
demisto/content pull request #24310
Opened 2023-02-02 16:10 UTC by BigEasyJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-1436](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-1436)
[EXPANDR-1600](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-1600)

## Description

- Update `Cortex ASM - ASM Alert` playbook to have Azure as an option in the automated remediation conditional.
- Update `Cortex ASM - Enrichment` playbook to have  Azure option to conditional and `Cortex ASM - Azure Enrichment` playbook.
- Update `Cortex ASM - Remediation` playbook to have Azure option to conditional and Azure Network Security Group Remediation playbook.
- Add new Cortex ASM - Azure Enrichment playbook.

## Screenshots

![Cortex_ASM_-_Azure_Enrichment_Updated_Feb_02_2023](https://user-images.githubusercontent.com/40349459/216378143-a5b8344b-b83c-4da6-8dac-bae3e4609313.png)
![Cortex_ASM_-_Enrichment_Updated_Feb_02_2023](https://user-images.githubusercontent.com/40349459/216378148-db89dcd9-7b83-4e0a-a278-0757ac25c216.png)
![Cortex_ASM_-_Remediation_Updated_Feb_02_2023](https://user-images.githubusercontent.com/40349459/216378151-53373508-bb43-4845-9599-32a430f99989.png)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests (performed internally)
- [x] Documentation

2023-02-02 16:20 UTC, BigEasyJ commented
CC: @johnnywilkes @capanw

2023-02-02 16:26 UTC, BigEasyJ commented
CC @johnnywilkes @capanw for review

2023-02-02 18:07 UTC, johnnywilkes commented
@BigEasyJ , please make changes in Jira when possible: https://qadium.atlassian.net/wiki/spaces/PM/pages/2383872027/XSOAR+XSIAM+Dev+Standards#Jira-Fields-to-Keep-Track-of-ASM-PRs

2023-02-02 20:32 UTC, johnnywilkes commented
@BigEasyJ , as we talked about in standup, can you also change the following to true as well (Same as "Skip this branch if this automation/playbook is unavailable" option in UI)"
- https://github.com/demisto/content/blob/54df7db0915efd2710fb728fdd0d90c61b577cb5/Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml#L65
- https://github.com/demisto/content/blob/54df7db0915efd2710fb728fdd0d90c61b577cb5/Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml#L118

2023-02-02 21:46 UTC, johnnywilkes reviewed
this is my review

2023-02-02 21:51 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/README.md
>  This automation checka if SNMP is enabled or not and gets the running version on the remote server.
resolved

2023-02-02 21:53 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
> +    skipunavailable: false
resolved

2023-02-02 21:53 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +    skipunavailable: false
resolved

2023-02-02 21:54 UTC, johnnywilkes commented
> @BigEasyJ , as we talked about in standup, can you also change the following to true as well (Same as "Skip this branch if this automation/playbook is unavailable" option in UI)"
> 
> * https://github.com/demisto/content/blob/54df7db0915efd2710fb728fdd0d90c61b577cb5/Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml#L65
> * https://github.com/demisto/content/blob/54df7db0915efd2710fb728fdd0d90c61b577cb5/Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml#L118

resolved

2023-02-03 13:32 UTC, johnnywilkes requested changes
another round

2023-02-03 13:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_0.md
> +- Update the GCP - Enrichment playbook task to skip this branch if this automation/playbook is unavailable
Change to:
- Updated the GCP - Enrichment playbook task to skip this branch if this automation/playbook is unavailable.

This should resolve https://github.com/demisto/content/actions/runs/4080101970/jobs/7032208152

2023-02-03 13:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/pack_metadata.json
> +        "Azure-Enrichment-Remediation",
at line 45 add:
"Azure-Enrichment-Remediation": {
        "mandatory": false,
        "display_name": "Azure Enrichment and Remediation"
    }

2023-02-03 13:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/README.md
> +![Cortex ASM - Azure Enrichment](https://raw.githubusercontent.com/demisto/content/23747a450237bb3762d7ec7788d5ff582c8576db/Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Azure_Enrichment
please change link to:
https://raw.githubusercontent.com/demisto/content/69b67c9a2330cbe9002d6d0ec8f32dbccb0c6877/Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Azure_Enrichment.png

That seems to work

2023-02-03 13:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/README.md
> +- [What does this pack do?](#what-does-this-pack-do)
not resolved

2023-02-03 13:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
> +      description: This playbook adds new firewall rules with access only from  private ip address range and blocks traffic that's exposed to public internet. For example, if RDP is exposed to the en
John, we actually need to revert this. Apologies. It seems like the description was updated on the child pack and not sure why it never made it to master:

[content/Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation.yml](https://github.com/demisto/content/blob/54df7db0915efd2710fb728fdd0d90c61b577cb5/Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation.yml#L4)

2023-02-03 13:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
> +          root: inputs.RemoteIp
Change this to: inputs.RemoteIP
this is how it is specified in playbook inputs and causing 2nd error in https://app.circleci.com/pipelines/github/demisto/content/231876/workflows/b391dc0e-22a8-44d0-ae08-cae7d5bd3d71/jobs/650542

2023-02-03 15:22 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
> +          root: inputs.RemoteIp
resolved in [Update input for Cortex ASM playbook](https://github.com/demisto/content/pull/24310/commits/40d107b39cd4653abe8e2fb89cb07126d9d6dcb5)

2023-02-03 15:28 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/README.md
> +- [What does this pack do?](#what-does-this-pack-do)
resolved in
https://github.com/demisto/content/pull/24310/commits/05e7231e87e8d08e66f2058411b27754fba3f52a

2023-02-03 15:30 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/README.md
> +![Cortex ASM - Azure Enrichment](https://raw.githubusercontent.com/demisto/content/23747a450237bb3762d7ec7788d5ff582c8576db/Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Azure_Enrichment
resolved in 
Update TOC and Azure playbook png

2023-02-03 15:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +inputs:
resolved in https://github.com/demisto/content/pull/24310/commits/ad0eb0dbd83d8dd1fe510dc59cdbbbf00f40f234

2023-02-03 15:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_0.md
> +- Update the GCP - Enrichment playbook task to skip this branch if this automation/playbook is unavailable
resolved in https://github.com/demisto/content/pull/24310/commits/abb84a9697d0903de6ff9ebb9928f6e08e3f1e1b

2023-02-03 15:33 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/pack_metadata.json
> +        "Azure-Enrichment-Remediation",
resolved in https://github.com/demisto/content/pull/24310/commits/c88af851fee1e0dde19ab7d443813494a48c2f27

2023-02-03 15:38 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/README.md
> +- [What does this pack do?](#what-does-this-pack-do)
@BigEasyJ , looks better but I think you removed for the parent playbook, please re-add:
`- [Cortex ASM - ASM Alert](#cortex-asm---asm-alert)`

2023-02-03 15:41 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/README.md
> +- [What does this pack do?](#what-does-this-pack-do)
resolved in
[Update TOC in README. Add missing link.](https://github.com/demisto/content/pull/24310/commits/79e053838402bf4f20c93c89bb752e80ff6b2fff)

2023-02-03 16:03 UTC, johnnywilkes approved these changes
@BigEasyJ , great work!  This is approved.

@ilaner , can you please assign @ShirleyDenkberg  for documentation review?

2023-02-05 08:51 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +description: Given the IP address this playbook enriches Azure information relevant to ASM alerts.
```suggestion
description: Given the IP address, this playbook enriches Azure information relevant to ASM alerts.
```

2023-02-05 08:52 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets  the potential Azure service owner to grid field for ASM service owner object.
```suggestion
      description: Sets the potential Azure service owner to the grid field for the ASM service owner object.
```

2023-02-05 08:53 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets Azure NSG information to grid field for ASM system IDs object.
```suggestion
      description: Sets Azure NSG information to the grid field for the ASM system IDs object.
```

2023-02-05 08:53 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets Azure resource group information to grid field for ASM system IDs object.
```suggestion
      description: Sets Azure resource group information to the grid field for the ASM system IDs object.
```

2023-02-05 08:54 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets Azure NIC information to grid field for ASM system IDs object.
```suggestion
      description: Sets Azure NIC information to the grid field for the ASM system IDs object.
```

2023-02-05 08:54 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets Azure Compute instance ID to grid field for ASM system IDs object.
```suggestion
      description: Sets the Azure Compute instance ID to the grid field for the ASM system IDs object.
```

2023-02-05 08:55 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets private IP to grid field for ASM private IP object.
```suggestion
      description: Sets the private IP to the grid field for the ASM private IP object.
```

2023-02-05 08:55 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets Azure subscription, resource group, and location information to grid field for ASM cloud object.
```suggestion
      description: Sets Azure subscription, resource group, and location information to the grid field for the ASM cloud object.
```

2023-02-05 08:56 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +      description: Sets Azure Compute instance name to grid field for ASM system IDs object.
```suggestion
      description: Sets the Azure Compute instance name to the grid field for the ASM system IDs object.
```

2023-02-05 08:57 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment.yml
> +  description: IP address of service
```suggestion
  description: IP address of the service.
```

2023-02-05 08:57 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment_README.md
> +* Azure - Enrichment
```suggestion
Azure - Enrichment
```

2023-02-05 08:57 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment_README.md
> +Given the IP address this playbook enriches Azure information relevant to ASM alerts.
```suggestion
Given the IP address, this playbook enriches Azure information relevant to ASM alerts.
```

2023-02-05 08:58 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Azure_Enrichment_README.md
> +| RemoteIP | IP address of service | alert.remoteip | Optional |
```suggestion
| RemoteIP | IP address of the service. | alert.remoteip | Optional |
```

2023-02-05 08:58 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
> +      description: Given the IP address this playbook enriches Azure information relevant to ASM alerts.
```suggestion
      description: Given the IP address, this playbook enriches Azure information relevant to ASM alerts.
```

2023-02-05 09:00 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
> +      description: This playbook adds new firewall rules with access only from  private ip address range and blocks traffic that's exposed to public internet. For example, if RDP is exposed to the en
```suggestion
      description: This playbook adds new firewall rules with access only from a private IP address range and blocks traffic that's exposed to the public internet. For example, if RDP is exposed to the entire world, this playbook adds new firewall rules that only allow traffic from a private IP address and blocks the rest of the RDP traffic.
```

2023-02-05 09:02 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
> +        This playbook adds new Azure Network Security Groups (NSG) rules to NSGs attached to a NIC. The new rules will give access only to a private IP address range and block traffic that's exposed
```suggestion
        This playbook adds new Azure Network Security Groups (NSG) rules to NSGs attached to a NIC. The new rules will give access only to a private IP address range and block traffic that's exposed to the public internet ([using the private IP of the VM as stated in Azure documentation](https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview)). For example, if RDP is exposed to the public internet, this playbook adds new firewall rules that only allow traffic from a private IP address and blocks the rest of the RDP traffic.
```

2023-02-05 09:02 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation.yml
> +        - 200 Azure rules viewed at once to find offending rule.
```suggestion
        - 200 Azure rules viewed at once to find the offending rule.
```

2023-02-05 09:06 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/README.md
> +Playbook that given the IP address enriches Azure information relevant to ASM alerts.
```suggestion
Given the IP address, this playbook enriches Azure information relevant to ASM alerts.	
```

2023-02-05 09:06 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_0.md
> +- Added an option for Azure in the automated remediation conditional.
```suggestion
Added an option for Azure in the automated remediation conditional.
```

2023-02-05 09:06 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_0.md
> +- Added the Cortex ASM - Azure Enrichment playbook as a remediation option.
```suggestion
Added the Cortex ASM - Azure Enrichment playbook as a remediation option.
```

2023-02-05 09:07 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_0.md
> +- Added the Azure Network Security Group Remediation playbook as a remediation option.
```suggestion
Added the Azure Network Security Group Remediation playbook as a remediation option.
```

2023-02-05 09:07 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_0.md
> +- Updated the GCP - Enrichment playbook task to skip this branch if this automation/playbook is unavailable.
```suggestion
Updated the GCP - Enrichment playbook task to skip this branch if this automation/playbook is unavailable.
```

2023-02-05 09:07 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_0.md
> +- Created a new playbook that takes in an IP address and enriches Azure information relevant to ASM alerts. (Available from Cortex XSOAR 6.5.0).
```suggestion
Created a new playbook that takes in an IP address and enriches Azure information relevant to ASM alerts. (Available from Cortex XSOAR 6.5.0).
```

2023-02-05 09:08 UTC, ShirleyDenkberg commented
@johnnywilkes @ilaner Doc review completed.

2023-02-09 13:54 UTC, merged