release notes
demisto/content pull request #24322
Opened 2023-02-03 15:53 UTC by ckaadic

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
In December the currently used alerts endpoint was moved to legacy and a new endpoint (v2) was released (see [List alerts](https://learn.microsoft.com/en-us/graph/api/security-list-alerts_v2?view=graph-rest-1.0&tabs=http) and [Get Alert](https://learn.microsoft.com/en-us/graph/api/security-alert-get?view=graph-rest-1.0&tabs=http)). I marked the current commands for get-alert-details and search-alerts as deprecated and added new commands for v2. The changes do not break backward compatibility, but the v2 endpoint does not provide exactly the same information as the legacy one.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [ ] Documentation

2023-02-03 15:53 UTC, ckaadic commented
Will be adding the documentation to the readme next week.

2023-02-05 08:49 UTC, adi88d commented
@ckaadic Please fille the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form

2023-02-06 09:41 UTC, ckaadic commented
@adi added the documentation to readme, fixed the lint/validate feedback

2023-02-08 12:29 UTC, adi88d requested changes
Hi @ckaadic and thank you for your contribution! it looks great!
- please add command examples for `msg-search-alerts-v2` and `msg-get-alert-details-v2`
- no need to deprecate the old commands, please revert

see my other comments below

2023-02-08 12:29 UTC, adi88d commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
> +    alert_details = client.get_alert_details(alert_id, alerts_v2)
```suggestion


    alert_details = client.get_alert_details(alert_id, True)
```

2023-02-08 12:29 UTC, adi88d commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
> +        'ActorDisplayName': alert_details['actorDisplayName'],
please use `get` for the other properties too and the context
```suggestion
        'ActorDisplayName': alert_details.get('actorDisplayName'),
```

2023-02-08 12:29 UTC, adi88d commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
> +                comments_hr += '- {}\n'.format(comment['comment'])
```suggestion
            for comment in comments:
                if comment.get('comment'):
                    comments_hr += '- {}\n'.format(comment['comment'])
```

2023-02-08 12:29 UTC, adi88d commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
> +    def search_alerts_v2(self, last_modified, severity, time_from, time_to, filter_query):
`search_alerts_v2` looks similar to `search_alerts` please try to change the `search_alerts` method by adding the parameter `use_alerts_v2=False` so it works for v1 and v2

2023-02-08 14:34 UTC, ckaadic commented
Hi @adi88d, validate wanted me to push image version again. Followed all your comments.

2023-02-08 16:39 UTC, adi88d requested changes
great job!

2023-02-08 16:39 UTC, adi88d commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
> +            'ID': alert['id'],
```suggestion
            'ID': alert.get('id'),
```

2023-02-08 16:39 UTC, adi88d commented on Packs/MicrosoftGraphSecurity/pack_metadata.json
> +    "currentVersion": "2.2.0",
please bump the version to 2.1.13
and change the `Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_0.md` file name to `Packs/MicrosoftGraphSecurity/ReleaseNotes/2_1_13.md`
```suggestion
    "currentVersion": "2.1.13",
```

2023-02-09 06:24 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: When the alert was last modified in the following string format - YYYY-MM-DD
```suggestion
      description: The date the alert was last modified in the following string format - YYYY-MM-DD
```

2023-02-09 06:25 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: The start time (creation time of alert) for the search in the following string format - YYYY-MM-DD
```suggestion
      description: The start time (creation time of the alert) for the search in the following string format - YYYY-MM-DD.
```

2023-02-09 06:25 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: The end time (creation time of alert) for the search in the following string format -  YYYY-MM-DD
```suggestion
      description: The end time (creation time of the alert) for the search in the following string format -  YYYY-MM-DD.
```

2023-02-09 06:26 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Use this field to filter on any of the alert properties in the format "{property} eq '{property-value}'", e.g. "assignedTo eq 'user1'"
```suggestion
      description: Filter on any of the alert properties in the format "{property} eq '{property-value}'", e.g., "assignedTo eq 'user1'".
```

2023-02-09 06:26 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert ID
```suggestion
      description: Alert ID.
```

2023-02-09 06:27 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert title
```suggestion
      description: Alert title.
```

2023-02-09 06:27 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert category
```suggestion
      description: Alert category.
```

2023-02-09 06:27 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert severity
```suggestion
      description: Alert severity.
```

2023-02-09 06:27 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert created date
```suggestion
      description: Alert created date.
```

2023-02-09 06:27 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert first activity time
```suggestion
      description: Alert first activity time.
```

2023-02-09 06:28 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert last activity time
```suggestion
      description: Alert last activity time.
```

2023-02-09 06:28 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert status
```suggestion
      description: Alert status.
```

2023-02-09 06:28 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert provider
```suggestion
      description: Alert provider.
```

2023-02-09 06:28 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert ID
```suggestion
      description: Alert ID.
```

2023-02-09 06:29 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert ID
```suggestion
      description: Alert ID.
```

2023-02-09 06:29 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert title
```suggestion
      description: Alert title.
```

2023-02-09 06:29 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert category
```suggestion
      description: Alert category.
```

2023-02-09 06:29 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert severity
```suggestion
      description: Alert severity.
```

2023-02-09 06:29 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert created date
```suggestion
      description: Alert created date.
```

2023-02-09 06:30 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert first associated activity time
```suggestion
      description: Alert first associated activity time.
```

2023-02-09 06:30 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert latest associated activity time
```suggestion
      description: Alert latest associated activity time.
```

2023-02-09 06:30 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert status
```suggestion
      description: Alert status.
```

2023-02-09 06:30 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: Alert provider
```suggestion
      description: Alert provider.
```

2023-02-09 06:30 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +      description: The Alert ID - Provider-generated GUID/unique identifier.
```suggestion
      description: The alert ID. Provider-generated GUID/unique identifier.
```

2023-02-09 06:31 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
> +| severity | Alert severity - set by vendor/provider. Possible values are: unknown, informational, low, medium, high. | Optional |
```suggestion
| severity | Alert severity set by the vendor/provider. Possible values are: unknown, informational, low, medium, high. | Optional | 
```

2023-02-09 06:32 UTC, ShirleyDenkberg commented
@adi88d Doc review completed.

2023-02-12 13:00 UTC, adi88d commented
Hello,
Your contribution is much appreciated. However, this endpoint it is not consistent with the API of this integration, and we will open an internal ticket to add it to the `Microsoft Graph Security` integration.
thanks again

2023-02-12 13:00 UTC, closed without merging

2023-02-14 10:10 UTC, ckaadic commented
Hi @adi88d is there a way for me to track the progress?

2023-03-02 14:20 UTC, ShacharKidor commented
Hi @ckaadic, 
I really apologize for the delay in response. 
@adi88d will contact you soon with explanations. 
Please reach out to me if you'll have more questions or need anything - available on Slack (DFIR). 

FYI - @Mark-Hillenaar.