Neosec fix time format bug
demisto/content pull request #24337
Opened 2023-02-05 10:13 UTC by gala-neosec

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-06 12:06 UTC, adi88d commented
@gala-neosec  Please fille the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form

2023-02-08 15:55 UTC, arsenyk-neosec commented
> 

@adi88d i submitted the form

2023-02-08 16:13 UTC, adi88d requested changes
Hi @gala-neosec and thank you for your contribution!
Good work :)

Please bump the version of the pack in the pack_metadata.json file and add notes describing your changes to a new Release Notes file. 
To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

2023-02-08 16:13 UTC, adi88d commented on Packs/Neosec/Integrations/Neosec/Neosec.py
> +        alert_timestamp = dateparser.parse(alert["timestamp"])
```suggestion
        alert_timestamp = dateparser.parse(alert.get("timestamp"))
```

2023-02-09 10:40 UTC, adi88d approved these changes
nice!

2023-02-09 10:40 UTC, merged