Microsoft Graph Mail Single User - Support Update of Refresh token from Integration Parameters
demisto/content pull request #24347
Opened 2023-02-05 13:34 UTC by ShacharKidor

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-08 18:05 UTC, ShacharKidor commented
@yuvalbenshalom, @yucohen - Please start the review. 

* The change in **MicrosoftGraphMail** is temporary (I made it only for triggering the TPBs of this integration to make sure that they pass successfully on instances of both self-deployed and Oproxy auth). 
* *  Will update the RN of all the packs that use the MicrosoftAPIModule when we will finish the review process (to prevent conflicts).

2023-02-09 11:53 UTC, yuvalbenshalom requested changes
looks good, see my comments

2023-02-09 12:05 UTC, yucohen approved these changes
Looks good from my side🙃

2023-02-09 14:15 UTC, ShacharKidor commented on Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.py
> +        # refresh_token_param).
Definitely better! will change that, thanks.

2023-02-09 16:55 UTC, yuvalbenshalom approved these changes

2023-02-12 15:35 UTC, merged