EWS O365 version using MSAL lib for ROPC flow
demisto/content pull request #24359
Opened 2023-02-06 00:28 UTC by hiep4hiep

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation 

## Docker image required
/docker_image_create name=demisto-ews-msal:2.1 base="demisto/py3ews:1.0.0.45234" dependencies=msal,urllib3==1.26.8

2023-02-13 08:13 UTC, adi88d requested changes
Hi @hiep4hiep ,Thank you for your contribution!

- Please update the **CrowdStrikeFalcon/README.md** file with the commands you added, 
To do that, please run the `demisto-sdk generate-docs` command (use the -e flag for using a commad_examples file) - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#generate-docs.
- see my other comments below

2023-02-13 08:13 UTC, adi88d commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +        raw_res = get_spotlight_vulnerabilities_list(after=None, limit=1000, time_range='now-1m')
```suggestion
        raw_res = get_spotlight_vulnerabilities_list(after= after, limit=limit, time_range= time_range)
```

2023-02-13 08:13 UTC, adi88d commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
> +
remove the empty line
```suggestion
```

2023-02-13 08:13 UTC, adi88d commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    vul_id = str(args.get('vul_id'))
there is no argument with the name `vul_id`
```suggestion
    vul_id = str(args.get('change_id'))
```

2023-02-13 08:13 UTC, adi88d commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
> +                    "local_ip":"192.000.0.2",
```suggestion
                    "local_ip":"127.0.0.1",
```

2023-02-13 08:13 UTC, adi88d commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
> +                    "http://www.live.com/liveMedia/public/changelog.txt"
```suggestion
                    "http://www.test.com/liveMedia/public/changelog.txt"
```

2023-02-13 16:58 UTC, adi88d requested changes
For the EWS_MSAL integration:
- please use CommandResults in the command methods.
- add `example.txt` file with examples to all the commands
- add test playbook

2023-02-13 16:58 UTC, adi88d commented on Packs/EWS/Integrations/EWS_MSAL/EWS_MSAL.py
> +#
remove
```suggestion

```

2023-02-13 16:58 UTC, adi88d commented on Packs/EWS/Integrations/EWS_MSAL/EWS_MSAL.py
> +import os
remove unused code
```suggestion

```

2023-02-13 16:58 UTC, adi88d commented on Packs/EWS/Integrations/EWS_MSAL/EWS_MSAL.py
> +from MicrosoftApiModule import *  # noqa: E402
move to the top
```suggestion
from MicrosoftApiModule import *  # noqa: E402
```

2023-02-13 16:58 UTC, adi88d commented on Packs/EWS/Integrations/EWS_MSAL/EWS_MSAL.py
> +        demisto.debug(f'memstat\n{str(subprocess.check_output(["ps", "-opid,comm,rss,vsz"]))}')
move this method

2023-02-13 23:54 UTC, hiep4hiep commented
Hi @adi88d , apologize for the mixed up as I am not intended to push the CrowStrikeFalcon pack to this PR because it is the other work in progress.
The content I wanted push is only EWS_MSAL. Please help review that one instead.
Thank you.

2023-02-13 23:57 UTC, hiep4hiep commented on Packs/EWS/Integrations/EWS_MSAL/EWS_MSAL.py
> +    def parse_element(element):
Hi @adi88d , this method is from the OOTB version. I did not modify anything.

2023-02-13 23:57 UTC, hiep4hiep commented on Packs/EWS/Integrations/EWS_MSAL/EWS_MSAL.py
> +        if str(e) != "must be string or buffer, not None":
Hi @adi88d , this method is from the OOTB version. I did not modify anything.

2023-02-16 13:55 UTC, adi88d commented
@hiep4hiep we decided to accept your contribution as community support, please change the pull request:
- create new pack with community support level for the **EWS MSAL** integration and revert all the changes in **CrowdStrikeFalcon** and **EWS** packs

2023-02-22 21:35 UTC, hiep4hiep commented
Hi @adi88d , I have deleted the CrowdStrikeFalcon and added EWS-MSAL as a community pack. Please help review. Thank you.

2023-02-26 11:52 UTC, adi88d requested changes
Hi @hiep4hiep
- please revert the changes in **CrowStrikeFalcon** pack - you deleted it instead
- delete this image `Packs/EWS-MSAL/Author_image.png`
- solve my other comments

2023-02-26 11:52 UTC, adi88d commented on Packs/EWS-MSAL/Integrations/EWS_MSAL/EWS_MSAL.py
> +def log_memory():
move this method before the main

2023-02-26 11:52 UTC, adi88d commented on Packs/EWS-MSAL/Integrations/EWS_MSAL/EWS_MSAL.py
> +from MicrosoftApiModule import *  # noqa: E402
move to the top

2023-02-26 11:52 UTC, adi88d commented on Packs/EWS-MSAL/Integrations/EWS_MSAL/EWS_MSAL.py
> +
remove

2023-03-12 16:07 UTC, adi88d commented
Hi @hiep4hiep,
Thank you for your contribution.
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue.
Thanks again.

2023-03-12 16:07 UTC, closed without merging