Add get prevalence command to core 2 (#23552)
demisto/content pull request #24367
Opened 2023-02-06 11:55 UTC by RosenbergYehuda

* Added get prevalence to PB

* Added get prevalence to PB

* Added get prevalence to PB

* Added get prevalence to PB

* Added get prevalence to PB

* Added get prevalence to PB

* Updated release notes

* fixed validation error

* Added DBotScore to verdict conditional task

* Added DBotScore to verdict conditional task

* Update playbook-AWS_IAM_User_Access_Investigation.yml

* updated get prevalence with dbot score

* updated release notes

* rollback

* Update QRadar_v3-test.yml

* Update playbook-SMB_test.yml

* Update 1_3_16.md

* updated release notes

* fixed conditional task logic

* removed changes

* removed changes

* Update 1_3_24.md

* removed prevalence check from PB

* remove prevalence check from playbook

* moved prevalence check to non malicious path

* updated release notes

* fixed comment and updated PB image

* updated release notes

* changed to original command instead of decoded

* removed changes for ransomware PB

* removed changes for rnasomware PB

* fixed validations

* updated release notes

* updated release notes

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-13 07:19 UTC, ShirleyDenkberg commented on Packs/Core/ReleaseNotes/1_4_0.md
> +- Added A new command.
```suggestion
Added the ***xdr-endpoint-alias-change*** command that gets a list of endpoints according to the passed filters, and changes their alias name.
```

2023-02-13 07:45 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: Gets a list of endpoints according to the passed filters, and changes their alias name. Filtering by multiple fields will be concatenated using AND condition (OR is not supported).
```suggestion
      description: Gets a list of endpoints according to the passed filters, and changes their alias name. Filtering by multiple fields will be concatenated using the AND condition (OR is not supported).
```

2023-02-13 07:47 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +            The group name to which the agent belongs.
```suggestion
            A comma-separated list of group names to which the agent belongs.
```

2023-02-13 07:48 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +        - description: 'The endpoint platform. Valid values are\: "windows", "linux", "macos", or "android". '
```suggestion
        - description: 'A comma-separated list of endpoint platforms. Valid values are\: "windows", "linux", "macos", or "android". '
```

2023-02-13 07:58 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +            Hostname
```suggestion
            A comma-separated list of hostnames.
```

2023-02-13 08:15 UTC, JasBeilin requested changes
Nice. Please check my comments.
1. Make sure you understand the meaning of the first_seen_XXX. 
2. Note the changes in the playbook looks like mistake, please  revert the parts you did not intend to change and keep only those you did.
3. Are you using the black or other formatter? When adding code to existing packs we do not use it as it seems like you changes *a lot* of lines that you did not touch.

2023-02-13 08:15 UTC, JasBeilin commented on Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml
> -fromversion: 5.0.0
Why was this removed?

2023-02-13 08:15 UTC, JasBeilin commented on Packs/CortexXDR/pack_metadata.json
> +    "currentVersion": "4.11.0",
Why minor?

2023-02-13 08:53 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +            All the agents that were last seen before {last_seen_gte}.
```suggestion
            All the agents that were last seen after  {last_seen_gte}.
```

2023-02-13 08:56 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +          description: The usernames to query for, accepts a single user, or comma-separated list of usernames.
```suggestion
          description: The usernames to query for. Accepts a single user, or comma-separated list of usernames.
```

2023-02-13 08:56 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +          description: The requested alias name to change to.
```suggestion
          description: The alias name to change to.
```

2023-02-13 09:08 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| group_name | The group name to which the agent belongs.<br/>Example: group_name1,group_name2. | Optional |
```suggestion
| group_name | A comma-separated list of group names to which the agent belongs.<br/>Example: group_name1,group_name2. | Optional | 
```

2023-02-13 09:09 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| platform | The endpoint platform. Valid values are\: "windows", "linux", "macos", or "android". . Possible values are: windows, linux, macos, android. | Optional |
```suggestion
| platform | A comma-separated list of endpoint platforms. Possible values are: windows, linux, macos, android. | Optional | 
```

2023-02-13 09:09 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| hostname | Hostname<br/>Example: hostname1,hostname2. | Optional |
```suggestion
| hostname | A comma-separated list of hostnames.<br/>Example: hostname1,hostname2. | Optional | 
```

2023-02-13 09:10 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| last_seen_gte | All the agents that were last seen before {last_seen_gte}.<br/>Supported values:<br/>1579039377301 (time in milliseconds)<br/>"3 days" (relative date)<br/>"2019-10-21T23:45:00" (dat
```suggestion
| last_seen_gte | All the agents that were last seen after {last_seen_gte}.<br/>Supported values:<br/>1579039377301 (time in milliseconds)<br/>"3 days" (relative date)<br/>"2019-10-21T23:45:00" (date). | Optional | 
```

2023-02-13 09:11 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| username | The usernames to query for, accepts a single user, or comma-separated list of usernames. | Optional |
```suggestion
| username | The usernames to query for. Accepts a single user, or comma-separated list of usernames. | Optional | 
```

2023-02-13 09:12 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +Gets a list of endpoints according to the passed filters, and changes their alias name. Filtering by multiple fields will be concatenated using AND condition (OR is not supported).
```suggestion
Gets a list of endpoints according to the passed filters, and changes their alias name. Filtering by multiple fields will be concatenated using the AND condition (OR is not supported).
```

2023-02-13 09:13 UTC, ShirleyDenkberg commented on Packs/CortexXDR/ReleaseNotes/4_11_0.md
> +- Added a new command, ***xdr-endpoint-alias-change***.
```suggestion
- Added  the ***xdr-endpoint-alias-change*** command.
```

2023-02-13 09:14 UTC, ShirleyDenkberg commented
@JasBeilin Doc review completed.

2023-02-13 14:14 UTC, JasBeilin requested changes
Make sure to check the flow Binat used.

2023-02-14 07:55 UTC, JasBeilin commented on Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
> +    assert mocker_set.call_args[1] == {'filters': [{'field': 'endpoint_status',
What happens when no filters were provided? lets add this usecase to the test.

2023-02-14 07:56 UTC, JasBeilin reviewed
Please add gracefully handling when no filters are provided.

2023-02-14 10:25 UTC, JasBeilin commented on Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
> +        raise DemistoException('No filters were given')
```suggestion
        raise DemistoException('Please provide at least one filter.')
```

2023-02-14 10:26 UTC, JasBeilin commented on Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
> +    assert e.value.message == 'No filters were given'
```suggestion
    assert e.value.message == 'Please provide at least one filter.'
```

2023-02-16 13:42 UTC, JasBeilin commented on Packs/Core/ReleaseNotes/1_3_31.md
> +Added the ***core-endpoint-alias-change*** command that gets a list of endpoints according to the passed filters, and changes their alias name.
```suggestion
- Added the ***core-endpoint-alias-change*** command that gets a list of endpoints according to the passed filters, and changes their alias name.
```

2023-02-16 13:46 UTC, JasBeilin reviewed
Great work. Please see my comments.

2023-02-18 08:26 UTC, JasBeilin commented on Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
> +    and in the second case the new alias name is a string of only double quotes.
you can just use this format next time, as docstrings are meant to be short and exact:

Given:
    - valid new alias name as string
    - empty new alias name (due to xsoar limitation, represented by a string of double quote)
    
   Then:
       Makes sure the request body is created correctly.

2023-02-18 08:26 UTC, JasBeilin approved these changes
Great job!

2023-02-19 08:36 UTC, merged