Fix get_dbotscore()
demisto/content pull request #24409
Opened 2023-02-07 09:13 UTC by mohlcyber

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
CP Threat Emulation provides a lower case combinedverdict like "benign". Previous code always set DBot Score to malicious also when it CP Threat Emulation returned a benign verdict. Code change fixes the DBot Score. Code Fix line 849.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2023-02-07 09:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=24409) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=24409) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=24409) it.</sub>

2023-02-09 16:41 UTC, adi88d requested changes
Hi @mohlcyber ,
Thank you for your contribution!
Good work :)

Please bump the version of the pack in the pack_metadata.json file and add notes describing your changes to a new Release Notes file. 
To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

2023-02-10 16:02 UTC, mohlcyber commented
Hi @adi88d,
thanks for the prompt response. I did the required changes. Hope that works out.
All the best,
Martin

2023-02-12 08:01 UTC, adi88d approved these changes

2023-02-12 08:01 UTC, merged