YUG-4241: Added new automation GRAAnomaliesDisplay.py, Corrected desc…
demisto/content pull request #24502
Opened 2023-02-09 06:58 UTC by Sudhi108

…riptions of all commands, fixed some typo errors in description.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-14 11:02 UTC, adi88d commented
@Sudhi108 please fill the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form

2023-02-14 11:06 UTC, Sudhi108 commented
@adi88d I had filled earlier also when submitted the pull request and filled it again now. 
Thanks.

2023-02-14 17:00 UTC, adi88d requested changes
Hi @Sudhi108,
Thank you for your contribution!
Good work :)
see my comments below

2023-02-15 08:29 UTC, Sudhi108 commented on Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.py
> +            # print(base_url)
removed

2023-02-15 08:29 UTC, Sudhi108 commented on Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
> +      type: Unknown
added context path to all outputs

2023-02-15 08:30 UTC, Sudhi108 commented on Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
> +      description: GRA Case Id
added required tag

2023-02-15 08:30 UTC, Sudhi108 commented on Packs/Gurucul/Integrations/GuruculGRA/README.md
> +|Gra.Cases.anomalies | Grid     | GRA Case Anomalies |
done

2023-02-15 08:31 UTC, Sudhi108 commented on Packs/Gurucul/ReleaseNotes/2_0_0.md
> +- The new anomalies will then be synced with XSOAR
If I remove this, it shows as one message

2023-02-15 08:32 UTC, Sudhi108 commented on Packs/Gurucul/Scripts/GRAAnomaliesDisplay/GRAAnomaliesDisplay.py
> +    incident = _get_incident()
fixed

2023-02-15 08:32 UTC, Sudhi108 commented on Packs/Gurucul/Scripts/GRAAnomaliesDisplay/README.md
> +| Cortex XSOAR Version | 6.5.0 |
fixed

2023-02-15 08:34 UTC, Sudhi108 commented
Hi @adi88d,

Thank you for such a detailed review.
I have made the changes as per your comments and pushed in git.

2023-02-15 15:02 UTC, adi88d commented on Packs/Gurucul/ReleaseNotes/2_0_0.md
> +- The new anomalies will then be synced with XSOAR
@Sudhi108 it looks the same:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/46249224/219064935-6c5f5dc6-bd0f-4c62-987b-43aa8077a888.png">

2023-02-15 15:03 UTC, adi88d commented
Nice

> Hi @adi88d,
> 
> Thank you for such a detailed review. I have made the changes as per your comments and pushed in git.

just update the file `Packs/Gurucul/ReleaseNotes/2_0_0.md` and we good to go

2023-02-15 15:37 UTC, adi88d approved these changes

2023-02-15 15:37 UTC, merged