Infoblox BloxOne Threat Defense
demisto/content pull request #24556
Opened 2023-02-12 12:22 UTC by esharf

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4728

## Description
added a new integration *Infoblox BloxOne Threat Defense*

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-15 15:51 UTC, DeanArbel requested changes
Mostly looks ok, please note the images need to be updated.
Please add tests.

2023-02-15 15:51 UTC, DeanArbel commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.py
> +            _filter = f'detected_at>="{detected_at}"'
Can't the filter be used with more than one filter value?
If not, please mention it in the description.

2023-02-15 15:51 UTC, DeanArbel commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.py
> +            raise ValueError("You must spesify one of the following arguments 'target_domain', 'detected_at' or 'filter'.")
```suggestion
            raise ValueError("Please provide one of the following arguments 'target_domain', 'detected_at' or 'filter'.")
```

2023-02-15 15:51 UTC, DeanArbel commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.py
> +            raise ValueError("You can spesify one of the following arguments 'target_domain', 'detected_at' or 'filter' not more.")
```suggestion
            raise ValueError("Exactly one of the following arguments must be provided 'target_domain', 'detected_at' or 'filter'. No more than one is argument is accepted")
```

2023-02-15 15:51 UTC, DeanArbel commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.py
> +        readable_output='Job is still running, it may take a little while...',
If you remove this part, there won't be any print after the first execution. Please consider avoiding further prints after the first one.

2023-02-15 15:51 UTC, DeanArbel commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/test_data/baseintegration-dummy.json
> +{
???

2023-02-16 14:59 UTC, esharf commented
i have fixed the comments.
still need to add Tests and Docs

2023-02-21 13:39 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +description: 'BloxOne Threat Defense is a hybrid cybersecurity solution that leverages DNS as the first line of defense to detect and block cyber threats.'
```suggestion
description: BloxOne Threat Defense is a hybrid cybersecurity solution that leverages DNS as the first line of defense to detect and block cyber threats.
```

2023-02-21 13:40 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The sources to query. Multiple sources can be specified, if no source is specified, the call will search on all available sources. (you can see the list of the available sources b
```suggestion
      description: 'The sources to query. Multiple sources can be specified. If no source is specified, the call will search on all available sources. (You can see the list of the available sources by running bloxone-td-dossier-source-list).'
```

2023-02-21 13:41 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The targeted indicator.'
```suggestion
      description: The targeted indicator.
```

2023-02-21 13:41 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The Dossier task id.'
```suggestion
      description: The Dossier task ID.
```

2023-02-21 13:41 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The indicator type.'
```suggestion
      description: The indicator type.
```

2023-02-21 13:42 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +    description: 'Get available Dossier sources.'
```suggestion
    description: Get available Dossier sources.
```

2023-02-21 13:42 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'Available Dossier sources.'
```suggestion
      description: Available Dossier sources.
```

2023-02-21 13:44 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The free query filter argument.'
```suggestion
      description: The free query filter argument.
```

2023-02-21 13:46 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'Maximum number of results to return from the query. Default is 50.'
```suggestion
      description: Maximum number of results to return from the query. 
```

2023-02-21 13:47 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'Return results starting at this offset. should be int - by default is 0'
```suggestion
      description: Return results starting at this offset. Should be an integer. Default is 0.
```

2023-02-21 13:47 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +    description: 'Get Lookalike Domain Lists.'
```suggestion
    description: 'Get Lookalike domain lists.'
```

2023-02-21 13:48 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The lookalike domain.'
```suggestion
      description: The lookalike domain.
```

2023-02-21 13:49 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The lookalike host.'
```suggestion
      description: The lookalike host.
```

2023-02-21 13:49 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The reason of the detection.'
```suggestion
      description: The reason for the detection.
```

2023-02-21 13:49 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
> +      description: 'The domain that was targeted by the lookalike domain.'
```suggestion
      description: The domain that was targeted by the lookalike domain.
```

2023-02-21 13:52 UTC, ShirleyDenkberg commented on Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense_description.md
> +  - **Service User**: Enter the name of the service users or choose one from the drop-down list. You can associated up to 10 service API keys per service user.
```suggestion
  - **Service User**: Enter the name of the service users or choose one from the drop-down list. You can associate up to 10 service API keys per service user.
```

2023-02-21 13:53 UTC, ShirleyDenkberg commented
@esharf You need to create the integration readme and the pack readme.  Let me know when these are done and I will review them.

2023-02-26 18:51 UTC, DeanArbel approved these changes
Great job, just a couple of notes

2023-02-28 11:56 UTC, merged