[Azure Active Directory Groups] authorization_code support
demisto/content pull request #24698
Opened 2023-02-17 14:05 UTC by ennozdd

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ x ] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-20 15:02 UTC, yucohen requested changes
@ennozdd Thanks for your contribution! Great work!
1. Lets not change the API module and try to handle all the changes in the integration code itself.
2. Why is the scopes parameter is needed? The endpoints we reach in the integration are determined, so therefore we can 'hardcode' the scope.

2023-02-21 06:52 UTC, ennozdd commented
> @ennozdd Thanks for your contribution! Great work!
> 
>     1. Lets not change the API module and try to handle all the changes in the integration code itself.
> 
>     2. Why is the scopes parameter is needed? The endpoints we reach in the integration are determined, so therefore we can 'hardcode' the scope.

hardcoding in my understanding might give the app more permission than necessary, for example an administrator might want to give permission only to add/remove members from a group or just read access for that matter. If hardcoding is a standard for scope handling that's fine I can revert that change.

2023-02-21 10:24 UTC, yucohen commented
@ennozdd We actually using the default scope in the API module for the login url (you can see [this microsoft docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/scopes-oidc#the-default-scope) 
So lets revert this change
If you need help or any consultation please reach out here, or on slack (you can also e-mail me at yucohen@paloaltonetworks.cpm)

2023-02-21 14:33 UTC, yucohen approved these changes

2023-02-21 14:33 UTC, merged