IPQualityScore Encoding and Results Bug Fixes
demisto/content pull request #24701
Opened 2023-02-18 03:06 UTC by IPQSDemisto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Bug fixes for two issues:
- The URL lookup functionality currently doesn't pull the correct value. It should pull risk_score instead of fraud_score.
- The Email lookup functionality did not URL encode all emails. This could lead to malformed results. The Email lookup functionality now encodes all emails.

## Screenshots
N/A

## Minimum version of Cortex XSOAR
- [ x ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-20 08:22 UTC, daryakoval requested changes
@IPQSDemisto Hi, 
1. Make sure to register your contribution by filling out the contribution registration form at https://forms.gle/XDfxU4E61ZwEESSMA
2. please add release notes and bump pack version. 
3. please fix test_email_command that fails after your changes.
4. The docker image tag is not the latest numeric tag, please update it to: 3.10.10.48392

2023-03-05 08:05 UTC, daryakoval commented
@IPQSDemisto Hi, please address the notes I added [here.](https://github.com/demisto/content/pull/24701#pullrequestreview-1305281699)

2023-03-05 19:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=24701) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=24701) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: IPQualityScore<br/>:x: IPQSDemisto<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=24701) it.</sub>

2023-03-05 22:01 UTC, IPQSDemisto commented
1. Done.
2. Done.
3. Done.
4. Done.

2023-03-06 08:36 UTC, daryakoval approved these changes

2023-03-06 08:41 UTC, merged