prepare testing bucket fix SDK nightly
demisto/content pull request #24755
Opened 2023-02-20 18:16 UTC by ilaner

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Fix prepare testing bucket to run on SDK nightly

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-21 11:59 UTC, YuvHayun approved these changes

2023-02-22 06:25 UTC, esharf requested changes
it looks that the create instances step is running twice
- https://code.pan.run/xsoar/content/-/jobs/22089347#L4568
- https://code.pan.run/xsoar/content/-/jobs/22089347#L4630

please check it

2023-02-22 09:09 UTC, ilaner commented
> it looks that the create instances step is running twice
> 
> * https://code.pan.run/xsoar/content/-/jobs/22089347#L4568
> * https://code.pan.run/xsoar/content/-/jobs/22089347#L4630
> 
> please check it

Fixed.
Retriggered SDK nightly: https://code.pan.run/xsoar/content/-/pipelines/4665912

2023-02-28 12:53 UTC, ilaner commented
Updated demisto-sdk nightly:
https://code.pan.run/xsoar/content/-/pipelines/4710044

2023-03-06 12:39 UTC, esharf approved these changes

2023-04-30 14:21 UTC, merged