[Deprecation Management] Detonate URL - Generic playbook fix
demisto/content pull request #24774
Opened 2023-02-21 13:50 UTC by samuelFain

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-22 17:55 UTC, ShacharKidor requested changes
@samuelFain - Nice :)

2023-02-22 17:55 UTC, ShacharKidor commented on Packs/CommonPlaybooks/ReleaseNotes/2_3_40.md
> +- Fixed an issue where the wrong sub-playbook was removed from the playbook.
```suggestion
- Fixed an issue where the **Detonate URL - CrowdStrike Falcon Intelligence Sandbox** sub-playbook was unnecessarily removed.
- Removed the deprecated **Detonate URL - CrowdStrike** sub-playbook. 
```

2023-02-22 17:55 UTC, ShacharKidor commented on Packs/CrowdStrikeFalconX/pack_metadata.json
> +}
Please revert this change.

2023-02-23 09:31 UTC, samuelFain commented on Packs/CrowdStrikeFalconX/pack_metadata.json
> +}
Done.

2023-02-23 09:31 UTC, samuelFain commented on Packs/CommonPlaybooks/ReleaseNotes/2_3_40.md
> +- Fixed an issue where the wrong sub-playbook was removed from the playbook.
Done.

2023-02-23 11:28 UTC, merged