Added code for Securonix Release 200
demisto/content pull request #24771
Opened 2023-02-21 13:11 UTC by scnx-knathani

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-02-21 13:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=24771) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=24771) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=24771) it.</sub>

2023-02-26 07:34 UTC, yucohen commented on Packs/Securonix/Integrations/Securonix/test_data/result_constants.py
> +            "Eventid": "3ae64498-1b89-44d7-aa14-6dc72af814bf",
are those real ID's? If so, lets change those to dummy values.

2023-02-26 10:36 UTC, efelmandar commented
@scnx-knathani Thank you for submitting your contribution! I've reviewed your PR and have identified a few areas that I would like you to consider before merging. 

1. To avoid creating duplicate fields, please use existing incident fields from the "commonTypes" pack where possible. for example: `Tenant Name` field already exist in `CommonTypes` and can be used instead of creating new one
2. The current configuration of the "incidentTypes" is not using the auto-extract function, which is usually not recommended. it might be useful if you are sure the fields in the response won't contain indicators to enrich, but usually it only apply for specific fields
3. Since there are two incident types, we recommend adding a classifier to automate the incident type classification. This will help ensure accuracy and efficiency. 

We appreciate your efforts and look forward to your response.

2023-02-26 12:06 UTC, yucohen requested changes
Thanks for your contribution! Please see my comments

2023-02-27 07:22 UTC, scnx-knathani commented on Packs/Securonix/Integrations/Securonix/test_data/result_constants.py
> +            "Eventid": "3ae64498-1b89-44d7-aa14-6dc72af814bf",
Done, changed to dummy value.

2023-02-27 07:22 UTC, scnx-knathani commented on Packs/Securonix/README.md
> +
Updated description.

2023-02-27 07:23 UTC, scnx-knathani commented on Packs/Securonix/Integrations/Securonix/Securonix.py
> +    TOTAL_RETRY_COUNT = arg_to_number(params.get('securonix_retry_count', '0'),  # type: ignore
Agree, added validation for the same.

2023-02-27 07:23 UTC, scnx-knathani commented on Packs/Securonix/Integrations/Securonix/Securonix.py
> +                reason = 'Reason: {}'.format(exception.args[0].reason.args[0])  # pylint: disable=no-member
Done, Changed to f-strings wherever required.

2023-02-27 07:25 UTC, scnx-knathani commented
> @scnx-knathani Thank you for submitting your contribution! I've reviewed your PR and have identified a few areas that I would like you to consider before merging.
> 
> 1. To avoid creating duplicate fields, please use existing incident fields from the "commonTypes" pack where possible. for example: `Tenant Name` field already exist in `CommonTypes` and can be used instead of creating new one
> 2. The current configuration of the "incidentTypes" is not using the auto-extract function, which is usually not recommended. it might be useful if you are sure the fields in the response won't contain indicators to enrich, but usually it only apply for specific fields
> 3. Since there are two incident types, we recommend adding a classifier to automate the incident type classification. This will help ensure accuracy and efficiency.
> 
> We appreciate your efforts and look forward to your response.

Hey @efelmandar,

1. That's a good catch, used the existing Tenant Name field available in Common Types packs.
2. Updated incident types to auto-extract all the available indicators if any.
3. In this case, Both incident types are fetched from different APIs, having a different set of fields and not a single common field that's why we have not used a classifier for bifurcating incident types.

2023-02-27 07:28 UTC, scnx-knathani commented
Hello @efelmandar @yucohen, 

We have resolved/replied to all the review comments. Please let us know if there are more changes required.

2023-03-01 10:18 UTC, scnx-knathani commented
Hello @efelmandar @yucohen @edik24 

We have resolved all the review comments based on your comments in yesterday's demo. 
Please let us know if there are any more suggestions.

2023-03-02 08:59 UTC, yucohen approved these changes

2023-03-02 09:00 UTC, merged