Change the pack category `Messaging` to `Messaging and Conferencing`
demisto/content pull request #24852
Opened 2023-02-23 13:31 UTC by maimorag

## Status
- [x] In Progress

## Related Issues
fixes: N/A

## Description
Change the pack category `Messaging` to `Messaging and Conferencing`. e.g packs: Slack, Microsoft Teams, Zoom.

## Minimum version of Cortex XSOAR
- [X] 6.0.0

## Does it break backward compatibility?
- [X] No

2023-03-01 10:57 UTC, Shellyber requested changes

2023-03-01 10:57 UTC, Shellyber commented on Packs/Kafka/ReleaseNotes/2_0_5.md
> +##### Kafka v2 (Deprecated)
Again no need to update deprecated content

2023-03-01 10:57 UTC, Shellyber commented on Packs/MicrosoftExchangeOnPremise/ReleaseNotes/1_0_3.md
> +- Updated the Docker image to *demisto/py-ews:1.0.0.49071*.
Revert this file

2023-03-01 10:57 UTC, Shellyber commented on Packs/Slack/ReleaseNotes/3_1_24.md
> +##### Slack v2 (Deprecated)
Same as above

2023-03-01 10:57 UTC, Shellyber commented on Packs/Telegram/Integrations/Telegram/Telegram.yml
> +display: Telegram_Beta (Beta)
Why did you add the beta to the display?

2023-03-01 13:14 UTC, Shellyber approved these changes

2023-03-05 11:42 UTC, maimorag commented
The validation error is :
Packs/Twilio/Integrations/Twilio/Twilio.yml - [IN140]

Therefore force merge is needed, @DeanArbel can you force merge?

2023-03-05 11:48 UTC, Shellyber requested changes

2023-03-05 11:48 UTC, Shellyber commented on Packs/MailListener/ReleaseNotes/1_0_31.md
> +- Updated the pack category to *Messaging and Conferencing*.
@maimorag Please add here the docker image update also

2023-03-05 11:48 UTC, Shellyber commented on Packs/Zoom/ReleaseNotes/1_2_6.md
> +Updated the pack category to *Messaging and Conferencing*.
Here as well

2023-03-05 17:34 UTC, merged