Removing all packs that are not PANW products and that require settin…
demisto/content pull request #24992
Opened 2023-03-02 10:07 UTC by maimorag

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5744

## Description
 removing all packs that are not PANW products and that require setting up an instance:
- UrlScan.zip
- FeedTAXII.zip
- Active_Directory_Query.zip
- VirusTotal.zip
- ipinfo.zip

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.0.0

## Does it break backward compatibility?
   - [x] No

2023-03-02 10:11 UTC, ShahafBenYakir requested changes
Before merging this PR need to make sure there are no dependencies that are outside of the core packs list.

2023-03-02 13:59 UTC, Shellyber requested changes

2023-03-02 13:59 UTC, Shellyber commented on Tests/Marketplace/core_packs_mpv2_list.json
>      "Phishing",
@maimorag We Need to remove from MPv2 Phishing as well.
See the ticket comments

2023-03-05 08:02 UTC, Shellyber commented on Tests/Marketplace/core_packs_mpv2_list.json
>      "Phishing",
Also what about the Phishing here?

2023-03-05 13:38 UTC, maimorag commented
verified using the UI and also the graph using the following queries:

MATCH (p:Pack {object_id:“**_pack that stays_**”})-[:DEPENDS_ON {mandatorily: true}]-(n)
WHERE n.deprecated IS NULL AND n.object_id IN [“UrlScan”, “FeedTAXII”, “Active_Directory_Query”, “VirusTotal”, “ipinfo”]
RETURN n.object_id

MATCH (p:Pack {object_id:“**_trimmed pack_**”})<-[:DEPENDS_ON {mandatorily: true, is_test: false, marketplaces: ‘marketplacev2’}]-(n) where n.deprecated is null
RETURN n.object_id

2023-03-05 13:41 UTC, Shellyber approved these changes

2023-03-06 08:22 UTC, ShahafBenYakir commented
@maimorag what is **trimmed pack**? 
Let's also do: 
```
MATCH (p:Pack {object_id:“pack that stays”})-[:DEPENDS_ON {mandatorily: true}]->(n)
WHERE n.deprecated IS NULL
RETURN n.object_id
```
It is without the list of packs you removed.
Go over the resulting list and make sure each item is a core pack.

2023-03-06 09:16 UTC, maimorag commented
@ShahafBenYakir trimmed packs are one of the following:[“UrlScan”, “FeedTAXII”, “Active_Directory_Query”, “VirusTotal”, “ipinfo”].

Also, I run the query, and each item is a core pack.

2023-03-06 12:20 UTC, ShahafBenYakir approved these changes

2023-03-06 13:07 UTC, merged