Email notif expandr 3032
demisto/content pull request #25036
Opened 2023-03-04 02:12 UTC by BigEasyJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-3032](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3032)

## Description
Update the Cortex ASM - ASM Alert playbook with a task at the end of the "Remediation Stage" to send a remediation notification email to service owners.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details:
   - [ ] No

## Must have
- [x] Tests
- [x] Documentation

2023-03-04 02:21 UTC, BigEasyJ commented
Please do not merge until review/acceptance from @johnnywilkes or @capanw.

2023-03-07 14:45 UTC, daryakoval commented
@BigEasyJ Hi, Is the pr ready for @capanw and @johnnywilkes review?

2023-03-07 17:24 UTC, capanw approved these changes

2023-03-07 22:34 UTC, johnnywilkes requested changes

2023-03-07 22:34 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
> +    taskid: 322faa9a-3a45-476d-88ac-ba4cf2bcc9d5
Please edit playbook so:
- email should only be sent for full AR
- Also, you need to add a conditional to check to make sure the service owner has an email.

2023-03-08 08:17 UTC, daryakoval approved these changes

2023-03-08 14:18 UTC, johnnywilkes commented
@daryakoval , we are still waiting on a few changes

2023-03-08 17:32 UTC, johnnywilkes approved these changes
@BigEasyJ , looks good!  I approve this!

2023-03-08 17:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
> +        simple: '[TESTING] A new security risk was addressed on an external service owned by your team'
@BigEasyJ , please remove `TESTING`

2023-03-08 17:32 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ASM_Alert.yml
> +              <p> THIS IS A TEST, PLEASE IGNORE <br><br>
@BigEasyJ , please remove this blurb as well

2023-03-09 09:21 UTC, daryakoval commented
Please comment here when the pr is ready for merge. Thanks.

2023-03-09 14:40 UTC, johnnywilkes commented
@daryakoval , this is ready to merge

2023-03-09 15:00 UTC, merged