Orca Event Collector
demisto/content pull request #25183
Opened 2023-03-09 14:20 UTC by RotemAmit

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5077)

## Description
Adding an event collector to Orca integration.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-03-19 08:48 UTC, Shellyber requested changes
Nice Work! See my notes :) 
Also, Change to demisto.debug where necessary 
What about the permissions for this API?

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector_description.md
> +XSOAR will query for Orca Alerts/ Alert updates every 1 minute
This is not right, this is not XSOAR integration - remove

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector_test.py
> +# from OrcaEventCollector import Client
If not needed, remove

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/ReleaseNotes/2_0_3.md
> +- Agentless, Workload-Deep, Context-Aware Security and Compliance for AWS, Azure, and GCP. (Available from Cortex XSOAR 6.8.0).
```suggestion
- Agentless, Workload-Deep, Context-Aware Security and Compliance for AWS, Azure, and GCP.
```

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/pack_metadata.json
> +    "currentVersion": "2.0.3",
```suggestion
    "currentVersion": "2.1.0",
```
Change also the release notes file name

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/README.md
> +    | Server URL (for example: https://app.eu.orcasecurity.io/api) |  | True |
Where is the note about the server URL? all the regions and options?

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector_description.md
> +    - Enter the server url.
Also here, lets add the note regarding the server_url

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.py
> +    demisto.info(f'in get alerts {next_page_token=} , {len(alerts)=}\n {alerts=}')
```suggestion
    demisto.debug(f'Get Alerts Response {next_page_token=} , {len(alerts)=}\n {alerts=}')
```

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.py
> +        demisto.info(f'in get_alerts request {params=}')
```suggestion
        demisto.info(f'In get_alerts request {params=}')
```

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.py
> +    :return:
remove

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.py
> +    server_url = demisto.params().get('server_url', 'https://app.eu.orcasecurity.io/api')
No need for default here, please remove

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.py
> +    demisto.info(f'{first_fetch_time=}')
Change to debug in all relevant places

2023-03-19 08:48 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.py
> +                    'lastRun': alerts[-1].get('state', {}).get('last_updated')[:-6] if alerts else last_fetch
explain this please

2023-04-04 09:12 UTC, Shellyber reviewed
nice

2023-04-04 09:21 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/Pipfile
> +[[source]]
No need for this file and the Pipfile.lock file - you can remove both

2023-04-04 09:21 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/command_examples
Also remove this

2023-04-09 07:55 UTC, ShirleyDenkberg commented
@Shellyber Doc review completed.

2023-04-16 13:41 UTC, Shellyber approved these changes
Nice work!

2023-04-16 13:41 UTC, Shellyber commented on Packs/Orca/ReleaseNotes/2_1_0.md
> +- Agentless, Workload-Deep, Context-Aware Security and Compliance for AWS, Azure, and GCP.
Fix the description according to the yml

2023-04-16 13:41 UTC, Shellyber commented on Packs/Orca/Integrations/OrcaEventCollector/README.md
> +Agentless, Workload-Deep, Context-Aware Security and Compliance for AWS, Azure, and GCP.
Fix the description according to yml

2023-04-18 05:57 UTC, merged