initial commit
demisto/content pull request #25201
Opened 2023-03-10 14:59 UTC by moin-loginsoft

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
NA

## Description
New Pack Datadog Cloud SIEM using datadog-api-client.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
 NA

## Must have
- [ ] Tests
- [ ] Documentation

2023-03-10 15:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=25201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=25201) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=25201) it.</sub>

2023-03-12 12:23 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +                readable_output = "No Events to present.\n"
```suggestion
                readable_output = "API didn't return any event for given search parameters."
```

2023-03-12 12:23 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +- additionalinfo: The API Key to use for authentication.
```suggestion
- additionalinfo: The application key to use for authentication.
```

2023-03-12 12:23 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM_test.py
> +# from datadog_api_client import ApiClient, Configuration
Remove comments

2023-03-12 12:23 UTC, gal-forer commented on Packs/DatadogCloudSIEM/pack_metadata.json
> +    "support": "partner",
```suggestion
    "support": "xsoar",
```

2023-03-13 12:49 UTC, ShirleyDenkberg commented
@moin-loginsoft 
- After implementing my YML comments, regenerate the integration README.
- Need to create a pack README.

@gal-forer Doc review completed.

2023-03-19 11:57 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +            f"Showing page {page} out of others that may exist"
?

2023-03-19 11:57 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +            # tags = [obj.get("Tag") for obj in tags_list]
Remove comments

2023-03-19 11:57 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +        readable_output = ERROR_MSG
Can you give a more elaborate error than something went wrong ? can we get what went wrong from the API ?

2023-03-19 11:57 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +        readable_output = ERROR_MSG
Can you give a more elaborate error than something went wrong ? can we get what went wrong from the API ?

2023-03-19 11:57 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +            else ERROR_MSG
Can you give a more elaborate error than something went wrong ? can we get what went wrong from the API ?

2023-03-19 11:57 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +            **{key: value for key, value in search_params.items() if value is not None}
```suggestion
            **{key: value for key, value in search_params.items() if value}
```

2023-03-29 10:26 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +        # Log exceptions
Remove comment

2023-03-29 10:26 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +    except (ForbiddenException, UnauthorizedException) as fex:
Why do you need the fex argument ?

2023-04-20 18:58 UTC, DanilVil commented
@moin-loginsoft Please update the display name for the *pack* to be `Datadog Cloud SIEM` instead of `DatadogCloudSIEM`

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: A more human-readable and abbreviated version of the metric name.
```suggestion
      description: A human-readable and abbreviated version of the metric name.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Metric type
```suggestion
      description: Metric type.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Primary unit of the metric
```suggestion
      description: Primary unit of the metric.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: A more human-readable and abbreviated version of the metric name.
```suggestion
      description: A .human-readable and abbreviated version of the metric name.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Primary unit of the metric
```suggestion
      description: Primary unit of the metric.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: A more human-readable and abbreviated version of the metric name.
```suggestion
      description: A human-readable and abbreviated version of the metric name.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Metric type
```suggestion
      description: Metric type.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Primary unit of the metric
```suggestion
      description: Primary unit of the metric.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +        Permitted value : False ( Bug will be fixed in near future)
```suggestion
        Permitted value : False (Bug will be fixed in the near future.)
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +        Permitted value :  normal (Bug will be fixed in near future)
```suggestion
        Permitted value :  normal (Bug will be fixed in the near future.)
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: The State of the incident.
```suggestion
      description: The state of the incident.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +        The Markdown content of the cell  which is used to format using the Markdown syntax rules.
```suggestion
        The Markdown content of the cell that is used to format using the Markdown syntax rules.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +        If content is provided important is required.
I don't understand this line.

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +    description: Datadog Incidents Create is used to Create an incident.
```suggestion
    description: Create an incident.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +        Timestamp  when customers began being impacted by the incident .
```suggestion
        Timestamp when customers began being impacted by the incident .
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +        The Severity of the incident.
```suggestion
        The severity of the incident.
```

2023-05-01 12:51 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: The State of the incident.
```suggestion
      description: The state of the incident.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: A unique identifier that represents the user.
The descriptions for the following are all the same.
....created_by_user.data.id
....modified_by_user.data.id
...last_modified_by_user.data.id
Is that correct?

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: A unique identifier that represents the user.
The descriptions for the following are all the same.
....created_by_user.data.id
....last_modified_by_user.data.id
...commander_user.data.id
Is that correct?

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +    - contextPath: Datadog.Incident.relationships.created_by_user.data.id
The descriptions for the following are all the same.
....created_by_user.data.id
....modified_by_user.data.id
...last_modified_by_user.data.id
....commander_user.data.id
Is that correct?

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +    description: Query of Sequence of data points which are collected over time intervals, allowing us to track changes over time.
```suggestion
    description: Query of sequence of data points that are collected over time intervals, allowing us to track changes over time.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Start of requested time window, milliseconds since Unix epoch.
```suggestion
      description: Start of requested time window in milliseconds since Unix epoch.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Message indicating the errors if status is not ok.
```suggestion
      description: Message indicating the errors if status is not OK.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: 'List of tag keys on which to group. '
```suggestion
      description: List of tag keys on which to group.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Message indicating success if status is ok.
```suggestion
      description: Message indicating success if status is OK.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: End of the time window, milliseconds since Unix epoch.
```suggestion
      description: End of the time window in milliseconds since Unix epoch.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Metric scope, comma separated list of tags.
```suggestion
      description: Metric scope, comma-separated list of tags.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: Start of the time window, milliseconds since Unix epoch.
```suggestion
      description: Start of the time window in milliseconds since Unix epoch.
```

2023-05-01 13:15 UTC, ShirleyDenkberg commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +      description: End of requested time window, milliseconds since Unix epoch.
```suggestion
      description: End of requested time window in milliseconds since Unix epoch.
```

2023-05-01 13:16 UTC, ShirleyDenkberg commented
@moin-loginsoft
- After implementing my YML comments, regenerate the integration README.
- Need to create a pack README.
@gal-forer Doc review completed.

2023-05-03 11:29 UTC, gal-forer requested changes

2023-05-03 11:29 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +    demisto.setLastRun({"lastRun": str(datetime.utcnow())})
Please in the the last run put the time value of the oldest event that had been fetched

2023-05-03 11:29 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.py
> +        return_error(f"Failed to execute {command} command. Error: {str(e)}")
Please use only one return_error

2023-05-03 11:29 UTC, gal-forer commented on Packs/DatadogCloudSIEM/Integrations/DatadogCloudSIEM/DatadogCloudSIEM.yml
> +- display: Use system proxy settings
Make sure that the checkboxes are at the bottom

2023-05-11 11:43 UTC, closed without merging