GCP - CIAC - 5981
demisto/content pull request #25410
Opened 2023-03-20 23:46 UTC by johnnywilkes

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/CIAC-5981

## Description
A customer would like to be able to use a GCP service account scoped at the organization level with the Xpanse "Cortex ASM - ASM Alert" playbook.  Please see my video for more information.

## Screenshots
See video

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [X] Documentation

2023-03-20 23:48 UTC, johnnywilkes commented
@daryakoval , i shared a demo video with you via google drive

2023-03-21 15:15 UTC, BigEasyJ requested changes

2023-03-21 15:15 UTC, BigEasyJ commented on Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
> +
```suggestion
```

2023-03-21 15:15 UTC, BigEasyJ commented on Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
> +    if response_asset:
```suggestion
    
    if response_asset:
```

2023-03-21 15:15 UTC, BigEasyJ commented on Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
> +    default_search_scope = demisto.params().get('default_search_scope')
Do you feel like this needs any error handling here or in the `if/else` for what the potential input could be?

2023-03-21 17:01 UTC, johnnywilkes commented on Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
> +
this is just remove a blank line?

2023-03-23 09:45 UTC, daryakoval approved these changes

2023-03-23 09:54 UTC, merged