GCP/ASM - EXPANDR-3281
demisto/content pull request #25484
Opened 2023-03-23 14:02 UTC by johnnywilkes

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/CIAC-5981
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3281

## Description
This is effectively updating playbooks after integration change in https://jira-hq.paloaltonetworks.local/browse/CIAC-5981

## Screenshots
video

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [X] Documentation

2023-03-23 14:08 UTC, johnnywilkes commented
@dansterenson , shared demo video with you via google drive

2023-03-26 13:00 UTC, dansterenson requested changes
Nice, see my notes. @efelmandar still needs to review the playbooks.

2023-03-26 23:08 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_1.md
@dansterenson , i fixed a typo in this release note.  I could create a separate PR, but it doesn't make sense for me to.

2023-03-27 00:05 UTC, johnnywilkes commented on Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_1.md
> +- Updated the playbook to incorporate changes from https://github.com/demisto/content/pull/25410.
[update GCP RN and redo Remediation play](https://github.com/demisto/content/pull/25484/commits/4efa8682fb788103f06c2c4962b1a481f2450b2b)

2023-03-27 00:05 UTC, johnnywilkes commented on Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_1.md
> +- Updated the playbook to incorporate changes from https://github.com/demisto/content/pull/25410.
[update GCP RN and redo Remediation play](https://github.com/demisto/content/pull/25484/commits/4efa8682fb788103f06c2c4962b1a481f2450b2b)

2023-03-27 00:05 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_3.md
[update GCP RN and redo Remediation play](https://github.com/demisto/content/pull/25484/commits/4efa8682fb788103f06c2c4962b1a481f2450b2b)

2023-03-27 13:46 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_3.md
> +- Added the value to the new 'GcpProject' input required by the 'GCP - Firewall Remediation' playbook.
```suggestion
Added the value to the new 'GcpProject' input required by the **GCP - Firewall Remediation** playbook.
```

2023-03-27 13:46 UTC, ShirleyDenkberg commented on Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation.yml
> +  description: The name of the GCP project associated the instance and related objects.
```suggestion
  description: The name of the GCP project associated with the instance and related objects.
```

2023-03-27 13:46 UTC, ShirleyDenkberg commented on Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation_README.md
> +| GcpProject | The name of the GCP project associated the instance and related objects. | alert.asmcloud.Project | Required |
```suggestion
| GcpProject | The name of the GCP project associated with the instance and related objects. | alert.asmcloud.Project | Required |
```

2023-03-27 13:46 UTC, ShirleyDenkberg commented on Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_1.md
> +- Updated the playbook to incorporate *Google Cloud Compute* integration improvements.
```suggestion
Updated the playbook to incorporate the *Google Cloud Compute* integration improvements.
```

2023-03-27 13:46 UTC, ShirleyDenkberg commented on Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_1.md
> +- Updated the playbook to incorporate *Google Cloud Compute* integration improvements.
```suggestion
Updated the playbook to incorporate the *Google Cloud Compute* integration improvements.
```

2023-03-27 13:47 UTC, ShirleyDenkberg commented
@dansterenson @efelmandar Doc review completed.

2023-03-30 08:38 UTC, dansterenson approved these changes

2023-03-30 08:39 UTC, merged