Added code for Extrahop Release 1.2.0
demisto/content pull request #25579
Opened 2023-03-28 14:04 UTC by crestdatasystems

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
#### Integrations

##### Rubrik Radar

- Updated the Docker image to: *demisto/rubrik-polaris-sdk-py3:1.0.0.50158*.
- Updated the rubrik-event-list command's parameters possible values.
- Updated the rubrik-polaris-vm-object-snapshot-list command's possible values.
- Updated the rubrik-polaris-object-list command to add type_filter argument as required parameter.
- Updated the rubrik-gps-vm-livemount command and used new function with updated parameters provided by the client.
- Updated the **Rubrik Data Object Discovery - Rubrik Polaris** playbook and attached sub playbook to it.
- Added the **Rubrik List Snapshots - Rubrik Polaris** sub playbook.

#### Playbooks
##### Rubrik List Snapshots - Rubrik Polaris
- Added a playbook which will list snapshots for all objects. (Available from Cortex XSOAR 6.0.0).

##### Rubrik Data Object Discovery - Rubrik Polaris

- Updated the playbook and attached **Rubrik List Snapshots - Rubrik Polaris** sub playbook for Data discovery of the object available in the incident. (Available from Cortex XSOAR 6.0.0).

#### Scripts

##### RubrikCDMClusterConnectionState

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.
##### DateToTimeStamp

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.
##### RubrikRadarFilesModified

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.
##### RubrikSonarSensitiveHits

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.
##### RubrikRadarFilesAdded

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.
##### RubrikSonarOpenAccessFiles

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.
##### RubrikRadarFilesDeleted

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.
##### RubrikSonarTotalHits

- Updated the Docker image to: *demisto/python3:3.10.10.50695*.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-03-29 12:52 UTC, yucohen requested changes
@crestdatasystems Thanks for your contribution! We highly appreciate it
Please see my comments

2023-03-29 12:52 UTC, yucohen commented on .devcontainer/devcontainer.json
> +// Development container for Content. Poetry hash 6c69ac4b4e71cfdddd29602e19df186c1118fb8ad974df7b2091dd9417b7aec9
please revert

2023-03-29 12:52 UTC, yucohen commented on Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/fetch_incidents_success_incidents.json
> +    "rawJSON": "{\"incidentClassification\": \"RubrikRadar\", \"message\": [{\"message\": \"Detected anomalous filesystem activity with high confidence and high levels of encryption (File Change: 349
Do we use this rawJSON in the tests? If not, lets delete this from the JSON

2023-03-30 09:17 UTC, jyotipatel2090 commented on Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
> +      name: snappable_id
Yes, we want to change this for the existing users also this is not working.

2023-04-04 08:38 UTC, yucohen commented on .devcontainer/devcontainer.json
>  }
please revert those as well

2023-04-04 15:47 UTC, edik24 commented
@jyotipatel2090 please fix all docker validation errors

2023-04-06 12:23 UTC, jyotipatel2090 commented
> @jyotipatel2090 please fix all docker validation errors

Fixed, Except one which is related to backward compatibility

2023-04-16 07:13 UTC, yucohen approved these changes

2023-04-16 07:13 UTC, merged