Use version 2.0.0 of argus-toolbelt docker image
demisto/content pull request #25650
Opened 2023-03-31 11:36 UTC by konraduh

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Hotfix. Version 3 of docker image argus-toolbelt not compatible with this integration. 

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ x ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-04-03 10:08 UTC, merit-maita requested changes
thanks for your contribution!
please make sure the checks pass

2023-04-03 10:08 UTC, merit-maita commented on .devcontainer/devcontainer.json
> +// Development container for Content. Poetry hash 1b1ee2d03208b85c59c1aaaf0726aa7db0fdf6bb5c0766919268dfb44d47b9b6
```suggestion
// Development container for Content. Poetry hash 1.11.0
```
it was changed to sdk version intentionally, so please revert it

2023-04-08 20:38 UTC, merit-maita commented
Hello @konraduh 
can you please address my comment you resolved regarding the hash added, and check the circleCi SetUp Environment that's failing.
thanks!

2023-04-15 22:28 UTC, merit-maita commented on .devcontainer/devcontainer.json
> +// Development container for Content. Poetry hash 1b1ee2d03208b85c59c1aaaf0726aa7db0fdf6bb5c0766919268dfb44d47b9b6
```suggestion
// Development container for Content. Poetry hash 1.11.0
```

2023-04-17 21:47 UTC, merit-maita commented
@konraduh  any update?

2023-04-17 23:47 UTC, konraduh commented
Hi,

So sorry, I'm away until next month, I'll see if someone else can deal with
it. I tried adding your suggested edit to the comment.

Sorry to take up your time.

BR,
Konrad

On Tue, 18 Apr 2023, 06:47 merit-maita, ***@***.***> wrote:

> @konraduh <https://github.com/konraduh> any update?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/demisto/content/pull/25650#issuecomment-1512125108>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACRY2ACE4QW35P7F5T52MDLXBW27ZANCNFSM6AAAAAAWORDEOI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-18 22:03 UTC, merit-maita commented
@konraduh please update me if someone can take it soon, if not, you can close it for now, and reopen it once its ready

2023-04-20 12:36 UTC, merit-maita commented
@konraduh i'm closing the pr now, since it seems like its being on-hold, please reopen in case there's some update

2023-04-20 12:36 UTC, closed without merging