Ciac 2676/detonate url generic enhancments
demisto/content pull request #25787
Opened 2023-04-10 10:23 UTC by efelmandar

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2676)

## Description
As some integrations such as Wildfire have been updated to have a builtin polling mechanism we can simplify the process of detonation to a single task or smaller playbook that doesn't require the use of generic polling
This PR introduces these new detonate URL playbooks, not a new V but that use fromversion for 6.8 and that will support polling commands

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.8.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Documentation

2023-05-18 10:30 UTC, dorschw requested changes

2023-05-18 10:30 UTC, dorschw commented on pyproject.toml
> +demisto_sdk = {git = "https://github.com/demisto/demisto-sdk.git", rev = "bd1826b53da8f33a69379f610be1006b14c26c50"}
please make sure to revert this change.

2023-05-30 15:58 UTC, altmannyarden commented on Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_27.md
> +- Updated the playbook to use the new command with built-in polling.
1. missing the part with the replace
2. you have two release note files

2023-05-30 15:58 UTC, altmannyarden commented on Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_27.md
> +- Updated the playbook to use the new command with built-in polling.
And by looking at the playbook image - why do we need the playbook?

2023-05-30 16:00 UTC, altmannyarden commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_24.md
> +- Updated the playbook to use the new command with built-in polling.
1. 2 release notes again
2. not sure that a playbook is needed

2023-07-13 13:48 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_v1.5.yml
> +    nexttasks:
What if the URL does not exist?
missing the next task for the 'else' condition

2023-07-16 07:06 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_v1.5.yml
> +    skipunavailable: false
change it to skipunavailable: true

2023-07-16 07:06 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_v1.5.yml
> +    skipunavailable: false
change it to skipunavailable: true

2023-07-16 07:45 UTC, OmriItzhak approved these changes

2023-07-17 12:56 UTC, merged