Anomali threatstream build ioc json
demisto/content pull request #25911
Opened 2023-04-17 10:14 UTC by sapirshuker

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5636

## Description
Builds A JSON array based on the values provided by the user for the 'threatstream-import-indicator-without-approval' command.

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

2023-04-17 14:13 UTC, Shellyber requested changes
Great job!

2023-04-17 14:13 UTC, Shellyber commented on Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson_test.py
> +def util_load_json(path):
Do you use it somewhere? if not remove

2023-04-17 14:13 UTC, Shellyber commented on Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson_test.py
> +@pytest.mark.parametrize('args, indicators_types, expected_result', [
Please add a case with comma-separated values as well

2023-04-17 14:13 UTC, Shellyber commented on Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson_test.py
> +def test_validate_indicators(email_list, md5_list, ip_list, url_list, domain_list, expected_result):
Add also a test for valid indicators

2023-04-17 14:13 UTC, Shellyber commented on Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson_test.py
> +    """Tests get_indicators_from_user function.
Change docstrings to the format we use `given, when, then`

2023-04-18 08:47 UTC, Shellyber approved these changes

2023-04-18 13:23 UTC, ShirleyDenkberg commented
@Shellyber Doc review completed.

2023-04-18 13:32 UTC, merged