xsiam uninstall packs bug
demisto/content pull request #26043
Opened 2023-04-23 12:40 UTC by rshunim

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6286

## Description
Monitoring when uninstall packs don't work was added and also re-calculate total time for uninstall packs by num of packs to uninstall.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-04-23 12:45 UTC, daryakoval commented
Please trigger the test nightly, and put here the build link.

2023-04-23 12:47 UTC, rshunim commented
Link to the [nightly](https://code.pan.run/xsoar/content/-/pipelines/5103241)

2023-04-23 13:14 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +        monitoring_amount_installed_packs = [1, 1, 1, len(installed_packs)]
```suggestion
        installed_packs_count_history = [1, 1, 1, len(installed_packs)]  # appended to on each attempt
```

2023-04-23 13:14 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +            if all_equal(monitoring_amount_installed_packs):
```suggestion
            if all_equal(installed_packs_count_history[-4:]):
```

2023-04-23 13:14 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +from itertools import groupby
```suggestion
from more_itertools import all_equal
```

2023-04-23 13:14 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +
```suggestion
```

2023-04-23 13:14 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +            monitoring_amount_installed_packs.append(len(installed_packs))
```suggestion
            installed_packs_count_history.append(len(installed_packs))
```

2023-04-23 16:04 UTC, dorschw requested changes

2023-04-23 16:04 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +    This function checks if installed packs amount is the same or not and updates accordingly.
```suggestion
    Checks if installed packs amount is the same or not and updates accordingly.
```

2023-04-23 16:04 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +    This function checks if installed packs amount is the same or not and updates accordingly.
`...and updates accordingly` - updates what?

2023-04-23 16:04 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +def monitoring_uninstall_packs(current_amount_packs: int, previous_amount_packs: int, counter_times_to_repeats: int):
```suggestion
def monitoring_uninstall_packs(current_amount_packs: int, previous_amount_packs: int, counter_times_to_repeats: int) -> tuple[int, int]:
```

2023-04-23 16:04 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +        installed packs amount in the current iteration and the counter
what's `the counter`?

2023-04-23 16:04 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +                                           counter_times_to_repeats)
I think we can put the logic here, instead of in an external method, whose first return value is its input (unclear)

2023-04-24 08:11 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +                counter_times_to_repeats = 0
```suggestion
        # Monitoring when uninstall packs don't work
        installed_packs_amount_history, failed_uninstall_attempt_count = len(installed_packs), 0
        # new calculation for num of retries
        retries = math.ceil(len(installed_packs) / 2)
        while len(installed_packs) > 1:
            if retry > retries:
                raise Exception('Waiting time for packs to be uninstalled has passed, there are still installed '
                                'packs. Aborting.')
            if installed_packs_amount_history >= 3:
                raise Exception(f'Uninstalling packs failed three times. {installed_packs=}')
            logging.info(f'The process of uninstalling all packs is not over! There are still {len(installed_packs)} '
                         f'packs installed. Sleeping for {sleep_duration} seconds.')
            sleep(sleep_duration)
            installed_packs = get_all_installed_packs(client)

            # Monitoring when uninstall packs don't work
            if len(installed_packs) == installed_packs_amount_history:
                failed_uninstall_attempt_count += 1
            else:
                failed_uninstall_attempt_count = 0
                installed_packs_amount_history = len(installed_packs)  # reset for next time
```

2023-04-24 10:23 UTC, dorschw approved these changes

2023-04-24 10:23 UTC, dorschw commented on Tests/Marketplace/search_and_uninstall_pack.py
> +
```suggestion
        # Monitoring when uninstall packs don't work
        previous_installed_packs_count, failed_uninstall_attempt_count = len(installed_packs), 0
        # new calculation for num of retries
        retries = math.ceil(len(installed_packs) / 2)
        while len(installed_packs) > 1:
            if retry > retries:
                raise Exception('Waiting time for packs to be uninstalled has passed, there are still installed '
                                'packs. Aborting.')
            if failed_uninstall_attempt_count >= 3:
                raise Exception(f'Uninstalling packs failed three times. {installed_packs=}')
            logging.info(f'The process of uninstalling all packs is not over! There are still {len(installed_packs)} '
                         f'packs installed. Sleeping for {sleep_duration} seconds.')
            sleep(sleep_duration)
            installed_packs = get_all_installed_packs(client)

            if len(installed_packs) == previous_installed_packs_count:
            # did not uninstall any pack 
                failed_uninstall_attempt_count += 1
            else:  # uninstalled at least one pack
                previous_installed_packs_count = len(installed_packs)
                failed_uninstall_attempt_count = 0

```

2023-04-30 09:18 UTC, merged