Add RDP cache use-case files
demisto/content pull request #26053
Opened 2023-04-23 16:58 UTC by efelmandar

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2714)

## Description
Adding all the necessary files for the RDP Cache Hunting use case pack which includes Playbooks, Automation scripts, Layout, Incident Types and Incident fields

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.8.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Documentation

2023-05-28 13:23 UTC, eyalpalo commented on Packs/CommonScripts/Scripts/BMCTool/BMCTool.py
> +        if not verbose or self.verb:
Don't really understand the condition, if verbose is set to False we will print the log.
Why not 
`if verbose or self.verb`?

2023-05-30 14:27 UTC, eyalpalo commented on Packs/RDPCacheHunting/Scripts/SetRDPOverallScore/SetRDPOverallScore.py
> +# register_module_line('RapidBreachResponse-CompletedTasksCount-Widget', 'end', __line__())
Please remove this line

2023-05-30 14:29 UTC, eyalpalo commented on Packs/RDPCacheHunting/Scripts/SetRDPOverallScore/SetRDPOverallScore.yml
> +name: SetRDPOverallScore
Same note regarding the outputs as above.

2023-06-04 13:13 UTC, eyalpalo commented on Packs/CommonScripts/Scripts/BMCTool/BMCTool.py
> +                        t_bmp = self.b_parse_rgb32b(self.bdat[len(t_hdr):len(t_hdr) + cf * t_width * t_height])
For example:
<img width="843" alt="image" src="https://github.com/demisto/content/assets/91007713/3cfbc5e2-bdd9-434f-829a-31bf2f6ff157">

2023-06-28 07:05 UTC, eyalpalo requested changes
Almost there! looks good
Few more changes. Lets have a final demo (maybe worth also inviting Yarden?)

2023-07-17 09:47 UTC, melamedbn commented on Packs/CommonScripts/Scripts/StringSimilarity/README.md
Should it be empty?

2023-07-17 09:48 UTC, melamedbn commented on Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity_test.py
Should it be empty?

2023-07-17 09:49 UTC, melamedbn commented on Packs/RDPCacheHunting/IncidentTypes/incidenttype-RDP_Sessions.json
Maybe we should reconsider the name? the type is "RDP Sessions Hunting" or something like that

2023-07-17 10:33 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +    simple: C:\Users\administrator\AppData\Local\Microsoft\Terminal Server Client\Cache\
If folder path is eligible, let's document it and give another example in the description.

2023-07-17 10:35 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +- key: ShouldCollectRDPCache
I see you also used the Retrieve File from Endpoint - Generic V3 playbook.
That means that we need to document in the playbook's readme and the input description that we can collect using x,y,z.

2023-07-17 10:36 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +description: This playbook automates the collection and forensic analysis of RDP sessions cache data by collecting the cache files and convert it to an image, extract readable text from the image and
Use MD instead.
I see you also used the Retrieve File from Endpoint - Generic V3 playbook.
That means that we need to document in the playbook's readme that we can collect using x,y,z.

2023-07-17 10:38 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      script: '|||xdr-file-retrieve'
Change to the matching Core command.

2023-07-17 10:41 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      - "31"
Please remove

2023-07-17 10:46 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +                  simple: bin
Why are you checking for bin files only?

2023-07-17 10:51 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +                accessor: attachment
Add filter for the attachment extension.

2023-07-17 10:51 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      description: Checkif the file was successfully retrieved
Add space Checkif -> Check if

2023-07-17 10:56 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      name: Convert pdf to image
Change to "Convert image to pdf"

2023-07-17 10:58 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      name: Convert image to png
Convert the bmp file to png

2023-07-17 11:00 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      name: Convert image to pdf
Rasterize the PDF file

2023-07-17 11:04 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +                  simple: original
We want to OCR both sharpened and greyscale images, the original is only for display.

2023-07-17 11:06 UTC, melamedbn commented on Packs/RDPCacheHunting/doc_files/Set_list_of_indicator_types.png
Can we remove it?

2023-07-17 11:07 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +          accessor: MalTools
If we won't provide the list we should retrieve it somehow.

2023-07-17 11:08 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +  "26":
Add the splunk and qradar time ranges to the playbook inputs.

2023-07-17 11:10 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +                  simple: original
Let's use the greyscale and sharpened.

2023-07-17 11:12 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      name: Suspicious strings hunting
Add the min_score and limit as a playbook inputs.

2023-07-17 11:12 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      name: Hunt RDP IoCs - Exe + Path
Why do we use only splunk?
We should make it generic.

2023-07-17 11:12 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      description: Searches Splunk for events.
Please elaborate.

2023-07-17 11:13 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +      similiarity_threshold:
Add the similarity_treshold as a playbook input.

2023-07-17 11:17 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +  "29":
Check if we can remove the sub playbook and put the tasks in the main one.

2023-07-17 11:37 UTC, melamedbn commented on Packs/RDPCacheHunting/Layouts/layoutscontainer-RDP_Sessions.json
> +                        "name": "Strings Similarity",
Sort by similarity ratio

2023-07-17 11:54 UTC, melamedbn commented on Packs/RDPCacheHunting/Layouts/layoutscontainer-RDP_Sessions.json
> +                        "query": "type:\"Windows Path\"",
Change to 'Windows File Path'

2023-07-17 11:54 UTC, melamedbn commented on Packs/RDPCacheHunting/Layouts/layoutscontainer-RDP_Sessions.json
> +                        "query": "type:\"Executables\"",
Change to 'Windows Executables'

2023-07-17 11:54 UTC, melamedbn commented on Packs/RDPCacheHunting/Layouts/layoutscontainer-RDP_Sessions.json
> +                        "query": "type:\"Windows Date\u0026Time\"",
Change to 'Windows Date and Time'

2023-07-17 11:56 UTC, melamedbn commented on Packs/RDPCacheHunting/Layouts/layoutscontainer-RDP_Sessions.json
> +                "id": "evidenceBoard",
Add the cache files and images as evidences.

2023-07-17 12:04 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt_README.md
re-generate docs

2023-07-20 13:15 UTC, melamedbn commented on Packs/RDPCacheHunting/Playbooks/playbook-RDP_Bitmap_Cache_-_Detect_and_Hunt.yml
> +  "58":
Missing "mark as evidence".

2023-07-23 10:44 UTC, eyalpalo approved these changes

2023-07-23 15:03 UTC, ShirleyDenkberg commented
@efelmandar 
Need readmes for:
SetIndicatortype
SetRDPOverallScore

@melamedbn, @eyalpalo, @altmannyarden, @esharf Doc review completed.

2023-07-27 14:36 UTC, merged