[Rapid7 InsightIDR] Fixed an issue with receiving the logs by query
demisto/content pull request #26205
Opened 2023-05-01 12:24 UTC by mmhw

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6152)

## Description
Fixed an issue with receiving the logs by query with the following commands:
* **rapid7-insight-idr-query-log**
* **rapid7-insight-idr-query-log-set**

2023-05-15 14:50 UTC, kobymeir requested changes

2023-05-15 14:50 UTC, kobymeir commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR_test.py
> +        outputs.extend(iter(result.get('events', [])))
can be simplified to a list-comprehension

2023-05-15 14:50 UTC, kobymeir commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR_test.py
> +        outputs.extend(iter(result.get('events', [])))
also simplify as a list-comprehension

2023-05-15 14:50 UTC, kobymeir commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
> +            for link in results.get('links', []):
```suggestion
        if links := results.get('links', []):
            for link in links:
```

2023-05-15 14:50 UTC, kobymeir commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
> +                demisto.debug(f'Events length: {events_len}, progress: {progress}')
```suggestion
                progress = results.get('progress')
                demisto.debug(f'Events length: {len(events)}, progress: {progress}')
```
events is already assigned a value in the previous if statement

2023-05-16 06:41 UTC, mmhw commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/test_data/query_log_set_page_1.json
> +    "links": [
@kobymeir I check it in the second function (test_insight_idr_query_log_with_callback), do you think it should be added here as well?

2023-05-18 07:46 UTC, kobymeir approved these changes

2023-05-18 08:00 UTC, bziser commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
> +def handle_query_log_results(client: Client, result):
please add description to the function

2023-05-18 08:07 UTC, bziser approved these changes
great, just add the description to the function

2023-05-18 09:04 UTC, bziser commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
> +    """This function get the first result of the query, then handles if the query has in progress, and handle pagination.
```suggestion
    """This function get the first result of the query, then handles if the query is still in progress, and handle pagination.
```

2023-05-18 09:05 UTC, bziser commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
> +            data_for_readable_output: The data for the readable output was contains all the events
```suggestion
            data_for_readable_output: The data for the readable output which contains all the events
```

2023-05-18 09:06 UTC, bziser commented on Packs/Rapid7_InsightIDR/Integrations/Rapid7_InsightIDR/Rapid7_InsightIDR.py
> +            raw_responcse: The raw response from the all the requests that returned events
```suggestion
            raw_responcse: Raw response from all events returned by the requests
```

2023-05-18 11:41 UTC, merged