[ASM] EXPANDR-3582 - Prisma cloud changes and Emails from Tags changes.
demisto/content pull request #26301
Opened 2023-05-04 07:24 UTC by capanw

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3582
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3411

## Description
Merging Prisma cloud playbooks into Cortex ASM pack and Adding new enhancement where we now extract email ownership from tags.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2023-05-04 13:11 UTC, johnnywilkes requested changes
A few things to look into

2023-05-04 15:42 UTC, capanw commented on Tests/Marketplace/core_packs_xpanse_list.json
> +    "PrismaCloud",
Done.

2023-05-04 15:43 UTC, capanw commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
> +fromversion: 6.5.0
Updated to 6.8.0. Not sure why format command overwrote this, but updated it back.

2023-05-05 13:13 UTC, johnnywilkes commented
@GuyAfik , is something not right with the build? https://github.com/demisto/content/actions/runs/4889973341/jobs/8728970663?pr=26301

Haven't seen these errors before

2023-05-05 15:50 UTC, capanw commented on Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.yml
> +  dockerimage: demisto/python3:3.10.11.56857
Done

2023-05-05 15:55 UTC, johnnywilkes approved these changes
Good work @capanw !  Approved, but I expect @GuyAfik to have to look over the small changes not in ASM pack

2023-05-07 08:52 UTC, GuyAfik approved these changes
looks good! nice work!

2023-05-07 08:52 UTC, merged