Fix the second bug
demisto/content pull request #26315
Opened 2023-05-04 12:13 UTC by RosenbergYehuda

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-05-21 12:53 UTC, ShacharKidor requested changes
Very nice :)

2023-05-22 08:47 UTC, ShirleyDenkberg commented on Packs/PrismaAccess/ReleaseNotes/2_0_2.md
> +- Fixed an issue with the *Frequency* field in the human readable of the ***prisma-sase-external-dynamic-list-create*** command.
...human readable output....

2023-05-22 08:48 UTC, ShirleyDenkberg commented
@ShacharKidor Doc review completed.

2023-05-22 09:19 UTC, ShacharKidor commented on Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.py
> +        if "404" and "Object Not Present" in e.message:
Please use e.res.status_code instead of searching "404" in the message.

2023-05-22 09:19 UTC, ShacharKidor commented on Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.py
> +def main():  # pragma: no cover  # sourcery skip: remove-redundant-if
What is this line: `# sourcery skip: remove-redundant-if`?

2023-05-22 09:23 UTC, ShacharKidor approved these changes

2023-05-22 17:35 UTC, merged