Added skipPrepare for some scripts
demisto/content pull request #26365
Opened 2023-05-07 13:28 UTC by israelpoli

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added skipPrepare for some scripts that are no needs to preparation fo incident to alert.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-05-07 18:15 UTC, yuvalbenshalom requested changes
see my comments.
also lets consider making the release notes specific for scripts.

2023-05-07 18:15 UTC, yuvalbenshalom commented on Packs/Securonix/Scripts/SecuronixCloseHistoricalXSOARIncidents/SecuronixCloseHistoricalXSOARIncidents.yml
> +skipPrepare:
should not be skipped

2023-05-07 18:15 UTC, yuvalbenshalom commented on Packs/SumoLogic_Cloud_SIEM/Scripts/SumoLogicLinkSignalIncidents/SumoLogicLinkSignalIncidents.yml
> +- script-name-incident-to-alert
do not skip

2023-05-07 18:15 UTC, yuvalbenshalom commented on Packs/qualys/Scripts/QualysCreateIncidentFromReport/QualysCreateIncidentFromReport.yml
> +- script-name-incident-to-alert
remove skip

2023-05-07 18:15 UTC, yuvalbenshalom commented on Packs/qualys/pack_metadata.json
> +    "currentVersion": "1.2.7",
remove

2023-05-21 16:40 UTC, dorschw commented
@yuvalbenshalom please force-merge this one. The only failing validations are `DO106`, `RM109`, `CJ105`.

2023-05-21 16:43 UTC, merged