Fix the fetching credential bug. Implemented the auto-comment feature…
demisto/content pull request #26423
Opened 2023-05-10 07:11 UTC by Suha1995

… to some commands and added the unit test caes for 3 commands

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-05-10 07:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=26423) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=26423) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=26423) it.</sub>

2023-05-10 10:48 UTC, DeanArbel requested changes
The code looks good, though you could make some changes to make it better as I noted above.
Please consider changing the descriptions.

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.py
> +        url_suffix = "/api/v1/secrets/" + str(secret_id) + "?autoComment=" + str(autocomment)
You can pass this via the `params` argument for `_http_request` - that way `autocomment` URL argument will not be passed at all when it's not set.

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.py
> +        url_suffix = "/api/v1/secrets/" + str(secret_id) + "/fields/password" + "?autoComment=" + str(auto_comment)
same comment as above.

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.py
> +        return self._http_request("POST", url_suffix="/api/v1/secrets/" + str(
same comment as above.

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.py
> +        return self._http_request("DELETE",
same comment as above.

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.yml
> +      description: Secret comment
I think you should provide a better description. What does this field do?

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.yml
> +      description: Secret comment
I think you should provide a better description. What does this field do?

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.yml
> +      description: Secret comment
I think you should provide a better description. What does this field do?

2023-05-10 10:48 UTC, DeanArbel commented on Packs/DelineaSS/Integrations/DelineaSS/DelineaSS.yml
> +      description: Secret comment
I think you should provide a better description. What does this field do?

2023-05-14 08:44 UTC, merit-maita commented
@Suha1995 i see you went over the changes requests @DeanArbel asked for, so to move forward with your contribution can you sign the [contribution registration ](https://forms.gle/XDfxU4E61ZwEESSMA) form please?

2023-05-18 07:58 UTC, closed without merging

2023-05-18 09:39 UTC, edik24 commented
this PR closed.
This is the new one:
https://github.com/demisto/content/pull/26619

2023-05-18 09:41 UTC, Suha1995 commented
Yes, I have closed this old PR and raised a new PR "https://github.com/demisto/content/pull/26619"