Xsoar file management
demisto/content pull request #26455
Opened 2023-05-11 09:19 UTC by maimorag

## Status
- [x] In Progress

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5887)

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [x] 6.8.0

2023-05-22 08:32 UTC, Shellyber requested changes
Please revert all the changes in the README.

2023-05-22 08:32 UTC, Shellyber commented on .github/workflows/handle-new-external-pr.yml
> +          fetch-depth: 2
What's this?
Please revert

2023-05-22 08:32 UTC, Shellyber commented on Packs/Base/Scripts/CommonServer/CommonServer.js
> + * @param {Object} fileEntryId- if file entry exist then fyck
then what? (typo in the comment)

2023-05-22 08:32 UTC, Shellyber commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> +### demisto-api-post
Revert the naming of the commands to core not demisto

2023-05-22 08:32 UTC, Shellyber commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> ->{"response":{"commitMessage":"","data":"list_data","definitionId":"","description":"","fromServerVersion":"","id":"list_name","itemVersion":"","locked":false,"modified":"2022-05-29T12:20:14.988577Z"
revert this

2023-05-22 08:32 UTC, Shellyber commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> ->{"response":{"addedSharedDashboards":["Threat Intelligence Feeds","Troubleshooting Instances"],"allRoles":["Administrator"],"defaultAdmin":true,"email":"admintest@core.com","id":"admin","image":"832
revert this

2023-05-22 08:36 UTC, maimorag commented on .github/workflows/handle-new-external-pr.yml
> +          fetch-depth: 2
reverting

2023-05-22 08:50 UTC, maimorag commented on Packs/Base/Scripts/CommonServer/CommonServer.js
> + * @param {Object} fileEntryId- if file entry exist then fyck
not relevant anymore- removed

2023-05-22 08:53 UTC, maimorag commented on Packs/Base/Scripts/CommonServer/CommonServer.js
> +    HumanReadable: HumanReadable
it's optional- if not specified it would return:
`${file_name} uploaded with entryID: ${fileEntryId}`

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
> +    description: This command checks if the file is existing in Xsoar by entry_id
```suggestion
    description: Check if the file exists in Cortex XSOAR by entry_id.
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
> +    - description: Dictionary with EntryID as key and boolean if the file exists as value
```suggestion
    - description: Dictionary with EntryID as the key and boolean if the file exists as a value.
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> +| incident_id | The incident's id. | Required |
```suggestion
| incident_id | The incident's ID. | Required | 
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> +| incident_id | The incident's id. | Required |
```suggestion
| incident_id | The incident's ID. | Required | 
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> +This command checks if the file is existing in Xsoar by entry_id
```suggestion
Check if the file exists in Cortex XSOAR by entry_id.
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> +| IsFileExists | unknown | Dictionary with EntryID as key and boolean if the file exists as value |
```suggestion
| IsFileExists | unknown | Dictionary with EntryID as the key and boolean if the file exists as a value. | 
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/ReleaseNotes/1_3_26.md
> +- Added the commands:
```suggestion
Added the following commands:
```
```suggestion
- Added the commands:
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/ReleaseNotes/1_3_26.md
> +  - ***core-api-file-upload***
```suggestion
- ***core-api-file-upload***
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/ReleaseNotes/1_3_26.md
> +  - ***core-api-file-delete***
```suggestion
- ***core-api-file-delete***
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/ReleaseNotes/1_3_26.md
> +  - ***core-api-file-attachment-delete***
```suggestion
- ***core-api-file-attachment-delete***
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented on Packs/DemistoRESTAPI/ReleaseNotes/1_3_26.md
> +  - ***core-api-file-check***
```suggestion
- ***core-api-file-check***
```

2023-05-22 12:05 UTC, ShirleyDenkberg commented
@Shellyber Doc review completed.

2023-05-22 15:10 UTC, Shellyber reviewed
Nice

2023-05-22 15:10 UTC, Shellyber commented on Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
> +### demisto-api-post
All command naming should start with `core-api-`and not demisto. please fix

2023-06-18 08:25 UTC, Shellyber approved these changes

2023-06-18 10:30 UTC, merged