Datadog cloud siem
demisto/content pull request #26508
Opened 2023-05-15 08:36 UTC by moin-loginsoft

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [x] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-05-15 13:19 UTC, gal-forer requested changes

2023-05-15 13:19 UTC, gal-forer commented on .devcontainer/devcontainer.json
> +// Development container for Content. Poetry hash 49339e5e097980a90532f509d5d9d1f14af7804c0b8acc8d94d7141dbad2603f
Please revert the changes you made

2023-05-15 13:35 UTC, moin-loginsoft commented on .devcontainer/devcontainer.json
> +// Development container for Content. Poetry hash 49339e5e097980a90532f509d5d9d1f14af7804c0b8acc8d94d7141dbad2603f
reverted.

2023-05-16 00:13 UTC, gal-forer approved these changes

2023-05-16 00:14 UTC, merged