Added code for integration of events
demisto/content pull request #26519
Opened 2023-05-15 17:13 UTC by cyble-dev

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-05-16 06:48 UTC, thefrieddan1 commented
Hi @cyble-dev, 
Thank you for your contribution.
In order for me to start reviewing, 
please be sure to fill the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA)

Thanks.

2023-05-18 14:19 UTC, RotemAmit requested changes
Nice work!
* Please run demisto-sdk pre-commit and fix the validate errors, if there are any.
* Add a readme to the playbook.
* Since you are creating a v2 to CybleEvents integration, please deprecate the old version. here is a link to an article on how to do it https://xsoar.pan.dev/docs/reference/articles/deprecation-process-and-hidden-packs#how-to-deprecate-an-integration.
* Since the old version of the integration will be deprecated, please add the command 'cyble-vision-fetch-event-detail' that is on v1 but not in v2 in order not to break backword compatibility.

2023-05-24 05:48 UTC, cyble-dev commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/README.md
> +
@RotemAmit , Is First fetch time is mandatory for Pack (Integration). if its mandatory, Kindly let me know, how to add them in the implementation

2023-05-24 06:47 UTC, RotemAmit commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/README.md
> +
The parameter first fetch time, isn't mandatory but it should has a default value that you should use in the first run of the fetch, When demisto.getLastRun() = None

2023-05-24 08:27 UTC, cyble-dev commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/README.md
> +
If data is none, I am assigning the current date in the last run, below code is added in line 358, is this fine

 if 'event_pull_start_date' not in last_run.keys():
            last_run['event_pull_start_date'] = datetime.now().astimezone().replace(microsecond=0).isoformat()

2023-05-24 08:36 UTC, RotemAmit commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/README.md
> +
Please change this assignment and use there the first fetch time.

2023-05-24 09:47 UTC, efelmandar commented
Hi @cyble-dev  first of all thank you for your contribution. I reviewed the content in your PR and found a couple of points I would like to bring to your attention.

1. In the `Incident Type`, the layout field should be the layout name, not an ID.
![image](https://github.com/demisto/content/assets/102903097/0ea0d147-3748-4d77-a253-243a334ab520)

2. In the playbook, I see that it only contains a single task of fetch alert, isn't it the same as `fetch incidents` in the integration? If it's not the same, I would consider adding other things to this playbook to bring the analyst more data such as enrichment maybe.

3. Also in the playbook if you decide to keep it, you pass the start, end date and limit as static values, I would recommend changing the task to use playbook inputs instead and setting the static dates and limit as default values for these inputs.
![image](https://github.com/demisto/content/assets/102903097/e817fc7a-e460-4144-b790-4f80615e6b02)

Please feel free to reach out if you have any questions or need any additional help, here or on DFIR channel on Slack.

2023-05-28 15:07 UTC, efelmandar commented
@cyble-dev Thank you for making the suggested changes and I approve the PR from my side.

Thank you again for your hard work and contribution to our platform.

2023-05-31 09:08 UTC, RotemAmit reviewed
Good work!
Here are some notes:
* Update the README files with the new changes in the YML and add the sections Command Example and Context Example, as in the example and explanations in this [link](https://xsoar.pan.dev/docs/documentation/readme_file#documentation-examples).
* Please bump the version of the pack CybleThreatIntel in the pack_metadata.json file and add notes describing your changes to a new Release Notes file. 
To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

2023-06-05 08:49 UTC, RotemAmit reviewed
Please resolve all the conflicts in CybleThrearIntel pack and in the pack metadata file of CybleEvents pack.

2023-06-05 15:38 UTC, RotemAmit reviewed
Nice work!
Please make sure to resolve the remaining comments from the previous reviews as well.

2023-06-05 15:38 UTC, RotemAmit commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
> +      description: Sorting order for alert fetch either Ascending or Descending
Please do this change.

2023-06-05 15:38 UTC, RotemAmit commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
> +      description: Returns records for the timeline starting from given indice
Please do this change.

2023-06-07 10:22 UTC, RotemAmit reviewed
Nice work!
Please update the docker image tag of the integration CybleThreatIntel. You can check for the most updated version of demisto/taxii-server here: https://hub.docker.com/r/demisto/taxii-server/tags. After you commit this change please run demisto-sdk update-release-notes, so this change will be added to the release notes file.

2023-06-07 10:22 UTC, RotemAmit commented on Packs/CybleEventsV2/README.md
> +# Cyble Events
Please update this file in order for it to match the structure in this [link](https://xsoar.pan.dev/docs/documentation/pack-docs#pack-readme) to xsoar pan dev website.

2023-06-07 10:22 UTC, RotemAmit reviewed
Nice work!
Please update the docker image tag of the integration CybleThreatIntel. You can check for the most updated version of demisto/taxii-server here: https://hub.docker.com/r/demisto/taxii-server/tags. After you commit this change please run demisto-sdk update-release-notes, so this change will be added to the release notes file.

2023-06-07 10:59 UTC, efelmandar commented
Hi @cyble-dev Thank you for all the hard work, I still see some validation errors which need to be fixed in order for the PR to pass, 

1. In the Incident Type, the layout field should have the layout name, not an ID. In your case, for example, it should be
`"layout": "Cyble Vision Alert V2"` instead of `"layout": "91b2b1be-7c2e-4ec5-8be8-3407aba92b65"`

2. In the Incident Type, I also see some mixup where the filename is `Cyble Inter Alert V2` but the name and ID fields in the JSON are `Cyble Vision Alert V2`

3. The playbook validation is failing because in the playbook you reference the integration ID (`cybleeventsv2`) but in the integration YML you've added a space in the ID and name `cybleevents V2` so to fix it please remove the space from the ID and Name fields in the integration YML

2023-06-08 07:15 UTC, RotemAmit reviewed
Nice work!
* Please in the release notes of CybleThreatIntel use the same amount of # as I asked.
* Please run: demisto-sdk format -i Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.yml

2023-06-08 07:15 UTC, RotemAmit commented on Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.yml
> +  dockerimage: demisto/taxii-server:1.0.0.56695
```suggestion
  dockerimage: demisto/taxii-server:1.0.0.62984
```

2023-06-08 07:15 UTC, RotemAmit commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
> +  dockerimage: demisto/python3:3.10.11.61265
```suggestion
  dockerimage: demisto/python3:3.10.12.62631
```

2023-06-11 14:25 UTC, RotemAmit reviewed
Nice work! Thank you very much for your contribution!

2023-06-12 06:53 UTC, RotemAmit reviewed
Please Update the docker image as in the comments

2023-06-12 06:53 UTC, RotemAmit commented on Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.yml
> +  dockerimage: demisto/taxii-server:1.0.0.62984
```suggestion
  dockerimage: demisto/taxii-server:1.0.0.63049
```

2023-06-12 06:53 UTC, RotemAmit commented on Packs/CybleThreatIntel/ReleaseNotes/2_0_11.md
> +- Updated the Docker image to: *demisto/taxii-server:1.0.0.62984*.
```suggestion
- Updated the Docker image to: *demisto/taxii-server:1.0.0.63049*.
```

2023-06-12 07:23 UTC, RotemAmit commented on Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml
> +  dockerimage: demisto/python3:3.10.12.63049
```suggestion
  dockerimage: demisto/python3:3.10.12.62631
```

2023-06-12 08:15 UTC, RotemAmit approved these changes

2023-06-12 08:15 UTC, merged