Rbr deprecated content
demisto/content pull request #26581
Opened 2023-05-17 12:54 UTC by AdiPeret

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6567

## Description
Replacing Depricated Content for Rapid Breach Response Playbooks

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2021_40444/Playbooks/playbook-CVE-2021-40444_-_MSHTML_RCE.yml
> +        This playbook blocks malicious Indicators using all integrations that are enabled, using the following sub-playbooks:
```suggestion
        This playbook blocks malicious indicators using all integrations that are enabled, using the following sub-playbooks:
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2021_40444/ReleaseNotes/1_0_5.md
> +- Added input `AutoBlockIndicators` - This input determines if to block the indicators automatically or manually using the sub-playbook `Block Indicators - Generic v3`. (Available from Cortex XSOAR 6
```suggestion
- Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the sub-playbook **Block Indicators - Generic v3**. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2021_40444/ReleaseNotes/1_0_5.md
> +- Added input `UserVerification` - This input determines if blocking IPs is should be done with or without user verification.  The IPs blocking is done by using the sub-playbook `Block Indicators - G
```suggestion
- Added the *UserVerification* input. This input determines whether blocking IPs should be done with or without user verification.  The IPs blocking is done by using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
> +description: "Critical RCE Vulnerability: log4j - CVE-2021-44228\n\nOn Dec. 9, 2021, a remote code execution (RCE) vulnerability in Apache log4j 2 was identified being exploited in the wild. Public p
```suggestion
description: "Critical RCE Vulnerability: log4j - CVE-2021-44228\n\nOn Dec. 9, 2021, a remote code execution (RCE) vulnerability in Apache log4j 2 was identified being exploited in the wild. Public proof of concept (PoC) code was released and subsequent investigation revealed that exploitation was incredibly easy to perform. \n\nOn Dec. 14 2021, another vulnerability was discovered related to the log4j 0-day exploit known as CVE-2021-45046.\n\nOn Dec 18 2021, yet another vulnerability was discovered related to the log4j 0-day exploit known as CVE-2021-45105 that allows an attacker with control over Thread Context Map data to cause a denial of service when a crafted string is interpreted. This issue was fixed in Log4j 2.17.0 and 2.12.3.\n\nOn Dec 28 2021, another RCE vulnerability was published for Apache Log4j2, versions 2.0-beta7 through 2.17.0 (excluding security fix releases 2.3.2 and 2.12.4).\nIn order to exploit this vulnerability, an attacker with permission to modify the logging configuration file can construct a malicious configuration using a JDBC Appender with a data source referencing a JNDI URI which can execute remote code. This issue is fixed by limiting JNDI data source names to the java protocol in Log4j2 versions 2.17.1, 2.12.4, and 2.3.2.\n\n**Affected Version**\n\nApache Log4j 2.x <= 2.17.0\n\nThis playbook should be triggered manually or can be configured as a job.\nPlease create a new incident and choose the **CVE-2021-44228 - Log4j RCE** playbook and **Rapid Breach Response** incident type.\n\n**The playbook includes the following tasks:**\n\n* Collect related known indicators from several sources.\n* Indicators and exploitation patterns hunting using PAN-OS, Cortex XDR and SIEM products.\n*Search for possible vulnerable servers using Xpanse and Prisma Cloud.\n* Block indicators automatically or manually.\n\n**Mitigations:**\n* Apache official CVE-2021-44228 patch.\n* Unit42 recommended mitigations.\n* Detection Rules.\n    * Snort\n    * Suricata\n    * Sigma\n    * Yara\n    * Zeek Intel\n\nMore information:\n[Apache Log4j Vulnerability Is Actively Exploited in the Wild (CVE-2021-44228)](https://unit42.paloaltonetworks.com/apache-log4j-vulnerability-cve-2021-44228/)\n\nNote: This is a beta playbook, which lets you implement and test pre-release software. Since the playbook is beta, it might contain bugs. Updates to the pack during the beta phase might include non-backward compatible features. We appreciate your feedback on the quality and usability of the pack to help us identify issues, fix them, and continually improve."
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
> +        This playbook blocks malicious Indicators using all integrations that are enabled, using the following sub-playbooks:
```suggestion
        This playbook blocks malicious indicators using all integrations that are enabled, using the following sub-playbooks:
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2021_44228/ReleaseNotes/1_0_14.md
> +- Added input `AutoBlockIndicators` - This input determines if to block the indicators automatically or manually using the sub-playbook `Block Indicators - Generic v3`. (Available from Cortex XSOAR 6
```suggestion
- Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2021_44228/ReleaseNotes/1_0_14.md
> +- Added input `UserVerification` - This input determines if blocking IPs is should be done with or without user verification.  The IPs blocking is done by using the sub-playbook `Block Indicators - G
```suggestion
- Added the *UserVerification* input. This input determines whether blocking IPs should be done with or without user verification.  The IPs blocking is done by using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2022_26134/Playbooks/playbook-CVE-2022-26134_-_Confluence_RCE.yml
> +        This playbook blocks malicious Indicators using all integrations that are enabled, using the following sub-playbooks:
```suggestion
        This playbook blocks malicious indicators using all integrations that are enabled, using the following sub-playbooks:
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2022_26134/ReleaseNotes/1_0_3.md
> +- Added input `AutoBlockIndicators` - This input determines if to block the indicators automatically or manually using the sub-playbook `Block Indicators - Generic v3`. (Available from Cortex XSOAR 6
```suggestion
- Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/CVE_2022_26134/ReleaseNotes/1_0_3.md
> +- Added input `UserVerification` - This input determines if blocking IPs is should be done with or without user verification.  The IPs blocking is done by using the sub-playbook `Block Indicators - G
```suggestion
- Added the *UserVerification* input. This input determines whether blocking IPs should be done with or without user verification.  The IPs blocking is done by using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-22893_-_Pulse_Connect_Secure_RCE_README.md
> +| SplunkWebshellsQuery | The Splunk search query used for "Hunt Activity Using Splunk".<br/>Please note that there are two specified fields: msg, message. the query will work for both field names. |
```suggestion
| SplunkWebshellsQuery | The Splunk search query used for "Hunt Activity Using Splunk".<br/>Please note that there are two specified fields: msg, message. The query will work for both field names. | index=* sourcetype=pulse:connectsecure "Licenseserverproto.cgi" OR "Secid_canceltoken.cgi" OR "compcheckresult.cgi" OR "Healthcheck.cgi" OR "meeting_testjs.cgi" OR "compcheckjava.cgi" | Optional |
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6.yml
> +      description: "Is the Exchange patched with the March 2021 security updates?\nIf needed, refer to Microsoft post about the patches: \nhttps://techcommunity.microsoft.com/t5/exchange-team-blog/re
```suggestion
      description: "Is the Exchange patched with the March 2021 security updates?\nIf needed, refer to the Microsoft post about the patches: \nhttps://techcommunity.microsoft.com/t5/exchange-team-blog/released-march-2021-exchange-server-security-updates/ba-p/2175901\n "
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6.yml
> +      description: "Follow Microsoft blog post about the interim mitigations.\nThe blog post explains how to configure the interim mitigations and their rollback if needed. \nhttps://msrc-blog.micros
```suggestion
      description: "Follow the Microsoft blog post about the interim mitigations.\nThe blog post explains how to configure the interim mitigations and their rollback if needed. \nhttps://msrc-blog.microsoft.com/2021/03/05/microsoft-exchange-server-vulnerabilities-mitigations-march-2021/\n\nNotes:\n- These mitigations are not a remediation if your Exchange servers have already been compromised, nor are they full protection against an attack.\n- This should only be used as a temporary mitigation until Exchange servers can be fully patched. \n"
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6_README.md
> +Collect indicators to be used in your threat hunting process Retrieve IOCs related to HAFNIUM and the exploited exchange 0-day vulnerabilities Discover IOCs related to the attack Query firewall logs
```suggestion
Collect indicators to be used in your threat hunting process. Retrieve IOCs related to HAFNIUM and the exploited exchange 0-day vulnerabilities. Discover IOCs related to the attack. Query firewall logs to detect malicious network activity. Search endpoint logs for malicious hashes to detect compromised hosts. (Available from Cortex XSOAR 5.5.0). Block indicators Note: This is a beta playbook, which lets you implement and test pre-release software. Since the playbook is beta, it might contain bugs. Updates to the pack during the beta phase might include non-backward compatible features. We appreciate your feedback on the quality and usability of the pack to help us identify issues, fix them, and continually improve. Read more about the attack on our Unit42 blog: https://unit42.paloaltonetworks.com/microsoft-exchange-server-vulnerabilities/ Sources: https://www.splunk.com/en_us/blog/security/detecting-hafnium-exchange-server-zero-day-activity-in-splunk.html https://www.microsoft.com/security/blog/2021/03/02/hafnium-targeting-exchange-servers/
```

Why were the bullets removed?

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6_README.md
>  | BlockIndicatorsAutomatically | Whether to automatically indicators involved with HAFNIUM exploits | False | Optional |
```suggestion
| BlockIndicatorsAutomatically | Whether to automatically block indicators involved with HAFNIUM exploits | False | Optional |
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.yml
> +      description: This playbook queries Splunk for indicators such as file hashes, IP addresses, domains, or urls. It outputs detected users, ip addresses, and hostnames related to the indicators.
```suggestion
      description: This playbook queries Splunk for indicators such as file hashes, IP addresses, domains, or URLs. It outputs detected users, IP addresses, and hostnames related to the indicators.
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.yml
> +      description: Sigma rules file has been downloaded as SigmaRules.yml and is available for download directly from XSOAR.
```suggestion
      description: Sigma rules file has been downloaded as SigmaRules.yml and is available for download directly from Cortex XSOAR.
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +      description: 'The Playbook queries QRadar SIEM for indicators such as file hashes, IP addresses, domains, or urls. '
```suggestion
      description: 'The Playbook queries QRadar SIEM for indicators such as file hashes, IP addresses, domains, or URLs. '
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +      description: This playbook queries Splunk for indicators such as file hashes, IP addresses, domains, or urls. It outputs detected users, ip addresses, and hostnames related to the indicators.
```suggestion
      description: This playbook queries Splunk for indicators such as file hashes, IP addresses, domains, or URLs. It outputs detected users, IP addresses, and hostnames related to the indicators.
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +  description: "possible values: True/False. \nWhether to provide user verification for blocking IPs. \n\nFalse - No prompt will be displayed to the user.\nTrue - The server will ask the user for blo
```suggestion
  description: "Whether to provide user verification for blocking IPs. \n\nFalse - No prompt will be displayed to the user.\nTrue - The server will ask the user for blocking verification and will display the blocking list."
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing_README.md
> +| UserVerification | possible values: True/False. <br/>Whether to provide user verification for blocking IPs. <br/><br/>False - No prompt will be displayed to the user.<br/>True - The server will ask
```suggestion
| UserVerification | Whether to provide user verification for blocking IPs. <br/><br/>False - No prompt will be displayed to the user.<br/>True - The server will ask the user for blocking verification and will display the blocking list. | False | Optional |
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +    Possible values: True/False.  Default: True.
```suggestion
   
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +
Possible values: True/False.  Default: True.

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing_README.md
> +| AutoBlockIndicators | Possible values: True/False.  Default: True.<br/>Should the given indicators be automatically blocked, or should the user be given the option to choose?<br/><br/>If set to Fal
```suggestion
| AutoBlockIndicators | Should the given indicators be automatically blocked, or should the user be given the option to choose?<br/><br/>If set to False - no prompt will appear, and all provided indicators will be blocked automatically.<br/>If set to True - the user will be prompted to select which indicators to block. | True | Optional |
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
> +      description: "Further investigate the incident (endpoints, entry point, etc.').\nIf Expanse found SolarWinds C2 connection, investigate the internal server too. "
```suggestion
      description: "Further investigate the incident (endpoints, entry point, etc.').\nIf Expanse found SolarWinds C2 connection, investigate the internal server too."
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
> +      description: "This playbook blocks malicious IP addresses using all integrations that are enabled. The direction of the traffic that will be blocked is determined by the XSOAR user (and set by
```suggestion
      description: "This playbook blocks malicious IP addresses using all integrations that are enabled. The direction of the traffic that will be blocked is determined by the Cortex XSOAR user (and set by default to outgoing)\nNote the following:\n-  some of those integrations require specific parameters to run, which are based on the playbook inputs. Also, certain integrations use FW rules or appended network objects.\n- Note that the appended network objects should be specified in blocking rules inside the system later on. \n\n\nSupported integrations for this playbook [Network security products such as FW/WAF/IPs/etc.]: \n\n* Check Point Firewall\n* Palo Alto Networks PAN-OS\n* Zscaler\n* FortiGate\n* Aria Packet Intelligence\n* Cisco Firepower \n* Cisco Secure Cloud Analytics\n* Cisco ASA\n* Akamai WAF\n* F5 SilverLine\n* ThreatX\n* Signal Sciences WAF\n* Sophos Firewall\n\n"
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
```suggestion
- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Added input `AutoBlockIndicators` - This input determines if to block the indicators automatically or manually using the sub-playbook `Block Indicators - Generic v3`. (Available from Cortex XSOAR 6
```suggestion
- Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Added input `UserVerification` - This input determines if blocking IPs is should be done with or without user verification.  The IPs blocking is done by using the sub-playbook `Block Indicators - G
```suggestion
- Added the *UserVerification* input. This input determines whether blocking IPs should be done with or without user verification.  The IPs blocking is done by using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Added input `UserVerification` - This input determines if blocking IPs is should be done with or without user verification.  The IPs blocking is done by using the sub-playbook `Block Indicators - G
```suggestion
- Added the *UserVerification* input. This input determines whether blocking IPs should be done with or without user verification.  The IPs blocking is done by using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Added input `AutoBlockIndicators` - This input determines if to block the indicators automatically or manually using the sub-playbook `Block Indicators - Generic v3`. (Available from Cortex XSOAR 6
```suggestion
- Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Added input `AutoBlockIndicators` - This input determines if to block the indicators automatically or manually using the sub-playbook `Block Indicators - Generic v3`. (Available from Cortex XSOAR 6
```suggestion
- Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:56 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Added input `UserVerification` - This input determines if blocking IPs is should be done with or without user verification.  The IPs blocking is done by using the sub-playbook `Block Indicators - G
```suggestion
- Added the *UserVerification* input. This input determines whether blocking IPs should be done with or without user verification.  The IPs blocking is done by using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-22 12:57 UTC, ShirleyDenkberg commented
@michalgold @idovandijk doc review completed.

2023-05-29 12:17 UTC, ShirleyDenkberg commented
@michalgold @idovandijk @OmriItzhak Doc review completed.

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/CVE_2021_40444/ReleaseNotes/1_0_5.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Is **Block Indicators - Generic v3** a playbook or a sub-playbook?

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/CVE_2021_44228/ReleaseNotes/1_0_14.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Is **Block Indicators - Generic v3** a playbook or a sub-playbook?

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/CVE_2022_26134/ReleaseNotes/1_0_3.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Is **Block Indicators - Generic v3** a playbook or a sub-playbook?

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-22893_-_Pulse_Connect_Secure_RCE_README.md
> +This playbook should be trigger manually and includes the following tasks:
```suggestion
This playbook should be triggered manually and includes the following tasks: 
```

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.yml
> +        This playbook blocks malicious Indicators using all integrations that are enabled, using the following sub-playbooks:
```suggestion
        This playbook blocks malicious indicators using all integrations that are enabled, using the following sub-playbooks:
```

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
> +      description: "Further investigate the incident (endpoints, entry point, etc.').\nIf Expanse found SolarWinds C2 connection, investigate the internal server too."
```suggestion
      description: "Further investigate the incident (endpoints, entry point, etc.').\nIf Xpanse found SolarWinds C2 connection, investigate the internal server too."
```

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Is **Block Indicators - Generic v3** a playbook or a sub-playbook?

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Is **Block Indicators - Generic v3** a playbook or a sub-playbook?

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Is **Block Indicators - Generic v3** a playbook or a sub-playbook?

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex
```suggestion
- Added the *AutoBlockIndicators* input. This input determines whether to block the indicators automatically or manually using the **Block Indicators - Generic v3** sub-playbook. (Available from Cortex XSOAR 6.5.0).
```

2023-05-31 06:55 UTC, ShirleyDenkberg commented on Packs/WhisperGateCVE-2021-32648/ReleaseNotes/1_0_4.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Is **Block Indicators - Generic v3** a playbook or a sub-playbook?

2023-05-31 06:56 UTC, ShirleyDenkberg commented
@AdiPeret I reviewed the docs again.  Not sure why the RN are failing.

2023-05-31 06:57 UTC, AdiPeret commented on Packs/CVE_2021_40444/ReleaseNotes/1_0_5.md
> +- Replaced the **Block Indicators - Generic v2** sub-playbook with the new **Block Indicators - Generic v3** playbook. (Available from Cortex XSOAR 6.5.0).
Playbook

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +      DomainToBlock:
need to remove `DomainToBlock`
Please ensure that the argument values on sub-playbook v3 match the argument values on the previous version of the sub-playbook Block Indicators - Generic v2.

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +      EmailToBlock:
need to remove EmailToBlock

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +      FilesToBlock:
need to remove FileToBlock

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +                  simple: DBotScore.Type
Please ensure that the argument values on sub-playbook v3 match the argument values on the previous version of the sub-playbook Block Indicators - Generic v2. For example on v2 the value is ExtractedIndicators.IP and here is DBotScore.Indicator where DBotScore.Type Equals ip.

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +                  simple: DBotScore.Indicator
same for the MD5

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +      SHA256:
same for sha256

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
> +                  simple: DBotScore.Type
same for url

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/ReleaseNotes/1_0_4.md
> +##### New: WhisperGate and HermeticWiper & CVE-2021-32648
There are duplicates of the changes described in the release note.
Delete the first description ##### New: WhisperGate and HermeticWiper & CVE-2021-32648

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/ReleaseNotes/1_0_4.md
> +- Added configuration `fromversion: 6.0.0` and `toversion: 6.4.9`
please delete the following lines:
- Added configuration `fromversion: 6.0.0` and `toversion: 6.4.9`
- Added configuration `fromversion: 6.5.0`

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +##### CVE-2021-22893 - Pulse Connect Secure RCE
Let's talk about it.  In this case the release note should include only a description and info about changes.

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +      MD5:
Please ensure that the argument values on sub-playbook v3 match the argument values on the previous version of the sub-playbook Block Indicators - Generic v2. For example on v2 the value is ExtractedIndicators and here is DBotScore.Indicator

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +                  simple: DBotScore.Indicator
same for sha256

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +                  simple: DBotScore.Type
same for url

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +      UserVerification:
You need to add new input for UserVerification and use it on this task.
To ensure that the flow is not affected, the input value should be set to false.

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +      AutoBlockIndicators:
You need to add new input for AutoBlockIndicator and use it on this task.

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +                  simple: DBotScore.Type
Please ensure that the argument values on sub-playbook v3 match the argument values on the previous version of the sub-playbook Block Indicators - Generic v2. For example on v2 the value is PANWHunting.DetectedExternalIPs and here is DBotScore.Indicator

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +                  simple: DBotScore.Indicator
Please ensure that the argument values on sub-playbook v3 match the argument values on the previous version of the sub-playbook Block Indicators - Generic v2. For example on v2 the value is ExtraFile.MD5 and here is DBotScore.Indicator

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +                  simple: DBotScore.Indicator
Please ensure that the argument values on sub-playbook v3 match the argument values on the previous version of the sub-playbook Block Indicators - Generic v2. For example on v2 the value is ExtraFile.SHA256 and here is DBotScore.Indicator

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +                  simple: DBotScore.Type
Please ensure that the argument values on sub-playbook v3 match the argument values on the previous version of the sub-playbook Block Indicators - Generic v2. For example on v2 the value is URL.Data and here is DBotScore.Indicator

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +      UserVerification:
You need to add new input for UserVerification and use it on this task.
To ensure that the flow is not affected, the input value should be set to false.

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Removed expanse-get-risky-flows and expanse-list-risk-rules as they are EOD with no suitable replacements
fix it to EOL

2023-06-01 14:47 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_31.md
> +- Modified `fromversion: 6.0.0` and `toversion: 6.4.9`
The following lines should be removed:

Added configuration fromversion: 5.5.0 and toversion: 6.4.9
Added configuration fromversion: 6.5.

2023-06-11 12:07 UTC, OmriItzhak requested changes

2023-06-11 12:07 UTC, OmriItzhak commented on Packs/SpringRCEs/Playbooks/playbook-Spring_Core_and_Cloud_Function_SpEL_RCEs.yml
> +        simple: config from cloud.resource where finding.type = 'Host Vulnerability' AND protection.finding.name IN ('CVE-2022-22963', 'CVE-2022-22965')
should be: 
network from vpc.flow_record where bytes > 0 AND destination.resource IN ( resource where finding.type IN ( 'Host Vulnerability' ) AND finding.source IN ( 'Prisma Cloud' ) AND finding.name IN ('CVE-2022-22963', 'CVE-2022-22965') ) AND source.publicnetwork IN ('Internet IPs', 'Suspicious IPs')

2023-06-11 12:07 UTC, OmriItzhak commented on Packs/SpringRCEs/Playbooks/playbook-Spring_Core_and_Cloud_Function_SpEL_RCEs.yml
> +        simple: config from cloud.resource where finding.type = 'Host Vulnerability' AND protection.finding.name = 'CVE-2021-44228'
should be:
config from cloud.resource where finding.type = 'Host Vulnerability' AND protection.finding.name IN ('CVE-2022-22963', 'CVE-2022-22965')

2023-06-11 12:07 UTC, OmriItzhak commented on Packs/SpringRCEs/Playbooks/playbook-Spring_Core_and_Cloud_Function_SpEL_RCEs.yml
> +    skipunavailable: false
should be  skipunavailable:true

2023-06-11 12:07 UTC, OmriItzhak commented on Packs/SpringRCEs/Playbooks/playbook-Spring_Core_and_Cloud_Function_SpEL_RCEs.yml
> +    skipunavailable: false
should be  skipunavailable:true

2023-06-11 12:07 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +      MD5:
please change to ExtractedIndicators.File

2023-06-11 12:07 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +      SHA256:
please change to ExtractedIndicators.File

2023-06-11 12:07 UTC, OmriItzhak commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +      URL:
please change to ExtractedIndicators.URL

2023-06-11 14:14 UTC, AdiPeret commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack_6_5.yml
> +          root: inputs.BlockIndicatorsAutomatically
Already Exist
nputs:
- key: UserVerification
  value:
    simple: "False"
  required: false
  description: "Possible values: True/False.\nWhether to provide user verification for blocking IPs. \n\nFalse - No prompt will be displayed to the user.\nTrue - The server will ask the user for blocking verification and will display the blocking list."
  playbookInputQuery:
- key: AutoBlockIndicators
  value:
    simple: "True"
  required: false

2023-06-11 14:19 UTC, AdiPeret commented on Packs/WhisperGateCVE-2021-32648/Playbooks/playbook-WhisperGate_&_CVE-2021-32648_6_5.yml
> +      MD5:
That comment is not clear, what should be ExtractedIndicators.File? the MD5 section?

2023-06-11 14:35 UTC, AdiPeret commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +      '#none#':
this is what i see not right?
iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "83"

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/CVE_2021_44228/Playbooks/playbook-CVE-2021-44228_-_Log4j_RCE.yml
There is a warning when uploading this playbook to XSOAR

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/.pack-ignore
> +[file:playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml]
why did you add the ignore code BA110?

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
There is a warning when uploading this playbook to XSOAR

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
> +      playbookName: Block Indicators - Generic v2
There are no argument keys on this playbook

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
There is a warning when uploading this playbook to XSOAR

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +      UserVerification:
use the input UserVerification (value:false)

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +      AutoBlockIndicators:
please add the input AutoBlockIndicators and use it here

2023-06-15 14:41 UTC, OmriItzhak commented on Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml
> +      device-group:
please add logforwarding argument

2023-06-18 08:05 UTC, AdiPeret commented on Packs/MajorBreachesInvestigationandResponse/.pack-ignore
> +[file:playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6_5.yml]
Ignoring words Demisto & Playbook

2023-06-28 07:17 UTC, OmriItzhak approved these changes

2023-07-16 13:43 UTC, merged