Get user devices generic
demisto/content pull request #26591
Opened 2023-05-17 16:08 UTC by tomer-pan

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6611

## Description
Generic playbooks for retrieving user devices by email/username.

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Email_Address_-_Generic_README.md
> +| ServiceNow.Computer.AssetTag | Computer Asset tag. | unknown |
```suggestion
| ServiceNow.Computer.AssetTag | Computer asset tag. | unknown |
```

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Username_-_Generic_README.md
> +| JAMF.MobileDevice.wifi_mac_address | The mobile device WIFI MAC address. | unknown |
```suggestion
| JAMF.MobileDevice.wifi_mac_address | The mobile device WI-FI MAC address. | unknown |
```

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Email_Address_-_Generic_README.md
> +| GSuite.MobileDevices.MobileListObjects.userAgent | Gives information about the mobile device such as the operating system version. | unknown |
```suggestion
| GSuite.MobileDevices.MobileListObjects.userAgent | Information about the mobile device such as the operating system version. | unknown |
```

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Username_-_Generic_README.md
> +| GSuite.MobileDevices.MobileListObjects.userAgent | Gives information about the mobile device such as the operating system version. | unknown |
```suggestion
| GSuite.MobileDevices.MobileListObjects.userAgent | Information about the mobile device such as the operating system version. | unknown |
```

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Username_-_Generic_README.md
> +Please note that not all of the supported integrations will be able to retrieve this information.
```suggestion
Note that not all of the supported integrations will be able to retrieve this information.
```

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_by_Username_-_Generic_README.md
> +| GsuiteCustomerID | In case of using Google Workspace, a customer ID is needed. |  | Optional |
```suggestion
| GsuiteCustomerID | If using Google Workspace, a customer ID is needed. |  | Optional |
```

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/ReleaseNotes/2_3_67.md
> +Please note that not all of the supported integrations will be able to retrieve this information.
```suggestion
Note that not all of the supported integrations will be able to retrieve this information.
```

2023-05-18 08:10 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/Playbooks/playbook-Get_User_Devices_-_Generic_README.md
> +In order to get the full list of supported integrations, please read the following sub-playbooks descriptions:
```suggestion
In order to get the full list of supported integrations, read the following sub-playbooks descriptions:
```

2023-05-18 08:11 UTC, ShirleyDenkberg commented
@idovandijk @AdiPeret @michalgold Doc review completed.

2023-05-18 09:50 UTC, idovandijk requested changes
Great playbooks. Looking forward to have these in content! You've put a lot of effort into this. I did find some small mistakes. My comments are numbered to make it easier for you to refer to them in your replies:

### Get User Devices by Username - Generic
I like the trick you did here :)
![image](https://github.com/demisto/content/assets/43602124/8e7cdfd6-4aa2-4bd2-9dfc-c8622f399863)

1. The SetMultipleValues task doesn't work correctly in my test:
![image](https://github.com/demisto/content/assets/43602124/c4acbbf6-8cb4-4768-84db-99cb97f5af41)
please check why the "integration" field is empty. For testing you can use the data I sent you on Slack. Maybe you should use `SetAndHandleEmpty` like you did in the other integrations?

2. The Microsoft Defender Advanced Threat Protection integration is deprecated. Please check if there is an alternative that you can replace it with, or remove it.

3. Is it possible to get devices from Google without `GsuiteCustomerID`?

4. AD seems to be missing an "OS" output here, but I do see it in the `Get User Devices by Email Address` playbook

### Get User Devices by Email Address - Generic

5. Please add an Else path for MS Graph:
![image](https://github.com/demisto/content/assets/43602124/b16c8b59-bba0-44ca-a27f-efe9e234d58b)


### Get User Devices - Generic
6. No need to append UserDevices. Task number 3 will only happen once both playbooks finished. You can simply `Set` the UserDevices and apply a `Unique` filter (without appending). Correct me if I'm wrong.

7. Please fix description - UserDevices is an object containing various data fields (not just name):
![image](https://github.com/demisto/content/assets/43602124/27f029a0-8eee-4925-b713-54470936ad5c)

8. Maybe this is not fixable, but if we find the same data by username and by email, we would have somewhat duplicated data. This is just an FYI:
![image](https://github.com/demisto/content/assets/43602124/200a9d7b-da70-4533-b010-2c9c04037a25)


### General Comments
9. You are outputting "Type" for AD, but "Model" for all other integrations. Please fix all occurrences so your outputs are consistent with the outputs declared in the playbooks and with the description of the playbook:
![image](https://github.com/demisto/content/assets/43602124/24078411-f089-4823-9583-d39d0333492f)
![image](https://github.com/demisto/content/assets/43602124/c745efcb-012d-40c2-b850-e7937304650b)

Note that in the descriptions, outputs and AD you are using "Type". All the other integrations use "Model" in their SetAndHandleEmpty tasks. The change requires updating the declared outputs, playbook descriptions and READMEs.

10. Jamf is also outputting MAC address:
![image](https://github.com/demisto/content/assets/43602124/14b661ce-17e1-4bdf-96cb-ec019281d767)

let's add it to the UserDevices object. Note that it requires the change in both playbooks, their declared UserDevices outputs (need to add UserDevices.MACAddress), and the descriptions of the 3 playbooks, as well as the readmes.

2023-05-22 12:56 UTC, tomer-pan commented
@idovandijk All of your suggestions/comments were fixed and implemented.

2023-05-24 13:06 UTC, idovandijk approved these changes
GJ!

2023-05-25 05:28 UTC, merged