Update OpenAiChatGPTV3_description.md
demisto/content pull request #26641
Opened 2023-05-19 10:08 UTC by sepaprivate

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-05-21 15:04 UTC, RotemAmit requested changes
Thank you very much for your contribution! 
Just a few small notes:
* Please update the docker image tag to the latest numeric tag. You can check for the most updated version of demisto/python3 here: https://hub.docker.com/r/demisto/python3/tags .
* Please bump the version of the pack in the pack_metadata.json file and add notes describing your changes to a new Release Notes file. 
To do that, please run the `demisto-sdk update-release-notes` command. for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

2023-05-30 07:47 UTC, RotemAmit commented
Hi @sepaprivate,
Haven’t heard from you since I published my review.
Do you need any help with something?
Please don’t hesitate to reach out to me here or on Slack.
Thanks again.

2023-05-30 09:16 UTC, sepaprivate commented
> Hi @sepaprivate,
> Haven’t heard from you since I published my review.
> Do you need any help with something?
> Please don’t hesitate to reach out to me here or on Slack.
> Thanks again.

Hi @RotemAmit, apology I got distracted with another development. I will work on that today. I have an issue with my development environment so I will work on it manually here

2023-06-06 12:45 UTC, RotemAmit approved these changes

2023-06-06 12:45 UTC, merged