DIsplayHtmlWithImages: added the dynamic section script
demisto/content pull request #26945
Opened 2023-05-23 12:16 UTC by ilappe

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-81822

## Description
Added a new dynamic-section script in order to display HTML with image reference as `cid:image_id`

## Screenshots
<img width="541" alt="image" src="https://github.com/demisto/content/assets/79846863/ad85fe80-9ece-437c-8709-66b6d3ff6e61">

## Minimum version of Cortex XSOAR
- [x] 6.5.0

2023-05-24 07:51 UTC, DeanArbel approved these changes
Looks good

2023-05-28 12:15 UTC, idovandijk requested changes
Please see comment for now. I'm running a few more tests

2023-05-28 12:15 UTC, idovandijk commented on Packs/CommonScripts/Scripts/DisplayHTMLWithImages/DisplayHTMLWithImages.py
> +    email_html = custom_fields.get('renderedhtmll', '') or \
Please fix `renderedhtmll` to be `renderedhtml`

2023-05-28 12:48 UTC, idovandijk requested changes
Please note that if all fields are empty it's showing some data. It should be empty instead:
![image](https://github.com/demisto/content/assets/43602124/793fa719-9276-4a6d-9861-033849553e31)

Also when Rendered HTML was empty and Email HTML had data, the dynamic section showed all the "None" values and only then displayed the data that it was supposed to display:
![image](https://github.com/demisto/content/assets/43602124/ea59ef6d-2ac4-4cfa-ba65-b7d2bf5353da)

Other than this it looked fine in my tests, great job

2023-05-29 07:31 UTC, idovandijk approved these changes
Great!

2023-05-29 07:34 UTC, merged