Expander v2 Pack enhancements - batch 1
demisto/content pull request #27006
Opened 2023-05-26 20:20 UTC by andrew-paloalto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
This update adds a new relatively simple default enrichment playbook for Expander v2 alerts. Additionally it adds several new widgets and a dashboard.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2023-05-29 11:23 UTC, RotemAmit commented
> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @RotemAmit will know the proposed changes are ready to be reviewed.

Thank you very much for your contribution! Please register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form. Thank you!

2023-05-30 23:17 UTC, johnnywilkes requested changes
@andrew-paloalto , did you run `demisto-sdk format` and `demisto-sdk validate` on all the widgets?  That might resolve some of validation errors

2023-05-30 23:17 UTC, johnnywilkes commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +
Please make sure the release notes (especially prefixes) match the template: https://xsoar.pan.dev/docs/documentation/release-notes#general

2023-06-07 08:28 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- Added a new widget that includes the number of Active Xpanse Incidents without an assignee.
```suggestion
Added a new widget that includes the number of active Cortex Xpanse incidents without an assignee.
```

2023-06-07 08:28 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- Added a new widget that includes the number of Active Xpanse Incidents with an assignee.
```suggestion
Added a new widget that includes the number of active Cortex Xpanse incidents with an assignee.
```

2023-06-07 08:28 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- Added a new widget that highlights the most common Xpanse Incidents by port.
```suggestion
Added a new widget that highlights the most common Cortex Xpanse incidents by port.
```

2023-06-07 08:28 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- Added a new widget that highlights the most common Xpanse Incidents by protocol.
```suggestion
Added a new widget that highlights the most common Cortex Xpanse incidents by protocol.
```

2023-06-07 08:28 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- Added a new widget that includes a timeline view of new high and critical severity Xpanse Incidents.
```suggestion
Added a new widget that includes a timeline view of new high and critical severity Cortex Xpanse incidents.
```

2023-06-07 08:28 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- Updated the Xpanse alert layout to include several new fields.
```suggestion
Updated the Cortex Xpanse alert layout to include several new fields.
```

2023-06-07 08:29 UTC, ShirleyDenkberg commented
@johnnywilkes @RotemAmit Doc review completed.

2023-06-07 18:08 UTC, johnnywilkes reviewed
to fix validation error

2023-06-07 18:08 UTC, johnnywilkes commented on Packs/CortexXpanse/Playbooks/Xpanse_-_Alert_Enrichment.yml
> +fromversion: 6.5.0
```suggestion
fromversion: 6.8.0
```

2023-06-07 18:08 UTC, johnnywilkes commented on Packs/CortexXpanse/Playbooks/Xpanse_-_Alert_Handler.yml
> +fromversion: 6.5.0
```suggestion
fromversion: 6.8.0
```

2023-06-07 18:24 UTC, johnnywilkes reviewed
I think this should take care of the release note errors

2023-06-07 18:24 UTC, johnnywilkes commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- This dashboard provides a high level view of incidents from Cortex Xpanse.
```suggestion
- Added a dashboard that provides a high level view of incidents from Cortex Xpanse.
```

2023-06-07 18:24 UTC, johnnywilkes commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- New: **Xpanse Service Validation**
```suggestion
- Added the incident field **Xpanse Service Validation** which keeps track of service validation details.
```

2023-06-07 18:24 UTC, johnnywilkes commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- New: **Xpanse Provider**
```suggestion
- Added the incident field **Xpanse Provider** which keeps track of the provider of the service.
```

2023-06-07 18:24 UTC, johnnywilkes commented on Packs/CortexXpanse/ReleaseNotes/1_0_4.md
> +- New: **Xpanse Service Classifications**
```suggestion
- Added the incident field **Xpanse Service Classifications** which keeps track of active service classifications.
```

2023-06-07 18:33 UTC, johnnywilkes requested changes
Lets see if this fixed validation errors

2023-06-07 18:33 UTC, johnnywilkes commented on Packs/CortexXpanse/IncidentTypes/incidenttype-Xpanse_Alert.json
>      "fromVersion": "6.5.0"
```suggestion
    "fromVersion": "6.8.0"
```

2023-06-07 20:30 UTC, johnnywilkes commented
@RotemAmit , what do you recommend for the current validation error?  This all stems from me setting `fromversion` for `GCP - Enrichment` playbook in https://github.com/demisto/content/pull/25809/files#diff-79ca7bf9df6cc6a406b7b7bca7c5ab11e17e4250942ad6f1eef54c71a93e380d

`Xpanse_-_Alert_Enrichment` references `GCP - Enrichment`, `Xpanse - Alert Handler` references `Xpanse_-_Alert_Enrichment`, and `incidenttype-Xpanse_Alert.json` references `Xpanse - Alert Handler`

2023-06-08 08:18 UTC, RotemAmit commented
> @RotemAmit , what do you recommend for the current validation error? This all stems from me setting `fromversion` for `GCP - Enrichment` playbook in https://github.com/demisto/content/pull/25809/files#diff-79ca7bf9df6cc6a406b7b7bca7c5ab11e17e4250942ad6f1eef54c71a93e380d
> 
> `Xpanse_-_Alert_Enrichment` references `GCP - Enrichment`, `Xpanse - Alert Handler` references `Xpanse_-_Alert_Enrichment`, and `incidenttype-Xpanse_Alert.json` references `Xpanse - Alert Handler`

I see that you changed the fromVersion in the file Packs/CortexXpanse/IncidentTypes/incidenttype-Xpanse_Alert.json from 6.5.0 to 6.8.0. try to change it back to 6.5.0, and see if it helps. Notice that this change will probably require a change in the field fromVersion to 6.5.0 in all the other files as well.

2023-06-08 22:05 UTC, efelmandar commented
@andrew-paloalto @johnnywilkes I reviewed the widgets and dashboard and everything looks great! nice work 👍

2023-06-09 12:28 UTC, johnnywilkes approved these changes
@andrew-paloalto , I approve this PR
@RotemAmit , please merge when possible

2023-06-11 06:44 UTC, RotemAmit reviewed
Thank you very much for your contribution!
Please resolve the validation errors regarding the release notes.

2023-06-13 06:52 UTC, RotemAmit approved these changes

2023-06-13 06:52 UTC, merged