Skyhigh SWG init
demisto/content pull request #27060
Opened 2023-05-30 14:29 UTC by ckaadic

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
McAfee Web Gateway is now Skyhigh Secure Webgateway. This pack includes the rebranding, a change from javascript to python and a new command.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2023-06-05 07:50 UTC, RotemAmit commented
Hi @ckaadic!
Thank you again for your contribution!
After some checks we made, it has been decided to take this issue of rebranding McAfee Web Gateway into Skyhigh Secure Webgateway internally and it will be solved by the content dev team.
Therefor I'm closing this PR. Thank you again.

2023-06-08 07:44 UTC, eyalpalo requested changes
Nice work! Thank you for that contribution!
Some notes:
1. In general, comments regarding a code that is shown in several methods is relevant to all (for example, the note about ElementTree).
2. test playbook need to be added. you can find some useful info here - https://xsoar.pan.dev/docs/integrations/test-playbooks.
3. let's add some unit tests to test what happens once the API does not return result as expected or exception.

2023-06-08 20:49 UTC, ckaadic commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.py
> +    return "ok"
connectivity and authentication are covered by the the with client part in main and will return indicative messages in the added try/except block in main

2023-06-09 20:58 UTC, ckaadic commented
@eyalpalo I changed the code following your notes and had to add 2 additional commands to create and delete lists to make the test playbook function best. However I am not sure what you want me to test in point 3, because the API only returns valid xml or 40X in other case:
>     3. let's add some unit tests to test what happens once the API does not return result as expected or exception.

- It is not possible to test invalid input, invalid session or actions on non existing content (delete non existing entry). These all return 40X status codes which raises DemistoException from the inherited Baseclient.
- It is not possible to test invalid xml response. This will always result in an error of the xml2json function.
- The only thing I can add is missing whole parts in the xml response which is no realistic scenario. I can add some of these, if this fulfills point 3.

2023-06-12 12:23 UTC, eyalpalo requested changes
Hi @ckaadic. Really nice job overall!
Almost there, some last minor comments.
Also, understood your point regarding the unit tests, let's stick to the current tests.

Also, I'm asking Shirley for doc-review, after her comments lets schedule a demo

2023-06-12 12:24 UTC, eyalpalo commented
@ShirleyDenkberg Can you please conduct a doc review on that PR? Thanks!

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    - description: List ID
```suggestion
    - description: List ID.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    - description: Entry Position in table
```suggestion
    - description: Entry position in the table.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List ID of entry's list
```suggestion
      description: List ID of the entry's list.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: Entry Name
```suggestion
      description: Entry name.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: Entry position in list
```suggestion
      description: Entry position in the list.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: Entry Description
```suggestion
      description: Entry description.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    - description: List ID
```suggestion
    - description: List ID.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    - description: Entry Position in table
```suggestion
    - description: Entry position in the table.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    - description: Entry description
```suggestion
    - description: Entry description.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: Entry Name
```suggestion
      description: Entry name.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: Entry Description
```suggestion
      description: Entry description.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    - description: List ID
```suggestion
    - description: List ID.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List ID
```suggestion
      description: List ID.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Title
```suggestion
      description: List title.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Type
```suggestion
      description: List type.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Description
```suggestion
      description: List description.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    description: Create a new list
```suggestion
    description: Create a new list.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Title
```suggestion
      description: List title.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Type
```suggestion
      description: List type.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Description
```suggestion
      description: List description.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +    - description: List ID
```suggestion
    - description: List ID.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List ID
```suggestion
      description: List ID.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Title
```suggestion
      description: List title.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Type
```suggestion
      description: List type.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/Integrations/SkyhighSecureWebGatewayOnPrem/SkyhighSecureWebGatewayOnPrem.yml
> +      description: List Description
```suggestion
      description: List description.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/README.md
> +Skyhigh Secure Web Gateway (SWG) is a cloud-native web security solution that provides the an advanced layered protection from threats and data loss with integrated RBI, CASB, and DLP capabilities in
```suggestion
Skyhigh Secure Web Gateway (SWG) is a cloud-native web security solution that provides an advanced layered protection from threats and data loss with integrated RBI, CASB, and DLP capabilities in the web and cloud. It enables organizations to implement a simplified SSE architecture that delivers security, scalability, and availability for a distributed and remote workforce.
```

2023-06-13 04:55 UTC, ShirleyDenkberg commented on Packs/SkyhighSecureWebGateway/README.md
> +* Manages the block and allow lists within Skyhihgh SWG
```suggestion
Manages the block and allow lists within Skyhigh SWG.
```

2023-06-13 04:56 UTC, ShirleyDenkberg commented
@eyalpalo Doc review completed.

2023-06-14 15:03 UTC, eyalpalo commented
Demo summary : @ckaadic 
1. Change the context prefix of the get available lists command to ```List```.
2. Insert the list_entries context entry under the list object.
3. When inserting a list entry, it needs to replace the old one in the context data.
4. Delete should not write to context.
5. Integration prefix - still to decide, will be updated tomorrow.

2023-06-14 19:18 UTC, ckaadic commented
@eyalpalo 
Adjusted the context to meet the requirements:
* Structure of SWG.List.ListEntries
* ListEnries data gets replaced when run get-list, modify-list, insert-entry, get-list-entry
* both delete commands do not write to context anymore
* adjusted testdata, test-playbook, yml and readme to meet the new structure

2023-06-15 14:01 UTC, eyalpalo commented
@ckaadic Looks great, lets have a 10 minute talk to see that everything is functioning as it should be and well merge it.
Also, pay attention that you missed 2 notes from Shirley in the doc review.

2023-06-18 08:38 UTC, eyalpalo approved these changes

2023-06-18 08:38 UTC, merged