add fetch logs to nightly build fetch integrations
demisto/content pull request #27124
Opened 2023-06-01 08:43 UTC by jbabazadeh

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
add fetch logs to fetch integrations
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-06-01 10:45 UTC, yuvalbenshalom requested changes
looks good.
see my comment.

2023-06-01 10:45 UTC, yuvalbenshalom commented on Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
> +                skip_incidents += 1
you cont them, but do not print.
print the skipped incidents

2023-06-06 10:01 UTC, yuvalbenshalom requested changes
the same combat about id and time like in the other PR.

2023-06-07 06:10 UTC, jbabazadeh commented on Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
> +                    smaller than the last fetch.""")
DONE

2023-06-08 09:27 UTC, yuvalbenshalom approved these changes

2023-06-11 08:21 UTC, merged