Fixed the way to return a null value. Instead of returning 'None', it will return a meaningful error message on FirstArrayElement and LastArrayElement
demisto/content pull request #27212
Opened 2023-06-05 05:59 UTC by spearmin10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
FirstArrayElement/LastArrayElement doesn't return corect values for null value retrieved from the argument.

## Screenshots
[https://paloaltonetworks.zoom.us/rec/share/QjLXMHQpAk-GFGfjlSnzFniSMDKnBlRl7bpLMVXnA2I9aKnMiSIBC4fZigosVYhB.ISBX-y6j_bUFkgVB](https://urldefense.proofpoint.com/v2/url?u=https-3A__paloaltonetworks.zoom.us_rec_share_QjLXMHQpAk-2DGFGfjlSnzFniSMDKnBlRl7bpLMVXnA2I9aKnMiSIBC4fZigosVYhB.ISBX-2Dy6j-5FbUFkgVB&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=Ofm-xnwIyR-wX5Qd5Wta5yebOWzrIzmkRd55xrRodnY&m=57x3um1RlcZV_-M7_Du2mAFJH_mpa4vGS_ZmxCojFsk40tMvzbGur0B9Mzn-h05w&s=qGz1YlYiRg0PTqT0HOPVGzcf4jMs2Z4hxA8tGkSeE_g&e=)
Passcode： K5!jz3zM7h

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-06-05 12:06 UTC, michal-dagan reviewed
Hi @spearmin10, Thank you very much for your contribution! Great job finding this issue and fixing it!

An alternative to the current solution:
instead of -
`    if value is None:
        value = []`
->  `demisto.results(value or [])`

2023-06-05 12:55 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/ReleaseNotes/1_2_20.md
> +- Fixed the way to return a null value. Instead of returning 'None', it will return a meaningful error message.
```suggestion
Fixed the way to return a null value. Instead of returning 'None', it will return a meaningful error message.
```

2023-06-05 12:55 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/ReleaseNotes/1_2_20.md
> +- Fixed the way to return a null value. Instead of returning 'None', it will return a meaningful error message.
```suggestion
Fixed the way to return a null value. Instead of returning 'None', it will return a meaningful error message.
```

2023-06-05 12:55 UTC, ShirleyDenkberg commented
@michal-dagan Doc review completed.

2023-06-06 12:26 UTC, michal-dagan requested changes
Hi @spearmin10 
After consulting with our team, we thought that in order not to break back for customers who want the current behavior, it would be best to add an "applyIfEmpty" argument, as the [SetIfEmpty](https://github.com/demisto/content/tree/master/Packs/FiltersAndTransformers/Scripts/SetIfEmpty) automation has, so that customers could specify the behavior they want.

2023-06-07 03:30 UTC, spearmin10 commented
@michal-dagan Thta's a good idea. But only adding `defaultValue` and `applyIfEmpty` didn't work on the issue, as there isn't good way to give an empty array to `defaultValueType`. It needs one more parameter which is `defaultValueType` to choose json value to give an empty array to give it to the value.

On the other hand, I found a workaround that putting `SetIfEmpty` with empty parameters right after `FirstArrayElement`/`LastArrayElement` works expectedly. I will choose that way and close the PR.

2023-06-07 03:30 UTC, closed without merging