Allow applying a new profile over an existing one in ***pan-os-apply-security-profile*** command
demisto/content pull request #27237
Opened 2023-06-05 14:33 UTC by rshunim

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6832

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-06-05 14:37 UTC, rshunim commented
@GuyAfik 
I checked it in the UI for Panorama and PAN-OS.
If you want, we can do a short demo together.

2023-06-06 07:24 UTC, GuyAfik requested changes
@rshunim nice work! please write a unit-test to cover this if possible.

2023-06-06 07:24 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +            element += f"<{p_type}><member>{profile_types_result[p_type]['member']['#text']}</member></{p_type}>"
`['#text']` is only true when the profile is un-committed, it fails if the rule was already committed.

use the `parse_pan_os_response` function to parse un-committed pan-os response to be like committed response

make sure to use `get` of `dict` instead also.

2023-06-06 07:24 UTC, GuyAfik commented on Packs/PAN-OS/ReleaseNotes/1_17_5.md
> +- Fixed an issue where ***pan-os-apply-security-profile*** command was failing when applying a new profile over an existing one.
```suggestion
- Fixed an issue where the ***pan-os-apply-security-profile*** command was failing when applying a new profile over an existing one.
- Fixed an issue where the ***pan-os-apply-security-profile*** command didn't work for panorama instances.
```

2023-06-06 07:24 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +    pre_post = args.get('pre_post')
nice catch

2023-06-06 07:24 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +        result.get('response', {}).get('result', {}).get('entry', {}).get('profile-setting', {}).get('profiles', {})
use maybe `dict_safe_get` from common server python instead

2023-06-06 07:34 UTC, rshunim commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +        result.get('response', {}).get('result', {}).get('entry', {}).get('profile-setting', {}).get('profiles', {})
Done

2023-06-06 13:48 UTC, GuyAfik approved these changes
looks great, few minor comments, fix them and merge

2023-06-06 13:48 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +            element += f"<{p_type}><member>{member}</member></{p_type}>"
```suggestion
            p_name = profile_types_result.get(p_type, {}).get('member')
            element += f"<{p_type}><member>{p_name}</member></{p_type}>"
```

2023-06-06 13:48 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +    element = f"<{profile_type}><member>{profile_name}</member></{profile_type}>"
```suggestion
    rule_profiles = f"<{profile_type}><member>{profile_name}</member></{profile_type}>"
```

2023-06-06 13:48 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +        'element': f'<profile-setting><profiles>{element}</profiles></profile-setting>'
```suggestion
        'element': f'<profile-setting><profiles>{rule_profiles}</profiles></profile-setting>'
```

2023-06-06 13:48 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +    result = http_request(URL, 'GET', params=params)
```suggestion
    # get the rule state
    params = {
        'action': 'get',
        'type': 'config',
        'xpath': xpath,
        'key': API_KEY,
    }
    result = http_request(URL, 'GET', params=params)
```

2023-06-06 13:48 UTC, GuyAfik commented on Packs/PAN-OS/Integrations/Panorama/Panorama.py
> +    # keep the context aligned with both committed and un-committed objects
```suggestion
    # align the response for both committed and un-committed profiles 
```

this isn't needed for the context as we dont return context in this command.

2023-06-07 05:29 UTC, merged