Splunk py raise timezone exception
demisto/content pull request #27316
Opened 2023-06-08 11:28 UTC by darkushin

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24965

## Description
Fixed an issue where the returned error message when defining mirroring without specifying a timezone wasn't informative;

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2023-06-08 12:33 UTC, ilappe requested changes
Nice job!

2023-06-12 08:29 UTC, yuvalbenshalom commented on Packs/SplunkPy/Integrations/SplunkPy/README.md
> +    | Timezone of the Splunk server, in minutes. For example, if GMT is gmt +3, set timezone to +180. For UTC, set the timezone to 0. Relevant only for fetching and mirroring notable events. Most be
```suggestion
    | Timezone of the Splunk server, in minutes. For example, if GMT is gmt +3, set timezone to +180. For UTC, set the timezone to 0. This is relevant only for fetching and mirroring notable events. It Must be specified when mirroring is enabled. |  | False |
```

2023-06-12 08:30 UTC, yuvalbenshalom commented on Packs/SplunkPy/ReleaseNotes/3_0_20.md
> +- Fixed an issue where the returned error message when enabling mirroring without specifying a timezone was not informative.
```suggestion
- Fixed an issue where the it was possible to configure mirroring without specifying a timezone.
```

2023-06-12 08:32 UTC, yuvalbenshalom commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
> +- display: Timezone of the Splunk server, in minutes. For example, if GMT is gmt +3, set timezone to +180. For UTC, set the timezone to 0. Relevant only for fetching and mirroring notable events. Mos
```suggestion
- display: Timezone of the Splunk server, in minutes. For example, if GMT is gmt +3, set timezone to +180. For UTC, set the timezone to 0. This is relevant only for fetching and mirroring notable events. It Must be specified when mirroring is enabled.
```

2023-06-12 08:39 UTC, yuvalbenshalom approved these changes

2023-06-12 10:37 UTC, ilappe approved these changes

2023-06-12 12:02 UTC, merged