Added Opensearch support for Elasticsearch feed
demisto/content pull request #27333
Opened 2023-06-09 04:32 UTC by anilagr

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added Opensearch support for Elasticsearch feed

## Screenshots
![ElasticSearchFeed_with_opensearch_option](https://github.com/demisto/content/assets/40182783/8590c704-fe0b-42b4-ae66-4335723fcfe9)
![indicator_index_in_opensearch](https://github.com/demisto/content/assets/40182783/34e1e26f-f15e-4bcf-aff6-801f6118b881)
![Fetched_indicator_from_opensearch](https://github.com/demisto/content/assets/40182783/2b724e7a-ee53-4339-913c-dc379a33cae8)
![Opensearch_deployment_proof](https://github.com/demisto/content/assets/40182783/afa5d456-57fe-43bd-8e47-1b6adcd64e42)

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [X] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-06-11 07:05 UTC, thefrieddan1 commented
Hi @anilagr thank you for your contribution we appreciate your effort, I reviewed the content in the PR and would like to provide some feedback:

Please notice you need to update the integration version. In the pack_metadata.json file and add a release note for that version. You can use the demisto-sdk update-release-notes -i <Path to integration yml file> to help you with that.
Need to update the integration README file with the addition of the new argument.
You can use demisto-sdk generate-docs -i <Path to integration yml file> to help you with that.
As this is an XSOAR level support integration please add unit test with your added argument.
Thanks

2023-06-14 05:21 UTC, anilagr commented
It would be great to get some help for unit test.

2023-06-14 08:58 UTC, thefrieddan1 commented
Sure @anilagr np about the unit test.
I thought about perhaps running a unit test once with the ELASTIC_SEARCH_CLIENT as OpenSearch and once with the default.
Im currently checking about the command :
`get-shared-indicators` which was removed from the README but is not present in the yml file.

2023-06-14 10:29 UTC, dorschw requested changes

2023-06-14 10:29 UTC, dorschw commented on poetry.lock
please undo the changes to `poetry.lock` before merging.

2023-06-19 10:29 UTC, dorschw submitted a review, later dismissed

2023-06-21 14:49 UTC, thefrieddan1 approved these changes

2023-06-21 19:41 UTC, merged