QRadar: Support API version 17
demisto/content pull request #27381
Opened 2023-06-12 08:52 UTC by ilaner

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4263?filter=-1

## Description
* Fully tested on API version 17
* Modified the test playbook to support API version 17
* Changed README

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-06-12 09:57 UTC, yuvalbenshalom approved these changes

2023-08-03 06:30 UTC, yuvalbenshalom requested changes
few comments:
1) please see my comments about possible refactor in the commands, I am not 100% about this, but the current state is very complex.
2) are you sure unit tests are covering the new code well?
3) about the readme - the diff is unreadable and looks like the order was changed.
lets consider running only the commands that changed and coping it to the readme.

2023-08-03 12:23 UTC, ilaner commented on Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
>      qradar_remote_network_cidr_create_command, get_cidrs_indicators, verify_args_for_remote_network_cidr, \
The old API is covered by the `test_commands`.
The new API is covered by the new test, with a test for a case which the result is ready and a test where the result is in progress.
In addition I added a test for the `indicators_upload` command which mocks the indicators from XSOAR

2023-08-03 12:26 UTC, ilaner commented on Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs.yml
> -    simple: "18"
This playbook creats a search for qradar. It works the same until version 18, and there are changes in version 19.

2023-08-03 14:19 UTC, yuvalbenshalom approved these changes

2023-08-06 11:13 UTC, merged