Align credentials stores part 17
demisto/content pull request #27433
Opened 2023-06-14 11:52 UTC by maimorag

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Relates:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5274)

## Description
Change the type of credentials, from type 4 to type 9.

## Minimum version of Cortex XSOAR
- [x] 6.5.0

## Does it break backward compatibility?
  - [x] No

2023-06-18 10:49 UTC, maimorag commented
The build fails since there is no instance [IN140] for:
- Pipl
- Twilio

2023-06-19 06:42 UTC, Shellyber commented on Packs/Twilio/Integrations/Twilio/Twilio.js
> +    var username = (params.credentials_token!== undefined)? params.credentials_token.identifier : params.sid;
Change the variable's names to the right ones - token, account_sid

2023-06-19 06:42 UTC, Shellyber commented on Packs/Twilio/Integrations/Twilio/Twilio.js
> +        throw('API key and Auth token must be provided.');
```suggestion
        throw('Account SID and Auth token must be provided.');
```

2023-06-20 13:38 UTC, Shellyber approved these changes

2023-06-20 13:38 UTC, Shellyber commented on Packs/Twilio/ReleaseNotes/1_0_5.md
> +Added the *API key* and *Auth token* integration parameters to support credentials fetching object.
```suggestion
Added the *Account SID* and *Auth token* integration parameters to support credentials fetching object.
```

2023-06-21 06:59 UTC, dantavori requested changes

2023-06-21 06:59 UTC, dantavori commented on Packs/Pipl/Integrations/Pipl/Pipl.js
> +    var key =  params.credentials_api_key !== null ? params.credentials_api_key.password : params.key;
```suggestion
    var key =  params.credentials_api_key || params.key;
```

2023-06-21 06:59 UTC, dantavori commented on Packs/Pipl/Integrations/Pipl/Pipl.js
> +    if (key !== null)
```suggestion
    if (!key)
```

2023-06-21 06:59 UTC, dantavori commented on Packs/Twilio/Integrations/Twilio/Twilio.js
> +    }
```suggestion
    var account_sid = params.credentials_token.identifier || params.sid;
    var auth_token = params.credentials_token || params.token;
    if (!(account_sid && auth_token)) {
        throw('Account SID and Auth token must be provided.');
    }
```

2023-06-22 10:46 UTC, dantavori commented on Packs/Pipl/Integrations/Pipl/Pipl.js
> +    var key =  (!params.credentials_api_key) ? params.credentials_api_key.password : params.key;
```suggestion
    var key =  params.credentials_api_key ? params.credentials_api_key.password : params.key;
```

2023-06-22 10:46 UTC, dantavori commented on Packs/Twilio/Integrations/Twilio/Twilio.js
> +    var auth_token = (!params.credentials_token)? params.credentials_token.password : params.token;
```suggestion
    var account_sid = params.credentials_token ? params.credentials_token.identifier : params.sid;
    var auth_token = params.credentials_token ? params.credentials_token.password : params.token;
```

2023-06-22 12:19 UTC, merged