Delete offset from CrowdStrike fetch
demisto/content pull request #27530
Opened 2023-06-18 09:23 UTC by ilaner

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR removes the offset argument to the fetch incidents and detections from CrowdStrike, as it no longer needed when using lookback.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-06-19 17:58 UTC, yuvalbenshalom reviewed
see my comment, I wold like to understand the order that the detections are returned from CS and what happens if we get more detections than the limit, not sure it will work without the offset at all.

2023-06-19 17:58 UTC, yuvalbenshalom commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +            incidents_ids = demisto.get(get_incidents_ids(filter_arg=fetch_query), 'resources')
I am not sure the integration knows how to handle a case where we get more new incidents than the limit, without using the offset at all.

2023-06-20 10:36 UTC, ilaner commented
@yuvalbenshalom 
The lookback handles this scenario and increases the limit.
However, we need to provide the new limit from look back to the query, did here

2023-06-20 12:22 UTC, yuvalbenshalom requested changes
see my comments, and please add release notes.
tag this as fixes both relevant issues.

2023-06-20 12:22 UTC, yuvalbenshalom commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    current_fetch_info_incidents.pop("offset", None)
can we move this to migrate?

2023-06-21 13:58 UTC, ilaner commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    current_fetch_info_incidents.pop("offset", None)
moved

2023-07-11 14:45 UTC, ilaner commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +def migrate_last_run(last_run: dict[str, str] | list[dict]) -> list[dict]:
added

2023-07-11 15:02 UTC, yuvalbenshalom approved these changes

2023-07-12 06:03 UTC, merged