[marketplace contributions] - fix issue with support labels
demisto/content pull request #27600
Opened 2023-06-20 15:04 UTC by GuyAfik

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7065)

## Description
* Fixed an issue where support labels were not added specifically in marketplace contributions. See the issues comment for further explanation  
* In case checkout to the contributor's branch fails, fallback to master branch to try to retrieve the support levels of packs.

2023-06-21 11:24 UTC, GuyAfik commented
along with @dansterenson we were able to check that this fix works on marketplace contributions too with this testing PR https://github.com/demisto/content/pull/27617

2023-06-21 11:39 UTC, ShacharKidor requested changes
Nice catch!
Please add a UT for testing MP contributions changes.

2023-06-21 11:39 UTC, ShacharKidor commented on Utils/github_workflow_scripts/handle_external_pr.py
> +            # marketplace contributions the name of the forked owner is not the same as the name of the owner
What is the difference between fork owner and the name of the owner - wording here could be better.

2023-06-22 10:43 UTC, ShacharKidor approved these changes

2023-06-22 12:20 UTC, GuyAfik commented
working version on the latest commit for marketplace contributions: https://github.com/demisto/content/pull/27657

2023-06-26 10:57 UTC, GuyAfik commented
needs force-merge, as the test-upload-flow is broken with validations failing which are un-related to this PR.

2023-06-26 14:58 UTC, merged