Pr/26918
demisto/content pull request #27609
Opened 2023-06-21 06:21 UTC by mohanreddy2121

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [x] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [X] Documentation

2023-06-26 10:55 UTC, edik24 commented
@mohanreddy2121 when will you move it out from draft?

2023-06-26 11:47 UTC, mohanreddy2121 commented
> @mohanreddy2121 when will you move it out from draft?

@edik24 , @michal-dagan, we can move it today night, our side we doing reviewing both integrations

2023-06-27 14:58 UTC, michal-dagan requested changes
Hi @mohanreddy2121,
Thank you for your contribution!
Good work :)
please address my comments
1. You can run locally:  demisto-sdk pre-commit -g --unit-test --validate --no-secrets --show-diff-on-failure --verbose this will fix automatically things.

2. Please update the decyfiriocs integration to match our standard of feed integrations: https://xsoar.pan.dev/docs/integrations/feeds

3. Please add unit tests and make sure that all pass - the coverage needs to be at least 70%: https://app.circleci.com/pipelines/github/demisto/content/274633/workflows/caf78787-6ecb-4601-83f1-c026509bdceb/jobs/707599/parallel-runs/0/steps/0-121


Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

2023-06-27 14:58 UTC, michal-dagan commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +                    for data1 in ta_rel_data:
why data1?

2023-06-27 14:58 UTC, michal-dagan commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +                                            if source_ti_data_obj[LABEL_RELATIONSHIPS]:
in line 300: `source_ti_data_obj[LABEL_RELATIONSHIPS] = []`
so when it will reach the if body?

2023-06-27 14:58 UTC, michal-dagan commented on Packs/DeCYFIR/Integrations/decyfir/README.md
> +This integration was integrated and tested with version xx of decyfir
version?

2023-06-28 08:38 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +                    for data1 in ta_rel_data:
changed

2023-06-28 08:45 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +                for label in list(ioc_labels):
This is decyfir ioc labels, and it's assigning the data to indicator tags and geo country related data.

2023-06-28 08:45 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfir/README.md
> +This integration was integrated and tested with version xx of decyfir
changed

2023-06-28 08:50 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +        source_value: str = str(source_data.get(LABEL_VALUE))
Because of it's failing code validation from the ci/circleci. Due to that i added.

2023-06-28 08:50 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +        source_value: str = str(source_data.get(LABEL_VALUE))
can i removed it ?
And it's always in string only

2023-06-28 08:51 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +
removed

2023-06-28 10:08 UTC, michal-dagan commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +        source_value: str = str(source_data.get(LABEL_VALUE))
yes you can remove the ":str" and "str()"

2023-06-28 10:15 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +                for label in list(ioc_labels):
got that 
will change that.

2023-06-28 10:15 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +        source_value: str = str(source_data.get(LABEL_VALUE))
ok

2023-06-28 10:15 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +        # indicator = params.get('indicator')
removed

2023-06-28 10:22 UTC, michal-dagan commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +                                            src_ti_relationships_data.append(ti_relationships)
```suggestion
                                if source_ti_data_obj and target_ti_data_obj:
                                    ti_relationships: dict = self.build_threat_actor_relationship_obj(source_ti_data_obj, target_ti_data_obj)
                                    if raw_ta_obj.get(LABEL_ID) != source_ref_obj.get(LABEL_ID):
                                        source_ti_data_obj[LABEL_RELATIONSHIPS] = []
                                        if ti_relationships:
                                            source_ti_data_obj[LABEL_RELATIONSHIPS] = [ti_relationships]
                                    else:
                                        ti_relationships = self.build_threat_actor_relationship_obj(source_ti_data_obj,
                                                                                                    target_ti_data_obj)
                                        if ti_relationships:
                                            src_ti_relationships_data = [ti_relationships]
```

2023-07-13 13:16 UTC, michal-dagan reviewed
Hi @mohanreddy2121, 
Here are a few more comments before you push more changes.
Let me know if you need my assistance in fixing these and previous issues. Meanwhile, @efelmandar will review the classifiers, incident fields& types, layouts, and playbooks.
* After reviewing your new changes we will schedule a [demo](https://xsoar.pan.dev/docs/contributing/demo-prep)

2023-07-13 13:54 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfir/decyfir.py
>          }
no, in playbook i think not used those only layout already have those fields and we updated data properly with this version

2023-07-13 13:55 UTC, michal-dagan commented on Packs/DeCYFIR/ReleaseNotes/1_0_6.md
> +
Please finish filling out the release notes. For common troubleshooting steps, please review the documentation found here: https://xsoar.pan.dev/docs/integrations/changelog#common-troubleshooting-tips

2023-07-13 13:57 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfir/decyfir.py
> +            "rawJSON": str(json.dumps(details)),
ok

2023-07-13 13:58 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.yml
> +  version: -1
i tried to change but while i do format command and then it's changing the value

2023-07-13 14:02 UTC, mohanreddy2121 commented on Packs/DeCYFIR/ReleaseNotes/1_0_6.md
> +##### DeCYFIR
ok i will add new one

2023-07-14 08:27 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +        return_data.extend(ta_indicators)
ok

2023-07-14 13:55 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +                    if label.get("geographies"):
ok

2023-07-14 14:29 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfir/decyfir.py
>          }
We are ok with this change, which does not affect existing releases.

2023-07-14 14:31 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py
> +        return_data.extend(ta_indicators)
added

2023-07-16 06:43 UTC, michal-dagan reviewed
Great!!
A few minor comments:
@efelmandar will review your PR.
thanks again!

2023-07-17 06:47 UTC, mohanreddy2121 commented on Packs/DeCYFIR/ReleaseNotes/1_0_6.md
> +- New: DeCYFIR API's provides External Threat Landscape Management insights.
ok

2023-07-17 07:06 UTC, mohanreddy2121 commented on Packs/DeCYFIR/ReleaseNotes/1_0_7.md
> +#### Integrations
updated

2023-07-17 08:16 UTC, michal-dagan commented
Hi @mohanreddy2121,
the `Run Unit Testing Ant Lint` job failed - 
1. Flake8 errors - decyfiriocs.py:330:37: E125 continuation line with same indent as next logical line
2. Unit-tests for 'Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.py' must reach a coverage of at least 70.0% (currently: 47.26%). [You can use the following guide - https://xsoar.pan.dev/docs/integrations/unit-testing as well as examples of unit tests in the HelloWorld integration and other packs from the content repository.]

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

2023-07-19 19:30 UTC, michal-dagan commented on Packs/DeCYFIR/Integrations/decyfir/decyfir.py
> +                # "decyfircategory": alert_type,
why in comment?

2023-07-20 07:31 UTC, mohanreddy2121 commented on Packs/DeCYFIR/Integrations/decyfir/decyfir.py
> +                # "decyfircategory": alert_type,
I forgot to remove. I will remove those

2023-07-22 17:50 UTC, merged