Traceable AI API Security Platform Integration
demisto/content pull request #27626
Opened 2023-06-22 03:54 UTC by mtraceable

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [ ] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2023-06-22 03:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=27626) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=27626) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=27626) it.</sub>

2023-06-26 12:15 UTC, michal-dagan commented
Hi @mtraceabl, 
Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @michal-dagan will know the proposed changes are ready to be reviewed.

2023-06-26 14:31 UTC, michal-dagan requested changes
Hi @mtraceable,
Thank you for your contribution!
Good Work!
1. please address my comments :)
2. please remove these files:
Pipfile
Pipfile.lock
baseintegration-dummy.json
pytest.ini
3. please revert changes in this file:
devcontainer.json
4. please change the Author_image.png according to the standard : https://xsoar.pan.dev/docs/packs/packs-format#author_imagepng
5. Please use our debugging standards instead of the logging package:
https://xsoar.pan.dev/docs/integrations/code-conventions#logging
https://xsoar.pan.dev/docs/integrations/debugging
https://xsoar.pan.dev/docs/integrations/code-conventions#return_error
https://xsoar.pan.dev/docs/reference/api/common-server-python#return_warning

Please feel free to reach out to me with any questions - I'm available here or on slack :)
Thanks again

2023-06-26 21:36 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +
Done

2023-06-26 21:50 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +    proxy = demisto.params().get("proxy", False)
Done

2023-06-26 23:19 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                environments.append(_env_item.strip())
Done

2023-06-26 23:20 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +
Done

2023-06-26 23:20 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +
Done

2023-06-26 23:20 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +        return d.strftime("%Y-%m-%dT%H:%M:%SZ")
Done

2023-06-26 23:22 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                elif type(value) == int or type(value) == float:
Done

2023-06-26 23:23 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +        raise Exception("Something went wrong: " + json.dumps(response, indent=2))
Done

2023-06-26 23:30 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +    logging.debug("First Incident: " + json.dumps(items[0], indent=3))
Done

2023-06-26 23:30 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +            # 'severity': item['severity'],
Done

2023-06-26 23:31 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +            "rawJSON": json.dumps(item),
Done

2023-06-27 07:10 UTC, michal-dagan commented
Hi @mtraceable ,
Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @michal-dagan will know the proposed changes are ready to be reviewed.

2023-06-27 08:38 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                        _value = '"' + '","'.join(value) + '"'
This doesn't work for the use case. If the string array: CRITICAL,HIGH,MEDIUM is provided as input, the suggested change results into:
"CRITICAL,HIGH,MEDIUM,LOW"

However the required result is:
"CRITICAL", "HIGH", "MEDIUM", "LOW".

Hence have changed it to:
_value = ",".join(['"{}"'.format(v) for v in value])

2023-06-27 08:39 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                + type
Done

2023-06-27 08:42 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                )
Done

2023-06-27 08:42 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +            json={"query": query, "variables": {}},
Done

2023-06-27 08:43 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +            if response.text is not None:
Done

2023-06-27 08:46 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                    _value = '"' + value + '"'
Done

2023-06-27 12:18 UTC, michal-dagan reviewed
Great!! 
You can run locally: ` pre-commit -g --unit-test --validate --no-secrets --show-diff-on-failure --verbose` this will fix automatically things.
Just please revert your changes to the `devcontainer.json` file.

We're ready for a demo. Please check [this page](https://xsoar.pan.dev/docs/contributing/demo-prep), and let me know when you're available for one over DFIR.

2023-06-27 15:35 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +s.mount("https://", HTTPAdapter(max_retries=retries))
The graphql service is ratelimited at Traceable end, and the ratelimiting works at the account as well as tenant level. so sometimes with no fault of ours we might get ratelimited, so this retry enables exponential backoff to circumvent the ratelimiting problem.

2023-06-27 16:54 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +
Done

2023-06-27 16:56 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +            "occurred": incident_created_time.strftime(DATE_FORMAT),
Done

2023-06-27 17:42 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                        _value = ",".join(['"{}"'.format(v) for v in value])
Done

2023-06-27 17:42 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                        _value = ",".join(["{}".format(str(v)) for v in value])
Done

2023-06-27 17:42 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable_test.py
> +    import json
Done

2023-06-27 17:43 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +        ok_codes=tuple(),
Done

2023-06-27 17:45 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +            msg = f"Error occurred: {response.text} | Status Code: {str(response.status_code)}"
Done

2023-06-28 17:50 UTC, michal-dagan requested changes
1. Please run `pre-commit -g --unit-test --validate --no-secrets --show-diff-on-failure --verbose` cause the pre-commit job failed
2. Regarding the author image - After I sent you the documentation I saw that the content is not updated, we are now working on updating it in [xsoar pan dev](https://xsoar-pan-dev--pull-request-1336-0i25g2kq.web.app/docs/packs/packs-format#author_imagepng), it should be a logo of the contributing company, you can see for example [Packs/Binalyze](https://github.com/demisto/content/tree/master/Packs/Binalyze)
3. [Tip: You should use dict.get(key) instead of dict[key]
](https://www.30secondsofcode.org/python/s/dict-getkey-vs-dictkey/#:~:text=get()%20will%20always%20return,the%20given%20key%20is%20missing.) consider to change in your code accordingly.
4. Please revert your changes to the devcontainer.json file.

thanks!!

2023-06-28 18:18 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +            _value = None
Done

2023-06-28 18:19 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +        results = result["data"]["explore"]["results"]
This part actually ensures that that hierarchy exists in the result:
`if Helper.is_error(result, "data", "explore", "results"):
            msg = "Error Object: " + json.dumps(result)
            demisto.error(msg)
            raise Exception(msg)`

2023-06-28 18:22 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                trace_id = domain_event["traceId"]["value"]
This is also preceeded by the call to `Helper.is_error` which ensures that the dictionary hierarchy exists, and error out if it doesn't.

2023-06-28 18:23 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.py
> +                domain_event["spans"] = []
Done

2023-06-28 18:25 UTC, mtraceable commented on Packs/Traceable/Integrations/Traceable/Traceable.yml
> +- name: max_fetch
Done

2023-07-02 05:39 UTC, merged