added CortexAttackSurfaceManagement to unremovable packs
demisto/content pull request #27749
Opened 2023-06-27 07:47 UTC by yucohen

## Description
added CortexAttackSurfaceManagement to unremovable packs

2023-06-27 10:31 UTC, daryakoval approved these changes

2023-06-27 12:59 UTC, daryakoval commented on .gitlab/ci/on-push.yml
> +    UNREMOVABLE_PACKS: "Base,CoreAlertFields,Core,CortexAttackSurfaceManagement "
```suggestion
    UNREMOVABLE_PACKS: "Base,CoreAlertFields,Core,CortexAttackSurfaceManagement"
```

2023-06-28 05:08 UTC, kobymeir requested changes

2023-06-28 05:08 UTC, kobymeir commented on Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
> +  python3 ./Tests/Marketplace/search_and_uninstall_pack.py --cloud_machine $CLOUD_CHOSEN_MACHINE_ID --cloud_servers_path $CLOUD_SERVERS_PATH --cloud_servers_api_keys "cloud_api_keys.json" --unremovab
```suggestion
  python3 ./Tests/Marketplace/search_and_uninstall_pack.py --cloud_machine $CLOUD_CHOSEN_MACHINE_ID --cloud_servers_path $CLOUD_SERVERS_PATH --cloud_servers_api_keys "cloud_api_keys.json" --unremovable_packs "${UNREMOVABLE_PACKS}"
```
Prevent globbing and expansion of bash variables

2023-06-28 05:08 UTC, kobymeir commented on Tests/Marketplace/search_and_uninstall_pack.py
> +        while len(installed_packs) > len(unremovable_packs):
i think set operation here is preferred:
```
while len(installed_packs - unremoveable_packs)
```
As we check explicitly that whatever is left is only the unremovable.

2023-06-28 05:08 UTC, kobymeir commented on Tests/Marketplace/Tests/search_and_unistall_pack_test.py
> +    ret_val_from_call = def_call(client, ['Base'])
more the `['Base']` list to be a parameter for the test, and test for more scenarios: Empty, 1 pack, 2 packs.

2023-06-28 06:43 UTC, merged