Jira V3 fetch incidents by id error
demisto/content pull request #27774
Opened 2023-06-27 19:14 UTC by anas-yousef

## Status
- [X] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7135

## Description
When fetching by ID, and the *Issue index to start fetching incidents from* is not found in the Jira instance, the integration returns an error: *Issue does not exist or you do not have permission to see it*. The fetch incidents should be able to handle such a case.
For example, when *Issue index to start fetching incidents from* is equal to 0, and there is no issue with index 0, then the error is returned.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Cortex XSOAR
- [X] 6.0.0
- [ ] 6.1.0
- [ ] 6.2.0
- [ ] 6.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

2023-07-09 16:10 UTC, ShacharKidor requested changes
Great work! 
Added a few comments please review them.

2023-07-10 07:53 UTC, ShirleyDenkberg commented
@ShacharKidor Doc review completed.

2023-07-10 16:12 UTC, anas-yousef commented on Packs/Jira/Integrations/JiraV3/JiraV3.py
> +            delta = {k: remote_args.data.get(k) for k in delta}
Yup, it was actually suggested by the [Ruff](https://beta.ruff.rs/docs/rules/in-dict-keys/)

2023-07-10 18:04 UTC, ShacharKidor commented on Packs/Jira/Integrations/JiraV3/JiraV3.py
> +            raise DemistoException('The fetch query configured returned no results, therefore, could not start fetching.')
yes, it is better :)

2023-07-10 18:04 UTC, ShacharKidor approved these changes

2023-07-11 13:35 UTC, merged