[Build] Fix Dependency Issues (Restore & fix after revert)
demisto/content pull request #28469
Opened 2023-07-25 06:52 UTC by MichaelYochpaz

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4543)

## Description
Currently, in the pre_update check that installs packs from master and assures they're installed properly, the required dependencies are taken from master (API call to marketplace), while the check whether each pack is deprecated, is done locally from the branch.
This causes issues when deprecating a pack and changing dependencies on the same PR.

This PR fixes the behavior to get deprecation data from the same API response used for fetching the dependencies instead of checking locally.

Test build before the fix: https://code.pan.run/xsoar/content/-/pipelines/5513561
Test build after the fix: https://code.pan.run/xsoar/content/-/pipelines/5514657
(only XSOAR instance builds are relevant to the changes)

This PR is a restore & fix for https://github.com/demisto/content/pull/27405, after it has been reverted on 5896217e5bc2e4aeea327a288d416e647bda2af2.

2023-07-25 14:16 UTC, MichaelYochpaz commented
Changes specific for this fix PR (without the "revert" changes, which restore the original  Marketplace changes) can be seen on:
https://github.com/demisto/content/pull/28469/files/90ae84763823c534958c859a0e6cdd6fc3011ff9..3c447bf0bbbcc5307b043be811858b569c559aa4

2023-07-30 08:42 UTC, MichaelYochpaz commented
@daryakoval @yaakovpraisler @ilaner PR is ready for review.

Changes specific for this fix PR (without the "revert" changes, which restore the original Marketplace changes) can be seen on:
https://github.com/demisto/content/pull/28469/files/05f51e4cf33ae12ec5fce7dba008a7d829321510..48d7d77ae3b162fa52fc39f860d162582f396ddc

2023-08-01 14:25 UTC, daryakoval requested changes
Great, lets change the logic a little, please see my comments.
Feel free to contact me if any assistance is needed.

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_uninstall_pack.py
> +                                                                 is_post_update=False)
```suggestion
                                                                 production_bucket=True)
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/configure_and_install_packs.py
> +                                                                     is_post_update=True)
```suggestion
                                                                    production_bucket=False)
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +                                                    is_post_update: bool = False):
```suggestion
                                                    production_bucket: bool = True):
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +        is_post_update (bool): Whether the installation is in post update mode. Defaults to False.
```suggestion
        production_bucket (bool): Whether the installation is from the production bucket or the custom bucket. Defaults to True.
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +                     "Pack deprecation status will be determined using Marketplace API.")
Remove from here, if you want to log this, add this to the `is_pack_deprecated` function, and use `logging.debug` not info. 
```suggestion
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +        'is_post_update': is_post_update,
```suggestion
        'production_bucket': production_bucket,
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +                                     is_post_update: bool,
```suggestion
                                     production_bucket: bool,
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +        is_post_update (bool): Whether the installation is done in post-update or not (pre-update otherwise).
```suggestion
        production_bucket (bool): Whether the installation is done using production bucket or custom bucket.
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +            is_deprecated = is_pack_deprecated(pack_id=dependency_id, check_locally=is_post_update, pack_api_data=dependency)
```suggestion
            is_deprecated = is_pack_deprecated(pack_id=dependency_id, check_locally=not production_bucket, pack_api_data=dependency)
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +            # if running on post-update, we check for deprecation locally on the branch.
remove from here
```suggestion
```

2023-08-01 14:25 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +                       commit_hash: str | None = None, pack_api_data: dict | None = None) -> bool:
Please change the function, move all logic related to the deprecated check inside this function, using my other comments, and add the explanations for the docstrings here.

2023-08-02 11:06 UTC, MichaelYochpaz commented on Tests/Marketplace/search_and_install_packs.py
> +                checked_packs.append(dependency['id'])
This is data that's returned from the Marketplace API. There shouldn't be a server response with pack data, but not an ID. If the API does change, functions called before this one will break anyway.

2023-08-03 09:41 UTC, daryakoval requested changes
Great work! Please see my notes. I don't support adding to much comments, since this codes goes trough refactoring a lot, the code changes but the comments stays and become wrong. 

Please trigger nightly and test upload flow, update me when they pass and I will approve the PR.

2023-08-03 09:41 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +        return
```suggestion
    if is_pack_deprecated(pack_id=pack_id, production_bucket=production_bucket, commit_hash=commit_hash):
        logging.warning(f"Pack '{pack_id}' is deprecated (hidden) and will not be installed.")
        return
```

2023-08-03 09:41 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +        return  # Error information already logged on 'get_pack_dependencies'.
```suggestion
    if not api_data:
        return
```

2023-08-03 09:41 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +        # If APIs response structure has unexpectedly changed, causing an error, print debug information
```suggestion
```

2023-08-03 09:41 UTC, daryakoval commented on Tests/Marketplace/search_and_install_packs.py
> +        logging.debug("Packs deprecation status will be determined by the local branch and its changes.")
Please delete. Explain these differences in the `is_pack_deprecated` docstring.
```suggestion
```

2023-08-03 10:00 UTC, MichaelYochpaz commented
Updated nightly: https://code.pan.run/xsoar/content/-/pipelines/5946644

2023-08-06 13:02 UTC, daryakoval approved these changes
Let the build be on our side!

2023-08-07 06:51 UTC, merged