Workday bug
demisto/content pull request #28490
Opened 2023-07-25 12:10 UTC by merit-maita

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25251

## Description
changed the dataset name of the workday collector.

## Must have
- [ ] Tests
- [ ] Documentation

2023-07-25 12:25 UTC, DeanArbel commented on Packs/Workday/ReleaseNotes/1_3_6.json
> +{"breakingChanges":true,"breakingChangesNotes":"Updated the dataset name of the Workday Collector."}
Please add an explanation that new events will be collected to the new dataset.

2023-07-25 14:35 UTC, DeanArbel requested changes
@merit-maita You should also update the python code, where the vendor+brand sets the name for the dataset, please make sure it creates the expected data set

2023-07-26 06:40 UTC, merit-maita commented
as seen in this screenshot, the dataset was set correctly to "workday_activity_raw"
![A52E6A3F-3595-4652-BB7D-CC52E6B4A8FF](https://github.com/demisto/content/assets/49760643/068fade1-9ef4-46e8-986b-7388ddad659c)

2023-07-26 08:47 UTC, DeanArbel approved these changes

2023-07-26 11:02 UTC, merged