Similarity list bugfix
demisto/content pull request #28598
Opened 2023-07-30 13:25 UTC by efelmandar

## Status
- [ ] In Progress
- [ ] Ready
- [x] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This fixes a bug with handling lists of strings

## Must have
- [x] Tests
- [x] Documentation

2023-07-30 14:05 UTC, eyalpalo requested changes
Nice!

2023-07-30 14:05 UTC, eyalpalo commented on Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.py
> +def stringSimilarity(firstString: str, secondString: str, similarityThreshold: float):
Can you please change all vars from camel case to using underscore as
firstString -> first_string, etc.

2023-07-30 14:05 UTC, eyalpalo commented on Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity.py
> +        commandResults = CommandResults("StringSimilarity", ["StringA", "StringB"], results)
We can move the CommandResults to be in the stringSimilarity itself.

2023-07-30 14:05 UTC, eyalpalo commented on Packs/CommonScripts/Scripts/StringSimilarity/StringSimilarity_test.py
> +            print(result)
Please remove print statement.

2023-07-31 08:17 UTC, eyalpalo approved these changes

2023-08-01 08:44 UTC, DeanArbel commented
Validate fails due to `BC103` - the change is inteneded.

2023-08-01 08:45 UTC, merged