[ASM] - Expander - Enrichment Status and N/A values (3581 & 4820)
demisto/content pull request #28663
Opened 2023-08-01 14:21 UTC by BigEasyJ

Please ignore #28573 and only refer to this PR.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## NOTE

This PR has a release version higher than #28375. If merged before #28375 please change the version.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
- [EXPANDR-4820](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-4820)
- [EXPANDR-3851](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3851)

## Description
- Added a new field, **ASM - Enrichment Status**, to track the status of types of platforms enrichment has been performed with.
- Updated all sub-playbooks in `Cortex ASM - Enrichment` to incorporate the `ASM - Enrichment Status` field to identify if enrichment was completed successfully or not.

## Must have
- [x] Tests (internal)
- [x] Documentation (internal)

2023-08-03 14:31 UTC, johnnywilkes commented
@ShirleyDenkberg , can you please look over?

2023-08-03 14:57 UTC, johnnywilkes requested changes
some nits for consistency sakes

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
> +    scriptarguments:
```suggestion
    scriptarguments:
      append:
        simple: "true"
```
Seem to always append in other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
> +    scriptarguments:
```suggestion
    scriptarguments:
      append:
        simple: "true"
```
Seem to always append in other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
> +    scriptarguments:
```suggestion
    scriptarguments:
      append:
        simple: "true"
```
Seem to always append in other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Prisma_Cloud_Enrichment.yml
> +      name: Set flag for completed enrichment
```suggestion
      name: Set true flag for completed enrichment
```
Consistency with other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
> +      name: Set ASM enrichment status field (s3)
```suggestion
      name: Set ASM enrichment status to true (s3)
```
Consistency with other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
> +      name: Set ASM enrichment status field (s3)
```suggestion
      name: Set ASM enrichment status to false (s3)
```
Consistency with other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
> +      name: Set ASM enrichment status field (AWS)
```suggestion
      name: Set ASM enrichment status to true (AWS)
```
Consistency with other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
> +      name: Set ASM enrichment status field (AWS)
```suggestion
      name: Set ASM enrichment status to false (AWS)
```
Consistency with other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Qualys_Enrichment.yml
> +      name: Set ASM - Enrichment Status
```suggestion
      name: Set ASM enrichment status to true
```
Consistency with other playbooks

2023-08-03 14:57 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Qualys_Enrichment.yml
> +      name: Set ASM - Enrichment Status
```suggestion
      name: Set ASM enrichment status to false
```
Consistency with other playbooks

2023-08-06 07:22 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_27.md
> +Added a new field, **ASM - Enrichment Status**, to track the status of types of platforms enrichment has been performed with.
```suggestion
Added a new field, **ASM - Enrichment Status**, to track the status of types of platform enrichment that has been performed.
```

2023-08-06 07:22 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_27.md
> +Update the comment field of the `result` key.
```suggestion
Updated the comment field of the *result* key.
```

2023-08-06 07:22 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_27.md
> +- Playbook now supports populating the ASM - Enrichment Status field to identify if enrichment was completed successfully or not.
```suggestion
Playbook now supports populating the ASM - Enrichment Status field to identify if enrichment was completed successfully or not.
```

2023-08-06 07:23 UTC, ShirleyDenkberg commented
@johnnywilkes @anas-yousef @efelmandar Doc review completed.

2023-08-08 05:10 UTC, BigEasyJ commented
@anas-yousef this PR is ready for merge.

2023-08-08 06:37 UTC, anas-yousef approved these changes

2023-08-08 06:39 UTC, merged