Yr/create a new filter any match/ciac 6748
demisto/content pull request #28696
Opened 2023-08-02 08:35 UTC by RosenbergYehuda

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6748

Description
Adding a new filter.
This filter accepts two inputs, left and right, which can each be either a single value of all types (e.g., string, int, etc) or a list of values. The filter iterates over each value in the left input and checks if the entire value or part of it exists within the right input. The matching process is case-insensitive, meaning it disregards letter case during the comparison.

Moreover, the comparison treats all inputs as strings. Hence, integers and strings are considered equal during the evaluation.

## Must have
- [x] Tests
- [x] Documentation 

##Screenshots

![AnyMatch_Test_Tue_Aug_01_2023](https://github.com/demisto/content/assets/90599084/fdf919ae-60b5-4f84-9d45-96549ac187f4)

2023-08-02 12:03 UTC, ShacharKidor requested changes
Good work!
Added several comments.

2023-08-02 12:03 UTC, ShacharKidor commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch_test.py
> +@pytest.mark.parametrize('left,right, call_count,result', [
```suggestion
@pytest.mark.parametrize('left,right, call_count,expected_result', [
```

2023-08-02 12:54 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.py
> +        demisto.results(is_substring_in_list(left_val, right_list))
Changed to return_results.
not sure abour the second note, this is the way it is in other filters, IsInCiderRange for exapmle.

2023-08-02 12:55 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.py
> +       str_list: A list of strings to check if the single_str is in it, fully or partly.
Fixed.

2023-08-02 12:55 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.py
> +    This function checks if a string is in a list of strings, fully or partly, case insensitive.
Fixed.

2023-08-02 13:05 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.yml
> +scripttarget: 0
Correct.No outputs in all examples I sow.

2023-08-02 13:09 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.yml
> +  e.g -AnyMatch left=[A,b,c] right=[baby] will return [a,b].
Fixed

2023-08-02 13:09 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.yml
> +    description: Value to check if it exists in the right side, fully or partially. can be a single value or a comma-separated list.
Fixed.

2023-08-02 13:11 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch_test.py
> +def test_main(mocker, left, right, call_count, result):
Fixed

2023-08-02 13:14 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/README.md
> +This filter accepts two inputs, left and right, each of which can be either a single value of any type (e.g., string, int, etc.) or a list of values. The filter iterates over each value in the left i
Fixed.

2023-08-02 13:15 UTC, RosenbergYehuda commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/README.md
> +| left              | Value to check if it exists in the right side, fully or partially. can be a single value or a comma-separated list.                    |
Fixed.

2023-08-02 16:37 UTC, ShacharKidor commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.py
> +        demisto.results(is_substring_in_list(left_val, right_list))
ok in that case, let's stick to that.

2023-08-03 07:49 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.yml
> +  e.g -AnyMatch left=baby right=A will return baby. For more examples see the filter's Readme.
```suggestion
  E.g., -AnyMatch left=baby right=I will return baby. For more examples see the filter's Readme.
```

2023-08-03 07:49 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.yml
> +    description: Value to check if it has a substring that is equal to an element in the right side. can be a single value or a comma-separated list.
```suggestion
    description: Value to check if it has a substring that is equal to an element in the right side. Can be a single value or a comma-separated list.
```

2023-08-03 07:49 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/AnyMatch.yml
> +    description: Value to check if it is equal to an element or to a substring of an element from the left. can be a single value or a comma-separated list.
```suggestion
    description: Value to check if it is equal to an element or to a substring of an element from the left. Can be a single value or a comma-separated list.
```

2023-08-03 07:49 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/README.md
> +All inputs are treated either as a string or as a list of strings, if it contains a comma. Json on the other hand is always treated as one string.
```suggestion
All inputs are treated either as a string or as a list of strings, if it contains a comma. A JSON is always treated as a string.
```

2023-08-03 07:49 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/Scripts/AnyMatch/README.md
> +| left              | Value to check if it has a substring that is equal to an element in the right side. can be a single value or a comma-separated list.                   |
```suggestion
| left              | Value to check if it has a substring that is equal to an element in the right side. Can be a single value or a comma-separated list.                   |
```

2023-08-03 07:50 UTC, ShirleyDenkberg commented
@ShacharKidor @ostolero Doc review completed.

2023-08-03 10:34 UTC, merged