WIP
demisto/content pull request #28863
Opened 2023-08-09 12:26 UTC by JasBeilin

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-08-09 12:41 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector.yml
> +    additionalinfo: Outbound traffic will be fetched in addition to inbound traffic
```suggestion
    additionalinfo: Outbound traffic will be fetched in addition to inbound traffic.
```

2023-08-09 12:42 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector.yml
> +    additionalinfo: Hide subject and attachments details from emails
```suggestion
    additionalinfo: Hide subject and attachments details from emails.
```

2023-08-09 12:42 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_description.md
> +2. Click on My Settings in the top navigation bar.
```suggestion
2. Click **My Settings** in the top navigation bar.
```

2023-08-09 12:42 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_description.md
> +3. Click the API Keys tab in the IAM console.
```suggestion
3. Click the **API Keys** tab in the IAM console.
```

2023-08-09 12:43 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_description.md
> +4. Click Create API Key.
```suggestion
4. Click **Create API Key**.
```

2023-08-09 12:43 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_description.md
> +8. Click Create API Key.
```suggestion
8. Click **Create API Key**.
```

2023-08-09 12:44 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_description.md
> +For accessing alerts APIs, the following additional entitlements are required:
```suggestion
For accessing alerts APIs, the following additional entitlement is required:
```

2023-08-09 12:44 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_description.md
> +For accessing trace APIs, the following additional entitlements are required:
```suggestion
For accessing trace APIs, the following additional entitlement is required:
```

2023-08-09 12:44 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector_description.md
> +For more information, check [Official Product Documentation](https://docs.trellix.com/bundle/etp_api/page/UUID-98fd1a2c-382d-130b-00c5-b9be402fe660_1.html#idm44910884288000).
```suggestion
For more information, see the [Official Product Documentation](https://docs.trellix.com/bundle/etp_api/page/UUID-98fd1a2c-382d-130b-00c5-b9be402fe660_1.html#idm44910884288000).
```

2023-08-09 12:45 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/README.md
> +    | Fetch outbound traffic | Outbound traffic will be fetched in addition to inbound traffic |  |
```suggestion
    | Fetch outbound traffic | Outbound traffic will be fetched in addition to inbound traffic. |  |
```

2023-08-09 12:45 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/README.md
> +    | Hide sensitive details from email | Hide subject and attachments details from emails |  |
```suggestion
    | Hide sensitive details from email | Hide subject and attachments details from emails. |  |
```

2023-08-09 12:47 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/README.md
> +1. Navigate to **Settings** > **Integrations** > **Servers & Services**.
```suggestion
1. Navigate to **Settings** > **Configurations** > **Data Collection** > **Automation & Feed Integrations**.
```

2023-08-09 12:47 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/README.md
> +You can execute these commands from the Cortex XSOAR CLI, as part of an automation, or in a playbook.
```suggestion
You can execute these commands from the Cortex XSIAM CLI, as part of an automation, or in a playbook.
```

2023-08-09 12:48 UTC, ShirleyDenkberg commented on Packs/FireEyeETP/ReleaseNotes/1_3_0.md
> +- New: Use this integration to fetch email security incidents from FireEye ETP as XSIAM events.
```suggestion
New: Use this integration to fetch email security incidents from FireEye ETP as XSIAM events.
```

2023-08-09 12:49 UTC, ShirleyDenkberg commented
@yuvalbenshalom Doc review completed.

2023-08-14 10:01 UTC, yuvalbenshalom requested changes
looks good. see my comments.

general comment, please check if passing **args is really needed. in general I prefer to avoid it.

2023-08-15 11:30 UTC, JasBeilin commented on Packs/FireEyeETP/pack_metadata.json
> -    "currentVersion": "1.2.4",
Yes, by design.

2023-08-15 11:38 UTC, JasBeilin commented on Packs/FireEyeETP/Integrations/FireEyeETPEventCollector/FireEyeETPEventCollector.py
> +        while results_left and res_count < event_type.client_max_fetch and (not (end_time and end_time <= start_time)):
It is due to the difference in paging param, and functions (for example if ID is not an existing field), I thought generic will be harder to read in this case, and might be more expensive in running time.

2023-08-16 13:26 UTC, JasBeilin commented
Some changes post Demo-
1. API Key display name change
2. Permission in Description are now joined
3. Handling a wrong credential error.
4. mapping changes
5. sensitive data will not be deleted but replaced with "hidden data"
6. better explanation of the outbound param affects
7. better get-command warning of use.

2023-08-17 08:50 UTC, yuvalbenshalom approved these changes

2023-08-23 12:14 UTC, merged