packs/GoogleDrive: add modify labels command
demisto/content pull request #28962
Opened 2023-08-14 18:21 UTC by GalNakash-RecoLabs

Add a command to modify labels in google drive

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-08-15 15:54 UTC, GalNakash-RecoLabs commented
PR is ready!

2023-08-16 15:18 UTC, ostolero requested changes
Hi Gal, great work!
Everything is really according to out standard and looks great, just a few points-
1. see my comment regarding adding the logger decorator.
2. There are 2 validation failures in the build, the first one is regarding the use of demisto.log (see comment). the second is regarding the use of demisto.results in main. this is not part of your code but if you can change that line to simply `return` that would be greatly appreciated :)
3. You should add another unit test for the coverage test to pass.
Let me you know if you need any help, I've reached out through slack to schedule a demo :)

2023-08-16 15:18 UTC, ostolero commented on Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
> +    demisto.log(full_url)
We don't really use demisto.log anymore let's change to demisto.info and add something more indicative
```suggestion
    demisto.info(f'full url for get labels is: {full_url}')
```

2023-08-20 15:29 UTC, ostolero commented
Thank you Gal for a great demo! 
During the demo we added proper Human readable outputs, and as discussed we still require outputs for the new commands in the yml. [here](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/generate_outputs/README.md) is the sdk command that helps achieve this.
when these are finished and all validation pass we can merge :)

2023-08-21 13:41 UTC, ostolero commented
The context is approved by @melamedbn , need to fix the last validation failures

2023-08-22 07:02 UTC, GalNakash-RecoLabs commented
@ostolero anything from my side?

2023-08-22 08:07 UTC, ostolero approved these changes
All looks great!

2023-08-22 08:08 UTC, ostolero commented
Hi Gal ,I approved as all the changes are done :) merging this and when the internal pr passes validations we can merge to master. I'll update over Slack when this is expected to show in the marketplace for the client.

2023-08-22 08:09 UTC, merged