[ASM] - Expander - command argument bug fix
demisto/content pull request #29205
Opened 2023-08-24 13:01 UTC by andrew-paloalto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
EXPANDR-5754

## Description
Update the enums used for alert statuses

## Must have
- [ ] Tests
- [x] Documentation

2023-08-24 13:51 UTC, johnnywilkes requested changes
This should fix validation and pre-commit errors

2023-08-24 13:51 UTC, johnnywilkes commented on Packs/CortexXpanse/README.md
> +![Xpanse - Alert Self-Enrichment](https://raw.githubusercontent.com/demisto/content/master/Packs/Packs/CortexXpanse/doc_files/Xpanse_-_Alert_Self-Enrichment.png)
```suggestion
![Xpanse - Alert Self-Enrichment](https://raw.githubusercontent.com/demisto/content/master/Packs/CortexXpanse/doc_files/Xpanse_-_Alert_Self-Enrichment.png)
```
This should fix validation and pre-commit errors

2023-08-24 14:07 UTC, johnnywilkes approved these changes
@andrew-paloalto , Looks good!

2023-08-24 14:07 UTC, johnnywilkes commented
@RosenbergYehuda , this is approved by Xpanse team.  When @andrew-paloalto takes out of draft mode, please merge when possible

2023-08-25 18:37 UTC, ben-expanse approved these changes
Tag Changes LGTM! Thanks Andrew 😄

2023-08-27 09:03 UTC, RosenbergYehuda approved these changes
Looks good! @andrew-paloalto

2023-08-27 09:16 UTC, merged