Xsup 27483/support relationships without
demisto/content pull request #29327
Opened 2023-08-30 10:01 UTC by AradCarmi

## Related Issues
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27483)

## Description
Added support for the **Report Object References** *Grid* indicator.

2023-08-31 11:33 UTC, Ni-Knight approved these changes
Can we do a small demo before merge? just us to make sure it works perfectly?

2023-08-31 12:11 UTC, AradCarmi commented
> Can we do a small demo before merge? just us to make sure it works perfectly?

Yes I will schedule for the next week.

2023-08-31 12:46 UTC, sapirshuker commented on Packs/FeedTAXII/ReleaseNotes/1_1_33.md
> +-
```suggestion

```

2023-09-03 09:03 UTC, sapirshuker requested changes
Nice Job! please add unit-test.

2023-09-04 16:52 UTC, dantavori approved these changes
very nice! see doc note

2023-09-04 16:52 UTC, dantavori commented on Packs/FeedDHS/ReleaseNotes/2_0_20.md
> +- Added support for the **Report Object References** indicator field.
```suggestion
- STIX report indicators pulled from the feed will now contain the *Report Object References* indicator field, which holds the IDs of related indicators.
```
update where needed

2023-09-05 07:17 UTC, merged