XSUP-27717/FortiSIEM
demisto/content pull request #29458
Opened 2023-09-05 10:37 UTC by sapirshuker

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-27717

## Description
Fix an issue where ***fetch-incident*** failed due to incident without incidentTitle.

## Must have
- [ ] Tests
- [ ] Documentation

2023-09-10 07:24 UTC, eyalpalo requested changes
Dont forget to change the integration id and name before sending to client

2023-09-10 07:24 UTC, eyalpalo commented on Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.py
> +            'name': incident.get('incidentTitle', f"FortiSIEM incident: {incident.get('incidentId')}"),
If none of id or title have been given? An error will occur

2023-09-10 08:08 UTC, sapirshuker commented
Sent to the customer: f5e1c3d

2023-09-12 13:17 UTC, eyalpalo approved these changes

2023-09-13 14:07 UTC, merged