[ASM] - Expander - Update ASM fields (4821)
demisto/content pull request #29506
Opened 2023-09-06 10:17 UTC by BigEasyJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-4821](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-4821)

## Description

Adding comments to incident fields and updating descriptions.

## Must have
- [x] Tests
- [x] Documentation

2023-09-06 12:39 UTC, johnnywilkes reviewed
@BigEasyJ , looks good.  Do we also want to include if the gridfield key is mandatory or optional such as: https://github.com/demisto/content/blob/56e2cd6df33f4a456d8fd0d0c72e21775288c836/Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Dev_Check_Details.json#L19 ?

2023-09-06 15:01 UTC, BigEasyJ commented
@johnnywilkes Yah I would like to, but I would like a meeting to help with identifying and going over each one.

2023-09-11 17:09 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Private_IP.json
> +            "_comment": "The IP address of the relevant asset."
```suggestion
            "_comment": "Mandatory: The IP address of the relevant asset."
```
to make the same as others

2023-09-11 17:10 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Private_IP.json
> +            "_comment": "The source of the IP address."
```suggestion
            "_comment": "Mandatory: The source of the IP address."
```

2023-09-11 17:14 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation.json
> +            "_comment": "Description of the remediation action."
```suggestion
            "_comment": "Mandatory: Description of the remediation action."
```

2023-09-11 17:14 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation.json
> +            "_comment": "Outcome of the remediation action."
```suggestion
            "_comment": "Mandatory: Outcome of the remediation action."
```

2023-09-11 17:14 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation.json
> +            "_comment": "timestamp of the remediation outcome."
```suggestion
            "_comment": "Mandatory: Timestamp of the remediation outcome."
```

2023-09-11 17:16 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Tags.json
> +            "_comment": "The source of tag. Ex: ServiceNOW, AWS, GCP, Tenable, etc."
```suggestion
            "_comment": "Mandatory: The source of tag. Ex: ServiceNOW, AWS, GCP, Tenable, etc."
```

2023-09-11 17:16 UTC, johnnywilkes requested changes
@BigEasyJ , just a few more to change

2023-09-11 20:56 UTC, johnnywilkes approved these changes
@BigEasyJ , looks good, ship it!

2023-09-14 13:59 UTC, ostolero commented
Hi @BigEasyJ there seems to be a conflict with our master which blocks merge. What you can do is either solve the conflict yourself (it's simply the rn overlapping with other changes, shouldn't be too complicated). Or grant me permission to push to your branch, An explanation on how to do that is [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository).

2023-09-14 17:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=29506) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=29506) before we can accept your contribution.<br/>**6** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: YuvHayun<br/>:white_check_mark: BigEasyJ<br/>:white_check_mark: samuelFain<br/>:white_check_mark: mmhw<br/>:white_check_mark: content-bot<br/>:white_check_mark: eyalpalo<br/>:x: nkanon<br/>:x: tomer-pan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=29506) it.</sub>

2023-09-14 17:13 UTC, BigEasyJ commented
@ostolero you are not a member of `PaloAltoNetworks` org for me to add you, you would need to put in a ticket with IT for access. I will push up the changes to fix the release versions.

2023-09-18 08:45 UTC, ostolero approved these changes
Looks great @BigEasyJ ! merging

2023-09-18 08:46 UTC, merged