Cybersixgill xsoar alerts typosquatting
demisto/content pull request #30068
Opened 2023-10-05 12:47 UTC by syed-loginsoft

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] Ready

## Related Issues
fixes: link to the issue

## Description
Added a command to populate context data for certain types of alerts.

## Must have
- [x] Tests
- [x] Documentation

2023-10-10 09:03 UTC, sapirshuker requested changes
Hey, @syed-loginsoft  thanks a lot for this contribution, It is highly appreciated.
I have reviewed it but unfortunately it has some issues.
I have posted some comments in the review.
In addition, there are a build failures, please [review](https://app.circleci.com/jobs/github/demisto/content/723287) and fix them.
I'm available for any of your questions here or on slack.

2023-10-11 13:35 UTC, sapirshuker commented on Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.yml
> +    - contextPath: Cybersixgill.AdditionalKeywords
Context outputs should be in the form Cybersixgill.context.Actor etc..

2023-10-17 08:35 UTC, sapirshuker commented
Hi @syed-loginsoft , we haven’t heard from you in a while.
Do you need any help with the pull request?

Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

2023-10-19 14:17 UTC, syed-loginsoft commented
@sapirshuker , Release notes already upto date. Guthub action is failing.
Please check

2023-10-19 14:37 UTC, sapirshuker commented
Hey @syed-loginsoft , 
You accidentally deleted the Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_2_6.md
and updated the Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_2_5.md file.
Please revert those changes.
The current version of the pack is 1.2.6. It needs to be raised.
in order to do that after you revert the 1_2_6.md and the 1_2_5.md changes, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.
I'm available for any of your questions here or on slack.

2023-10-19 14:39 UTC, sapirshuker commented on Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.yml
> +    - contextPath: Cybersixgill.AdditionalKeywords
@syed-loginsoft Please note I added another comment.

2023-10-19 15:08 UTC, syed-loginsoft commented
If I restore file and run command. It gets deleted.
![image](https://github.com/demisto/content/assets/97145640/035c1c2e-318f-46c5-99d5-841042ee9359)

2023-10-19 15:38 UTC, sapirshuker commented
> If I restore file and run command. It gets deleted. ![image](https://user-images.githubusercontent.com/97145640/276661049-035c1c2e-318f-46c5-99d5-841042ee9359.png)

@syed-loginsoft , you should merge from master and then retry.

2023-10-20 04:10 UTC, syed-loginsoft commented
> > If I restore file and run command. It gets deleted. ![image](https://user-images.githubusercontent.com/97145640/276661049-035c1c2e-318f-46c5-99d5-841042ee9359.png)
> 
> @syed-loginsoft , please try to merge from master and retry.

Done.

2023-10-22 07:40 UTC, kgal-pan commented
Hi @syed-loginsoft  - As discussed in the email thread with the rest of the CyberSixGill team, we will be closing this PR as the introduced changes are not best practice and the solution should be redesigned before it can be contributed.

Thanks for the effort you put into this work!

2023-10-22 07:40 UTC, closed without merging