[EWS V2] Handle ErrorMimeContentConversionFailed error
demisto/content pull request #30066
Opened 2023-10-05 11:21 UTC by samuelFain

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [XSUP-28730](https://jira-dc.paloaltonetworks.com/browse/XSUP-28730)

## Description
Add handling for error object `ErrorMimeContentConversionFailed` that can be returned in the stream of results when fetching email objects.

## Must have
- [x] Tests
- [x] Documentation

2023-10-24 14:24 UTC, JasBeilin requested changes
looks great, see my comments.

2023-10-24 14:24 UTC, JasBeilin commented on Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
> +            demisto.debug(f"Encountered an AttributeError error object while iterating: {exc}.\
```suggestion
            demisto.debug(f"Encountered an Attribute error object while iterating: {exc}.\
```

2023-10-24 14:24 UTC, JasBeilin commented on Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
The test makes sure that the value error still errors the same?
Can we add a test to make sure that if we receive a list like [incident, error, incident] we return 2 incidents?

2023-10-24 18:16 UTC, samuelFain commented on Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
Yes. the UT makes the differentiation between the different types of errors.
Also, I've added another UT to test the use-case you described in the second line of the comment.

2023-10-25 14:40 UTC, JasBeilin approved these changes

2023-10-25 19:03 UTC, samuelFain commented
@yuvalbenshalom
Requesting force merge due to the following issue which fails the build: https://jira-dc.paloaltonetworks.com/browse/CIAC-8733

2023-10-26 10:03 UTC, merged