Threatzone Integration
demisto/content pull request #30097
Opened 2023-10-09 13:32 UTC by vvelitkn-malwation

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Malwation Threatzone Integration

## Must have
- [ ] Tests
- [] Documentation

2023-10-09 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=30097) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=30097) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: root<br/>:x: vvelitkn-malwation<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=30097) it.</sub>

2023-10-12 13:51 UTC, ilappe requested changes
Thank you @@vvelitkn-malwation for great contribution!

please see my comment 
and feel free to reach out to me with any questions - I'm available here or on slack :)

@melamedbn, will made the review of the palybooks etc.

2023-10-12 13:51 UTC, ilappe commented on Packs/ThreatZone/Integrations/ThreatZone/ThreatZone.py
> +    )
The `ComandREsults` object has the `outputs_prefix` and `outputs_key_field` properties which together combined the old key `ThreatZone.Limits(val.Job_ID == obj.Job_ID)` 
please use this syntax in all the CommandaResults objects it's our new convention 
see https://xsoar.pan.dev/docs/integrations/code-conventions#commandresults

BTW - where is the `Job_ID` defined ? it should be a key in each object in `availability["Limits"]` 

```suggestion
    return CommandResults(
        outputs_prefix='ThreatZone.Limits',
        outputs_key_field='Job_ID',
        readable_output=readable_output,
        outputs=availability["Limits"]
    )
```

2023-10-12 13:51 UTC, ilappe commented on Packs/ThreatZone/Integrations/ThreatZone/ThreatZone.py
> +    ispublic = args.get('isPublic')
`isPublic` is not defined in the yml file 
and instead there is the arg `private` which are not been used in the code

2023-10-12 13:51 UTC, ilappe commented on Packs/ThreatZone/Integrations/ThreatZone/ThreatZone.py
> +    )
as mention above - please refactor the usage of CommandResults, and if you need to return two different keys to the context (like `ThreatZone.Limit` and `ThreatZone.Analysis`) you can return list of two CommandResults one for each of them

2023-10-12 13:51 UTC, ilappe commented on Packs/ThreatZone/Integrations/ThreatZone/README.md
> +
this command are not defined in the yml file and not implemented in the py file

Please regenerate a README.md file.
To do that, please run the `demisto-sdk generate-docs` command (use the -e flag for using a commad_examples file) - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#generate-docs.

2023-10-12 13:51 UTC, ilappe commented on Packs/ThreatZone/Integrations/ThreatZone/ThreatZone.py
> +            demisto.results(test_module(params))
```suggestion
            return_results(test_module(params))
```

2023-10-16 07:36 UTC, melamedbn commented
Hi @vvelitkn-malwation,

I trust you're doing well. Firstly, thank you for your contribution; the effort you've put into the content is clear! I've taken some time to review it, and I'd like to share a few insights to help streamline and refine the playbooks:

### Playbooks: 
**Analyze File - Sandbox - ThreatZone, Analyze File - Static Scan - ThreatZone & Sanitize File - CDR - ThreatZone**

1. For consistency across all tasks, please maintain the same input logic. For instance, in task 1 and 8, it would be ideal to use `user inputs.File.EntryID` instead of just `File.EntryID`.
2. I recommend opting for the complex context method as opposed to the simple one. *(See attached screenshot for reference)*.

![Screenshot 2023-10-16 at 10 22 42](https://github.com/demisto/content/assets/28757135/e1c5a6b3-558d-490d-b6b4-7e651f13945a)
**Simple**

![Screenshot 2023-10-16 at 10 22 59](https://github.com/demisto/content/assets/28757135/9c179aa8-bcd6-4808-8f43-87d2ddb62644)
**Complex**

3. There appear to be some irregularities with the grid arrows that might benefit from correction.

![image](https://github.com/demisto/content/assets/28757135/5daad582-34a6-43df-aa2e-f0f35cb635ca)
**Current state**

![image](https://github.com/demisto/content/assets/28757135/62759d24-a676-42be-9df2-cd31fa6e74d1)
**Preferred state**

4. **Recommendation:** If the primary difference between the playbooks is just the static/sandbox/CDR scan, consider consolidating the three playbooks into one. You could introduce a conditional task along with a playbook input, allowing users to select their preferred flow.

Your dedication is truly commendable, and these suggestions are geared towards enhancing the usability of your contribution. If you have any queries or if there's anything you'd like to discuss further, please don't hesitate to reach out.

Warm regards,
Ben

2023-10-17 14:43 UTC, vvelitkn-malwation commented
> Hi @vvelitkn-malwation,
> 
> I trust you're doing well. Firstly, thank you for your contribution; the effort you've put into the content is clear! I've taken some time to review it, and I'd like to share a few insights to help streamline and refine the playbooks:
> ### Playbooks:
> 
> **Analyze File - Sandbox - ThreatZone, Analyze File - Static Scan - ThreatZone & Sanitize File - CDR - ThreatZone**
> 
>     1. For consistency across all tasks, please maintain the same input logic. For instance, in task 1 and 8, it would be ideal to use `user inputs.File.EntryID` instead of just `File.EntryID`.
> 
>     2. I recommend opting for the complex context method as opposed to the simple one. _(See attached screenshot for reference)_.
> 
> 
> ![Screenshot 2023-10-16 at 10 22 42](https://user-images.githubusercontent.com/28757135/275425363-e1c5a6b3-558d-490d-b6b4-7e651f13945a.png) **Simple**
> 
> ![Screenshot 2023-10-16 at 10 22 59](https://user-images.githubusercontent.com/28757135/275425393-9c179aa8-bcd6-4808-8f43-87d2ddb62644.png) **Complex**
> 
>     3. There appear to be some irregularities with the grid arrows that might benefit from correction.
> 
> 
> ![image](https://user-images.githubusercontent.com/28757135/275425883-5daad582-34a6-43df-aa2e-f0f35cb635ca.png) **Current state**
> 
> ![image](https://user-images.githubusercontent.com/28757135/275426020-62759d24-a676-42be-9df2-cd31fa6e74d1.png) **Preferred state**
> 
>     4. **Recommendation:** If the primary difference between the playbooks is just the static/sandbox/CDR scan, consider consolidating the three playbooks into one. You could introduce a conditional task along with a playbook input, allowing users to select their preferred flow.
> 
> 
> Your dedication is truly commendable, and these suggestions are geared towards enhancing the usability of your contribution. If you have any queries or if there's anything you'd like to discuss further, please don't hesitate to reach out.
> 
> Warm regards, Ben

Hi Ben,
Thank you for your valuable feedback. I've incorporated an additional function for obtaining sanitized files. I will proceed with the necessary changes in playbooks and anticipate completion within the next few hours.

2023-10-19 08:34 UTC, ilappe requested changes
Thank @vvelitkn-malwation!

clean and nice implementation!
please see my few small comments

2023-10-19 09:16 UTC, vvelitkn-malwation commented on Packs/ThreatZone/Integrations/ThreatZone/ThreatZone.py
> +                outputs_prefix='ThreatZone.Analysis',
ThreatZone.Result is deprecated, we use ThreatZone.Analysis instead, fixed in YML.

2023-10-19 10:52 UTC, melamedbn commented
Hi @vvelitkn-malwation,

Did you get a chance to address my feedback?

Thanks,
Ben

2023-10-19 10:54 UTC, vvelitkn-malwation commented
> Hi @vvelitkn-malwation,
> 
> Did you get a chance to address my feedback?
> 
> Thanks, Ben

Yes, I done changes according to your valuable feedbacks.

2023-10-22 07:25 UTC, melamedbn approved these changes

2023-10-23 09:15 UTC, ilappe approved these changes
veri nice!
the only one comment
i think it will be better to define unique context path for the 3 upload types
`static` `cdr` and `sandbox`
as currently the context output are ThreatZone.Submission for all of them
and if customer will want to know which of the outputs url are for the `static` and which of the `cdr `- he can’t
so may be the good context output should be `ThreatZone.CdrSubmission`  `ThreatZone.StaticSubmission`  etc
but if you think this is not so important - we can go forward in the process

2023-10-23 11:42 UTC, merged