[DevSecOps] MinIO Bug fix and add new commands
demisto/content pull request #30132
Opened 2023-10-12 12:05 UTC by pl-brault

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description

This PR adds 3 commands to the integration `MinIO`:
- minio-copy-object: Create an object by server-side copying data from another object.
- minio-set-tag: Set tags configuration to an object.
- minio-get-tags: Get tags configuration of an object.

It also fix an issue where the parameter `bucket_name` had an predefined value to empty string which show a dropdown menu for the `minio-put-object` and `minio-fput-object` commands. It fix the same issue on the parameter `length` for the `minio-get-object` command.

Here is the visual picture:
![image](https://github.com/demisto/content/assets/143391737/d792fbfd-1170-45b1-85a2-31500138ffd4)
Here is the code: 
![image](https://github.com/demisto/content/assets/143391737/887ebc57-e451-47ab-922e-4aae4c3ce499)

## Must have
- [ ] Tests
- [ ] Documentation

2023-10-16 09:11 UTC, ilappe requested changes
Thanks @pl-brault for your contribution!
great job!
please see my review comment
in addition - please see the build errors
- [validation](https://app.circleci.com/pipelines/github/demisto/content/309045/workflows/d1558365-d3a2-47eb-9925-cf5cd8c4462d/jobs/723810?invite=true#step-119-7477_92)  some small issue about the docker image and `.` missed
- [Lint issue](https://app.circleci.com/pipelines/github/demisto/content/309045/workflows/d1558365-d3a2-47eb-9925-cf5cd8c4462d/jobs/723814?invite=true#step-120-4999_52) 

if you need any help, i'm here..

2023-10-16 09:11 UTC, ilappe commented on Packs/DevSecOps/Integrations/MinIO/MinIO.py
> +        outputs_prefix='MinIO.Objects',
the context output not defined in the YML file

2023-10-16 09:11 UTC, ilappe commented on Packs/DevSecOps/Integrations/MinIO/MinIO.py
> +        outputs_prefix='MinIO.Objects',
the context output not defined in the YML file

2023-10-16 09:11 UTC, ilappe commented on Packs/DevSecOps/Integrations/MinIO/MinIO.yml
>    dockerimage: demisto/minio:1.0.0.19143
see the [validation error ](https://app.circleci.com/pipelines/github/demisto/content/309045/workflows/d1558365-d3a2-47eb-9925-cf5cd8c4462d/jobs/723810?invite=true#step-119-4918_163) about this docker image

2023-10-16 09:11 UTC, ilappe commented on Packs/DevSecOps/Integrations/MinIO/MinIO.py
> +    bucket_name_src = str(args.get('bucket_name_src', ''))
no need to use `str()`,
relevant for all places

2023-10-16 12:09 UTC, pl-brault commented
Hi @ilappe 
I've fix all your review comments and there no more build errors

2023-10-18 12:49 UTC, ilappe approved these changes
Great job!

2023-10-18 12:49 UTC, merged