Api updates
demisto/content pull request #30210
Opened 2023-10-16 20:24 UTC by andrew-paloalto

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
- https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6490
- https://jira-dc.paloaltonetworks.com/browse/EXPANDR-5050
- https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6145
- https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6561

## Description
Adding several new commands and addressing some known bugs and usability issues.

## Must have
- [x] Tests
- [x] Documentation

2023-10-18 16:58 UTC, johnnywilkes requested changes

2023-10-18 16:58 UTC, johnnywilkes commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
> +    search_from = args.get('search_from', 0)
The new `search_to` and `search_from` args need to be added to the yml file as well as README

2023-10-18 16:58 UTC, johnnywilkes commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
>    dockerimage: demisto/python3:3.10.13.75921
run command `demisto-sdk format -ud -i Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml`

2023-10-18 22:03 UTC, johnnywilkes commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
>    dockerimage: demisto/python3:3.10.13.75921
resolved

2023-10-18 22:04 UTC, johnnywilkes approved these changes
@andrew-paloalto , looking good

2023-10-19 08:47 UTC, sapirshuker commented
@ShirleyDenkberg can you please review?

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
> +      description: IP Address to enrich.
```suggestion
      description: IP address to enrich.
```

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
> +    description: Returns enrichment for a Domain.
```suggestion
    description: Returns enrichment for a domain.
```

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/Integrations/CortexXpanse/README.md
> +Returns additional details about a specific incident. Note: Incident IDs may also be references as "Case IDs' elsewhere in the API.
```suggestion
Returns additional details about a specific incident. Note: Incident IDs may also be references as "Case IDs" elsewhere in the API.
```

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/Integrations/CortexXpanse/README.md
> +| incident_id | The ID of the incident to be fetched | Required |
```suggestion
| incident_id | The ID of the incident to be fetched. | Required |
```

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/Integrations/CortexXpanse/README.md
> +| IP.Address              | String   | IP Address.                                                |
```suggestion
| IP.Address              | String   | IP address.                                                |
```

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/Integrations/CortexXpanse/README.md
> +Returns enrichment for a Domain.
```suggestion
Returns enrichment for a domain.
```

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/Integrations/CortexXpanse/README.md
> +| Domain.Name                 | String   | Name of the Domain.                                        |
```suggestion
| Domain.Name                 | String   | Name of the domain.                                        |
```

2023-10-19 09:20 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_12.md
> +- Updated the ***asm-list-asset-internet-exposure*** command to support pagination
```suggestion
- Updated the ***asm-list-asset-internet-exposure*** command to support pagination.
```

2023-10-19 09:21 UTC, ShirleyDenkberg commented
@johnnywilkes @sapirshuker Doc review completed.

2023-10-19 09:31 UTC, sapirshuker commented
Hey, @andrew-paloalto 
Please fix the doc review comments and let me know when the PR is ready for review.

2023-10-19 09:36 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_12.md
> +Updated the Cortex Xpanse integration to add the following commands:
```suggestion
- Updated the Cortex Xpanse integration to add the following commands:- 
```

2023-10-19 09:36 UTC, ShirleyDenkberg commented on Packs/CortexXpanse/ReleaseNotes/1_0_12.md
> +- ***domain***
```suggestion
   - ***asm-get-incident***
   - ***ip***
   - ***domain***
```

2023-10-19 12:48 UTC, andrew-paloalto commented
@sapirshuker I think all comments have been addressed.

2023-10-19 14:54 UTC, sapirshuker submitted a review, later dismissed

2023-10-19 22:18 UTC, BigEasyJ requested changes
Great job! Just left a few comments.

2023-10-19 22:18 UTC, BigEasyJ commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
> +- name: integration_reliability
Please add this to the ReadMe as well as an integration parameter.

2023-10-19 22:18 UTC, BigEasyJ commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
> +        search_from = int(search_from)
I would move this up to where the variable is instantiated, since you will always have a default.

2023-10-19 22:18 UTC, BigEasyJ commented on Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
> +        search_to = int(search_to)
I would move this up to where the variable is instantiated, since you will always have a default.

2023-10-22 08:36 UTC, sapirshuker commented
@BigEasyJ is it ready for merge?

2023-10-23 13:19 UTC, johnnywilkes commented on Packs/CortexXpanse/Integrations/CortexXpanse/README.md
> +4.
```suggestion
```
@andrew-paloalto , you should remove this line

2023-10-23 16:16 UTC, johnnywilkes commented
@sapirshuker , this is ready to merge.  Please and thank you

2023-10-23 18:03 UTC, andrew-paloalto commented
@sapirshuker I think we're good now

2023-10-24 10:49 UTC, sapirshuker approved these changes

2023-10-24 10:49 UTC, merged