[ASM] - EXPANDER 4377 - ServiceNow ITSM Enrichment
demisto/content pull request #30296
Opened 2023-10-18 12:38 UTC by BigEasyJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-4377](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-4377)

## Description
Create a new playbook to query ServiceNow ITSM for service owners.

## Must have
- [x] Tests
- [x] Documentation

2023-10-18 14:04 UTC, johnnywilkes requested changes

2023-10-18 14:04 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_ITSM_Enrichment.yml
> +  '27':
@BigEasyJ , in this task (or a separate task) we need to make sure SNOW-ITSM integration is enabled or there is no reason to continue.

2023-10-18 18:27 UTC, johnnywilkes approved these changes
@BigEasyJ , thanks for the change.

2023-10-18 18:46 UTC, capanw commented
LGTM

2023-10-19 08:46 UTC, sapirshuker commented
@ShirleyDenkberg , Can you please review?

2023-10-19 09:41 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_ITSM_Enrichment.yml
> +      description: Set the beginning of a key used for querying ServiceNow using SN descriptions and a timestamp.
```suggestion
      description: Set the beginning of a key used for querying ServiceNow using ServiceNow descriptions and a timestamp.
```

2023-10-19 09:41 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_ITSM_Enrichment.yml
> +      description: Set the remaining query value with SN short descriptions for querying ServiceNow.
```suggestion
      description: Set the remaining query value with ServiceNow short descriptions for querying ServiceNow.
```

2023-10-19 09:41 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_ITSM_Enrichment.yml
> +      description: Conditional to check if values were provided to the search terms input or not.
```suggestion
      description: Check if values were provided to the search terms input or not.
```

2023-10-19 09:41 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_ITSM_Enrichment.yml
> +      description: Conditional to check if any assignees were found in the assigned_to property of retrieved ServiceNow tickets.
```suggestion
      description: Check if any assignees were found in the assigned_to property of retrieved ServiceNow tickets.
```

2023-10-19 09:41 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_ITSM_Enrichment.yml
> +  description: Search terms to be used in the ServiceNow ITSM query search
```suggestion
  description: Search terms to be used in the ServiceNow ITSM query search.
```

2023-10-19 09:41 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_ITSM_Enrichment_README.md
> +* ServiceNow v2
```suggestion
ServiceNow v2
```

2023-10-19 09:44 UTC, ShirleyDenkberg commented
@sapirshuker When there is only one item in a list, no hyphen is needed.

@johnnywilkes @capanw @melamedbn @sapirshuker Doc review completed.

2023-10-19 10:37 UTC, sapirshuker commented
Hey, @BigEasyJ
Please fix the doc review comments and let me know when the PR is ready for review.

2023-10-19 19:39 UTC, BigEasyJ commented
@sapirshuker updated and ready

2023-10-22 10:42 UTC, sapirshuker commented
Build process failed due an known issue: [CIAC-6419](https://jira-hq.paloaltonetworks.local/browse/CIAC-6419)

2023-10-22 10:46 UTC, sapirshuker approved these changes

2023-10-23 14:53 UTC, sapirshuker commented
Hey, @BigEasyJ 
please resolve the conflicts.

2023-10-24 12:16 UTC, sapirshuker commented
Build process failed due an known issue: [CIAC-6419](https://jira-hq.paloaltonetworks.local/browse/CIAC-6419)

2023-10-24 12:17 UTC, sapirshuker approved these changes

2023-10-24 13:38 UTC, merged