CS Falcon: fix fetch incidents issues
demisto/content pull request #30358
Opened 2023-10-23 16:20 UTC by ilaner

* Fetch the incidents using the offset
* Will not increase fetch limit
* Should fix missing incidents

2023-10-24 12:03 UTC, yuvalbenshalom requested changes
looks good. see my comments and please answer my questions on DM.

2023-10-24 13:49 UTC, ilaner commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +    demisto.debug(f"CrowdStrikeFalconMsg: Getting idp detections from {endpoint_url} with {params=}. {response=}")
it doesn't

2023-10-25 07:18 UTC, yuvalbenshalom approved these changes

2023-10-25 11:20 UTC, ilaner commented
Needs a force merge as it fails on XSOAR NG to pull the integration docker image:
```
Failure message: Script failed to run: failed pull of docker image: [demisto/py3-tools:1.0.0.79419]. Local pull error: failed to pull docker Image "demisto/py3-tools:1.0.0.79419" got error: [exit status 125] with stderr: [Resolving "demisto/py3-tools" using unqualified-search registries (/etc/containers/registries.conf)
```

2023-10-25 12:40 UTC, merged