Made premium packs free. Added new alert states to the Code42 Check I…
demisto/content pull request #30361
Opened 2023-10-23 22:30 UTC by jdullum

…ncydr Status And Close XSOAR Incident playbook. Deprecated commands.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
The main goal of this PR is to move the playbooks from the Code42 Insider Threat Remediation premium pack to the Code42 free pack. It also fixes a minor bug with the "Check Incydr Status and Close XSOAR Incident" playbook, and deprecates commands that are no longer supported. 

## Must have
- [x] Tests
- [x] Documentation

2023-10-23 22:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=30361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=30361) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=30361) it.</sub>

2023-10-25 09:17 UTC, ilappe requested changes
Thanks @jdullum for your great effort in this contribution!
i reviewed the code related files, please see my few comments 
in addition please note the [validation error](https://app.circleci.com/pipelines/github/demisto/content/311646/workflows/a5dac0ef-a72b-4970-ad2d-3abc3df52a3b/jobs/725761?invite=true#step-119-10549_92) 

@melamedbn will review the playbooks etc.

2023-10-25 09:17 UTC, ilappe commented on Packs/Code42/Integrations/Code42/Code42.py
our policy is to remaining the functionality of a deprecated commands as is
so please return back the deprecated commands functionality

2023-10-25 09:17 UTC, ilappe commented on Packs/Code42/Integrations/Code42/Code42_test.py
as mentioned above, we will need back the test for the deprecated commands 
as the implementation of them should remain as is.

2023-10-25 15:38 UTC, jdullum commented on Packs/Code42/Integrations/Code42/Code42.py
Hi @ilappe, these commands no longer work because the backend APIs have been removed. We followed our API deprecation process, which included notifying our customers, so no one should be using them anymore. It looks like we forgot to mark these commands as deprecated in XSOAR, but we did previously update our playbooks to stop using them. I also can't simply leave the code as-is, because the functionality has been removed from py42 too. While we would prefer to remove the commands altogether since they are broken and no longer supported by our product, doing so caused build errors. If you have another suggestion for us to do in cases like this, please let me know. I did mark the version as a breaking change, and documented it in the release notes.

2023-10-26 06:56 UTC, ilappe commented on Packs/Code42/Integrations/Code42/Code42.py
@jdullum 
so if this are the case, i think it will be helpful for existing user to know about the alternative command within the war room
so can you please, in the readable_output of the deprecated command, to print `Deprecated. please use the <the alternative command> command` ?

2023-10-26 23:04 UTC, jdullum commented on Packs/Code42/Integrations/Code42/Code42.py
Sure!

2023-10-29 11:06 UTC, ilappe approved these changes
Thanks @jdullum, great work!
@melamedbn, did you finish with the review?

2023-11-05 14:17 UTC, melamedbn approved these changes

2023-11-06 07:52 UTC, ilappe commented
pre commit fail due to change in gitlab files, will be fixed in the internal PR

2023-11-06 07:52 UTC, merged