EclecticIQv3integration
demisto/content pull request #30508
Opened 2023-10-30 00:15 UTC by mikhva-eiq

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
New version of integration with EclecticIQ Intelligence Center. New commands and functionality.

## Must have
- [ ] Tests
- [x] Documentation

2023-10-30 00:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=30508) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=30508) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=30508) it.</sub>

2023-10-31 12:29 UTC, ilappe commented
Thanks @mikhva-eiq for the contribution!
1. what are the relation between `EclecticIQIntelligenceCenterv3` and `EclecticIQv2`? 
2. please sign the CLA https://github.com/demisto/content/pull/30508#issuecomment-1784288143
3. please fix the workflow issues [lint & unit test](https://circleci.com/gh/demisto/content/726879), [validation](https://circleci.com/gh/demisto/content/726884)

i'm reviewing the files..

2023-11-01 12:15 UTC, melamedbn commented
Hi @mikhva-eiq,

I hope this message finds you well. Firstly, I'd like to express our appreciation for your contribution to our content.

Regarding the indicator fields, it would be great if we could align with our best practices. It helps in ensuring consistency and ease of use for users. For instance:

- Replacing `EclecticIQ Entity Description` with `Description`
- Replacing `EclecticIQ Entity Title` with `Title`
etc.


These changes can streamline the user's experience, especially when they are searching or querying for indicators.

If there's a specific reason behind introducing these new fields, we'd love to understand more. Your insights are always valuable.

Thanks again for your collaboration and understanding. Look forward to your feedback!

Best regards,
Ben

2023-11-05 10:46 UTC, ilappe requested changes
Thanks @mikhva-eiq, your contribution is very appreciated!
in addition of [this comment](https://github.com/demisto/content/pull/30508#issuecomment-1787124782)
please see my review comments

2023-11-05 10:46 UTC, ilappe commented on Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
> +'''
please use the command calls within the `try except` block

2023-11-13 11:03 UTC, ilappe commented
Hi @mikhva-eiq  , we haven’t heard from you in a while.
Do you need any help with the pull request?

Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

2023-11-18 13:21 UTC, mikhva-eiq commented on Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.yml
fixed.

2023-11-18 13:25 UTC, mikhva-eiq commented on Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
> +            output_result.append(record)
fixed

2023-11-18 13:26 UTC, mikhva-eiq commented on Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
> +            )
fixed

2023-11-18 13:27 UTC, mikhva-eiq commented on Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
> +        del sighting_tag[:]
fixed

2023-11-21 23:05 UTC, mikhva-eiq commented
@ilappe could you please take a look, there are some checks failed which I cannot get clearly, like secrets found in readme are examples or ip/uris, also that's a message related to tlp_color which I cannot get why it appears (the same in my local demisto-sdk)

also want to ask, can we go forward without test coverage? if it's a must what is test coverage expected? anyway it will delay to fix that

2023-11-21 23:07 UTC, mikhva-eiq commented
Hi @melamedbn regarding indicator fields, reason to add is following - EclecticIQ platform is TIP which aggregates threat intel and provides consolidated result, in case of our customers we have use case when they want to enrich/ingest TI from EIQ but still to have capability to have description field from different TI integration in XSOAR, thatst a reason why there are additional fields added.

2023-11-22 07:34 UTC, ilappe commented on Packs/EclecticIQ/Author_image.png
please revert this change
logo should be 120x50

2023-11-22 07:55 UTC, ilappe commented
Hi @mikhva-eiq 
- secret error - if it's not a secret, please add the url mentioned in the [error](https://app.circleci.com/pipelines/github/demisto/content/319900/workflows/dfaa05b6-807f-462c-bfdf-b1f3075ad92f/jobs/730358?invite=true#step-118-450_47) to the ignore file Packs/EclecticIQ/.secrets-ignore.
- `tlp` error - i made a small change to fix it.
- unit test (coverage) - we must have a `*_test.py` file in the integration directory with tests for each command appear in the integration. you can create it based on the [previous test file ](https://github.com/demisto/content/blob/master/Packs/EclecticIQ/Integrations/EclecticIQv2/EclecticIQv2_test.py) and coverage should be at least 70%.
- please note the [lint errors](https://app.circleci.com/pipelines/github/demisto/content/319900/workflows/dfaa05b6-807f-462c-bfdf-b1f3075ad92f/jobs/730361?invite=true#step-120-9074_48), there is description regarding the issue
thanks in advance

let me know if you need any help

2023-11-22 09:58 UTC, melamedbn approved these changes

2023-11-23 09:42 UTC, zed-eiq commented
hello! i see that @melamedbn has approved this PR. Just to be clear: do you still need us to make those changes you've described @ilappe here https://github.com/demisto/content/pull/30508#issuecomment-1822272715 ? 🙏

2023-11-23 10:14 UTC, ilappe commented
@zed-eiq 
> hello! i see that @melamedbn has approved this PR. Just to be clear: do you still need us to make those changes you've described @ilappe here [#30508 (comment)](https://github.com/demisto/content/pull/30508#issuecomment-1822272715) ? 🙏

yes, he approved his responsibility items (like fields, playbooks etc)
but my comment is still relevant
thanks

2023-12-06 12:53 UTC, mikhva-eiq commented
Hi @ilappe could you provide some guidance regarding Mypy errors? for me makes no sense following:
- Name "datetime" already defined (possibly by an import)  [no-redef] // it's first import, why error?
- "Type[datetime]" has no attribute "datetime"  [attr-defined] // it has that attribute, why error?
some errors related to "demisto Common"
- Incompatible types in assignment (expression has type "URL", variable has type "IP")  [assignment] 
and also
-home/circleci/project/Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py:2068:51: error: "object" has no attribute "get"  [attr-defined]     ...           record["observable_classification"] = maliciousness_to_meta...

whats expected from my side to resolve that? or just exclude that from Mypy scope??

2023-12-12 09:48 UTC, ilappe commented
Hi @mikhva-eiq 
i push few small fix regarding the mypy errors
please validate them.
regarding the error "error: "object" has no attribute "get" [attr-defined]"
it's due to `maliciousness_to_meta` have the "Unknown" key with empty `{}`

you can ignore them like i did

2023-12-24 07:36 UTC, ilappe commented
Hi @mikhva-eiq
what's the status here ?
if you need any help, i will be happy to help..

2024-01-16 09:21 UTC, mikhva-eiq commented
@ilappe what could happen with ci/cd on PANW side? I made a couple of commits but in the checks see errors related to demisto-sdk or something else but not the integration.

2024-01-23 10:18 UTC, merged