Add is malicious to process Cortex XDR
demisto/content pull request #30519
Opened 2023-10-30 12:16 UTC by ilaner

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-29510?filter=-1

Add is malicious to the Process artifact

2023-10-30 14:21 UTC, yuvalbenshalom requested changes
looks good. see my comment.

2023-10-30 14:21 UTC, yuvalbenshalom commented on Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
> +            relevant_processes = filter(lambda p: p.get("SHA256") == file_sha, process_context)
please also check that sha is not None or empty

2023-11-01 13:21 UTC, yuvalbenshalom approved these changes

2023-11-02 11:55 UTC, ilaner commented
This fails on Test XDR Playbook execute script on XSOAR SAAS.
The failure is unrelated to this PR and happens in other builds. Need to force merge.
@yuvalbenshalom

2023-11-05 15:20 UTC, merged