Akamai Guardicore Event Collector
demisto/content pull request #30606
Opened 2023-11-01 13:59 UTC by dansterenson

Still need to add UT.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue
](https://jira-hq.paloaltonetworks.local/browse/CIAC-6559?filter=-1)

## Must have
- [ ] Tests
- [ ] Documentation

2023-11-06 17:18 UTC, DeanArbel requested changes

2023-11-06 17:18 UTC, DeanArbel commented on Packs/GuardiCore/Integrations/AkamaiGuardicoreEventCollector/AkamaiGuardicoreEventCollector.py
> +        {'from_ts': end_time} if len(retrieve_events) < limit else {'from_ts': start_time, 'offset': offset + limit}
Does the API treat `start_time` as `gt` or `gte`? i.e. will there be a need to dedupe the data between 2 subsequent runs?

2023-11-06 17:18 UTC, DeanArbel commented on Packs/GuardiCore/Integrations/AkamaiGuardicoreEventCollector/AkamaiGuardicoreEventCollector.py
> +            event['_time'] = event.get('start_time')
It should be faster to do this in comprehension i.e.
```suggestion
        [{**event, '_time': event.get('start_time')} for event in events]
```

2023-11-06 17:18 UTC, DeanArbel commented on Packs/GuardiCore/Integrations/AkamaiGuardicoreEventCollector/AkamaiGuardicoreEventCollector.py
> +    hr = tableToMarkdown(name='Test Event', t=events)
These aren't necessarily test events

2023-11-06 17:18 UTC, DeanArbel commented on Packs/GuardiCore/Integrations/AkamaiGuardicoreEventCollector/AkamaiGuardicoreEventCollector.yml
> +- defaultvalue: https://some_url.com
Is there some other default URL that can be configured?

2023-11-06 17:18 UTC, DeanArbel commented on Packs/GuardiCore/Integrations/AkamaiGuardicoreEventCollector/AkamaiGuardicoreEventCollector_description.md
> +- Set *Max events number per fetch* the the fetch events parameters \9default 1000)
```suggestion
- Set *Max events number per fetch* the the fetch events parameters. default 1000)
```

2024-01-07 12:35 UTC, DeanArbel approved these changes
lgtm

2024-01-10 10:31 UTC, eepstain approved these changes

2024-01-30 16:33 UTC, closed without merging