[ASM] EXAPNDR-6427 Adding delete context changes
demisto/content pull request #30627
Opened 2023-11-02 05:28 UTC by capanw

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6427

## Description
Adding DeleteContext at the start of the playbook.

## Must have
- [ ] Tests
- [ ] Documentation

2023-11-02 05:30 UTC, capanw commented
@johnnywilkes @BigEasyJ, Can you guys please review. Thank you

2023-11-02 12:02 UTC, johnnywilkes requested changes
@capanw , looks good.  See my slack comment about adding to .packs-ignore for the validation.  Also, please update the playbook README via SDK (so it includes DeleteContext script).  After that we should be GTG

2023-11-02 16:01 UTC, capanw commented
@johnnywilkes Thanks for the suggestions - Updated the pack ignore and readme.

2023-11-02 16:39 UTC, johnnywilkes approved these changes
@capanw , approved.  You can let XSOAR reviewers to know to merge when possible

2023-11-02 17:08 UTC, capanw commented
@melamedbn @sapirshuker Approved from our side. Can you guys review and merge. Thanks

2023-11-06 10:13 UTC, sapirshuker approved these changes

2023-11-06 10:13 UTC, merged