GIT_DEPTH=1
demisto/content pull request #30902
Opened 2023-11-14 14:40 UTC by michal-dagan

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-11-15 09:22 UTC, michal-dagan commented on .gitlab/ci/.gitlab-ci.variables.yml
> +  GIT_DEPTH: 1
```suggestion
  GIT_DEPTH: 100
```

2023-11-15 09:31 UTC, michal-dagan commented on .gitlab/ci/.gitlab-ci.variables.yml
> +  GIT_DEPTH: 100
```suggestion
  GIT_DEPTH: 1000
```

2023-11-15 11:56 UTC, michal-dagan commented on .gitlab/ci/.gitlab-ci.global.yml
> +        git fetch -q --deepen="$DEEPEN_LENGTH" origin "$BASE_REF" "$HEAD_REF";
```suggestion
        git fetch -q --deepen="$DEEPEN_LENGTH" origin;
```

2023-11-15 21:21 UTC, kobymeir requested changes

2023-11-15 21:21 UTC, kobymeir commented on .gitlab/ci/.gitlab-ci.global.yml
> +  - DEEPEN_LENGTH=${DEEPEN_LENGTH:-50}
don't run it when the current branch is master

2023-11-16 16:00 UTC, kobymeir approved these changes

2023-11-18 19:30 UTC, merged