Generic polling   wildfire
demisto/content pull request #30929
Opened 2023-11-15 12:27 UTC by karinafishman

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8740

## Description
Deprecate for the old playbook of Wildfire

## Must have
- [ ] Tests
- [x] Documentation

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2.yml
> +  description: File type e.g. "PE".
```suggestion
  description: File type, e.g., "PE".
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2.yml
> +  description: The indicator we tested.
```suggestion
  description: The indicator tested.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2.yml
> +  description: The File object.
```suggestion
  description: The file object.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2_README.md
> +* WildFire-v2
```suggestion
WildFire-v2
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2_README.md
> +| URL | URL of the webpage or file url to detonate. The URL is taken from the context. | URL.Data | Optional |
```suggestion
| URL | URL of the webpage or file URL to detonate. The URL is taken from the context. | URL.Data | Optional |
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2_README.md
> +| DBotScore.Indicator | The indicator we tested. | string |
```suggestion
| DBotScore.Indicator | The indicator tested. | string |
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2_README.md
> +| File | The File object. | unknown |
```suggestion
| File | The file object. | unknown |
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
> +      description: Check if integration instance is enabled.
```suggestion
      description: Check if the integration instance is enabled.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
> +      description: Check if file type is supported.
```suggestion
      description: Check if the file type is supported.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
> +        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
```suggestion
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.12/Cortex-XSOAR-Administrator-Guide/Automations
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
> +        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
```suggestion
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.12/Cortex-XSOAR-Administrator-Guide/Automations
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
> +      description: Check if there are any supported files to upload to wildfire for detonation.
```suggestion
      description: Check if there are any supported files to upload to WildFire for detonation.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
> +  description: The duration after which to stop polling and to resume the playbook. (in minutes)
```suggestion
  description: The duration after which to stop polling and to resume the playbook (in minutes).
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2.yml
> +  description: The file type, e.g. "PE".
```suggestion
  description: The file type, e.g., "PE".
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2_README.md
> +* SetAndHandleEmpty
```suggestion
SetAndHandleEmpty
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2_README.md
> +| Timeout | The duration after which to stop polling and to resume the playbook. \(in minutes\) | 15 | Optional |
```suggestion
| Timeout | The duration after which to stop polling and to resume the playbook \(in minutes\). | 15 | Optional |
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/Playbooks/WildFire_-_Detonate_file_v2_README.md
> +| File.Type | The file type, e.g. "PE". | string |
```suggestion
| File.Type | The file type, e.g., "PE". | string |
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_37.md
> +- Deprecated. Use Detonate File From URL - WildFire v2 instead.
```suggestion
Deprecated. Use Detonate File From URL - WildFire v2 instead.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_37.md
> +- New: Detonate one or more files using the Wildfire integration. This playbook returns relevant reports to the War Room and file reputations to the context data.
```suggestion
New: Detonate one or more files using the Wildfire integration. This playbook returns relevant reports to the War Room and file reputations to the context data.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_37.md
> +- Deprecated. Use Detonate URL - WildFire v2.2 instead.
```suggestion
Deprecated. Use Detonate URL - WildFire v2.2 instead.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_37.md
> +- New: Detonate a webpage or remote file using the WildFire integration. This playbook returns relevant reports to the War Room and file reputations to the context data.
```suggestion
New: Detonate a webpage or remote file using the WildFire integration. This playbook returns relevant reports to the War Room and file reputations to the context data.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_37.md
> +- Deprecated. Use Detonate URL - WildFire v2.2 instead.
```suggestion
Deprecated. Use Detonate URL - WildFire v2.2 instead.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_37.md
> +- Deprecated. Use WildFire - Detonate file v2 instead.
```suggestion
Deprecated. Use WildFire - Detonate File v2 instead.
```

2023-11-16 11:17 UTC, ShirleyDenkberg commented on Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_37.md
> +- New: Detonate one or more files using the Wildfire integration. This playbook
```suggestion
New: Detonate one or more files using the Wildfire integration. This playbook
```

2023-11-16 13:36 UTC, idovandijk requested changes
Great job with the PR! Here are my comments, numbered so you can easily refer to them if you have questions:

### Detonate File From URL - Wildfire v2

1. Note how the condition checks if Wildfire **OR** Wildfire v2 is enabled. However, the command you're then executed is tied to Wildfire v2 only:
![image](https://github.com/demisto/content/assets/43602124/1b075ac1-66e6-439e-a3ca-9702c80485e0)

Since the old Wildfire version is deprecated, and we're releasing a new playbook, let's also fix the condition to check only if v2 is enabled.
Also, please note that as a best practice, we prefer to not tie the command to the integration brand unless we have a reason to
![image](https://github.com/demisto/content/assets/43602124/cdd6dfeb-3d35-4f7c-bd7e-e8e879466330)

but since we really intend to only use Wildfire v2 here, we're OK here.

2. As we are tackling resource hogs, let's rethink the timeout. I think 15 is excessive. Try it on a medium size and larger size file please, and check the duration of the task (you will see the duration in the task itself), and let's tweak the timeout input so that it's at a safe level, yet not too long:
![image](https://github.com/demisto/content/assets/43602124/c2664b80-6a08-42be-954e-8a96bd54d216)

3. It seems that the "hash" argument is deprecated ;) let's use the SHA256 argument (and test it).

4. Please also update the playbook description (and generate new readme) to indicate that we're using Wildfire v2 (not Wildfire)

5. Please add the Unique transformer to the FileURL input, to ensure we don't accidentally process duplicate URLs (also part of our performance efforts):
![image](https://github.com/demisto/content/assets/43602124/fd9a7653-d97f-4d90-a070-e2496d1cab0c)

6. We have new outputs from the `wildfire-report` command. Let's add those that we think are useful to the playbook outputs. Please make sure to output the sub-keys as well. For example, not only output the `WildFire.Report.ExtractedURL` object, but also the `WildFire.Report.ExtractedURL.URL` and `WildFire.Report.ExtractedURL.Verdict` outputs.
FYI - outputting the main key will also output the sub-keys. However, not outputting the sub-keys will cause the parent playbooks to be blind to them, so it's good practice to declare the sub-keys as well.

7. Looks like there are 2 tests for our playbook. Let's check if one of them is irrelevant - E.g., using the GenericPolling playbook, thus not really testing what we want.

### Detonate URL - Wildfire v2.2
Excellent job!
8. Let's tweak the unrealistic `Timeout` playbook input of 60 minutes to something much shorter.
9. Let's also add a Unique transformer to the `URL.Data` input
10. Please also update the playbook description to Wildfire v2, as well as the playbook README.

### Wildfire - Detonate File v2
11. Please add a Unique transformer to the File input.
12. Let's tweak the Timeout input here too.
13. I believe this condition should be changed to "Is Not Empty". The reason is that in the previous tasks we set those keys, and if there's no value, they'll be set with an empty value. This will cause the `Is Defined` condition to pass through because the key is defined, but it's empty. I'm not entirely sure if my theory is correct here, but it's worth being on the safe side.
14. In the Get Report task, let's use the non deprecated argument SHA256 (and test):
![image](https://github.com/demisto/content/assets/43602124/ad89a0ef-b5e8-45db-8d87-a4ce675ac681)
15. Please add more outputs that you think could be useful, to the playbook outputs.
16. Please update the playbook description to be Wildfire v2 (and the playbook README).
17. Please check if we can remove a test from the "tests" section of our playbook YML file. If one of the tests is not testing the file detonation flow, it's irrelevant.

### Deprecated Playbooks
18. Please update the README of the deprecated playbooks, so that it will be documented on our documentation portal too.

### Release Notes
19. While the release-notes are correct, it's worth adding a line explaining that the v2/v2.2 playbook features polling at the integration level, instead of using the GenericPolling playbook.

Let me know if you're unsure about anything or need help! Awesome job.

2023-11-21 12:44 UTC, idovandijk reviewed
Looks good, however I see that point 11 is still missing (Unique for the File playbook input), and see that point 1 is still as before (I remember you wanted to change it - your call).
Once these are fixed let me know and I'll approve

2023-11-21 14:52 UTC, idovandijk approved these changes
Well done

2023-11-22 11:40 UTC, merged