Cloud user investigation inputs description fix
demisto/content pull request #30965
Opened 2023-11-19 09:18 UTC by OmriItzhak

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8940)

## Description
Updated the outputs description for `cloud user investigation - generic` playbook

## Must have
- [ ] Tests
- [ ] Documentation

2023-11-19 15:29 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic_README.md
> +| GcpAnomalousNetworkTraffic | Determines whether there are events of anomalous network traffic performed by the user in the GCP environment.<br/>Possible values: True/False. | string |
Should be boolean

2023-11-19 15:29 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic_README.md
> +| GcpSuspiciousApiUsage | Determines whether there are events of suspicious API usage by the user in the GCP environment.<br/>Possible values: True/False. | string |
Should be boolean

2023-11-19 15:29 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic_README.md
> +| GsuiteUserPasswordLeaked | Determines whether user's password was leaked in the G Suite environment.<br/>Possible values: True/False. | string |
Should be boolean

2023-11-19 15:29 UTC, idovandijk commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation_README.md
> +| GcpAnomalousNetworkTraffic | Determines whether there are events of anomalous network traffic performed by the user in the GCP environment.<br/>Possible values: True/False. | string |
Should be boolean

2023-11-19 15:29 UTC, idovandijk commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation_README.md
> +| GcpSuspiciousApiUsage | Determines whether there are events of suspicious API usage by the user in the GCP environment.<br/>Possible values: True/False. | string |
Should be boolean

2023-11-19 15:29 UTC, idovandijk commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation_README.md
> +| GsuiteUserPasswordLeaked | Determines whether the user's password was leaked in the G Suite environment.<br/>Possible values: True/False. | string |
Should be boolean

2023-11-19 15:29 UTC, idovandijk commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation.yml
> +  type: string
Should be boolean

2023-11-19 15:29 UTC, idovandijk commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation.yml
> +  type: string
Should be boolean

2023-11-19 15:30 UTC, idovandijk commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation.yml
> +  type: string
Should be boolean

2023-11-19 15:30 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
> +  type: string
Should be boolean

2023-11-19 15:30 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
> +  type: string
Should be boolean

2023-11-19 15:30 UTC, idovandijk commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
> +  type: string
Should be boolean

2023-11-19 15:31 UTC, idovandijk requested changes
Looks good. I commented on some outputs that should be Boolean instead of String. Please update them and regenerate playbook README, then ping me and I'll approve :)

2023-11-20 08:38 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic_README.md
> +| GcpAnomalousNetworkTraffic | Determines whether there are events of anomalous network traffic performed by the user in the GCP environment.<br/>Possible values: True/False. | string |
Done

2023-11-20 08:38 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic_README.md
> +| GcpSuspiciousApiUsage | Determines whether there are events of suspicious API usage by the user in the GCP environment.<br/>Possible values: True/False. | string |
Done

2023-11-20 08:38 UTC, OmriItzhak commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation_README.md
> +| GcpAnomalousNetworkTraffic | Determines whether there are events of anomalous network traffic performed by the user in the GCP environment.<br/>Possible values: True/False. | string |
Done

2023-11-20 08:38 UTC, OmriItzhak commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation_README.md
> +| GcpSuspiciousApiUsage | Determines whether there are events of suspicious API usage by the user in the GCP environment.<br/>Possible values: True/False. | string |
Done

2023-11-20 08:38 UTC, OmriItzhak commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation.yml
> +  type: string
Done

2023-11-20 08:38 UTC, OmriItzhak commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation.yml
> +  type: string
Done

2023-11-20 08:39 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
> +  type: string
Done

2023-11-20 08:39 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
> +  type: string
Done

2023-11-20 08:39 UTC, OmriItzhak commented on Packs/CommonPlaybooks/Playbooks/playbook-Cloud_User_Investigation_-_Generic.yml
> +  type: string
Done

2023-11-20 08:39 UTC, OmriItzhak commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation.yml
> +  type: string
Done

2023-11-20 08:39 UTC, OmriItzhak commented on Packs/GCP-Enrichment-Remediation/Playbooks/playbook-GCP_-_User_Investigation_README.md
> +| GsuiteUserPasswordLeaked | Determines whether the user's password was leaked in the G Suite environment.<br/>Possible values: True/False. | string |
Done

2023-11-20 14:27 UTC, ShirleyDenkberg commented on Packs/AWS-Enrichment-Remediation/Playbooks/playbook-AWS_-_User_Investigation_README.md
> +* AWS - CloudTrail
```suggestion
AWS - CloudTrail
```
If there is only one item in a "list" then that item does not get a bullet.

2023-11-20 14:27 UTC, ShirleyDenkberg commented on Packs/AWS-Enrichment-Remediation/Playbooks/playbook-AWS_-_User_Investigation_README.md
> +* aws-cloudtrail-lookup-events
```suggestion
aws-cloudtrail-lookup-events
```

2023-11-20 14:27 UTC, ShirleyDenkberg commented on Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation_README.md
> +* Azure Log Analytics
```suggestion
Azure Log Analytics
```

2023-11-20 14:27 UTC, ShirleyDenkberg commented on Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation_README.md
> +* azure-log-analytics-execute-query
```suggestion
azure-log-analytics-execute-query
```

2023-11-20 14:28 UTC, ShirleyDenkberg commented
@idovandijk Doc review completed.

2023-11-21 10:36 UTC, idovandijk approved these changes
great

2023-11-21 11:58 UTC, merged