Symantec web security service pack long running
demisto/content pull request #30990
Opened 2023-11-20 11:55 UTC by israelpoli

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-5375

## Must have
- [ ] Tests
- [ ] Documentation

2023-11-26 09:33 UTC, ShirleyDenkberg commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/README.md
> +    | Fetch interval in seconds, (The minimum threshold is 30 seconds) | True |
```suggestion
    | Fetch interval in seconds. The minimum threshold is 30 seconds. | True |
```

2023-11-26 09:33 UTC, ShirleyDenkberg commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.yml
> +description: Palo Alto Networks Symantec Cloud Secure Web Gateway Event Collector integration for XSIAM.
```suggestion
description: Palo Alto Networks Symantec Cloud Secure Web Gateway Event Collector integration for Cortex XSIAM.
```

2023-11-26 09:33 UTC, ShirleyDenkberg commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.yml
> +- display: Fetch interval in seconds, (The minimum threshold is 30 seconds)
```suggestion
- display: Fetch interval in seconds. The minimum threshold is 30 seconds.
```

2023-11-26 09:33 UTC, ShirleyDenkberg commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector_description.md
> +1. In Service Mode, select Account Maintenance > MDM, API Keys.
```suggestion
1. In Service Mode, select **Account Maintenance** > **MDM, API Keys**.
```

2023-11-26 09:33 UTC, ShirleyDenkberg commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector_description.md
> +3. In the API section (bottom half of the screen), click Add API Key.
```suggestion
3. In the API section (bottom half of the screen), click **Add API Key**.
```

2023-11-26 09:33 UTC, ShirleyDenkberg commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector_description.md
> +5. Click Add.
```suggestion
5. Click **Add**.
```

2023-11-26 09:33 UTC, ShirleyDenkberg commented
@yuvalbenshalom Doc review completed.

2023-11-28 09:17 UTC, cweltPA commented
@ShirleyDenkberg 
Added another readme file to the main pack level, if you could review it as well : 
https://github.com/demisto/content/blob/8d9147040c0927098e18e3d47fde8d818c7ce51d/Packs/SymantecCloudSecureWebGateway/README.md

2023-11-29 16:30 UTC, yuvalbenshalom requested changes
this is a preliminary review. I did not review yet the zip parts and tests.
but there is already points to start working with.

2023-11-30 13:25 UTC, israelpoli commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.yml
> +fromversion: 6.8.0
This is a required field
so I changed it to version 8.2.0 like the other collectors that merged recently

2023-12-05 15:52 UTC, yuvalbenshalom requested changes
looks good.
see my comments.

2023-12-05 15:52 UTC, yuvalbenshalom commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.py
> +        except Exception as err:
probably here you sold remove also the temp file, if it existed.

2023-12-05 15:52 UTC, yuvalbenshalom commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.py
> +        ) = extract_logs_and_push_to_XSIAM(last_run_model, tmp_file_path, token_expired)
you sold remove the themp file if there is an exception here.

2023-12-05 15:52 UTC, yuvalbenshalom commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.py
> +def get_file_size(file_path: Path) -> int:
this is not really nesseary.
better use stat().st_size directly/

also when you write something like this(and you did):
file_size = get_file_size(file_path)
you already know form the variable name that it is file size.
so this is just as readable:
file_size = file_path.stat().st_size.

2023-12-05 15:52 UTC, yuvalbenshalom commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.py
> +def get_events_and_write_to_file_system(
why are you passing all params? lets talk about this.

2023-12-05 15:52 UTC, yuvalbenshalom commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.py
> +    client.get_logs(params)
dose this run in a resemble time?

2023-12-05 15:52 UTC, yuvalbenshalom commented on Packs/SymantecCloudSecureWebGateway/Integrations/SymantecCloudSecureWebGatewayEventCollector/SymantecCloudSecureWebGatewayEventCollector.py
> +def management_next_fetch(
maybe calculate next fetch?

2023-12-07 11:58 UTC, yuvalbenshalom approved these changes

2023-12-07 20:21 UTC, merged