Add a manuale fatch once in 12 hours
demisto/content pull request #31123
Opened 2023-11-26 14:19 UTC by RosenbergYehuda

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-11-30 14:19 UTC, kgal-pan commented on Packs/iDefense/pack_metadata.json
This Pack is deprecated.

2023-11-30 15:25 UTC, RosenbergYehuda commented on Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
> +    last_updated = current_time.strftime("%a, %d %b %Y %H:%M:%S GMT")
fixed

2023-11-30 15:27 UTC, RosenbergYehuda commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +def has_passed_time_threshold(timestamp_str, hours_threshold):
Done.

2023-12-04 12:43 UTC, JasBeilin reviewed
I am not sure about the new method in CSP. Lets talk about it.

2023-12-04 15:20 UTC, RosenbergYehuda commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +        raise ValueError('Either hours_threshold or seconds_threshold must be provided.')
fixed

2023-12-05 14:01 UTC, ShirleyDenkberg commented on Packs/Base/ReleaseNotes/1_32_53.md
> +- Added a utility methods to determine the time gap between a given datetime and the present moment.
```suggestion
Added a utility method to determine the time gap between a given datetime and the present moment.
```

2023-12-05 14:02 UTC, ShirleyDenkberg commented
@kgal-pan @JasBeilin Doc review completed.

2023-12-06 15:44 UTC, JasBeilin requested changes
Looks great, please address my comments.

2023-12-06 16:44 UTC, RosenbergYehuda commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +    timestamp = dateparser.parse(timestamp_str,['%Y-%m-%dT%H:%M:%SZ'])
fixed

2023-12-07 05:53 UTC, JasBeilin approved these changes
Looks good, see my comments.

2023-12-07 13:22 UTC, RosenbergYehuda commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +    # using astimezone since utcnow() returns a naive datetime object
fixed

2023-12-10 12:28 UTC, merged