test
demisto/content pull request #31152
Opened 2023-11-28 09:16 UTC by michal-dagan

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-05 10:09 UTC, kobymeir commented on .gitlab/ci/.gitlab-ci.on-push.yml
>  fan-in-on-merge:
```suggestion
fan-in-on-merge:
  needs:
    - job: pre_job
```

2023-12-05 10:11 UTC, kobymeir commented on Tests/scripts/clone_and_cache_gitlab_repos.sh
> +  curl --fail --silent --show-error --output /dev/null --header "PRIVATE-TOKEN: ${token}" "https://${user_info}${host}/api/v4/projects/${CI_PROJECT_ID}/repository/branches?search=${branch}" 1>/dev/nu
perhaps revert to ls-remote

2023-12-07 05:38 UTC, kobymeir requested changes

2023-12-07 10:52 UTC, kobymeir approved these changes

2023-12-07 11:19 UTC, michal-dagan commented
force-merge: 
we have split the `Tests/scripts/download_conf_repos.sh` into 2 files:
1. clone_and_cache_gitlab_repos.sh
2. use_cached_gitlab_repos.sh

Due to GitHub limitation, the renamed file (download_conf_repos.sh) was mistakenly recognized as a deleted file. Therefore, force-merging is required for error code BA115.

2024-06-07 00:13 UTC, closed without merging