EXPANDR-7181 Fix issues for AWS rule logic
demisto/content pull request #31237
Opened 2023-12-01 13:33 UTC by capanw

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-7181

## Description
SOC bug fixes

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-04 05:16 UTC, BigEasyJ commented on Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_9.md
> +- Updated the script to fix an issue with security group rule case and add a change flag.
```suggestion
Updated the script to fix an issue with security group rule case and add a change flag.
```

2023-12-06 07:26 UTC, capanw commented
@BigEasyJ Can you review this?

2023-12-06 18:20 UTC, capanw commented
@adi88d PR is ready for review.

2023-12-07 15:25 UTC, adi88d requested changes
Great job!

2023-12-07 15:25 UTC, adi88d commented on Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_1_9.md
> +Updated the script to fix an issue with security group rule case and add a change flag.
```suggestion
- Updated the Docker image to: *demisto/python3:3.10.13.82467*.
- Updated the script to fix an issue with security group rule case and add a change flag.
```

2023-12-07 16:56 UTC, capanw commented
@adi88d. Thank you for the suggestion. Updated Readme.

2023-12-11 10:45 UTC, ShirleyDenkberg commented
@BigEasyJ @adi88d Doc review completed.

2023-12-11 13:45 UTC, adi88d approved these changes

2023-12-11 13:45 UTC, merged