Qualys_Add_New_Commands
demisto/content pull request #31463
Opened 2023-12-13 16:15 UTC by DaniSalcedoGFT

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
None

## Description
We added five new commands to Qualys due to new requirements of our project that needed more functionality of existing 
functionality.
This includes functionality regarding of qualys-update-unix-record and new functionality in order to map ESXi actives against the VCenters

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-13 16:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=31463) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31463) before we can accept your contribution.<br/><hr/>**Dani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=31463) it.</sub>

2023-12-14 09:37 UTC, adi88d commented
please sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31463) before we can accept your contribution.

2023-12-14 10:00 UTC, adi88d requested changes
Hi @DaniSalcedoGFT and thank you for your contribution!
- Please remove the empty lines from `Qualysv2.py`.
- Update release notes by using [demisto-sdk update-release-notes](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/update_release_notes/README.md) command.
- please format the `Qualysv2.yml` file and keep only the command you added.
- add the new commands to the `README.md` file by using [demisto-sdk generate-docs](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/generate_docs/README.md) command.

2023-12-14 10:00 UTC, adi88d commented on Packs/qualys/Integrations/Qualysv2/Qualysv2.py
> +
remove

2023-12-14 10:00 UTC, adi88d commented on Packs/qualys/Integrations/Qualysv2/Qualysv2.py
> +
remove

2023-12-14 10:00 UTC, adi88d commented on Packs/qualys/Integrations/Qualysv2/Qualysv2.py
> +
remove

2023-12-18 14:40 UTC, adi88d commented
Hi @DaniSalcedoGFT,
I see that you didnt update the `Qualysv2.py` file structure, Do you need any help with the pull request?

Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

2023-12-18 14:44 UTC, DaniSalcedoGFT commented
Hi @adi88d,
I'm short of time these days but I expect to push the changes before tomorrow ends.
Thanks for asking

2023-12-24 08:36 UTC, adi88d commented
Your contribution was impacted by changes in the git history of the content repo, and you see many file changes that are not related to your PR. Our team is currently working on a solution, and we hope that it will be resolved soon.

2023-12-25 09:32 UTC, adi88d commented
Hello @DaniSalcedoGFT  ,

Last Thursday, December 20th, there was an update in the content repo. This is why your PR looks like there were a lot of commits and files changed.
To fix this issue please do the following:
1. Save all of your changes locally or in a new branch.
2. Enter your forked repository page in GitHub.
3. At the top of the page, you will probably see something like this, please ensure you are in the master branch.
<img width="624" alt="image" src="https://github.com/demisto/content/assets/46249224/18836b1b-287e-4189-a16c-8b420a969073">

5. Click on “Sync fork” button on the top right side of the page.
<img width="646" alt="image" src="https://github.com/demisto/content/assets/46249224/19c343fe-2fb4-421c-a862-2bb62042444d">

6. The following message will appear (This branch has conflicts that must be resolved).

7. Click on the button “Discard commits”. Note that for this action to work, you should have permission to do a force push in the forked repo. If you don’t have one, ask the forked repo Owner to do that.
8. Enter your branch and repeat the same steps (4-6).
9. Check your PR, and see if your changes have been saved. If yes - you finished the update process.
10. If your PR does not show your changes, open a new PR with the changes that you saved at the beginning of the process.
11. In case you opened a new PR please close the old one, and update your reviewer with the new PR link.
12. Please paste on the new open PR the URL to your previous PR so our team member can continue the review from the same place.

Thank you very much for your contribution and your understanding of the situation.
Have a nice holiday season!

2023-12-31 13:10 UTC, adi88d commented
Hi @DaniSalcedoGFT , 
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

2023-12-31 13:10 UTC, closed without merging

2024-01-02 16:19 UTC, DaniSalcedoGFT commented
Hi @adi88d, I opened a new PR https://github.com/demisto/content/pull/31917
The new update on the content repo broke the push and every time I tried to push the content I wasn't pushing my changes