Google Cloud Storage - Update gcs-list-bucket-objects to support prefix and delimiter arguments.
demisto/content pull request #31496
Opened 2023-12-15 20:59 UTC by zdrouse

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
The google cloud storage python client supports these arguments.
https://github.com/googleapis/python-storage/blob/main/samples/snippets/storage_list_files_with_prefix.py

## Description
Add support prefix and delimiter support for gcs-list-bucket-objects command.  This will allow users to limit blobs returned from a GCS bucket.

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-17 15:30 UTC, adi88d requested changes
Great Job!
Thanks a lot for this contribution, It is highly appreciated.
I added some review comments and suggestion:
- remove the `Packs/GoogleCloudStorage/CONTRIBUTORS.json` file
- update release notes for the pack using [demisto-sdk update-release-notes](https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/update_release_notes/README.md) command
- add to the delimiter and prefix arguments to`GoogleCloudStorage/README.md`

2023-12-17 15:30 UTC, adi88d commented on Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
> +      name: prefix
```suggestion
       description: use a delimiter if you want to limit results within a specific "folder", default is None
    - name: delimiter
       description: specify to limit blobs within a "folder" i.e. "folder-1/" if blob is "folder-1/file.txt"
    - name: prefix
```
please remove the default value and fix the yml structure

2023-12-17 19:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=31496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31496) before we can accept your contribution.<br/>**11** out of **14** committers have signed the CLA.<br/><br/>:white_check_mark: zdrouse<br/>:white_check_mark: eyalpalo<br/>:white_check_mark: YuvHayun<br/>:white_check_mark: ssokolovich<br/>:white_check_mark: content-bot<br/>:white_check_mark: Ni-Knight<br/>:white_check_mark: MichaelYochpaz<br/>:white_check_mark: amshamah419<br/>:white_check_mark: ilaner<br/>:white_check_mark: mmhw<br/>:white_check_mark: ShirleyDenkberg<br/>:x: jbabazadeh<br/>:x: karinafishman<br/>:x: kobymeir<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=31496) it.</sub>

2023-12-17 19:19 UTC, zdrouse reviewed
I committed the suggestion for YAML file although I'm not sure I understand it since all the other arguments and commands already implemented don't follow it

2023-12-18 14:45 UTC, ShirleyDenkberg commented on Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
> +    - description: Specify to limit blobs within a "folder" i.e. "folder-1/" if blob is "folder-1/file.txt".
```suggestion
    - description: Specify to limit blobs within a "folder" i.e., "folder-1/" if blob is "folder-1/file.txt".
```

2023-12-18 14:45 UTC, ShirleyDenkberg commented on Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
> +    - description: Use a delimiter if you want to limit results within a specific "folder" and without any nested blobs i.e. "/".
```suggestion
    - description: Use a delimiter if you want to limit results within a specific "folder" and without any nested blobs i.e., "/".
```

2023-12-18 14:45 UTC, ShirleyDenkberg commented on Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/README.md
> +<td style="width: 421px;">Specify to limit blobs within a "folder" i.e. "folder-1/" if blob is "folder-1/file.txt".</td>
```suggestion
<td style="width: 421px;">Specify to limit blobs within a "folder" i.e., "folder-1/" if blob is "folder-1/file.txt".</td>
```

2023-12-18 14:45 UTC, ShirleyDenkberg commented on Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/README.md
> +<td style="width: 421px;">Use a delimiter if you want to limit results within a specific "folder" and without any nested blobs i.e. "/".</td>
```suggestion
<td style="width: 421px;">Use a delimiter if you want to limit results within a specific "folder" and without any nested blobs i.e., "/".</td>
```

2023-12-18 14:45 UTC, ShirleyDenkberg commented on Packs/GoogleCloudStorage/ReleaseNotes/1_0_12.md
> +  - ***prefix***
```suggestion
  - *delimiter*
  - *prefix*
```

2023-12-18 14:45 UTC, ShirleyDenkberg commented on Packs/GoogleCloudStorage/ReleaseNotes/1_0_12.md
> +- Added the following arguments to the **gcs-list-bucket-objects** command:
```suggestion
- Added the following arguments to the ***gcs-list-bucket-objects*** command:
```

2023-12-18 14:57 UTC, merged