Add Joesecurity onprem integration
demisto/content pull request #31674
Opened 2023-12-22 09:20 UTC by rundssoar

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
This is a new pull request, after PR 31576 was somehow "corrupted"
This implements https://xsoar.ideas.aha.io/ideas/FR-I-3623

## Description
Add a Version of the Integration that is compatible with an on-premise instance
The On-Premise Integration is a direct copy of the existing Cloud integration with the following adjustments:
- Removed already deprecated ´export-to-jbxview´ parameter usage
- Remove 'Cloud Only' ´delete-after-days´ parameter 
Details regarding Deprecation / Cloud Only taken from https://github.com/joesecurity/jbxapi/blob/master/jbxapi.py
- The "Detonate File - Joe Sandbox V2" Playbook has been adjusted, to support both Versions of the Integration instead of only the Cloud Version

## Must have
- [x] Tests
- [x] Documentation

2023-12-25 08:45 UTC, MLainer1 commented
Hi @rundssoar, thank you for your contribution.
After talking to our product design team, we prefer that you will add your changes to the original integration, and not create a new integration, as the changes that you added can be inserted to the original integration.
If you need any help with it, feel free to reach out.

2023-12-25 09:48 UTC, melamedbn approved these changes

2024-01-28 12:25 UTC, MLainer1 requested changes
Nice work!
Please add a breaking changes .json file to document the deprecated arguments.

When you are ready, let's schedule a quick demo to make sure everything works as expected.

2024-01-29 07:43 UTC, rundssoar commented on Packs/JoeSecurity/ReleaseNotes/1_1_18.md
> +
done

2024-01-29 08:50 UTC, rundssoar commented
@MLainer1 I've added the breaking changes json as requested
Unless there is something else missing, i'm ready to do the demo

2024-02-05 09:15 UTC, MLainer1 commented
Hi @rundssoar, thank you for your time in the demo. 
- Please add a detailed error message when using the premise argument with the cloud configuration, so the user will have a better understanding of the error.
- After checking, a deprecated argument will not appear on the xsoar UI.

Let me know when the PR is ready :)

2024-02-05 09:49 UTC, rundssoar commented
@MLainer1 I did implement the more detailed Error message, as discussed.
Also, when looking into that, i came across the fact, that the filename could be given to the API, so i made another small addition, that should have no functional impact: i added a parameter to the joe-submit-sample command, that allows to provide the filename of the sample. 
This is based on the Documentation of the functions: https://github.com/joesecurity/jbxapi/blob/master/docs/api.md
Since i made that after the demonstration, i'm adding a picture depicting the difference between providing and not providing the optional parameter here.
![filename_demo](https://github.com/demisto/content/assets/139948408/5c217c81-00a0-4c80-8183-857961061b71)
I did add it to the Readme and the Release Notes.
From my point, the PR is ready, unless you have any comments to that last minute additions

2024-02-12 13:52 UTC, ShirleyDenkberg commented on Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
> +  additionalinfo: Only use Features that are available in On-Premise installations
```suggestion
  additionalinfo: Only use features that are available in On-Premise installations
```

2024-02-12 13:52 UTC, ShirleyDenkberg commented on Packs/JoeSecurity/ReleaseNotes/1_1_18.md
> +- added *file_name* parameter to joe-submit-sample command to allow providing the original filename in submissions
```suggestion
- The *export_to_jbxview* parameter is deprecated and is no longer used.
- Added support for On-Premise Servers.
- Added the *file_name* parameter to the ***joe-submit-sample*** command to allow providing the original filename in submissions.
```

2024-02-12 13:54 UTC, ShirleyDenkberg commented
@melamedbn @michal-dagan @sapirshuker @MLainer1 Doc review completed.

2024-02-12 15:14 UTC, MLainer1 commented
Hi @rundssoar, please merge from master, and make sure to update the docker image. When it's done, we can move forward and merge the PR

2024-02-14 07:01 UTC, MLainer1 approved these changes

2024-02-14 07:01 UTC, merged