Feed misp
demisto/content pull request #31711
Opened 2023-12-25 09:16 UTC by maimorag

## Status
- [x] In Progress

## Related Issues
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-31708)
https://jira-dc.paloaltonetworks.com/browse/XSUP-31078

## Description
Adding pagination mechanism to ***Feed MISP***

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-31 09:18 UTC, eyalpalo requested changes
Nice, lets add some tests also.

2023-12-31 09:18 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +    demisto.debug(f'{indicators}')
Why do we logging all indicators? Lets print more helpful or informative info.

2023-12-31 09:18 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +    demisto.debug(f'fetch_indicators response: {response}')
We debug the response multiple times, lets consider removing some of the irrelevant debug logs.

2023-12-31 09:18 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +    demisto.debug("fetch_indicators starts")
Lets add the relevant params we are using to that debug log.

2023-12-31 09:18 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +        elif command == 'fetch-indicators':
Please remove.

2023-12-31 09:18 UTC, eyalpalo commented on Packs/FeedMISP/ReleaseNotes/1_0_30.md
> +- Fixed an issue where ***fetch-indicators*** fails if needs to fetch a large amount of indicator, by implanting pagination mechanism
```suggestion
- Fixed an issue where ***fetch-indicators*** timed out when large amount of indicators were fetched.
```

2023-12-31 09:18 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +    while True:
Lets remove the while True and replace it to a condition relates to the len of _search_query_per_page_ var.

2023-12-31 22:53 UTC, maimorag commented
@eyalpalo I finished applying the code review notes beside the unit test, and I'm fixing on fixing it

2024-01-01 09:19 UTC, eyalpalo requested changes

2024-01-01 09:19 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +    return response
```suggestion
    search_query_per_page = client.search_query(params_dict).get('response', {}).get('Attribute')
    while len(search_query_per_page):
        demisto.debug(f'search_query_per_page:{params_dict["page"]} {search_query_per_page}')
        response['response']['Attribute'].extend(search_query_per_page)
        params_dict['page'] += 1
        search_query_per_page = client.search_query(params_dict).get('response', {}).get('Attribute')
    return response
```

Pay attention to the indentation as the suggestion made in a text editor.

2024-01-01 09:19 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
> +def test_search_query_indicators_pagination(mocker):
Please add docstring with Given, When Then as we do for better readability.

2024-01-01 09:19 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_test.py
> +    mocker.patch.object(Client, '_http_request', return_value={'response': {'Attribute': ['data1', 'data2']}})
This unit test will have an infinite loop, you return the same response for each request and run in the method until an empty response is received.
Please fix this UT to suit the use case and fix the infinite loop.

2024-01-01 10:09 UTC, eyalpalo requested changes

2024-01-01 10:09 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +    demisto.debug(f"fetch_indicators starts using the params: {params}")
```suggestion
```

2024-01-01 10:09 UTC, eyalpalo commented on Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
> +    demisto.debug(f"fetch indicator results: {indicators} /n/n fetch_indicators finished")
Lets add the debug log to the fetch indicators itself instead of the main

2024-01-01 14:21 UTC, eyalpalo approved these changes

2024-01-02 08:50 UTC, merged