ANYRUN Add Command line parameter
demisto/content pull request #31802
Opened 2023-12-27 09:50 UTC by vasilydavydov

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-27 09:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=31802) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31802) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=31802) it.</sub>

2023-12-27 10:41 UTC, adi88d commented
@vasilydavydov 
Please sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31802)

2023-12-27 10:53 UTC, adi88d requested changes
Hi @vasilydavydov ,
Thank you for your contribution!
Good work :)
- Please bump the pack version in the pack_metadata.json file and add notes describing your changes to a new Release Notes file.
To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.
- Please attach screenshot or pdf file for this request API documentation

2023-12-27 10:53 UTC, adi88d commented on Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.py
> +
revert this

2023-12-27 10:53 UTC, adi88d commented on Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.py
> +            args['obj_ext_cmd'] = args.get('obj_ext_cmd')
```suggestion
        if obj_ext_cmd and (obj_type == 'file' or obj_type == 'download'):
            args['obj_ext_cmd'] = args.get('obj_ext_cmd')
```
and add this :
`obj_ext_cmd = args.get('obj_ext_cmd')`
in line 854 under:
`obj_type = args.get('obj_type')`

2023-12-28 05:54 UTC, vasilydavydov commented
Hello,

Pack_metadata.json and the new Release Notes file were updated in current brunch

Screenshot of documentation is here (link<https://any.run/api-documentation/#api-Analysis-PostAnalysis>)

***@***.***


Best regards,

Vasily Davydov | Product Manager | ANY.RUN

Mobile: +995 555 136 849<tel:+995555136849> | ***@***.******@***.***>



From: Adi Daud ***@***.***>
Date: Wednesday, 27 December 2023 at 14:53
To: demisto/content ***@***.***>
Cc: Vasily Davydov ***@***.***>, Mention ***@***.***>
Subject: Re: [demisto/content] ANYRUN Add Command line parameter (PR #31802)

@adi88d requested changes on this pull request.

Hi @vasilydavydov<https://github.com/vasilydavydov> ,
Thank you for your contribution!
Good work :)

  *   Please bump the pack version in the pack_metadata.json file and add notes describing your changes to a new Release Notes file.
To do that, please run the demisto-sdk update-release-notes command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.
  *   Please attach screenshot or pdf file for this request API documentation

________________________________

In Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.py<https://github.com/demisto/content/pull/31802#discussion_r1436943435>:

> @@ -865,7 +865,7 @@ def run_analysis(args):

             files = {

                 'file': (name, open(file_path, 'rb'))

             }

-

+

revert this

________________________________

In Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.py<https://github.com/demisto/content/pull/31802#discussion_r1436948075>:

> +        if obj_type == 'file' or obj_type == 'download' :

+            args['obj_ext_cmd'] = args.get('obj_ext_cmd')
⬇️ Suggested change

-        if obj_type == 'file' or obj_type == 'download' :

-            args['obj_ext_cmd'] = args.get('obj_ext_cmd')

+        if obj_ext_cmd and (obj_type == 'file' or obj_type == 'download'):

+            args['obj_ext_cmd'] = args.get('obj_ext_cmd')

and add this :
obj_ext_cmd = args.get('obj_ext_cmd')
in line 854 under:
obj_type = args.get('obj_type')

—
Reply to this email directly, view it on GitHub<https://github.com/demisto/content/pull/31802#pullrequestreview-1797043929>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BE5UTTL3Y2O26RU2SNXCIR3YLP42FAVCNFSM6AAAAABBEFF3NWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJXGA2DGOJSHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-12-28 10:26 UTC, ShirleyDenkberg commented on Packs/ANYRUN/ReleaseNotes/1_0_21.md
> +- Added the *obj_ext_cmd* argument to **anyrun-run-analysis** command.
```suggestion
Added the *obj_ext_cmd* argument to ***anyrun-run-analysis*** command.
```

2023-12-28 10:27 UTC, ShirleyDenkberg commented
@adi88d Doc review completed.

2023-12-28 10:32 UTC, adi88d approved these changes

2023-12-28 10:33 UTC, merged