Symantec EDR enhancement
demisto/content pull request #31837
Opened 2023-12-28 11:14 UTC by shubhamloginsoft

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-28 11:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=31837) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31837) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=31837) it.</sub>

2023-12-28 11:49 UTC, shubhamloginsoft commented
Hi @AradCarmi,
Meital Aizen has asked us to assign this PR to you, hence we are tagging you.
Can you kindly provide us with the partner ID so that we complete the contribution form?

2023-12-28 14:24 UTC, AradCarmi commented
> Hi @AradCarmi, Meital Aizen has asked us to assign this PR to you, hence we are tagging you. Can you kindly provide us with the partner ID so that we complete the contribution form?

Hey @shubhamloginsoft,
As you are not a partner, you can fill out the form as an individual contributor.
I will review the code ASAP meanwhile, please go over our build failing steps and make sure to fix all the validation issues.
Thank you and feel free to reach out with any questions!

2024-01-01 13:09 UTC, AradCarmi requested changes
Good Job! 
Please view my notes and the build failures.

2024-01-01 13:10 UTC, AradCarmi commented
@ShirleyDenkberg Can you please review the YAML and MD files?
Thanks!

2024-01-01 13:39 UTC, melamedbn commented
Hi @shubhamloginsoft,

As I was reviewing, a query came to mind regarding your distinction between Symantec Event and Symantec Incident.

From what I can see, there's a potential overlap, and I'd like to know if we could have streamlined the process by modifying the existing type and layout instead of creating new ones. What differentiates these two within our implementation? Understanding the specific nuances or use cases you had in mind will help assess the need for separate entities.

Thanks again for your diligent work. I am looking forward to your thoughts on this.

Best regards,
Ben

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/README.md
> +    | Incident data source | Fetch incident type, e.g. 'incident', 'event'. If not selected, incident will be selected | False |
```suggestion
    | Incident data source | Fetch incident type, e.g., 'incident', 'event'. If not selected, incident will be selected. | False |
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/README.md
> +Isolates or Quarantines endpoints by cutting connections that the endpoint(s) has to internal networks and external networks, based on the endpoint device IDs.
```suggestion
Isolates or quarantines endpoints by cutting connections that the endpoint(s) has to internal networks and external networks, based on the endpoint device IDs.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/README.md
> +Get system activities or Logs.
```suggestion
Get system activities or logs.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/README.md
> +Get events or System Alerts from EDR on-premise.
```suggestion
Get events or system alerts from EDR on-premise.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      Isolates or Quarantines endpoints by cutting connections that the endpoint(s) has to internal networks and external networks, based on the endpoint device IDs.
```suggestion
      Isolates or quarantines endpoints by cutting connections that the endpoint(s) has to internal networks and external networks, based on the endpoint device IDs.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +  additionalinfo: If not selected, will fetch Info Events.
```suggestion
  additionalinfo: If not selected, will fetch Info events.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/README.md
> +    | Incidents "Status" to filter out fetching as incidents. Comma-separated lists are supported, e.g., Open, In-Progress | If not selected, will fetch Open Incidents. | False |
```suggestion
    | Incidents "Status" to filter out fetching as incidents. Comma-separated lists are supported, e.g., Open, In-Progress | If not selected, will fetch Open incidents. | False |
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/README.md
> +    | Events "Status" to filter out fetching as incidents. Comma-separated lists are supported, e.g., Unknown, Success | If not selected, will fetch Success Events. | False |
```suggestion
    | Events "Status" to filter out fetching as incidents. Comma-separated lists are supported, e.g., Unknown, Success | If not selected, will fetch Success events. | False |
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/README.md
> +    | Events "Severity" to filter out fetching as incidents. Comma-separated lists are supported, e.g., Info, Warning | If not selected, will fetch Info Events. | False |
```suggestion
    | Events "Severity" to filter out fetching as incidents. Comma-separated lists are supported, e.g., Info, Warning | If not selected, will fetch Info events. | False |
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +    description: Get system activities or Logs.
```suggestion
    description: Get system activities or logs.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +    description: Get Audit Events.
```suggestion
    description: Get audit events.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: 'The type of the managed entity.Depending on this entity type, data would contain the corresponding entity content. Refer to this link  https://techdocs.broadcom.com/content/dam/br
```suggestion
      description: 'The type of the managed entity. Depending on this entity type, data would contain the corresponding entity content. Refer to this link  https://techdocs.broadcom.com/content/dam/broadcom/techdocs/symantec-security-software/endpoint-security-and-management/endpoint-detection-and-response/generated-pdfs/EDR_API_Legacy.pdf section 3.74 Entity for all the possible values for managed entity types.'
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: The device name (iseverity_id.e., the name of the endpoint or appliance associated with an event).
Not sure what this should be.

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +    description: Get events or System Alerts from EDR on-premise.
```suggestion
    description: Get events or system alerts from EDR on-premise.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: Event User associated with Domain.
```suggestion
      description: Event user associated with the domain.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: Process User Name.
```suggestion
      description: Process user name.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: Process Unique SID.
```suggestion
      description: Process unique SID.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: The MD5 Checksum of the file.
```suggestion
      description: The MD5 checksum of the file.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: Enriched Rule Description.
```suggestion
      description: Enriched rule description.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: The Unique event UUID.
```suggestion
      description: The unique event UUID.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: 'Indicates the reason of event being related to an incident. Possible values are: 1 - Event triggered the incident , 2 - Event is part of process lineage tracking, 3 - Event is lik
```suggestion
      description: 'Indicates the reason the event was related to an incident. Possible values are: 1 - Event triggered the incident , 2 - Event is part of process lineage tracking, 3 - Event is likely related to the incident.'
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: The Event Reference UID.
```suggestion
      description: The event reference UID.
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +      description: 'The unique ID of this allow list policy. This ID can be used in patch or delete request. Note: This is ignored if present in create request.'
```suggestion
      description: 'The unique ID of this allow list policy. This ID can be used in a patch or delete request. Note: This is ignored if present in a create request.'
```

2024-01-02 10:55 UTC, ShirleyDenkberg commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.yml
> +    - description: The SHA256 value of the target file,.
```suggestion
    - description: The SHA256 value of the target file.
```

2024-01-02 10:56 UTC, ShirleyDenkberg commented
@AradCarmi, @melamedbn @MLainer1 Doc review completed.

2024-01-02 15:15 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +        result["event_type"] = event_type
Since we're only receiving the Event Type ID in the response. To display the corresponding Event Type, I added a parsed type to use it in the mapper.

2024-01-02 15:18 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +EVENT_SEVERITY_MAPPING = {"1": 0.5, "2": 1, "3": 2, "4": 3, "5": 4, "6": 4}
We receive a Severity ID in the response. To map this severity ID to XSOAR severity, we utilize the following mapping.
1 = info (default)
2 = warning
3 = minor
4 = major
5 = critical
6 = fatal

2024-01-02 15:19 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +        query = self.fetch_query if self.fetch_query else ""
modified

2024-01-02 15:19 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +        )
modified

2024-01-02 15:19 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +                data = fetch_events(client)
modified

2024-01-02 15:19 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +    query = client.fetch_query
modified

2024-01-02 15:19 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +    condition = query if query else f"priority_level: ({priority}) AND state: ({state})"
modified

2024-01-02 15:20 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +        "query": condition,
modified

2024-01-02 15:20 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +    }
done

2024-01-02 15:20 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +    demisto.debug(f"length {len(results)}")
modified

2024-01-02 15:20 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +    demisto.debug(f"length of incident {len(incidents_insert)}")
created a new mediator function

2024-01-03 08:17 UTC, AradCarmi commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +EVENT_SEVERITY_MAPPING = {"1": 0.5, "2": 1, "3": 2, "4": 3, "5": 4, "6": 4}
@shubhamloginsoft Please use the `IncidentSeverity` class under CommonServerPython instead of the integers.

2024-01-03 09:22 UTC, shubhamloginsoft commented on Packs/SymantecEDR/Integrations/SymantecEDR/SymantecEDR.py
> +EVENT_SEVERITY_MAPPING = {"1": 0.5, "2": 1, "3": 2, "4": 3, "5": 4, "6": 4}
@AradCarmi done

2024-01-03 09:25 UTC, shubhamloginsoft commented
Hi @ShirleyDenkberg, I've implemented all the suggested changes.

2024-01-09 08:43 UTC, melamedbn approved these changes

2024-01-09 09:41 UTC, AradCarmi commented
@shubhamloginsoft Nicely done!
Please fix the build conflicts and also please update the TPB as we talked on Slack.
let's schedule a short demo in Slack or you can send me a video that you ran the command.
Thanks!

2024-01-11 15:11 UTC, AradCarmi approved these changes

2024-01-14 08:00 UTC, merged