Google-drive/get parents reco
demisto/content pull request #31859
Opened 2023-12-31 10:07 UTC by GalNakash-RecoLabs

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2023-12-31 12:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=31859) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31859) before we can accept your contribution.<br/>**4** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: GalNakash-RecoLabs<br/>:white_check_mark: ShirleyDenkberg<br/>:white_check_mark: content-bot<br/>:white_check_mark: daryakoval<br/>:x: tomer-pan<br/>:x: guytamir10<br/>:x: shmuel44<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=31859) it.</sub>

2024-01-01 11:37 UTC, YuvHayun requested changes
Hey @GalNakash-RecoLabs, thx a lot for your contribution!
I've added several small comments.
Also:
- Please try to [squash commits](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together) to fix the form issue.
- Make sure to run the `demisto-sdk pre-commit` command to fix the failures.
Thx again and let met know if any question comes up.

2024-01-01 11:37 UTC, YuvHayun commented on Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
> +  - name: google-drive-file-get-parents
```suggestion
  - name: google-drive-get-file-parents
```

2024-01-01 11:37 UTC, YuvHayun commented on Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
> +  - name: google-drive-file-get-parents
Also, make sure to add this info to the readme file.

2024-01-01 11:37 UTC, YuvHayun commented on Packs/GoogleDrive/ReleaseNotes/1_3_0.md
> +- Get list of parents directory command
```suggestion
- Added the **google-drive-get-file-parents** command.
```

2024-01-01 11:37 UTC, YuvHayun commented on Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive_test.py
> +        - Calling google-drive-drive-get command with the parameters provided.
```suggestion
        - Calling google-drive-get-file-parents command with the parameters provided.
```

2024-01-01 11:37 UTC, YuvHayun commented on Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive_test.py
> +    def test_drive_get_file_get_parents_success(self, mocker_http_request, gsuite_client):
```suggestion
    def test_drive_get_file_parents_success(self, mocker_http_request, gsuite_client):
```

2024-01-01 11:37 UTC, YuvHayun commented on Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
> +    Query a single file in Google Drive.
```suggestion
    google-drive-get-file-parents
    Query a single file in Google Drive to retrieve its parents.
```

2024-01-01 11:37 UTC, YuvHayun commented on Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
> +def file_get_parents_recursive(client: 'GSuiteClient', args: dict[str, str]) -> CommandResults:
let's put this logs under the main function.

2024-01-01 11:53 UTC, GalNakash-RecoLabs commented
@YuvHayun fixed!

2024-01-03 16:14 UTC, closed without merging