Block file generic enhancment for mde and falcon
demisto/content pull request #31885
Opened 2024-01-01 11:25 UTC by karinafishman

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-5747

## Description
- Added new playbook for block file using Crowdstrike.
- Added new playbook for block file using Microsoft Defender for Endpoint.
- Added additional vendors to "Block File - Generic v2" playbook,  CrowdStrike Falcon and Microsoft Defender for Endpoint.

## Must have
- [ ] Tests
- [ ] Documentation

2024-01-02 09:47 UTC, AdiPeret requested changes
Check my comments and change accordingly

2024-01-02 09:47 UTC, AdiPeret commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2.yml
> +  "20":
The same applies to MDE; we can have the checks done in the playbook itself.

2024-01-02 09:47 UTC, AdiPeret commented on Packs/CrowdStrikeFalcon/Playbooks/CrowdStrike_Falcon_-_Block_File.yml
Change the playbook layout so the conditional lines are clearer; currently, it's a bit hard to understand which condition each line is related to.

2024-01-02 09:47 UTC, AdiPeret commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File.yml
Same here, change the conditional lines to make it clearer to which condition each line refers to, it's currently hard to see which is which

2024-01-02 11:37 UTC, karinafishman commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2.yml
> +  "19":
* If I will remove the redundancy we will not be able to use this playbook as standalone.
* Anyway the command supports only 1 type every time, so we need 2 tasks in the playbook. one for MD5 and one for SHA256.

2024-01-03 13:53 UTC, AdiPeret approved these changes

2024-01-04 08:11 UTC, ssokolovich commented on Packs/CommonPlaybooks/Playbooks/playbook-Block_File_-_Generic_v2.yml
> +    skipunavailable: false
```suggestion
    skipunavailable: true
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/CommonPlaybooks/ReleaseNotes/2_5_5.md
> +- Added 2 vendors for block file: CrowdStrike Falcon and Microsoft Defender for Endpoint.
```suggestion
Added 2 vendors for blocked files: 
- CrowdStrike Falcon
- Microsoft Defender for Endpoint
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/CrowdStrikeFalcon/Playbooks/CrowdStrike_Falcon_-_Block_File.yml
> +      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'.
```suggestion
      description: Returns 'yes' if the integration brand is available. Otherwise returns 'no'.
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/CrowdStrikeFalcon/Playbooks/CrowdStrike_Falcon_-_Block_File.yml
> +  description: In this input you can insert either MD5 or SHA256 that you wish to block.
```suggestion
  description: In this input you can insert either MD5 or SHA256 to block.
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/CrowdStrikeFalcon/Playbooks/CrowdStrike_Falcon_-_Block_File_README.md
> +
```suggestion
CrowdStrikeFalcon

### Scripts

IsIntegrationAvailable

### Commands

cs-falcon-upload-custom-ioc

```
When there is only 1 item in a bulleted list, you do not use the bullet.

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/CrowdStrikeFalcon/Playbooks/CrowdStrike_Falcon_-_Block_File_README.md
> +| Hash | In this input you can insert either MD5 or SHA256 that you wish to block. |  | Optional |
```suggestion
| Hash | In this input you can insert either MD5 or SHA256 to block. |  | Optional |
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_11.md
> +- New: This playbook receives an MD5 or a SHA256 hash and adds it to the block list in CrowdStrike Falcon.
```suggestion
New: This playbook receives an MD5 or a SHA256 hash and adds it to the block list in CrowdStrike Falcon. 
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File.yml
> +      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'.
```suggestion
      description: Returns 'yes' if the integration brand is available. Otherwise returns 'no'.
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File.yml
> +  description: Whether to generate alert or not (the default is true)
```suggestion
  description: Whether to generate an alert or not. The default is true.
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File.yml
> +  description: In this input you can insert either MD5 or SHA256 that you wish to block.
```suggestion
  description: In this input you can insert either MD5 or SHA256 to block.
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File_README.md
> +* microsoft-atp-sc-indicator-create
```suggestion
MicrosoftDefenderAdvancedThreatProtection

### Scripts

IsIntegrationAvailable

### Commands

microsoft-atp-sc-indicator-create
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File_README.md
> +| GenerateAlert | Whether to generate alert or not \(the default is true\) | true | Optional |
```suggestion
| GenerateAlert | Whether to generate an alert or not. The default is true. | true | Optional |
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/MDE_-_Block_File_README.md
> +| Hash | In this input you can insert either MD5 or SHA256 that you wish to block. |  | Optional |
```suggestion
| Hash | In this input you can insert either MD5 or SHA256 to block. |  | Optional |
```

2024-01-04 11:51 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_24.md
> +- New: This playbook receives an MD5 or a SHA256 hash and adds it to the block list in Microsoft Defender for Endpoint.
```suggestion
New: This playbook receives an MD5 or a SHA256 hash and adds it to the block list in Microsoft Defender for Endpoint. 
```

2024-01-04 11:52 UTC, ShirleyDenkberg commented
@ssokolovich @AdiPeret Doc review completed.

2024-01-08 08:23 UTC, merged