CSP - IPv4 Regex update
demisto/content pull request #31913
Opened 2024-01-02 14:23 UTC by Ni-Knight

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-01-09 09:38 UTC, AradCarmi requested changes
Well done Dror!

2024-01-09 09:38 UTC, AradCarmi commented on Packs/Base/ReleaseNotes/1_33_16.md
> +- Fixed an issue with the IPv4 regex in Common Server Python not supporting IPv4s with ports.
```suggestion
- Added support for IPv4s with ports in the IPv4s regex.
```

2024-01-09 09:38 UTC, AradCarmi commented on Packs/Base/ReleaseNotes/1_33_16.md
> +- Fixed an issue with the URL regex not capturing a hyphen in the URL path.
```suggestion
- Fixed an issue where the URL regex not capturing a hyphen in the URL path.
```

2024-01-09 10:02 UTC, AradCarmi approved these changes

2024-01-09 14:58 UTC, MLainer1 commented on Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus_test.py
> +    "IP",
Was it intended?

2024-01-10 14:11 UTC, Ni-Knight commented on Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus_test.py
> +    "IP",
Yep, its an IP.

2024-01-11 08:21 UTC, merged