Illumio - Fix Invalid IP List HREF
demisto/content pull request #31921
Opened 2024-01-02 22:47 UTC by dsommerville-illumio

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues

No related issues.

## Description

Fixes hardcoded IP list HREF in Rapid Ransomware Containment playbook.

Re-submitting this PR after previous branch desync from upstream.

## Must have
- [x] Tests
- [x] Documentation

2024-01-02 22:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=31921) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31921) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: dsommerville-illumio<br/>:x: yashgaikwad-crest<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=31921) it.</sub>

2024-01-03 07:43 UTC, YuvHayun requested changes
Hey @dsommerville-illumio, thx for your contribution!
The PR looks good.
Please fix the pre-commit & validation failures.

2024-01-03 07:43 UTC, YuvHayun commented on Packs/Illumio/ReleaseNotes/1_0_18.md
> +- Fix hardcoded IP list HREF in Rapid ransomware containment playbook
```suggestion
- Fixed an issue where the playbook included a hardcoded IP list HREF.
```

2024-01-03 16:30 UTC, dsommerville-illumio commented
> Hey @dsommerville-illumio, thx for your contribution! The PR looks good. Please fix the pre-commit & validation failures.

@YuvHayun - The pre-commit error is 

```
Error: Playbook Rapid ransomware containment - Illumio uses inputs that do not appear in the inputs section: Answers
```

which seems to be triggering on the scriptarguments root for input values taken from a previous collection task. The `Enter the necessary inputs.Answers` root with accessor was correct in 6.2.0, has this formatting changed since then?

Note also that this error doesn't come up when running `demisto-sdk validate -i Packs/Illumio` locally (version 1.25.1), is there a difference between that and the pre-commit validation?

2024-01-04 08:01 UTC, YuvHayun commented
Hey @

> > Hey @dsommerville-illumio, thx for your contribution! The PR looks good. Please fix the pre-commit & validation failures.
> 
> @YuvHayun - The pre-commit error is
> 
> ```
> Error: Playbook Rapid ransomware containment - Illumio uses inputs that do not appear in the inputs section: Answers
> ```
> 
> which seems to be triggering on the scriptarguments root for input values taken from a previous collection task. The `Enter the necessary inputs.Answers` root with accessor was correct in 6.2.0, has this formatting changed since then?
> 
> Note also that this error doesn't come up when running `demisto-sdk validate -i Packs/Illumio` locally (version 1.25.1), is there a difference between that and the pre-commit validation?

The error doesn't come up when you run it locally because this particular validation is running only when triggered with -g.
That also might be the reason why we didn't encounter it so far.
The fix should be pretty simple and we can take a look at it together if you wish.
Also, please make sure to run `./Utils/git_pull_master_into_fork.sh` as your branch seems to be outdated.

2024-01-04 17:04 UTC, dsommerville-illumio commented
> The error doesn't come up when you run it locally because this particular validation is running only when triggered with -g. That also might be the reason why we didn't encounter it so far. The fix should be pretty simple and we can take a look at it together if you wish. Also, please make sure to run `./Utils/git_pull_master_into_fork.sh` as your branch seems to be outdated.

@YuvHayun - sounds good, can you please recommend a fix for the issue or point me to the relevant documentation?

2024-01-07 07:55 UTC, YuvHayun commented
@yashgaikwad-crest can you sign the from please?
Triggering tests at the mean time.

2024-01-07 08:49 UTC, melamedbn approved these changes

2024-01-07 10:26 UTC, YuvHayun commented
Tests passed, waiting for @yashgaikwad-crest to sign before merging to internal pr.

2024-01-08 18:51 UTC, dsommerville-illumio commented
@YuvHayun - @yashgaikwad-crest is no longer working on this pack, he made the initial change but may not be able to sign the agreement. Can you waive his signature on the CLA here?

2024-01-09 08:19 UTC, YuvHayun commented
Hey @dsommerville-illumio 
In that case we have 3 options:
- you can try and ask him to see if he might be able to do so.
- you can try [squash his commit](https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together)
- you can try re-open a new pr after closing this one and making sure you're up to date with master.

Let me know which you choose.

2024-01-10 07:21 UTC, YuvHayun commented
@dsommerville-illumio thx for your contribution!
merging to internal pr.

2024-01-10 07:22 UTC, YuvHayun approved these changes

2024-01-10 07:23 UTC, merged