Update argument computer_name of command sentinelone-list-agents
demisto/content pull request #31988
Opened 2024-01-05 15:04 UTC by chloerongier

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR updates the argument *computer_name* so the **sentinelone-list-agents** command  will now be able to match partial computer names value (substring) which was not possible before.

## Must have
- [ ] Tests
- [ ] Documentation

2024-01-07 10:26 UTC, kgal-pan commented
@munna-metron @parag-metron @saurabh-metron - Can you please review and approve these changes?

2024-01-08 05:17 UTC, munna-metron commented
> @munna-metron @parag-metron @saurabh-metron - Can you please review and approve these changes?

HI @kgal-pan , reviewed the changes and those are looking good. Thanks
cc: @parag-metron @saurabh-metron

2024-01-08 08:04 UTC, YuvHayun requested changes
Looks good, added 1 small comment.
Just to make sure **computerName__like** is as shown in the endpoint docs?
can you add a link to it please?
At the meantime, triggering instance test.

2024-01-08 08:04 UTC, YuvHayun commented on Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
> +    - description: The computer name by which to filter the results. It can match a partial computer name value (substring).
Make sure to edit the readme as well.

2024-01-08 08:48 UTC, YuvHayun commented
@chloerongier please also make sure you're up to date with master.

2024-01-08 09:51 UTC, chloerongier commented
> Looks good, added 1 small comment. Just to make sure **computerName__like** is as shown in the endpoint docs? can you add a link to it please? At the meantime, triggering instance test.

Here is the URI to the doc "/api-doc/api-details?category=agents&api=get-agents" and a screenshot with the query params :
![image](https://github.com/demisto/content/assets/150173582/39a774e2-6106-4f79-a9ea-d14a86b9f129)

2024-01-08 10:05 UTC, YuvHayun commented
> > Looks good, added 1 small comment. Just to make sure **computerName__like** is as shown in the endpoint docs? can you add a link to it please? At the meantime, triggering instance test.
> 
> Here is the URI to the doc "/api-doc/api-details?category=agents&api=get-agents" and a screenshot with the query params : ![image](https://private-user-images.githubusercontent.com/150173582/294862723-39a774e2-6106-4f79-a9ea-d14a86b9f129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDg0ODEsIm5iZiI6MTcwNDcwODE4MSwicGF0aCI6Ii8xNTAxNzM1ODIvMjk0ODYyNzIzLTM5YTc3NGUyLTYxMDYtNGY3OS1hOWVhLWQxNGE4NmI5ZjEyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxMDAzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzBkNjVjNWMxM2VhNjU5N2M5Y2RhMDYzMjE0NzU2NzgyM2M3MWI4YzZiZTc5NGM2YzczODUwY2VmZDZmNjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z3YCs6tT3fz8r1PmoUpry4070nGrZ_IEgf5Z_YmSZAQ)

Thx!
So please just pull from master.

2024-01-08 11:32 UTC, YuvHayun commented
Merging to internal PR.
Thx for your contribution @chloerongier

2024-01-08 11:32 UTC, merged