Additional command to get IOA Rules for custom IOA rule triggered detections.
demisto/content pull request #31992
Opened 2024-01-06 11:36 UTC by zeekforit

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
To be able to get IOA Rules for custom IOA rule triggered detections.

## Must have
- [ ] Tests 
- [ ] Documentation 

Honestly, I can't have this tested on our environment but this is the same way how we do this using another SOAR platform. Our team will be really thankful if this feature has been added. I don't care if I don't get any credits for this or if this code was used. we just need a command that can get IOA Rules. Thank you.

2024-01-06 11:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=31992) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=31992) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=31992) it.</sub>

2024-01-06 12:49 UTC, zeekforit reviewed
Fixed errors

2024-01-06 13:13 UTC, zeekforit reviewed
Fixed errors

2024-01-06 13:58 UTC, zeekforit reviewed
cleanup

2024-01-08 09:23 UTC, yucohen commented
Hi @zeekforit Thanks for your contribution! 
Let's set up a short session to test your changes together :) 
Please reach out here or on DFIR in slack in order to set the session

2024-01-08 12:11 UTC, zeekforit commented
Hi @yucohen,

Thank you for your response. Unfortunately, I haven't received the invite for DFIR in slack yet. Wanted to ask how we can proceed on testing?

2024-01-08 16:46 UTC, yucohen commented
@zeekforit I sent you an email, lets discuss it there :)

2024-01-10 14:49 UTC, yucohen requested changes
Great work! Please see my comments

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +                     'rulegroup_id', 'ruletype_id', 'ruletype_name', 'version_ids'],
```suggestion
        readable_output=tableToMarkdown(
            name='CrowdStrike IOA Rules',
            t=ioarules,
            headers=['instance_id', 'description', 
            'enabled', 'name', 'pattern_id'],
```

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +                     'rulegroup_id', 'ruletype_id', 'ruletype_name', 'version_ids'],
We can narrow down the table, all relevant data would be in the context

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
> +      name: rule_id
```suggestion
      name: rule_ids
```

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +        return mapping.get(header, header)
```suggestion
  
```

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +        return mapping.get(header, header)
we can use `headerTransform=string_to_table_header` instead

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +            headerTransform=table_headers_transformer,
```suggestion
            headerTransform=string_to_table_header,
```

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
> +            headerTransform=table_headers_transformer,
it does the same thing :)

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_11.md
> +The playbook uses the integration "CrowdStrike Falcon". (Available from Cortex XSOAR 6.10.0).
lets revert this change

2024-01-10 14:49 UTC, yucohen commented on Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_12.md
> +This command allows to retrieve rules for Custom IOA rules detections.
```suggestion
- Added the ***cs-falcon-ioarules*** command that allows to retrieve rules for Custom IOA rules detections.
```

2024-01-10 15:47 UTC, zeekforit commented
Hello @yucohen

All needed changes were made. Thank you so much for the extended help you've made to achieve this.

2024-01-10 15:59 UTC, zeekforit reviewed
All needed changes were made. Thank you so much for the extended help you've made to achieve this.

2024-01-10 16:00 UTC, zeekforit reviewed
.

2024-01-10 16:05 UTC, zeekforit reviewed
update docker image

2024-01-10 16:16 UTC, zeekforit reviewed
.

2024-01-11 07:42 UTC, yucohen approved these changes

2024-01-11 07:42 UTC, merged