JSON Feed - Remove ports from IPv4s Indicators
demisto/content pull request #32223
Opened 2024-01-15 14:23 UTC by Ni-Knight

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9208

## Description
Allows the user to:
1. Remove ports from IPv4s coming from the feed using a parameter (off by default)
2. The user can remove or leave the ports when using the integration command.

## Must have
- [ ] Tests
- [ ] Documentation

2024-01-22 16:59 UTC, AradCarmi requested changes
Great Job Dror!
See my notes, regarding the RN let's change the unaffected ones to general notes or just write `Maintenance and stability enhancements` or just add also the functionality to all of the integrations.

2024-01-23 14:39 UTC, Ni-Knight commented on Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
> +  display: Remove ports from IPv4 type indicators
Maybe `Remove IPv4 Ports`?

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/AccentureCTI_Feed/ReleaseNotes/1_1_35.md
> +- Added the option to remove ports from IPv4s in the JSONAPIModule.
```suggestion
Added the option to remove ports from IPv4 type indicators in the JSONAPIModule.
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/FeedAWS/ReleaseNotes/1_1_49.md
> +- Added the option to remove ports from IPv4s in the JSONAPIModule.
```suggestion
Added the option to remove ports from IPv4 type indicators in the JSONAPIModule.
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/FeedFastly/ReleaseNotes/1_1_27.md
> +- Added the option to remove ports from IPv4s in the JSONAPIModule.
```suggestion
Added the option to remove ports from IPv4 type indicators in the JSONAPIModule.
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/FeedGCPWhitelist/ReleaseNotes/2_0_38.md
> +- Added the option to remove ports from IPv4s in the JSONAPIModule.
```suggestion
Added the option to remove ports from IPv4 type indicators in the JSONAPIModule.
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/FeedIntel471/ReleaseNotes/2_1_3.md
> +- Added the option to remove ports from IPv4s.
```suggestion
Added the option to remove ports from IPv4 type indicators.

##### Intel471 Actors Feed (Deprecated)

Added the option to remove ports from IPv4 type indicators.
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
> +- additionalinfo: Remove ports from IPv4 type indicators in the fetch command (e.g. 192.168.1.1:8080 -> 192.168.1.1)
```suggestion
- additionalinfo: Remove ports from IPv4 type indicators in the fetch command (e.g. ,192.168.1.1:8080 -> 192.168.1.1)
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/FeedJSON/Integrations/FeedJSON/FeedJSON.yml
> +  additionalinfo: "When using a custom classifier and mapper with this feed, use this option to include the indicator type in the raw json used for classification and mapping."
```suggestion
  additionalinfo: "When using a custom classifier and mapper with this feed, use this option to include the indicator type in the raw JSON used for classification and mapping."
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/FeedMalwareBazaar/ReleaseNotes/1_0_38.md
> +- Added the option to remove ports from IPv4s in the JSONAPIModule.
```suggestion
Added the option to remove ports from IPv4 type indicators in the JSONAPIModule.
```

2024-02-01 12:58 UTC, ShirleyDenkberg commented on Packs/iDefense/ReleaseNotes/3_2_13.md
> +- Added the option to remove ports from IPv4s in the JSONAPIModule.
```suggestion
Added the option to remove ports from IPv4 type indicators in the JSONAPIModule.
```

2024-02-01 12:59 UTC, ShirleyDenkberg commented
@AradCarmi Doc review completed.

2024-02-06 13:16 UTC, AradCarmi approved these changes

2024-02-06 16:17 UTC, merged