DFIR IRIS Integration contribution
demisto/content pull request #32355
Opened 2024-01-22 17:49 UTC by Enigmatyk

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
New integration

## Description
IRIS is a collaborative platform aiming to help incident responders to share technical details during investigations

## Must have
- [ ] Tests
- [X] Documentation

2024-01-23 17:42 UTC, yucohen requested changes
Thanks for your contribution! Great job!
1. Please see my review comments.
2. make sure to fix all build steps.
3. Isn't mandatory, but adding a detailed description on how to get api tokens to `IRISDFIR_description.md` file would be really useful to the customer using this integration.

Dont hesitate to reach out if you have any questions here or on slack DFIR :)

2024-01-23 17:42 UTC, yucohen commented on Packs/IRISDFIR/Integrations/IRISDFIR/IRISDFIR.py
> +        outputs=results_str,
if it just retrieves an str no need for outputs in this case.

2024-01-24 13:28 UTC, Enigmatyk commented on Packs/IRISDFIR/Integrations/IRISDFIR/IRISDFIR.py
> +                return cases['message']
Removed.

2024-01-24 13:28 UTC, Enigmatyk commented on Packs/IRISDFIR/Integrations/IRISDFIR/IRISDFIR.py
> +                return cases['message']
Removed.

2024-01-24 13:28 UTC, Enigmatyk commented on Packs/IRISDFIR/Integrations/IRISDFIR/IRISDFIR.py
> +                return cases['message']
Removed.

2024-01-24 13:29 UTC, Enigmatyk commented on Packs/IRISDFIR/Integrations/IRISDFIR/IRISDFIR.py
> +                return cases['message']
Removed.

2024-01-24 14:17 UTC, Enigmatyk commented on Packs/IRISDFIR/Integrations/IRISDFIR/IRISDFIR.py
> +        outputs=results_str,
change the name to results to not create confusion.

2024-01-25 14:12 UTC, yucohen commented
@Enigmatyk Great! approving!
waiting for your confirmation before merging :)

2024-01-25 14:12 UTC, yucohen approved these changes

2024-01-29 17:48 UTC, yucohen approved these changes
Great!!

2024-01-29 17:49 UTC, merged