Read pdf hash feature
demisto/content pull request #32387
Opened 2024-01-23 15:16 UTC by anas-yousef

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32377

## Description
Added support for extracting hashes.

## Must have
- [ ] Tests
- [ ] Documentation

2024-01-23 15:32 UTC, anas-yousef commented
@JasBeilin We just need to decide how we want to update the documentation of the script.

2024-01-24 06:56 UTC, JasBeilin requested changes
Nice work, lets enhance a bit and merge :)

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> -    pass
Why removing it?

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> -    pass
?

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> -    pass
?

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> +def get_hashes_from_file(file_path: str) -> dict[str, set[Any]]:
Please add docstring

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> +        pdf = PyPDF2.PdfReader(pdf_file, strict=False)
Why opening again the pdffile? Why not run on the text extracted from it?

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> +    return hash_context
```suggestion
def convert_hash_to_context(hash_type: str, hashes: set[Any]) -> list[dict[str, Any]]:
    hash_context = [{'type': hash_type, 'value': hash} for hash in hashes]
    return hash_context
```

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> +            hash_contexts.extend(convert_hash_to_context(hash_type, hashes))
You can check it before the for loop and then have it a one liner, but its not critical.

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> +        hash_contexts = extract_hash_contexts_from_pdf_file(cpy_file_path)
Why running here and not on the text file like the URL and EMAIL? Lets keep the code clean and consistent.

2024-01-24 06:56 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/test_data/pdf-with-hashes.pdf
Lets make sure our example has both hashes and ip/url something else to make sure they are unaffected/ not detected as hash by mistake.

2024-01-24 09:27 UTC, anas-yousef commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> -    pass
Ruff

2024-01-24 09:28 UTC, anas-yousef commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> -    pass
[Ruff](https://docs.astral.sh/ruff/rules/unnecessary-placeholder/)

2024-01-24 09:28 UTC, anas-yousef commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> -    pass
[Ruff](https://docs.astral.sh/ruff/rules/unnecessary-placeholder/)

2024-01-24 15:13 UTC, JasBeilin approved these changes

2024-01-25 09:27 UTC, merged