move the exit and error
demisto/content pull request #32419
Opened 2024-01-25 08:28 UTC by MosheEichler

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-01-28 09:21 UTC, kobymeir requested changes

2024-01-28 09:21 UTC, kobymeir commented on .hooks/bootstrap
> +        exit_on_error $error_code "Failed to install Poetry version:${POETRY_VERSION}"
```suggestion
         if [ -n "${ARTIFACTS_FOLDER}" ]; then
        cp ${CI_PROJECT_DIR}/poetry-installer-error-*.log "${ARTIFACTS_FOLDER}"
        fi
        exit_on_error $error_code "Failed to install Poetry version:${POETRY_VERSION}"
```

2024-01-28 09:21 UTC, kobymeir commented on .hooks/bootstrap
> +        error_code = $?
```suggestion
        error_code=$?
```
no spaces in bash assignment

2024-01-28 11:59 UTC, kobymeir requested changes

2024-01-28 11:59 UTC, kobymeir commented on .hooks/bootstrap
> +            cp "${CI_PROJECT_DIR}/poetry-installer-error-*.log" "${ARTIFACTS_FOLDER}"
```suggestion
            cp ${CI_PROJECT_DIR}/poetry-installer-error-*.log "${ARTIFACTS_FOLDER}"
```

2024-01-28 12:37 UTC, kobymeir approved these changes

2024-01-29 09:11 UTC, MosheEichler commented
[Triggered](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/790654) SDK nightly

2024-02-01 13:44 UTC, merged