Contributing to Cortex XSOAR Content
demisto/content pull request #32437
Opened 2024-01-25 18:33 UTC by dmelgar-ssc

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: - Added fixes requested in this PR https://github.com/demisto/content/pull/32230

## Description
The update includes three new playbooks and a few new commands to power them. This new content is able to interact with SecurityScorecard's Event Log, pulling in event data and then fetching detailed information for particularly relevant events. Furthermore it is able to bring in metadata for issues such as description and resolution information.

2024-01-25 18:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=32437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=32437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=32437) it.</sub>

2024-01-25 18:55 UTC, kgal-pan commented
@dmelgar-ssc - Is there a reason we need to open this PR to merge into https://github.com/demisto/content/pull/32230 or can we continue working on that PR? You should be able to run:

```bash
gh pr checkout 32230
```

To pull the work into your local environment.

2024-01-25 19:05 UTC, dmelgar-ssc commented
The previous pull request (32230) is based on a fork created by a contributor who is no longer working in Security Scorecard and the fork was created using his account.
That's why I've created a new one with a new fork using my account, the idea is to apply the requested changes on the original PR from this pull request having all track of it.
Also, I'm taking this work from an internal ticket in Security Scorecard that we tracking these changes.
After merging the Pull Requests, I will register myself as a contributor and create my pull requests directly.

2024-01-28 08:10 UTC, YuvHayun requested changes
Hey @dmelgar-ssc, thx for your contribution!
Looks good in general, please see my notes.
Also, please make sure to add tests for the commands you've added.

2024-01-28 08:10 UTC, YuvHayun commented on Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
> +- display: Portfolio ID
I don't seem to find this param in the code, where are you using it?

2024-01-28 08:10 UTC, YuvHayun commented on Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
> +    - name: domain
Let's add description.

2024-01-28 08:10 UTC, YuvHayun commented on Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
> +    - name: date_to
same here.

2024-01-28 08:10 UTC, YuvHayun commented on Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
> +    - contextPath: SecurityScorecard.Events.Event.ssc_event_id
Make sure to add a description field for all outputs, arguments & commands.

2024-01-28 08:10 UTC, YuvHayun commented on Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
> +  - name: securityscorecard-company-findings-get
No outputs for this command?

2024-01-28 08:10 UTC, YuvHayun commented
@melamedbn @MLainer1 ready for your review.

2024-01-28 13:24 UTC, melamedbn commented
Hi @dmelgar-ssc,

I've taken some time to review the SecurityScorecard playbooks and have a few suggestions that could enhance their functionality and clarity:

### SecurityScorecard Event
- **Playbook Description**: It's important to add a description for clarity and understanding of the playbook's purpose.
- **Naming**: Could we find a more descriptive term than 'event' that better encapsulates the playbook's functionality?
- **Playbook Inputs**: Please provide descriptions and default values for the playbook's inputs for better user guidance.
- **Task Clarification (Tasks 2, 4, 6)**: These tasks reference playbook inputs that don't seem to exist. Could you please recheck and rectify this?
- **Playbook Purpose**: The current playbook appears to create an incident from incident info, potentially leading to duplicated incidents. This process might be more efficiently handled with a classifier. Could you elaborate on the playbook's intended use?

### SecurityScorecard Events
- **Playbook Description**: It's important to add a description for clarity and understanding of the playbook's purpose.
- **Naming**: Could we find a more descriptive term than 'event' that better encapsulates the playbook's functionality?
- **Hardcoded Values in Inputs**: Are there reasons for the hardcoded values in the playbook inputs? It's generally advisable to use adjustable inputs.
- **Playbook Outputs**: Have you considered whether this playbook requires outputs?

### SecurityScorecard Sync
- **Playbook Description**: It's important to add a description for clarity and understanding of the playbook's purpose.
- **Naming**: Could we find a more descriptive term than 'event' that better encapsulates the playbook's functionality?
- **Task 5 - 'portfolio_id' Input**: This task is missing the mandatory input 'portfolio_id'. Please include it.
- **Avoiding Hardcoded Values**: Adjustable playbook inputs are recommended over hardcoded values for flexibility and wider applicability.

### General Note
- **Combining Playbooks**: It seems feasible and efficient to combine all three playbooks into one, given their overlapping functionality and scope.

Looking forward to your thoughts on these suggestions.

Best regards,

Ben

2024-02-07 13:45 UTC, dmelgar-ssc commented
> Hey @dmelgar-ssc how is it going? Let me know if you need help with my comments / @melamedbn comments.

Hey @melamedbn, I had an issue trying to complete the contributor form (getting the required ID from slack) I received the invite but it was canceled immediately. 
I am working with our Product Manager to get the information required to complete the release notes and the information requested on descriptions fields and others.

2024-02-13 08:51 UTC, YuvHayun commented
Alright, let me know if you need any help from my side @dmelgar-ssc

2024-02-26 12:02 UTC, YuvHayun commented
Closing the pr for now.
Feel free to reopen when you get to address the comments.

2024-02-26 12:02 UTC, closed without merging