YR/Handle-long-running-pipelines/CIAC-9386
demisto/content pull request #32462
Opened 2024-01-29 10:47 UTC by RosenbergYehuda

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-02-04 13:00 UTC, kobymeir requested changes

2024-02-10 21:37 UTC, RosenbergYehuda commented on Tests/scripts/common.py
> +        previous_commit = list_of_commits[index]
fixed

2024-02-10 22:33 UTC, RosenbergYehuda commented on Tests/scripts/common.py
> +    elif direction == "older":
fixed

2024-02-12 09:54 UTC, kobymeir requested changes

2024-02-12 09:54 UTC, kobymeir commented on Tests/scripts/infrastructure_tests/common_test.py
> +def test_was_message_already_sent__was_sent_for_true_pivot(mocker, commits=COMMITS, pipelines=PIPLINES):
why UT have a default value? bad practice.

2024-02-12 09:54 UTC, kobymeir commented on Tests/scripts/infrastructure_tests/common_test.py
> +def test_was_message_already_sent__was_sent_for_false_pivot(mocker, commits=COMMITS, pipelines=PIPLINES):
same

2024-02-12 10:02 UTC, RosenbergYehuda commented on Tests/scripts/infrastructure_tests/common_test.py
> +def test_was_message_already_sent__was_sent_for_true_pivot(mocker, commits=COMMITS, pipelines=PIPLINES):
Sorry, fixed

2024-02-15 11:31 UTC, kobymeir approved these changes

2024-02-15 12:07 UTC, merged