[CommonScripts] (ProvidesCommand): Fix dict key when comparing command with enable instances
demisto/content pull request #32552
Opened 2024-01-31 14:08 UTC by pl-brault

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
When comparing the instance name with the enabled instance the check was made on the "display" key which wasn't the same as the "brand" key retrieved before.

Example:
Here is the display:
![image](https://github.com/demisto/content/assets/143391737/41dbb735-afad-40ee-a3b3-a7c64a0d21b3)

Here is the brand:
![image](https://github.com/demisto/content/assets/143391737/5ec57e89-1d7e-4da0-9412-1a86875ce65e)

## Must have
- [ ] Tests
- [ ] Documentation

2024-02-01 06:34 UTC, YuvHayun commented
Hi @pl-brault, thx for your contribution.
I'm not sure I fully understand the issue, can you try to elaborate a bit about the problem?

2024-02-01 08:23 UTC, pl-brault commented
> Hi @pl-brault, thx for your contribution. I'm not sure I fully understand the issue, can you try to elaborate a bit about the problem?

Hello, 

This Script find all available integration instance for a specific command passed in argument.
To find which integration that implement the command, the script  run two API requests:
- one that list all integration with their commands (line 18,19)
- one that list all available integration (line 28)

Line 41 the script construct a dict based on the the "brand" for all integration enabled.
Then when iterating (line 56-64) on all all commands for all integrations, if we want only enabled instance, the script search for the "display name" of the integration in the dict constructed line 41, therefore if the brand and the display name of an integration isn't the same the "integration" isn't return even if it has the command implemented and is enable.

For example:
For the integration EclecticIQ  the brand is `EclecticIQ Platform` and the display name is `EclecticIQ Platform (Deprecated) (Partner Contribution)`
therefore if we search for `EclecticIQ Platform (Deprecated) (Partner Contribution)` in the dict that has the key `EclecticIQ Platform` it's never return

```python
integration_instances_enabled = {
    "EclecticIQ Platform": True
}

# This line is never true because we compare the display name which isn't in integration_instances_enabled 
"EclecticIQ Platform (Deprecated) (Partner Contribution)" in integration_instances_enabled
```

2024-02-01 09:21 UTC, YuvHayun commented
> > Hi @pl-brault, thx for your contribution. I'm not sure I fully understand the issue, can you try to elaborate a bit about the problem?
> 
> Hello,
> 
> This Script find all available integration instance for a specific command passed in argument. To find which integration that implement the command, the script run two API requests:
> 
> * one that list all integration with their commands (line 18,19)
> * one that list all available integration (line 28)
> 
> Line 41 the script construct a dict based on the the "brand" for all integration enabled. Then when iterating (line 56-64) on all all commands for all integrations, if we want only enabled instance, the script search for the "display name" of the integration in the dict constructed line 41, therefore if the brand and the display name of an integration isn't the same the "integration" isn't return even if it has the command implemented and is enable.
> 
> For example: For the integration EclecticIQ the brand is `EclecticIQ Platform` and the display name is `EclecticIQ Platform (Deprecated) (Partner Contribution)` therefore if we search for `EclecticIQ Platform (Deprecated) (Partner Contribution)` in the dict that has the key `EclecticIQ Platform` it's never return
> 
> ```python
> integration_instances_enabled = {
>     "EclecticIQ Platform": True
> }
> 
> # This line is never true because we compare the display name which isn't in integration_instances_enabled 
> "EclecticIQ Platform (Deprecated) (Partner Contribution)" in integration_instances_enabled
> ```

Thx a lot for the clarification.
Now I fully understand the issue, I'll review it quickly.

2024-02-01 09:23 UTC, YuvHayun requested changes
Nice catch, please add tests and note my comment and pre-commit failures.

2024-02-01 09:23 UTC, YuvHayun commented on Packs/CommonScripts/ReleaseNotes/1_13_32.md
> +- Fixed an issue where the comparison key wasn't the same when checking that a command is part of enabled instances.
```suggestion
- Fixed an issue where the script would miss enabled commands due to a mismatch between comparison key when checking that a command is part of enabled instances.
```

2024-02-01 14:27 UTC, YuvHayun commented
Moving to instance test.

2024-02-02 08:59 UTC, YuvHayun commented
Merging to intenrnal PR, thx a lot for your contribution.

2024-02-02 08:59 UTC, merged