Fixing Mandiant ASM Issue Status Sync
demisto/content pull request #32767
Opened 2024-02-06 15:50 UTC by chrishultin

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Fixes an issue where ASM issue status was not synced to Cortex XSOAR.

## Must have
- [ ] Tests
- [ ] Documentation

2024-02-07 07:35 UTC, YuvHayun requested changes
Looks good!
I left one small comment regarding the release notes.
Please attach a short demo video with the following sequence:
- An incident being fetched (show the incident in the incidents tab and the incident status)
- Closing that incident in Mandiant Advantage ASM UI.
- Show that the fetched incident in xsoar is closed: both the status in the context and the closed updated in the incident page.

2024-02-07 07:35 UTC, YuvHayun commented on Packs/MandiantAdvantageAttackSurfaceManagement/ReleaseNotes/1_0_5.md
> +- Fixing issue where closing an incident in Mandiant Advantage ASM did not close the corresponding incident in Cortex XSOAR.
```suggestion
- Fixed an issue where closing an incident in Mandiant Advantage ASM did not close the corresponding incident in Cortex XSOAR.
```

2024-02-13 08:45 UTC, YuvHayun commented
Hey @chrishultin how is it going?
Let me know if you need any help with the changes.

2024-02-13 16:22 UTC, chrishultin commented
> Hey @chrishultin how is it going? Let me know if you need any help with the changes.

Sorry for the delay.  I've tweaked the release notes as per your request, and sent you a video via Slack of the system working.

2024-02-14 08:44 UTC, YuvHayun commented
Merging to internal pr.
Thx for the fix!

2024-02-14 08:44 UTC, YuvHayun approved these changes

2024-02-14 08:44 UTC, merged