AWS Cloud Watch logs - fix proxy issue
demisto/content pull request #32956
Opened 2024-02-15 17:23 UTC by Enigmatyk

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Fixed an issue where the proxy setting was not present.

## Description
Fixed an issue where the proxy setting was not present.

## Must have
- [ ] Tests
- [ ] Documentation

2024-02-18 11:32 UTC, merit-maita requested changes
thank you for your contribution!
it looks good, please see my comments.

2024-02-18 11:32 UTC, merit-maita commented on Packs/AWS-CloudWatchLogs/Integrations/AWS-CloudWatchLogs/AWS-CloudWatchLogs.yml
> +  required: false
it's a needed field
```suggestion
  required: false
  section: Connect
```

2024-02-18 11:32 UTC, merit-maita commented on Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_19.md
> +- Fixed an issue where the proxy setting was not present.
```suggestion
- Added the *Use system proxy settings* parameter. 
- Updated the Docker image to *demisto/boto3py3:1.0.0.87887*.
```

2024-02-19 12:05 UTC, Enigmatyk commented on Packs/AWS-CloudWatchLogs/Integrations/AWS-CloudWatchLogs/AWS-CloudWatchLogs.yml
> +  required: false
Done.

2024-02-19 12:05 UTC, Enigmatyk commented on Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_19.md
> +- Fixed an issue where the proxy setting was not present.
Done.

2024-02-19 14:01 UTC, merit-maita requested changes
as seen in the pr checks, there's a conflict
a new version of the pack was released very recently, with the same version as yours, so please change your version to be 1_2_20.md and in pack_metadata file as well.
thank you!

2024-02-20 08:51 UTC, merit-maita approved these changes

2024-02-20 09:51 UTC, merged