Spur context api
demisto/content pull request #33110
Opened 2024-02-26 15:51 UTC by jjunqueira

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-02-26 15:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=33110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=33110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=33110) it.</sub>

2024-03-04 20:10 UTC, jbabazadeh requested changes
Hi @jjunqueira 
Thank you for your contribution!
Good work :)
Please see my comments

Please feel free to reach out to me with any questions - I'm available here or on slack :)

2024-03-04 20:10 UTC, jbabazadeh commented on Packs/SpurContextAPI/Integrations/SpurContextAPI/SpurContextAPI.py
> +        return_error(f'Error: {stacktrace}')
```suggestion
        return_error(f'Error: {traceback.format_exc()}')
```

2024-03-04 20:10 UTC, jbabazadeh commented on Packs/SpurContextAPI/.secrets-ignore
> +192.168.1.1
why to use this in the tests? and not 1.1.1.1 instead?

2024-03-06 20:09 UTC, ShirleyDenkberg commented
I am on PTO through March 14. If this cannot wait, please contact @Richard
Bluestone ***@***.***> .

On Wed, Mar 6, 2024, 4:55 AM JudithB ***@***.***> wrote:

> @jbabazadeh
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jbabazadeh&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=l1TMalb3xP1UY_aONoWgkkOLLPWa8OaHTvodf5Gtmg8&m=-Dy4elfCDuBEXk1oUYZTBxXJJ7tweam18f8lnu8E8yVmZTulzYE6NQRex12x3s3P&s=P088OfCnPcXBbdiYiTFI75Ns9UpjMu5hS742s4CgOew&e=>
> requested your review on: #33110
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_33110&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=l1TMalb3xP1UY_aONoWgkkOLLPWa8OaHTvodf5Gtmg8&m=-Dy4elfCDuBEXk1oUYZTBxXJJ7tweam18f8lnu8E8yVmZTulzYE6NQRex12x3s3P&s=QLVZKgPi-steHt6xf-0mT9Jpf1fayuuHqkFFkAhLrb4&e=>
> Spur context api.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_33110-23event-2D12025364897&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=l1TMalb3xP1UY_aONoWgkkOLLPWa8OaHTvodf5Gtmg8&m=-Dy4elfCDuBEXk1oUYZTBxXJJ7tweam18f8lnu8E8yVmZTulzYE6NQRex12x3s3P&s=pRy2DuJ9H5bpWljyJef3KbzcRjyzdabQKoBAbuSil1g&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AO44YEV2I7IC6HGG553UPRLYW3RXJAVCNFSM6AAAAABD2OOZWOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGAZDKMZWGQ4DSNY&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=l1TMalb3xP1UY_aONoWgkkOLLPWa8OaHTvodf5Gtmg8&m=-Dy4elfCDuBEXk1oUYZTBxXJJ7tweam18f8lnu8E8yVmZTulzYE6NQRex12x3s3P&s=Ju3gomP7muwqujzoL-cLeVlhH5_e9wu62SsRcJQiIv8&e=>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-03-07 07:06 UTC, jbabazadeh approved these changes

2024-03-10 09:50 UTC, jbabazadeh approved these changes

2024-03-10 11:59 UTC, merged

2024-03-11 10:13 UTC, jbabazadeh commented
Hi @jjunqueira ,
I merged the internal PR, and your update is now in the master branch of content repo.
Your update should be available in the marketplace within the next 72 hours.
Again, thank you very much for your contribution!