Redmine integration
demisto/content pull request #33139
Opened 2024-02-29 09:08 UTC by tcarmeli1

## Status
- [x] In Progress

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9331

## Description
New Redmine integration

2024-03-06 13:16 UTC, jbabazadeh reviewed
Great work!
I just have a few comments..

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +def map_predefined_values_to_id(predefined_value, converter_dict, error_message):
you can remove it as we talk in the call

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +    tracker_id = args.pop('tracker_id', None)
need to be change as we talk.

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +    file_path = get_file_path_res.pop('path')
```suggestion
    file_path = get_file_path_res.get('path')
```

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +            uploads = assign_params(token=token_response['upload'].get('token', ''),
move the token_response to the if and check if the token exists.

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +            message = 'Authorization Error: make sure API Key is correctly set'
add the error message (e) to the message

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +                raise DemistoException("Invalid status ID, please use only predefined values")
```suggestion
        status_id = ISSUE_STATUS_DICT.get(args.get('status_id', None))       
```

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +        custom_fields = custom_fields.split(',')
use ArgToList function 
Please go over other places and replace the split with this function if needed

2024-03-06 13:16 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +        args['watcher_user_ids'] = argToList(watcher_user_ids)
remove this lines and add  change line 195 with argToList

2024-03-10 12:59 UTC, BEAdi requested changes
Great work!

Please make sure to:
1. Fix the build failures.
2. Run `demisto-sdk format`.
3. Ask for docs review, also for the error messages.

2024-03-13 08:52 UTC, jbabazadeh reviewed
few more comments..

2024-03-13 08:52 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +        raise DemistoException('project_id field is missing in order to create an issue')
```suggestion
   project_id =  args.get('project_id', client._project_id) 
   if not project_id:
        raise DemistoException('project_id field is missing in order to create an issue')
```

2024-03-13 08:52 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +    project_id = args.pop('project_id', client._project_id)
remove

2024-03-13 08:52 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +        watcher_user_ids = argToList(watcher_user_ids)
```suggestion
    watcher_user_ids = argToList(args.get('watcher_user_ids', None))
```

```

2024-03-13 08:52 UTC, jbabazadeh commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +    handle_file_attachment(client, args)
check if entry_id

2024-03-13 18:29 UTC, BEAdi reviewed
Great job👏

2024-03-13 18:29 UTC, BEAdi commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +        custom_field['is_filter'] = str(custom_field['is_filter'])
It is because the `is_auto_json_transform=True`, lets open a dev-bug ticket to fix this 😊

2024-03-13 18:29 UTC, BEAdi commented on Packs/Redmine/Integrations/Redmine/Redmine.py
> +            raise DemistoException("Invalid status value- please use the predefined options only.")
You decision, but why won't you first check if it is in the dict and not wait for an exception to be raised? If we have a way to check it ourselves it is better IMO.
```suggestion
    if status_string not in USER_STATUS_DICT:
                raise DemistoException("Invalid status value- please use the predefined options only.")
    args['status'] = USER_STATUS_DICT[status_string]
```

2024-03-17 18:16 UTC, ShirleyDenkberg commented on Packs/Redmine/Integrations/Redmine/Redmine.yml
> +      description: Display a list of users mails.
```suggestion
      description: A list of users.
    - contextPath: Redmine.Users.id
      description: A list of users IDs.
    - contextPath: Redmine.Users.login
      description: A list of users login usernames.
    - contextPath: Redmine.Users.admin
      description: A list of users admins permission.
    - contextPath: Redmine.Users.firstname
      description: A list of users first name.
    - contextPath: Redmine.Users.lastname
      description: A list of users last name.
    - contextPath: Redmine.Users.mail
      description: A list of users mails.
```

2024-03-17 18:16 UTC, ShirleyDenkberg commented on Packs/Redmine/Integrations/Redmine/Redmine_description.md
> +4. Click on "API access key" and select "Show" to reveal your API key.
```suggestion
4. Click **API access key** and select **Show** to reveal your API key.
```

2024-03-17 18:16 UTC, ShirleyDenkberg commented on Packs/Redmine/Integrations/Redmine/Redmine_description.md
> +3. If you would like to display data related only to a project with id x- Fill it in the Redmine integration authentication window.
```suggestion
- Your API key determines your role in Redmine. 
- If you have insufficient permissions when using commands such as "update" or "create," certain fields may remain unchanged due to insufficient privileges. In such cases, while the command itself will not fail, those particular fields will not be updated.
- If you would like to display data related only to a project with ID x-. Fill it in the Redmine integration authentication window.
```

2024-03-17 18:18 UTC, ShirleyDenkberg commented
@jbabazadeh @BEAdi Doc review completed.
@tcarmeli1 Need content in the pack README.

2024-03-21 10:04 UTC, jbabazadeh approved these changes

2024-03-21 11:31 UTC, BEAdi approved these changes

2024-03-21 12:29 UTC, merged