Qualys VMDR unify
demisto/content pull request #33240
Opened 2024-03-06 08:12 UTC by moishce

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8834)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-03-13 12:53 UTC, dantavori requested changes

2024-03-13 12:53 UTC, dantavori commented on Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
> +    name: qualys-get-events
what about `qualys-get-assets`?

2024-03-13 12:53 UTC, dantavori commented on Packs/qualys/ReleaseNotes/3_0_0.md
> +  - ***fetch-assets*** command to fetch assets and vulnerabilities.
```suggestion
##### Qualys VMDR (formerly QualysV2)
- Updated the Docker image to: *demisto/python3:3.10.13.87159*.
- Renamed the integration from ***Qualys v2*** to ***Qualys VMDR***.
- Added the  following commands:
  - ***fetch-events***
  - ***fetch-assets*** 
  - ***qualys-get-events***
  - ***qualys-get-assets*** 
```
also not sure if validate will like the ` (formerly QualysV2)`, if not - remove

2024-03-27 15:56 UTC, dantavori approved these changes

2024-04-05 13:10 UTC, moishce commented
@ShahafBenYakir, this PR needs force-merge because we deleted files.

2024-04-07 06:35 UTC, ShahafBenYakir commented
@moishce I see other failures here, please fix them asap and ping me so we can merge this

2024-04-07 08:33 UTC, ShahafBenYakir approved these changes

2024-04-07 08:34 UTC, merged