ReadPDFFileV2 unescaping
demisto/content pull request #33258
Opened 2024-03-07 12:24 UTC by anas-yousef

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32895

## Description
Added handling of html encoded URLs, by using **html.unescape**

## Must have
- [ ] Tests
- [ ] Documentation

2024-03-21 10:47 UTC, JasBeilin requested changes
I got some minor corrections but overall looks good.

2024-03-21 10:47 UTC, JasBeilin commented on Packs/CommonScripts/ReleaseNotes/1_14_20.json
> +    "breakingChangesNotes": "The script ReadPDFFileV2 now uses the argument *unescape*, with a default value of *True*. This update will change the default behavior of the script. System playbooks su
```suggestion
    "breakingChangesNotes": "The ***ReadPDFFileV2*** script now unescapes special character when extracting URLs by default. This update will affect the behavior of the script and of playbooks using it such as *Extract Indicators From File - Generic v2*, or any custom playbooks using it. In order to disable this behavior, set the *unescape* argument to `false`."
```

2024-03-21 10:47 UTC, JasBeilin commented on Packs/CommonScripts/ReleaseNotes/1_14_20.md
> +- Added the argument **unescape**. When set to *true*, the script will unescape the URLs that have been escaped (Ignoring them). Default is 'True'.
```suggestion
- Added the argument **unescape**. When set, the script will unescape the URLs that have been escaped (by ignoring them). Default is 'true'. 
```

2024-03-21 10:47 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> +                    html_content += line
```suggestion
                html_content += html.unescape(line) if unescape else line
```

2024-03-21 10:47 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
> +                          unescape: bool = True) -> None:
I think I would change the parameter name to unescape_url, WDYT?

2024-03-21 10:47 UTC, JasBeilin commented on Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
> +  name: unescape
I think I would change the parameter name to unescape_url, WDYT?

2024-03-25 09:20 UTC, yuvalbenshalom approved these changes

2024-03-25 09:46 UTC, JasBeilin approved these changes
Nice

2024-03-25 09:47 UTC, merged