[ServiceNow v2] Add the add_as_entry arg to get-ticket-notes command
demisto/content pull request #33319
Opened 2024-03-12 12:24 UTC by mmhw

## Status
- [x] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-34490)

## Description
Added the *add_as_entry* argument to the *servicenow-get-ticket-notes* command to optionally add the notes and work_notes as an entry to the War Room.

## Must have
- [ ] Tests
- [ ] Documentation

2024-03-12 13:32 UTC, DeanArbel approved these changes
Looks great, good job. As part of the documentation effort, don't forget to add it to the readme.

2024-03-13 07:26 UTC, julieschwartz18 requested changes
Doc review complete. Note that I only reviewed the updates

2024-03-13 07:26 UTC, julieschwartz18 commented on Packs/ServiceNow/ReleaseNotes/2_5_58.md
> +- Added the *add_as_entry* argument to the *servicenow-get-ticket-notes* command to optionally add the notes and work_notes as an entry to the War Room.
Recommend:
Added the *add_as_entry* argument to the ***servicenow-get-ticket-notes*** command to optionally add ticket notes and work notes as notes in the War Room.

2024-03-13 07:26 UTC, julieschwartz18 commented on Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
> +      description: Whether to add the ticket notes and work notes as an entry note in the War Room.
Recommend:
Whether to add ticket notes and work notes as notes in the War Room.

2024-03-13 07:26 UTC, julieschwartz18 commented on Packs/ServiceNow/Integrations/ServiceNowv2/README.md
> +| limit | Maximum number of ticket notes. Default is 10. Default is 10. | Optional |
Recommend: remove the extra "Default is 10."

2024-03-13 07:26 UTC, julieschwartz18 commented on Packs/ServiceNow/Integrations/ServiceNowv2/README.md
> +| ticket_type | The type of the ticket for which notes should be retrieved when using the `use_display_value` option. Possible values are: incident, problem, change_request, sc_request, sc_task, sc_r
Recommend:
The ticket type that notes should be retrieved for when using the `use_display_value` option. Possible values are: incident, problem, change_request, sc_request, sc_task, sc_req_item, sn_si_incident. Default is incident.

2024-03-13 07:26 UTC, julieschwartz18 commented on Packs/ServiceNow/Integrations/ServiceNowv2/README.md
> +| add_as_entry | Whether to add the ticket notes and work notes as an entry note in the War Room. Possible values are: true, false. | Optional |
Recommend:
Whether to add ticket notes and work notes as notes in the War Room. Possible values are true, false.

2024-03-13 07:26 UTC, julieschwartz18 commented on Packs/ServiceNow/Integrations/ServiceNowv2/README.md
> +Gets notes from the specified ServiceNow ticket. Notes can be retrieved either by granting "Read permissions" for the sys_journal_field table, or by setting the `use_display_value` parameter to true.
Recommend:
Gets notes from the specified ServiceNow ticket. Notes can be retrieved either by granting Read permissions for the sys_journal_field table, or by setting the `use_display_value` parameter to true.

2024-03-14 08:04 UTC, merged