[Microsoft Graph Security] update docs
demisto/content pull request #33325
Opened 2024-03-12 14:45 UTC by michal-dagan

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Documentation and metadata improvements.

## Must have
- [ ] Tests
- [ ] Documentation

2024-03-13 15:19 UTC, julieschwartz18 requested changes
Doc review complete. Note: I only reviewed the updates

2024-03-13 15:19 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml
> +    description: Get a list of the edicovery cases.
Recommend:
Get a list of the eDiscovery cases.

2024-03-13 15:19 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_description.md
> +To use the **Cortex XSOAR application** and allow Cortex XSOAR access to Microsoft Graph Security an administrator has to approve our app using an admin consent flow by clicking this **[link](https:/
Recommend:
To allow Cortex XSOAR access to Microsoft Graph Security, an administrator has to approve the Cortex XSOAR app using an admin consent flow by clicking this [link](https://oproxy.demisto.ninja/ms-graph-security).

2024-03-13 15:19 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_description.md
> +1. The *eDiscovery* and *Threat Assessment* commands are only supported when using the `Authorization Code flow` with `Delegated (work or school account)` permission type.
Recommend:
The ***eDiscovery*** and ***Threat Assessment*** commands are only supported when using the `Authorization Code flow` with `Delegated (work or school account)` permission type.

2024-03-13 15:19 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_description.md
> +2. When using `Authorization Code flow`, the connection should be tested using the `!msg-auth-test` command.
Recommend:
 When using `Authorization Code flow`, the connection should be tested using the ***!msg-auth-test*** command.

2024-03-13 15:19 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
> +**EDiscovery**:
Recommend:
**eDiscovery**

2024-03-13 15:19 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
> +Generate the login URL used for authorization code flow.
Recommend:
Generate the login URL used for the authorization code flow.

2024-03-13 15:19 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/README.md
> +and paste it in your instance configuration under the **Authorization code** parameter.
Recommend:
and paste it in the *Authorization code* parameter under your integration instance settings.

2024-03-13 15:21 UTC, julieschwartz18 commented on Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_12.md
> +Documentation and metadata improvements.
Is this enough detail? Do you need to mention anything about improved descriptions for eDiscovery and Threat Assessment commands?

2024-03-14 08:59 UTC, bziser approved these changes

2024-03-14 15:05 UTC, merged