Palo alto networks ai ops
demisto/content pull request #33358
Opened 2024-03-14 10:26 UTC by tcarmeli1

## Status
- [x] In Progress

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9040)

## Description
bpa polling integration

## Must have
- [ ] Tests
- [ ] Documentation

2024-03-24 10:32 UTC, jbabazadeh requested changes
Great job!!
a few comments.

2024-03-24 10:32 UTC, jbabazadeh commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.py
> +            raise DemistoException("The downloaded config file could not be converted.")
```suggestion
            raise DemistoException("The downloaded config file from Panorama/Pan-os could not be converted.")
```

2024-03-24 10:32 UTC, jbabazadeh commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.py
> +            result.append(root.find(tag).text)  # type: ignore
what if `root.find(tag)` return `None`?

2024-03-24 10:32 UTC, jbabazadeh commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.py
> +        if sub_tags is not None:
```suggestion
        if sub_tags:
```

2024-03-24 10:32 UTC, jbabazadeh commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.py
> +        raise DemistoException("Request Succeeded, A parse error occurred.")
please change the error message to be more informative

2024-03-24 15:01 UTC, tcarmeli1 commented on Packs/BPA/pack_metadata.json
> +    "name": "Best Practice Assessment (BPA) by Palo Alto Networks (Deprecated)",
DID IT HERE: https://github.com/demisto/content/pull/33520

2024-04-01 15:22 UTC, BEAdi reviewed
Great job!!
Some minor comments

2024-04-02 14:52 UTC, tcarmeli1 commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.py
> +                                 full_url=f'https://api.stratacloud.paloaltonetworks.com/aiops/bpa/v1/reports/{report_id}',
Yes. talked in zoom :)

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +        - Entry_id from xsoar war-room after uploading a file - should be a config file in xml format.
```suggestion
        - Entry_id from Cortex XSOAR War Room after uploading a file - should be a config file in xml format.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      description: Export the generated report as a file.
```suggestion
      description: Whether to export the generated report as a file.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      description: Show the report data inside the context.
```suggestion
      description: Whether to show the report data inside the context.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      - Get configuration file of Pan-OS/Panorama, if the user provides an entry_id to a config file this steps is skipped.
```suggestion
      - Get configuration file of Pan-OS/Panorama. If the user provided an entry_id to a config file this step is skipped.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      - Use the two above in order to generate a bpa report.
```suggestion
      - Use the information retrieved above to generate a BPA report.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      - During this process the API generates also a report_id for internal use.
```suggestion
      - During this process the API also generates a report_id for internal use.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      description: Show the report data inside the context.
```suggestion
      description: Whether to export the generated report as a file.
      defaultValue: true
    - name: show_in_context
      description: Whether to show the report data inside the context.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      description: Does this polling round is the first round.
```suggestion
      description: Whether this polling round is the first round.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps_description.md
> +- This Integration enables you to programmatically generate BPA data for both the free and premium instances of AIOps for NGFW.
```suggestion
- This integration enables you to programmatically generate BPA data for both the free and premium instances of AIOps for NGFW.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps_description.md
> +- Use your server url, username and password in order to get your API-key.
```suggestion
- Use your server URL, username and password in order to get your API-key.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps_description.md
> +- Optional: revoke all currently valid API keys, follow this [link](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-panorama-api/get-started-with-the-pan-os-xml-api/get-your-api-key)
```suggestion
- Optional: To revoke all currently valid API keys, follow this [link](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-panorama-api/get-started-with-the-pan-os-xml-api/get-your-api-key)
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/README.md
> +This integration was integrated and tested with version from March 2024 of PaloAltoNetworksAIOps.
```suggestion
This integration was integrated and tested with the March 2024 version of PaloAltoNetworksAIOps.
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/README.md
> +| entry_id | Entry_id from xsoar war-room after uploading a file. | Optional |
```suggestion
| entry_id | Entry_id from Cortex XSOAR War Room after uploading a file. | Optional | 
```

2024-04-02 15:45 UTC, ShirleyDenkberg commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/README.md
> +
I think this README has to be regenerated as it is missing much information from the yml file.

2024-04-02 15:46 UTC, ShirleyDenkberg commented
@BEAdi @jbabazadeh Doc review completed.
@tcarmeli1 Please regenerate the integration readme.

2024-04-07 07:07 UTC, jbabazadeh approved these changes
Amazing!

2024-04-07 12:37 UTC, tcarmeli1 commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps_description.md
> +            gJlQWE56987nBxIqyfa62sZeRtYuIo2BgzEA9UOnlZBhU==
What do you mean here?
changed the value to api-key 
thats what you mean?

2024-04-07 13:00 UTC, tcarmeli1 commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      description: Whether to show the report data inside the context.
it does this automatically when using defaultValue (line below)

2024-04-07 13:00 UTC, tcarmeli1 commented on Packs/PaloAltoNetworksAIOps/Integrations/PaloAltoNetworksAIOps/PaloAltoNetworksAIOps.yml
> +      description: Whether to export the generated report as a file.
it does this automatically when using defaultValue (line below)

2024-04-14 06:39 UTC, merged