New Integration - AWS EKS
demisto/content pull request #33412
Opened 2024-03-19 08:33 UTC by RotemAmit

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-7998)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-03-26 14:30 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.py
> +        arg_num = arg_num + 1 if arg else arg_num
```suggestion
    arg_num = sum(bool(arg) for arg in arr) # counts the number of non-empty args.
```

2024-03-26 15:11 UTC, ShirleyDenkberg commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS_description.md
> +- Create an Amazon EKS clusters.
```suggestion
- Create Amazon EKS clusters.
```

2024-03-26 15:12 UTC, ShirleyDenkberg commented
@eyalpalo @sapirshuker Doc review completed.

@RotemAmit Make sure to regenerate the integration readme after implementing my comments in the yml file.

2024-03-26 15:35 UTC, eyalpalo requested changes
Nice! See my comments, some of them appear once or twice but should be implemented on all of the same code in other commands.

2024-03-26 15:35 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.py
> +    demisto.params().get('proxy', False)
No need, handled by default in the aws client

2024-03-26 15:35 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.yml
> +  required: false
Generally we add also timeout params - please see other aws integration add align the params accordingly.

2024-03-26 15:35 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.yml
> +      type: Unknown
String?

2024-03-26 15:35 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.py
> +        return 'ok'
```suggestion
    return True
```
Or we can remove it entirely

2024-03-26 15:35 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/README.md
> +    | Secret Key |  | True        |
Please add description

2024-03-26 15:35 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/README.md
> +    | Use system proxy settings |  | False        |
Same as above

2024-03-26 15:46 UTC, RotemAmit commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.py
> +    return aws_client.aws_session(service='eks', region=args.get('region'))
It stays to be the same as declared in the params

2024-03-27 09:16 UTC, RotemAmit commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.py
> +            ).get('accessEntry')
If I send the username as None, there is an error saying that username should be of type string.
When I send the username as an empty string, I receive an error that the username must contain at least one char.
This is why I did it this way.

2024-03-28 07:44 UTC, eyalpalo commented on Packs/AWS-EKS/Integrations/AWSEKS/AWSEKS.py
> +        response_data['clusterName'] = cluster_name
you are right, my bad

2024-03-28 07:51 UTC, eyalpalo approved these changes
Great!

2024-03-31 08:17 UTC, merged