Poking around and messing around with the Ancient Grain artifacts
demisto/content pull request #33673
Opened 2024-04-01 04:30 UTC by rhermida

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-04-01 04:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=33673) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=33673) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=33673) it.</sub>

2024-04-01 08:04 UTC, maimorag commented
> [![CLA assistant check](https://camo.githubusercontent.com/fbf2b4a56b8f8dacb3fb4f7f3cf7877b8c27f9cfee8546ff24c8df94facca0f6/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/demisto/content?pullRequest=33673) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=33673) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=33673) it.

Hi @rhermida ,
Thank you for your contribution!
Please sign the CLA so I can start reviewing your contribution :)

2024-04-10 08:49 UTC, ssokolovich requested changes
Hey @rhermida, Thanks for your contribution to our Marketplace. 
Before we proceed, please sign your CLA so we can proceed forward with this Pull Request.

Adding below my notes on your work:
1. Assuming that the `TestMalware` pack is indeed a Test of yours. Please mention if that is intentional or by mistake. In case it was added by mistake, please remove it from this PR.
2. Added some comments on your contributed content- please review them. Feel free to mention me or reach out through our DFIR if you have any questions.

Moving forward (after the CLA), I would like to see a demo of this content.

2024-04-10 08:49 UTC, ssokolovich commented on Packs/AncientGrain/README.md
Please add some sentences about the pack. It is always helpful to describe the pack's intention.

2024-04-10 08:49 UTC, ssokolovich commented on Packs/AncientGrain/Playbooks/RH_-_ChatGPT_Ancient_Grain_Recipes.yml
> +      script: Perplexity LLM Custom|||perplexity-send-prompt
didn't find this command in our repository - can you please share more details on this?

2024-04-21 07:05 UTC, maimorag commented
Hi @rhermida, we haven’t heard from you in a while.
Do you need any help with the pull request?

Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

2024-04-24 07:02 UTC, maimorag commented
Hi @rhermida, 
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

2024-04-24 07:02 UTC, closed without merging