[ASM] - EXPANDER 8513 - XDR Mitigation for ASM
demisto/content pull request #33857
Opened 2024-04-10 04:53 UTC by BigEasyJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-8513](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-8513)

## Description

- Cortex ASM - ASM Alert playbook to support Cortex Endpoint remediation option being selected by a user

- Cortex ASM - Remediation Path Rules playbook to incorporate a new option for Cortex Endpoint remediation to be given as an option to users. This option will be prioritized after cloud and on-premise remediation options. Also, **removed the Cortex ASM - Remediation Objectives** playbook from Cortex ASM - Remediation Path Rules playbook.

- New ** Cortex ASM - Cortex Endpoint Remediation** playbook used to isolate a single Cortex Endpoint (XSIAM/XDR) for remediation purposes.

## Must have
- [x] Tests
- [x] Documentation

2024-04-10 17:04 UTC, johnnywilkes requested changes
some changes plus notes in https://jira-dc.paloaltonetworks.com/browse/EXPANDR-8513

2024-04-11 10:45 UTC, BigEasyJ commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Cortex_Endpoint_Remediation.yml
> +quiet: true
[dbbbce5](https://github.com/demisto/content/pull/33857/commits/dbbbce5cb0f0fe753cce877c86f8c414973bac04)

2024-04-11 10:46 UTC, BigEasyJ commented on Packs/CortexAttackSurfaceManagement/README.md
> +![Cortex ASM - Cortex Endpoint Remediation](https://raw.githubusercontent.com/demisto/content/935a77339c2b1ecde3b9ea64992018bd625c61ed/Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_Corte
[53cecc4](https://github.com/demisto/content/pull/33857/commits/53cecc45c1dc1a564a3468effd3ee152a81aada6)

2024-04-11 14:20 UTC, johnnywilkes approved these changes
@BigEasyJ , thanks for making those changes.  Approved!

2024-04-11 18:08 UTC, BigEasyJ commented
@anas-yousef @ssokolovich this PR is ready from the Xpanse side.

2024-04-14 12:48 UTC, anas-yousef approved these changes

2024-04-14 12:48 UTC, merged