[ASM] EXPANDR-9134 service account changes
demisto/content pull request #33926
Opened 2024-04-12 06:37 UTC by capanw

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9134
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-8417

## Description
Add support for distinguishing service accounts for IAM enrichment steps

## Must have
- [ ] Tests
- [ ] Documentation

2024-04-12 18:52 UTC, johnnywilkes requested changes
@capanw , The PR looks good.  Adding a more broad playbook question in https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9134

2024-04-18 06:29 UTC, capanw commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_GCP_Enrichment.yml
> +        simple: GCP-SERVICE-ACCOUNT
added accounttype field and updated RankServiceOwners script

2024-04-18 06:31 UTC, capanw commented on Packs/CortexAttackSurfaceManagement/doc_files/Cortex_ASM_-_GCP_Enrichment.png
Done!!

2024-04-18 12:49 UTC, johnnywilkes requested changes
made another comment in https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9134

2024-04-18 21:14 UTC, capanw commented
> made another comment in https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9134

@johnnywilkes, added a new branch in the playbook

2024-04-19 19:54 UTC, johnnywilkes approved these changes
@capanw , thanks for making changes
@BigEasyJ , what you incorporated looks good

2024-04-19 20:12 UTC, capanw commented
@maimorag, this is approved from RC side. Please review and merge when you have time. Thanks

2024-04-21 07:07 UTC, maimorag approved these changes

2024-04-21 07:15 UTC, maimorag approved these changes
Hi @capanwת
Good work :)

2024-04-21 07:34 UTC, merged