Added ARO comment command
demisto/content pull request #33928
Opened 2024-04-12 17:26 UTC by FieldEffect-OperationalDevelopment

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-04-15 13:46 UTC, maimorag requested changes
Hi @FieldEffect-OperationalDevelopment  ,
Thank you for your contribution!
Good work :)

2024-04-15 17:17 UTC, FieldEffect-OperationalDevelopment commented on Packs/CovalenceManagedSecurity/ReleaseNotes/1_3_0.md
> +  - ***cov-mgsec-comment-aro***
Done, thank you.

2024-04-16 06:24 UTC, maimorag commented
Hi @FieldEffect-OperationalDevelopment, the code looks good!

We're ready for a demo. Please check [this page](https://xsoar.pan.dev/docs/contributing/demo-prep), and let me know when you're available for one over DFIR. 
Feel free also to send me a recording of a demo.

2024-04-21 07:10 UTC, maimorag commented
Hi @FieldEffect-OperationalDevelopment, we haven’t heard from you in a while.
Do you need any help with the pull request?


Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

> Hi @FieldEffect-OperationalDevelopment, the code looks good!
> 
> We're ready for a demo. Please check [this page](https://xsoar.pan.dev/docs/contributing/demo-prep), and let me know when you're available for one over DFIR. Feel free also to send me a recording of a demo.

2024-04-24 15:09 UTC, maimorag approved these changes

2024-04-25 06:49 UTC, merged