Ews fetch fix image
demisto/content pull request #34116
Opened 2024-04-25 22:25 UTC by tcarmeli1

## Status
- [x] In Progress

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10016

## Description
fix inline mages

2024-05-12 08:27 UTC, jbabazadeh reviewed
Great work!
I did a partial review there is things i would like to discuss over a call

2024-05-12 08:27 UTC, jbabazadeh commented on Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py
> +                        # if header.get('name') == 'Content-Disposition':
remove the comments

2024-05-12 08:27 UTC, jbabazadeh commented on Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
> +    - description: identifier ids not download all files to xsoar (for preprocess script).
```suggestion
    - description: Identifier ids to download to XSOAR (to avoid downloading all files to XSOAR during the preprocessing script).
```

2024-05-12 08:27 UTC, jbabazadeh commented on Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
> +    - description: Content IDs of the required attachments.
should have the same description like other integrations.

2024-05-12 08:27 UTC, jbabazadeh commented on Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
> +            demisto.debug(f"this is debugging {incidents[0]['attachment']}")
remove

2024-05-12 08:27 UTC, jbabazadeh commented on Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
> +    - description: Content IDs of the required attachments.
same here

2024-06-08 19:59 UTC, jbabazadeh requested changes
Nice job! 
please see my comments. 
most of the comments on Gmail are relevant to all other email integrations please fix on all.

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
> +    context_html_body = re.sub(r'(<img[^>]+src="/markdown[^"]*")', r'\1 width="400" height="400"', body_to_html)
remove the fix width and height.

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
> +def convert_internal_url_to_base64(match):
add docstring

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
> +    return f'src="data:image/{image_type};base64,{base64_data_image}" width="300" height="300"'
Remove the fix size

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
> +def handle_image_type(base64_string):
Add docstring

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
> +    result_array.append(msg)
why you need to return array now and not just the msg?

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/Gmail/Integrations/Gmail/Gmail.py
> +    demisto.debug(f"i_have_file_results {file_results=}")
remove debug

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/Gmail/Integrations/Gmail/Gmail.py
> +            demisto.debug('11111')
remove debugs

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/Gmail/Integrations/Gmail/Gmail.py
> +        cid = (f'{name}@{random_word_generator(8)}_{random_word_generator(8)}')
you can use UUID - uuid.uuid4()

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/Gmail/Integrations/Gmail/Gmail.py
> +            if part['body'].get('attachmentId') is not None and part.get('headers'):
is the headers always exist if the email have attachments?

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/Gmail/Integrations/Gmail/Gmail.yml
> +    - description: Identifier ids to download to XSOAR (to avoid downloading all files to XSOAR during the preprocessing script).
nice!

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
> +    - description: The content in html format (htmlBody) of the email.
the command already have body and bodytype args

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +            if integration_name in ['EWS v2', 'EWSO365']
add a comment

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.py
> +    def _build_inline_layout_attachments_input(cls, inline_from_layout_attachments):
lets talk about this again.

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.py
> +        demisto.debug(f"{json_data=}")
remove debug

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.py
> +    def random_word_generator(length):
Use UUID instead

2024-06-08 19:59 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.yml
> +dockerimage: demisto/crypto:1.0.0.96042
Need also release note and to all the integration that depends on this api module (should happen automticly when running demisto-sdk update-release-notes)

2024-06-16 14:16 UTC, michal-dagan commented on Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/README.md
> +from MicrosoftApiModule import *  # noqa: E402
```suggestion
from MicrosoftGraphMailApiModule import *
```

2024-06-16 14:18 UTC, michal-dagan commented on Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/README.md
> +Then, the `MicrosoftGraphClient` will be available for usage. For examples, see the `Microsoft Graph Listener` or `Microsoft Graph Mail` integrations.
```suggestion
Then, the `MsGraphMailBaseClient` will be available for usage. For examples, see the `Microsoft Graph Listener` or `Microsoft Graph Mail` integrations.
```

2024-06-24 09:47 UTC, tcarmeli1 commented
Hi @yuvalbenshalom ,
Can you please assist with a force-merge on this PR.
TPBs are failing in xsoar-ng as detailed below:
- IAMInitOktaUser - Test : succeed locally in xsoar 6 (uses EWSO365 but not the commands i changed).
- Send Investigation Summary Reports - Test: succeed locally in xsoar 6 (fails in ng on GenerateSummaryReports which is not related to my changes)
- pyEWS_Test : succeed in xsoar 6 build flow.
- Gmail Single User - Test: instance has expired creds.
- Phishing v3 - DomainSquatting+EML+MaliciousIndicators - Test: fails on Manually search & delete emails which is not related to my changes.
- EWS search-mailbox test : succeed locally in xsoar 6.
Thank you!

2024-06-24 09:49 UTC, jbabazadeh approved these changes

2024-06-25 10:26 UTC, merged