XSUP-36437/FireEyeAXSeries
demisto/content pull request #34188
Opened 2024-05-05 07:05 UTC by sapirshuker

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36437)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-05-16 09:13 UTC, yaakovpraisler approved these changes

2024-05-16 09:13 UTC, yaakovpraisler commented on Packs/fireeye/ReleaseNotes/1_0_18.md
> +- Fixed an issue where the ***fe-submit-result*** command failed with not informative error.
```suggestion
- Fixed an issue where the ***fe-submit-result*** command failed with an uninformative error.
```

2024-05-19 06:54 UTC, eyalpalo requested changes
Nice, see my comment

2024-05-19 06:54 UTC, eyalpalo commented on Packs/fireeye/Integrations/Fireeye/Fireeye.js
> +            if (command === 'fe-submit-result' && 'submissionStatus' in result && result.submissionStatus.submissionStatus === 'In Progress'){
if result is not a dict, but class, the in operator should not work to check if an attribute exists. We should use hasattr

2024-08-06 00:11 UTC, closed without merging