fixing bug artifacts from XDR missing
demisto/content pull request #34204
Opened 2024-05-05 10:55 UTC by maimorag

## Status
- [x] In Progress

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36770)

## Description
- Fixing incident artifacts is not populated on new incidents when bringing them into XSOAR.
- Setting exclude_fields with default_value=False

2024-05-20 07:04 UTC, eyalpalo requested changes

2024-05-20 07:18 UTC, maimorag commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +    raw_incident = client.get_multiple_incidents_extra_data(incident_id_list=[incident_id], fields_to_exclude=False)
ok, add a parameter for the function if the customer rather return artifacts or not

2024-05-20 09:30 UTC, eyalpalo approved these changes

2024-05-20 09:30 UTC, eyalpalo commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
> +                                                  statuses=statuses, starred=starred,
```suggestion
                                                  statuses=statuses,
                                                  starred=starred,
```

2024-05-22 19:18 UTC, maimorag commented
test playbook "test Playbook - Cortex XDR - Retrieve File by sha256 " fails on 
https://jira-dc.paloaltonetworks.com/browse/CIAC-9932.

2024-05-24 13:19 UTC, maimorag commented
test playbook "test Playbook - Cortex XDR - Retrieve File by sha256 " 
 fails on each [server](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/6147595) on:
 https://jira-dc.paloaltonetworks.com/browse/CIAC-9932.

@ShahafBenYakir can you please FM?

2024-05-26 11:35 UTC, merged