Support multiple drilldown searches response
demisto/content pull request #34327
Opened 2024-05-12 09:36 UTC by ShacharKidor

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [CIAC-9888](https://jira-dc.paloaltonetworks.com/browse/CIAC-9888).

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-05-30 14:15 UTC, ShacharKidor commented
Hi @yuvalbenshalom, 
Please review the PR. 
About the delicate change we discussed (in the `submitted()` function - line 707), I investigated that again and now have a better understanding. I changed the condition there and added a similar change to the `failed_to_submit()` function (line 725). 
Let's talk about it again once you get there.  

Please let me know if something is unclear or needs to be improved. 
Thanks!

2024-06-02 09:49 UTC, ShirleyDenkberg commented
@ilappe @yuvalbenshalom Doc review completed.

2024-06-05 12:19 UTC, yuvalbenshalom requested changes
Looks good, see my comments.

2024-06-05 12:19 UTC, yuvalbenshalom commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
> +        # TODO: consult with Yuval regarding the delicate change in the condition here.
```suggestion
```

2024-06-05 12:19 UTC, yuvalbenshalom commented on Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
> +MAX_RESULTS_TO_DISPLAY = 10  # TODO: need to remove this const (used only for demo)
```suggestion
```

2024-06-06 09:19 UTC, ShacharKidor commented on Packs/SplunkPy/ReleaseNotes/3_1_28.md
> +Added support for getting results of multiple drilldown searches enrichment associated with a Splunk notable (supported from Enterprise Security v7.2.0).
Added thanks!

2024-06-06 10:56 UTC, ShacharKidor commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
> +@pytest.mark.parametrize('enrichments, expected_result', [
Added. 
Cool feature thanks :)

2024-06-06 11:25 UTC, yuvalbenshalom approved these changes

2024-06-06 18:29 UTC, merged