Proofpoint TAP v2 - Added a validation to the start time
demisto/content pull request #34338
Opened 2024-05-12 13:12 UTC by RotemAmit

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36905)

## Description
* Since the API states that "the maximum time into the past that can be queried is 7 days", I added a validation to enforce it, instead of getting an exception from the API.
* Updated the fetch-incidents to use `dateparser.parse()` instead of `parse_date_range()`, because it is deprecated.

## Must have
- [ ] Tests
- [ ] Documentation

2024-05-12 14:30 UTC, MLainer1 approved these changes
Nice! 🆒

2024-05-12 14:30 UTC, MLainer1 commented on Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
> +    demisto.debug(f'In validate_start_query_time {start_query_time=}')
```suggestion
```

2024-05-12 15:05 UTC, eyalpalo requested changes

2024-05-12 15:05 UTC, eyalpalo commented on Packs/ProofpointTAP/ReleaseNotes/1_2_12.md
> +Fixed an issue where too old start date could be sent in the request to the API in the fetch-incidents command.
```suggestion
Fixed an issue where excessively old start dates could be sent API in the fetch-incidents command.
```

2024-05-12 15:18 UTC, RotemAmit commented on Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
> +    dt_start_query_time = datetime.strptime(start_query_time, DATE_FORMAT) if start_query_time else get_now() - timedelta(hours=1)
yes

2024-05-12 15:39 UTC, eyalpalo approved these changes
Nice

2024-05-16 13:57 UTC, MLainer1 reviewed
😎

2024-05-19 07:42 UTC, eyalpalo approved these changes

2024-05-19 07:42 UTC, eyalpalo commented on Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
> +
Please remove

2024-05-19 12:46 UTC, merged