New exabeam security pack
demisto/content pull request #34397
Opened 2024-05-16 13:03 UTC by inbalapt1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +- display: Client Id
```suggestion
- display: Client ID
```

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +    - description: Comma-separated list of fields to GROUP BY.
```suggestion
    - description: Comma-separated list of fields by which to group the results.
```

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +      description: Represents the raw logs associated with the event.
```suggestion
      description: The unique identifier associated with the event.
      type: String
    - contextPath: ExabeamPlatform.Event.rawLogIds
      description: The raw log identifiers associated with the event.
      type: String
    - contextPath: ExabeamPlatform.Event.tier
      description: The tier associated with the event.
      type: String
    - contextPath: ExabeamPlatform.Event.parsed
      description: Whether the event has been parsed.
      type: String
    - contextPath: ExabeamPlatform.Event.rawLogs
      description: The raw logs associated with the event.
```

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform_description.md
> + - **Basic Authentication** - Providing Key ID and Key Secret in the corresponding   parameters in the configuration.
```suggestion
 - **Basic Authentication** - Provide the Key ID and Key Secret in the corresponding  parameters in the configuration.
```

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform_description.md
> +For assistance accessing the Exabeam API, please refer to [Exabeam API Base URLs documentation](https://developers.exabeam.com/exabeam/docs/exabeam-api-base-urls)
```suggestion
For assistance accessing the Exabeam API, refer to [Exabeam API Base URLs documentation](https://developers.exabeam.com/exabeam/docs/exabeam-api-base-urls)
```

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/README.md
> +    | Client Id | True |
```suggestion
    | Client ID | True |
```

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/README.md
> +| group_by | Comma-separated list of fields to GROUP BY. | Optional |
```suggestion
| group_by | Comma-separated list of fields by which to group the results. | Optional | 
```

2024-05-22 09:18 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/README.md
> +| ExabeamPlatform.Event.rawLogs | String | Represents the raw logs associated with the event. |
```suggestion
| ExabeamPlatform.Event.id | String | The unique identifier associated with the event. | 
| ExabeamPlatform.Event.rawLogIds | String | The raw log identifiers associated with the event. | 
| ExabeamPlatform.Event.tier | String | The tier associated with the event. | 
| ExabeamPlatform.Event.parsed | String | Whether the event has been parsed. | 
| ExabeamPlatform.Event.rawLogs | String | The raw logs associated with the event. | 
```

2024-05-22 15:13 UTC, omerKarkKatz requested changes
Good job! Please add a few words in the pack readme as well about Exabeam product.

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +    This Client implements API calls, and does not contain any XSOAR logic.
Please remove this part of the description

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +
please add code examples to the doc_string (look it up).

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +    if error == 'not enough values to unpack (expected 2, got 1)':
Will it always be with this numbers 2 and 1 i think its better to remove the number part.?

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +        if parsed_entry:
```suggestion
        if parsed_entry := _parse_entry(entry)
```

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +    return 'ok'
Can we add a check the client.access_token is populated? Otherwise client is not used and should not appear in the function definition.

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +      name: group_by
If this is an array an the isArray key to the argument (look it up in the repo).

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform_test.py
> +@pytest.mark.parametrize('input_str, expected_output', [
Please add a test involving all the scenarios together true/false and a string value.

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform_test.py
> +def test_search_request(mocker):
Why do we have # inside the doc string?

2024-05-22 15:13 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/TestPlaybooks/ExabeamSecurityOperationsPlatform-test.yml
> +id: ExabeamSecurityOperationsPlatform-test
Change to version -1

2024-05-26 11:45 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform_description.md
> + - **OAuth2.0** - Provide the Key ID and Key Secret in the corresponding  parameters in the configuration.
```suggestion
 - **OAuth2.0** - Provide the ID and Secret in the integration configuration.
```

2024-05-26 11:49 UTC, omerKarkKatz approved these changes

2024-05-26 11:51 UTC, omerKarkKatz commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/README.md
> +This integration was integrated and tested with version v1.0 of ExabeamSecOpsPlatform.
```suggestion
Exabeam Security Operations Platform offers a centralized and scalable platform for log management.
This integration was integrated and tested with version v1.0 of ExabeamSecOpsPlatform.
```

2024-05-26 15:19 UTC, merged