Opencti filter update
demisto/content pull request #34432
Opened 2024-05-19 10:33 UTC by noydavidi

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9809

## Description
A few sentences describing the overall goals of the pull request's commits.

1. docker image changed
2. filters object in the get_indicators function changed according to the new version of OpenCTI
3. not inserting parameters to the command opencti_get_indicators created a bug - fixed by changing the default in this case to filter "ALL"
4. by those changes the "test-module" button is fixed. 
5. bug fix: inserting just score_end or just score_start in the command created an error, now when inserting just one of them, there are default value for each value
6. added some test for those case mentioned above

## Must have
- [x] Tests
- [x] Documentation

2024-05-19 12:55 UTC, JudahSchwartz reviewed
amazing first pr!!!

2024-05-19 12:55 UTC, JudahSchwartz commented on Packs/OpenCTI/ReleaseNotes/1_0_11.md
> +bug fix: inserting just score_end or just score_start in the command created an error, now when inserting just one of them, there are default value for each value. added some tests for those cases me
```suggestion
Added default values for **score_end** and **just** score_start in the **___** command.
```

2024-05-19 12:55 UTC, JudahSchwartz commented on Packs/OpenCTI/ReleaseNotes/1_0_11.md
> +- filters object in the get_indicators function changed according to the new version of OpenCTI
Too much details for release notes. Main point should be "Switched x command to work with version x.y of opencti)

2024-05-19 12:55 UTC, JudahSchwartz commented on Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.py
> +            'mode': 'or'
are we sure this should be "or" ?

2024-05-19 13:30 UTC, ShirleyDenkberg commented
@noydavidi I agree with Judah's comments.
@JudahSchwartz Doc review completed.

2024-05-22 12:25 UTC, JudahSchwartz approved these changes
🥳

2024-05-22 12:26 UTC, JudahSchwartz requested changes

2024-05-22 12:26 UTC, JudahSchwartz commented on Packs/OpenCTI/Integrations/OpenCTI/README.md
> +This integration is compatible with OpenCTI versions from 4.X to 5.12.X.
is this still true? compatible version 4.x? didnt we just break it?

2024-05-22 13:20 UTC, JudahSchwartz approved these changes

2024-05-23 10:14 UTC, merged