Ciac 10199 azure storage management supporting client credentials flow
demisto/content pull request #34454
Opened 2024-05-20 13:37 UTC by ilaredo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[Jira ticket](https://jira-dc.paloaltonetworks.com/browse/CIAC-10199?filter=-1)

## Description
- Verify that all the commands work as expected in the new flow.
- Update documentation with new authentication options.

## Must have
- [x] Tests
- [x] Documentation

2024-05-20 14:14 UTC, michal-dagan commented on Packs/AzureStorage/Integrations/AzureStorage/README.md
> +   i. Run the `!azure-storage-generate-login-url` command in the War Room and follow the instruction.
same

2024-05-20 16:44 UTC, ShirleyDenkberg commented
@michal-dagan @eyalpalo @sapirshuker Doc review completed.

2024-05-21 11:38 UTC, michal-dagan commented on Packs/AzureStorage/Integrations/AzureStorage/AzureStorage_test.py
> +def test_generate_login_url(mocker, authentication_type):
the command is relevant only for `authorization code flow`
as in the previous integration: https://github.com/demisto/content/pull/34394#discussion_r1606044150

2024-05-21 11:44 UTC, michal-dagan commented on Tests/conf.json
> +            "instance_names": "azure_storage_client_cred",
please add the first instance_name  (before, it takes it as default because the secret has the integration name, now it considers only the new)

2024-05-23 12:13 UTC, eyalpalo requested changes

2024-05-23 12:13 UTC, eyalpalo commented on Packs/AzureStorage/Integrations/AzureStorage/AzureStorage_test.py
>          return json.loads(f.read())
Why don't we add relevant tests here?

2024-05-28 08:32 UTC, eyalpalo approved these changes

2024-05-28 11:17 UTC, merged