Trend micro vision one
demisto/content pull request #34456
Opened 2024-05-20 19:53 UTC by shaqnawe

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests
- [x] Documentation

2024-05-21 13:47 UTC, Shellyber requested changes
Looks good!
Thank you for your contribution
Please see my notes

2024-05-21 13:47 UTC, Shellyber commented on Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.py
> +        return_error(message=f"{err.message}", error=str(err))
```suggestion
        raise Exception(message=f"{err.message}", error=str(err))
```

2024-05-21 13:47 UTC, Shellyber commented on Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.py
> +        return_error("Please refine search, this query returns more than 50 results.")
```suggestion
        raies Exception("Please refine search, this query returns more than 50 results.")
```

2024-05-21 13:47 UTC, Shellyber commented on Packs/TrendMicroVisionOne/pack_metadata.json
> +    "currentVersion": "4.2.0",
```suggestion
    "currentVersion": "4.1.2",
```
Please update the release notes file name accordingly

2024-05-28 12:38 UTC, kgal-pan commented on Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3.yml
> +  dockerimage: devtesting/pytmv1:0.8.3.1715976040
```suggestion
  dockerimage: demisto/pytmv1:0.8.3.96268
```

2024-06-13 06:20 UTC, Shellyber commented
Hi @shaqnawe ,
Thank you for your contribution.
I have not received your response in the last two weeks, so I will close your PR now.
Please feel free to re-open it whenever you're available.
Thanks again.

2024-06-13 06:20 UTC, closed without merging