add: update octoxlabs
demisto/content pull request #34532
Opened 2024-05-24 10:45 UTC by ogulcanhero

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Octox Labs Cyber Security Asset Management platform XSoar Integration update.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [x] 6.1.0
- [x] 6.2.0
- [x] 6.5.0
- [x] 6.12.0 

## Must have
- [x] Tests
- [x] Documentation

2024-05-24 11:43 UTC, ogulcanhero commented
Hi @kgal-pan, I'm running this command `demisto-sdk update-release-notes -i Packs/OctoxLabs` and I receive AttributeError for my added files (example: **Packs/OctoxLabs/Integrations/OctoxLabs/test_data/get_user.json**). Is any bug in demisto-sdk like this case?

2024-05-26 09:31 UTC, kgal-pan commented
> Hi everyone, I'm running this command `demisto-sdk update-release-notes -i Packs/OctoxLabs` and I receive AttributeError for my added files (example: **Packs/OctoxLabs/Integrations/OctoxLabs/test_data/get_user.json**). Is any bug in demisto-sdk like this case?

Hey @ogulcanhero - I see that you already have a new release note created (`Packs/OctoxLabs/ReleaseNotes/2_0_0.md`). Please use that to fill out the changes you've introduced.

2024-05-26 09:44 UTC, Shellyber requested changes
Looking good.
Please update the release notes

2024-05-26 09:44 UTC, Shellyber commented on Packs/OctoxLabs/ReleaseNotes/2_0_0.md
> +##### OctoxLabs
Please update the release notes with all the new commands

2024-05-27 13:00 UTC, ogulcanhero commented
Hi! I made the changes you requested. Is everything the way you want?

2024-05-27 21:07 UTC, ogulcanhero commented
Okay, then if you tell us your available time, we can set a meeting with @ahmetkotan

2024-05-30 11:21 UTC, Shellyber commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.py
> +        outputs_prefix="OctoxLabs.Companies",
```suggestion
        outputs_prefix="OctoxLabs.Company",
```
You should do it for the rest of the commands as well (domains, users) etc.

2024-05-30 11:24 UTC, Shellyber commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.py
> +        outputs_prefix="OctoxLabs.Users",
```suggestion
        outputs_prefix="OctoxLabs.User",
```

2024-05-30 11:24 UTC, Shellyber commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.py
> +        outputs_prefix="OctoxLabs.Domains",
```suggestion
        outputs_prefix="OctoxLabs.Domain",
```

2024-05-30 11:39 UTC, ogulcanhero commented
![Screenshot 2024-05-30 at 14 31 40](https://github.com/demisto/content/assets/99717065/b5e0f018-535e-45fe-b63e-a512283f5861)

Hi @Shellyber! We run octoxlabs-get-companies, after that run octoxlabs-get-company-by-id. As you can see in the image above, the schemes look irregular in our opinion. It seems like it's better to keep it the way it was before in terms beacuse Companies schema is plural. Do you think we should change it anyway?

2024-05-30 12:08 UTC, Shellyber commented
@ogulcanhero It's because when you run the `get-companies` command you return the result as is, instead of only what under the results. 
You can keep it as is if you don't want to change the entire command.

2024-05-30 12:30 UTC, ogulcanhero commented
For now, we want to keep the command as it is. Older commands also had the same structure. We separate 'companies' and 'company' on purpose. Let’s proceed with that if it’s viable.

2024-05-30 13:25 UTC, Shellyber approved these changes

2024-05-30 13:25 UTC, merged