added relationships
demisto/content pull request #34656
Opened 2024-05-31 10:11 UTC by enes-oezdemir

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-06-05 09:40 UTC, jlevypaloalto requested changes
Hi @enes-oezdemir ,
Thank you for your contribution!
Great work :)

Just a few comments:

2024-06-05 09:40 UTC, jlevypaloalto commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +        return f"Relationship between {request_id01} and {request_id02} is created"
```suggestion
        return f"Created relationship between {request_id01} and {request_id02}."
```

2024-06-05 09:40 UTC, jlevypaloalto commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +    """BmcITSM ticket delete command.
Is this the right command?

2024-06-05 09:40 UTC, jlevypaloalto commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +        association_type01 = association_types.get(association_type01) or [
Let's use one bi-directional dict instead of checking values for keys.

2024-06-05 09:40 UTC, jlevypaloalto commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +    return all(not value for value in dict_obj.values())
Nice :)

2024-06-05 09:40 UTC, jlevypaloalto commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.yml
> -    - name: assigned_group
When fixing argument names, please change them in the code and not in the yml.

2024-06-05 10:44 UTC, enes-oezdemir commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +                                           request_type01: str,
since there is no request_type02 I simply removed the numbers from `request type`, `association type` and `request description`

2024-06-16 15:24 UTC, jlevypaloalto commented
Closing this PR as it's changes are incorporated in [this](https://github.com/demisto/content/pull/34741) PR.

2024-06-16 15:24 UTC, closed without merging