Implemented bypassing malformed indicators
demisto/content pull request #34657
Opened 2024-05-31 10:11 UTC by cyble-dev

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This is just a minor fix. Sometimes a few indicators fetched from our servers were malformed and were not properly structured. Due to this, the code was breaking. To fix this, we have configured to bypass such indicators.

## Must have
- [ ] Tests
- [ ] Documentation

2024-05-31 10:57 UTC, cyble-dev commented
Hello @edik24, @Shellyber, @MLainer1
Please proceed, let me know if you need anything else.

2024-06-02 07:24 UTC, Shellyber requested changes
Nice work!
Please see my small comments.
Also, please have a look at the pre-commit step that fails, and fix it as well

2024-06-02 07:24 UTC, Shellyber commented on Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.py
> +                    # raise ValueError("Last fetch time retrieval failed.")
If it is not needed, please remove :)

2024-06-02 07:24 UTC, Shellyber commented on Packs/CybleThreatIntel/ReleaseNotes/2_0_23.md
> +- Implemented a check to ignore malformed indicators.
```suggestion
- Fixed an issue where the **fetch-indicators** command failed when encountering improperly structured indicators
```

2024-06-02 10:54 UTC, cyble-dev commented on Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.py
> +                    # raise ValueError("Last fetch time retrieval failed.")
Done

2024-06-02 10:54 UTC, cyble-dev commented on Packs/CybleThreatIntel/ReleaseNotes/2_0_23.md
> +- Implemented a check to ignore malformed indicators.
Done

2024-06-03 04:47 UTC, cyble-dev commented
Hi @Shellyber,
I have implemented the fixes suggested by you.
For the issue in pre-commit, I couldn't figure out how to fix it. I tried a couple of fixes but still getting the error. Please take a look at the error and commits and suggest how can I fix it.
Thanks.

2024-06-03 09:30 UTC, Shellyber commented
@cyble-dev The error is happening because it doesn't get to the `except` part. 
The values for the try clause are:
val = []
time = 2022-06-11 00:00:00
It doesn't go the the exception, need to investigate further why

2024-06-03 16:26 UTC, cyble-dev commented
Hi @Shellyber,
Fixed the test as well. Please proceed.

2024-06-04 06:21 UTC, Shellyber approved these changes
Great work!

2024-06-04 06:35 UTC, merged

2024-06-04 06:36 UTC, cyble-dev commented
Hello @Shellyber,
Just noticed that the docker image is not update in release note. Somehow I missed it and it didn't reflect in test as well. Can you please update it?