Allinone
demisto/content pull request #34741
Opened 2024-06-05 13:57 UTC by enes-oezdemir

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-06-16 15:19 UTC, jlevypaloalto requested changes
Hi @enes-oezdemir,

Let's continue our conversation here, I'll add the unaddressed comments here too.

2024-06-16 15:19 UTC, jlevypaloalto commented on Packs/BmcITSM/Integrations/BmcITSM/README.md
> +### bmc-itsm-service-request-update
This looks like a duplicate of a pre-existing command. There are more command docs that have this duplication. Let's remove them.

2024-06-25 07:17 UTC, jlevypaloalto commented
Hi @enes-oezdemir, we haven’t heard from you in a while.
Do you need any help with the pull request?

Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

2024-06-25 08:07 UTC, enes-oezdemir commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +            res = self._http_request("GET",
![image](https://github.com/demisto/content/assets/151725756/5d669133-cb7b-40bd-9182-17a075db6890)

2024-06-25 08:12 UTC, enes-oezdemir commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +            res = self._http_request("GET",
`/api/arsys/v1/entry/HPD:WorkLog?q='Incident Number'="XYZ"`

lists out this worklog and there is the reference to that file

2024-06-25 09:43 UTC, enes-oezdemir commented
> Hi @enes-oezdemir, we haven’t heard from you in a while. Do you need any help with the pull request?
> 
> Please feel free to reach out to me here or on Slack. Thanks again for contributing to our repo, hope to hear from you soon.

Sorry, I got caught up with work. demisto-sdk command is creating duplicates and throwing errors for some reason. I will get back to it

2024-06-26 07:17 UTC, jlevypaloalto commented on Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py
> +            res = self._http_request("GET",
How do you know that there are always only 1-4 pages?
Let's use the URLs in the response instead of making our own.

2024-07-04 06:32 UTC, jlevypaloalto commented
Hi @enes-oezdemir,
As we discussed, I will close the PR.
Please feel free to re-open it when you are available to continue.
Thanks again.

2024-07-04 06:32 UTC, closed without merging