back adopt_pack and checkout_contribution scripts
demisto/content pull request #34796
Opened 2024-06-09 11:53 UTC by israelpoli

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-06-09 14:20 UTC, RotemAmit commented on contribution/README.md
> +This folder is used by contributors.
```suggestion
This folder is used for contributions related scripts.
```

2024-06-09 14:28 UTC, kobymeir approved these changes

2024-06-09 15:12 UTC, kgal-pan requested changes
Looks good overall! 

Just one thing that I believe need to be addressed:

- The file `git_pull_master_into_fork.sh` is also referenced in `.circleci/is_file_up_to_date.sh`:

```bash
❯ grep "git_pull_master_into_fork.sh" -rnw .
./.circleci/is_file_up_to_date.sh:34:          echo "Run ./.circleci/git_pull_master_into_fork.sh or merge manually from upstream demisto content"
```

So we probably want to change the path there as well.

2024-06-09 16:16 UTC, israelpoli commented
I changed the message to contributions to the new location
although the script will still exist in the old location (in addition to the new location)

2024-06-10 07:11 UTC, kgal-pan approved these changes
Nice work!

2024-06-10 07:13 UTC, merged