Topic/privx integration
demisto/content pull request #34841
Opened 2024-06-13 10:39 UTC by jjh-ssh

Compatible with PrivX version 26 onwards.

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues

## Description
This is the first release of PrivX integration for PrivX 26 onwards.
Depends on demisto/privx-api:26.0.0.97238 dockerfile (so version number marked as 1.26.0 to indicate that).
Base container image will be upgraded later to v34, after that this PR will be finished.

## Must have
- [ ] Tests
- [ ] Documentation

2024-06-13 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=34841) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=34841) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=34841) it.</sub>

2024-06-16 08:11 UTC, Shellyber requested changes
Thank you for your contribution!
Great work.
Please see my comments and let me know if you need any help with it.
Also, let's schedule a demo for this new pack

2024-06-16 08:11 UTC, Shellyber commented on Packs/PrivX/Integrations/PrivX/PrivX.yml
> +  type: 0
All the authentication params need to be of type 9 - [credentials](https://xsoar.pan.dev/docs/integrations/code-conventions#credentials)

2024-06-16 09:27 UTC, kgal-pan commented
@jjh-ssh - Please sign the [Contribution Form](https://forms.gle/XDfxU4E61ZwEESSMA). Use `ssh-communications-security-17060` in the Partner ID field.

2024-06-26 10:24 UTC, Shellyber commented
Hi @jjh-ssh,
Thank you for your contribution. 
I am closing  your PR for the moment.
Please feel free to re-open it when you are available to continue. 
Thanks again.

2024-06-26 10:24 UTC, closed without merging