Ciac 5471 exabeam fetch users
demisto/content pull request #34900
Opened 2024-06-18 07:17 UTC by YairGlik

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-5471)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests
- [ ] Documentation

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/CommonTypes/ReleaseNotes/3_5_6.md
> +- Added support for incident type Exabeam Notable User.
```suggestion
##### Location
Added support for incident type Exabeam Notable User.

##### Department
Added support for incident type Exabeam Notable User.

##### End Time
Added support for incident type Exabeam Notable User.

##### Work Phone
Added support for incident type Exabeam Notable User.

##### Start Time
Added support for incident type Exabeam Notable User.

##### First Seen
Added support for incident type Exabeam Notable User.

##### Last Seen
Added support for incident type Exabeam Notable User.

##### Mobile Phone
Added support for incident type Exabeam Notable User.

##### Manager Name
Added support for incident type Exabeam Notable User.

##### User Groups
Added support for incident type Exabeam Notable User.

##### Title
Added support for incident type Exabeam Notable User.

##### Email
Added support for incident type Exabeam Notable User.

##### Username
Added support for incident type Exabeam Notable User.

##### Risk Score
Added support for incident type Exabeam Notable User.
```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- New: Created a new layout for the incident type: **Exabeam Notable User**.
```suggestion
Added a mapping for the new incident type: **Exabeam Notable User**.


#### Incident Types

##### New: Exabeam Notable User

New: Created a new incident type for notable users fetched.

##### Exabeam Incident

Added a new layout.


#### Layouts

##### New: Exabeam Incident

New: Created a new layout for the incident type: **Exabeam Incident**.

##### New: Exabeam Notable User

New: Created a new layout for the incident type: **Exabeam Notable User**.
```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- Updated the Docker image to: *demisto/python3:3.10.14.99865*.
```suggestion

```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +
```suggestion
- Updated the Docker image to: *demisto/python3:3.10.14.99865*.
```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- Added a new parameters:
```suggestion
- Added the following new parameters:
```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +  - **Minimum Risk Score To Fetch Users**.
```suggestion
  - *Fetch Type*.
  - *Max Users Per Fetch*.
  - *Notable Users Fetch Interval*.
  - *Notable Users First Fetch Timestamp*.
  - *Minimum Risk Score To Fetch Users*.
```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- Updated the integration previously known as **Exabeam** will now be displayed as **Exabeam Advanced Analytics**.
```suggestion
- Updated the integration previously known as **Exabeam** to now be displayed as **Exabeam Advanced Analytics**.
```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +  - If the source is the new users fetch `/uba/api/users/notable`, the incident type will be **Exabeam Notable User**.
```suggestion
Created a new classifier to classify incidents based on the source of the data.
- If the source is the fetch endpoint `/ir/api/incidents/search`, the incident type will be **Exabeam Incident**.
- If the source is the new users fetch `/uba/api/users/notable`, the incident type will be **Exabeam Notable User**.
```

2024-07-02 18:14 UTC, ShirleyDenkberg commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- Added a new incident field to store the session IDs of a user.
```suggestion
Added a new incident field to store the average risk score of a user.

##### New: Exabeam Highest Session Login Host

Added a new incident field to store the highest session login host of a user.

##### New: Exabeam Highest Session Number Of Asset

Added a new incident field to store the number of assets in the highest risk session.

##### New: Exabeam Highest Session Number Of Reasons

Added a new incident field to store the number of reasons in the highest risk session.

##### New: Exabeam Last Activity Time

Added a new incident field to store the last activity time of a user.

##### New: Exabeam Last Activity Type

Added a new incident field to store the type of the last activity of a user.

##### New: Exabeam Past Scores

Added a new incident field to store past risk scores of a user.

##### New: Exabeam Session IDs

Added a new incident field to store the session IDs of a user.
```

2024-07-02 18:15 UTC, ShirleyDenkberg commented
@altmannyarden @idovandijk @jbabazadeh Doc review completed.

2024-07-09 07:51 UTC, jbabazadeh requested changes
Great job!
Please see my comments :)

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +        username, risk_score = user_details.get("username", ""), user_details.get("riskScore", -1)
```suggestion
        username = user_details.get("username", "")
        risk_score = user_details.get("riskScore", -1)
```

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +    excess_length = max(len(combined_usernames) - MAX_LENGTH_CONTEXT, 0)
add comment that explain the logic

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +            new_usernames.append(username)
you don't need both lists. you can use one list

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +    demisto.debug(f"After the added lest run contain {len(usernames_to_lest_run)} usernames")
you have typo in `usernames_to_lest_run` should be last

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +            if key in incident['highestRiskSession'] and incident['highestRiskSession'][key]:
incident['highestRiskSession'][key] can be exist but None? if not remove the and condition

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
> +- display: Max Users Per Fetch
add additional info that its relevant only yo fetch users. to all the fetch user configurations

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
> +- display: Notable Users Fetch Interval
add additional info

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/README.md
> +- Important: Duplicate notable users are never fetched unless the "Reset the 'last run' timestamp" button is pressed.
Great!!

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- Updated the integration to support fetching notable users.
```suggestion
- Updated the integration to support fetch notable users.
```

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- Updated the integration previously known as **Exabeam** to now be displayed as **Exabeam Advanced Analytics**.
```suggestion
- Updated the integration display Name from  **Exabeam** to  **Exabeam Advanced Analytics**.
```

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/Exabeam/ReleaseNotes/2_4_0.md
> +- If the source is the new users fetch `/uba/api/users/notable`, the incident type will be **Exabeam Notable User**.
```suggestion
- If the source is the fetch incidents, the incident type will be **Exabeam Incident**.
- If the source is the fetch notable users the incident type will be **Exabeam Notable User**.
```

2024-07-09 07:51 UTC, jbabazadeh commented on Packs/CommonTypes/IncidentFields/incidentfield-Username.json
> +        "Exabeam Notable User"
wrong indentation

2024-07-09 07:52 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/README.md
> +### Fetch
move this section to be before the commands

2024-07-09 08:37 UTC, YairGlik commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +        fetch_interval = arg_to_number(args.get("notable_users_fetch_interval")) or 60
I added "or 60" because function arg_to_number() returned type None

2024-07-09 08:48 UTC, YairGlik commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +    current_time = datetime.now(pytz.utc)
The method "utcnow" in class "datetime" is deprecated

2024-07-09 08:51 UTC, YairGlik commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +    current_time = datetime.now(pytz.utc)
Are you sure should replace it?

2024-07-09 08:52 UTC, YairGlik commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +        if difference_minutes <= fetch_interval:
I added

2024-07-11 06:33 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +    current_time = datetime.now(pytz.utc)
no

2024-07-11 06:36 UTC, jbabazadeh commented on Packs/Exabeam/Integrations/Exabeam/Exabeam.py
> +        if fetch_interval % 60 != 0:
you should do this validation in the test module. and here just to change it to be whole hours if its not.

2024-07-14 11:22 UTC, jbabazadeh commented
@ShirleyDenkberg , yes the yml and the readme files was changed.

2024-07-14 11:33 UTC, jbabazadeh approved these changes

2024-07-14 11:38 UTC, merged