Ciphertrust integration
demisto/content pull request #34989
Opened 2024-06-20 15:47 UTC by mayyagoldman

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-06-23 08:02 UTC, YuvHayun requested changes

2024-06-23 08:02 UTC, YuvHayun commented on validation_config.toml
> -    "RM101", "RN103", "RM104", "RM105", "RM109", "RM113", "RM114",
Don't remove it completely, move it to warning s,ection please.

2024-06-23 17:23 UTC, omerKarkKatz requested changes

2024-06-24 09:46 UTC, mayyagoldman commented on Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.py
> +        return datetime.strptime(iso_date, DATE_FORMAT_NO_MS).strftime(DATE_FORMAT_HR)
Just a general exception to be printed to the console

2024-06-24 09:56 UTC, mayyagoldman commented on Packs/ThalesCipherTrustManager/README.md
> +## Permissions
the Permissions part?

2024-06-24 17:41 UTC, omerKarkKatz commented on Packs/ThalesCipherTrustManager/README.md
> +## Permissions
yes.

2024-06-24 17:45 UTC, omerKarkKatz commented on Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.py
> +def ciphertrust_table_to_markdown_transform_data(data: dict, keys: list[str], keys_headers_mapping: dict,
Please reomve this function now that we dont use it any more

2024-06-24 17:49 UTC, omerKarkKatz commented on Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.py
> +                                 sort_headers=False)
please add new lines after for loop, if/else or any other cluse statments

2024-06-24 17:50 UTC, omerKarkKatz commented on Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.py
> +    pending_cas = tableToMarkdown('Pending CAs', [{
```suggestion
    } for ca in raw_response.get('resources', []) if ca.get('state') == 'active'], headerTransform=underscoreToCamelCase,
                                 sort_headers=False)

    pending_cas = tableToMarkdown('Pending CAs', [{
```

2024-06-24 17:50 UTC, omerKarkKatz commented on Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.py
> +    expired_cas = tableToMarkdown('Expired CAs', [{
```suggestion
        'Fingerprint': ca.get('sha1Fingerprint', '')
    } for ca in raw_response.get('resources', []) if ca.get('state') == 'pending'], headerTransform=underscoreToCamelCase,
                                  sort_headers=False)
                                  
    expired_cas = tableToMarkdown('Expired CAs', [{
```

2024-06-24 17:56 UTC, omerKarkKatz commented on Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.py
> +            'system') else 'User',
```suggestion
        'Defined By': 'System' if group.get('app_metadata', {}).get('system') ekse 'User',
```

2024-06-25 11:42 UTC, omerKarkKatz approved these changes

2024-06-27 06:59 UTC, YuvHayun commented on validation_config.toml
> +warning = ["DS107", "LO107", "RN103" ]
Was already merged in another pr, revert changes on this file.

2024-06-27 06:59 UTC, YuvHayun approved these changes

2024-06-27 11:57 UTC, merged