XSUP-38612/TAXII2Feed
demisto/content pull request #35166
Opened 2024-07-01 15:32 UTC by sapirshuker

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-07-28 13:58 UTC, eyalpalo requested changes

2024-07-28 13:58 UTC, eyalpalo commented on Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
> +    Checks the correctness of the url.
Can you describe here what makes the url correct?
Also, this code will return true for the URL that contains taxii but not as a suffix, is it valid? The error message you added in the main suggests no.

2024-07-28 14:10 UTC, eyalpalo approved these changes
If the path is indeed the suffix, ok by me

2024-07-28 14:26 UTC, MLainer1 reviewed
🆒

2024-07-28 14:26 UTC, MLainer1 commented on Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
> +    if url and (match := re.search(urlRegex, url)):
Let's use `urllib.parse` instead of regex

2024-07-28 14:26 UTC, MLainer1 commented on Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
> +def is_valid_url(url: Optional[str]):
```suggestion
def is_valid_taxii_url(url: Optional[str]):
```

2024-08-01 11:49 UTC, Ni-Knight commented on Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
> +        if path and ('taxii' in path or 'taxii2' in path):
The path MUST end with `/taxii/` or `/taxii2/`. This will cause a FP if the discovery URL is:
`domain.com/taxii2/bad_path/`

2024-08-01 12:00 UTC, Ni-Knight commented on Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
> +        return_error("Discovery Service URL is not valid, The URL suffix should be taxii or taxii2")
Maybe a warning? do we have those?

2024-08-01 12:18 UTC, sapirshuker commented on Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
> +        return_error("Discovery Service URL is not valid, The URL suffix should be taxii or taxii2")
Add debug logs

2024-08-06 10:12 UTC, merged