fix fetch-incidents returns duplicates bug
demisto/content pull request #35424
Opened 2024-07-15 10:37 UTC by YaelShamai

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39390)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests
- [x] Documentation

2024-07-15 11:53 UTC, RosenbergYehuda requested changes

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    # therefor we dedup alerts that have the backend_timestamp of the last alert in the last run.
```suggestion
   # Alerts may be created with the same backend_timestamp. Therefore, we deduplicate alerts that have the same # backend_timestamp as the last alert we saved in the previous run.
```

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    last_backend_timestamp = response['results'][-1]['backend_timestamp']
I don't like the "backend" in the variable name, maybe change to "last_fetched_alert_timestamp".

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    def get_backend_timestamp(alert):
I don't like one-liner functions.

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    # alert ids that have that backend_timestamp (need to be deduped in the next run).
```suggestion
    # All IDs of alerts that share the same timestamp as the last one.
```

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
> +  additionalinfo: Note, due to duplicates alert that the API retreives, there might be less alerts than the set limit.
```suggestion
  additionalinfo: Note: If the API returns duplicates, we will drop them, causing the total number of alerts fetched to potentially be fewer than the set limit.
```

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    from more_itertools import map_reduce
this should be on the top of the file

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    last_fetched_alerts_ids = last_run.get('last_fetched_alerts_ids', '')
```suggestion
    last_fetched_alerts_ids = last_run.get('last_fetched_alerts_ids', [])
```

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    alert_ids_grouped_by_backend_timestamp = map_reduce(response['results'], get_backend_timestamp)
What happens if the response is empty?

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    last_backend_timestamp = response['results'][-1]['backend_timestamp']
here too:
What happens if the response is empty?

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    alerts_ids_to_save = [alert['id'] for alert in alert_ids_grouped_by_backend_timestamp[last_backend_timestamp]]
here too

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
> +    res = {'last_fetched_alert_create_time': alert_create_date, 'last_fetched_alerts_ids': alerts_ids_to_save}
Make sure if the response was empty, i don't want the last run to change

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
> +        - Running 'fetch-incidents' command in the second time (there is a last_run value).
```suggestion
        - When the fetch is running for the second cycle (there is an existing last_run to use).
```

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
> +        - The fetch_incidents fun returns the right incidents.
Please add an explanation: "should drop the duplicates and return only these".
please note the typo "fun"

2024-07-15 11:53 UTC, RosenbergYehuda commented on Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_35.md
> +- Fixed a bug in the **fetch-incidents** which used to return duplicate alerts.
```suggestion
- Fixed an issue in the **fetch-incidents** which used to return duplicate alerts.
```

2024-07-15 12:02 UTC, RosenbergYehuda commented
Great job @YaelShamai !!

2024-07-16 06:36 UTC, ShirleyDenkberg commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
> +  additionalinfo: Note, If the API returns duplicates, we will drop them, causing the total number of alerts fetched to potentially be fewer than the set limit.
```suggestion
  additionalinfo: If the API returns duplicates, the duplicates will be dropped, causing the total number of alerts fetched to potentially be fewer than the set limit.
```

2024-07-16 06:36 UTC, ShirleyDenkberg commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md
> +Note, If the API returns duplicates, we will drop them, causing the total number of alerts fetched to potentially be fewer than the set limit.
```suggestion
Note: If the API returns duplicates, the duplicates will be dropped, causing the total number of alerts fetched to potentially be fewer than the set limit.
```
This is really not a troubleshooting issue. Not sure it belongs under a Troubleshooting heading.  It's just a Note.  Perhaps it belongs with **fetch-incidents**.

2024-07-16 06:36 UTC, ShirleyDenkberg commented on Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_35.md
> +- Fixed an issue in the **fetch-incidents** which used to return duplicate alerts.
```suggestion
Fixed an issue in the **fetch-incidents** which used to return duplicate alerts.
```

2024-07-16 06:37 UTC, ShirleyDenkberg commented
@RosenbergYehuda Doc review completed.

2024-07-16 09:07 UTC, RosenbergYehuda approved these changes
Awesome!!

2024-07-16 10:40 UTC, merged