fix cb eedr testplaybook
demisto/content pull request #35542
Opened 2024-07-22 05:19 UTC by YaelShamai

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-07-28 06:27 UTC, ShirleyDenkberg commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
> +- Carbon Black Enterprise EDR process search with polling test
```suggestion
- Carbon Black Enterprise EDR process search with polling Test
```

2024-07-28 06:27 UTC, ShirleyDenkberg commented on Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_37.md
> +- Fixed an issue in the **cb-list-alerts** command witch used to return an 500 error.
```suggestion
Fixed an issue with the **cb-list-alerts*** command that used to return an 500 error.
```
Why did it return a 500 error?  What was the problem?

2024-07-28 06:28 UTC, ShirleyDenkberg commented
@sapirshuker Doc review completed.

2024-08-01 09:18 UTC, JasBeilin requested changes
Nice!

2024-08-01 09:18 UTC, JasBeilin commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
> +        Then:
lets clarify

2024-08-01 09:18 UTC, JasBeilin commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
> +        {'criteria': {'event_id': [None], 'process_hash': ['63d423ea882264dbb157a965c200306212fc5e1c6ddb8cbbb0f1d3b51ecd82e6'],
lets check for None or []

2024-08-01 09:18 UTC, JasBeilin commented on Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
> +    assert http_request.call_args.kwargs['json_data']['criteria']['event_id'] == [123]
lets remove

2024-08-01 09:18 UTC, JasBeilin commented on Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_37.md
> +- Fixed an issue in the ***cb-eedr-process-search*** command that failed when specifying an *event_id* argument.
```suggestion
- Fixed an issue where ***cb-eedr-list-alerts*** command failed if *start* and *end* arguments were not provided.
- Fixed an issue where ***cb-eedr-process-search*** command failed if *event_id* argument was specified.
```

2024-08-01 09:18 UTC, JasBeilin commented on Packs/CarbonBlackEnterpriseEDR/TestPlaybooks/Carbon_Black_Enterprise_EDR_Test.yml
> +        simple: ${watchListId}
Due to not wanting to break BC for keys in different case (upper/ lower) to avoid duplictions.

2024-08-01 09:18 UTC, JasBeilin commented on Tests/conf.json
> -            "instance_names": "legacy_context_output",
revert

2024-08-01 09:18 UTC, JasBeilin commented on Tests/conf.json
> -            "memory_threshold": 100,
revet please

2024-08-01 09:18 UTC, JasBeilin commented on Tests/conf.json
> -            "instance_names": "legacy_context_output",
revert

2024-08-01 09:18 UTC, JasBeilin commented on Tests/conf.json
> +            "timeout": 700,
revert

2024-08-01 09:18 UTC, JasBeilin commented on Tests/conf.json
> -        },
revert

2024-08-01 09:18 UTC, JasBeilin commented on Tests/conf.json
> -            "fromversion": "6.9.0"
revet

2024-08-01 09:18 UTC, JasBeilin commented on Tests/conf.json
Please make sure to include only our changes.

2024-08-04 05:51 UTC, JasBeilin approved these changes
Great!

2024-08-04 08:32 UTC, merged