Get status of an asset of Kenna
demisto/content pull request #35614
Opened 2024-07-26 11:18 UTC by anrmgft

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
We add a new command to Kenna that get the status of an asset.

## Must have
- [ ] Tests
- [ ] Documentation

2024-07-26 11:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=35614) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=35614) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=35614) it.</sub>

2024-07-26 11:25 UTC, anrmgft commented
![image](https://github.com/user-attachments/assets/35290b87-3460-49a9-aa87-e60f697f92f6)

2024-07-31 11:10 UTC, samuelFain requested changes
@anrmgft Thank you for your contribution!
Please see my comments.

Also, your PR seem to be missing some necessary changes to files in this Pack:
1.  `Packs/Kenna/Integrations/KennaV2/KennaV2.yml` - describing the new command you add and its arguemnts (see more [here](https://xsoar.pan.dev/docs/integrations/yaml-file)).
2. A Unit-Test for the new command in `Packs/Kenna/Integrations/KennaV2/KennaV2_test.py`.
3. The command description in and examples in `Packs/Kenna/Integrations/KennaV2/README.md` (see more [here](https://xsoar.pan.dev/docs/documentation/readme_file)).
4. Also, the Pack version needs to be bumped.

See the full contribution guide [here](https://xsoar.pan.dev/docs/contributing/contributing).

For any issues, I'm available in Slack's DFIR or by email at sfainberg@paloaltonetworks.com

2024-08-15 07:46 UTC, samuelFain commented
Hi @anrmgft,
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue.
Thanks again.

2024-08-15 07:46 UTC, closed without merging