EXPANDR-9478 deprecate integrations, scripts and playbooks
demisto/content pull request #35628
Opened 2024-07-29 05:51 UTC by capanw

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-9478

## Description
Deprecating Ev1 integrations, playbooks and scripts.

## Must have
- [ ] Tests
- [ ] Documentation

2024-07-29 09:03 UTC, ssokolovich reviewed
Please leave the old descriptions\comments in place and add the "Deprection" sentence at the top.

2024-07-29 19:29 UTC, BigEasyJ requested changes
@ShirleyDenkberg please review

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. Use Xpanse - Alert Handler playbook.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. Use CortexXpanse integration instead.
```suggestion
Deprecated. Use CortexXpanse integration instead.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. Use CortexXpanse integration instead.
```suggestion
Deprecated. Use CortexXpanse integration instead.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:29 UTC, BigEasyJ commented on Packs/ExpanseV2/ReleaseNotes/1_10_56.md
> +- Deprecated. No available replacement.
```suggestion
Deprecated. No available replacement.
```

2024-07-29 19:38 UTC, BigEasyJ commented
@capanw it might be worth it to add references to the [Cortex Xpanse](https://xsoar.pan.dev/docs/reference/integrations/cortex-xpanse) and [Feed](https://xsoar.pan.dev/docs/reference/integrations/xpanse-feed) content docs in the release notes when specifying what to use like the [Xpanse Alert - Handler playbook](https://xsoar.pan.dev/docs/reference/playbooks/xpanse---alert-handler)

@ssokolovich just to note:

- This pack has been replaced by [CortexXpanse](https://github.com/demisto/content/tree/master/Packs/CortexXpanse) pack.
- The APIs in these integrations no longer work and have been deprecated.
- We have worked internally and externally to gather information about what customers use today from this pack to port over to the EV2 pack.

2024-07-29 23:04 UTC, capanw commented
@BigEasyJ, Thank you for adding those comment. Updated with provided suggestion.

2024-07-29 23:05 UTC, capanw commented
@ssokolovich Re-added description along with deprecated messages.

2024-07-30 07:17 UTC, ShirleyDenkberg commented on Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
> +  The Xpanse integration for Cortex XSOAR leverages the Expander API to create incidents from Xpanse issues. It also leverages Xpanse's unparalleled view of the Internet to enrich IPs, domains and ce
```suggestion
  The Xpanse integration for Cortex XSOAR leverages the Expander API to create incidents from Cortex Xpanse issues. It also leverages Cortex Xpanse's unparalleled view of the Internet to enrich IPs, domains and certificates using information from assets discovered by Cortex Xpanse Expander and risky flows detected by Cortex Xpanse Behavior.
```

2024-07-30 07:17 UTC, ShirleyDenkberg commented on Packs/ExpanseV2/Playbooks/playbook-Expanse_Find_Cloud_IP_Address_Region_and_Service.yml
> +  Subplaybook for Expanse Enrich Cloud Assets subplaybook. This playbook
```suggestion
  Sub-playbook for Expanse Enrich Cloud Assets sub-playbook. This playbook
```

2024-07-30 07:18 UTC, ShirleyDenkberg commented
@ssokolovich @BigEasyJ @israelpoli @MLainer1 Doc review completed.

2024-07-30 07:32 UTC, ssokolovich commented
> @capanw it might be worth it to add references to the [Cortex Xpanse](https://xsoar.pan.dev/docs/reference/integrations/cortex-xpanse) and [Feed](https://xsoar.pan.dev/docs/reference/integrations/xpanse-feed) content docs in the release notes when specifying what to use like the [Xpanse Alert - Handler playbook](https://xsoar.pan.dev/docs/reference/playbooks/xpanse---alert-handler)
> 
> @ssokolovich just to note:
> 
> * This pack has been replaced by [CortexXpanse](https://github.com/demisto/content/tree/master/Packs/CortexXpanse) pack.
> * The APIs in these integrations no longer work and have been deprecated, therefore many playbooks and scripts do not work as well.
> * The new APIs have had significant changes to where some features can not port over.
> * We have worked internally and externally to gather information about what customers use today from this pack to port over to the EV2 pack.

I'm with you 100% - the only reason why I asked that is if someone would like to use that script in the future or even using that today and want to understand what the script/playbook does :) Since the files will remain in our repo, I want to make sure we have all the required info about them.

2024-07-30 18:55 UTC, capanw commented
Hello @MLainer1 @ShirleyDenkberg @israelpoli, thank you for reviewing. Updated with suggestions provided. Thanks.

2024-07-30 22:11 UTC, israelpoli commented
Hi @capanw looks good, I'll take it to the next step hoping to merge it to master soon

thanks 🙏

2024-07-30 22:11 UTC, israelpoli approved these changes

2024-07-30 22:12 UTC, merged