Add new script to convert json to html table
demisto/content pull request #35633
Opened 2024-07-29 08:39 UTC by nikstuckenbrock

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Adds a new community script to convert a JSON object to a HTML table. Depends on [this](https://github.com/demisto/dockerfiles/pull/29877) PR.

## Must have
- [X] Tests
- [X] Documentation

2024-07-31 08:06 UTC, nikstuckenbrock commented
@samuelFain Is there something i can do to fix the run validations step?

2024-07-31 12:42 UTC, samuelFain requested changes
> @samuelFain Is there something i can do to fix the run validations step?

Hi @nikstuckenbrock! The PR looks great!
There does seem to be an issue with the `demisto/py3-native` docker image, but its something we need to handle on our end.
The `demisto/py3-tools:1.0.0.105909` from https://github.com/demisto/dockerfiles/pull/29877 passes all the checks and we should be good to merge.
As usual, please send me a demo screen recording as usual so we can advance.

2024-07-31 13:33 UTC, nikstuckenbrock commented
Same procedure as every PR @samuelFain 😄 [Here](https://drive.google.com/file/d/1P-tGS2TDIJ9_XwTQZ_ECSw2kigUKgIfY/view?usp=sharing) you go.

2024-08-05 10:50 UTC, samuelFain approved these changes

2024-08-05 10:50 UTC, merged