feat: Adding integration
demisto/content pull request #35727
Opened 2024-08-01 14:18 UTC by ronh1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Hey!
This integration contains old and new commands. Note that we keep the old command context outputs, and the new XSOAR conventions not align them. You can watch it in the attached design.

## Must have
- [ ] Tests
- [ ] Documentation

2024-08-04 09:02 UTC, thefrieddan1 requested changes
Nice professional work.
I realy like the validate authentication decorator.
Please fill in the missing Release Notes Readme and breaking changes json.
Thanks

2024-08-06 08:53 UTC, thefrieddan1 commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
> +    domain = args["domain"]
Yes please.

2024-08-06 12:08 UTC, ShirleyDenkberg commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
> +          description: Standard deviation of the amount of time set that DNS records should be cached.
```suggestion
          description: Minimum amount of time that DNS records should be cached.
          type: Unknown
        - contextPath: Domain.DNSHistory.TtlsMax
          description: Maximum amount of time that DNS records should be cached.
          type: Unknown
        - contextPath: Domain.DNSHistory.TtlsMean
          description: Average amount of time that DNS records should be cached.
          type: Unknown
        - contextPath: Domain.DNSHistory.TtlsMedian
          description: Median amount of time that DNS records should be cached.
          type: Unknown
        - contextPath: Domain.DNSHistory.TtlsStddev
          description: Standard deviation of the amount of time that DNS records should be cached.
```

2024-08-06 12:08 UTC, ShirleyDenkberg commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
> +          type: Unknown
```suggestion
          description: Whether an MX query for this domain name has been seen.
          type: Boolean
        - contextPath: Domain.DNSHistory.NonRoutable
          description: Whether one of the IPs is in a reserved, non-routable IP range.
          type: Boolean
        - contextPath: Domain.DNSHistory.FfCandidate
          description: Whether the domain name looks like a candidate for fast flux. This does not necessarily mean the domain is in fast flux, but rather that the IP address the domain resolves to changes rapidly.
          type: Boolean
```

2024-08-06 12:08 UTC, ShirleyDenkberg commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
> +          type: Unknown
```suggestion
          description: True if the requested domain is a subdomain of another.
          type: Boolean
```

2024-08-06 12:08 UTC, ShirleyDenkberg commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
> +          description: "Enter an IP Address:."
```suggestion
          description: An IP address.
```

2024-08-06 12:08 UTC, ShirleyDenkberg commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
> +          description: Limit fetched results, removing limit can fetch big amount of results into context.
```suggestion
          description: Limit fetched results. Removing the limit can fetch a large amount of results into context.
```

2024-08-06 12:08 UTC, ShirleyDenkberg commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_description.md
> +   - Click **Create** to generate the API key and secret.
```suggestion
   Access your Cisco Umbrella account dashboard.

2. **Navigate to API Keys:**
   Click **Investigate** in the menu.

3. **Create New Token:**
   a. Locate and click **API Keys**.
   b. Click **CREATE NEW TOKEN**.
   c. Provide a **Title** for your token (e.g., "Cortex XSOAR Integration").
   d. Click **Create** to generate the API key and secret.
```

2024-08-06 12:08 UTC, ShirleyDenkberg commented on Packs/Cisco-umbrella/ReleaseNotes/2_0_0.md
> +- Updated the Docker image to: *demisto/python3:3.10.12.66339*.
```suggestion
- **Breaking Change**: Improved implementation of the DBotScore calculation. The *status* field now takes precedence over the *security_rank2* field.
- Removed 2 outputs from the ***umbrella-domain-categorization*** command:
     - Domain.Malicious.Vendor
     - Domain.Malicious.Description
- Added 12 commands:
    - ***umbrella-get-domain-risk-score***
    - ***umbrella-list-domain-related-resources***
    - ***umbrella-list-name-related-resource***
    - ***umbrella-list-raw-related-resource***
    - ***umbrella-list-domain-subdomian***
    - ***umbrella-get-ip-bgp***
    - ***umbrella-get-asn-bgp***
    - ***umbrella-get-domain-whois-history***
    - ***umbrella-get-nameserver-whois***
    - ***umbrella-get-email-whois***
    - ***umbrella-get-regex-whois***
    - ***umbrella-get-top-most-seen-domain***
- Removed 3 commands:
    - ***umbrella-get-domain-classifiers***
    - ***umbrella-domain-dns-history***
    - ***umbrella-ip-dns-history***
- Updated the Docker image to: *demisto/python3:3.10.12.66339*.
```

2024-08-06 12:10 UTC, ShirleyDenkberg commented
@thefrieddan1 @qfortress-dev Doc review completed.
@ronh1 After implementing my comments/edits, please regenerate the integration readme.

2024-08-06 12:39 UTC, ronh1 commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
> +      description: This contains multiple scores or security features, each of which can be used to determine relevant datapoints to build insight on the reputation or security risk posed by the site
This command is deprecated.

2024-08-06 14:41 UTC, ronh1 commented on Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
> +        client.authenticate()
Yes, it will throw an exception with an error message

2024-08-25 07:25 UTC, thefrieddan1 approved these changes

2024-08-25 08:59 UTC, merged