Xql query engine
demisto/content pull request #35749
Opened 2024-08-04 11:58 UTC by tcarmeli1

## Status
- [x] Ready

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10975

## Description
- Create CoreXQLApiModule.
- Update XQLQueryingEngine to use CoreXQLApiModule.
- Create CortexCoreXQLQueryEngine which use CoreXQLApiModule

2024-08-06 19:58 UTC, jbabazadeh requested changes
Great work !!

2024-08-06 19:58 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
> +    return ','.join(f'"{item}"' for item in list_of_args)
```suggestion
    list_of_args = string_of_argument.split(',') if string_of_argument else ['']
    return ','.join(f'"{item}"' for item in list_of_args)
```

2024-08-06 19:58 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
> +    if not file_sha256_list:
its already required no?

2024-08-06 19:58 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/CoreXQLApiModule/README.md
please add readme as other apimodule have

2024-08-06 19:58 UTC, jbabazadeh commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
add troubleshoot section as we talked

2024-08-06 19:58 UTC, jbabazadeh commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +- No tests
add test playbook?

2024-08-06 19:58 UTC, jbabazadeh commented on Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_test.py
> +    response = CoreXQLApiModule.wrap_list_items_in_double_quotes(input_arg)
why not using the XQLQueringEngine?

2024-08-07 07:23 UTC, tcarmeli1 commented on Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
> +FORWARD_USER_RUN_RBAC = is_xsiam() and is_demisto_version_ge(version=RBAC_VALIDATIONS_VERSION,
done

2024-08-07 08:05 UTC, tcarmeli1 commented on Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
> +    if not file_sha256_list:
yes- deleted it

2024-08-07 08:14 UTC, tcarmeli1 commented on Packs/ApiModules/Scripts/CoreXQLApiModule/README.md
added

2024-08-07 08:42 UTC, tcarmeli1 commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
added:
## Troubleshooting

1. To use this integration, the machine must be an XSIAM machine with version 8.6.0-992980 or higher.
2. When using a query with more than 1000 results, the XSIAM version must be at least 8.7.0-1230614.
As a result, if the XSIAM version is lower than the mentioned version, please set the limit to 1000 or fewer.

2024-08-07 08:56 UTC, tcarmeli1 commented on Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_test.py
> +    response = CoreXQLApiModule.wrap_list_items_in_double_quotes(input_arg)
changed them all

2024-08-07 10:21 UTC, tcarmeli1 commented on Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
> +        if response_data_type == 'bin' and not ALLOW_RESPONSE_AS_BINARY:
done

2024-08-11 07:55 UTC, tcarmeli1 commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +- No tests
added

2024-08-11 08:27 UTC, tcarmeli1 commented on Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
> +    if not file_sha256_list:
yes- deleted in other places also

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results command.
```suggestion
      description: An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: remote IP.
```suggestion
      description: remote IP address.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: Remote IP.
```suggestion
      description: Local IP address.
      type: String
    - contextPath: PaloAltoNetworksXQL.NetworkConnection.results.action_remote_ip
      description: Remote IP address.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +    - description: 'event log ID to search. - Windows: Event ID of the event-log - Linux: For action_evtlog_source = AuthLog, one of the following: 0 = Unknown 1 = Successful Login 2 = Failed Login 3
```suggestion
    - description: 'Event log ID to search. - Windows: Event ID of the event-log - Linux: For action_evtlog_source = AuthLog, one of the following: 0 = Unknown 1 = Successful Login 2 = Failed Login 3 = Failed Password (Same as failed login, but should include a username) 4 = Logout.'
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: List of application IDs action, actual activities that took place and recorded by the agent.
```suggestion
      description: List of application IDs action. Actual activities that took place and recorded by the agent.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: List of application IDs action, actual activities that took place and recorded by the agent.
```suggestion
      description: List of application IDs action. Actual activities that took place and recorded by the agent.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: List of application IDs action, actual activities that took place and recorded by the agent.
```suggestion
      description: List of application IDs action. Actual activities that took place and recorded by the agent.
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: CID.
```suggestion
      description: Causality identifier (CID).
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +      description: CID.
```suggestion
      description: Causality identifier (CID).
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| query | String of the XQL query. By default up to 100 results are returned. To retrieve more results, enter a custom limit in the query. | Required |
```suggestion
| query | XQL query string. By default up to 100 results are returned. To retrieve more results, enter a custom limit in the query. | Required | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.ProcessEvent.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-resu
```suggestion
| PaloAltoNetworksXQL.ProcessEvent.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.DllModule.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results
```suggestion
| PaloAltoNetworksXQL.DllModule.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.NetworkConnection.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query
```suggestion
| PaloAltoNetworksXQL.NetworkConnection.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.Registry.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results
```suggestion
| PaloAltoNetworksXQL.Registry.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.EventLog.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results
```suggestion
| PaloAltoNetworksXQL.EventLog.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.DNS.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-results comma
```suggestion
| PaloAltoNetworksXQL.DNS.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.FileDropper.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-resul
```suggestion
| PaloAltoNetworksXQL.FileDropper.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.ProcessInstanceNetworkActivity.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-
```suggestion
| PaloAltoNetworksXQL.ProcessInstanceNetworkActivity.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.ProcessCausalityNetworkActivity.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr
```suggestion
| PaloAltoNetworksXQL.ProcessCausalityNetworkActivity.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.GenericQuery.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the  xdr-xql-get-query-resu
```suggestion
| PaloAltoNetworksXQL.GenericQuery.execution_id | String | An integer representing a unique ID of a successful XQL query execution. The execution_id value can be passed to the xdr-xql-get-query-results command. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.NetworkConnection.results.action_remote_ip | String | Remote IP. |
```suggestion
| PaloAltoNetworksXQL.NetworkConnection.results.action_local_ip | String | Local IP address. | 
| PaloAltoNetworksXQL.NetworkConnection.results.action_remote_ip | String | Remote IP address. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.FileDropper.results.causality_actor_remote_ip | String | remote IP. |
```suggestion
| PaloAltoNetworksXQL.FileDropper.results.causality_actor_remote_ip | String | remote IP address. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| event_id | event log ID to search. - Windows: Event ID of the event-log - Linux: For action_evtlog_source = AuthLog, one of the following: 0 = Unknown 1 = Successful Login 2 = Failed Login 3 = Fail
```suggestion
| event_id | Event log ID to search. - Windows: Event ID of the event-log - Linux: For action_evtlog_source = AuthLog, one of the following: 0 = Unknown 1 = Successful Login 2 = Failed Login 3 = Failed Password (Same as failed login, but should include a username) 4 = Logout. | Required | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.DNS.results.action_app_id_transitions | String | List of application IDs action, actual activities that took place and recorded by the agent |
```suggestion
| PaloAltoNetworksXQL.DNS.results.action_app_id_transitions | String | List of application IDs action. Actual activities that took place and recorded by the agent | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.ProcessInstanceNetworkActivity.results.action_app_id_transitions | String | List of application IDs action, actual activities that took place and recorded by the agent. |
```suggestion
| PaloAltoNetworksXQL.ProcessInstanceNetworkActivity.results.action_app_id_transitions | String | List of application IDs action. Actual activities that took place and recorded by the agent. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.ProcessCausalityNetworkActivity.results.action_app_id_transitions | String | List of application IDs action, actual activities that took place and recorded by the agent. |
```suggestion
| PaloAltoNetworksXQL.ProcessCausalityNetworkActivity.results.action_app_id_transitions | String | List of application IDs action. Actual activities that took place and recorded by the agent. | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.ProcessCausalityNetworkActivity.results.actor_causality_id | String | CID. |
```suggestion
| PaloAltoNetworksXQL.ProcessCausalityNetworkActivity.results.actor_causality_id | String | Causality identifier (CID). | 
```

2024-08-11 09:23 UTC, ShirleyDenkberg commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
> +| PaloAltoNetworksXQL.ProcessInstanceNetworkActivity.results.actor_causality_id | String | CID. |
```suggestion
| PaloAltoNetworksXQL.ProcessInstanceNetworkActivity.results.actor_causality_id | String | Causality identifier (CID). | 
```

2024-08-11 09:24 UTC, ShirleyDenkberg commented
@jbabazadeh Doc review completed.

2024-08-12 08:57 UTC, tcarmeli1 commented on Packs/Core/Integrations/CortexCoreXQLQueryEngine/CortexCoreXQLQueryEngine.yml
> +- display: Server URL (copy URL from Core - click ? to see more info.)
deleted

2024-08-20 11:25 UTC, tcarmeli1 commented on Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
> +    return ','.join(f'"{item}"' for item in list_of_args)
changed that

2024-09-01 05:54 UTC, jbabazadeh commented on Packs/Core/TestPlaybooks/Test_Playbook_-_XQL_Engine.yml
please add screenshot to the PR description

2024-09-01 07:09 UTC, tcarmeli1 commented on Packs/Core/TestPlaybooks/Test_Playbook_-_XQL_Engine.yml
added

2024-09-01 08:48 UTC, jbabazadeh approved these changes
well done! :)

2024-09-01 10:51 UTC, tcarmeli1 commented
Hi @yuvalbenshalom ,
Would appreciate your assistance with a force merge on this PR.
Explanation in this comment: https://jira-dc.paloaltonetworks.com/browse/CIAC-10975?focusedId=10409297&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-10409297
Thank you!

2024-09-04 11:32 UTC, merged