change picture
demisto/content pull request #35779
Opened 2024-08-07 06:23 UTC by YaelShamai

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Change SentinalOne integration's picture
## Must have
- [ ] Tests
- [ ] Documentation

2024-08-07 08:59 UTC, JasBeilin approved these changes
Lets add release notes.

2024-08-07 11:10 UTC, ShirleyDenkberg commented on Packs/SentinelOne/ReleaseNotes/3_2_29.md
> +- Changed the integration's picture
```suggestion
Changed the integration's picture
```

2024-08-07 11:10 UTC, ShirleyDenkberg commented
@JasBeilin Doc review completed.

2024-08-14 08:07 UTC, JasBeilin requested changes

2024-08-14 08:07 UTC, JasBeilin commented on Packs/SentinelOne/Integrations/SentinelOne/SentinelOne_image.png
change to v2 :)

2024-08-14 08:09 UTC, closed without merging