Exabeam sop add ap is ciac 10717
demisto/content pull request #35794
Opened 2024-08-07 22:46 UTC by YairGlik

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-08-14 18:04 UTC, jbabazadeh requested changes
Great work! 
please see my comment.
I just need to go over the test playbook and the unit test

2024-08-14 18:04 UTC, jbabazadeh commented on Packs/ExabeamSecurityOperationsPlatform/pack_metadata.json
> +        "Exabeam"
```suggestion    
    "itemPrefix": [
        "Exabeam"
```
i think the indentation not right

2024-08-14 18:04 UTC, jbabazadeh commented on Packs/ExabeamSecurityOperationsPlatform/TestPlaybooks/ExabeamSecurityOperationsPlatform-test.yml
>  id: ExabeamSecurityOperationsPlatform-test
please add a screenshot of the test playbook in the PR description

2024-08-15 12:46 UTC, YairGlik commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +            return _make_request()
I want to catch cases where the token has expired even though the time has not yet passed

2024-08-15 12:53 UTC, YairGlik commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +        return current_time_utc < (expiry_time_utc - TOKEN_EXPIRY_BUFFER)
🙏🏻

2024-08-15 13:00 UTC, YairGlik commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +    if not isinstance(cases, list):
Because the pre-commit falls on len(cases)} in mypy

2024-08-18 08:12 UTC, YairGlik commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +    if not isinstance(cases, list):
I added this because I get an error from mypy about len(cases):
Argument 1 to "len" has incompatible type "object"; expected "Sized"

2024-08-21 08:06 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +      description: A dictionary mapping attribute names to their values, For example:`{"attributeName":["val1", "val2"]}`.
```suggestion
      description: A dictionary mapping attribute names to their values, for example:`{"attributeName":["val1", "val2"]}`.
```

2024-08-21 08:06 UTC, ShirleyDenkberg commented on Packs/ExabeamSecurityOperationsPlatform/ReleaseNotes/1_1_0.md
> +- Add the new params:
```suggestion
- Added the following new parameters:
```

2024-08-21 08:08 UTC, ShirleyDenkberg commented
@jbabazadeh @altmannyarden @idovandijk Doc review completed.

2024-08-21 08:31 UTC, YairGlik commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
> +    if client.access_token and generic_search_command(client, {}, "case"):
Sometimes there is a token but the command doesn't work

2024-08-25 09:24 UTC, jbabazadeh reviewed
a few small comments

2024-08-25 11:34 UTC, YairGlik commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +      description: Order results by a specified field in ASC or DESC order, such as "riskScore ASC" or "riskScore DESC".
The default for sorting seems to be "caseCreationTimestamp DESC"

2024-08-25 13:06 UTC, YairGlik commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +      description: Order results by a specified field in ASC or DESC order, such as "riskScore ASC" or "riskScore DESC".
The default for sorting seems to be "caseCreationTimestamp DESC"

2024-09-01 17:45 UTC, jbabazadeh commented on Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
> +      description: Order results by a specified field. Defaults to ascending (ASC), for example, "riskScore". Use "DESC" for descending, for example, "riskScore DESC".
```suggestion
      description: Order results by a specified field. The default ordering is ascending (ASC). To sort in descending order, use "DESC" after the field, for example, "riskScore DESC"."
```

2024-09-03 07:12 UTC, jbabazadeh approved these changes
Great Job!

2024-09-03 10:19 UTC, merged