[DBotPredictURLPhishing] Fix mailto URLs fail with rasterize responses.
demisto/content pull request #35849
Opened 2024-08-13 06:46 UTC by jlevypaloalto

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40525)

## Description
Fixed an issue in which the response from `rasterize` for `mailto` URLs would not be parsed correctly as the `DBotPredictURLPhishing` filtered out all responses from `rasterize` in which the `Contents` key was a string and assumed all other responses were dictionaries, as was the case when this logic was written.
In the latest version of Rasterize, responses for `mailto` URLs are returned in this format:
```python
{
  'Type': 11,
   'ContentsFormat': 'json',
   'Contents': None,
   'HumanReadable': '<messsage>',
   'EntryContext': {},
   'IndicatorTimeline': [],
   'IgnoreAutoExtract': False,
   'Note': False,
   'Relationships': []
}
```
In this case, the `Contents` key contains a `NoneType` causing the error: `AttributeError: 'NoneType' object has no attribute 'get'`
In this PR, the key `HumanReadable` is used when the `Contents` key is "falsy" and all non-dictionary responses are dealt with as errors.

## Must have
- [ ] Tests
- [ ] Documentation

2024-08-13 10:20 UTC, sapirshuker reviewed
Please see my comment

2024-08-13 10:39 UTC, jlevypaloalto commented on Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
> +        if not isinstance(res, dict)
yes

2024-08-14 15:28 UTC, JudahSchwartz requested changes
lets add a lot of test cases in the test playbook

2024-08-15 09:13 UTC, JudahSchwartz approved these changes

2024-08-15 09:25 UTC, merged