DeCYFIR IoC Integration bug fixes
demisto/content pull request #35900
Opened 2024-08-15 12:53 UTC by mohanreddy2121

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-08-18 15:19 UTC, adi88d requested changes
Hi @mohanreddy2121
Thank you for your contribution!
It looks great!
Please bump the pack version in the pack_metadata.json file and add notes describing your changes to a new Release Notes file.
To do that, please run the `demisto-sdk update-release-notes` command - for more information please see: https://xsoar.pan.dev/docs/concepts/demisto-sdk#update-release-notes.

and also revert the package-lock.json file

2024-08-19 08:18 UTC, mohanreddy2121 commented
Thanks @adi88d , I will update soon

2024-08-19 11:24 UTC, mohanreddy2121 commented
@adi88d , When i use this command (demisto-sdk update-release-notes -i Packs/DeCYFIR/) nothing is updated. 
can you please let me know any other steps to do.

[2024-08-19 15:08:57,308] [INFO] Either no changes were found in DeCYFIR pack or the changes found should not be documented in the release notes file.
If relevant changes were made, please commit the changes and rerun the command.

2024-08-19 13:37 UTC, adi88d commented on Packs/DeCYFIR/Integrations/decyfiriocs/decyfiriocs.yml
>    dockerimage: demisto/python3:3.10.13.84405
Please change to the latest docker:

dockerimage: demisto/python3:3.11.9.107902

2024-08-19 14:13 UTC, mohanreddy2121 commented
Hi @adi88d , I clear all errors but only pre commit options cannot clear it out

2024-08-20 11:07 UTC, adi88d commented
@mohanreddy2121 We have some internal issue with the docker image creation now, I will merge this pull request when it resolved. Thanks

2024-08-20 11:37 UTC, mohanreddy2121 commented
I changed the docker image version demisto/python3:3.11.9.107902
Please check it out once let me know if any thing need to change.

2024-08-20 14:37 UTC, adi88d commented
Thanks @mohanreddy2121 , just revert the `package-lock.json` file

2024-08-21 05:04 UTC, mohanreddy2121 commented
Hi @adi88d, Thanks for update. Is anything I need to update. My side code part fixes are done, we can ready release it prod. 

I have doubt for next PR, We want develop a new version v2 for both Threat intel and xsoar, can you please let us know how we need to do the new version v2?

2024-08-21 09:06 UTC, mohanreddy2121 commented
Sure @adi88d, will do that and thanks for sharing

2024-08-21 12:42 UTC, adi88d approved these changes
Nice!

2024-08-21 12:43 UTC, merged