[Symantec MSS] mypy
demisto/content pull request #35954
Opened 2024-08-20 14:02 UTC by shmuel44

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-08-26 08:54 UTC, dorschw approved these changes

2024-08-26 11:13 UTC, kobymeir requested changes

2024-08-26 11:13 UTC, kobymeir commented on Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.py
> +    incident["name"] = "Incident: {} ({})".format(event["IncidentNumber"], event["Classification"])
why format and not f-string?

2024-08-27 12:19 UTC, shmuel44 commented on Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.py
> +    incident["name"] = "Incident: {} ({})".format(event["IncidentNumber"], event["Classification"])
ruff don't fixed it

2024-08-27 13:39 UTC, kobymeir approved these changes

2024-08-28 09:26 UTC, shmuel44 commented
@kobymeir need to force merge (failing on IN140)

2024-08-28 09:37 UTC, merged