Xsup 39289 auto resolve
demisto/content pull request #36028
Opened 2024-08-26 14:46 UTC by maimorag

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

2024-09-04 08:37 UTC, YuvHayun approved these changes
Nice catch!

2024-09-04 13:28 UTC, eyalpalo requested changes

2024-09-04 13:28 UTC, eyalpalo commented on Packs/Core/ReleaseNotes/3_0_59.md
> +- Updated the CoreIRApiModule with support for for status ***resolved_auto_resolve***  close-reason in XSOAR-XDR close-reasons mapping.
```suggestion
- Updated the CoreIRApiModule to support status ***resolved_auto_resolve***  close-reason in XSOAR-XDR close-reasons mapping.
```

2024-09-04 13:28 UTC, eyalpalo commented on Packs/Core/ReleaseNotes/3_0_59.md
> +- Updated the CoreIRApiModule with support for for status ***resolved_auto_resolve***  close-reason in XSOAR-XDR close-reasons mapping.
Same as above

2024-09-04 13:28 UTC, eyalpalo commented on Packs/CortexXDR/ReleaseNotes/6_1_68.md
> +- Added support for status ***resolved_auto_resolve***  close-reason in XSOAR-XDR close-reasons mapping.
Same as above

2024-09-04 13:28 UTC, eyalpalo commented on Packs/ctf01/ReleaseNotes/1_0_27.md
> +- Updated the CoreIRApiModule with support for for status ***resolved_auto_resolve***  close-reason in XSOAR-XDR close-reasons mapping.
Same as above

2024-09-05 12:37 UTC, eyalpalo approved these changes

2024-09-05 13:05 UTC, merged