[Marketplace Contribution] -  EXPANDR-2805 - Update Get VM Details Command
demisto/content pull request #36048
Opened 2024-08-27 18:57 UTC by BigEasyJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-2805](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-2805)

## Description

- Updated the `azure-vm-get-instance-details` command to add `Tags` from a VM instance to alert context.

## Must have
- [x] Tests
- [x] Documentation

2024-08-28 05:27 UTC, JasBeilin requested changes
Hi @BigEasyJ , Thank you for the contribution!
Please check my comments and send a demo video so we can move forward.

2024-08-28 05:27 UTC, JasBeilin commented on Packs/AzureCompute/Integrations/AzureCompute_v2/README.md
> +| Azure.Compute.Tags | Unknown | Tags associated with the VM. |
```suggestion
| Azure.Compute.Tags | string | Tags associated with the VM. | 
```

2024-08-28 05:27 UTC, JasBeilin commented on Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/get_vm_command.json
> +                "vmAgentVersion": "2.11.1.12"
This is being recognized as a secret. It can be ignored by showing in the .secret-ignore file in the pack.

2024-09-03 07:46 UTC, BigEasyJ commented
@JasBeilin I have updated the PR with your comments, however I don't know what we should demo for this since it just extends an existing field from raw to context. Most of the change in testing.

2024-09-03 09:12 UTC, thefrieddan1 approved these changes

2024-09-03 10:11 UTC, JasBeilin approved these changes
Great!

2024-09-03 10:17 UTC, merged