Add Dragos Platform modeling rule
demisto/content pull request #36056
Opened 2024-08-28 09:15 UTC by yasta5

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8434)

## Description
Add modeling rule for Dragos Platform logs.

2024-10-10 09:27 UTC, OBavly requested changes

2024-10-10 09:27 UTC, OBavly commented on Packs/Dragos_Platform/pack_metadata.json
Looks good - Let's just add keywords and tags

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +- Log Normalization - XDM mapping for key event types.
```suggestion
Log Normalization - XDM mapping for key event types.
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +1. Logon to Dragos as an administrator.
```suggestion
1. Log in to Dragos as an administrator.
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +3. Go to the **SERVERS** tab and click on **+ ADD SERVER**.
```suggestion
3. Go to the **SERVERS** tab and click **+ ADD SERVER**.
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +    | Hostname/IP                           | Enter the Broker VM IP Address.                                                       |
```suggestion
    | Hostname/IP                           | Enter the Broker VM IP address.                                                       |
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +    | TLS Protocol Configuration (optional) | If protocol set to TLS, set all the relevant values.                                  |
```suggestion
    | TLS Protocol Configuration (optional) | If protocol is set to TLS, set all the relevant values.                                  |
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +7. Click on **Next: SET TEMPLATE**.
```suggestion
7. Click **Next: SET TEMPLATE**.
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +6. Check the "Use newline delimiter for TCP and TLS streams" checkbox under **Message Delimiter**.
```suggestion
5. Check the **RFC 5424 Modern Syslog** checkbox under **Message Format**.
6. Check the **Use newline delimiter for TCP and TLS streams** checkbox under **Message Delimiter**.
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +    | `Protocol`   | Select **UDP** for the default forwarding, **TCP** or **Secure TCP** (depends on the protocol you configured in Dragos Platform configuration). |
```suggestion
    | `Protocol`   | Select **UDP** for the default forwarding, **TCP** or **Secure TCP** (depends on the protocol you configured in the Dragos Platform configuration). | 
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +    | `Port`       | Enter the syslog service port that Cortex XSIAM Broker VM should listen on for receiving forwarded events from Dragos Platform.                 |
```suggestion
    | `Port`       | Enter the syslog service port that Cortex XSIAM Broker VM should listen on for receiving forwarded events from the Dragos Platform.                 |
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented on Packs/Dragos_Platform/README.md
> +    | `Product`    | Enter platform.                                                                                                                                 |
```suggestion
    | `Vendor`     | Enter **dragos**.                                                                                                                                   |
    | `Product`    | Enter **platform**.                                                                                                                                 |
```

2024-10-10 10:24 UTC, ShirleyDenkberg commented
@OBavly Doc review completed.

2024-10-13 08:19 UTC, yasta5 commented on Packs/Dragos_Platform/pack_metadata.json
Added

2024-10-13 20:07 UTC, OBavly approved these changes

2024-10-13 20:26 UTC, merged