Shodan collector ciac 11405
demisto/content pull request #36333
Opened 2024-09-15 14:45 UTC by YairGlik

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [CIAC-11405](https://jira-dc.paloaltonetworks.com/browse/CIAC-11405)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-09-22 18:39 UTC, jbabazadeh requested changes
Great work!! please see my comments and please add more unit test to match the coverage that needed.

2024-09-22 18:39 UTC, jbabazadeh commented on Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.py
> +    start_date = arg_to_datetime(last_run.get("start_date"))
i prefer to call it last_fetch_time or something like that.

2024-09-22 18:39 UTC, jbabazadeh commented on Packs/Shodan/Integrations/Shodan_v2/Shodan_v2_description.md
> +Integration description:
put this first and add titles  (remove the integration description)

2024-09-23 09:12 UTC, YairGlik commented on Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.yml
> +      defaultValue: "3 days ago"
According to the documentation - it brings me the list of all active alerts in the account,
And I filter it in the code

2024-09-26 10:35 UTC, jbabazadeh approved these changes
Great! just small comments. pleas ask doc review from @ShirleyDenkberg

2024-09-26 10:35 UTC, jbabazadeh commented on Packs/Shodan/Integrations/Shodan_v2/README.md
> +Shodan is a search engine for Internet-connected devices. Unlike traditional search engines that index websites, Shodan indexes information about the devices connectedש to the internet, such as serve
```suggestion
Shodan is a search engine for Internet-connected devices. Unlike traditional search engines that index websites, Shodan indexes information about the devices connected to the internet, such as servers, routers, webcams, and other IoT devices.
```

2024-09-26 10:35 UTC, jbabazadeh commented on Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.py
> +        return_error("Missing API key")
```suggestion
        return_error("Missing API key - You must provide API KEY parameter.")
```

2024-09-26 10:58 UTC, ShirleyDenkberg commented on Packs/Shodan/Integrations/Shodan_v2/README.md
> +    | Base url to Shodan API |  | True |
```suggestion
    | Base URL to Shodan API |  | True |
```

2024-09-26 10:58 UTC, ShirleyDenkberg commented on Packs/Shodan/Integrations/Shodan_v2/README.md
> +Once you have an API key you insert it into the API Key field and click the Test button.
```suggestion
Once you have an API key, you insert it into the *API Key* field and click the **Test** button.
```

2024-09-26 10:58 UTC, ShirleyDenkberg commented on Packs/Shodan/Integrations/Shodan_v2/Shodan_v2_description.md
> +Once you have an API key you insert it into the API Key field and click the Test button.
```suggestion
Once you have an API key you insert it into the *API Key* field and click the **Test** button.
```

2024-09-26 10:59 UTC, ShirleyDenkberg commented
@jbabazadeh Doc review completed.

2024-10-01 10:20 UTC, YairGlik commented
Hi @DeanArbel,
There were no tests before, and I added tests only for the functions I wrote. As a result, the coverage is now below 70%. Please force merge.

2024-10-08 12:48 UTC, merged