Update sec comp
demisto/content pull request #36385
Opened 2024-09-18 14:28 UTC by JudahSchwartz

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-09-19 10:48 UTC, dantavori approved these changes

2024-09-19 10:52 UTC, amshamah419 requested changes
This is potentially a big change. Moving to a new version of OS is sizable and should be done with care. It needs to be throughly tested. Was this requested by a customer?

2024-09-19 11:48 UTC, amshamah419 approved these changes

2024-09-22 10:58 UTC, JudahSchwartz commented on Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_6.md
> +- Updated the Docker image to: *demisto/pwsh-exchange:1.0.0.112381*.
```suggestion
- Updated the Docker image to: *demisto/pwsh-exchangev3:1.0.0.112382*.
```

2024-09-22 13:41 UTC, merged