New command in the Azure Storage Contaitner pack for blocking public access to containers
demisto/content pull request #36526
Opened 2024-09-26 07:38 UTC by yash-metron

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR introduces a new command in the Azure Storage Contaitner pack for blocking public access to Azure containers. Initially, I was using a custom script to implement public access prevention in my playbooks. However, following the suggestion by [@Michal Goldshtein](https://paloaltonetworks.enterprise.slack.com/team/WH8QAFMU0), this functionality has now been incorporated directly into the Azure Storage Contaitner pack. This will enable seamless usage of the public access block in various playbooks, reducing the need for custom scripts and improving efficiency.

## Must have
- [x] Tests
- [x] Documentation

2024-09-28 20:20 UTC, rshunim commented
Hi @yash-metron, thanks for your contribution.
At first, please upgrade the pack version and add a Release Note file.

2024-09-30 06:05 UTC, yash-metron commented
Hi @aaron1535 
We are getting these undefined errors from the previous code and not from the changes we have made.
It would be great if you could help me resolving these errors.
Attaching the screenshot of errors from the pre-commit. 
![image](https://github.com/user-attachments/assets/f8f31db2-cbc7-4f41-8b03-1640a0e842c1)

2024-10-01 06:34 UTC, yash-metron commented
Hi @aaron1535

2024-10-07 13:22 UTC, aaron1535 requested changes
Hi @yash-metron, 
Thank you again for your contribution.
Nice job!
Please pay attention to the required changes and then we can make a demo for the new command you added

2024-10-07 13:22 UTC, aaron1535 commented on Packs/AzureStorageContainer/pack_metadata.json
> +    "currentVersion": "2.0.0",
We should leave it with 1.0.23. Please run the `demisto-sdk update-release-notes` command again with the `-u revision` argument

2024-10-07 13:22 UTC, aaron1535 commented on Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer_test.py
> +    assert result.readable_output == expected_response
```suggestion
    expected_response = f"Public access to container '{container_name}' has been successfully blocked"
    assert result.readable_output == expected_response
```

2024-10-07 13:22 UTC, aaron1535 commented on Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer_description.md
> +For more information, see [Shared access keys](https://learn.microsoft.com/en-gb/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#regenerate-access-keys).
```suggestion
- For more information, see [Shared access keys](https://learn.microsoft.com/en-gb/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#regenerate-access-keys).

For more information, see [Managed identities for Azure resources](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview).
```

2024-10-07 13:29 UTC, aaron1535 commented on Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.yml
> +  required: false
Please add `additionalinfo` and `section` to this parameter.

2024-10-08 14:07 UTC, aaron1535 commented
Hi @yash-metron,
About the errors that you get from the pre-commit
the first one it's in your code. Just remove the unnecessary 'f' string
All other errors are because you deleted the `from CommonServerPython import *` import
If there is no specific reason why you deleted the import, please return it

2024-10-09 06:34 UTC, yash-metron commented on Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.py
> +        )
No it doesn't exist. It only returns response status and headers.

2024-10-09 08:59 UTC, aaron1535 commented on Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.py
> +        )
Okay, in that case you don't need to return the response.
I am trying to understand something in your condition. What is meant 
```
if response:
    message = f"Public access to container '{container_name}' has been successfully blocked"
else:
    message = f"Failed to block public access, Status code: {response.status_code}"
```
in the else scope you get the `response.status_code` **but there is no response**

2024-10-09 09:09 UTC, yash-metron commented
Hi @aaron1535 ,
Thanks for the review. I have made changes as per your suggestions.

2024-10-09 10:29 UTC, aaron1535 commented
Hi @yash-metron,
I see you are still having problems with the `pre-commit`
You can write me on Slack if you want

2024-10-09 11:20 UTC, yash-metron commented
> Hi @yash-metron, I see you are still having problems with the `pre-commit` You can write me on Slack if you want

Hi @aaron1535 I couldn't find you on Slack. Could you please share your Slack username so that we can connect there?

2024-10-09 11:21 UTC, yash-metron commented
> Hi @yash-metron, I see you are still having problems with the `pre-commit` You can write me on Slack if you want

2024-10-10 09:02 UTC, aaron1535 approved these changes

2024-10-10 09:06 UTC, merged