Splunk double quates bug
demisto/content pull request #36551
Opened 2024-09-29 12:34 UTC by eyalpalo

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39874)

## Description
Fixed an issue where double quotes were unnecessarily removed.

## Must have
- [ ] Tests
- [ ] Documentation

2024-10-08 09:17 UTC, ilappe requested changes
great work!!

2024-10-08 09:17 UTC, ilappe commented on Packs/SplunkPy/ReleaseNotes/3_1_39.md
> +- Fixed an issue where double quotes were unnecessarily removed.
please put more informative RN
it was related to drilldown etc.

2024-10-08 09:17 UTC, ilappe commented on Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
> +DRILLDOWN_REGEX = r'([^\s\$]+)\s*=\s*["]*(\$[^\s\$]+\$)["]*|"*(\$[^\s\$]+\$)"*'
as discussed
the `"` should be with the `?` 
and add the `\\`
something like that 
`([^\s\$]+)\s*=\s*"?(\$[^\s\$\\]+\$)"?|"?(\$[^\s\$\\]+\$)"?`

2024-10-08 14:00 UTC, dantavori approved these changes

2024-10-09 06:57 UTC, ilappe approved these changes
great!

2024-10-09 12:45 UTC, merged