Fixed an issue where caseless=true doesn't work on algorithm=literal.
demisto/content pull request #36590
Opened 2024-10-03 05:18 UTC by spearmin10

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
caseless=true doesn't work when using algorithm=literal.

## Must have
- [ ] Tests
- [ ] Documentation

2024-10-06 12:41 UTC, tcarmeli1 requested changes
Hi @spearmin10 ,
Thank you for your contribution!
Good work :)
I guess the type changes are due to pre-commit right?
Can you please reshare the video? i could not manage to log in.
Thank you!

2024-10-06 13:46 UTC, spearmin10 commented
> Hi @spearmin10 , Thank you for your contribution! Good work :) I guess the type changes are due to pre-commit right? Can you please reshare the video? i could not manage to log in. Thank you!

Hi @tcarmeli1,
Thank you for your review.

Yes, types were automatically changed by pre-commit.
The video link is here and shared for you. I think you should be able to access with PANW SSO login.

Video: https://paloaltonetworks.zoom.us/rec/play/cLi7btoTmCtkMD4MOxXjQnIGMAJuxkdGlsI0xlQUgXYof3sh-piViLilISs21_dUwE-O6Zcpwdt9nuyj.oYbQ_E41EUwgHjhb?autoplay=true
Passcode: @4tGtdsQ1

Thank you,

2024-10-07 08:11 UTC, tcarmeli1 commented
Hi @spearmin10 ,
I tried to log in to the video but i get an error for invalid passcode.
maybe can you please check again that the video details are correct?
Thank you so much!

2024-10-07 08:51 UTC, tcarmeli1 approved these changes

2024-10-07 08:58 UTC, ShirleyDenkberg commented on Packs/FiltersAndTransformers/ReleaseNotes/1_2_78.md
> +- Fixed an issue where caseless=true doesn't work on algorithm=literal.
```suggestion
Fixed an issue where caseless=true doesn't work on algorithm=literal.
```

2024-10-07 08:58 UTC, ShirleyDenkberg commented
@tcarmeli1 Doc review completed.

2024-10-07 09:06 UTC, tcarmeli1 approved these changes

2024-10-07 09:17 UTC, tcarmeli1 commented
Watched the demo video and approved it.

2024-10-07 10:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=36590) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=36590) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: spearmin10<br/>:x: tcarmeli1<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=36590) it.</sub>

2024-10-08 07:20 UTC, merged