Ciac 10972 zoom add user sso token revoke
demisto/content pull request #36725
Opened 2024-10-14 14:00 UTC by ilaredo

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [CIAC-10972](https://jira-dc.paloaltonetworks.com/browse/CIAC-10972)

## Description
Added new Zoom command to support DELETE /users/\{userId}/token

## Must have
- [x] Tests
- [x] Documentation

2024-10-14 18:49 UTC, ShirleyDenkberg commented on Packs/Zoom/Integrations/Zoom/README.md
> +To list all available users use `zoom-list-users` command.
```suggestion
To list all available users use the `zoom-list-users` command.
```

2024-10-14 18:49 UTC, ShirleyDenkberg commented on Packs/Zoom/Integrations/Zoom/Zoom.yml
> +    description: Revoke a user's Zoom SSO session if their account becomes compromised. Use the command zoom-list-users to get the user ID or user email.
```suggestion
    description: Revoke a user's Zoom SSO session if their account becomes compromised. Use the zoom-list-users command to get the user ID or user email.
```

2024-10-14 18:49 UTC, ShirleyDenkberg commented on Packs/Zoom/ReleaseNotes/1_6_14.md
> +  - ***zoom-delete-user-token***
```suggestion
Added the following command:
- ***zoom-delete-user-token***
```

2024-10-14 18:50 UTC, ShirleyDenkberg commented
@ilaredo Doc review completed.

2024-10-20 12:55 UTC, eyalpalo requested changes
Nice!

2024-10-20 12:55 UTC, eyalpalo commented on Packs/Zoom/Integrations/Zoom/Zoom.yml
> +    description: Revoke a user's Zoom SSO session if their account becomes compromised. Use the zoom-list-users command to get the user ID or user email.
```suggestion
    description: Revoke a user's Zoom SSO session. Use the zoom-list-users command to get the user ID or user email.
```

lets stick to the actual behavior of the command and not to the use case

2024-10-20 12:55 UTC, eyalpalo commented on Packs/Zoom/Integrations/Zoom/README.md
> +
Lets add a command run example

2024-10-21 12:21 UTC, eyalpalo approved these changes

2024-10-21 13:40 UTC, merged