Elasticsearch Feed - Generic Feed Type - Fixes
demisto/content pull request #36745
Opened 2024-10-15 14:38 UTC by ShacharKidor

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
relates: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-10-27 14:09 UTC, DeanArbel approved these changes
Looks good

2024-10-27 14:42 UTC, yuvalbenshalom requested changes
looks good. see my comment.

2024-10-27 14:42 UTC, yuvalbenshalom commented on Packs/FeedElasticsearch/ReleaseNotes/1_1_9.md
> +- Maintenance and stability enhancements.
```suggestion
```
no need.

2024-10-28 14:54 UTC, yuvalbenshalom approved these changes

2024-10-28 15:10 UTC, merged