[ASM] EXPANDR-10510 Updated ServiceNow playbook
demisto/content pull request #36897
Opened 2024-10-30 06:20 UTC by capanw

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[EXPANDR-10510](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-10510)

## Description
Updating ServiceNow playbook to add additional details to description.

## Must have
- [ ] Tests
- [ ] Documentation

2024-10-30 13:22 UTC, johnnywilkes commented
@ShirleyDenkberg, please review

2024-10-30 13:36 UTC, johnnywilkes requested changes
@capanw , not sure about that validation error.  I added some testing comments in the Jira, please take care and let me know if you have questions.

2024-10-30 13:39 UTC, johnnywilkes requested changes

2024-10-30 13:39 UTC, johnnywilkes commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_57.md
> +##### Cortex ASM - ServieNow Notification
```suggestion
##### Cortex ASM - ServiceNow Notification
```
Small typo

2024-10-30 23:25 UTC, capanw commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification.yml
> +          Tags: ${alert.tags}
Hey @BigEasyJ, Thanks for reviewing. Utkarsh requested to just have EV2 tags. So, just added them.

2024-10-31 13:51 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification.yml
> +- description: Generic group for inputs
```suggestion
- description: Generic group for inputs.
```

2024-10-31 13:51 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_ServiceNow_Notification.yml
> +- description: Generic group for outputs
```suggestion
- description: Generic group for outputs.
```

2024-10-31 13:51 UTC, ShirleyDenkberg commented on Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_57.md
> +Updated the playbook to add additional information to ServiceNow ticket in description.
```suggestion
Updated the playbook to add additional information to the description in the ServiceNow ticket.
```

2024-10-31 14:15 UTC, johnnywilkes approved these changes
Thanks for the updates

2024-10-31 14:27 UTC, ShirleyDenkberg commented
@BigEasyJ @johnnywilkes @tcarmeli1 @tomer-pan Doc review completed.

2024-10-31 23:25 UTC, capanw commented
@tcarmeli1 @tomer-pan Approved from our side. Please review and merge, please. Thanks

2024-11-06 21:21 UTC, capanw commented
@tcarmeli1 @tomer-pan Please let me know if there is anything that is pending for merging. Thank you!!!

2024-11-12 09:01 UTC, tcarmeli1 commented
Hi @capanw ,
Great work!
Thank you for your contribution.
I am now working on merging this PR.
Thank you again.

2024-11-12 12:13 UTC, tcarmeli1 approved these changes
Great work!

2024-11-12 12:14 UTC, merged