Add Sub Resolution Option When Closing An Insight
demisto/content pull request #37133
Opened 2024-11-08 22:10 UTC by yleiferman

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added an option to set up a sub resolution in the CLI when closing an insight.

## Must have
- [x] Tests
- [x] Documentation

2024-11-10 07:11 UTC, aaron1535 commented
Hi @yleiferman,
Thank you for your contribution.
So we can continue your PR
Please make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form.

2024-11-11 19:50 UTC, yleiferman commented
Hi @aaron1535 , please let me know if there's anything else that you would like me to do. Thank you for your help.

2024-11-12 15:02 UTC, aaron1535 requested changes
Hi @yleiferman
good work
Check my comments please so we can move forward with the merger

2024-11-12 15:44 UTC, yleiferman commented on package-lock.json
> -      },
Done @aaron1535 . I've removed it. Thank you for the feedback.

2024-11-13 06:54 UTC, aaron1535 approved these changes

2024-11-13 06:59 UTC, merged