fetch all computers without a date filter.
demisto/content pull request #37219
Opened 2024-11-14 09:37 UTC by yedidyacohenpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [CIAC-12027](https://jira-dc.paloaltonetworks.com/browse/CIAC-12027)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-11-14 12:34 UTC, jbabazadeh requested changes
great job! please see my comments

2024-11-14 15:43 UTC, yedidyacohenpalo commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
> +        """
```suggestion
        """done
```

2024-11-14 15:44 UTC, yedidyacohenpalo commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
> +        """
done

2024-11-14 16:02 UTC, yedidyacohenpalo commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.yml
> +- display: Fetch all computers
done

2024-11-17 11:39 UTC, yedidyacohenpalo commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_test.py
done

2024-11-17 21:59 UTC, jbabazadeh commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.yml
> +  additionalinfo: When set to true, retrieves all available computers during the initial fetch, ignoring the Events Fetch Interval and not limited to recent changes.
```suggestion
  additionalinfo: When set to true, retrieves all available computers during the initial fetch.
```

2024-11-17 21:59 UTC, jbabazadeh commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/README.md
> +    | Fetch all computers | When set to true, retrieves all available computers during the initial fetch, ignoring the Events Fetch Interval and not limited to recent changes. | False |
```suggestion
    | Fetch all computers | When set to true, retrieves all available computers during the initial fetch. | False |
```

2024-11-17 22:00 UTC, jbabazadeh commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/README.md
> +
```suggestion
```

2024-11-17 22:00 UTC, jbabazadeh approved these changes
looks good!

2024-11-20 18:59 UTC, jbabazadeh approved these changes
Nice!

2024-11-20 18:59 UTC, jbabazadeh commented on Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py
> +
add debug log that print the `latest_event`

2024-11-21 09:10 UTC, merged