Feedly/fetch reports as incidents
demisto/content pull request #37229
Opened 2024-11-14 14:15 UTC by Mathieu4141

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description

- Add a new integration to ingest articles as incidents. This was requested by one of our customer to fit their workflow, and discussed with our partner at XSOAR.
- Added a playbook that search and associates some indicators (malware, intrusion sets and TTPs) to the incident.
- Making it optional to ingest articles as indicators in the old feed, to avoid duplicating information in different places if the incident integration is enabled
- Fixed an issue with the continuation that caused some articles to not be ingested if the integration velocity was too high

<img width="1740" alt="Screenshot 2024-11-14 at 3 15 03 PM" src="https://github.com/user-attachments/assets/1a255d60-077f-4a10-bf03-d8accf26c0c3">

2024-11-19 13:53 UTC, YairGlik commented
Hi @Mathieu4141,
Thank you for your contribution!
It seems that the build failed on unit tests and validation. Could you please address these issues to allow the merge?

2024-11-19 16:01 UTC, Mathieu4141 commented
> Hi @Mathieu4141, Thank you for your contribution! It seems that the build failed on unit tests and validation. Could you please address these issues to allow the merge?

I think I fixed most of the issues, however I don't understand the remaining one
There seems to be an issue with a file that I exported from the UI, so not sure what is wrong here

2024-11-20 15:00 UTC, MLainer1 commented
Hi @Mathieu4141, thank you for your contribution.
One thing that I saw in the PR that is done incorrectly:
The Feed integration functionality in XSOAR is only used for fetching indicators. You cannot create a feed to create incidents.
Inorder to create incidents, you need to create a **new pack** that will contain the integration with the Fetch Incidents function.
Please follow the guide here https://xsoar.pan.dev/docs/integrations/fetching-incidents

2024-11-20 15:08 UTC, Mathieu4141 commented
> Hi @Mathieu4141, thank you for your contribution. One thing that I saw in the PR that is done incorrectly: The feed integration functionality in XSOAR is only used to fetch indicators. You cannot use a feed integration to create incidents. Inorder to create incidents, you need to create a **new pack** that will contain the integration with the Fetch Incidents function. Please follow the guide here https://xsoar.pan.dev/docs/integrations/fetching-incidents

Thanks for your review!

Is there a way to have only 1 pack? The 2 integration work together, so anything that makes it easier for users to install would increase the chances that they don't forget half of the integration :)

2024-11-21 08:27 UTC, MLainer1 commented
> > Hi @Mathieu4141, thank you for your contribution. One thing that I saw in the PR that is done incorrectly: The feed integration functionality in XSOAR is only used to fetch indicators. You cannot use a feed integration to create incidents. Inorder to create incidents, you need to create a **new pack** that will contain the integration with the Fetch Incidents function. Please follow the guide here https://xsoar.pan.dev/docs/integrations/fetching-incidents
> 
> Thanks for your review!
> 
> Is there a way to have only 1 pack? The 2 integration work together, so anything that makes it easier for users to install would increase the chances that they don't forget half of the integration :)

Unfortunetly no, they will have to be in separate packs.

2024-11-26 13:34 UTC, idovandijk requested changes
Hi @Mathieu4141. I'll be happy to review some of the files in this PR but in order for me to do so, I need to ask that you fix the Incident Field file.
You can export the incident fields from the Incident Fields page or from the Settings / Troubleshooting page (depending on the XSOAR version you're on).
In your case I think you used the 2nd method, which exports a unified file of all the incident fields.

What we need instead is an individual file for each incident field you want to add (3 fields = 3 files). Please refer to other Incident Fields in other packs to see how it should look.

Once you can address @MLainer1 's comment and this, give me a ping and I'll review and add my comments.

Thanks for your patience, and don't hesitate to reach out if you're having any issue.

2024-11-27 17:19 UTC, Mathieu4141 commented
> You can export the incident fields from the Incident Fields page or from the Settings / Troubleshooting page (depending on the XSOAR version you're on).

What is the Incident Fields page?

2024-11-28 11:12 UTC, idovandijk commented
> > You can export the incident fields from the Incident Fields page or from the Settings / Troubleshooting page (depending on the XSOAR version you're on).
> 
> What is the Incident Fields page?
On XSOAR 6 that would be here
<img width="660" alt="image" src="https://github.com/user-attachments/assets/6f9c8fe1-ab1f-4f96-a50d-f01a12c06637">

On XSOAR 8 you can go to the Configuration page and Objects Setup.

You can then select which fields to export. If it exports it to one file still, please separate them.

2024-12-03 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37229) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37229) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37229) it.</sub>

2024-12-05 08:50 UTC, YairGlik commented
Hi [@Mathieu4141](https://github.com/Mathieu4141), thank you for your contribution.
One thing that I saw in the PR that is done incorrectly:
The feed integration functionality in XSOAR is only used to fetch indicators. You cannot use a feed integration to create incidents.
Inorder to create incidents, you need to create a new pack that will contain the integration with the Fetch Incidents function.
Please follow the guide here https://xsoar.pan.dev/docs/integrations/fetching-incidents

2024-12-12 09:50 UTC, YairGlik commented
Hi @Mathieu4141,
I would be happy to have a Zoom meeting with you to clarify things. When are you available?

2024-12-23 08:53 UTC, YairGlik commented
Hi @Mathieu4141, 
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

2024-12-24 11:41 UTC, Mathieu4141 commented
Sorry for the late reply @YairGlik 
I separated the packs & incident fields as requested

2024-12-29 08:54 UTC, YairGlik requested changes

2024-12-29 11:09 UTC, YairGlik commented on Packs/FeedFeedly/pack_metadata.json
> +    "currentVersion": "1.1.0",
please add Release Notes 1_1_0.md file.

2024-12-29 12:13 UTC, YairGlik commented
```
Packs/FeedlyArticles/IncidentFields/incident_feedlycrawleddate.json: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedlyArticles/IncidentTypes/customIncidentTypes.json: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedFeedly/Integrations/FeedFeedly/FeedFeedly.yml: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedlyArticles/Classifiers/classifier-Feedly_-_Report_Mapper.json: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedlyArticles/IncidentFields/incident_feedlythreatactornames.json: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedlyArticles/IncidentFields/incident_feedlymalwarenames.json: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedlyArticles/IncidentFields/incident_feedlyurl.json: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedlyArticles/Integrations/IncidentsFeedly/IncidentsFeedly.yml: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
Packs/FeedlyArticles/Playbooks/Feedly_threats.yml: [BA102] - The given file is not supported in the validate command, see the error above.
The validate command supports: Integrations, Scripts, Playbooks, Incident fields, Incident types, Indicator fields, Indicator types, Objects fields, Object types, Object modules, Images, Release notes, Layouts, Jobs, Wizards, Descriptions And Modeling Rules.
```
It seems there are issues with several files. Please run `demisto-sdk format` to fix them.

2025-01-10 14:29 UTC, Mathieu4141 commented
> It seems there are issues with several files. Please run `demisto-sdk format` to fix them.

How does it work? I get `Did not find any files to format`

2025-01-12 08:20 UTC, YairGlik commented
> > It seems there are issues with several files. Please run `demisto-sdk format` to fix them.
> 
> How does it work? I get `Did not find any files to format`

for example:
`demisto-sdk format -i 'Packs/FeedlyArticles/IncidentTypes/customIncidentTypes.json'`

2025-01-12 08:25 UTC, YairGlik commented
please add file `Packs/FeedlyArticles/.pack-ignore`

2025-01-19 14:14 UTC, idovandijk commented
> > @Mathieu4141 for me to review I would need all files to be formatted (playbooks included). Feel free to ping me once you're able to format them and I'll take a look!
> 
> Is it good now @idovandijk ?
> 
> Also why are the exports invalid in the first place? I downloaded from the XSOAR instance, I'd expect them to be formatted correctly?

@Mathieu4141 I can see why this is confusing. Exported files are valid, but they're not release-ready. Using the SDK to format the files ensures they meet the Cortex standard required to work optimally and correctly in the Marketplace.
Formatting the files also allows us to perform some parts of the review that without it we cannot do (we would need to change your files which we would like to avoid). I hope this answers the question. If you're unsure about certain parts of the Format command you can visit https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/commands/format/README.md

I'll be looking into your updates and let you know if anything else is needed, thanks again

2025-01-19 15:03 UTC, idovandijk requested changes
Great job, happy to see these new additions for Feedly!

My comments are numbered below for easy reference

### Playbook - Feedly threats
1. Please add a data validation task - verify that the MITRE IDs exist in ${incident} before searching it. Same for the rest of the indicators searched. Imagine if one of them ends up empty and we end up querying all indicators and associating all of them to the incident ;)
2. Please add a task that verifies that the search yielded any results, before associating to the incident.

### Incident Fields
3. Please set the incident fields to be associated with the Feedly Report incident type instead of being Associated To All.
4. Do you need the fields to be searchable in XSOAR/XSIAM? For example is someone going to search incidents by the Feedly URL field? If not, please set `unsearchable` to `true`.

### Mapper
5. Once your fields are associated to the Feedly Report incident type, I suggest modifying the mapper to have mapping for the Feedly Report type (not under Common Mapping)
<img width="271" alt="image" src="https://github.com/user-attachments/assets/b45e3174-87c2-44cc-9887-1656c1bf2252" />

<img width="232" alt="image" src="https://github.com/user-attachments/assets/c24dc415-7870-441a-9dbe-b96303a6116b" />

This will keep things more tidy as we currently only intend to map fields related to Feedly Reports.

As always, if there's any question or issue, don't hesitate to reach out to us.
When you're done making changes, let me know and I'll gladly approve from my side.

2025-01-20 11:45 UTC, Mathieu4141 commented
Thanks @idovandijk for the explanation and the detailed review!

1 & 2: I'm not sure how to do any of the 2 modifications in the playbook. Which tasks / changes do you suggest to do that?

3, 4, & 5: done :)

2025-01-29 12:03 UTC, idovandijk commented
> Thanks @idovandijk for the explanation and the detailed review!
> 
> 1 & 2: I'm not sure how to do any of the 2 modifications in the playbook. Which tasks / changes do you suggest to do that?
> 
> 3, 4, & 5: done :)

What I'm suggesting is adding conditional tasks that check that the context you use in your tasks exists prior to executing it.
You can take a look for example at the `Extract Indicators From File - Generic v2` playbook, which has a task that checks if a certain file format exists in the context before extracting indicators from the file.

2025-01-30 13:32 UTC, Mathieu4141 commented
@idovandijk should be good :)

2025-01-30 14:41 UTC, idovandijk commented
> @idovandijk should be good :)

Perfect, that's exactly what I meant. Don't forget to update the playbook image ;)
Adding security approval

2025-01-30 15:01 UTC, Mathieu4141 commented
> Perfect, that's exactly what I meant. Don't forget to update the playbook image ;)

Great! :D

What do you mean by the playbook image?

2025-02-09 14:48 UTC, idovandijk commented
> > Perfect, that's exactly what I meant. Don't forget to update the playbook image ;)
> 
> Great! :D
> 
> What do you mean by the playbook image?

@Mathieu4141 under Packs/your_pack/doc_files
should be a picture of the playbook, which is then used in the Playbook README.
Since you made some changes in the playbook it's a good idea to keep the image up to date too. You can export it from the Playbook Editor using the button on the right side

2025-02-10 14:00 UTC, Mathieu4141 commented
I added the image in the folder :)

2025-02-18 08:39 UTC, idovandijk commented
Hi @Mathieu4141, great!
Now it's just a matter of following the build and fixing any issues that our validations find. I can see that your playbook is missing a playbook README file - you can create it by using `demisto-sdk generate-docs -i Packs/<Your_Pack_Name>/Playbooks/<Your_Playbook_Name>`.
After creating the README note the image link generated at the bottom of that file - ensure it matches the actual name of the playbook image.
By doing this you are creating a README page for your playbook available on our documentation site xsoar.pan.dev :)

2025-02-18 13:21 UTC, YairGlick commented
Hi @Mathieu4141,
It looks like there are some errors in the pre-commit checks. Please fix them.
it seems like you need to run:
`demisto-sdk format -i`
on the following files:
`Packs/FeedlyArticles/Classifiers/classifier-Feedly_-_Report_Mapper.json`
`Packs/FeedlyArticles/Layouts/layoutscontainer-Feedly_Report.json`
Let me know if you need any help! Thanks.

2025-02-18 15:01 UTC, YairGlick commented
Hey @Mathieu4141,
Tryusing the full path, making sure to replace `userName` with your actual username:
`demisto-sdk format -i '/Users/userName/dev/demisto/content/Packs/FeedlyArticles/Layouts/layoutscontainer-Feedly_Report.json'`
Let me know if you still run into issues

2025-02-18 15:10 UTC, Mathieu4141 commented
It looks like I was using an outdated version of the SDK, which was causing the issue

I re-ran the commands and it updated the files

2025-02-19 13:20 UTC, YairGlick commented
Hey @Mathieu4141,

It looks like the formatting is now resolved. Now, we just need to fix the remaining pre-commit errors. Let me know if you need any help!

Thanks.

2025-03-04 14:14 UTC, Mathieu4141 commented
> Hi @Mathieu4141, we haven’t heard from you in a while. Do you need any help with the pull request?
> 
> Please feel free to reach out to me here or on Slack. Thanks again for contributing to our repo, hope to hear from you soon.

Hi @YairGlick ! Thanks for the review
I was on vacation, will resume working on the pre-commit issues early this week! :)

2025-03-09 14:13 UTC, YairGlick commented
Hi @Mathieu4141,
It looks like there are still some validation errors that need to be fixed. Let me know if you need any help with that. Also, it seems that the license/cla hasn’t been signed. If you’ve already signed it, could you please sign it again?
Thanks!

2025-03-19 22:06 UTC, YairGlick commented
Hi @Mathieu4141, we haven’t heard from you in a while.
Do you need any help with the pull request?

Please feel free to reach out to me here or on Slack.
Thanks again for contributing to our repo, hope to hear from you soon.

2025-03-31 07:19 UTC, YairGlick commented
Hi @Mathieu4141, 
Thank you for your contribution. 
I have not received a response from you in the last two weeks, so I will close your PR now.
Please feel free to re-open it when you are available to continue. 
Thanks again.

2025-03-31 07:19 UTC, closed without merging