Feature: Infoblox manage session with cookies in integration storage
demisto/content pull request #37240
Opened 2024-11-15 13:57 UTC by jesusgpo

## Contributing to Cortex XSOAR Content

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Now the infoblock integration is doing the authentication for each command execution, this has a very high impact on infoblox, that's why the cookies are stored in the context of the integration and loaded before each call, avoiding to login unless the cookies expire.

2024-11-17 10:32 UTC, MLainer1 requested changes
Thank you for your contribution.
Please attach a short demo video demonstrating your change.

2024-11-17 10:32 UTC, MLainer1 commented on Packs/Infoblox/Integrations/Infoblox/Infoblox.py
> +            if error.message is not None and error.message == INTEGRATION_AUTHORIZATION_EXCEPTION_MESSAGE:
```suggestion
            if error.message  and error.message == INTEGRATION_AUTHORIZATION_EXCEPTION_MESSAGE:
```

2024-11-19 09:46 UTC, jesusgpo commented
Hi may, yesterday I attached you the demo video by slack

2024-11-21 11:28 UTC, MLainer1 commented
Looks great! make sure to fix the pre-commit errors in the Github workflows.
Afterwards we can continue to merging the PR.

2024-11-24 12:10 UTC, MLainer1 commented
@jesusgpo Is it ready for merge from your side?

2024-11-25 06:46 UTC, jesusgpo commented
Hi @MLainer1 

I have just updated the release, thank you for your help.

Kind regards

2024-11-28 10:33 UTC, Shellyber commented
For the Reviewer: Trigger build request has been accepted for this contribution PR.

2024-11-28 10:33 UTC, Shellyber commented
For the Reviewer: Successfully created a pipeline in GitLab with url: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1717709

2024-12-03 12:34 UTC, ShirleyDenkberg commented
@jesusgpo Doc review completed.

2024-12-03 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37240) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: MLainer1<br/>:x: jesusgpo<br/>:x: samuelFain<br/><hr/>**MLainer1** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37240) it.</sub>

2024-12-03 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37240) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: MLainer1<br/>:x: jesusgpo<br/>:x: samuelFain<br/><hr/>**MLainer1** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37240) it.</sub>

2024-12-10 09:00 UTC, MLainer1 approved these changes

2024-12-11 10:43 UTC, Shellyber commented
For the Reviewer: Trigger build request has been accepted for this contribution PR.

2024-12-11 10:43 UTC, Shellyber commented
For the Reviewer: Successfully created a pipeline in GitLab with url: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1789964

2024-12-12 10:56 UTC, merged