Feature: OpenCTI Improvements
demisto/content pull request #37270
Opened 2024-11-18 14:21 UTC by jesusgpo

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

In progess doing test, waiting for paloalto review

## Description
- Rename indicators commands to observable commands according to [OpenCTI naming](https://docs.opencti.io/latest/usage/exploring-observations/)
- Develop Incident commands
- Develop indicators commands

## Must have
- [ ] Tests
- [ ] Documentation

2024-11-19 11:01 UTC, samuelFain commented
@jesusgpo Following our sync on this contribution:
1. Please make sure you sign the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form so I can start my review on this PR.
2. We are currently reviewing the original commands depreciation issue and whether we should keep or completely remove them, I will update you as soon as I have more information.

Thanks!

2024-11-21 08:20 UTC, samuelFain commented
@jesusgpo Following our sync on this contribution:
> Hi Samuel, I have just completed the form and I filled the description with the commands developed and updated, my next step is develop the tests for the commands

Thanks for the update! I will start reviewing the PR.

2024-11-27 10:35 UTC, samuelFain requested changes
@jesusgpo You have done amazing work so far!
I reviewed most of the command changes so I'm posting my initial review for them.
I will be reviewing the incident commands (3 commands), test file and other file changes in this PR shortly.
In the meanwhile, please see my comments, some of them might have already been addressed by your latests commits.
Also, it seems like you have a conflict in README.md.

2024-11-27 10:35 UTC, samuelFain commented on Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.yml
> +    - contextPath: OpenCTI.IndicatorTypes.ndicatorTypesList.description
```suggestion
    - contextPath: OpenCTI.IndicatorTypes.IndicatorTypesList.description
```

2024-11-27 11:18 UTC, samuelFain commented
@jesusgpo A few more issues that came up when running demisto-sdk pre-commit command on your PR (I strongly suggest to use it as well, more about this command [here](https://docs-cortex.paloaltonetworks.com/r/1/Demisto-SDK-Guide/pre-commit)):
- ruff error code [E731](https://docs.astral.sh/ruff/rules/lambda-assignment/): Do not assign a `lambda` expression, use a `def`. For example in: `query = lambda *args, **kwargs: None`.
- Getting a mypy linting error where the `indicator` argument has a type of `Optional[str]` but expects `str` for this line:
`pattern = build_stix_pattern(indicator, main_observable_type)` 
- I also have 3 UTs failing when trying to run them via pytest on the docker container, not sure if there is real issue with them or not, we can wait until the conflict in `Packs/OpenCTI/Integrations/OpenCTI/README.md` is resolved and then pre-commit will also run inside one of this PRs Github actions (also runs the UTs), giving us something to compare with:
test_incident_create_command_exception, test_incident_types_list_command_exception, 
OpenCTI_test.py::test_incident_create_command_exception_id.

2024-12-02 15:29 UTC, samuelFain commented
@jesusgpo the latest changes are looking good! i've sent you a slack massage regarding the current error messages. mostly small discrepancy in commands between the .yml and .py files, and updating the test playbook to match the changes in this PR.
Please let me know if any issues arise.

2024-12-03 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37270) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37270) it.</sub>

2024-12-04 15:01 UTC, samuelFain commented on Packs/OpenCTI/Integrations/OpenCTI/OpenCTI.yml
> +      type: string
Regarding the following validation error RM102:
>opencti-indicator-create:
The following outputs are missing from yml: OpenCTI.Indicator.value, OpenCTI.Indicator.type

The validation's description validates that all context outputs defined in the README file are present in the YML file, and vice versa.
Where the rational is:
>"Ensuring consistency between the README and YML files helps maintain accurate documentation and prevents discrepancies."

So basically there is a consistency between the readme:
https://github.com/demisto/content/blob/bf19c98a05b0af567658e6e6624091b3cda295d6/Packs/OpenCTI/Integrations/OpenCTI/README.md?plain=1#L154
And the yml file which only have OpenCTI.Indicator.id in the context output:
https://github.com/demisto/content/pull/37270/files#diff-3a03284b240156d148b67fe01f470c1da9010d62638df25c8b68e4b5e184b4b2R428

It also relevant for `opencti-get-indicators`:
>opencti-get-indicators:
The following outputs are missing from readme: OpenCTI.Indicators.IndicatorList.creators

2024-12-05 12:35 UTC, samuelFain commented
@jesusgpo Great work so far!
As discussed on Slack, we will schedule a demo call to review the changes made in this PR before merging this contribution.

2024-12-11 07:43 UTC, Shellyber commented
For the Reviewer: Trigger build request has been accepted for this contribution PR.

2024-12-11 07:43 UTC, Shellyber commented
For the Reviewer: Successfully created a pipeline in GitLab with url: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1788990

2024-12-12 09:10 UTC, ShirleyDenkberg commented on Packs/OpenCTI/Integrations/OpenCTI/README.md
> +| source | Incident Source. | Optional |
```suggestion
| source | Incident source. | Optional | 
```

2024-12-12 09:10 UTC, ShirleyDenkberg commented on Packs/OpenCTI/Integrations/OpenCTI/README.md
> +| last_seen | Incident Last seen. YYYY-MM-DDThh:mm:ss.sssZ. | Optional |
```suggestion
| first_seen | Incident first seen. YYYY-MM-DDThh:mm:ss.sssZ. | Optional | 
| last_seen | Incident last seen. YYYY-MM-DDThh:mm:ss.sssZ. | Optional | 
```

2024-12-12 09:10 UTC, ShirleyDenkberg commented on Packs/OpenCTI/Integrations/OpenCTI/README.md
> +| limit | The maximum number of incidents to return. Default value is 50. Maximum value is 500. Default is 50. | Optional |
```suggestion
| limit | The maximum number of incidents to return. Maximum value is 500. Default is 50. | Optional | 
```

2024-12-12 09:10 UTC, ShirleyDenkberg commented on Packs/OpenCTI/Integrations/OpenCTI/README.md
> +| all_results | When the argument is set to true, the limit argument is ignored. Default is false. Possible values are: true, false. Default is false. | Optional |
```suggestion
| all_results | When the argument is set to true, the limit argument is ignored. Possible values are: true, false. Default is false. | Optional | 
```

2024-12-15 10:56 UTC, samuelFain commented on Packs/OpenCTI/ReleaseNotes/2_0_0.md
> +- Deprecate old `indicator` commands
@ShirleyDenkberg is this a mistake?

2024-12-15 11:05 UTC, samuelFain approved these changes
Amazing work! Approved.

2024-12-17 08:00 UTC, merged