Add Padding
demisto/content pull request #37340
Opened 2024-11-21 10:20 UTC by BEAdi

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-44110

## Description
Add padding to decoding a base 64 image to binary, to avoid "Incorrect padding" error.

## Must have
- [ ] Tests
- [ ] Documentation

2024-11-25 11:40 UTC, ShirleyDenkberg commented on Packs/ApiModules/ReleaseNotes/2_2_30.md
> +Fixed an issue where the ***send-mail***, ***reply-mail***, ***get-attachments*** and ***fetch-incidents*** commands failed to decode the **htmlBody** argument if it was provided with no padding.
```suggestion
Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
- ***send-mail***
- ***reply-mail***
- ***get-attachments***
- ***fetch-incidents*** 
```

2024-11-25 11:40 UTC, ShirleyDenkberg commented on Packs/Gmail/ReleaseNotes/1_3_29.md
> +Fixed an issue where the ***send-mail*** and ***reply-mail*** commands failed to decode the **htmlBody** argument if it was provided with no padding.
```suggestion
Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
- ***send-mail***
- ***reply-mail***
```

2024-11-25 11:40 UTC, ShirleyDenkberg commented on Packs/GmailSingleUser/ReleaseNotes/1_4_9.md
> +Fixed an issue where the ***send-mail*** and ***reply-mail*** commands failed to decode the **htmlBody** argument if it was provided with no padding.
```suggestion
Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
- ***send-mail***
- ***reply-mail***
```

2024-11-25 11:40 UTC, ShirleyDenkberg commented on Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_18.md
> +Fixed an issue where the ***send-mail*** and ***reply-mail*** commands failed to decode the **htmlBody** argument if it was provided with no padding.
```suggestion
Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
- ***send-mail***
- ***reply-mail***
```

2024-11-25 11:40 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphMail/ReleaseNotes/1_6_20.md
> +Fixed an issue where the ***send-mail***, ***reply-mail***, ***get-attachments*** and ***fetch-incidents*** commands failed to decode the **htmlBody** argument if it was provided with no padding.
```suggestion
Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
- ***send-mail***
- ***reply-mail***
- ***get-attachments***
- ***fetch-incidents*** 
```

2024-11-25 11:40 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphMail/ReleaseNotes/1_6_20.md
> +Fixed an issue where the ***send-mail***, ***reply-mail***, ***get-attachments*** and ***fetch-incidents*** commands failed to decode the **htmlBody** argument if it was provided with no padding.
```suggestion
Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
- ***send-mail***
- ***reply-mail***
- ***get-attachments***
- ***fetch-incidents*** 
```

2024-11-25 11:41 UTC, ShirleyDenkberg commented
@tcarmeli1 Doc review completed.

2024-11-25 13:50 UTC, tcarmeli1 requested changes
Great Work! :)

2024-11-25 13:50 UTC, tcarmeli1 commented on Packs/ApiModules/ReleaseNotes/2_2_30.md
> +Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
You fixed also comments that do not use the htmlBody such as file_result_creator inside the create_attachment command (also would suggest changing the get-attachments to the real name), maybe i would change the release notes to :
Fixed an issue where the following commands failed to decode Base64-encoded attachments or images inside the htmlBody when provided without padding:
- ***send-mail***
- ***reply-mail***
- ***msgraph-mail-get-attachment***
- ***fetch-incidents*** 
wdyt?

2024-11-25 13:50 UTC, tcarmeli1 commented on Packs/MicrosoftGraphMail/ReleaseNotes/1_6_20.md
> +Fixed an issue where the following commands failed to decode the **htmlBody** argument if it was provided with no padding:
Same as above:
You fixed also comments that do not use the htmlBody such as file_result_creator inside the create_attachment command (also would suggest changing the get-attachments to the real name), maybe i would change the release notes to :
Fixed an issue where the following commands failed to decode Base64-encoded attachments or images inside the htmlBody when provided without padding:

send-mail
reply-mail
msgraph-mail-get-attachment
fetch-incidents
wdyt?

2024-11-26 08:25 UTC, tcarmeli1 requested changes

2024-11-26 08:25 UTC, tcarmeli1 commented on Packs/MicrosoftGraphMail/ReleaseNotes/1_6_20.md
> +- ***get-attachments***
```suggestion
- ***msgraph-mail-get-attachment***
```

2024-11-26 08:28 UTC, BEAdi commented on Packs/ApiModules/ReleaseNotes/2_2_30.md
> +Fixed an issue where the following commands failed to decode Base64-encoded attachments or images inside the html נody when provided without padding:
```suggestion
Fixed an issue where the following commands failed to decode Base64-encoded attachments or images inside the html body when provided without padding:
```

2024-11-26 08:28 UTC, BEAdi commented on Packs/MicrosoftGraphMail/ReleaseNotes/1_6_20.md
> +- ***fetch-incidents***
```suggestion
Fixed an issue where the following commands failed to decode Base64-encoded attachments or images inside the html body when provided without padding:
- ***send-mail***
- ***reply-mail***
- ***msgraph-mail-get-attachment***
- ***fetch-incidents*** 

##### O365 Outlook Mail (Using Graph API)

Fixed an issue where the following commands failed to decode Base64-encoded attachments or images inside the html body when provided without padding:
- ***send-mail***
- ***reply-mail***
- ***msgraph-mail-get-attachment***
- ***fetch-incidents*** 
```

2024-11-26 08:33 UTC, tcarmeli1 approved these changes
Amazing work!

2024-12-01 09:27 UTC, merged