Nozomi fix lost incidents
demisto/content pull request #37351
Opened 2024-11-21 15:19 UTC by nicoloereni

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests
- [x] Documentation

2024-11-26 08:49 UTC, YairGlik requested changes
Good job!

2024-11-26 08:49 UTC, YairGlik commented on Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
> +        response = requests.request(
It is not recommended to use requests.request,
It is safer to use _http_request from CommonServerPython.
To determine the status code they are ok You can send in the status_code parameter.

2024-12-01 12:24 UTC, YairGlik commented
Hi @nicoloereni,
We're ready for a demo. Please let me know when you're available for one over DFIR.
We'll talk about the http_request in the meeting.

2024-12-02 10:03 UTC, nicoloereni commented
> Hi @nicoloereni, We're ready for a demo. Please let me know when you're available for one over DFIR. We'll talk about the http_request in the meeting.

Hi @YairGlik, perfect!
I'm in the CET timezone, I'm sending my availability via Slack.
Thanks

2024-12-03 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37351) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37351) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37351) it.</sub>

2024-12-03 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37351) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37351) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37351) it.</sub>

2024-12-04 13:00 UTC, YairGlik approved these changes

2024-12-04 13:44 UTC, nicoloereni commented
@YairGlik 
What can I do to make the `demisto/pull-check` geen?

2024-12-04 16:05 UTC, nicoloereni commented
@YairGlik 
All checks are green, if you want you can merge it, thanks

2024-12-05 11:54 UTC, Shellyber commented
For the Reviewer: Trigger build request has been accepted for this contribution PR.

2024-12-05 11:54 UTC, Shellyber commented
For the Reviewer: Successfully created a pipeline in GitLab with url: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1757182

2024-12-05 16:14 UTC, Shellyber commented
For the Reviewer: Trigger build request has been accepted for this contribution PR.

2024-12-05 16:14 UTC, Shellyber commented
For the Reviewer: Successfully created a pipeline in GitLab with url: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1759405

2024-12-09 09:54 UTC, nicoloereni commented
@YairGlik @Shellyber 

Our common customer has reached out to request an ETA for the fix of this issue. They are looking forward to having this resolved soon.
Thank you for your support!

2024-12-09 12:45 UTC, YairGlik commented
Hello,

Thank you for your contribution to the project! There are a few small fixes needed to get your changes ready for merging:

1. Docker Image: The current image version (demisto/python3:3.10.14.92207) is outdated. Please update it to the latest version: demisto/python3:3.11.10.116949.
2. Description File: A description file is missing for the integration. Please add a file named NozomiNetworks_description.md and include the necessary description.
If you need any help or further clarification, feel free to reach out.

Thank you and good luck!

2024-12-09 13:54 UTC, Shellyber commented
For the Reviewer: Trigger build request has been accepted for this contribution PR.

2024-12-09 13:54 UTC, Shellyber commented
For the Reviewer: Successfully created a pipeline in GitLab with url: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1777902

2024-12-09 14:37 UTC, merged