update name and logo
demisto/content pull request #37361
Opened 2024-11-22 14:06 UTC by nitsan-tzur

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-11-24 09:36 UTC, MLainer1 requested changes
Thank you for your contribution.
Make sure to fix the pre-commit errors, and sign the contribution form.

2024-11-25 19:09 UTC, nitsan-tzur commented
> Thank you for your contribution. Make sure to fix the pre-commit errors, and sign the contribution form.

Fixed the relevant pre-commit issues

2024-12-02 16:07 UTC, MLainer1 approved these changes

2024-12-03 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37361) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: samuelFain<br/>:x: RotemAmit<br/>:x: nitsan-tzur<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37361) it.</sub>

2024-12-03 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37361) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: samuelFain<br/>:x: RotemAmit<br/>:x: nitsan-tzur<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37361) it.</sub>

2024-12-03 14:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37361) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37361) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: nitsan-tzur<br/>:x: RotemAmit<br/>:x: samuelFain<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37361) it.</sub>

2024-12-04 15:45 UTC, samuelFain commented
Hi @nitsan-tzur, due to Github technical issue, can you please re-sign the [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37361)?
This should help `license/cla` Github action to run.

2024-12-08 09:13 UTC, merged