Rasterize url bug
demisto/content pull request #37463
Opened 2024-11-28 09:58 UTC by merit-maita

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-44315

## Description
Fixed an issue where the ***rasterize*** command failed to parse URLs.

## Must have
- [ ] Tests
- [ ] Documentation

2024-11-28 12:42 UTC, adi88d approved these changes
nice!

2024-12-01 09:10 UTC, tkatzir approved these changes

2024-12-01 09:13 UTC, tkatzir approved these changes
Approved, with a comment

2024-12-01 09:13 UTC, tkatzir commented on Packs/rasterize/Integrations/rasterize/rasterize.py
> +    # Do not remove this line
```suggestion
    # Do not remove this line, as rasterize does not support array in `url`.
```

2024-12-01 09:15 UTC, tkatzir requested changes
Need to remove `isArray: true` in the yml file.

2024-12-01 09:15 UTC, tkatzir commented on Packs/rasterize/ReleaseNotes/2_0_30.md
> +- Fixed an issue where the ***rasterize*** command failed to parse URLs.
```suggestion
- Fixed an issue where the ***rasterize*** command failed to parse URLs that contained a comma.
```

2024-12-01 09:26 UTC, tkatzir approved these changes
Great! Approved.

2024-12-01 11:11 UTC, ilaredo approved these changes
line 877:   paths = argToList(path)
become redundant

2024-12-02 12:11 UTC, merit-maita commented
the rasterize_test TPB  failing in saas is a known issue, so it's going to be force merged.

2024-12-02 12:26 UTC, merged