Update ruff to 0.8.0
demisto/content pull request #37472
Opened 2024-11-28 14:59 UTC by RotemAmit

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Update ruff to 0.8.0.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-03 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37472) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37472) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37472) it.</sub>

2024-12-03 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37472) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37472) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37472) it.</sub>

2024-12-08 13:05 UTC, kobymeir commented
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12222018616)
- **CommonScripts** pack version was bumped to **1.17.3**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

2024-12-08 17:03 UTC, kobymeir commented
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12223634618)
- **Base** pack version was bumped to **1.38.2**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

2024-12-09 09:00 UTC, kobymeir commented
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12232153401)
- **Syslog** pack version was bumped to **2.0.20**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

2024-12-09 09:12 UTC, kobymeir commented
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12232346213)
- **CommonScripts** pack version was bumped to **1.17.4**.
- **FeedTAXII** pack version was bumped to **1.2.26**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

2024-12-18 16:31 UTC, eyalpalo approved these changes
See my comments.. Nice job!!!

2024-12-19 11:49 UTC, RotemAmit commented on Packs/AWS_WAF/Integrations/AWSWAF/AWSWAF.py
> +        result = CommandResults()
It is probably an auto fix of pre-commit.

2024-12-19 15:24 UTC, RotemAmit commented
The step run-validations in ci/gitlab/gitlab.xdr.pan.local fails with the following errors:
Packs/AWS_Sagemaker/Integrations/AWSSagemaker/AWSSagemaker.yml: [IN140] - The integration AWS Sagemaker is currently in skipped. Please add working tests and unskip. Skip comment: No instance - License expired, and probably not going to get it.
Packs/CommonScripts/Scripts/CVSSCalculator/CVSSCalculator.yml: [CJ105] - Either CVSSCalculator does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.
Packs/Troubleshoot/Scripts/TroubleshootExecuteCommand/TroubleshootExecuteCommand.yml: [CJ105] - Either TroubleshootExecuteCommand does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.

2025-01-01 10:23 UTC, eyalpalo requested changes
Please go over the validations, and build steps. Will be approved after all is green before the force.

2025-01-02 13:51 UTC, RotemAmit commented
Failures and explanations:
* pre-commit (github action) - fails since the PR contains too many files, and it can't handle it.
* run-validations in gitlab.xdr.pan.local fails on:
* Packs/Troubleshoot/Scripts/TroubleshootExecuteCommand/TroubleshootExecuteCommand.yml - [CJ105] - Either TroubleshootExecuteCommand does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.
* Packs/AWS_Sagemaker/Integrations/AWSSagemaker/AWSSagemaker.yml - [IN140] - The integration AWS Sagemaker is currently in skipped.
* Packs/CommonScripts/Scripts/CVSSCalculator/CVSSCalculator.yml - [CJ105] - Either TroubleshootExecuteCommand does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.

2025-01-06 15:08 UTC, eyalpalo approved these changes

2025-01-06 15:18 UTC, RotemAmit commented
@dantavori Please force merge this PR.
The reasons for the force merge are written in this comment https://github.com/demisto/content/pull/37472#issuecomment-2567807239

2025-01-06 15:43 UTC, merged