Yc/update links
demisto/content pull request #37473
Opened 2024-11-28 15:06 UTC by yedidyacohenpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12049)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-02 19:12 UTC, jbabazadeh requested changes
great work! please see my comments

2024-12-03 08:46 UTC, ShirleyDenkberg commented on Packs/AHA/TestPlaybooks/AHA_TestPlaybook.yml
> +        For XSOAR 6 use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations and for XSOAR 8 use the link https://docs-cortex.paloaltone
```suggestion
      - For Cortex XSOAR 6 use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Administrator-Guide/Automations
       
         (Note: Replace 6.x with the version number of your environment, i.e., 6.12, 6.13, etc.)
     
       - For Cortex XSOAR 8 Cloud use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script.
```
What about Cortex XSOAR on-prem? It should be added and should be something like this:
   - For Cortex XSOAR on-prem, use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Scripts

   (Note: Replace 8.x with the version number of your environment, i.e., 8.6, 8.7, etc.)

2024-12-03 08:47 UTC, ShirleyDenkberg commented
This change needs to be made everywhere:
      - For Cortex XSOAR 6 use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Administrator-Guide/Automations
       
         (Note: Replace 6.x with the version number of your environment, i.e., 6.12, 6.13, etc.)
     
       - For Cortex XSOAR 8 Cloud use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script.

     - For Cortex XSOAR on-prem, use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Scripts
     
      (Note: Replace 8.x with the version number of your environment, i.e., 8.6, 8.7, etc.)

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/Securonix/Integrations/Securonix/README.md
> +The administrator and Cortex XSOAR users on the recipient's list receive a notification when an integration experiences an incident fetch error. Cortex XSOAR users can select their notification metho
```suggestion
The administrator and Cortex XSOAR users on the recipient's list receive a notification when an integration experiences an incident fetch error. Cortex XSOAR users can select their notification method, such as email, from their user preferences. Refer to [XSOAR 6.13 documentation](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Receive-Notification-on-an-Incident-Fetch-Error) or [XSOAR 8 Cloud documentation](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Receive-notifications-on-an-incident-fetch-error) for more information.
```
What about on-prem?  https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Receive-notifications-on-an-incident-fetch-error

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/ServiceNow/Integrations/ServiceNowv2/README.md
> +      For more information about Customize Incident Close Reasons, see [XSOAR 6.13](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Customize-Incident-Cl
```suggestion
      For more information about Customize Incident Close Reasons, see [XSOAR 6.13](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Customize-Incident-Close-Reasons) or [XSOAR 8 Cloud](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Customize-incident-close-reasons).
```
What about on-prem? https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Customize-incident-close-reasons

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/ShiftManagement-AssignToNextShift/Playbooks/playbook-Assign_Active_Incidents_to_Next_Shift.yml
> +      description: "Randomly assigns the incidents to users on call (requires shift management) and users on call.
```suggestion
      description: "Randomly assigns the incidents to users on call (requires shift management) and users on call.
```
Is the second "users on call" supposed to be there?  If so, maybe it should be "users on call (with no shift management)."

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/ShiftManagement-AssignToNextShift/Playbooks/playbook-Assign_Active_Incidents_to_Next_Shift.yml
> +        [XSOAR 8](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Manage-roles-in-the-Cortex-XSOAR-tenant)
```suggestion
        [XSOAR 8 Cloud](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Manage-roles-in-the-Cortex-XSOAR-tenant)
```
What about on-prem?  https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Manage-roles-in-the-Cortex-XSOAR-tenant

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/ShiftManagement-AssignToNextShift/Playbooks/playbook-Assign_Active_Incidents_to_Next_Shift.yml
> +        Incident Ids should be passed in as a comma separated list."
```suggestion
        Incident IDs should be passed as a comma-separated list."
```

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/ShiftManagement-AssignToNextShift/Scripts/AssignToNextShift/AssignToNextShift.yml
>    Incident Ids should be passed in as a comma separated list.
```suggestion
  Incident IDs should be passed as a comma-separated list.
```

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/README.md
> +After following the [tutorial (XSOAR 6.13)](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Configure-Python-Docker-Integrations-to-Trust-Custom-Certific
```suggestion
After following the [tutorial (XSOAR 6.13)](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Configure-Python-Docker-Integrations-to-Trust-Custom-Certificates) or [tutorial (XSOAR 8 Cloud)](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Configure-Docker-integrations-to-trust-custom-certificates) to update your custom certificate in `Cortex XSOAR Server`/ `Cortex XSOAR Engine`, validate the configuration applied using this script.
```
What about on-prem?  https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Configure-Docker-integrations-to-trust-custom-certificates

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/Use_Case_Builder/IncidentFields/incidentfield-Use_Case_TIM_Best_Practice.json
> +    "template": "# Threat Intel Management\n## Manually Add Indicators to the Exclusion List\nFrom the Exclusion List page, you can manually add a single indicator or define indicators using a regula
```suggestion
    "template": "# Threat Intel Management\n## Manually Add Indicators to the Exclusion List\nFrom the Exclusion List page, you can manually add a single indicator or define indicators using a regular expression (regex) or CIDR.\n\n### Regex\n\nA regular expression enables you to identify a sequence of characters in an unknown string. The following example would identify www.demisto.com: [A-Za-z0-9!@#$%\\.\u0026]*demisto[A-Za-z0-9!@#$%\\.\u0026]*.\n\n### CIDR\nClassless inter-domain routing (CIDR) enables you to define a range of IP addresses. For example, the IPv4 block 192.168.100.0/22 represents the 1024 IPv4 addresses from 192.168.100.0 to 192.168.103.255.\n\n## Indicator Management: [TIM (XSOAR 6.13)](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Threat-Intel-Management-Guide/Exclusion-List) or [TIM (XSOAR 8 Cloud)](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Delete-and-exclude-indicators)",
```
What about on-prem? https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Delete-and-exclude-indicators

2024-12-03 12:27 UTC, ShirleyDenkberg commented on Packs/VectraXDR/Integrations/VectraXDR/README.md
> +The administrator and Cortex XSOAR users on the recipient's list receive a notification when an integration experiences an incident fetch error. Cortex XSOAR users can select their notification metho
```suggestion
The administrator and Cortex XSOAR users on the recipient's list receive a notification when an integration experiences an incident fetch error. Cortex XSOAR users can select their notification method, such as email, from their user preferences. Refer to [XSOAR 6.13 documentation](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Receive-Notification-on-an-Incident-Fetch-Error) or [XSOAR 8 Cloud documentation](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Receive-notifications-on-an-incident-fetch-error) for more information.
```
What about on-prem?  https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Receive-notifications-on-an-incident-fetch-error

2024-12-03 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37473) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37473) it.</sub>

2024-12-03 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37473) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37473) it.</sub>

2024-12-03 15:28 UTC, yedidyacohenpalo commented on Packs/AnsibleAlibabaCloud/Integrations/AnsibleAlibabaCloud/README.md
> +See step 2 of this [XSOAR 6.12 guide](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.12/Cortex-XSOAR-Administrator-Guide/Run-Docker-with-Non-Root-Internal-Users), Or for XSOAR 8 use the [X
done

2024-12-03 15:37 UTC, yedidyacohenpalo commented on Packs/Base/Scripts/CreateIndicatorRelationship/README.md
> +[filter (XSOAR 6.13)](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Indicators) or [filter (XSOAR 6.13)](https://docs-cortex.paloaltonetworks.com/r/Cor
done

2024-12-03 15:46 UTC, yedidyacohenpalo commented on Packs/Flashpoint/Integrations/Ignite/README.md
> +Both incident types **Ignite Alert** and **Flashpoint Compromised Credentials** support the auto extraction feature by default. This feature extracts indicators and enriches their reputations using c
done

2024-12-03 16:17 UTC, yedidyacohenpalo commented on Packs/OTSecurity/README.md
> +[XSOAR 6](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations) or [XSOAR 8](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSO
done

2024-12-11 13:27 UTC, ShirleyDenkberg commented on Packs/Base/TestPlaybooks/playbook-Onion_address_extraction_test.yml
> +        - For Cortex XSOAR 8.7 On-prem use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script.
```suggestion
        - For Cortex XSOAR 6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations 
        - For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script
        - For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script
```

2024-12-11 13:27 UTC, ShirleyDenkberg commented on Packs/Base/TestPlaybooks/playbook-URLextraction-Test.yml
> +        - For Cortex XSOAR 8.7 On-prem use the link https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script.
```suggestion
        - For Cortex XSOAR 6 see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations 
        - For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script
        - For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script
```

2024-12-15 13:17 UTC, ShirleyDenkberg commented on Packs/ThreatIntelligenceManagement/Scripts/ThreatIntelligenceManagementGetIncidentsPerFeed/README.md
> +For Cortex XSOAR 6, see the https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations for Cortex XSOAR 8 Cloud, see the https://docs-cortex.paloaltone
```suggestion
- For Cortex XSOAR 6, see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
- For Cortex XSOAR 8 Cloud, see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script
- For Cortex XSOAR 8 On-prem, see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script
```

2024-12-15 13:17 UTC, ShirleyDenkberg commented on Packs/TrendMicroCAS/ReleaseNotes/1_1_9.md
> +- Documentation and metadata improvements.
```suggestion
Documentation and metadata improvements.
```

2024-12-15 13:17 UTC, ShirleyDenkberg commented on Packs/Use_Case_Builder/ReleaseNotes/1_0_12.md
> +- Documentation and metadata improvements.
```suggestion
Documentation and metadata improvements.
##### Use Case TIM Best Practice

Documentation and metadata improvements.

#### Playbooks

##### Use Case Builder

Documentation and metadata improvements.
```

2024-12-15 13:17 UTC, ShirleyDenkberg commented on Packs/VectraXDR/ReleaseNotes/1_0_8.md
> +- Documentation and metadata improvements.
```suggestion
Documentation and metadata improvements.
##### Dispatch Incident - Vectra XDR

Documentation and metadata improvements.
```

2024-12-15 13:17 UTC, ShirleyDenkberg commented on Packs/Vectra_AI/ReleaseNotes/2_0_2.md
> +- Documentation and metadata improvements.
```suggestion
Documentation and metadata improvements.
##### Close Duplicate XSOAR Incidents - Vectra Detect

Documentation and metadata improvements.
##### Dispatch Incident - Vectra Detect

Documentation and metadata improvements.
```

2024-12-15 13:17 UTC, ShirleyDenkberg commented on Packs/Veeam/ReleaseNotes/1_0_5.md
> +- Documentation and metadata improvements.
```suggestion
Documentation and metadata improvements.
##### Veeam - Start Configuration Backup

Documentation and metadata improvements.
##### Veeam - Start Instant VM Recovery Automatically

Documentation and metadata improvements.
```

2024-12-15 13:18 UTC, ShirleyDenkberg commented
@jbabazadeh Doc review completed.

2025-01-05 09:19 UTC, closed without merging