Add ErrorReasons to 'core-action-status-get' Command
demisto/content pull request #37483
Opened 2024-12-01 11:48 UTC by BEAdi

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12145

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-03 14:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37483) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37483) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37483) it.</sub>

2024-12-03 14:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37483) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37483) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37483) it.</sub>

2024-12-08 06:41 UTC, kobymeir commented
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12219590859)
- **Core** pack version was bumped to **3.2.0**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

2024-12-08 11:55 UTC, kobymeir commented
### This PR was automatically updated by a [GitHub Action](https://github.com/demisto/content/actions/runs/12221532525)
- **Core** pack version was bumped to **3.3.0**.

To stop automatic version bumps, add the `ignore-auto-bump-version` label to the github PR.

2024-12-29 07:22 UTC, jbabazadeh requested changes
Great work! please fix the tests

2024-12-29 07:22 UTC, jbabazadeh commented on Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
> +    #  add a case where it doesn't exist (an older version)
please add thee relevant tests and remove the comment

2024-12-29 07:28 UTC, BEAdi commented on Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
> +        return_results(command_results)
If we don't add this, the response will not show in the context and the fields won't be added

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
> +      description: The bucket that the error happened in.
```suggestion
      description: The bucket in which the error occurred.
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.RetrievedFiles.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.RetrievedFiles.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/Integrations/CortexXDRIR/README.md
> +| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket that the error happened in. |
```suggestion
| PaloAltoNetworksXDR.GetActionStatus.ErrorReasons.bucket | String | The bucket in which the error occurred. | 
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented on Packs/CortexXDR/ReleaseNotes/6_2_5.md
> +Added the **ErrorReasons** output to the following commands: ***xdr-file-quarantine***, ***xdr-file-restore***, ***xdr-endpoint-scan-execute***, ***xdr-file-retrieve***, ***xdr-snippet-code-script-ex
```suggestion
Added the **ErrorReasons** output to the following commands: 
- ***xdr-file-quarantine***
- ***xdr-file-restore***
- ***xdr-endpoint-scan-execute***
- ***xdr-file-retrieve***
- ***xdr-snippet-code-script-execute***
- ***xdr-script-commands-execute***
- ***xdr-file-delete-script-execute***
- ***xdr-file-exist-script-execute***
- ***xdr-kill-process-script-execute***
```

2025-01-06 12:38 UTC, ShirleyDenkberg commented
@jbabazadeh Doc review completed.

2025-01-14 08:06 UTC, jbabazadeh approved these changes
great work

2025-01-14 12:11 UTC, merged