Nozomi make result per run configurble
demisto/content pull request #37531
Opened 2024-12-02 14:23 UTC by nicoloereni

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
WIP draft
* add the possibility to decide how many incidents can be fetched per run
* max is 1000 min 20

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-02 14:25 UTC, kobymeir commented
Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @YairGlik will know the proposed changes are ready to be reviewed.
For your convenience, here is a [link](https://xsoar.pan.dev/docs/contributing/sla) to the contributions SLAs document.

2024-12-02 14:25 UTC, kobymeir commented
Hi @nicoloereni, thanks for contributing to the XSOAR marketplace. To receive credit for your generous contribution please follow this [link](https://xsoar.pan.dev/docs/packs/packs-format#contributorsjson).

2024-12-03 08:01 UTC, nicoloereni commented
> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @YairGlik will know the proposed changes are ready to be reviewed. For your convenience, here is a [link](https://xsoar.pan.dev/docs/contributing/sla) to the contributions SLAs document.

Hi @kobymeir, 
I'm waiting for this [PR](https://github.com/demisto/content/pull/37351) to be merged, then I open this to review.
Thanks for the support!

2024-12-03 14:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37531) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37531) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37531) it.</sub>

2024-12-03 14:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37531) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37531) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37531) it.</sub>

2024-12-12 08:58 UTC, YairGlik commented
Hi @nicoloereni,
I see that the PR is currently in draft status. If it's ready, please update the status so we can move forward.
Thank you!

2024-12-12 10:46 UTC, nicoloereni commented
> Hi @nicoloereni, I see that the PR is currently in draft status. If it's ready, please update the status so we can move forward. Thank you!

I'm waiting for green flag from our management. 
If it's better for your process I can close it and re-ope when we are ready

2024-12-12 12:56 UTC, YairGlik commented
> > Hi @nicoloereni, I see that the PR is currently in draft status. If it's ready, please update the status so we can move forward. Thank you!
> 
> I'm waiting for green flag from our management. If it's better for your process I can close it and re-ope when we are ready

No need to close it. I'll wait until you're ready to proceed.

2024-12-24 07:50 UTC, YairGlik commented
> Thank you for your contribution. Your generosity and caring are unrivaled! Make sure to register your contribution by filling the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form, so our content wizard @YairGlik will know the proposed changes are ready to be reviewed. For your convenience, here is a [link](https://xsoar.pan.dev/docs/contributing/sla) to the contributions SLAs document.

Hi @nicoloereni,

Thank you for your contribution! Please remember to fill out the [Contribution Registration](https://forms.gle/XDfxU4E61ZwEESSMA) form so we can review your changes. Let us know if you need any help!

2024-12-24 08:03 UTC, nicoloereni commented
https://github.com/user-attachments/assets/b9abccb6-ac9c-4aa6-9196-d53ebf0586a0

2024-12-24 15:36 UTC, YairGlik commented
Hi @nicoloereni,

It looks like there are some issues with line lengths in the test file:

NozomiNetworks_test.py:433:131: E501 Line too long (138 > 130 characters)
To fix this, please adjust the lines to meet the 130-character limit.

Additionally, please run the following commands:

`demisto-sdk split --input <path_to_yml_file>` to split your integration into the correct format.
`demisto-sdk pre-commit `to check and fix any remaining issues.
Let me know if you need any assistance! 😊

2025-01-07 18:18 UTC, YairGlik requested changes
Good job!

2025-01-08 08:15 UTC, nicoloereni commented on Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py
>          response = requests.request(
Hi @YairGlik,
thanks for your review.

I used the `requests` library because we started encountering issues with `_http_request`. When the verify parameter is set to `True`, we receive the following error:

'cortex xsoar Cannot set verify_mode to CERT_NONE when check_hostname is enabled.'

I wasn't able to disable `check_hostname`. So, I reviewed the other apps that use the verify configuration and noticed that they all use requests.request.

This happen on our demisto cloud instance version 6.6.0.

2025-01-08 18:06 UTC, YairGlik approved these changes

2025-01-08 18:09 UTC, merged