update: octoxlabs integration
demisto/content pull request #37676
Opened 2024-12-13 13:49 UTC by ogulcanhero

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Octox Labs Cyber Security Asset Management platform XSoar Integration update.

## Minimum version of Cortex XSOAR
- [x] 6.0.0
- [x] 6.1.0
- [x] 6.2.0
- [x] 6.5.0
- [x] 6.12.0 

## Must have
- [x] Tests
- [x] Documentation

2024-12-13 13:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37676) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37676) it.</sub>

2024-12-15 12:29 UTC, MLainer1 requested changes
Thank you for your contribution.
 A few notes:
 1. Make sure to add a human readable output for every command.
 2. Add tests for the new commands.

Let me know if you need any help/

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml
> +        description: 'List<Dict> Application information.'
```suggestion
        description: 'List Application information.'
```

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.py
> +        "octoxlabs-search-scroll-users-inventory": search_scroll_users,
This command is missing from the .yml file

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml
> +        description: 'List<Dict> Device information.'
```suggestion
        description: 'List Device information.'
```

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml
> +      - default:
In the code it looks like there is a default size: 50. It is better to add this in the description

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml
> +      - default:
In the code it looks like there is a default size: 1. It is better to add this in the description

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml
> +      - default:
In the code it looks like there is a default size: 1. It is better to add this in the description

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml
> +      - default:
In the code it looks like there is a default size: 50. It is better to add this in the description

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.py
> +        "octoxlabs-search-users-inventory": search_users_inventory,
This command is missing from the .yml file

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.py
> +
Is it necessary?

2024-12-15 12:29 UTC, MLainer1 commented on Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml
> +
Those 2 new parameters are not documented in the release notes

2024-12-16 07:05 UTC, ogulcanhero commented
Hi @MLainer1, thank you for your review. I'm having a problem with the demisto-sdk lint command. When I run the code, I get the error lint() got an unexpected keyword argument 'console_log_threshold'. Is this a known bug?

2024-12-16 14:51 UTC, MLainer1 commented
> Hi @MLainer1, thank you for your review. I'm having a problem with the demisto-sdk lint command. When I run the code, I get the error lint() got an unexpected keyword argument 'console_log_threshold'. Is this a known bug?

Hi @ogulcanhero, it is a known issue, and a fix will be out in the next few days.
You can use the `pre-commit` command in the mean time.

2024-12-16 18:08 UTC, ogulcanhero commented
Hi @MLainer1, I have 2 questions;

- Pre-commit is completely passed in my local, I couldn't understand the reason for the error here.
- Is there anything I need to do for the Legacy Validate test?

Thank You!

2024-12-18 11:05 UTC, MLainer1 commented
Hi @ogulcanhero, are you running the `demisto-sdk pre-commit` command? Is your demisto-sdk up to date with the latest version?

2024-12-18 19:30 UTC, ogulcanhero commented
Hi @MLainer1 ,
Yes, I use `demisto-sdk pre-commit` and I am sure that demisto-sdk is in the latest version because when I had a problem with lint, the first thing I did was to update demisto-sdk.

2024-12-19 10:09 UTC, MLainer1 commented
@ogulcanhero It looks like the pre-commit fails to add a dot at the end of some sentences. I think that adding that manually shouldn't take more than a few minutes.

2024-12-20 07:06 UTC, ogulcanhero commented
Hi @MLainer1, 
I think everything is ok. When can you merge.
Thank You!

2024-12-22 08:00 UTC, MLainer1 commented
Hi @ogulcanhero, let's schedule a demo to review your changes and make sure everything works as expected. I'll reach out through email to schedule it.

2024-12-30 12:05 UTC, ogulcanhero commented
Hi @MLainer1 , 
Thank you for the review. Is it possible for us to make the improvements you mentioned for now in the next version because our customer has been waiting for the features we added for a long time?
Have a nice day!

2024-12-30 12:42 UTC, MLainer1 commented
@ogulcanhero Yes, as the code works and my suggestions are for the visibility of the commands (human readable and better error management)

2024-12-30 13:34 UTC, MLainer1 commented
@ogulcanhero, is the PR finished on your side?

2024-12-30 16:43 UTC, ogulcanhero commented
Yes @MLainer1 , Thank you!

2024-12-31 07:57 UTC, MLainer1 approved these changes

2024-12-31 07:57 UTC, merged