Cisco ThousandEyes -  XSIAM Collector
demisto/content pull request #37681
Opened 2024-12-15 07:15 UTC by aaron1535

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10421)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-24 08:26 UTC, AradCarmi reviewed
First review, nicely done!

2024-12-24 08:44 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyesEventCollector/CiscoThousandEyesEventCollector.py
> +            pagination_offset = len(fetched_events) % 500
Done

2024-12-24 13:37 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyesEventCollector/CiscoThousandEyesEventCollector.py
> +        pagination_offset = 0 if current_batch_events else pagination_offset
Right
There can't be a situation where we started the fetch with a positive offset and the current_batch_events list would be empty
I'm resetting it anyway

2024-12-24 13:38 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyesEventCollector/CiscoThousandEyesEventCollector.py
> +            next_page_url = next_page_url or request_url
Done

2024-12-24 13:39 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyesEventCollector/CiscoThousandEyesEventCollector.py
> +) -> tuple[str, str]:
Done

2024-12-24 13:39 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyesEventCollector/CiscoThousandEyesEventCollector.py
> +    deduplicate_events(events, start_date, "startDate")
Done

2024-12-24 13:40 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyesEventCollector/CiscoThousandEyesEventCollector.py
> +    if any(d.get("offset") for d in (alert_next_run, audit_next_run)):
Done

2025-01-01 16:16 UTC, AradCarmi requested changes
Nice Work!
Please ask for a docs review.

2025-01-01 16:16 UTC, AradCarmi commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes_test.py
> +    def mock_http_request(method, full_url, params=None):
If this is the same in several places you can use it as a fixture function by adding `@pytest.fixture(autouse=True)` and treat it like a mocker in the test argument.

2025-01-02 07:37 UTC, ShirleyDenkberg commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes_description.md
> +If user has permission View activity log for all users in account group the logs returned include events across all the account groups they belong to.
```suggestion
If the user has View activity log permission for all users in the account group, the logs returned include events across all the account groups they belong to.
```

2025-01-02 07:37 UTC, ShirleyDenkberg commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/README.md
> +If user has permission View activity log for all users in account group the logs returned include events across all the account groups they belong to.
```suggestion
If the user has View activity log permission for all users in the account group, the logs returned include events across all the account groups they belong to.
```

2025-01-02 07:37 UTC, ShirleyDenkberg commented
@aaron1535 Need content for the pack readme.
@AradCarmi Doc review completed.

2025-01-02 09:06 UTC, aaron1535 commented on .gitignore
> +a.py
Temporarily
dropped

2025-01-02 09:25 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.yml
> +display: CiscoThousandEyes
Done

2025-01-02 09:26 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.yml
> +name: CiscoThousandEyes
Done

2025-01-02 10:00 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.py
> +RESPONSE_KEY = {"alerts": "alerts", "events": "auditEvents"}
Done

2025-01-05 12:52 UTC, OBavly approved these changes

2025-01-06 11:07 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.py
> +    pagination_offset = previous_offset
Moved to use prepare_next_run function

2025-01-06 11:23 UTC, aaron1535 commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.py
> +        response = client._http_request("GET", full_url=request_url, params=params)
I built the whole URL because I need it for `alert` type when the `fetch_limit` is lower than `page_size`
In that case, I need the full URL of that call to save to `next_page` in the `next_run`

2025-01-07 12:39 UTC, AradCarmi requested changes
Great work! please view my last comments.

2025-01-07 12:39 UTC, AradCarmi commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.py
> +        pagination_offset = 0
let's move this as we discussed.

2025-01-07 12:39 UTC, AradCarmi commented on Packs/CiscoThousandEyes/Integrations/CiscoThousandEyes/CiscoThousandEyes.py
> +    demisto.info(f"got {len(events)} before deduplication")
```suggestion
    demisto.debug(f"got {len(events)} before deduplication")
```

2025-01-08 08:56 UTC, AradCarmi approved these changes

2025-01-08 09:00 UTC, merged