CybelAngel pack for incidents
demisto/content pull request #37711
Opened 2024-12-16 13:50 UTC by dneilcybel

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-16 14:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37711) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37711) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37711) it.</sub>

2024-12-23 10:00 UTC, YairGlik commented
It seems there are some errors in the pre-commit checks. If you could fix them, we can move forward with the merge. Thank you!

2024-12-31 13:07 UTC, YairGlik requested changes
Good job!
I have a few things for you to check:

Why is this picture here?
`Packs/CybelAngel/Playbooks/CybelAngel_image.png
`
Please run `demisto-sdk pre-commit` and fix the comments.

Please bump the pack version in the `pack_metadata.json` file and add notes describing your changes to a new Release Notes file. To do that, please run the `demisto-sdk update-release-notes` command. For more information, see: [Release Notes Documentation](https://xsoar.pan.dev/docs/documentation/release-notes).

Thanks!

2024-12-31 13:20 UTC, YairGlik commented on Packs/CybelAngel/Integrations/CybelAngel/CybelAngel.py
> +    first_fetch_interval = int(demisto.params().get('first_fetch'))
```suggestion
    first_fetch_interval = arg_to_number(demisto.params().get('first_fetch'))
```

2024-12-31 13:21 UTC, YairGlik commented on Packs/CybelAngel/Integrations/CybelAngel/CybelAngel.py
> +    first_fetch = False if "first_pull" in demisto.getIntegrationContext().keys() else True
```suggestion
    first_fetch = "first_pull" not in demisto.getIntegrationContext().keys()
```

2024-12-31 13:23 UTC, YairGlik commented on Packs/CybelAngel/Integrations/CybelAngel/CybelAngel.py
> +        return_error('Failed to execute {} command.\nError:\n{}'.format(demisto.command(), str(e)))
```suggestion
        return_error(f'Failed to execute {demisto.command()} command.\nError:\n{str(e)}')

```

2024-12-31 13:26 UTC, YairGlik commented on Packs/CybelAngel/Integrations/CybelAngel/CybelAngel.py
> +        return_error('Failed to execute {} command.\nError:\n{}'.format(demisto.command(), str(e)))
The f-string provides better performance and readability, and it is the modern and most efficient way to work with strings.

2025-01-16 14:34 UTC, idovandijk submitted a review, later dismissed
Hi @dneilcybel, thank you so much for your patience and your work here.
I've reviewed the files and have some comments. The comments are numbered purely for convenience purposes and to make it easy to you to refer to if you have any questions. 

Please don't hesitate to reach out to us if you need help with anything or if something is not clear from the comments.

### General comments
1. Please make a distinction between generic, general purpose fields, such as "IP", and specific CybelAngel fields related to the external system. The incident fields you're adding are currently under the CybelAngel pack which is for XSIAM only - is this our intention?

The fields which are specific to CybelAngel should get a CybelAngel prefix (as indicated in the failed validations in the build). So "incident id" should become "CybelAngel Incident ID" or another name that includes the prefix of the pack name.

On the other hand, for any general purpose field not specific to CybelAngel, please take the following approach: If the field already exists in the content repo - use it instead.
If it doesn't exist, but you think it should be a common field because its name and type make it a good fit for other use-cases and vendors, please add it to the CommonTypes pack.

2. Your playbooks seem to all be set in run in Quiet Mode. This improves performance but it won't display the inputs, outputs and results of your tasks, which I think defeats the purpose of some of the playbooks. I suggest removing quiet-mode each playbook through the playbook settings.



### CybelAngel Display Report
3. I see that you're using ${alert.alertid} but that field does not exist. The field you're adding in this PR is called "incident id". If you did not write alertid, it's possible that it was changed automatically (and this is not the only place) when you imported your files into XSIAM - that's because XSOAR incidents are XSIAM alerts. Please check if there are similar issues like this one where the word "alert" is being used instead of "incident".

4. I believe the DT can be accomplished using transformers. Please check - there is a transformer that can turn 1 object into an array with 1 object - this ensures you always have an array. There is another transformer called Last Array Element IIRC which can take the last element of an array. I think using both together will be more readable.

<img width="359" alt="image" src="https://github.com/user-attachments/assets/0d7e0c6b-1a36-4e95-a602-29f34b2f04de" />

5. If the command `'cybelangel-get-report-pdf` has an input of `report_id` why are we passing incident/alert ID as the argument? Is this intentional? Maybe we can rename one of them?

### CybelAngel Get Attachement
6. I don't necessarily see a need for this playbook. Can it be accomplished in 1 task instead of 2? If so, we most likely don't need the playbook :) If you disagree, I'm happy to hear your opinion here
7. The naming of the tasks can be improved to be more indicative of their purpose.

### CybelAngel Get Comments, CybelAngel Post Comment, CybelAngel Send Remediation Request, CybelAngel Update Status
8. In my observation, these playbooks are redundant as they don't offer any value over running the command directly. Please remove them or alternatively provide a more comprehensive / expanded use-case scenario for the playbooks.


### CybelAngel (Alert Layout)
9. I don't see any usage of the incident fields in the layout. Wouldn't you want to display the fields in the layout? Other than that it looks good.

### CybelAngel (Classifier/Mapper)
10. Looks good, but once you make changes to the fields please make sure to update the mapper and playbooks too.

Once you're able to address these points please give us a heads up and we will confirm your changes, moving towards the final stage of the process.

2025-01-23 18:26 UTC, dneilcybel commented on Packs/CybelAngel/Integrations/CybelAngel/CybelAngel.py
> +        return_error('Failed to execute {} command.\nError:\n{}'.format(demisto.command(), str(e)))
Updated in code. Thank you

2025-02-16 12:54 UTC, YairGlick commented
Hi @dneilcybel,
URL and IP addresses were found in the following files, and they should not appear in the code:
fetch_incidents.json
get_report_by_id.json
baseintegration-dummy.json
Please replace the URL and IP addresses with a generic address such as example.com, or use the entries listed in the Tests/secrets_white_list.json file.
Thank you for your cooperation!

2025-02-18 13:28 UTC, idovandijk commented
Hi @dneilcybel just wanted to check that all is fine. I see that not all changes have made it to the playbook yet. Is this something you need help with?

2025-02-18 13:30 UTC, dneilcybel commented
Hi Ido,

Which playbook is the issue, from my side I removed all of the playbooks except for the CybelAngel Display reprots

2025-02-18 14:00 UTC, idovandijk commented
> Hi Ido,
> 
> Which playbook is the issue, from my side I removed all of the playbooks except for the CybelAngel Display reprots

I can see playbook `CybelAngel Display Report` but didn't see any changes there since we last spoke. Did I miss something? It is still configured to run in Quiet Mode and uses the same DT

2025-03-03 15:16 UTC, YairGlick commented
Hi @dneilcybel,
I noticed that you made changes to `pyproject.toml` and `poetry.lock`. Generally, these files shouldn’t be modified directly. Could you revert the changes? Is there a specific reason for them?

2025-03-03 15:22 UTC, dneilcybel commented
> Hi @dneilcybel, I noticed that you made changes to `pyproject.toml` and `poetry.lock`. Generally, these files shouldn’t be modified directly. Could you revert the changes? Is there a specific reason for them?

Hi @YairGlick I made the changes to update python version for the local testing. I will make revert these changes now!

2025-03-09 14:08 UTC, YairGlick commented
Hi @dneilcybel,
It seems there are some errors in the build. Please fix them so we can move forward.
Also, there are conflicts that need to be resolved.
Additionally, it looks like the License/CLA hasn't been signed. If you've already signed it, please sign it again.
Thanks!

2025-03-11 13:58 UTC, edik24 commented
@dneilcybel please update the metadata and the readme files as well

2025-03-11 13:59 UTC, YairGlick commented
Hi @dneilcybel ,
Please update the following files:  
1. **`pack_metadata.json`**  
   - Set `"support": "partner"`  
   - Add `"email": "<your_email_here>"`  
2. **`CybelAngelEventCollector.yml`**  
   - Add `supportlevelheader: xsoar`  
Let me know once it's done or if you have any questions. Thanks!

2025-03-11 14:14 UTC, dneilcybel commented
Hi @YairGlick just made the updates requested

2025-03-11 14:16 UTC, dneilcybel commented
Re-signed CLA

2025-03-20 15:00 UTC, YairGlick commented
It looks like there are some build failures that need to be fixed.
It also seems that demisto-sdk update-release-notes needs to be run.
Let me know if you need any further assistance.

2025-03-20 15:06 UTC, dneilcybel commented
Hi Yair, 

I am having issues running the recommended commands, I've run both commands prior to this commit and I keep running into the same issue. Would we be able to walk through this on a call?

2025-03-20 15:13 UTC, YairGlick commented
Would you like to jump on a call now, or would another time work better for you?

2025-03-20 15:14 UTC, dneilcybel commented
Right now works for me !

2025-03-20 15:16 UTC, YairGlick commented
What is your email address?

2025-03-26 12:58 UTC, dneilcybel commented
Hi @YairGlick is there anything that is needed from me to finish this integration?

2025-03-31 07:20 UTC, YairGlick commented
Hey @dneilcybel , thanks for the PR When would be a good time to schedule a demo? Let me know your availability.

2025-03-31 12:42 UTC, dneilcybel commented
Hi Yair,

I am available this morning until 10:30 EST (New York Time) 

Wednesday 9-10:30 AM EST
Thurday 9-11 AM EST

2025-04-06 15:00 UTC, YairGlick approved these changes
Great work!

2025-04-06 15:03 UTC, merged