Microsoft365Defender gcc endpoints addition
demisto/content pull request #37723
Opened 2024-12-17 10:25 UTC by noydavidi

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-6391)

## Description
Added the endpoints for Microsoft365Defender for gcc.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-22 13:09 UTC, ShirleyDenkberg commented on Packs/Microsoft365Defender/ReleaseNotes/4_5_39.md
> +- Added support for National Cloud.
```suggestion
Added support for National Cloud.
```

2024-12-22 13:09 UTC, ShirleyDenkberg commented on Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_10.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:09 UTC, ShirleyDenkberg commented on Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_18_1.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:09 UTC, ShirleyDenkberg commented on Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_23.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:09 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphAPI/ReleaseNotes/1_1_53.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:09 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphApplications/ReleaseNotes/1_3_0.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphCalendar/ReleaseNotes/1_1_29.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_1_34.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphFiles/ReleaseNotes/1_1_32.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphGroups/ReleaseNotes/1_1_53.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_2_57.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphMail/ReleaseNotes/1_6_23.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
-Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSearch/ReleaseNotes/1_0_17.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:10 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_22.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:11 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphTeams/ReleaseNotes/1_1_10.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:11 UTC, ShirleyDenkberg commented on Packs/MicrosoftGraphUser/ReleaseNotes/1_5_42.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:11 UTC, ShirleyDenkberg commented on Packs/MicrosoftManagementActivity/ReleaseNotes/1_4_0.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:11 UTC, ShirleyDenkberg commented on Packs/MicrosoftTeams/ReleaseNotes/1_5_11.md
> +- Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```suggestion
Added support for National Cloud in Microsoft 365 Defender, implemented in the Microsoft API Module.
```

2024-12-22 13:12 UTC, ShirleyDenkberg commented
@kobymeir @Shellyber @michal-dagan Doc review completed.

2024-12-23 10:50 UTC, kobymeir requested changes

2024-12-23 10:50 UTC, kobymeir commented on Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md
> +| Endpoint Type | The endpoint type. When selecting the Custom option, the Server URL parameter must be filled. | False |
endpoint type values table is missing, refer to other defender integrations.

2025-01-01 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37723) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37723) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: noydavidi<br/>:x: Content Bot<br/><hr/>**Content Bot** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37723) it.</sub>

2025-02-12 08:02 UTC, kobymeir requested changes

2025-04-23 13:29 UTC, closed without merging