Update content before upgrading pylint
demisto/content pull request #37732
Opened 2024-12-17 14:33 UTC by RotemAmit

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Update content before upgrading pylint

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-30 11:07 UTC, eyalpalo approved these changes
See my comment, also please run nightly before merging

2025-01-01 10:23 UTC, eyalpalo requested changes
Please go over the validations, and build steps. Will be approved after all is green before the force.

2025-01-01 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37732) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37732) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: RotemAmit<br/>:x: Content Bot<br/><hr/>**Content Bot** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37732) it.</sub>

2025-01-02 13:58 UTC, RotemAmit commented
Failures and explanations:

* pre-commit (github action) - fails since the PR contains too many files, and it can't handle it.
* **run-validations in gitlab.xdr.pan.local fails on:**
* Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.yml - [IN140] - The integration AWS Sagemaker is currently in skipped.
* Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.yml - [CJ105] - Either TroubleshootExecuteCommand does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.
* Packs/PrismaAccess/Integrations/PrismaAccess/PrismaAccess.yml - [CJ105] - Either TroubleshootExecuteCommand does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.
* Packs/AWS-NetworkFirewall/Integrations/AWS-NetworkFirewall/AWS-NetworkFirewall.yml - [CJ105] - Either TroubleshootExecuteCommand does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.
* **run-validations-new-validate-flow in gitlab.xdr.pan.local fails on:**
*

2025-01-15 11:05 UTC, RotemAmit commented
The run-validations step in ci/gitlab/gitlab.xdr.pan.local fails with the following error:
* Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.yml: [CJ105] - Either Windows Remote Management does not have any test playbooks or that all test playbooks in this pack are currently skipped, and there is no unittests file to be found.

2025-01-15 11:40 UTC, eyalpalo approved these changes

2025-01-15 11:46 UTC, RotemAmit commented
@ShahafBenYakir Can you force merge this PR?
A comment with the explanation is [here](https://github.com/demisto/content/pull/37732#issuecomment-2592365773).

2025-01-15 15:42 UTC, merged