Update Pack: CTM360
demisto/content pull request #37743
Opened 2024-12-18 08:59 UTC by edx-sayed-salem

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
None

## Description
Update the integration docker image.
Add another integration module.

## Must have
- [x] Tests
- [x] Documentation

2024-12-18 08:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37743) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37743) it.</sub>

2024-12-24 13:01 UTC, karinafishman commented
Here are some comments regarding the PR:

**Dashboard**
- Please notice that the dashboard is not on full screen, there is a space on the right side. You can see the difference with the default dashboards.
![image](https://github.com/user-attachments/assets/8182e1e4-06d5-4c88-93a6-51d44e1f5bc2)
**Release notes**
- Make sure you don't have unnecessary data like: </~XSIAM>.
**IncidentFields**
- Using "unsearchable": false can negatively affect the performance. Please, change it to True.
**Playbook**
- Please fix the general visualization of the playbook. The labels and the linking lines are not clear.
![image](https://github.com/user-attachments/assets/2e3125f4-23a3-4e13-b607-13d488bef42e)
- Task numbers: 25,26,27,28 are not linked to anything. Please link them to the end of the playbook or the relevant next task.
- Assign Analyst section header is not needed. Usually, we will use section headers that combine multiple tasks under the section header. In this case, the section header and the task after are the same.
- You have 2 same section headers: End of Playbook. Please use the same one. (In task 22)
**General comments**
- Please fix all the errors in the build.
- Check all the comments I added to the PR.

2024-12-25 07:56 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/ReleaseNotes/2_0_0.md
> +<~XSOAR> (Available from Cortex XSOAR 6.10.0).</~XSOAR>
Change made

2024-12-25 07:56 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/IncidentFields/incidentfields-Asset_Type.json
> +    "unsearchable": false,
Change made

2024-12-25 07:56 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/ReleaseNotes/2_0_0.md
> +
Change made

2024-12-25 07:57 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Playbooks/playbook-HackerView_Incident_Management.yml
> +              simple: In,Both
Change made

2024-12-25 07:58 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Playbooks/playbook-HackerView_Incident_Management.yml
> +      name: End of Playbook
Used one end section

2024-12-25 07:58 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Playbooks/playbook-HackerView_Incident_Management.yml
> +      name: Is Incident Closed?
Correction made

2024-12-25 07:59 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Playbooks/playbook-HackerView_Incident_Management.yml
> +              simple: inactive
Change made

2024-12-25 08:09 UTC, edx-sayed-salem commented
I'm not sure I have control over why the CI pre-commit fails, can anyone take a look?

2024-12-25 08:48 UTC, karinafishman commented
@edx-sayed-salem Did you executed "demisto-sdk pre-commit"?

2024-12-25 09:03 UTC, MLainer1 requested changes
Hi, thank you for your contribution.
I'm publishing the first half of the review, the second part will be published later.
Let me know if you need anything.

2024-12-25 09:21 UTC, edx-sayed-salem commented
> @edx-sayed-salem Did you executed "demisto-sdk pre-commit"?

Yes, it looks like something related to pylint and python 3.12 issue (the docker image version is 3.12)

2024-12-25 09:25 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +                return_results(hv_commands[demisto_command]())
For commands that take args and those that don't to get called correctly like: `get_remote_data_command(client, args)` and `get_mapping_fields()`

2024-12-25 09:27 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +            log(DEBUG, f'{incidents=}')
It's for debug though.

2024-12-25 09:44 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +        incidents = incidents[::max_fetch - 1]
Yes, this just ensures we don't exceed 200 incidents in 1 fetch. We store the greatest timestamp among the incidents further down in the function to be used in the next run to pick up where we left.

2024-12-25 10:30 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    )
Would adding `readable_output=tableToMarkdown(...)` argument to CommandResults be sufficient?

2024-12-25 10:45 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    log(DEBUG, f'map_and_create======{unmapped_incident=}')
Should I remove the debug statements or find those that may contain lists and slice them?

2024-12-25 10:55 UTC, MLainer1 commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    )
Yes

2024-12-25 11:59 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    log(DEBUG, f'{params=}')
These `args` and `params` should have nothing to do with the `demisto.params()` that may contain the user API credentials. `demisto.params()` is only being passed to `test_module()` as far as I know. Do we need to remove them?

2024-12-25 12:04 UTC, MLainer1 commented
> > @edx-sayed-salem Did you executed "demisto-sdk pre-commit"?
> 
> Yes, it looks like something related to pylint and python 3.12 issue (the docker image version is 3.12)

It is a known issue and a fix is in the works

2024-12-25 14:45 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +            log(DEBUG, f'{incidents=}')
Changed to log length of list

2024-12-25 14:45 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +        log(DEBUG, f'Demisto Args are {demisto_params=}')
Removed logging demisto_params

2024-12-25 14:46 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    )
Added readable_output

2024-12-25 14:46 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    )
Added readable_output

2024-12-25 14:47 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    log(DEBUG, f'{params=}')
Removed these

2024-12-25 14:47 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    log(DEBUG, f'{params=}')
Removed these

2024-12-25 14:47 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    log(DEBUG, f'{params=}')
Removed these

2024-12-25 14:47 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Integrations/HackerView/HackerView.py
> +    log(DEBUG, f'map_and_create======{unmapped_incident=}')
Removed

2024-12-25 14:47 UTC, edx-sayed-salem commented on Packs/CTM360-CyberBlindspot/Playbooks/playbook-HackerView_Incident_Management.yml
> +      name: Start Investgation
Corrected

2024-12-30 13:37 UTC, MLainer1 commented
@edx-sayed-salem Did you finish with the previous notes from the review? If so, make sure to request a second review from us to go over your changes.

2024-12-30 14:38 UTC, karinafishman approved these changes

2024-12-31 09:01 UTC, MLainer1 requested changes
Nice work!
Let's schedule a demo to check your changes and your new pintegration/
I'll reach out over on DFIR to schedule it.

2025-01-05 10:00 UTC, MLainer1 commented
Hi @edx-sayed-salem, looks like there are some pre-commit errors. can you have a look at them?

2025-01-06 06:09 UTC, edx-sayed-salem commented
> Hi @edx-sayed-salem, looks like there are some pre-commit errors. can you have a look at them?

Hi, yes it seems the same error from before about python 12 and ruff/pylint. There's another about `too many requests` when pulling from docker hub.

![image](https://github.com/user-attachments/assets/2e48e33c-396a-4808-8d94-0da6c6ecbb06)

![image](https://github.com/user-attachments/assets/55263541-2f55-4040-bd6c-1f9914327f42)

![image](https://github.com/user-attachments/assets/ec5a5117-ee8b-4fa1-86e0-815c8c485a76)

I think `too many requests` will solve itself, but ruff/pylint fix was said to be in the works.

2025-01-06 07:25 UTC, MLainer1 commented
> > Hi @edx-sayed-salem, looks like there are some pre-commit errors. can you have a look at them?
> 
> Hi, yes it seems the same error from before about python 12 and ruff/pylint. There's another about `too many requests` when pulling from docker hub.
> 
> ![image](https://private-user-images.githubusercontent.com/136978057/400316109-2e48e33c-396a-4808-8d94-0da6c6ecbb06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDg1ODksIm5iZiI6MTczNjE0ODI4OSwicGF0aCI6Ii8xMzY5NzgwNTcvNDAwMzE2MTA5LTJlNDhlMzNjLTM5NmEtNDgwOC04ZDk0LTBkYTZjNmVjYmIwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQwNzI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGM5MTdjMTJhNDA4ZjIxMTM5OGJlNjg2YmI5MDNmZmI4YTRmM2YwMWIyODk2MDRjNGQ3M2M3MDM2OTE4MTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TsAGP0iU4_WaH3_xvnnocdfevDXGDc55-wQ1f5UOl00)
> 
> ![image](https://private-user-images.githubusercontent.com/136978057/400316199-55263541-2f55-4040-bd6c-1f9914327f42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDg1ODksIm5iZiI6MTczNjE0ODI4OSwicGF0aCI6Ii8xMzY5NzgwNTcvNDAwMzE2MTk5LTU1MjYzNTQxLTJmNTUtNDA0MC1iZDZjLTFmOTkxNDMyN2Y0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQwNzI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTBkOTUxYTYzNThkZWY0YWY2YTM1YmI2YjlkNjAzZTQ0N2M2M2Q5OTQzZTZmYzIxOWIwOGNiYTFmYmMwMGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UcRURP-voGJbZtM3gpJrfI9T3BNkZ8ltsiaCJmcGang)
> 
> ![image](https://private-user-images.githubusercontent.com/136978057/400316445-ec5a5117-ee8b-4fa1-86e0-815c8c485a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDg1ODksIm5iZiI6MTczNjE0ODI4OSwicGF0aCI6Ii8xMzY5NzgwNTcvNDAwMzE2NDQ1LWVjNWE1MTE3LWVlOGItNGZhMS04NmUwLTgxNWM4YzQ4NWE3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQwNzI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDAyNTVhZDYwMTQ4MTFlYWMyMTE5NzJiYjViZmM0MWFlZWU2NDQ1NDA1YjU2NDI5NzMyNzcyNmU1NGQ3ZjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KTIVmdHLBBDtbTkw3sCIShil7hR-tMMtvYQOPyo9Gpc)
> 
> I think `too many requests` will solve itself, but ruff/pylint fix was said to be in the works.

Can you create another commit (can be empty) just to run the checks again? the fix should be deployed already

2025-01-06 08:39 UTC, edx-sayed-salem commented
ruff/pylint error remains

![image](https://github.com/user-attachments/assets/62867ac1-2398-4c66-a440-86c2f7a3ed0e)

2025-01-06 12:05 UTC, MLainer1 approved these changes

2025-01-06 12:27 UTC, MLainer1 commented
Hi @edx-sayed-salem 

> ruff/pylint error remains
> 
> ![image](https://private-user-images.githubusercontent.com/136978057/400360172-62867ac1-2398-4c66-a440-86c2f7a3ed0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjU1MzUsIm5iZiI6MTczNjE2NTIzNSwicGF0aCI6Ii8xMzY5NzgwNTcvNDAwMzYwMTcyLTYyODY3YWMxLTIzOTgtNGM2Ni1hNDQwLTg2YzJmN2EzZWQwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxMjA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGYxMWFjNTEyNjcyZTRkZDNjYjZkOTljODY5NjgzMGJmYThhNzZhMjM3MzhlMmQzYTE2MDVkYWI4ZDMxMDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oPX1cTj5S_uU3_HztNJA6ScpSdgtS_QewvL3tBhkJII)

After discussing with my team, we've decided it's best to hold off on updating the Docker image to Python 3.12. Instead, we should revert to the version prior to the latest one (demisto/python3:3.12.7.117934).

2025-01-06 12:52 UTC, edx-sayed-salem commented
> Hi @edx-sayed-salem
> 
> > ruff/pylint error remains
> > ![image](https://private-user-images.githubusercontent.com/136978057/400360172-62867ac1-2398-4c66-a440-86c2f7a3ed0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjU1MzUsIm5iZiI6MTczNjE2NTIzNSwicGF0aCI6Ii8xMzY5NzgwNTcvNDAwMzYwMTcyLTYyODY3YWMxLTIzOTgtNGM2Ni1hNDQwLTg2YzJmN2EzZWQwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxMjA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGYxMWFjNTEyNjcyZTRkZDNjYjZkOTljODY5NjgzMGJmYThhNzZhMjM3MzhlMmQzYTE2MDVkYWI4ZDMxMDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oPX1cTj5S_uU3_HztNJA6ScpSdgtS_QewvL3tBhkJII)
> 
> After discussing with my team, we've decided it's best to hold off on updating the Docker image to Python 3.12. Instead, we should revert to the version prior to the latest one (demisto/python3:3.12.7.117934).

Do I need to do anything?

2025-01-06 14:47 UTC, MLainer1 commented
> > Hi @edx-sayed-salem
> > > ruff/pylint error remains
> > > ![image](https://private-user-images.githubusercontent.com/136978057/400360172-62867ac1-2398-4c66-a440-86c2f7a3ed0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNjU1MzUsIm5iZiI6MTczNjE2NTIzNSwicGF0aCI6Ii8xMzY5NzgwNTcvNDAwMzYwMTcyLTYyODY3YWMxLTIzOTgtNGM2Ni1hNDQwLTg2YzJmN2EzZWQwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNlQxMjA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGYxMWFjNTEyNjcyZTRkZDNjYjZkOTljODY5NjgzMGJmYThhNzZhMjM3MzhlMmQzYTE2MDVkYWI4ZDMxMDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oPX1cTj5S_uU3_HztNJA6ScpSdgtS_QewvL3tBhkJII)
> > 
> > 
> > After discussing with my team, we've decided it's best to hold off on updating the Docker image to Python 3.12. Instead, we should revert to the version prior to the latest one (demisto/python3:3.12.7.117934).
> 
> Do I need to do anything?

Yes. reverse the dockerimage update you did in this PR

2025-01-07 07:10 UTC, MLainer1 commented
Looks good! I'll merge the PR

2025-01-07 07:10 UTC, merged