Cybersixgill DVE feed max indicators fix
demisto/content pull request #37742
Opened 2024-12-18 08:26 UTC by syed-loginsoft

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] Ready

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [x] Tests
- [x] Documentation

2024-12-18 08:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37742) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37742) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37742) it.</sub>

2024-12-18 12:00 UTC, YairGlik requested changes

2024-12-18 12:42 UTC, syed-loginsoft commented
Please wait for merge. We are verifying changes in our environment.

2024-12-18 18:17 UTC, YairGlik commented
> Please wait for merge. We are verifying changes in our environment.

I'm waiting, please let me know if you want to move forward.

2024-12-23 05:40 UTC, syed-loginsoft commented
> > Please wait for merge. We are verifying changes in our environment.
> 
> I'm waiting, please let me know if you want to move forward.

Done. Please move forward. 
Thanks for waiting.

2024-12-23 06:25 UTC, merged