New Integration for Gatewatcher-AionIQ Pack
demisto/content pull request #37769
Opened 2024-12-19 10:50 UTC by clement-lyonnet

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: -

## Description
New Integration for the Gatewatcher AionIQ Pack.
This integration bring the fetch incidents support for the new version of the GCenter (v103)

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-19 10:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37769) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37769) it.</sub>

2024-12-22 12:59 UTC, karinafishman commented
Hi, here are some comments regarding the PR:

1. I saw that there are 2 incident types, is there any need to have 2 types? they look the same besides the name. 
2. I saw that you created  2 mappers. While it is possible to use the same mapper for several incident types, please consider using only one mapper. 
3. Go over all fields:
  - Change incident field names (inside json) to look normal. (without any punctuation marks), The names of the fields should be readable and understandable to the users. It's hard to understand what does "Gatewatcher dcerpc.res" field means.
  - Consider using existing fields. For example, for destination IP we already have a field for that: ״destinationip״
  - In field types verify you used the correct types. for example for date use date type and no shortext. 
  - incident fields file names to look normal. Meaningful names without numbers. For example (incidentfield-Destination_IPs.json and not incidentfield-Gatewatcher-99.json)
4. In Incident fields: Unsearchable=False may cause XSOAR to be slow. please change all of them to true.

2024-12-22 13:00 UTC, karinafishman requested changes

2024-12-24 11:07 UTC, amshamah419 requested changes

2024-12-24 11:07 UTC, amshamah419 commented on Packs/Gatewatcher-AionIQ/Integrations/GCenter103/GCenter103.py
> +        if proxy:
You can use the `handle_proxies()` func from CommonServer which should also cover some edgecases.

2024-12-24 11:07 UTC, amshamah419 commented on Packs/Gatewatcher-AionIQ/Integrations/GCenter103/GCenter103.py
> +    return e_s
You can try something like this:

```suggestion
def fix_broken_list(params: Dict[str, Any]) -> List[str]:
    if 'engine_selection' not in params or not isinstance(params['engine_selection'], (str, list)):
        raise ValueError("Invalid 'engine_selection' parameter")

    bdl = params['engine_selection']

    known_engines = {
        "malcore", "shellcode_detect", "malicious_powershell_detect",
        "sigflow_alert", "dga_detect", "active_cti", "retrohunt",
        "ransomware_detect", "beacon_detect"
    }
    e_s = []

    if isinstance(bdl, str):
        e_s = [engine for engine in known_engines if engine in bdl]
    elif isinstance(bdl, list):
        e_s = [engine for engine in known_engines if engine in bdl]

    return e_s
```

2024-12-26 08:49 UTC, clement-lyonnet commented
> Hi, here are some comments regarding the PR:
> 
>     1. I saw that there are 2 incident types, is there any need to have 2 types? they look the same besides the name.
> 
>     2. I saw that you created  2 mappers. While it is possible to use the same mapper for several incident types, please consider using only one mapper.
> 

Hi, regarding these questions:

1. We choose to use 2 Incident Types in order to have 2 different Layouts. These incidents do not have the same verbosity.
2. We were not able to use 1 Incoming Mapper for 2 Incident Types: one of the Incident Types was not mapped at all. Maybe we missed something in the manner to do so.

2024-12-26 08:54 UTC, clement-lyonnet commented on Packs/Gatewatcher-AionIQ/IncidentFields/incidentfield-Gatewatcher-121.json
> +    "name": "Gatewatcher krb.sname",
Giving these fields a more detailed name will be accepted ? e.g. krb.cname -> krb auth username, krb.sname -> krb service name

2024-12-26 11:06 UTC, karinafishman commented on Packs/Gatewatcher-AionIQ/IncidentFields/incidentfield-Gatewatcher-121.json
> +    "name": "Gatewatcher krb.sname",
yes, I think it will be better :)

2025-01-02 06:32 UTC, amshamah419 commented
Hi @clement-lyonnet, just checking in. Hope you had a great New Years! Please let me know if there is anything I can do to assist.

2025-01-02 08:41 UTC, clement-lyonnet commented
Hi @amshamah419, I wish you an happy New Year ! :tada: 
Thanks for checking in.
I think I applied correctly the suggested changes, so I think it is ready for a second review from your side :smiley:

2025-01-02 08:54 UTC, amshamah419 commented
Fantastic! I think on my end, we are good to go. I'll approve shortly. @karinafishman everything look good on your end?

2025-01-02 09:41 UTC, karinafishman commented
It looks fine to me. Approved.

2025-01-05 22:04 UTC, amshamah419 commented
Hi @clement-lyonnet, I'm trying to get the pack to pass validations and it looks like we are failing on a few things. Most I can take care of for you, however, these ones I am a bit hesitant to change since I'm not sure where the changes would effect your other content items.

>Following prefixes are allowed for this IncidentField:
Gatewatcher AionIQ
Packs/Gatewatcher-AionIQ/IncidentFields/incidentfield-Gatewatcher_NFS_file_transmission.json: [IF113] - Field name must start with the relevant pack name or one of the item prefixes found in pack metadata.

Can you please take a look?

2025-01-06 09:27 UTC, clement-lyonnet commented
> Hi @clement-lyonnet, I'm trying to get the pack to pass validations and it looks like we are failing on a few things. Most I can take care of for you, however, these ones I am a bit hesitant to change since I'm not sure where the changes would effect your other content items.
> 
> > Following prefixes are allowed for this IncidentField:
> > Gatewatcher AionIQ
> > Packs/Gatewatcher-AionIQ/IncidentFields/incidentfield-Gatewatcher_NFS_file_transmission.json: [IF113] - Field name must start with the relevant pack name or one of the item prefixes found in pack metadata.
> 
> Can you please take a look?

Hi @amshamah419, I have updated the fields :blush:
I hope it will passes the tests, let me know if not.
Thank you

2025-01-07 08:28 UTC, merged