CIAC-11415
demisto/content pull request #37778
Opened 2024-12-19 12:53 UTC by ilaredo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2025-01-01 13:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37778) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37778) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37778) it.</sub>

2025-01-06 07:35 UTC, ShirleyDenkberg commented
@eyalpalo Looks good.  Doc review completed.

2025-01-21 09:20 UTC, eyalpalo requested changes
Very nice! see my notes, and also:
1. Please add docstring to all methods/
2. Please add tests to test the start date and end date in consecutive fetches

2025-01-21 09:20 UTC, eyalpalo commented on Packs/Absolute/ReleaseNotes/1_0_25.md
> +- Added the ability to fetch events in Cortex XSIAM.
```suggestion
- Enhanced Cortex XSIAM with the capability to fetch events.
```

2025-01-21 11:30 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        datetime.strptime(last_end_date, "%Y-%m-%d %H:%M:%S") if last_end_date else end_date - timedelta(minutes=1))
in case no last end date meaning this is the first fetch, start date will be one minute ago and end date now

2025-01-22 14:29 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +    if start_date > end_date:
it just return no entries

2025-01-27 11:39 UTC, eyalpalo requested changes
Almost there, nice job!

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        request_payload_data = self.prepare_request_payload(request_data)
In the prepare request data method the payload is always an empty dict. Why do we need the prepare_request_payload?

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        headers = self.prepare_request_headers(request_data)
Are those headers relevant to all requests?

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +                                  headers={"content-type": "text/plain"}, timeout=60)
What is the default value for timeout? Not sure we need to pass it

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        return response
```suggestion
        return self.perform_request(signed)
```

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +def prepare_query_string_for_fetch_events(page_size: int = None, start_date: datetime = None, end_date: datetime = None,
This method is logically related to the Client. Let's move it to be there.

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +    def fetch_events(self, query_string: str) -> dict[str, Any]:
```suggestion
    def fetch_events_request(self, query_string: str) -> dict[str, Any]:
```

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +    # TODO: remove this temp start_date
Please remove

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +    # TODO: remove this temp start_date
Also here

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +def fetch_events(client: ClientV3, fetch_limit: int, last_run: Dict[str, Any]) -> tuple[List[Dict[str, Any]], Dict[str, Any]]:
Please add docstring

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +def prepare_query_string_for_fetch_events(page_size: int = None, start_date: datetime = None, end_date: datetime = None,
Please add docstring to explain the logic

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        datetime.strptime(last_end_date, "%Y-%m-%d %H:%M:%S") if last_end_date else end_date - timedelta(minutes=7))
why timedelta of 7?

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +    events, latest_events_id = handle_duplication_and_add_time_field_to_events_and_get_latest_events(all_events,
if all_events is empty, the handle_duplication_and_add_time_field_to_events_and_get_latest_events method should return empty list of events and empty array of latest_events_id. If so, we can remove the if condition and leave just the return statement at the end of the method.

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +def handle_duplication_and_add_time_field_to_events_and_get_latest_events(events: List[Dict[str, Any]],
Please add docstring, and think of a simpler name to this method.

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +            continue
```suggestion
        if event.get('id') in last_run_latest_events_id:
            continue
```
This condition should be enough to handle duplication

2025-01-27 11:39 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        headers_v3: dict = {"content-type": "text/plain"}
This can be global

2025-01-27 12:29 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        request_payload_data = self.prepare_request_payload(request_data)
you are right, no need.

2025-01-27 12:35 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +                                  headers={"content-type": "text/plain"}, timeout=60)
default value is 0. but in requests.post was 60. so i tried to align it with the raw request, but it is not necessary to pass it, it also works without it.
removed.

2025-01-27 12:43 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +            continue
i did it in purpose to reduce the times of checking if id exist in the list. 
think about it, if there is 1000 events, and last_run_latest_events_id hold some id's (maybe could be also large number), why to pass with all the 1000 over the list?

2025-01-27 13:04 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        datetime.strptime(last_end_date, "%Y-%m-%d %H:%M:%S") if last_end_date else end_date - timedelta(minutes=7))
for testing. i will change after the demo

2025-01-27 15:05 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +    # TODO: remove this temp start_date
for testing. i will remove after the demo

2025-01-27 15:05 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +    # TODO: remove this temp start_date
for testing. i will remove after the demo

2025-01-30 08:45 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +                                  headers={"content-type": "text/plain"}, timeout=60)
The default is set to 60... We can look at it together if you want

2025-01-30 13:09 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        latest_event_time = ''
Not sure it is needed. If there are no events this is already ''. If there are events it has value.
If the latest event was filtered out, it means all events were duplications and we still want to fetch from the latest event we found so far...

2025-01-30 13:15 UTC, eyalpalo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +            headers=HEADERS_V3,
We can change the init method of the Client to get the HEADERS_V3 if no headers were passed... and here not to pass headers.

2025-01-30 13:35 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        fetch_limit *= 2
you mean by default each fetch, fetch limit will set to  fetch_limit + len(last_run_latest_events_id) ?

2025-01-30 14:55 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +        latest_event_time = ''
this handling the following case:
fist fetch some events, last run will hold latest_events_id, latest_event_time.
next fetch lets say fetch only 1 event, the same event of the last events id, because the new start date is the same time of the latest event time of last fetch.
now in process events, this event is duplicated and we will continue in the loop and finish with filtered_events = [], but latest_event_time is not ''.
if you need live explanation, lets zoom it few minutes

2025-01-30 15:06 UTC, ilaredo commented on Packs/Absolute/Integrations/Absolute/Absolute.py
> +            next_page_token = response.get('metadata', {}).get('pagination', {}).get('nextPage', '')
case events not in the same time: this will work without next page token because my next fetch will start from the last fetched event.
case events in the same time: as we decided, if we assume that the fetch limit is big enough, and the possibility of big number of events to be at the same time is very small, we can handle this situation with adding to the fetch limit the length of last_fetch_events_id list

2025-02-02 19:56 UTC, eyalpalo approved these changes
Great

2025-02-06 07:30 UTC, merged