Make GetIncidentTasks compatible with tenants
demisto/content pull request #37783
Opened 2024-12-20 13:12 UTC by OneToughMonkey

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
The GetIncidentTasks automation from the Cortex REST API Content Pack fails for incidents on tenants with "Work plan for incident XY has no tasks.". This minor change addresses this while maintaining backwards compatibility for non-tenant incidents.

## Must have
- [x] Tests
- [x] Documentation

2024-12-20 13:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37783) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37783) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37783) it.</sub>

2024-12-22 12:33 UTC, MLainer1 requested changes
Hi @OneToughMonkey, thank you for your contribution!
Please make sure to add a release note file, and increase the pack version. You can use the `demisto-sdk update-release-notes` command

2024-12-31 12:16 UTC, MLainer1 commented
Hi @OneToughMonkey, do you need help with any change for the PR?

2024-12-31 16:30 UTC, OneToughMonkey commented
Hi, sorry, I can do as requested when I am back from holidays in the week starting Jan 13th.On 31. Dec 2024, at 13:17, MLainer1 ***@***.***> wrote:﻿
Hi @OneToughMonkey, do you need help with any change for the PR?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-27 10:31 UTC, OneToughMonkey commented
jesus, sorry for the mass tagging... trying to figure this out

2025-01-30 12:27 UTC, OneToughMonkey commented
scratch this, just figured out that the REST API integration has a configuration option to use tenants by default

2025-01-30 12:27 UTC, closed without merging