[New Pack] - Internal - UVEM - Cortex VM
demisto/content pull request #37799
Opened 2024-12-22 12:07 UTC by BigEasyJ

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[UVEM-557](https://jira-dc.paloaltonetworks.com/browse/UVEM-557)

## Description
Please review ticket

## Must have
- [x] Tests
- [x] Documentation

2024-12-26 09:01 UTC, YairGlik commented
Hi @BigEasyJ ,

Thank you so much for your contribution!  Please note that the PR is still marked as a draft. If you're ready to proceed with it, kindly change its status to open.

Let me know if you need any assistance!

2024-12-26 11:35 UTC, karinafishman commented
Hi, here are some comments regarding the PR:

- I can't see the release notes added to the vulnerability management pack.
- Images of the playbooks are missing.
- Missing Release note for Cortex VM - ServiceNow CMDB playbook.
- Please fix all the errors in the build.

2025-01-16 12:14 UTC, mayyagoldman requested changes
Hey @BigEasyJ, 

Great work, thank you! 🎉 Please take a look at my small comments. 😊

2025-01-16 12:14 UTC, mayyagoldman commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +      name: Initialize grid fields - TODO add new field/possibly remove
I noticed there’s a TODO left here—please address it or remove it.

2025-01-16 12:14 UTC, mayyagoldman commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +      description: 'TODO Edit Given the IP address this playbook enriches ServiceNow CMDB information relevant to ASM alerts. '
I noticed there’s a TODO left here—please address it or remove it.

2025-01-16 12:14 UTC, mayyagoldman commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue_README.md
> +* Cortex Core - IR
Ensure that the playbooks verify whether the integration brand is active.

2025-01-17 20:59 UTC, johnnywilkes commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue_README.md
> +* Cortex Core - IR
This brand should always be active for XSIAM/platform

2025-01-17 21:46 UTC, johnnywilkes commented
@ShirleyDenkberg , can you please review?

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB.yml
> +description: 'Given provided indicators (IPs, Hostnames, FQDNs, etc) this playbook enriches ServiceNow CMDB information relevant to vulnerability issues.'
```suggestion
description: 'Given provided indicators (IPs, Hostnames, FQDNs, etc.) this playbook enriches ServiceNow CMDB information relevant to vulnerability issues.'
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB.yml
> +        Subplaybook for finding CI records in ServiceNow CMDB.
```suggestion
        Sub-playbook for finding CI records in ServiceNow CMDB.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB.yml
> +        Subplaybook for finding CI records in ServiceNow CMDB.
```suggestion
        Sub-playbook for finding CI records in ServiceNow CMDB.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB.yml
> +        Subplaybook for finding CI records in ServiceNow CMDB.
```suggestion
        Sub-playbook for finding CI records in ServiceNow CMDB.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB.yml
> +        Subplaybook for finding CI records in ServiceNow CMDB.
```suggestion
        Sub-playbook for finding CI records in ServiceNow CMDB.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB_README.md
> +Given provided indicators (IPs, Hostnames, FQDNs, etc) this playbook enriches ServiceNow CMDB information relevant to vulnerability issues.
```suggestion
Given provided indicators (IPs, Hostnames, FQDNs, etc.) this playbook enriches ServiceNow CMDB information relevant to vulnerability issues.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB_README.md
> +* servicenow-query-users
```suggestion
ServiceNow CMDB Search

### Integrations

ServiceNow v2

### Scripts

GridFieldSetup

### Commands

servicenow-query-users
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_ServiceNow_CMDB_README.md
> +| FQDN | Fully Qualified Domain Name |  | Optional |
```suggestion
| IPv4 | IPv4 address. |  | Optional |
| IPv6 | IPv6 address. |  | Optional |
| HostName | Hostname. |  | Optional |
| FQDN | Fully Qualified Domain Name. |  | Optional |
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
```suggestion
       For Cortex XSOAR 6.13, see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.13/Cortex-XSOAR-Administrator-Guide/Automations
       For Cortex XSOAR 8 Cloud, see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Scripts
       For Cortex XSOAR on-prem, see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Scripts
       For Cortex XSIAM, see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Documentation/Automations

```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +      description: Extract all indicators according to server indicators configuration
```suggestion
      description: Extract all indicators according to the server indicators configuration.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +      description: 'Given provided indicators (IPs, Hostnames, FQDNs, etc), enriches ServiceNow CMDB information relevant to vulnerability issues.'
```suggestion
      description: 'Given provided indicators (IPs, Hostnames, FQDNs, etc.), enriches ServiceNow CMDB information relevant to vulnerability issues.'
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +      description: Sleep for X seconds
```suggestion
      description: Sleep for X seconds.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +      description: Checks if there an email that is n/a?
```suggestion
      description: Checks if there an email that is n/a.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue.yml
> +      description: Checks if there an email that is not n/a?
```suggestion
      description: Checks if there an email that is not n/a.
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/Playbooks/Cortex_VM_-_Vulnerability_Issue_README.md
> +* Cortex Core - IR
```suggestion
Cortex VM - ServiceNow CMDB

### Integrations

Cortex Core - IR
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/README.md
> +By leveraging the vulnerability detection capabilities present in many of the core and optional XSIAM add-ons, XSIAM is able to help organizations make sense of their vulnerability posture and take m
```suggestion
By leveraging the vulnerability detection capabilities present in many of the core and optional Cortex XSIAM add-ons, Cortex XSIAM is able to help organizations make sense of their vulnerability posture and take mitigating actions. 
```

2025-01-19 06:23 UTC, ShirleyDenkberg commented on Packs/CortexVulnerabilityManagement/README.md
> +A playbook that given provided indicators (IPs, Hostnames, FQDNs, etc), enriches ServiceNow CMDB information relevant to vulnerability issues.
```suggestion
A playbook that when given provided indicators (IPs, Hostnames, FQDNs, etc.), enriches ServiceNow CMDB information relevant to vulnerability issues.
```

2025-01-19 06:24 UTC, ShirleyDenkberg commented
@johnnywilkes @mayyagoldman @karinafishman Doc review completed.

2025-01-19 14:49 UTC, mayyagoldman commented
Hey @BigEasyJ , 

Is the PR intentionally still in draft status?  

I’ve handled the first two issues you mentioned. Regarding the release notes (RN) for a new contribution pack, this is a known issue, and there is an [open development bug](https://jira-dc.paloaltonetworks.com/browse/CIAC-12482) addressing it. Let me know if you need further clarification! 😊

> @mayyagoldman, can you please show us how to fix these? https://github.com/demisto/content/actions/runs/12836737677/job/35798998093?pr=37799 https://github.com/demisto/content/actions/runs/12836737676/job/35798998146?pr=37799
> 
> Also, typically you dont have a release notes for 1.0.0 so how can we fix the build errors in here? https://github.com/demisto/content/actions/runs/12837076169/job/35800010100?pr=37799
> 
> Thank you in advance

2025-01-24 15:29 UTC, johnnywilkes commented
@mayyagoldman, yes the PR is still in draft for us to finish our testing

2025-01-28 12:28 UTC, mayyagoldman approved these changes

2025-01-28 12:28 UTC, merged