Generic event collector
demisto/content pull request #37806
Opened 2024-12-22 18:29 UTC by kobymeir

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: CIAC-11325

## Description
CIAC-11325 [Integration] - Generic REST API Event Collector Integration

## Must have
- [ ] Tests
- [ ] Documentation

2025-02-17 09:21 UTC, JasBeilin requested changes
Nice!
There were some pieces of code I believe can be improved and some edge cases that needs to be consider but overall it looks great.
Please check my comments and add more debug logs.

2025-02-17 09:21 UTC, JasBeilin commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +def iso8601_to_datetime_str(iso8601_time: str) -> str:
Worth adding log of the input since if the method will fail, there will be no way of understanding the issue.

2025-02-17 09:21 UTC, JasBeilin commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +        events = client.search_events(endpoint=endpoint,
When not sending the time, fetch can tak a long time, worth checking for limitation using of starting time of 1 day at most.

2025-02-17 09:21 UTC, JasBeilin commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_test.py
> +    org_dict = {'key1': 'value1', 'key2': {'key3': 'value3'}}
Don't we wat to also check the case where 
    org_dict = {'key1': 'value', 'key2': {'key3': 'value'}}
    substitutions = [('value', 'new_value1')]

2025-02-17 09:21 UTC, JasBeilin commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_test.py
> +    events = {'next_page': 'page2', 'has_more': True}
What about cases where the events json contain only next_page?

2025-02-17 09:21 UTC, JasBeilin commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_test.py
> +def test_is_pagination_not_needed():
In most cases when pagination is not needed, the next page will no be accounted for.

2025-02-17 09:21 UTC, JasBeilin commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_test.py
> +
when using the safe_load there is no need for this test.

2025-02-17 12:39 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +            params=request_data.query_params,
missing ok_codes=204

2025-02-17 12:55 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +    pagination_needed: bool = argToBoolean(params.get('pagination_needed', False))
add logs

2025-02-23 10:09 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_image.png
yes

2025-02-23 10:10 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +MAX_INCIDENTS_TO_FETCH = 10_000
python supports integer commas `,` using `_`

2025-02-23 10:13 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +KNOWN_TIME_FORMATS = [
future support, i removed the function that used it. i will remove this in the meantime.

2025-02-23 11:10 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +            params=request_data.query_params,
added support, with default to "200"

2025-02-23 11:13 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +def organize_events_to_xsiam_format(raw_events: Any, events_keys: list[str]) -> list[dict[str, Any]]:
yes, it's in the fetch_events function

2025-02-23 11:18 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +        # to prevent duplicates, we are only adding events with creation_time > last fetched incident
as discussed, it's a decision we will proceed with at this time.

2025-02-23 11:20 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +        if incident_created_dt > last_fetched_datetime:
As discussed, a design decision that I'm ok with.

2025-02-23 11:25 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +                # We assume the last event contains the last id.
The point is that some APIs need the last ID for the pagination, and in case the ID is a hash/string the ID type should be a string.

2025-02-23 15:45 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +    return json.loads(json_str)
changing.

2025-02-23 15:47 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +
will use safe_load_json, but here i want to return None when no json object is passed. rather than an empty dict/list that safe_load_json returns.

2025-02-23 15:47 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.py
> +                events = organize_events_to_xsiam_format(raw_events, events_keys)
the code is correct.

2025-02-23 15:54 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    display: Server URL
done. although pycharm doesn't show it.

2025-02-23 15:54 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +      - POST
will add if someone wants it. for now no.

2025-02-23 15:55 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: "API Key to access the service REST API."
type 9 doesn't have additionalinfo. will be removed.

2025-02-23 17:19 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_description.md
> +   Vendor and Product values are added so that data can be ingested and categorized properly. The name of the ingested dataset will be in the format: `{Vendor}_{Product}_generic`
the `_raw` comes from the platform.

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: Add the endpoint you want to collect data from (Alert/Events Etc..)
```suggestion
    additionalinfo: Add the endpoint you want to collect data from (Alert/Events, etc.).
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: Select the authentication method
```suggestion
    additionalinfo: Select the authentication method.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: 'If the additional header are required,
```suggestion
    additionalinfo: 'If the additional header is required,
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +     please add it here in a dictionary format {unique_field : 286} if there''s
```suggestion
     add it here in dictionary format {unique_field : 286}. If there''s
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    a need to add more then one use it in this format: {''field-1'': value_example,
```suggestion
    a need to add more then one, use it in this format: {''field-1'': value_example,
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: 'Enter vendor name for dataset'
```suggestion
    additionalinfo: Enter vendor name for dataset.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: 'Enter product name for dataset'
```suggestion
    additionalinfo: Enter product name for dataset.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    please add it here in a dictionary format {unique_field : 286} if there''s
```suggestion
    add it here in dictionary format {unique_field : 286}. If there''s
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    a need to add more then one use it in this format: {''field-1'': value_example,
```suggestion
    a need to add more then one, use it in this format: {''field-1'': value_example,
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: 'If the product requires a different initial DATA,  please add it here in a dictionary format {unique_field : 286} if there''s
```suggestion
    additionalinfo: 'If the product requires a different initial DATA, add it here in dictionary format {unique_field : 286}. If there''s
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    a need to add more then one use it in this format: {''field-1'': value_example,
```suggestion
    a need to add more then one, use it in this format: {''field-1'': value_example,
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: 'If required to pass JSON data when calling the API to collect data, please add it here in a dictionary format {unique_field : 286} if there''s
```suggestion
    additionalinfo: 'If required to pass JSON data when calling the API to collect data, add it here in dictionary format {unique_field : 286}. If there''s
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    a need to add more then one use it in this format: {''field-1'': value_example,
```suggestion
    a need to add more then one, use it in this format: {''field-1'': value_example,
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    additionalinfo: 'If the product requires a different initial request JSON, please add it here in a dictionary format {unique_field : 286} if there''s
```suggestion
    additionalinfo: 'If the product requires a different initial request JSON, add it here in dictionary format {unique_field : 286}. If there''s
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    a need to add more then one use it in this format: {''field-1'': value_example,
```suggestion
    a need to add more then one, use it in this format: {''field-1'': value_example,
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    a need to add more then one use it in this format: {''field-1'': value_example,
```suggestion
   please add it here in dictionary format {unique_field : 286}. If there''s
    a need to add more then one, use it in this format: {''field-1'': value_example,
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    display: 'Events lookup path in the response JSON, dot seperated, e.g. "data.items".'
```suggestion
    additionalinfo: 'The name of the event creation time in the response data, e.g., "timestamp" or "created_at".'
  - name: events_keys
    section: Collect
    display: 'Events lookup path in the response JSON, dot-separated, e.g. ,"data.items".'
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +    display: 'Event ID lookup path in the event response JSON, dot seperated, e.g. "id".'
```suggestion
    display: 'Event ID lookup path in the event response JSON, dot-separated, e.g., "id".'
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_description.md
> +   No Authorization (for publicly accessible data)
```suggestion
   - Basic Authentication (username and password)
   - Token Based Authentication (Token key)
   - Bearer Token (API key)
   - Raw Token (for custom token-based authentication)
   - No Authorization (for publicly accessible data)
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_description.md
> +   POST (if the endpoint requires sending specific parameters to retrieve data)
```suggestion
   - GET (to retrieve information)
   - POST (if the endpoint requires sending specific parameters to retrieve data)
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector_description.md
> +Note: This is a beta Integration, which lets you implement and test pre-release software. Since the integration is beta, it might contain bugs. Updates to the integration during the beta phase might
```suggestion
Note: This is a beta integration, which lets you implement and test pre-release software. Since the integration is beta, it might contain bugs. Updates to the integration during the beta phase might include non-backward compatible features. We appreciate your feedback on the quality and usability of the integration to help us identify issues, fix them, and continually improve.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Endpoint                                                                   | Add the endpoint you want to collect data from \(Alert/Events Etc..\)
```suggestion
| Endpoint                                                                   | Add the endpoint you want to collect data from \(Alert/Events etc.\).                                                                                                                                                                                                                      | True         |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Authentication Type                                                        | Select the authentication method
```suggestion
| Authentication Type                                                        | Select the authentication method.                                                                                                                                                                                                                                                           | True         |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Request data                                                               | If the product authentication requires more fields to add to the DATA please add it here in a dictionary format \{unique
```suggestion
| Request data                                                               | If the product authentication requires more fields to add to the DATA add it here in dictionary format \{unique_field : 286\}. If there's a need to add more then one, use it in this format: \{'field-1': value_example, 'field-2': value_2, 'field-3': value_3\}                  | False        |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Initial query parameters                                                   | If the product requires a different initial query parameters for the first fetch call, please add it here in a dictionar
```suggestion
| Request JSON parameters                                                    | If the product authentication requires more fields to add to the body as JSON add it here in dictionary format \{unique_field : 286\}. If there's a need to add more then one, use it in this format: \{'field-1': value_example, 'field-2': value_2, 'field-3': value_3\}          | False        |
| Initial request JSON parameters                                            | If the product requires a different initial request JSON, add it here in dictionary format \{unique_field : 286\}. If there's a need to add more then one, use it in this format: \{'field-1': value_example, 'field-2': value_2, 'field-3': value_3\}                              | False        |
| Query parameters                                                           | If the product authentication allows to filter the results using query Parameters add it here in dictionary format \{unique_field : 286\}. If there's a need to add more then one, use it in this format: \{'field-1': value_example, 'field-2': value_2, 'field-3': value_3\}      | False        |
| Initial query parameters                                                   | If the product requires a different initial query parameters for the first fetch call, add it here in dictionary format \{unique_field : 286\}. If there's a need to add more then one, use it in this format: \{'field-1': value_example, 'field-2': value_2, 'field-3': value_3\} | False        |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Timestamp format of the event creation time or "epoch".                    | Python compatible datetime formatting \(e.g. "%Y-%m-%dT%H:%M:%S.%fZ" or "%Y.%m.%d %H:%M:%S"\) or "epoch" to use UNIX epo
```suggestion
| Timestamp format of the event creation time or "epoch".                    | Python compatible datetime formatting \(e.g. ,"%Y-%m-%dT%H:%M:%S.%fZ" or "%Y.%m.%d %H:%M:%S"\) or "epoch" to use UNIX epoch time.                                                                                                                                                           | False        |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Timestamp field                                                            | The name of the event creation time in the response data, e.g. "timestamp" or "created_at".
```suggestion
| Timestamp field                                                            | The name of the event creation time in the response data, e.g., "timestamp" or "created_at".                                                                                                                                                                                                | True         |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| The type of ID field, either "integer" or "string"                         | ID field of type integer are comparable and when last fetched id is the maximum ID between the fetched events, when the
```suggestion
| Event ID lookup path in the event response JSON, dot-separated, e.g., "id". | Where within the event object to find the event ID.                                                                                                                                                                                                                                       | False        |
| The type of ID field, either "integer" or "string"                         | ID field of type integer are comparable and when last fetched ID is the maximum ID between the fetched events, when the type is string, the last fetched ID is the last event returned from the API.                                                                                       | False        |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Add Fields To header                                                       | If the product authentication requires more fields to add to the header please add it here in a dictionary format \{uniq
```suggestion
| Add Fields To header                                                       | If the product authentication requires more fields to add to the header add it here in dictionary format \{unique_field : 286\}. If there's a need to add more then one, use it in this format: \{'field-1': value_example, 'field-2': value_2, 'field-3': value_3\}                | False        |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Product                                                                    | Enter product name for dataset
```suggestion
| Vendor                                                                     | Enter vendor name for dataset.                                                                                                                                                                                                                                                              | True         |
| Product                                                                    | Enter product name for dataset.                                                                                                                                                                                                                                                            | True         |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Initial request data                                                       | If the product requires a different initial DATA,  please add it here in a dictionary format \{unique_field : 286\} if t
```suggestion
| Initial request data                                                       | If the product requires a different initial DATA,  add it here in dictionary format \{unique_field : 286\}. If there's a need to add more then one, use it in this format: \{'field-1': value_example, 'field-2': value_2, 'field-3': value_3\}                                     | False        |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +| Events lookup path in the response JSON, dot seperated, e.g. "data.items". | Where within the response object to find the events list.
```suggestion
| Events lookup path in the response JSON, dot-separated, e.g., "data.items". | Where within the response object to find the events list.                                                                                                                                                                                                                                  | False        |
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +How to configure the event collector
```suggestion
## How to configure the event collector
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +6. No Authorization (for publicly accessible data)
```suggestion
- Basic authentication (username and password)
- Token-based authentication
- Bearer token
- Api-Key token
- Raw Token (for custom token-based authentication)
- No Authorization (for publicly accessible data)
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +When the API supports pagination in the response, the collector can fetch more pages of data using the below parameters
```suggestion
When the API supports pagination in the response, the collector can fetch more pages of data using the following parameters:
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +3. Pagination flag, The Next page existence in JSON response e.g., "has_more" or "next"
```suggestion
- Is pagination needed If the API JSON response supports events pagination.
- Pagination field name, Next page field in JSON response, e.g., "cursor" or "next_page" | False |
- Pagination flag, The Next page existence in JSON response e.g., "has_more" or "next"
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +Please add it here in a dictionary format.
```suggestion
Add it here in dictionary format.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +here in a dictionary format.
```suggestion
here in dictionary format.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +If the product authentication allows filtering the results using query parameters, please add it here in a dictionary format:
```suggestion
If the product authentication allows filtering the results using query parameters, add it here in dictionary format:
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +The name of the event creation time in the response data, e.g. "timestamp" or "created_at".
```suggestion
The name of the event creation time in the response data, e.g., "timestamp" or "created_at".
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +The formatting supported is Python-compatible datetime formatting (e.g. "%Y-%m-%dT%H:%M:%S.%fZ" or "%Y.%m.%d %H:%M:%S").
```suggestion
The formatting supported is Python-compatible datetime formatting (e.g., "%Y-%m-%dT%H:%M:%S.%fZ" or "%Y.%m.%d %H:%M:%S").
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +Where within the response JSON to search for the events, dot seperated (e.g. "data.items").
```suggestion
Where within the response JSON to search for the events, dot-separated (e.g., "data.items").
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +Example 1:
```suggestion
Example 2:
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +Where within the event object to find the events' id.
```suggestion
Event ID lookup path in the event response JSON, dot-separated, e.g., "id"
Where within the event object to find the event ID.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +- ID field of type integer is comparable, and when last fetched id is the maximum ID between the fetched events.
```suggestion
- ID field of type integer is comparable, and when last fetched ID is the maximum ID between the fetched events.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +The event id field should be "id" and the type should be integer, and the last fetched id will be 4.
```suggestion
The event ID field should be "id" and the type should be integer, and the last fetched ID will be 4.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +The event id field should be "uuid" and the type should be string, and the last fetched id will be "123e4567-e89b-12d3-a456-426614174001".
```suggestion
The event ID field should be "uuid" and the type should be string, and the last fetched ID will be "123e4567-e89b-12d3-a456-426614174001".
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +4. `@fetch_size_limit` - The number of incidents to fetch per fetch.
```suggestion
- `@last_fetched_id` - The last ID that was fetched from the API, if this is the first fetch, the value will be empty.
- `@last_fetched_datetime` - The last fetched event time from the API, if this is the first fetch, the value will be empty.
- `@first_fetch_datetime` - The first fetch time, when the integration first started to fetch events.
- `@fetch_size_limit` - The number of incidents to fetch per fetch.
```

2025-02-24 14:37 UTC, ShirleyDenkberg commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/README.md
> +- This will substitute the `@last_fetched_id` with the last fetched id from a previous fetch call.
```suggestion
- This will substitute the `@last_fetched_id` with the last fetched ID from a previous fetch call.
```

2025-02-24 17:53 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +          description: Maximum number of results to return.
yes

2025-02-24 17:56 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +configuration:
?

2025-02-24 17:56 UTC, kobymeir commented on Packs/GenericAPIEventCollector/Integrations/GenericAPIEventCollector/GenericAPIEventCollector.yml
> +  id: GenericAPIEventCollector
```suggestion
  id: GenericAPIEventCollector 
```

2025-03-02 07:51 UTC, JasBeilin approved these changes
Looks Good, may the force be with us once it is out.

2025-03-03 13:47 UTC, merged