Active Directory Query v2 - global catalog reference
demisto/content pull request #37816
Opened 2024-12-23 10:42 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-23 10:55 UTC, ShacharKidor requested changes
@adi88d Nice work, 
Please add a tech writer for a docs review.

2024-12-23 10:55 UTC, ShacharKidor commented on Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
> +- display: Server port. If not specified, the default port is 389, 636 for LDAPS, or 3268 for global catalog servers.
```suggestion
- display: Server port. If not specified, the default port is 389 for LDAP, 636 for LDAPS, or 3268 for global catalog servers.
```

2024-12-23 10:55 UTC, ShacharKidor commented on Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
> +| Port  | Server port. If not specified, the default port is 389, 636 for LDAPS, or 3268 for global catalog servers.                        | False |
```suggestion
| Port  | Server port. If not specified, the default port is 389 for LDAP, 636 for LDAPS, or 3268 for global catalog servers.                        | False |
```

2024-12-23 10:55 UTC, ShacharKidor commented on Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
> +For more information on global catalog see the [Microsoft documentation](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/planning-global-catalog-server-placement).
```suggestion
> <i>Note:</i> For queries and operations across multiple domains within an Active Directory forest the server port should be 3268. This port is used for queries specifically targeted for the global catalog. LDAP requests sent to port 3268 can be used to search for objects in the entire Active Directory forest.
For more information on global catalog see the [Microsoft documentation](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/planning-global-catalog-server-placement).
```

2024-12-24 07:52 UTC, ShirleyDenkberg commented on Packs/Active_Directory_Query/ReleaseNotes/1_6_44.md
> +- Documentation and metadata improvements.
```suggestion
Documentation and metadata improvements.
```
Do you need to be more specific?  Added 3268 for global catalog servers port value.

2024-12-24 07:53 UTC, ShirleyDenkberg commented
@ShacharKidor Doc review completed.

2024-12-24 09:16 UTC, ShacharKidor approved these changes

2024-12-25 16:27 UTC, merged