RSS Feed - Add default headers param
demisto/content pull request #37836
Opened 2024-12-24 16:11 UTC by adi88d

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-45253)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2025-01-01 13:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=37836) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=37836) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=37836) it.</sub>

2025-01-20 13:38 UTC, DeanArbel requested changes

2025-01-20 13:38 UTC, DeanArbel commented on Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
> +    if default_headers:
This will break BC since users of existing instances will not have the default value from the YML in their instance configuration. Please add the previous USER_AGENT when `default_headers` is missing.

2025-01-20 14:37 UTC, adi88d commented on Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
> +    if default_headers:
done

2025-01-20 15:07 UTC, DeanArbel requested changes

2025-01-20 15:07 UTC, DeanArbel commented on Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
> +                 read_timeout=20, enrichment_excluded=False, headers={}):
Please don't init with a `dict` value - better to set it to `None`, and set its value in the code via an `if` condition.

2025-01-20 15:07 UTC, DeanArbel commented on Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
> +    default_headers = params.get('default_headers', USER_AGENT)
`USER_AGENT` isn't the required JSON - please change it to a JSON with the header key.

2025-01-20 15:34 UTC, adi88d commented on Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
> +                 read_timeout=20, enrichment_excluded=False, headers={}):
done

2025-01-20 15:34 UTC, adi88d commented on Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
> +    default_headers = params.get('default_headers', USER_AGENT)
done

2025-01-21 10:24 UTC, DeanArbel approved these changes
Small improvement, other than that looks great

2025-01-21 10:24 UTC, DeanArbel commented on Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py
> +            super().__init__(base_url=server_url, proxy=proxy, verify=use_ssl)
Do you need this if/else? passing headers should be the same

2025-01-21 11:49 UTC, ShirleyDenkberg commented on Packs/FeedRSS/ReleaseNotes/1_0_15.md
> +- The integration is now parsing the `indicator.links` value when exists in the feed.
```suggestion
- Added the *Request headers* parameter.
- The integration now parses the `indicator.links` value if it exists in the feed.
```

2025-01-21 11:49 UTC, ShirleyDenkberg commented
@DeanArbel Doc review completed.

2025-01-21 14:33 UTC, merged