Fix TroubleshootExecutePlaybookByAlertQuery
demisto/content pull request #37848
Opened 2024-12-26 07:44 UTC by inbalapt1

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12472)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-31 17:54 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +            updated_query = f"-status:closed AND {original_query}"
Please add a short one liner doc string #..... 
What are you doing here.

2024-12-31 18:34 UTC, omerKarkKatz requested changes
Please go over the review comments and fix accordingly. 
Also please add more logs to the python code in relevant places. 
Good job!

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +                           flag_pending_idle: bool):
same..

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +        handle_results(command_results, playbook_id, alert_ids, results_summary)
Why are the 2 lines repeating this is the same functionality for the if and the else.

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +        if "pending" in original_query or "idle" in original_query:
Add a log here please

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +def handle_results(command_results: dict, playbook_id: str, alert_ids: str | list, results_summary: ResultsSummary):
fix doc string.

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +            result_dict = command_results[0].get('Contents', {})
Do you extract the result_dict only to check if it is a string?

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +                return None
You can remove the none 
```suggestion
                return
```

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +        if isinstance(alert_ids, str):
If its a string wrap it with a list and continue with the same code as before, no need for the outer if else.

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +    def update_failure_create(self, playbook_id: str, failed_ids: str | list):
Same as the comment in update_success

2024-12-31 18:34 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +                    f"{sorted(alerts_fail)}.")
Add relevant logs.

2025-01-01 09:00 UTC, inbalapt1 commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +        handle_results(command_results, playbook_id, alert_ids, results_summary)
Because the second time these lines exist, is in a for loop.

2025-01-02 17:21 UTC, omerKarkKatz commented on Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py
> +        handle_results(command_results, playbook_id, alert_ids, results_summary)
ok

2025-01-02 17:25 UTC, omerKarkKatz approved these changes

2025-01-05 09:07 UTC, merged