Add script to delete indicators
demisto/content pull request #37855
Opened 2024-12-27 00:07 UTC by ali-sawyer

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A

## Description
Simple script to easily delete indicators by query, ID, or value.

## Must have
- [ ] Tests
- [ ] Documentation

2024-12-29 13:03 UTC, YairGlik requested changes
Please fill out the readme file.

2024-12-30 18:28 UTC, ali-sawyer commented
@YairGlik Done.

2024-12-30 22:35 UTC, YairGlik requested changes

2024-12-30 22:35 UTC, YairGlik commented on Packs/CommunityCommonScripts/Scripts/DeleteIndicators/DeleteIndicators.py
> +        indicator_ids = args.get('indicator_ids', None)
```suggestion
        indicator_vals = argToList(args.get('indicator_values', None))
        indicator_ids = argToList(args.get('indicator_ids', None))
```

2024-12-30 22:35 UTC, YairGlik commented on Packs/CommunityCommonScripts/Scripts/DeleteIndicators/DeleteIndicators.py
> +            search_query = f"id:({re.sub(',', ' ', indicator_ids)})"
```suggestion
        elif indicator_vals:
            search_query = f"value:({' '.join(indicator_vals)})"
        elif indicator_ids:
            search_query = f"id:({' '.join(indicator_ids)})"
```

2024-12-30 22:35 UTC, YairGlik commented on Packs/CommunityCommonScripts/Scripts/DeleteIndicators/DeleteIndicators.py
> +        indicator_ids = args.get('indicator_ids', None)
Using `argToList` ensures `indicator_values` and `indicator_ids` are always handled as lists, improving consistency and preventing errors.

2024-12-31 21:31 UTC, YairGlik commented
Hi @ali-sawyer, the code looks good!

We're ready for a demo. Please check [this page](https://xsoar.pan.dev/docs/contributing/demo-prep), and let me know when you're available. 
Feel free also to send me a recording of a demo.

2025-01-01 11:14 UTC, YairGlik approved these changes

2025-01-01 11:19 UTC, merged