Yc/cloudflare
demisto/content pull request #37861
Opened 2024-12-30 10:11 UTC by yedidyacohenpalo

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9424)

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2025-01-01 11:44 UTC, OBavly approved these changes

2025-01-05 18:52 UTC, jbabazadeh requested changes
Great work! well done!! 
please see my comments
and fix the pre commit

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +            retries=3
why we need retries?

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +            event_types_to_fetch=[ACCOUNT_AUDIT_TYPE, USER_AUDIT_TYPE]
why not to test also the other type?

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    credentials = params.get("credentials", {})
move it up

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +            base_url=params.get('url', 'https://api.cloudflare.com/'),
url is not mandatory field? why it need a default value?

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    new_last_run = {"last_fetch": start_date, "events_ids": previous_event_ids}
im not sure what happen if there is no result? the start_date and the previous_event_ids are stay the same?

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    # start_date = next_run.get('last_fetch') or "2024-12-01T10:08:58Z"
remove comment

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    latest_time = events[-1].get('when') or events[-1].get('created_at', "")
why you check 2 field? is it base on the event type?

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +            create_time = arg_to_datetime(arg=event.get('when') or event.get('created_at'))
same here is this field are base on the event type?

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/README.md
> +| Account ID | True |
add information how to get this fields

2025-01-05 18:52 UTC, jbabazadeh commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.yml
> +  name: account_id
maybe you can add additional information about this fields

2025-01-06 16:03 UTC, yedidyacohenpalo commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    latest_time = events[-1].get('when') or events[-1].get('created_at', "")
Yes, In Account Audit Logs and User Audit Logs, the timestamp is returned in the when field, while in Access Authentication Logs, it is provided in the created_at field.

2025-01-06 16:04 UTC, yedidyacohenpalo commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +            create_time = arg_to_datetime(arg=event.get('when') or event.get('created_at'))
Same here:
In Account Audit Logs and User Audit Logs, the timestamp is returned in the when field, while in Access Authentication Logs, it is provided in the created_at field.

2025-01-06 16:04 UTC, yedidyacohenpalo commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    # start_date = next_run.get('last_fetch') or "2024-12-01T10:08:58Z"
done

2025-01-06 16:20 UTC, yedidyacohenpalo commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    new_last_run = {"last_fetch": start_date, "events_ids": previous_event_ids}
Yes, they will remain as they were.

2025-01-06 17:07 UTC, yedidyacohenpalo commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +            retries=3
removed

2025-01-07 10:10 UTC, yedidyacohenpalo commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector.py
> +    credentials = params.get("credentials", {})
done

2025-01-07 10:10 UTC, yedidyacohenpalo commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/README.md
> +| Account ID | True |
done

2025-01-07 11:04 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- Visit [Retrieve Global API Key](https://developers.cloudflare.com/fundamentals/api/get-started/keys/).
Why do I need to visit this page?
Maybe start with "To find how to retrieve a Cloudflare Global API Key, see [Retrieve Global API Key](https://developers.cloudflare.com/fundamentals/api/get-started/keys/).

2025-01-07 11:04 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +  - API Key is available here: [Cloudflare API Tokens](https://dash.cloudflare.com/profile/api-tokens)
Is the API Key different than the Global API Key?
I find this very confusing.
Why do I need to go here?

2025-01-07 11:04 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- **API email** can be found here: [Cloudflare Profile](https://dash.cloudflare.com/profile).
Again, need more information.  This is very confusing to me.

2025-01-07 11:04 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/README.md
> +| event_types_to_fetch | Event types to fetch. You can choose more than one, separated by commas, possible values are `Account Audit Logs`, `User Audit Logs`, and `Access Authentication Logs`. Possib
```suggestion
| event_types_to_fetch | Comma-separated list of event types to fetch. Possible values are: Account Audit Logs, User Audit Logs, Access Authentication Logs. Default is Account Audit Logs,User Audit Logs. | Optional | 
```

2025-01-07 11:05 UTC, ShirleyDenkberg commented
@jbabazadeh @OBavly Doc review completed.
@yedidyacohenpalo Need content in the pack readme.

2025-01-07 13:53 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- Scroll to the API Keys section.
```suggestion
2. Scroll to the **API Keys** section.
```

2025-01-07 13:53 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- Here, you will find the Global API Key. Click View to reveal it (you may need to enter your password).
```suggestion
3. Click **View** to reveal the Global API Key.  (You may need to enter your password).
```

2025-01-07 13:53 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- Go to [Cloudflare API Tokens](https://dash.cloudflare.com/profile/api-tokens).
```suggestion
1. Go to [Cloudflare API Tokens](https://dash.cloudflare.com/profile/api-tokens).
```

2025-01-07 13:53 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- To learn more about the Global API Key, visit the [Cloudflare API Key Documentation.](https://developers.cloudflare.com/fundamentals/api/get-started/keys/).
```suggestion
To learn more about the Global API Key, visit the [Cloudflare API Key Documentation.](https://developers.cloudflare.com/fundamentals/api/get-started/keys/).
```

2025-01-07 13:53 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- API email can be found here: [Cloudflare Profile](https://dash.cloudflare.com/profile).
```suggestion
The associated API email can be found here: [Cloudflare Profile](https://dash.cloudflare.com/profile).
```

2025-01-07 13:53 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +- For more details on verifying your associated email, visit the  [Verify Email Address](https://developers.cloudflare.com/fundamentals/setup/account/verify-email-address/).
```suggestion
For more details on verifying your associated email, visit the  [Verify Email Address](https://developers.cloudflare.com/fundamentals/setup/account/verify-email-address/).
```

2025-01-07 13:53 UTC, ShirleyDenkberg commented on Packs/CloudflareZeroTrust/Integrations/CloudflareZeroTrustEventCollector/CloudflareZeroTrustEventCollector_description.md
> +This API token will affect the below accounts and zones, along with their respective permissions:
```suggestion
This API token will affect the following accounts and zones, along with their respective permissions:
```

2025-01-07 13:53 UTC, ShirleyDenkberg commented
@yedidyacohenpalo I reviewed the files again.

2025-01-26 17:47 UTC, jbabazadeh approved these changes
Well done!

2025-01-26 17:49 UTC, merged