Update integration-AMP.yml
demisto/content pull request #8247
Opened 2020-07-28 12:14 UTC by tzemel

Added 4 new commands per customer request https://github.com/demisto/etc/issues/25617 NTT
amp_delete_computers_isolation
amp_options_computers_isolation
amp_put_computers_isolation
amp_get_computers_isolation

## Status
- [ x] Ready

## Related Issues
fixes: link to the issue

## Description
Added 4 new commands per customer request https://github.com/demisto/etc/issues/25617 NTT
amp_delete_computers_isolation
amp_options_computers_isolation
amp_put_computers_isolation
amp_get_computers_isolation
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [ ] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [x] NO
   
## Must have
- [X] Tests

2020-08-13 07:13 UTC, tzemel commented
fixed version issue and not test was added

2020-08-19 09:26 UTC, guyfreund commented
@kirbles19 this is an internal contribution (XSOAR supported), therefore your review is needed here.

2020-08-19 09:27 UTC, guyfreund commented
@tzemel please add a release notes file, please see [RN Docs](https://xsoar.pan.dev/docs/integrations/changelog) for more information.

2020-08-19 09:59 UTC, tzemel commented
add Change Log

2020-08-19 10:00 UTC, tzemel commented
i have added change log

On Wed, Aug 19, 2020 at 12:27 PM Guy Freund <notifications@github.com>
wrote:

> @tzemel
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tzemel&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=0RruRMBUli4bDWNMBMqrnb-WhtAwmnwY4PsRdlBGz_w&e=>
> please add a release notes file, please see RN Docs
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__xsoar.pan.dev_docs_integrations_changelog&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=z5lBPBjR48VCHyxNYrsKdP2iVB8HszGipmHzz7gFdxU&e=>
> for more information.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_8247-23issuecomment-2D676024283&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=zcexuAtnCV1lkmrlT05JXlL1l4P9PkwmAVHdHDBXbqs&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVKBF4VTES7VKWQICXVSZ3SBOLJTANCNFSM4PKORYYQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=Yst9Ex2WsaUsKGAPAPzVl-PE3AR-kwlUKcrMQgvZcaY&e=>
> .
>

2020-08-19 11:14 UTC, guyfreund commented
> i have added change log
> […](#)
> On Wed, Aug 19, 2020 at 12:27 PM Guy Freund ***@***.***> wrote: @tzemel <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tzemel&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=0RruRMBUli4bDWNMBMqrnb-WhtAwmnwY4PsRdlBGz_w&e=> please add a release notes file, please see RN Docs <https://urldefense.proofpoint.com/v2/url?u=https-3A__xsoar.pan.dev_docs_integrations_changelog&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=z5lBPBjR48VCHyxNYrsKdP2iVB8HszGipmHzz7gFdxU&e=> for more information. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_8247-23issuecomment-2D676024283&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=zcexuAtnCV1lkmrlT05JXlL1l4P9PkwmAVHdHDBXbqs&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVKBF4VTES7VKWQICXVSZ3SBOLJTANCNFSM4PKORYYQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=8R3n0EZ_PzPfgBnAJ3KLxl9J_tzZRiVmdtDVunrJaLo&s=Yst9Ex2WsaUsKGAPAPzVl-PE3AR-kwlUKcrMQgvZcaY&e=> .

@tzemel you should use `demisto-sdk update-release-notes` command to update the release notes. The changelog file update is not needed anymore, please revert it.
You can check the documentation I've mentioned above for more info on the `demisto-sdk update-release-notes` command.

2020-08-19 11:19 UTC, tzemel commented
I don't use git control I am doing everything from the  ui can you help?

On Wed, Aug 19, 2020, 14:15 Guy Freund <notifications@github.com> wrote:

> @tzemel
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tzemel&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=h_H5IkT20xjFxCf1LgqnZvrCP373GMtreKmr3AA6_k0&s=_Uw0JzkStUqE1YQRQoA8sefcRDDWCW2Y-9grwJM_rXI&e=>
> you should use demisto-sdk update-release-notes command to update the
> release notes. The changelog file update is not needed anymore, please
> revert it.
> You can check the documentation I've mentioned above for more info on the demisto-sdk
> update-release-notes command.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_8247-23issuecomment-2D676168374&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=h_H5IkT20xjFxCf1LgqnZvrCP373GMtreKmr3AA6_k0&s=ieXWsVv5Z9KYa6hHOjLTb9pJpYajYsFDSb-sfsKuf0M&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVKBF32HCX64RHOZ4BTDYDSBOX33ANCNFSM4PKORYYQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=h_H5IkT20xjFxCf1LgqnZvrCP373GMtreKmr3AA6_k0&s=-8R2I-5M6i6P_b0HAVacAuWksvAHwSMPuMTmwD2LdL0&e=>
> .
>

2020-08-19 11:20 UTC, guyfreund commented
@tzemel yeah sure, I do it for you.

2020-08-19 12:29 UTC, guyfreund requested changes
If you want to commit changes, first pull since I've made some changes.

2020-08-19 12:29 UTC, guyfreund commented on Packs/AMP/Integrations/integration-AMP.yml
> +                return base
why is the return here needed? we return `base` at the end of the switch case statement.
```suggestion
```

2020-08-28 21:20 UTC, tzemel commented
No I am good, @guyfreund
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_guyfreund&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=x9c6zwqx6vPBZH3rVIya9EElyMm3p1yXxq9cZGm8HfU&s=rl_NeJSfWT5pYGdWsesB2fIaybLcjO4QefaQaqGEj0k&e=>'s
want to check with the customer, the customer replied last week that
everything is fine with the enhancement and now I am waiting

On Fri, Aug 28, 2020, 19:30 content-bot <notifications@github.com> wrote:

> This PR is starting to get a little stale. @tzemel
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tzemel&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=x9c6zwqx6vPBZH3rVIya9EElyMm3p1yXxq9cZGm8HfU&s=pR2bvlxkFxBiIhpscenvI3Iz7zy_CeSBuOlhSwHEbn4&e=>
> are there any changes you wanted to make since @guyfreund
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_guyfreund&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=x9c6zwqx6vPBZH3rVIya9EElyMm3p1yXxq9cZGm8HfU&s=rl_NeJSfWT5pYGdWsesB2fIaybLcjO4QefaQaqGEj0k&e=>'s
> last comment?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_8247-23issuecomment-2D682837783&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=x9c6zwqx6vPBZH3rVIya9EElyMm3p1yXxq9cZGm8HfU&s=iZQxCGhni_Re59WcwnIZQS0oAa9oyCCmbLdrBxx6Jus&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVKBF6KFRLQLJGUOSYTPRTSC7LSZANCNFSM4PKORYYQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=x9c6zwqx6vPBZH3rVIya9EElyMm3p1yXxq9cZGm8HfU&s=VUvY1CUXTLSDRCO5UR_LeayxLum-3bOQ48LtfjfwYig&e=>
> .
>

2020-08-30 07:59 UTC, guyfreund commented
@tzemel what are we waiting for?

2020-08-30 08:11 UTC, tzemel commented
@guyfreund
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_guyfreund&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=x9c6zwqx6vPBZH3rVIya9EElyMm3p1yXxq9cZGm8HfU&s=rl_NeJSfWT5pYGdWsesB2fIaybLcjO4QefaQaqGEj0k&e=>'s
as
requested you wanted confirmation from the customer (working session that
he won't provide) i have asked the customer to share the integration that i
implemented there,
i just want to compare the 2 integration to see that we have a match, i
think i did change something with the uri but i am not sure.
let's wait a few more days and wait for his response. i hope he will share
the integration

On Sun, Aug 30, 2020 at 11:00 AM Guy Freund <notifications@github.com>
wrote:

> @tzemel
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tzemel&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=0_z2-XOYl-rGqMhdXytFQKuz-ItGSTEP3RC6rXKC73k&s=-MSNtwhM-5pCMk4gZMbG9G0zTwIlGMYn1VD_LRiXM2A&e=>
> what are we waiting for?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_8247-23issuecomment-2D683389585&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=0_z2-XOYl-rGqMhdXytFQKuz-ItGSTEP3RC6rXKC73k&s=Hw4fiXhKV5EybVz3wf9dpfnifmHwbf2HDiu8Q27IYqA&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVKBFZVXYXONLBT3XM7A73SDIBIPANCNFSM4PKORYYQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=0_z2-XOYl-rGqMhdXytFQKuz-ItGSTEP3RC6rXKC73k&s=EeaOLvyaqkIZ1ehxGZ28KLXboFUkUmfaLIDtdEXyvoY&e=>
> .
>

2020-09-06 08:00 UTC, tzemel commented
Hi All,

i tired to get the integration from the customer, however the customer is
not responding we can push it

On Sat, Sep 5, 2020 at 7:30 PM content-bot <notifications@github.com> wrote:

> This PR is starting to get a little stale. @tzemel
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tzemel&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=Z1u-2D96a9FCQqLn_JXGkqyfACFBuQc9gORi3M6BJJw&s=VH68rOZo9TMXb6X1ciAdS5TZa8jngBcJbJSmecPdsV0&e=>
> are there any changes you wanted to make since @guyfreund
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_guyfreund&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=Z1u-2D96a9FCQqLn_JXGkqyfACFBuQc9gORi3M6BJJw&s=kp1s81LGMxUIKMYq3M4WxOXn_O8v1RmS2yjyNPccSPs&e=>'s
> last comment?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_8247-23issuecomment-2D687632787&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=Z1u-2D96a9FCQqLn_JXGkqyfACFBuQc9gORi3M6BJJw&s=ufM63vnQGBoVLvSOW8fiOHlfusCoeYzGa0Y8TOdV9UQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVKBF3YGYU6HT5H2PNFWEDSEJRSNANCNFSM4PKORYYQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=Z1u-2D96a9FCQqLn_JXGkqyfACFBuQc9gORi3M6BJJw&s=n5JiAhEUkjSap4uCLIIgYNJTZEEZ-l5xQ06ah9qFC-8&e=>
> .
>

2020-09-06 08:47 UTC, guyfreund commented
@tzemel as I said, we need the customer confirmation that all is working, we need to see it live or in a video recording.
We can't move on with it until then.

2020-09-06 08:56 UTC, tzemel commented
guy you got the confirmation last week from the customer, video dont think
its possible i asked for the integration even that i didnt get.
if you want you can take it with @Kate Pang <kpang@paloaltonetworks.com>

On Sun, Sep 6, 2020 at 11:47 AM Guy Freund <notifications@github.com> wrote:

> @tzemel
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tzemel&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=G1Jjxnd3jI4lhytD6X1LaEbZr3UdPx0SbGaGzYBA6jk&s=QA2D-mCq0qmpnnjfOhCw7xWvzyCGiD3oDVV6NGKpWeM&e=>
> as I said, we need the customer confirmation that all is working, we need
> to see it live or in a video recording.
> We can't move on with it until then.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_demisto_content_pull_8247-23issuecomment-2D687728395&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=G1Jjxnd3jI4lhytD6X1LaEbZr3UdPx0SbGaGzYBA6jk&s=eCH0fgfTeXIP3vy9g-cJ6q8K5ACgYOM7RlboR_sOzO0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANVKBFYQJ7ZAW5TZ62TDYETSENEDDANCNFSM4PKORYYQ&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=-oDaSfHi_h7DL_NtMRfbvCb6c9W2WjpjR56xcU449Us&m=G1Jjxnd3jI4lhytD6X1LaEbZr3UdPx0SbGaGzYBA6jk&s=4Tp7H6XpX-Od0BRRXxhFcnDR4U8MH0Wa23iDMTfRVxE&e=>
> .
>

2020-09-29 16:36 UTC, tzemel commented
@ShahafBenYakir @GavrielFilippov @Kate-Pang 
Shahaf after repeated request to participate in a meeting to verify the new commands according to @guyfreund request unfortunately the customer didn't participate in any meeting.
i don't know what to do know, you can close the case, and we will lose the new commands

2020-10-09 14:33 UTC, guyfreund commented
Closing as there's no answer from @Kate-Pang in https://github.com/demisto/etc/issues/25617
@tzemel please reopen when we have an instance to test this contribution's changes...

2020-10-09 16:09 UTC, ShahafBenYakir commented
@omercnet FYI

2020-10-20 07:22 UTC, guyfreund requested changes
@tzemel we went on a demo with the customer, what's left to do here:
- for the `amp_options_computers_isolation` command there's no output in war room, please add one that will correspond to the [API docs](https://api-docs.amp.cisco.com/api_actions/details?api_action=OPTIONS+%2Fv1%2Fcomputers%2F%7B%3Aconnector_guid%7D%2Fisolation&api_host=api.eu.amp.cisco.com&api_resource=Endpoint+Isolation&api_version=v1)
- Fix the conflicts in the PR

2020-11-02 07:37 UTC, ShahafBenYakir commented
@guyfreund What is left here?

2020-11-19 10:58 UTC, guyfreund approved these changes

2020-11-19 11:25 UTC, merged