F5 Firewall v2
demisto/content pull request #8396
Opened 2020-08-06 14:15 UTC by GillSamia

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
New integration to f5. This integration allows user to manage f5 firewall.
Existing endpoint: 
1.	Policy management: list, apply, export and delete
2.	Policy method – CRUD
3.	File types – CRUD
4.	Cookies – CRUD
5.	Hostname – CRUD
6.	Urls – CRUD
7.	Whitelist Ips – CRUD
8.	Blocking-settings – list 

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [x] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [x] The title must be in the following format: **Qmasters**

2020-08-18 06:40 UTC, barchen1 commented on Packs/F5/Integrations/f5_v2/f5_v2.yml
> +  id: F5_firewall
please change the id to F5 WAF

2020-08-18 06:40 UTC, barchen1 commented on Packs/F5/Integrations/f5_v2/f5_v2.yml
> +display: f5 firewall - v2
The display name should be F5 Application Security Manager (WAF)

2020-08-18 06:42 UTC, barchen1 commented on Packs/F5/Integrations/f5_v2/f5_v2.yml
> +name: F5_firewall
The name should be F5 WAF

2020-08-19 13:10 UTC, GillSamia commented on Packs/F5/Integrations/f5_v2/f5_v2.py
> +            if element.get('name') == policy_name:
The response is not filtered. I removed the params from the request as it has no effect.

2020-08-19 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=8396) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=8396) before we can accept your contribution.<br/>**4** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: anara123<br/>:white_check_mark: avidan-H<br/>:white_check_mark: IkaDemisto<br/>:white_check_mark: GillSamia<br/>:x: esharf<br/>:x: ohaim1008<br/>:x: orhovy<br/>:x: barchen1<br/>:x: gal-berger<br/>:x: idovandijk<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=8396) it.</sub>

2020-08-20 14:17 UTC, anara123 commented on Packs/F5/Integrations/f5_ASM/f5_ASM.yml
> +- display: Server URL (e.g. 8.8.8.8)
you ask for server url but give an IP as example/
Change to URL example

2020-10-01 14:28 UTC, barchen1 requested changes
Thanks again for your contribution!
Please add the changes for the update/delete commands as we discussed.
Let's talk over Slack and schedule a demo.
Let me know if you need help.

2020-11-10 07:32 UTC, yaakovi approved these changes

2020-11-10 07:34 UTC, merged