[expanse-272] Add additional checks to test playbook and update input values
demisto/content pull request #8451
Opened 2020-08-10 20:05 UTC by andrew-expanse

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: Failing CircleCI build due to a removed domain in our test environment. 

## Description
This PR updates the test playbook input to replace a domain that was removed from our test environment and it also adds some conditional checks to ensure that the playbook exits if an input is removed in the future. 

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 4.5.0
- [x] 5.0.0
- [ ] 5.5.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation 

## Demisto Partner?
- [x] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

2020-08-10 20:05 UTC, andrew-expanse commented
@trorabaugh and I will review this together on 8/11/20.

2020-08-11 20:49 UTC, andrew-expanse commented
@trorabaugh and I did a live demo walkthrough of the changes to the test playbook and everything should be fixed and less prone to break this way in the future.

2020-08-11 20:57 UTC, trorabaugh commented
Let us know if you need anything else on this.

2020-08-11 22:36 UTC, trorabaugh commented
@andrew-expanse you may need to review the circle ci and potentially update any merge conflicts.

2020-08-18 14:58 UTC, barchen1 commented on Packs/Expanse/ReleaseNotes/1_1_1.md
> +- Updated the author field to reflect Expanse contact email
No need to change the author, it should stay "Expanse"

2020-08-18 17:56 UTC, andrew-expanse commented on Packs/Expanse/pack_metadata.json
> +    "author": "help@expanseinc.com",
Sorry, must've been some miscommunication earlier - I've removed this now.

2020-08-20 09:21 UTC, barchen1 requested changes
Packs/AutoFocus/Integrations/FeedAutofocus/demo_video/AutoFocus_Feed_demo.mp4 - This file looks unrelated to this PR.

2020-08-20 13:14 UTC, andrew-expanse commented
> Packs/AutoFocus/Integrations/FeedAutofocus/demo_video/AutoFocus_Feed_demo.mp4 - This file looks unrelated to this PR.

ughh I have no idea how this got here - I'll try to remove it.

2020-08-20 14:16 UTC, barchen1 approved these changes

2020-08-20 14:20 UTC, merged

2020-10-07 10:50 UTC, barchen1 commented
@andrew-expanse Hi Andrew 
I tried to to run the `test-Expanse` test playbook and it failed on `domain` task.
The error I get when I tried to run `!domain domain=shack.com` is: `'NoneType' object has no attribute 'get'`
We need to fix this command and make sure the testplaybook pass.

![Screen Shot 2020-10-07 at 13 47 07](https://user-images.githubusercontent.com/54398957/95321399-aec88380-08a3-11eb-8534-64d455d5ff97.png)

![Screen Shot 2020-10-07 at 13 47 37](https://user-images.githubusercontent.com/54398957/95321390-abcd9300-08a3-11eb-84b2-00756f296c34.png)

2020-10-07 13:15 UTC, andrew-expanse commented
Hi @barchen1 I'm looking into this now. It appears it may be an API related issue on our end. I've contacted our product engineering team and will update ASAP once I know more about why this change occurred and whether it was intentional.