Atlassian cloud it admin
demisto/content pull request #8510
Opened 2020-08-14 10:46 UTC by sonaaru

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A. New Integration.

## Description
Initial commit.

## Screenshots
N/A

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

2020-08-23 19:15 UTC, dantavori requested changes
see my notes - also please generate the readme file of the integration

2020-08-24 17:54 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin.py
> +        demisto.error(f'Failed to execute {demisto.command()} command. Traceback: {traceback.format_exc()}')
> done

2020-08-24 17:54 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin.py
> +def enablee_disable_user_command(client, args, is_active):
done

2020-08-24 17:54 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin.py
> +    return enablee_disable_user_command(client, args, True)
done

2020-08-24 17:54 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin.py
> +    return enablee_disable_user_command(client, args, False)
done

2020-08-24 17:55 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin.py
> +        err_msg = 'Invalid url: ' + client.base_url + f'/scim/directory/{encode_string_results(client.directory_id)}'
done

2020-08-24 17:55 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/pack_metadata.json
> +    "description": "Atlassian Cloud IT Admin",
done

2020-08-24 17:55 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/TestPlaybooks/playbook-Atlassian_Cloud_IT_Admin.yml
> +id: testplaybook-Atlassian_Cloud_IT_Admin
No. Moving the playbook to be under NonCircleTests dir.

2020-08-24 17:56 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/CHANGELOG.md
> +## [Unreleased]
done

2020-08-24 17:56 UTC, sonaaru commented on Packs/AtlassianCloudITAdmin/Integrations/Atlassian_Cloud_IT_Admin/Atlassian_Cloud_IT_Admin_description.md
> +•	By default, the key expires one week from today. If you’d like to change the expiration date, pick a new date under Expires on. You’re unable to select a date longer than a year from the date of cr
https://confluence.atlassian.com/cloud/create-an-admin-api-key-969537932.html

2020-08-24 18:12 UTC, sonaaru commented on Tests/conf.json
> +        {
We wrongly updated this file so reverted the changes

2020-09-02 15:00 UTC, dantavori approved these changes

2020-09-02 15:00 UTC, merged