Zoom it admin
demisto/content pull request #8511
Opened 2020-08-14 15:47 UTC by sonaaru

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
N/A. New Integration.

## Description
Initial commit.

## Screenshots
N/A

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation 

## Demisto Partner?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**

2020-08-23 19:15 UTC, dantavori requested changes
see my notes - also please generate the readme file of the integration

2020-08-24 14:10 UTC, sonaaru commented on Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/CHANGELOG.md
> +## [Unreleased]
Done

2020-08-24 14:10 UTC, sonaaru commented on Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin_description.md
> +- Here you should explain how to configure the instance in Demisto
Done the changes

2020-08-24 14:10 UTC, sonaaru commented on Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/common-example.txt
> +create-user scim="{"userName":"rbilgundi+demistotest@paloaltonetworks.com","emails":[{"type":"work","primary":true,"value":"rbilgundi+demistotest@paloaltonetworks.com"}],"name":{"familyName":"Test","
Done the changes

2020-08-24 14:11 UTC, sonaaru commented on Packs/ZoomITAdmin/TestPlaybooks/playbook-Zoom_IT_Admin.yml
> +id: playbook-Zoom_IT_Admin
Done the changes. moved the playbook inside NonCircleTests

2020-08-24 14:12 UTC, sonaaru commented on Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin.py
> +    readable_output = tableToMarkdown('Update Zoom User:', generic_iam_context.data)
Done the changes

2020-08-24 14:13 UTC, sonaaru commented on Packs/ZoomITAdmin/Integrations/Zoom_IT_Admin/Zoom_IT_Admin.py
> +    def build_zoom_profile_create_user(self, args, scim, custom_mapping):
We cannot merge it, because these two method builds dict in a different structure

2020-09-02 15:04 UTC, dantavori approved these changes

2020-09-02 15:04 UTC, merged