Fix pack metadata files
demisto/content pull request #8595
Opened 2020-08-20 06:55 UTC by gal-berger

## Status
- [] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
#24669

## Description
Bad contact details in the pack_metadata files for Cymulate, Silverfort, and Infinipoint.

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-08-20 07:42 UTC, KGausel commented
Looks good to me

2020-08-24 06:58 UTC, yuvalbenshalom requested changes
looks good, added proposed fixes to RN

2020-08-24 06:58 UTC, yuvalbenshalom commented on Packs/Cymulate/ReleaseNotes/1_0_4.md
> +- fix contact details in pack_metadata.json
```suggestion
- Fix contact details
```

2020-08-24 06:58 UTC, yuvalbenshalom commented on Packs/Digital_Defense_FrontlineVM/ReleaseNotes/1_1_1.md
> +- fix contact details in pack_metadata.json
```suggestion
- Fix contact details
```

2020-08-24 06:58 UTC, yuvalbenshalom commented on Packs/Humio/ReleaseNotes/1_0_1.md
> +- fix contact details in pack_metadata.json
```suggestion
- Fix contact details
```

2020-08-24 06:58 UTC, yuvalbenshalom commented on Packs/Infinipoint/ReleaseNotes/1_0_1.md
> +- fix contact details in pack_metadata.json
```suggestion
- Fix contact details
```

2020-08-24 06:58 UTC, yuvalbenshalom commented on Packs/Silverfort/ReleaseNotes/1_0_2.md
> +- fix contact details in pack_metadata.json
```suggestion
- Fix contact details
```

2020-08-24 07:50 UTC, gal-berger commented on Packs/Cymulate/ReleaseNotes/1_0_4.md
> +- fix contact details in pack_metadata.json
fixed

2020-08-24 07:50 UTC, gal-berger commented on Packs/Humio/ReleaseNotes/1_0_1.md
> +- fix contact details in pack_metadata.json
fixed.

2020-08-24 07:51 UTC, gal-berger commented on Packs/Silverfort/ReleaseNotes/1_0_2.md
> +- fix contact details in pack_metadata.json
fixed.

2020-08-24 07:51 UTC, gal-berger commented on Packs/Infinipoint/ReleaseNotes/1_0_1.md
> +- fix contact details in pack_metadata.json
fixed

2020-08-24 09:27 UTC, yuvalbenshalom approved these changes

2020-08-25 09:01 UTC, ShahafBenYakir commented on Packs/illuminate/ReleaseNotes/1_0_1.md
> +##### ￿illuminate
```suggestion
##### illuminate
```

2020-08-25 14:16 UTC, gal-berger commented on Packs/illuminate/ReleaseNotes/1_0_1.md
> +##### ￿illuminate
fixed

2020-08-26 15:08 UTC, merged