PyDT - General Python transformer
demisto/content pull request #8685
Opened 2020-08-26 17:15 UTC by mhouston007

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Python alternative to the DT transformer

## Screenshots
![image](https://user-images.githubusercontent.com/58996090/91335248-246a0b80-e79e-11ea-9da9-0c3cfc5ba91f.png)

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-08-30 08:31 UTC, anara123 requested changes

2020-08-30 08:31 UTC, anara123 commented on Packs/CommonScripts/Scripts/PyDT/PyDT.py
> +    code = compile(source, '<string>', 'exec')
We can't allow arbitrary user input code execution.

2020-08-30 08:34 UTC, anara123 commented
Hello @mhouston007 
Thank you for contribution. But unfortunately I must reject it. We can't allow arbitrary user input code execution. 
If you have other way to implement it, feel free to reopen the PR and update the code.
Closing for now

2020-08-30 09:54 UTC, anara123 commented
@mhouston007 Sorry, Didn't noticed you have other files in your PR. Please remove the PyDT script or change the implementation,

2020-08-30 13:16 UTC, reutshal commented
@anara123 The other files are being reviewed in this PR by @barchen1 : https://github.com/demisto/content/pull/8659/files

2020-08-31 17:18 UTC, mhouston007 commented
Didn't mean to include the other files, those are a separate PR, closing this one

2020-09-03 20:28 UTC, mhouston007 commented
Made the updates a bit too restricted, closing until I can get it right

2020-09-03 20:28 UTC, closed without merging