uptycs-185 bug fixes for integration, change playbook inputs and add gatherEvidence Tasks, slight clarification added to parameters section of documentation, uptycs support info added
demisto/content pull request #8688
Opened 2020-08-26 20:16 UTC by bkschmoll-uptycs

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
This PR includes:
-bug fixes for integration
-slight clarification added to parameters section of documentation
-uptycs support info added

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [x] Yes
       - Further details: Playbook input changed from "incident.alertid" to "incident.labels.alertId", addition of the labels path may break backwards compatibility as older Playbooks did not use the labels path in the input.
   - [ ] No

## Must have
- [ ] Tests
- [x] Documentation

2020-08-27 08:47 UTC, guyfreund requested changes
Overall looking good, but there are two things to do here.
1. Add release notes, see [RN Docs](https://xsoar.pan.dev/docs/integrations/release-notes) for more information.
2. Add fromversion in the integration & playbook (yml files)

2020-08-27 08:48 UTC, guyfreund commented
@mayagoldb can you please review the pb?

2020-08-28 19:23 UTC, bkschmoll-uptycs commented on Packs/Uptycs/pack_metadata.json
>      "keywords": []
I have added the githubUser field to pack_metadata.  We do not currently have a documentation page for integrations on our website.  Can we use the xsoar documentation page for reference until we have added the appropriate documentation to our website and then change the url in a later PR?

2020-08-28 19:25 UTC, bkschmoll-uptycs commented on Packs/Uptycs/pack_metadata.json
> +    "url": "https://xsoar.pan.dev/docs/reference/integrations/uptycs",
We do not currently have a documentation page for integrations on our website.  Can we use the xsoar documentation page for reference until we have added the appropriate documentation to our website and then change the url in a later PR?

2020-08-28 19:26 UTC, bkschmoll-uptycs commented on Packs/Uptycs/Playbooks/playbook-Uptycs_-_Outbound_Connection_to_Threat_IOC_Incident.yml
> -fromversion: 4.0.0
I downloaded the new version of the playbook from my developer instance and I guess 'fromversion' wasn't in it?  I have added it back in.

2020-08-30 07:53 UTC, guyfreund commented on Packs/Uptycs/pack_metadata.json
> +    "url": "https://xsoar.pan.dev/docs/reference/integrations/uptycs",
The url should be of Uptycs, you can submit a link to the support/contact page of Uptycs.

2020-08-30 07:55 UTC, guyfreund commented on Packs/Uptycs/pack_metadata.json
>      "keywords": []
Email should be the support mail, no need for the change.

2020-08-30 07:58 UTC, guyfreund requested changes
Looking good, make sure your [build](https://app.circleci.com/jobs/github/demisto/content/97124) is passing.

2020-08-30 07:58 UTC, guyfreund commented on Packs/Uptycs/pack_metadata.json
> +    "githubUser": "bkschmoll-uptycs"
```suggestion
    "githubUser": ["bkschmoll-uptycs"]
```

2020-08-30 07:58 UTC, guyfreund commented on Packs/Uptycs/pack_metadata.json
> +    "email": "bschmoll@uptycs.com",
```suggestion
    "email": "support@uptycs.com",
```

2020-08-30 07:58 UTC, guyfreund commented on Packs/Uptycs/Playbooks/playbook-Uptycs_-_Outbound_Connection_to_Threat_IOC_Incident.yml
> +fromversion: "4.0.0"
can the fromversion be bumped to 5.0.0?

2020-08-30 07:58 UTC, guyfreund commented on Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
> +fromversion: "4.0.0"
can the fromversion be bumped to 5.0.0?

2020-08-30 07:58 UTC, guyfreund commented on Packs/Uptycs/pack_metadata.json
>      "currentVersion": "1.0.1",
pack version should be the same as the latest rn file.
```suggestion
    "currentVersion": "1.0.2",
```

2020-08-31 17:34 UTC, bkschmoll-uptycs commented on Packs/Uptycs/pack_metadata.json
> +    "url": "https://xsoar.pan.dev/docs/reference/integrations/uptycs",
ok, I have changed the url to Uptycs

2020-08-31 22:43 UTC, anara123 commented on Packs/Uptycs/pack_metadata.json
> +    "url": "https://xsoar.pan.dev/docs/reference/integrations/uptycs",
@bkschmoll-uptycs The URL is not for documentation, but for support. You can provide either email or url or both. These should be contact details, where the users/customers can go in order to submit an issue/ticket that relates to the integration.

2020-09-01 13:07 UTC, guyfreund approved these changes
You should two things to make the CCI pass:
1. update the docker image tag in the integration yml file to `1.0.0.10664` instead of `1.0.0.1126`
2. run demisto-sdk format on the playbook yml file

2020-09-03 15:35 UTC, guyfreund requested changes
- Improve the api domain parameter display name:
This needs to be done in the yml file in line 15.
Something like: `display: API Domain (e.g. staging.uptycs.io)`
- Fix the `set_tag` command bug we've seen in the demo.

2020-09-03 15:46 UTC, mayagoldb commented
@bkschmoll-uptycs Thanks for the demo!
On the playbook side - 
Add the check for parent process rows after the get-processes command and you're good to go.

2020-09-07 11:57 UTC, guyfreund commented
@bkschmoll-uptycs merge content master into your base branch and make sure the working branch is updated too, this will make the build pass.

2020-09-07 14:39 UTC, bkschmoll-uptycs commented
> @bkschmoll-uptycs merge content master into your base branch and make sure the working branch is updated too, this will make the build pass.

I have merged content master into my fork, however the build is still not passing.  I believe this may be due to the following error I receive from running the demisto-sdk validate command:

"Value '{'simple': '${inputs.alert_time}'}' is not of type 'text'. Path: '/tasks/1/evidencedata/occurred'.: Path: '/'>"

I'm not sure what should go in this field, the playbook works as intended with the 'occurred' field being filled with the appropriate alert_time from ${inputs.alert_time}.

2020-09-07 15:16 UTC, guyfreund commented
@bkschmoll-uptycs we should wait for the demisto-sdk release, it will be done until the end of the week and then the build will pass.

2020-09-10 11:31 UTC, guyfreund commented
@bkschmoll-uptycs let's submit the requested changes @mayagoldb and I have asked and then we can merge this PR.

2020-09-10 12:48 UTC, mayagoldb approved these changes

2020-09-10 14:41 UTC, bkschmoll-uptycs commented
> @bkschmoll-uptycs let's submit the requested changes @mayagoldb and I have asked and then we can merge this PR.

I believe I have made the requested changes.  Are there any I have missed?

2020-09-13 16:35 UTC, guyfreund commented
> > @bkschmoll-uptycs let's submit the requested changes @mayagoldb and I have asked and then we can merge this PR.
> 
> I believe I have made the requested changes. Are there any I have missed?

Yes.
- Improve the API domain parameter display name:
This needs to be done in the yml file in line 15.
Something like: display: API Domain (e.g. staging.uptycs.io)

2020-09-14 14:05 UTC, bkschmoll-uptycs commented
> > > @bkschmoll-uptycs let's submit the requested changes @mayagoldb and I have asked and then we can merge this PR.
> > 
> > 
> > I believe I have made the requested changes. Are there any I have missed?
> 
> Yes.
> 
> * Improve the API domain parameter display name:
>   This needs to be done in the yml file in line 15.
>   Something like: display: API Domain (e.g. staging.uptycs.io)

Whoops, forgot about that.  Just pushed.

2020-09-14 14:33 UTC, guyfreund approved these changes

2020-09-14 14:33 UTC, merged