Added ConvertTo-Markdown method
demisto/content pull request #8706
Opened 2020-08-27 15:39 UTC by hod-alpert

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/10273

## Description
Added ConvertTo-Markdown method

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-08-27 16:45 UTC, glicht commented
is this doing what `tableToMarkdown` does? If so name it `TableToMarkdown`. We are trying to use the same names as in python for utility functions. We can have an alias of `ConvertTo-Markdown` for completeness.

2020-08-28 11:56 UTC, kirbles19 commented
@hod-alpert Done

2020-08-30 09:49 UTC, hod-alpert commented
@glicht Renamed the function

2020-08-30 14:11 UTC, glicht requested changes

2020-08-30 14:11 UTC, glicht commented on Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
> +                    $values += $_.Value
I think we need to apply escaping to chars that might break the MD. See stringEscapeMD in cmmonserverpython.

2020-08-31 14:42 UTC, hod-alpert commented
@glicht Added support for escaping characters and for nested objects

2020-08-31 20:09 UTC, glicht commented
What about `name` argument for the table as we have in CommonServerPython?

2020-09-01 11:55 UTC, hod-alpert commented
@glicht `Name` is already supported.
Added support for hash-tables and non list objects

2020-09-03 15:44 UTC, glicht commented
@hod-alpert it is looking better. I would just try to handle nested objects better. I would avoid serializing to json but instead simply use the string representation. Try looking at Format-Table and the output they provide. 

For example output from format-table for `$psversiontable`:
![image](https://user-images.githubusercontent.com/1395797/92136437-b2846880-ee14-11ea-9719-8c91e8a89cdc.png)

Output from tableToMarkdown:
![image](https://user-images.githubusercontent.com/1395797/92136653-f11a2300-ee14-11ea-9a64-d4a1ee8cb314.png)

2020-09-06 13:57 UTC, hod-alpert commented
No luck with `Format-Table`.
However, `Out-String` does the trick IMO.

But with big nested objects it becomes less and less readable.

With Json serialization it looks like this:

| PSVersion | PSEdition | GitCommitId | OS | Platform | PSCompatibleVersions | PSRemotingProtocolVersion | SerializationVersion | WSManStackVersion
| --- | --- | --- | --- | --- | --- | --- | --- | ---
| \{<br>  "Major": 6,<br>  "Minor": 2,<br>  "Patch": 3,<br>  "PreReleaseLabel": null,<br>  "BuildLabel": null<br>\} | Core | Unix | \{<br>  "Major": 1,<br>  "Minor": 1,<br>  "Build": 0,<br>  "Revision": 1,<br>  "MajorRevision": 0,<br>  "MinorRevision": 1<br>\} | 6.2.3 | \[<br>  \{<br>    "Major": 1,<br>    "Minor": 0,<br>    "Build": \-1,<br>    "Revision": \-1,<br>    "MajorRevision": \-1,<br>    "MinorRevision": \-1<br>  \},<br>  \{<br>    "Major": 2,<br>    "Minor": 0,<br>    "Build": \-1,<br>    "Revision": \-1,<br>    "MajorRevision": \-1,<br>    "MinorRevision": \-1<br>  \},<br>  \{<br>    "Major": 3,<br>    "Minor": 0,<br>    "Build": \-1,<br>    "Revision": \-1,<br>    "MajorRevision": \-1,<br>    "MinorRevision": \-1<br>  \},<br>  \{<br>    "Major": 4,<br>    "Minor": 0,<br>    "Build": \-1,<br>    "Revision": \-1,<br>    "MajorRevision": \-1,<br>    "MinorRevision": \-1<br>  \},<br>  \{<br>    "Major": 5,<br>    "Minor": 0,<br>    "Build": \-1,<br>    "Revision": \-1,<br>    "MajorRevision": \-1,<br>    "MinorRevision": \-1<br>  \},<br>  \{<br>    "Major": 5,<br>    "Minor": 1,<br>    "Build": 10032,<br>    "Revision": 0,<br>    "MajorRevision": 0,<br>    "MinorRevision": 0<br>  \},<br>  \{<br>    "Major": 6,<br>    "Minor": 2,<br>    "Build": 3,<br>    "Revision": \-1,<br>    "MajorRevision": \-1,<br>    "MinorRevision": \-1<br>  \}<br>\] | Linux 4.19.76\-linuxkit \#1 SMP Tue May 26 11:42:35 UTC 2020 | \{<br>  "Major": 3,<br>  "Minor": 0,<br>  "Build": \-1,<br>  "Revision": \-1,<br>  "MajorRevision": \-1,<br>  "MinorRevision": \-1<br>\} | \{<br>  "Major": 2,<br>  "Minor": 3,<br>  "Build": \-1,<br>  "Revision": \-1,<br>  "MajorRevision": \-1,<br>  "MinorRevision": \-1<br>\}


And with `Out-String` it looks like this:

| PSVersion | PSEdition | GitCommitId | OS | Platform | PSCompatibleVersions | PSRemotingProtocolVersion | SerializationVersion | WSManStackVersion
| --- | --- | --- | --- | --- | --- | --- | --- | ---
| Core | <br>Major  Minor  Build  Revision<br>\-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-\-\-\-<br>3      0      \-1     \-1<br><br> | Unix | <br>Major  Minor  Build  Revision<br>\-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-\-\-\-<br>2      3      \-1     \-1<br><br> | 6.2.3 | <br>Major  Minor  Build  Revision<br>\-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-\-\-\-<br>1      1      0      1<br><br> | Linux 4.19.76\-linuxkit \#1 SMP Tue May 26 11:42:35 UTC 2020 | <br>Major  Minor  Build  Revision<br>\-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-\-\-\-<br>1      0      \-1     \-1<br>2      0      \-1     \-1<br>3      0      \-1     \-1<br>4      0      \-1     \-1<br>5      0      \-1     \-1<br>5      1      10032  0<br>6      2      3      \-1<br><br> | <br>Major  Minor  Patch  PreReleaseLabel BuildLabel<br>\-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-<br>6      2      3                      <br><br>


Which one you think is better?

2020-09-06 15:15 UTC, glicht commented
I suggest using `ToString()` on each object property.

For example: 
![image](https://user-images.githubusercontent.com/1395797/92328935-d6da8200-f06c-11ea-8005-836a668afa81.png)

2020-09-07 06:59 UTC, hod-alpert commented
@glicht `Tostring` does not work well with arrays and hash tables
![image](https://user-images.githubusercontent.com/41257953/92357595-c8ce4500-f0f0-11ea-9831-33060dfa8e04.png)

2020-09-10 06:54 UTC, hod-alpert commented
@glicht Can you please re-review?

2020-09-10 09:40 UTC, glicht approved these changes
Excellent

2020-09-10 13:55 UTC, merged