[Community Contribution] Adding Lacework Integration
demisto/content pull request #8709
Opened 2020-08-28 03:17 UTC by alannix-lw

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues

## Description
This commit adds an integration for the Lacework cloud security platform.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-08-28 03:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=8709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=8709) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=8709) it.</sub>

2020-09-07 07:25 UTC, barchen1 requested changes
Thanks a lot for your contribution!
Here are some notes about this PR:
1. For the commands which return a lot of data I would suggest you to add a "limit" argument.
2. If you dont want to add unitests you can delete the Lacework_test.py file.

Let me know if you have any questions

2020-09-09 00:46 UTC, alannix-lw commented on Packs/Lacework/Integrations/Lacework/README.md
> +This integration was integrated and tested with version xx of Lacework
Resolved with latest commit.

2020-09-09 00:46 UTC, alannix-lw commented on Packs/Lacework/Integrations/Lacework/Lacework.yml
> +    name: lw-get-host-vulnerabilities
Resolved with latest commit.

2020-09-09 00:46 UTC, alannix-lw commented on Packs/Lacework/Integrations/Lacework/Lacework.yml
> +  type: python
Resolved with latest commit.

2020-09-09 00:46 UTC, alannix-lw commented on Packs/Lacework/Integrations/Lacework/Lacework.py
> +        outputs=compliance_data['data'][0]['recommendations']
Resolved with latest commit.

2020-09-13 07:23 UTC, barchen1 commented
@alannix-lw I would like to schedule a short demo for us to go over your PR
let me know when is a good time for you where we could have a call.

2020-09-14 13:07 UTC, alannix-lw commented
@barchen1 I'm UTC-4, so let me know if there's an agreeable time you think we could meet.  I can also do a screen recording if you let me know what you'd like to see.

2020-09-14 13:12 UTC, barchen1 commented
> @barchen1 I'm UTC-4, so let me know if there's an agreeable time you think we could meet. I can also do a screen recording if you let me know what you'd like to see.

2020-09-14 13:14 UTC, barchen1 commented
@alannix-lw Lets talk over Slack and schedule a time for a demo. 
you can also send me an email to bachen@paloaltonetworks.com

2020-09-30 07:38 UTC, barchen1 approved these changes

2020-09-30 08:16 UTC, merged