add Talos IPv4 feed
demisto/content pull request #8734
Opened 2020-08-31 08:22 UTC by DctrG

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Talos IPv4 blocklist feed

## Screenshots

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-09-07 09:07 UTC, barchen1 requested changes
Thanks for your contribution!
Please edit the integration according to my comments and then we'll schedule a demo.

Let me know if you have any questions.

2020-09-08 07:48 UTC, DctrG commented on Packs/FeedTalos/pack_metadata.json
> +    "support": "xsoar",
This is to be supported by Content, I did the same as in my previous contributions, or did something in the procedure change?

2020-09-08 07:48 UTC, DctrG commented on Packs/FeedTalos/pack_metadata.json
> +    "author": "Cortex XSOAR",
Same as above

2020-09-08 08:15 UTC, DctrG commented on Packs/FeedTalos/TestPlaybooks/FeedTalos_Test.yml
> +fromversion: 4.5.0
Changed.

2020-09-08 08:15 UTC, DctrG commented on Packs/FeedTalos/TestPlaybooks/FeedTalos_Test.yml
> +id: FeedTalosTestPlaybook.yml
Done

2020-09-08 08:15 UTC, DctrG commented on Packs/FeedTalos/TestPlaybooks/FeedTalos_Test.yml
> +name: FeedTalosTestPlaybook.yml
Done

2020-09-08 08:15 UTC, DctrG commented on Tests/conf.json
> +            "playbookID": "TalosFeed_Test",
Done

2020-09-08 08:16 UTC, DctrG commented on Packs/FeedTalos/Integrations/FeedTalos/FeedTalos.yml
> +  required: false
Interesting, no idea how did happened, could it be something with the sdk? I have removed them manually.

2020-09-08 09:35 UTC, barchen1 commented on Packs/FeedTalos/pack_metadata.json
> +    "support": "xsoar",
yes, it has been changed.
If you want this pack to be supported by xsoar you need to open an issue about it

2020-09-08 10:01 UTC, DctrG commented on Packs/FeedTalos/pack_metadata.json
> +    "support": "xsoar",
Understood. I've made the changed and pushed the code

2020-09-14 08:51 UTC, barchen1 requested changes
Thanks for the demo!
Here are the things we talked about:
1. Run demisto-sdk secrets and add the secrets to secrets_ignore file.
2. Need a better error handling for invalid url parameter.
3. Change the url parameter location to be above the Indicator Reputation parameter.

Please let me know if you have any questions.

2020-09-14 08:51 UTC, barchen1 commented on Packs/FeedTalos/Integrations/FeedTalos/FeedTalos.py
> +        type_ = item.get('type', FeedIndicatorType.Domain)
Please change as we talked in the demo

2020-09-16 07:27 UTC, barchen1 requested changes

2020-09-16 07:27 UTC, barchen1 commented on Packs/FeedTalos/Integrations/FeedTalos/FeedTalos.yml
> +  required: false
Looks like it happened again, please fix it like you did last time.
<img width="545" alt="Screen Shot 2020-09-16 at 10 24 14" src="https://user-images.githubusercontent.com/54398957/93305269-f0b35c00-f806-11ea-9bd3-06fa84597041.png">

2020-09-16 08:43 UTC, DctrG commented on Packs/FeedTalos/Integrations/FeedTalos/FeedTalos_description.md
>  Collects indicators from Talos Threat Intelligence IPv4 feed:
The whole file empty? By the way, the first 4 lines must have been added by the SDK...

2020-09-21 16:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=8734) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=8734) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: DctrG<br/>:x: barchen1<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=8734) it.</sub>

2020-09-21 16:26 UTC, barchen1 approved these changes

2020-09-22 09:43 UTC, merged