Phishing classifier Ui improvements
demisto/content pull request #8803
Opened 2020-09-03 09:42 UTC by lperryp

Standardizing the terminology of "Confidence threshold" 
Fixing error messages 

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-09-03 17:46 UTC, erezh31 requested changes

2020-09-03 17:46 UTC, erezh31 commented on Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
> +    explain_result_hr['Confidence'] = "%.2f" % predicted_prob
please add another field called confidence and don't replace the current one so we won't have backward compatabilites issues. Also you need to update the outputs - add new output (also have this, the old one)

2020-09-03 17:46 UTC, erezh31 commented on Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
> +                                    confidence_threshold,
you need to support the deprecated argument also

2020-09-03 17:46 UTC, erezh31 commented on Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
> +  description: The label probability threshold. Deprecated, please use quivalnet "confidenceThreshold" arguement.
you need to mark it as deprecated: true, look on other samples

2020-09-03 17:46 UTC, erezh31 commented on Packs/ML/Scripts/DBotPredictOutOfTheBox/DBotPredictOutOfTheBox.yml
> +  description: The label probability threshold. Deprecated, please use quivalnet "confidenceThreshold" arguement.
same

2020-09-08 08:39 UTC, lperryp commented
Changing DBotPRedictPhishingWords to run once as requested at: https://github.com/demisto/etc/issues/27011

2020-09-08 13:07 UTC, erezh31 approved these changes

2020-09-08 13:21 UTC, kirbles19 commented
@lperryp Done

2020-09-09 07:41 UTC, meirwah commented on Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
> +runas: DBotWeakRole
why you need to add this?

2020-09-10 15:34 UTC, Itay4 commented
build fails on non relevant docker image validation
merging

2020-09-10 15:34 UTC, merged