[malwarebytes-254] Fix for events to show up in Classification Mapping
demisto/content pull request #8862
Opened 2020-09-07 14:32 UTC by rskumarmb

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-09-07 15:54 UTC, guyfreund requested changes
Overall looking good, to be done here:
- You've added the `send_usage_data` to send data of the users configuring the integration.
You should mention in the ntegration documentation (`Packs/Malwarebytes/Integrations/Malwarebytes/README.md`) file that this integration sends data of the user using this integration and specify what data is being sent.
- Make sure the CircleCI build passes.

2020-09-11 08:02 UTC, rskumarmb commented
@guyfreund I have made the changes.

2020-09-13 17:07 UTC, guyfreund approved these changes

2020-09-13 17:09 UTC, guyfreund commented
@rskumarmb I've mentioned `Malwarebytes` as the data collector in the integration docs, if that's okay from your end we can proceed to schedule a demo. We are available Sunday-Thursday 9:00-18:00 IST (Israel).

2020-10-05 12:29 UTC, merged