adding new commands
demisto/content pull request #8895
Opened 2020-09-09 08:12 UTC by esharf

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28082.

## Description
added new commands
  - ***esm-create-watchlist***
  - ***esm-delete-watchlist***
  - ***esm-get-watchlists***
  - ***esm-watchlist-add-entry***
  - ***esm-watchlist-delete-entry***
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-09-12 18:29 UTC, yaakovi requested changes

2020-09-12 18:29 UTC, yaakovi commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +    def watchlist_values(self, file_token, buff_size=50):
add doc-string to the function and inline comments.

2020-09-13 04:46 UTC, esharf commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +        for i in itertools.count(start=0):
Because it needs to be endless (using a `break`).
so this is replacing.
```
i = 0
while True:
    ...
    i += 1
```

2020-09-13 06:26 UTC, esharf commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +        return 'Watchlists removed', {}, {}
there is no response

2020-09-13 06:27 UTC, esharf commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +        return human_readable, {}, {}
there is no response

2020-09-13 06:28 UTC, esharf commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +        return human_readable, {}, {}
there is no response

2020-09-13 06:28 UTC, esharf commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +        count_results = result.get('recordCount') or result.get('valueCount')
other versions (10 vs 11)

2020-09-13 06:31 UTC, esharf commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +                if i < offset:
I need this for counting the data.
(I got the data as bytes)

2020-09-13 16:56 UTC, yaakovi commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
> +      description: The watchlist data.
```suggestion
      description: The watchlist name.
```

2020-09-13 16:56 UTC, yaakovi commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +        count_results = result.get('recordCount') or result.get('valueCount')
add a comment for it

2020-09-13 16:57 UTC, yaakovi commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +    def watchlist_values(self, file_token, buff_size=50):
add inline comments to explain the code

2020-09-15 12:23 UTC, yaakovi approved these changes

2020-09-15 12:23 UTC, yaakovi commented on Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
> +        # count_results = result['recordCount'] (v 11) or result['valueCount'] (v 10)
```suggestion
        # v10.x uses 'valueCount' while v11.x uses 'recordCount'.
```

2020-09-22 12:31 UTC, merged