Hackaton - Tidy project
demisto/content pull request #9012
Opened 2020-09-18 12:21 UTC by GalRabin

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Description
Only the First draft.

## Must have
- [ ] Tests
- [ ] Documentation

2020-09-18 12:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=9012) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=9012) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=9012) it.</sub>

2020-09-21 05:14 UTC, hod-alpert requested changes
Looks good!!
a few comments:
1. In both `tidy-python` and `tidy-golang` we have a parameter `globals` which can be given as array of globals, are we sure this is possible? AFAIK there can be only one global configured at a time.
2. In both `tidy-python` and `tidy-golang` since we're talking about limited amount of versions I think I would make it PRE-DEFINED with all relevant versions (for both globals and versions)
3. What happened to the profiles and users we discussed? Aren't they supposed to be there too?
4. Installing go, python and cloning git repos are not enough IMO, this is not the time-consuming part and I think we should be able to do more then just that to be valuable. For example
In the internal demisto ansible you have also installed bashrc to zshrc with global variables and useful aliases and also some git config was there. I think this can be the game changer or at least part of it.

2020-09-23 08:02 UTC, GalRabin commented
# Tasks:
## @GalRabin 
- [ ] Python
- [ ] GoLang
- [ ] Git clones
- [ ] Github ssh key

## @hod-alpert 
- [ ] Env variables, bash_profile, zshrc
- [ ] ZSH

- [ ] Home brew

2020-09-25 07:20 UTC, hod-alpert commented
Merged to tidy/master

2020-09-25 08:17 UTC, closed without merging