Analyst1 - Rebrand illuminate to Analyst1
demisto/content pull request #9019
Opened 2020-09-18 16:00 UTC by runt9

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
Recently AnalystPlatform has rebranded itself as Analyst1, consolidating both the company name, AnalystPlatform, and our flagship product, illuminate, under the same name. This Pull Request is opened to update our integration to reflect the appropriate rebranding.

One note is it appears there is also some test data for the CortexXDR integration and I wasn't sure if it was safe to update said test data to reflect the rebranding or not.

2020-09-18 16:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=9019) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=9019) before we can accept your contribution.<br/><hr/>**Alex Vester** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=9019) it.</sub>

2020-09-21 18:14 UTC, runt9 commented
Looks like I'm having issues with the release notes being accepted. I renamed the Packs directory from `illuminate` to `Analyst1` and I think that's throwing off the `1.0.1` and `1.0.2` release notes, and the validator is treating this update as a "new" pack and thus is saying I should remove the `1.0.3` release notes. What's the right way to proceed?

2020-09-22 08:11 UTC, barchen1 commented
> Looks like I'm having issues with the release notes being accepted. I renamed the Packs directory from `illuminate` to `Analyst1` and I think that's throwing off the `1.0.1` and `1.0.2` release notes, and the validator is treating this update as a "new" pack and thus is saying I should remove the `1.0.3` release notes. What's the right way to proceed?

@runt9 You should threat this pack as a new pack and delete the ReleaseNotes folder.

2020-09-22 16:26 UTC, runt9 commented
> @runt9 You should threat this pack as a new pack and delete the ReleaseNotes folder.

@barchen1 Thank you, I'll be sure to do that! In addition, I modified the illuminate -> Analyst1 name in other Packs. Should I generate release notes for those Packs, or should I not change them and allow the developers of those Packs to update them?

2020-09-30 10:59 UTC, barchen1 requested changes
Thanks for your contribution!
Here are some notes about this PR:
The changes you made here break BC for users who are already use this integration. 
Here is my suggestion:
1. Change the pack directory to its original name- illuminate.
    - changing the folder name will create a new pack and the customers will not be notified on this update.
2. The `name` field in the pack_metadata file is the name of the pack that the customers see so you can leave it as Analyst1.
3. Create a duplicate integration of illuminate which will be named as `Analyst1` and deprecate the `illuminate` integration. 
for deprecating an integration you need to:
     - add `deprecated: true` filed to illuminate yml file and 
     -  add `tests:
                  - No Tests - Deprected` to the illuminate yml file.
     - add `hidden: true` filed to illuminate playbooks. 

Update me what you would like to do - break BC or do the changes as I suggested.
Either way you choose the pack folder needs to be named as illuminate.
Let me know if you have any questions.

2020-10-01 20:08 UTC, runt9 commented
@barchen1 Thank you for your review. I just merged the upstream branch in and did a hard reset so I can apply the changes on a fairly clean branch without hurting the PR. I will have the proper commit in shortly.

2020-10-07 14:08 UTC, barchen1 commented
@runt9 From your last commit I understand you choose to deprecate illuminate.
If you want to deprecate this integration you need to have only one pack name `illuminate`
Under this pack you will have 2 integrations - `illuminate` and `Analyst1`.
You don't need to add a pack named `Analyst1`
Please reach me out on Slack if you need help with that.

2020-10-07 14:14 UTC, barchen1 requested changes

2020-10-07 14:14 UTC, barchen1 commented on Packs/illuminate/Integrations/illuminate/illuminate.yml
> +  - Deprecated
```suggestion
tests:
  - No Tests  - Deprecated
```

2020-10-07 14:14 UTC, barchen1 commented on Packs/Analyst1/Integrations/Analyst1/Analyst1.yml
> +- No tests (auto formatted)
```suggestion
- Analyst1 Integration Demonstration - Test
```

2020-10-11 12:16 UTC, barchen1 approved these changes

2020-10-11 12:53 UTC, merged