Logizo - remove tests
demisto/content pull request #9037
Opened 2020-09-21 08:07 UTC by ChanochShayner

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
In case you are a technological partner:
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

If you are not a technological partner (i.e. PANW employee, customer or individual developer), please delete this section.

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/26729#

## Description
remove the test from conf.json and add - No tests to the integration yml.
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-09-21 08:25 UTC, ShahafBenYakir approved these changes

2020-09-21 08:41 UTC, guykeller approved these changes

2020-09-22 07:34 UTC, ShahafBenYakir commented on Packs/Logzio/ReleaseNotes/1_1_1.md
> +- Change docker image to - 3.8.5.10845, Maintenance and stability enhancements.
```suggestion
- Change the docker image to - 3.8.5.10845.
```

2020-09-22 07:35 UTC, ShahafBenYakir commented
Why have you moved the test PB to the NonCircle folder?

2020-09-23 09:03 UTC, ShahafBenYakir requested changes
Remove the NonCircleFolder

2020-10-04 15:45 UTC, Itay4 commented
@ShahafBenYakir @ChanochShayner what is the status here?

2020-10-05 07:56 UTC, ShahafBenYakir commented
@Itay4  There is a bug in the flow of collecting tests we have a meeting on this tomorrow which after we'll decide what is needed.

2020-11-25 07:51 UTC, ShahafBenYakir commented
@ChanochShayner The issue was fixed pull and re run

2020-11-25 08:11 UTC, ChanochShayner commented
@ShahafBenYakir I'm not sure I understand, what's supposed to change in this PR?
At the moment the changes are - removing the tests from logzio, is that what it should be?

2020-11-25 08:18 UTC, ShahafBenYakir commented
@ChanochShayner Yes. Your build failed because of an issue with the collect test that was fxied.

2020-11-25 14:30 UTC, ChanochShayner commented
@ShahafBenYakir Waiting for your approval, thanks.

2020-11-25 15:34 UTC, ShahafBenYakir approved these changes

2020-11-25 15:37 UTC, merged