Ssl troubleshout
demisto/content pull request #9081
Opened 2020-09-23 15:04 UTC by GalRabin

FYI - @chris4490 

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/28501

## Description
A new pack for troubleshooting which currently includes only custom certificate output and information.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-09-25 23:07 UTC, yaakovi requested changes

2020-09-25 23:07 UTC, yaakovi commented on Packs/Troubleshout/Scripts/CertificatesTroubleshout/CertificatesTroubleshout.py
> +        "CustomCertificateAuthorities": parse_all_certificates(certificates)
```suggestion
        "CustomCertificateAuthorities": parse_all_certificates(certificates),
```

2020-09-25 23:07 UTC, yaakovi commented on Packs/Troubleshout/Scripts/CertificatesTroubleshout/CertificatesTroubleshout.py
> +            "CERT_FILE": os.environ.get('REQUESTS_CA_BUNDLE')
```suggestion
            "CERT_FILE": os.environ.get('REQUESTS_CA_BUNDLE'),
```

2020-09-27 12:15 UTC, GalRabin commented on Packs/Troubleshout/Scripts/CertificatesTroubleshout/CertificatesTroubleshout.yml
> +  description: Endpoint identifier IP/URL:Port, If port not included will use 443
The description isn't right, By default, it will be 443, By its influenced by port arg (Not by the endpoint).

2020-09-29 09:26 UTC, yaakovi approved these changes

2020-10-11 06:53 UTC, ShirleyDenkberg commented
@gal001 Review is done.

2020-10-11 12:28 UTC, merged