[safebreach-129] SafeBreach fix small bugs
demisto/content pull request #9083
Opened 2020-09-23 15:27 UTC by gtsafeB

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
In case you are a technological partner:
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

If you are not a technological partner (i.e. PANW employee, customer or individual developer), please delete this section.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: fix calculation of the total simulations number and 'indicatorLimit' params was cast to default value(1000) if not provided.

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-09-29 14:39 UTC, barchen1 requested changes
Thanks for your contribution!

2020-09-30 08:17 UTC, gtsafeB commented on Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
> +        indicator_limit_param = 1000
I'm not sure that's correct when indicatorLimit is not provided in the configure screen its set as '' (=empty string) which get() will return a value and the default value will not be returned.

2020-09-30 09:07 UTC, barchen1 requested changes

2020-09-30 09:07 UTC, barchen1 commented on Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
> +        indicator_limit_param = 1000
So you can edit the indicatorLimit param and add an initial value.

<img width="556" alt="Screen Shot 2020-09-30 at 11 35 16" src="https://user-images.githubusercontent.com/54398957/94662532-31d06380-0311-11eb-8bf8-27549870d22b.png">


Cause 1000 can cause to an overload, 200 is our default.

2020-09-30 09:12 UTC, gtsafeB commented on Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
> +        indicator_limit_param = 1000
Great, let's do it that way.
I'll keep the initial value to be 1000 if that's ok

2020-09-30 09:34 UTC, barchen1 requested changes

2020-09-30 09:34 UTC, barchen1 commented on Packs/SafeBreach/Integrations/SafeBreach_v2/SafeBreach_v2.py
> +        indicator_limit_param = 1000
np, you can keep it as 1000

2020-09-30 11:14 UTC, barchen1 approved these changes

2020-09-30 12:00 UTC, merged