Added option to provide string as input and convert to JSON in the code.
demisto/content pull request #9124
Opened 2020-09-25 09:38 UTC by aburt-demisto

Added another test for the string input too.

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
In case you are a technological partner:
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

If you are not a technological partner (i.e. PANW employee, customer or individual developer), please delete this section.

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
https://github.com/demisto/etc/issues/28801

## Description
This code alteration allows the transformer to accept a string as its "value" input. It will then attempt to convert this string into JSON data within the code. This is to remediate the issue listed above.

## Screenshots
![image](https://user-images.githubusercontent.com/53576129/94251958-3238bb00-ff1b-11ea-8a3d-eec61c902e31.png)

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-09-28 17:48 UTC, yaakovi commented on Packs/CommonScripts/Scripts/Jmespath/jmespath_transformer.py
> +    if type(value) == str:
```suggestion
    if isinstance(value, str):
```

2020-09-29 09:20 UTC, barchen1 requested changes
Thanks for your contribution!
Please add release notes to this directory : Packs/CommonScripts/ReleaseNotes
Your unitest failed, please fix it 
Let me know if you need help

2020-10-04 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=9124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=9124) before we can accept your contribution.<br/>**7** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: aburt-demisto<br/>:white_check_mark: content-bot<br/>:white_check_mark: barchen1<br/>:white_check_mark: yaakovi<br/>:white_check_mark: Shellyber<br/>:white_check_mark: roysagi<br/>:white_check_mark: reutshal<br/>:x: GalRabin<br/>:x: lperryp<br/>:x: esharf<br/>:x: altmannyarden<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=9124) it.</sub>

2020-10-04 10:54 UTC, barchen1 approved these changes

2020-10-04 10:57 UTC, merged