Devsecops
demisto/content pull request #9134
Opened 2020-09-26 14:47 UTC by ayman-m

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A pack of DevSecOps integrations and playbooks, more information in pack's README file

## Screenshots
Screenshots in pack's README file

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2020-10-26 11:11 UTC, yaakovi requested changes
following our session,
please remove the Github-related changes to a separate PR and apply them to the current Github integration.

when opening the new PR, link it to this one.
after you are done, we will take it from there.

thank you.

2020-11-08 10:50 UTC, ayman-m commented
Hello @yaakovi, I have pushed a new commit after reviewing your comments

2020-11-25 06:52 UTC, ayman-m commented
The Github integration update [PR](https://github.com/demisto/content/pull/9972)

2020-12-30 06:17 UTC, ayman-m commented
Hello @yaakovi, I have pushed a new Integration to this Pack,

2021-02-07 07:13 UTC, ChanochShayner commented
Following our conversation from Thursday, here are comments we talked about:
 - Please run the demisto-sdk format command on the files you have in PR.
 - You are missing 3 incident types (which appear within the incident fields) and one type indicator.
 - The indicator - commit_id associated with incident types instead of indicator types.
The names of all incident/indicator/fields/types should start with the name of the pack - for example, `commitid` -> `devsecops_commitid`
Please correct these comments and update me so I can go through all the files in PR.
Thanks!!

2021-02-08 15:12 UTC, ayman-m commented
>     * `devsecops_commitid`

@ChanochShayner , I've pushed two new commits that reflect the updates based on the findings above

2021-02-10 08:45 UTC, ChanochShayner commented on Packs/DevSecOps/IncidentFields/DevSecOps_After_Commit_ID.json
> +    "id": "incident_aftercommitid",
```suggestion
    "id": "incident_devsecopsaftercommitid",
``` 
Same in all incident fields/types indicator fields/types

2021-02-10 08:46 UTC, ChanochShayner commented on Packs/DevSecOps/IncidentFields/DevSecOps_After_Commit_ID.json
> +    "name": "After Commit ID",
```suggestion
    "name": "Dev Sec Ops After Commit ID",
```
Same in all incident fields/types indicator fields/types

2021-02-10 08:46 UTC, ChanochShayner commented on Packs/DevSecOps/IncidentFields/DevSecOps_After_Commit_ID.json
> +    "cliName": "aftercommitid",
```suggestion
    "cliName": "devsecopsaftercommitid",
```
Same in all incident fields/types indicator fields/types

2021-02-10 08:47 UTC, ChanochShayner commented on Packs/DevSecOps/IncidentFields/DevSecOps_After_Commit_ID.json
> +        "New Git PR"
```suggestion
        "Dev Sec Ops New Git PR"
```
Same in all incident fields/types indicator fields/types

2021-02-10 09:44 UTC, ChanochShayner reviewed
Looks great!!
1 - Are the versions of the files in the Pack intentionally version 5 rather than version 6?
2 - You have a lot of files with run examples (mostly readme files) that have really specific details about people or codes.
Please remove them, you can use names that are understood to be sample/test only.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Integrations/DockerEngine/DockerEngine.yml
> +  type: 12
```suggestion
  type: 4
```
Please use encrypted type - 4

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Integrations/DockerEngine/DockerEngine.yml
> +  type: 12
```suggestion
  type: 4
```
Same here

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Integrations/GitLab/GitLab.yml
> +type: python
This file does not look good, please fix it.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Playbooks/DevSecOps_-_Fetch_PR_-_Triage.yml
> +fromversion: 1.0.0
```suggestion
fromversion: 5.0.0
```
The version should be consistent across all files in the Pack
(It's currently 5.0.0) Please fix this.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Playbooks/DevSecOps_-_LGTM_-_Analysis_-_SubPB.yml
> +fromversion: 1.0.0
```suggestion
fromversion: 5.0.0
```
The version should be consistent across all files in the Pack
(It's currently 5.0.0) Please fix this.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Playbooks/DevSecOps_-_Prisma_-_Analysis_-SubPB.yml
> +fromversion: 1.0.0
```suggestion
fromversion: 5.0.0
```
The version should be consistent across all files in the Pack
(It's currently 5.0.0) Please fix this.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/TestPlaybooks/GitLab-test-playbook.yml
> +fromversion: 4.5.0
```suggestion
fromversion: 5.0.0
```
The version should be consistent across all files in the Pack
(It's currently 5.0.0) Please fix this.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/TestPlaybooks/LGTM-test-playbook.yml
> +fromversion: 4.5.0
```suggestion
fromversion: 5.0.0
```
The version should be consistent across all files in the Pack
(It's currently 5.0.0) Please fix this.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/TestPlaybooks/MinIO-test-playbook.yml
> +fromversion: 4.5.0
```suggestion
fromversion: 5.0.0
```
The version should be consistent across all files in the Pack
(It's currently 5.0.0) Please fix this.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/pack_metadata.json
> +    "url": "https://www.paloaltonetworks.com/cortex",
The URL here should be the product in the pack, please remove it.

2021-02-10 09:44 UTC, ChanochShayner commented on Tests/conf.json
> +            "playbookID": "playbook-MinIO-Test"
Please remove the changes from this file.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/README.md
> +![](doc_files/Prisma%20Analysis%20PB.png)
It seems that the file has not been updated for recent changes, for example, there is only one incident type.
Please update it.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Integrations/MinIO/README.md
> +This integration was integrated and tested with version xx of MinIO.
```suggestion
This integration was integrated and tested with version ? of MinIO.
```
Please fill in the relevant version (if there is one)

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Integrations/GitLab/README.md
> +            "name": "Omar Elkhayam",
```suggestion
            "name": "?",
```
We do not want specific people's names to be in our files.

2021-02-10 09:44 UTC, ChanochShayner commented on Packs/DevSecOps/Integrations/GitLab/README.md
> +            "username": "OmarElkhayam",
same here

2021-02-15 07:25 UTC, ChanochShayner reviewed
Please go over the validation and lint errors and fix them.
In layouts, you changed the versions from - 
"fromVersion": "5.0.0",
"toVersion": "5.9.9",
To -
"fromVersion": "6.0.0",

In layouts there is a difference between the versions, so to change a version you need to remove the change and run the command - `demisto-sdk convert-layout -i Packs / TestPack1 -fts`

2021-02-15 07:25 UTC, ChanochShayner commented on Tests/conf.json
> +}
Could you please remove the changes (even if they are just blank lines) from this file - conf.json?
It causes conflicts.

2021-02-15 07:25 UTC, ChanochShayner commented on Packs/DevSecOps/TestPlaybooks/LGTM-test-playbook.yml
> +fromversion: 4.5.0
```suggestion
fromversion: 6.0.0
```

2021-02-15 07:25 UTC, ChanochShayner commented on Packs/DevSecOps/TestPlaybooks/MinIO-test-playbook.yml
> +fromversion: 4.5.0
```suggestion
fromversion: 6.0.0
```

2021-02-15 07:25 UTC, ChanochShayner commented on Packs/DevSecOps/TestPlaybooks/GitLab-test-playbook.yml
> +fromversion: 4.5.0
```suggestion
fromversion: 6.0.0
```

2021-02-19 15:49 UTC, ayman-m commented
@ChanochShayner, I am not sure what's wrong with Test/conf.json, and why it's causing a merge conflict, one more issue, I am currently  using a non-demisto docker image for the MinIO integration (minio:latest), shall I submit another PR for a docker build file ?

2021-02-22 07:24 UTC, ChanochShayner reviewed
You need to be consistent with the file versions - currently, all files are from version 6, except:
`Packs / DevSecOps / Integrations / GitLab / GitLab.yml`
`Packs / DevSecOps / Layouts / layout-DevSecOps_New_Git_Issue.json` - (I think this incident type no longer exists, if so please remove this layout.)
`Packs / DevSecOps / Layouts / layout-DevSecOps_New_Git_PR.json`
If you want to change the layout to version 6 you can use the command that exists in sdk (I explained it in the previous comment)

2021-02-22 10:24 UTC, ayman-m commented
> You need to be consistent with the file versions - currently, all files are from version 6, except:
> `Packs / DevSecOps / Integrations / GitLab / GitLab.yml`
> `Packs / DevSecOps / Layouts / layout-DevSecOps_New_Git_Issue.json` - (I think this incident type no longer exists, if so please remove this layout.)
> `Packs / DevSecOps / Layouts / layout-DevSecOps_New_Git_PR.json`
> If you want to change the layout to version 6 you can use the command that exists in sdk (I explained it in the previous comment)

2021-03-21 17:00 UTC, ayman-m commented
MinIO integration requires the "minio" package , I am referencing a local (non xsoar) docker image in the code

2021-03-22 07:22 UTC, ChanochShayner commented
Unassigning myself, @guykeller @yaakovi FYI.

2021-04-10 10:05 UTC, yaakovi reviewed
PR is pending for https://github.com/demisto/content/pull/12148

2021-05-14 10:23 UTC, ayman-m commented
> PR is pending for #12148

@yaakovi FYI #12148 is now merged

2021-05-25 21:04 UTC, yaakovi approved these changes

2021-05-30 08:09 UTC, merged