Added URLEncode transformer
demisto/content pull request #9160
Opened 2020-09-29 10:17 UTC by adi88d

## XSOAR [Partner](https://xsoar.pan.dev/docs/partners/become-a-tech-partner)?
In case you are a technological partner:
- [ ] The title must be in the following format: **[YOUR_PARTNER_ID] short description**.

If you are not a technological partner (i.e. PANW employee, customer or individual developer), please delete this section.

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28694

## Description
Added URLEncode transformer.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-10-01 00:32 UTC, yaakovi requested changes

2020-10-01 00:32 UTC, yaakovi commented on Packs/CommonScripts/TestPlaybooks/playbook-URLEncode-Test.yml
> +      scriptName: URLEncode
you should use it as a transformer, not as a regular script.

2020-10-01 00:32 UTC, yaakovi commented on Packs/CommonScripts/Scripts/URLEncode/URLEncode.py
> +    return CommandResults(readable_output=processed_value,
a transformer shouldn't have context and readable output.
no need to use `CommandResults`

2020-10-01 00:32 UTC, yaakovi commented on Packs/CommonScripts/TestPlaybooks/playbook-URLEncode-Test.yml
> +      name: URLDecode
```suggestion
      name: URLEncode
```

2020-10-01 00:32 UTC, yaakovi commented on Packs/CommonScripts/Scripts/URLEncode/URLEncode.py
> +def main(args):
add sanity unit-tests:
* where input is encoded
* where input isn't encoded

2020-10-01 00:32 UTC, yaakovi commented on Packs/CommonScripts/Scripts/URLEncode/URLEncode.yml
> +  Converts
improve description

2020-10-01 00:32 UTC, yaakovi commented on Packs/CommonScripts/Scripts/URLEncode/URLEncode.yml
> +  type: String
remove

2020-10-01 00:32 UTC, yaakovi commented on Packs/CommonScripts/ReleaseNotes/1_2_50.md
> +- Converts
update with the new description

2020-10-04 20:38 UTC, yaakovi approved these changes

2020-10-04 20:38 UTC, yaakovi commented on Packs/CommonScripts/Scripts/URLEncode/URLEncode_test.py
> +def test_URLEncode_partial_encoded_input():
nice!

2020-10-05 09:25 UTC, kirbles19 commented
@adi88d Done

2020-10-05 12:14 UTC, merged