majestic million feed 101
demisto/content pull request #9321
Opened 2020-10-06 08:04 UTC by bakatzir

## Status
- [x] In Progress - pending design

## Related Issues
fixes: https://github.com/demisto/etc/issues/24432

## Description
a referenced draft pr to have the knowledge saved.

## Minimum version of Demisto
- [x] 5.5.0

## Does it break backward compatibility?
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-10-11 06:47 UTC, yuvalbenshalom requested changes
looks good.
please add descriptions and readme to the feed.
lets talk about performance testing.

2020-10-11 06:47 UTC, yuvalbenshalom commented on Packs/FeedMajesticMillion/pack_metadata.json
> +    "description": "TODO",
add description

2020-10-11 07:39 UTC, bakatzir commented
@kirbles19 please review the readme, detailed_desc and yml of this PR, aside from the RN.
one note - as it is ingesting up to 1M indicators, i've added a troubleshooting message regarding performance both in the readme and the detailed desc, please have a look at it as well.

2020-10-12 13:06 UTC, bakatzir commented
I've added more memory to majestic million as there are 1m IOCs.
alienvaultfeed seems to fail from time to time on exceeding the docker memory as well, might be related to the fact that both of them are running on the same machine.

2020-10-12 20:36 UTC, yuvalbenshalom requested changes
looks good.
see my comments.

2020-10-12 20:36 UTC, yuvalbenshalom commented on Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
> +        if not regex_extractor:  # do not run the regex match only if a regex_extractor does not exist
I think you can drop the comment, it is clear without.

2020-10-12 20:36 UTC, yuvalbenshalom commented on Packs/FeedMajesticMillion/Integrations/MajesticMillion/MajesticMillion_description.md
> +Free search and download of the top million websites.
```suggestion
Free search and download of the top million websites.
This feed integration ingests the top most common web sites addresses as 'good' indicators.
```

2020-10-14 09:08 UTC, yuvalbenshalom approved these changes

2020-10-18 15:36 UTC, bakatzir commented
@ShirleyDenkberg Any more comments? please review the README.md file with regards to the performance issues that may arise when fetching 1M indicators.

2020-10-19 05:59 UTC, ShirleyDenkberg commented
@bakatzir Doc review is done.

2020-10-19 13:37 UTC, merged