Build env miss calculation fix
demisto/content pull request #9337
Opened 2020-10-07 07:17 UTC by Shellyber

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28974

## Description
Checking now in the modified files if there is a `fromversion` that it’s bigger than the `toversion` that was found.
If so, the `toversion` will become the default.

## Screenshots
![image](https://user-images.githubusercontent.com/45915502/95299233-07892380-0886-11eb-83e9-fc7fed2d3ff4.png)

## Must have
- [ ] Tests

2020-10-07 18:48 UTC, yaakovi commented on Tests/scripts/collect_tests_and_content_packs.py
> +        'Server Master': True,
remove this - not relevant.
`Demisto Marketplace` is the master.

2020-10-07 18:48 UTC, yaakovi commented on Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
> +        Given:
fix docstring

2020-10-07 18:48 UTC, yaakovi commented on Tests/scripts/collect_tests_and_content_packs.py
> +                        max_from_version = max(min_from_version, LooseVersion(from_version))
```suggestion
                        max_from_version = max(max_from_version, LooseVersion(from_version))
```

2020-10-08 05:14 UTC, hod-alpert requested changes

2020-10-08 05:14 UTC, hod-alpert commented on Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
> +                                          modified_tests_list=[test_playbook_path])
Why do you need this in the test?
Why not just create a set of modified files and assert the generated from\to version.

2020-10-08 05:14 UTC, hod-alpert commented on Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
> +            filter_envs = json.load(filter_envs_file)
Also this is not required

2020-10-08 05:14 UTC, hod-alpert commented on Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
> +        assert filter_envs.get('Demisto GA') is True
And this

2020-10-08 05:14 UTC, hod-alpert commented on Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
> +                                          modified_tests_list=[test_playbook_path])
Just give different sets of files and see that the from,to version gets the expected values

2020-10-08 05:14 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
> +    max_from_version = LooseVersion('0.0.0')
Do you really need the max from version in this calculation?
Why not simply do in line 1228
```
max_to_version.vstring == '0.0.0' or max_to_version <= min_from_version
```

2020-10-08 05:14 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
> +    max_from_version = LooseVersion('0.0.0')
Also update the method's doc string about what we're doing in that case

2020-10-08 07:18 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
> +    In case that max_from_version is bigger than max to version - to version will be the the highest default.
```suggestion
    In case that max_from_version is higher than max to version - to version will be the the highest default.
```

2020-10-08 07:20 UTC, hod-alpert approved these changes
Just fix the grammer and docstring of the unittest

2020-10-08 07:23 UTC, hod-alpert commented on Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
> +            - Check that the toversion in the default (99.99.99)
```suggestion
            - Check that the toversion is the default (99.99.99)
```

2020-10-08 07:24 UTC, hod-alpert commented on Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
> +        test_path_integration = 'Tests/scripts/infrastructure_tests/tests_data/mock_integrations/' \
```suggestion
        test_integration_path = 'Tests/scripts/infrastructure_tests/tests_data/mock_integrations/' \
```

2020-10-08 09:33 UTC, merged