Added error message for untrusted certificate EWS V2
demisto/content pull request #9364
Opened 2020-10-08 11:46 UTC by teizenman

## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/29218

## Description
The status code is 503, the error is different than generic.

## Screenshots
![image](https://user-images.githubusercontent.com/50326704/95454266-e3f0d680-0974-11eb-929f-c71c3bfd7bb0.png)

2020-10-08 12:51 UTC, glicht requested changes

2020-10-08 12:51 UTC, glicht commented on Packs/EWS/Integrations/EWSv2/EWSv2.py
> +            error_message_simple = "Got timeout from the server. " \
Remove this line about timeout. As it is not timeout related. Let's use the following message:

`Certificate verification failed - This error may happen if the server certificate cannot be validated or as a result of a proxy that is doing SSL/TLS termination. It is possible to bypass certificate validation by checking 'Trust any certificate' in the instance settings.`

@kirbles19 please review this message.

2020-10-13 07:51 UTC, teizenman commented
@kirbles19 
Can you please review the error message here: https://github.com/demisto/content/blob/65ea732f7a4f90b10d913810397305c109faa6ba/Packs/EWS/Integrations/EWSv2/EWSv2.py#L2133:L2136

2020-10-14 15:39 UTC, glicht approved these changes

2020-10-14 15:40 UTC, glicht commented
> @kirbles19
> Can you please review the error message here: https://github.com/demisto/content/blob/65ea732f7a4f90b10d913810397305c109faa6ba/Packs/EWS/Integrations/EWSv2/EWSv2.py#L2133:L2136

@kirbles19 waiting for you. Add the `docs-approved` tag when done.

2020-10-18 05:59 UTC, kirbles19 commented
@teizenman Looks good to me.

2020-10-18 09:02 UTC, merged