ServiceNow CMDB
demisto/content pull request #9431
Opened 2020-10-12 14:42 UTC by darkushin

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/14034

## Description
Implementing the integration for Service Now CMDB.

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-10-12 14:46 UTC, Itay4 commented on Packs/ServiceNow_CMDB/Integrations/ServiceNow_CMDB/test_data/result_constants.py
> +                'email_id': 'akrupnik@paloaltonetworks.com',
make sure we dont have this kind of sensitive data in the mocks

2020-10-13 06:54 UTC, bakatzir reviewed
@Arsenikr Do we want this integration as a new pack? or shall it be part of the `ServiceNow` pack?

2020-11-12 17:01 UTC, yuvalbenshalom requested changes
this is a preliminary review, see my comments.

2020-11-12 17:01 UTC, yuvalbenshalom commented on Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB.py
> +def handle_sysparms(sys_parms: List, args: dict) -> dict:
lets talk about this one. not sure if it is necessary.

2020-11-15 10:14 UTC, yuvalbenshalom requested changes
good, just remove the hello world leftovers.

2020-11-15 10:14 UTC, yuvalbenshalom commented on Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB.yml
> +defaultclassifier: HelloWorld
remove

2020-12-02 18:22 UTC, yuvalbenshalom commented
@darkushin please check the test playbook, its still failing.

2020-12-06 06:18 UTC, yuvalbenshalom approved these changes

2020-12-06 08:07 UTC, darkushin commented
@kirbles19 @ShirleyDenkberg This is a new integration for a ServiceNow product we didn't support before. Thank you!

2020-12-13 06:48 UTC, ShirleyDenkberg commented
@Itay4 @bakatzir  @yuvalbenshalom 
Doc review completed.

2020-12-13 08:53 UTC, merged