ApiModule for tokenization
demisto/content pull request #9536
Opened 2020-10-18 13:58 UTC by lperryp

## Description
Replacing WordTokenizerV2 call to ApiModule 

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-10-19 16:33 UTC, erezh31 requested changes

2020-10-19 16:33 UTC, erezh31 commented on Packs/ApiModules/Scripts/MLApiModule/MLApiModule.py
> +        return_error("Input text length ({}) exceeds the legal maximum length for preprocessing".format(len(t)))
why we return error in that case?
I think return error do sys.exit, do we want that?

2020-10-19 16:33 UTC, erezh31 commented on Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml
> +    "German", "French", "Spanish", "Portuguese", "Italian", "Dutch", or "Other".
I think we need to update the languages, no?

2020-10-19 16:33 UTC, erezh31 commented on Packs/ApiModules/Scripts/MLApiModule/TestData/input_json_file_test
> +[{"body": "This is a sample of the body", "subject": "This is a sample of the subject"},
let's have some UTF-8 chars in the file

2020-10-19 16:33 UTC, erezh31 commented on Packs/ApiModules/Scripts/MLApiModule/TestData/input_json_file_test
> +{"body2": "This is a sample of the body2", "subject2": "This is a sample of the subject2", "subject": "This is a sample of the subject"}]
maybe add also a CSV - we use it also in the train from file. Also include utf8 characters in the CSV

2020-10-19 16:33 UTC, erezh31 commented on Packs/ApiModules/Scripts/MLApiModule/MLApiModule.py
> +            return pd.read_csv(file_path).fillna('').to_dict(orient='records')
add test to csv case as mentioned below

2020-10-19 16:33 UTC, erezh31 commented on Packs/ApiModules/Scripts/MLApiModule/MLApiModule.py
> +                token_without_punct = ''.join([c for c in t if c not in string.punctuation])
I think NLTK has punct tokenizer, maybe we can consider using that

2020-10-20 11:32 UTC, kirbles19 commented
@lperryp Done

2020-10-21 11:20 UTC, lperryp commented
Hard to follow changes, will re-open and apply changes in new pr: https://github.com/demisto/content/pull/9594

2020-10-21 11:20 UTC, closed without merging