Cylance protect v2
demisto/content pull request #9550
Opened 2020-10-19 08:42 UTC by abaumgarten

## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/29543

## Description
Fixed un-matched parameters' names as page to pageNumber and pageItems to pageSize

## Minimum version of Demisto
- [x] 5.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [x] Tests
- [x] Documentation

2020-10-19 09:15 UTC, guykeller requested changes

2020-10-19 09:15 UTC, guykeller commented on Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.yml
> +      name: pageSize
Why was this change needed? Just because the older name wasn't accurate?

2020-10-19 09:15 UTC, guykeller commented on Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.py
> +    page_size = demisto.args()['pageSize'] if 'pageSize' in demisto.args() else None
Also - no tests?

2020-10-19 09:28 UTC, abaumgarten commented on Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.py
> +    page_size = demisto.args()['pageSize'] if 'pageSize' in demisto.args() else None
changed to:
page = demisto.args().get('pageNumber')
page_size = demisto.args().get('pageSize')
There are no UT of this integration at all

2020-10-19 10:22 UTC, abaumgarten commented
validate fails on this : https://github.com/demisto/etc/issues/29602
@roysagi Do you think it will break master if merged?

2020-10-19 12:50 UTC, roysagi commented
> validate fails on this : [demisto/etc#29602](https://github.com/demisto/etc/issues/29602)
> @roysagi Do you think it will break master if merged?

Docker is not validated in master so no merging this is more than likely not going to break master.
We can test this by running `demisto-sdk validate -a` on your branch, if it passes we are good to go.

2020-10-20 08:19 UTC, abaumgarten commented
@guykeller 
running demisto-sdk validate -a finished with the following output:
![Screen Shot 2020-10-20 at 11 14 19](https://user-images.githubusercontent.com/71635916/96559720-14663800-12c6-11eb-8966-a01436748c10.png)

@roysagi do you think it will break master?

2020-10-21 06:56 UTC, roysagi commented
> @guykeller
> running demisto-sdk validate -a finished with the following output:
> ![Screen Shot 2020-10-20 at 11 14 19](https://user-images.githubusercontent.com/71635916/96559720-14663800-12c6-11eb-8966-a01436748c10.png)
> 
> @roysagi do you think it will break master?

This looks fine, it is not related to this PR.

2020-10-22 07:47 UTC, abaumgarten commented
Waiting for answers from @guykeller and @roysagi about forcing merge to master or wait until demisto-sdk validate will be fixed.

2020-10-25 08:38 UTC, teizenman commented
Freeze is today

Whats the status of the error? @roysagi @guykeller

2020-10-25 08:45 UTC, roysagi commented
> > @guykeller
> > running demisto-sdk validate -a finished with the following output:
> > ![Screen Shot 2020-10-20 at 11 14 19](https://user-images.githubusercontent.com/71635916/96559720-14663800-12c6-11eb-8966-a01436748c10.png)
> > @roysagi do you think it will break master?
> 
> This looks fine, it is not related to this PR.

answered already

2020-10-25 08:46 UTC, teizenman commented
@abaumgarten 
Please wrap it up before the freeze

2020-10-25 08:50 UTC, guykeller commented
@abaumgarten @roysagi Why do we have docker image related failures in the tests?

2020-10-25 09:02 UTC, roysagi commented
@guykeller - I am not referring to the server failures, but validation fails because the change from `latest` tag to a numerical one is not recognized correctly - https://github.com/demisto/etc/issues/29602. 

Docker is not checked on `validate -a` hence this will not cause failure on master and it should not repeat on additional tag changes.

2020-10-27 15:34 UTC, guykeller approved these changes

2020-10-27 15:41 UTC, merged