Handle ignored packs in nightly build
demisto/content pull request #9554
Opened 2020-10-19 10:00 UTC by Itay4

## Status
- [x] In Progress - still need to test

## Related Issues
fixes: https://github.com/demisto/etc/issues/29574

## Description
- Added the functionality to remove ignored packs to the nightly build
- Added util for content packs
- Modified the test collection of the nightly build to be from the test filter file

## Must have
- [ ] Tests

2020-10-19 10:01 UTC, yaakovi requested changes
add tests

2020-10-19 14:52 UTC, Itay4 commented
successful nightly build  https://app.circleci.com/pipelines/github/demisto/content/34768/workflows/f27f5bc0-1a80-4680-ad1d-a8accc59abec/jobs/151546

2020-10-20 06:24 UTC, yaakovi approved these changes

2020-10-21 09:25 UTC, Itay4 commented
build fails on non related tests
merging

2020-10-21 09:25 UTC, merged