[enhancement] CommonServerPython return_results add list support
demisto/content pull request #9613
Opened 2020-10-22 13:27 UTC by DeanArbel

## Status
- [x] In Progress

## Related Issues
step 1 in https://github.com/demisto/etc/issues/29016

## Description
Added to **return_results** support for list of results.

## Does it break backward compatibility?
   - [x] No

## Must have
- [x] Tests
- [x] Documentation (updated `docstring`)

2020-10-25 10:36 UTC, DeanArbel commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +                return_results(result)
@anara123 comment: implement inline and not recursively.

2020-10-26 14:08 UTC, anara123 requested changes

2020-10-26 14:08 UTC, anara123 commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +        if not results:
no need for this validation

2020-10-26 14:08 UTC, anara123 commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +        elif isinstance(results[0], CommandResults):  # other cases should be handled by default case
check in single condition if results exists, is a list, has length > 0 and the first item is of type CommandResults

2020-10-27 06:45 UTC, amshamah419 commented on Packs/Base/ReleaseNotes/1_3_21.md
> +- Added to **return_results** support for list of **CommandResults**.
```suggestion
- Added support for lists of **CommandResults** objects to the **return_results** function.
```

2020-10-27 10:22 UTC, anara123 commented on Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
> +    if results and isinstance(results, list) and isinstance(results[0], CommandResults):
```suggestion
    if results and isinstance(results, list) and len(results) > 0 and isinstance(results[0], CommandResults):
```

2020-10-27 14:18 UTC, DeanArbel commented
@amshamah419 Can you please review the new `Release Notes`?
Packs/AutoFocus/ReleaseNotes/1_1_7.md

2020-10-27 14:19 UTC, amshamah419 commented on Packs/AutoFocus/ReleaseNotes/1_1_7.md
> +- Updated reputation commands, **ip** **url** **domain** and **file**, to return a different result for each indicator.
```suggestion
- Updated reputation the commands, **ip** **url** **domain** and **file**, to return a different result for each indicator. 
```

2020-10-27 14:19 UTC, amshamah419 commented on Packs/CyberTotal/ReleaseNotes/1_0_2.md
> +- Updated reputation commands, **ip** **url** **domain** and **file**, to return a different result for each indicator.
```suggestion
- Updated the reputation commands, **ip** **url** **domain** and **file**, to return a different result for each indicator. 
```

2020-10-27 14:27 UTC, anara123 commented on Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
> +            indicators=[domain]
change this to be `indicator=domain`
leave the `indicators` arg in `__init__` too but use only `indicator`

2020-10-27 14:52 UTC, anara123 approved these changes
looks good. see my comments

2020-10-27 20:50 UTC, merged

2020-10-28 06:16 UTC, bakatzir commented
@DeanArbel Can you please add a few lines regarding the changes in: https://xsoar.pan.dev/docs/integrations/code-conventions#commandresults ?