PreprocessEmail script enhancements
demisto/content pull request #9635
Opened 2020-10-25 12:42 UTC by Bargenish

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Added unittests
Added a list of the email attachments to the `set_email_reply` return value.
Replaced the source of the email attachments with entry ids in order to view inline images.
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-11-18 07:56 UTC, yaakovi requested changes

2020-11-18 07:56 UTC, yaakovi commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +        return res[0]['Contents'].get('context', {}).get('File', [])
use `dict_safe_get`

2020-11-18 07:56 UTC, yaakovi commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +        incident_id (str): The ID of the incident whose context we'd like to get.
why `incident_id` here is a string and in the `update_latest_message_field` it is a number

2020-11-18 07:56 UTC, yaakovi commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +    for entry_id in entry_id_list:
how does entry_id look like? what is the first object? what is the second?
split it into different variables: `for image_name, image_path in entry_id_list:` (I guessed the meanings)

2020-11-18 07:56 UTC, yaakovi commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
> +def create_email_html(email_html='', entry_id_list=[]):
don't use mutable objects as a default value, this is a bug.
use None and handle that case inside the function.
https://florimond.dev/blog/articles/2018/08/python-mutable-defaults-are-the-source-of-all-evil/

2020-11-18 07:56 UTC, yaakovi commented on Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
> +    # mocker.patch.object(PreprocessEmail, 'check_incident_status')
remove if not needed

2020-11-18 07:57 UTC, yaakovi commented
please schedule a demo after fixing the comments

2020-11-18 18:08 UTC, kirbles19 commented
@Bargenish Done.

2020-11-22 09:31 UTC, yaakovi approved these changes

2020-11-22 09:34 UTC, merged