Rundeck integration
demisto/content pull request #9707
Opened 2020-10-28 16:11 UTC by gal-berger

## Status
- [X] In Progress
- [] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/25109

## Minimum version of Demisto
- [ ] 5.0.0
- [X] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [X] No

## Must have
- [X] Tests
- [X] Documentation

2020-11-05 16:39 UTC, yuvalbenshalom requested changes
mostly cleanup. see my comments.

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    node_keepgoing: str = args.get('node_keepgoing', '')  # TODO: add list option true\false
done?

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +        # raise DemistoException(f'Got unexpected response: {result}')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    node_keepgoing: str = args.get('node_keepgoing', '')  # TODO: add list option true\false
todo done?

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    interpreter_args_quoted: str = args.get('interpreter_args_quoted', '')  # TODO: add list option true\false
todo done?

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    # raise DemistoException(f'Got unexpected response: {result}')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +def filter_results(results: Union[list, dict], fields_to_remove: list, remove_signs) -> Union[list, dict]:
please remove logs from this function. this is an internal object manipulation function, no need for logging.
as long as its not errors. then we will want to add the input arguments in the error.

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +def attribute_pairs_to_dict(attrs_str: Optional[str], delim_char: str = ","):
please remove logs from this function. this is an internal object manipulation function, no need for logging.
as long as its not errors. then we will want to add the input arguments in the error.

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info(f'start converting {val_to_convert} to integer')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info(f'finish converting {val_to_convert} to integer')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    iso_with_timezone = parse(f'in {selected_time} UTC').isoformat()
is this calculating the local time correctly?

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('start filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('finish filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('start filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('finish filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('start filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('start filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('finish filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.log('start filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.log('finish filter results from the api')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.log('finish sending adhoc script run from url request')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('sending webhook event send request')
remove

2020-11-05 16:39 UTC, yuvalbenshalom commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    demisto.info('finish sending webhook event send request')
remove

2020-11-05 16:49 UTC, gal-berger commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    node_keepgoing: str = args.get('node_keepgoing', '')  # TODO: add list option true\false
yes

2020-11-05 16:49 UTC, gal-berger commented on Packs/Rundeck/Integrations/Rundeck/Rundeck.py
> +    # raise DemistoException(f'Got unexpected response: {result}')
I've commented it out

2020-11-05 16:51 UTC, gal-berger commented on Packs/Rundeck/Integrations/Rundeck/Rundeck_description.md
> +## Hello World
you've commented on a file that is not up to date.
please view this file again.

2020-11-05 16:54 UTC, gal-berger commented on Packs/Rundeck/.secrets-ignore
> +https://www.markdownguide.org
when you create a new pack using demisto-sdk, it uses it in the code examples.

2020-11-07 11:00 UTC, yuvalbenshalom requested changes
looks good.
only one delete from the yml(in comment)
and add command examples to the readme.

2020-11-07 11:13 UTC, gal-berger commented on Packs/Rundeck/Integrations/Rundeck/README.md
> +Rundeck is runbook automation for incident management, business continuity, and self-service operations.
I've put them in "commands_examples.txt" should I add them as well here and delete the examples file?

2020-11-07 12:18 UTC, yuvalbenshalom approved these changes

2020-11-11 11:25 UTC, ShirleyDenkberg commented
@yuvalbenshalom Doc review completed.

2020-11-12 13:56 UTC, gal-berger commented
@ShirleyDenkberg can you please review this file as well?: `Rundeck-job-execute-Generic_README.md`

2020-11-19 09:45 UTC, ShirleyDenkberg commented
@yuvalbenshalom Looks good.

2020-11-19 13:53 UTC, merged