[Developer Contribution] Add FireEye Detection on Demand integration to marketplace
demisto/content pull request #9711
Opened 2020-10-28 20:35 UTC by mckibbenc

…ks folder

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2020-10-28 20:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=9711) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=9711) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=9711) it.</sub>

2020-11-02 13:43 UTC, mchasepan commented
This is contributed by a vendor, but FE has not signed our TPA agreement yet. Will post here when they do, and then upgrade to Partner Supported.

2020-11-06 15:57 UTC, mchasepan commented
@orlichter1 FireEye has signed our agreement! Okay to proceed as Partner-Supported. Thanks, all.

2020-11-06 15:58 UTC, mchasepan commented
PartnerID: fireeye-58

2020-11-08 10:16 UTC, orlichter1 requested changes
Please add unit tests to the pack. For more information about unit tests [see here](https://xsoar.pan.dev/docs/integrations/unit-testing)

2020-11-08 10:16 UTC, orlichter1 commented on Packs/FireEye-Detection-on-Demand/pack_metadata.json
> +}
Please also add your gihub user in the following format. That way you'll be notified in any change of the pack.
```
    "githubUser": [
        "<GitHub_User>"
    ]
```

2020-11-08 10:16 UTC, orlichter1 commented on Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/README.md
> +This integration was integrated and tested with version xx of FireEye Detection on Demand
Please fill out the version of FireEye Detection on Demand you tested on.

2020-11-10 14:55 UTC, mckibbenc commented on Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/LICENSE
> +MIT License
This integration was produced in collaboration with a third party.  In order for us to publish this, we need to include this MIT License to give credit to the original author.

2020-11-10 15:00 UTC, mckibbenc commented on Packs/FireEye-Detection-on-Demand/Playbooks/playbook-Detonate_File_-_FireEye_Detection_on_Demand.yml
> +      script: FireEye Detection on Demand|||fireeye-dod-submit-file
How do I unbind the command?  Do I change line 46 to be:
```
script: fireeye-dod-submit-file
```

2020-11-10 16:20 UTC, orlichter1 commented on Packs/FireEye-Detection-on-Demand/Playbooks/playbook-Detonate_File_-_FireEye_Detection_on_Demand.yml
> +      script: FireEye Detection on Demand|||fireeye-dod-submit-file
I think code-wise it'd be `|||fireeye-dod-submit-file` but to be on the safe side I would do the above in the playbook itself and download it.

2020-11-10 20:16 UTC, mckibbenc commented on Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/FireEye-Detection-on-Demand.py
> +            stored_artifacts = fileResult('artifacts.zip', artifacts)
I get this error when using suggested code:

FireEye-Detection-on-Demand.py:354:60: error: Cannot determine type of
'artifacts'  [has-type]
    ...  stored_artifacts = fileResult('artifacts.zip', artifacts, entryTypes...
                                                        ^
Found 1 error in 1 file (checked 1 source file)

2020-11-11 09:47 UTC, orlichter1 commented on Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/LICENSE
> +MIT License
All content repository is licensed with MIT license so no need to include it specifically in this pack.

2020-11-12 18:58 UTC, mckibbenc commented on Packs/FireEye-Detection-on-Demand/pack_metadata.json
> +    "keywords": []
Added keywords

2020-11-12 18:59 UTC, mckibbenc commented on Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/README.md
> +``` ```
Created command examples

2020-11-12 19:00 UTC, mckibbenc commented on Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/FireEye-Detection-on-Demand.py
> +            stored_artifacts = fileResult('artifacts.zip', artifacts)
The suggested fix caused validation errors.  I just reverted to the old way since it worked.

2020-11-12 19:01 UTC, mckibbenc commented on Packs/FireEye-Detection-on-Demand/Integrations/FireEye-Detection-on-Demand/FireEye-Detection-on-Demand.py
> +            stored_img = fileResult('screenshot.gif', screenshot)
The suggested fix caused validation errors, so I reverted to the old way.

2020-11-30 14:52 UTC, orlichter1 approved these changes

2020-11-30 14:54 UTC, orlichter1 commented
@mckibbenc In order for me to merge this the conflict needs to be resolved. As we no longer test the integrations nightly, there's no need to change `conf.json` at all. Could you please revert that file back to origin?

2020-12-01 20:26 UTC, mckibbenc commented
@orlichter1 I reverted it

2020-12-02 07:34 UTC, orlichter1 commented
@mckibbenc Looks like you haven't [signed the CLA ](https://github.com/demisto/content/pull/9711#issuecomment-718193064). (Hopefully, this is the last thing)

2020-12-20 15:07 UTC, orlichter1 commented
@mckibbenc Hey, Tried to reach you via mail as well

2020-12-20 16:57 UTC, mchasepan commented
Colin left fire eye, getting a new contact.

2020-12-21 16:19 UTC, mchasepan commented
@orlichter1 Colin left FireEye, can you please update to make @chrisunick the main contact on this now? Or advise how to move forward. Thx.

2020-12-23 07:07 UTC, orlichter1 commented
@mchasepan We already did the demo and fixes, it's just the CLA to wrap this up. If Colin left, how do we settle that? someone else will sign it?

2020-12-23 14:44 UTC, mchasepan commented
Yes. How can we enable another user to sign?

2020-12-28 06:56 UTC, orlichter1 commented
@mchasepan Sorry for the late answer. We have to have everyone involved in the PR sign the CLA so we have 2 options:
1. Ask Colin to sign this CLA
2. Open a new PR with the same files from someone else from Fireye.
@guykeller FYI

2020-12-29 16:15 UTC, ShahafBenYakir commented
@orlichter1 I asked @mchasepan for another person from Fireye to sign the CLA. Once he'll do that I will force merge this. Sound ok?

2020-12-30 07:21 UTC, orlichter1 commented
@ShahafBenYakir if that's ok with @glicht it's ok with me :)

2021-01-04 17:40 UTC, glicht commented
@ShahafBenYakir @orlichter1 if someone else is signing please request to open a new PR

2021-01-04 18:55 UTC, mchasepan commented
> @ShahafBenYakir @orlichter1 if someone else is signing please request to open a new PR

Guy, I'll work with FireEye to open a new PR.

2021-01-18 17:59 UTC, ShahafBenYakir commented
Created a new PR for this 
https://github.com/demisto/content/pull/10950

2021-01-18 17:59 UTC, closed without merging