Servicenow bug fix
demisto/content pull request #9718
Opened 2020-10-29 08:36 UTC by Shellyber

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28820

## Description
Fixed mirror closing ticket/incident for ticket type of `sc_task`

## Minimum version of Demisto
- [x] 6.0.0

## Does it break backward compatibility?
   - [x] No

2020-10-29 08:52 UTC, ShirleyDenkberg commented
@Itay4 Doc review completed.

2020-10-29 10:30 UTC, Itay4 requested changes
please add test

2020-10-29 10:30 UTC, Itay4 commented on Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
> +        if ticket_type == 'sc_task' and parsed_args.inc_status == 2 and params.get('close_ticket'):
```suggestion
        if ticket_type == 'sc_task' and parsed_args.inc_status == IncidentStatus.DONE and params.get('close_ticket'):
```

2020-10-29 10:30 UTC, Itay4 commented on Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
> +            parsed_args.data['state'] = '3'
please add comment here why is this done

2020-10-29 15:48 UTC, Shellyber commented
Tested it also in the customer env, works great.

2020-11-01 11:10 UTC, Itay4 commented on Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
> +    if ticket.get('resolved_by') or ticket.get('closed_at'):
is there test for `closed_at` ?

2020-11-01 11:16 UTC, Itay4 commented on Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
> +        'short_description': 'Post parcel', 'sla_due': '0001-01-01T00:00:00Z', 'urgency': '3', 'state': '3',
remove from here all the fields that aren't actually sent from the server, such as `state`
change `DATA` to an indicative name

2020-11-01 13:11 UTC, Itay4 approved these changes

2020-11-01 13:24 UTC, merged