XM Cyber Integration
demisto/content pull request #9741
Opened 2020-10-29 18:13 UTC by matan-xmcyber

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
XM Cyber fetches incidents which are events about risk to the organization and also enriches incidents with data about critical assets at risk.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ X ] No

## Must have
- [ V ] Tests
- [ V ] Documentation

2020-10-29 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=9741) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=9741) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: MarkRachmanXMCyber<br/>:x: matan-xmcyber<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=9741) it.</sub>

2020-10-30 14:27 UTC, mchasepan commented
@matan-xmcyber awesome, nice working with you. Appreciate the work!

2020-11-01 16:04 UTC, orlichter1 requested changes
Please run `demisto-sdk format` on all the pack. Should solve most of my comments.

2020-11-02 18:30 UTC, matan-xmcyber commented on Packs/XMCyber/.secrets-ignore
> +            "matan@xmcyber.com",
yes comfortable with it

2020-11-02 18:30 UTC, matan-xmcyber commented on Packs/XMCyber/Integrations/XMCyberIntegration/upload_version.sh
> +#!/usr/bin/env bash
I will remove

2020-11-02 18:43 UTC, matan-xmcyber commented on Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.yml
> +        description: timeId for example timeAgo_days_7
thanks I elaborated in the description

2020-11-02 18:59 UTC, matan-xmcyber commented on Packs/XMCyber/Playbooks/XM_Cyber_Endpoint_Enrichment_README.md
> +![XM Cyber Endpoint Enrichment](Insert the link to your image here)
I think we'll use the same image as the integration throughout. Does that make sense?

2020-11-04 16:07 UTC, matan-xmcyber commented on Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.yml
> +      - contextPath: entityId
XMCyber.entityId is what it is supposed to be. Thanks

2020-11-04 16:11 UTC, matan-xmcyber commented on Packs/XMCyber/Playbooks/XM_Cyber_Risk_Score_To_Jira.yml
> +id: XM_Cyber_Risk_Score_To_Jira
Yes. We agree it seems too simple. Maybe you can help us think of how to add more sophistication to it.

2020-11-04 16:12 UTC, matan-xmcyber commented on Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.yml
> +        isArray: false
ok

2020-11-10 16:35 UTC, orlichter1 commented
So just writing down everything we said:
**Classifier**:
- [ ] remove unused incident type
- [ ] use "Direct unclassified events to" option

**Mapper**
- [ ] remove unused incident field
- [ ] rename the incident type with the link to XM
- [ ]  map fields to relevant XM incident types (can use the "copy from option")

**Jira Playbook**
- [ ] remove hardcoded project
- [ ] remove undersocres 

**Enrichment Playbook**
- [ ] add "isIntegrationConfigured" at the beginning to check that XMCyber integration is configured
- [ ] remove mapper script and use inputs
- [ ] merge with endpoint enrichment playbook

**Playbooks in general**
- [ ] use playbook inputs
- [ ] if you like to rename the playbooks as ".... - XM Cyber"

**Commands**
- [ ] add an `Entity` level to outputs (`XMCyber.Entity....`)
- [ ] remove `xmcyber-entity-get` as it isn't needed anymore

2020-11-17 22:14 UTC, matan-xmcyber commented
> So just writing down everything we said:
> **Classifier**:
> 
> * [ x ]  remove unused incident type
> * [ x ]  use "Direct unclassified events to" option
> 
> **Mapper**
> 
> * [ x ]  remove unused incident field
> * [ x ]  rename the incident type with the link to XM
> * [ x ]   map fields to relevant XM incident types (can use the "copy from option")
> 
> **Jira Playbook**
> 
> * [ x ]  remove hardcoded project
> * [ x ]  remove undersocres
> 
> **Enrichment Playbook**
> 
> * [ x ]  add "isIntegrationConfigured" at the beginning to check that XMCyber integration is configured
> * [ x ]  remove mapper script and use inputs
> * [ x ]  merge with endpoint enrichment playbook
> 
> **Playbooks in general**
> 
> * [ x ]   use playbook inputs
> * [ x ]  if you like to rename the playbooks as ".... - XM Cyber"
> 
> **Commands**
> 
> * [ x ]  add an `Entity` level to outputs (`XMCyber.Entity....`)
> * [ x ]  remove `xmcyber-entity-get` as it isn't needed anymore

All is completed

2020-11-18 11:21 UTC, orlichter1 commented
@matan-xmcyber @MarkRachmanXMCyber Hey guys looks great! Just 3 very small question:
1. We now have 4 different incident types. Is that on purpose? Before we had 3 and we said we don't need one of them.
2. Looks like some unittests are failing for some reason.
3. Did we always have layouts or are they new?

2020-11-18 14:51 UTC, matan-xmcyber commented
> @matan-xmcyber @MarkRachmanXMCyber Hey guys looks great! Just 3 very small question:
> 
> 1. We now have 4 different incident types. Is that on purpose? Before we had 3 and we said we don't need one of them.
> 2. Looks like some unittests are failing for some reason.
> 3. Did we always have layouts or are they new?

1. Yes I changed to 4 different incident types, it makes sense for them to be more specific.
2. Unitests should pass now
3. We always had layouts

2020-11-24 08:28 UTC, orlichter1 approved these changes

2020-11-24 08:28 UTC, merged