IPv6 highlight issue
demisto/content pull request #9755
Opened 2020-11-01 07:05 UTC by ChanochShayner

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
Fixed some highlight (yellow color) issues.
Fixed some of the issues - https://github.com/demisto/etc/issues/29690

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-11-01 07:45 UTC, ronykoz commented
update the fixes link

2020-11-01 22:29 UTC, anara123 requested changes
![image](https://user-images.githubusercontent.com/7270217/97817016-633aa700-1ca2-11eb-90fc-3de89f5b41d0.png)
The regex still not good enough to catch ipv6 properly. It still catches false positives

2020-11-02 08:10 UTC, ChanochShayner commented
@anara123 
So is there any other change to make in regex?
I tried for a long time to fix it and failed.

2020-11-02 08:18 UTC, ronykoz commented
@ChanochShayner yes, we need to fix it so that only the right regexes will pan out.

2020-11-04 12:15 UTC, ronykoz requested changes
Let's go over the TPB together

2020-11-04 12:15 UTC, ronykoz commented on Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.yml
> +  description: The ipv6 to vriefy.
```suggestion
  description: The IPv6 to vriefy.
```

2020-11-04 12:15 UTC, ronykoz commented on Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
> +        demisto.results('')
i think it should be an empty list

2020-11-04 12:15 UTC, ronykoz commented on Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
> +        return
use True False

2020-11-04 14:52 UTC, ChanochShayner commented on Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.yml
> +  description: The ipv6 to vriefy.
done

2020-11-04 14:52 UTC, ChanochShayner commented on Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
> +        demisto.results('')
done

2020-11-04 14:52 UTC, ChanochShayner commented on Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
> +        return
done

2020-11-05 18:11 UTC, ronykoz approved these changes

2020-11-11 06:54 UTC, kirbles19 commented
@ChanochShayner @ronykoz Done.

2020-11-11 08:44 UTC, anara123 approved these changes

2020-11-11 08:44 UTC, merged