Changed AD integration category to Identity and Access Management
demisto/content pull request #9767
Opened 2020-11-01 14:16 UTC by idovandijk

## Status
Ready

## Related Issues
Related to: https://github.com/demisto/etc/issues/30043

## Description
- Changed AD integration category to Identity and Access Management
- Removed redundant space in description

## Does it break backward compatibility?
   - [ ] No

2020-11-02 21:55 UTC, anara123 requested changes
We don't want to change the category to IAM. It is not the right category of the integraiton

2020-11-04 16:54 UTC, kirbles19 commented
@idovandijk Done.

2020-11-05 13:19 UTC, michalgold approved these changes

2020-11-05 13:23 UTC, anara123 approved these changes

2020-11-05 13:27 UTC, merged