removed random tests
demisto/content pull request #9806
Opened 2020-11-04 11:25 UTC by jochman

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/29251

## Description
Ne
## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2020-11-04 11:30 UTC, Itay4 commented on Tests/scripts/collect_tests_and_content_packs.py
>              logging.debug('Adding 3 random tests due to: {}'.format(','.join(changed_common)))
need to update this log

2020-11-04 11:31 UTC, Itay4 commented
what tests do we have for this? did we trigger a build against these changes?

2020-11-04 12:52 UTC, hod-alpert commented
That's not enough IMO.
As written in the issue https://github.com/demisto/etc/issues/29251
We need four playbooks that will be run instead of the random tests and the sample test stated by the quoted code:
```
tests.add('TestCommonPython')  # test with no integration configured
tests.add('HelloWorld-Test')  # test with integration configured
packs_to_install.add("HelloWorld")
```
We need to write 4 **new** playbooks that will be as **light and fast** as possible with the following criteria:
Playbook without integration - Pure sanity test for the infra.
Playbook with integration - Making sure the build infra can configure an integration with the configuration from `content-test-conf`.
Playbook with mock - Making sure that the MITMproxy mechanism is working.
Playbook without mock - Making sure that the locking mechanism is working.

The main goal of these playbooks will be to check the infrastructure of the build so these tests should not do much, even one or two steps in each will be enough

2020-11-04 14:07 UTC, hod-alpert approved these changes
Just fix these comments and add another PR with the new test playbooks

2020-11-04 14:07 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
> +        packs_to_install = set()  # No random tests
```suggestion
        packs_to_install = set()
```

2020-11-04 14:07 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
> +        logging.debug("Running Sanity check only")
```suggestion
        logging.info("No tests found running sanity check only")
```

2020-11-04 14:07 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
>          tests.add('HelloWorld-Test')  # test with integration configured
```suggestion
        logging.debug('Adding test playbook with no integration configured: TestCommonPython')
        tests.add('TestCommonPython')
        logging.debug('Adding test playbook with integration configured: HelloWorld-Test')
        tests.add('HelloWorld-Test')
```

2020-11-04 15:30 UTC, yaakovi reviewed
looks ok to me

2020-11-04 15:30 UTC, yaakovi commented on Tests/scripts/collect_tests_and_content_packs.py
> +        packs_to_install = set()
redundant, already initialized at [line 1167](https://github.com/demisto/content/pull/9806/files#diff-25b80cc78a0efaee708db1ce39fb154ac3358eae6361e3e336922d8a77599863R1167)

2020-11-04 16:27 UTC, hod-alpert commented
Rename the playbooks, the current names are unclear I think the names should be:
1. `Sanity Test - Playbook with no integration` (instead of the Pure one)
2. `Sanity Test - Playbook with mocked integration` (instead of the configuration one)
3. You can remove the MITMproxy one since the configuration one uses HelloWorld command too)
4. Add another test playbook that uses an unmockable integration like Gmail and list emails with limit of 3

2020-11-04 16:42 UTC, hod-alpert requested changes
Rename the playbooks, the current names are unclear I think the names should be:
1. `Sanity Test - Playbook with no integration` (instead of the Pure one)
2. `Sanity Test - Playbook with mocked integration` (instead of the configuration one)
3. You can remove the MITMproxy one since the configuration one uses HelloWorld command too which is a mocked integration)
4. Add another test playbook that uses an unmockable integration like Gmail and list emails with limit of 3
Lets call it `Sanity Test - Playbook with unmocked integration`

2020-11-05 08:33 UTC, jochman commented
> 2\. Sanity Test - Playbook with mocked integration

The HelloWorld one isn't using any API call

2020-11-05 08:36 UTC, hod-alpert commented
> > 2. Sanity Test - Playbook with mocked integration
> 
> The HelloWorld one isn't using any API call

Got you, So remove the configuration one

2020-11-05 13:18 UTC, hod-alpert requested changes
Add the new playbooks to conf.json so that they will run in the build

2020-11-05 13:18 UTC, hod-alpert commented on Packs/HelloWorld/TestPlaybooks/Sanity_Test_-_MITMProxy.yml
> +id: Sanity Test - MITMProxy
Rename it to `Sanity Test - Playbook with mocked integration`

2020-11-05 13:18 UTC, hod-alpert commented on Packs/HelloWorld/TestPlaybooks/Sanity_Test_-_Mocked_Integration.yml
> +id: Sanity Test - Playbook with mocked integration
```suggestion
id: Sanity Test - Playbook with integration
```

2020-11-05 13:18 UTC, hod-alpert commented on Packs/HelloWorld/TestPlaybooks/Sanity_Test_-_Mocked_Integration.yml
> +id: Sanity Test - Playbook with mocked integration
Rename the playbook - this does not run any mock

2020-11-05 13:18 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
> +            "Sanity Test - Non-Mocked Integration"
```suggestion
            "Sanity Test - Playbook with Unmockable Integration"
```

2020-11-05 13:18 UTC, hod-alpert commented on Tests/scripts/collect_tests_and_content_packs.py
> +        packs_to_install.add("Gmail")
Add a debug log that explains why these packs are being added

2020-11-05 16:17 UTC, hod-alpert approved these changes

2020-11-05 16:54 UTC, merged