Palo Alto Networks Enterprise DLP Integration
demisto/content pull request #9816
Opened 2020-11-04 23:45 UTC by megbindal

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-11-04 23:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=9816) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=9816) before we can accept your contribution.<br/><hr/>**Megha Bindal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=9816) it.</sub>

2020-11-09 18:05 UTC, adi88d requested changes
Thanks for your contribution @megbindal! it Looks great.
few notes before:
- Use BaseClient in the code, see this [doc](https://xsoar.pan.dev/docs/integrations/code-conventions#client-class)
- add [function and variables type hints](https://docs.python.org/3/library/typing.html)
- add function doc-strings
- add test playbook
- don't forget to update the README file after changing the yml.

2020-11-09 18:05 UTC, adi88d commented on Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.yml
> +image: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMkAAACvCAYAAABXa/pCAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAjtSURBVHgB7d3rldvGGYfxv3LyPU4FhlNAztoNmIm/O0oKiGA3YKcCMG
```suggestion
```
remove this and put the image inside `Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP` folder with the name `Palo_Alto_Networks_Enterprise_DLP_image.png`.
 Logo should match the [requirements](https://xsoar.pan.dev/docs/integrations/integration-logo)(120x50 px PNG, transparent background, Size<10kB )

2020-11-10 07:53 UTC, adi88d commented on Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
> +	"support": "internalContribution",
```suggestion
	"support": "xsoar",
```

2020-11-10 08:29 UTC, megbindal commented on Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.py
> +        raise Exception("Request to {} failed with status code {}".format(url, res.status_code))
Done

2020-11-10 16:01 UTC, adi88d requested changes
please add [function and variables type hints](https://docs.python.org/3/library/typing.html)

2020-11-10 16:01 UTC, adi88d commented on Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.yml
> +  type: 4
```suggestion
  type: 4
- display: Trust any certificate (not secure)
  name: insecure
  required: false
  type: 8
- display: Use system proxy settings
  name: proxy
  required: false
  type: 8
```

2020-11-10 18:41 UTC, megbindal commented on Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/README.md
> +This integration was integrated and tested with Palo Alto Networks Enterprise DLP
We don't have a specific version. It's a cloud service and we don't expose the version number

2020-11-10 19:47 UTC, megbindal commented on Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.py
> +def makehash():
Done

2020-11-16 09:35 UTC, kirbles19 commented
@adi88d Done.

2020-11-16 10:01 UTC, adi88d approved these changes

2020-11-18 15:44 UTC, merged