Domain Email Bug
demisto/content pull request #9884
Opened 2020-11-09 12:18 UTC by ChanochShayner

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-11-09 21:40 UTC, ChanochShayner commented
build that goes through the problematic task of the emails, the problematic TPB was removed from skip tests and tested and passed the problematic task. - https://app.circleci.com/pipelines/github/demisto/content/41757/workflows/86f818cc-fdaa-41a4-9daa-885afcce205c/jobs/180572

2020-11-10 07:43 UTC, ronykoz approved these changes

2020-11-10 07:46 UTC, barchen1 requested changes

2020-11-10 07:46 UTC, barchen1 commented on Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
> +description: Test our repution*.json regexes in misc folder
```suggestion
description: Test our reputation*.json regexes in misc folder
```

2020-11-10 07:55 UTC, ChanochShayner commented on Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml
> +description: Test our repution*.json regexes in misc folder
done

2020-11-10 07:58 UTC, barchen1 approved these changes

2020-11-10 12:17 UTC, merged