Carbon Black Fix bug
demisto/content pull request #9899
Opened 2020-11-10 07:30 UTC by GalRabin

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/28219

## Description
**Integration:** VMware Carbon Black EDR (Live Response API)
**Command:** cb-push-file-to-endpoint
**Description:** When using this command to retrieve a big file, The command doesn't return a valid response, the user expects to get the file from the endpoint.

### Solution:
#### Integrations
##### VMware Carbon Black EDR (Live Response API)
- Remove deprecate from 'cb-file-get' command.
- Add argument 'download' to 'cb-get-file-from-enpoint', True for downloading the file and False for just uploading it to Carbon black (Will not BC, By default True). Will be used for large files download. 

#### Playbooks
##### New: Carbon Black Live Response - Create active session
- Create an active session, If the active session already will use the existing session.
##### New: Carbon Black Live Response - Wait until command complete
- Polling command status until finished with an error or complete.
##### New: Carbon Black Live Response - Download file
- Download file from a sensor.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [x] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [x] Documentation

2020-11-10 11:47 UTC, yaakovi requested changes
let's do a short demo (want to see the playbook runs)

2020-11-10 11:47 UTC, yaakovi commented on Packs/Carbon_Black_Enterprise_Live_Response/Playbooks/playbook-Carbon_Black_Live_Response_-_Download_file.yml
> +      brand: carbonblackliveresponse
```suggestion
      script: "|||cb-session-close"
      type: regular
      iscommand: true
      brand: ""
```

2020-11-10 11:47 UTC, yaakovi commented on Packs/Carbon_Black_Enterprise_Live_Response/Playbooks/playbook-Carbon_Black_Live_Response_-_Create_active_session.yml
> +
?

2020-11-18 15:29 UTC, GalRabin commented
@yaakovi @EdenOhana 
Fixed all review comment, Validated with 63 MB file.

2020-11-18 16:42 UTC, Itay4 commented
@kirbles19 are you done here? is this docs approved?

2020-11-22 07:59 UTC, yaakovi approved these changes

2020-11-22 07:59 UTC, yaakovi commented on Packs/Carbon_Black_Enterprise_Live_Response/Playbooks/playbook-Carbon_Black_Live_Response_-_Download_file.yml
> +      description: Create an active sessio.
```suggestion
      description: Create an active session.
```

2020-11-22 08:49 UTC, ShirleyDenkberg commented
@yaakovi Doc review completed.

2020-11-22 09:52 UTC, merged