Okta IAM - phase 2
demisto/content pull request #9918
Opened 2020-11-10 17:57 UTC by dantavori

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30103

## Description
Okta IAM: added `fetch-incidents` and `okta-get-assigned-user-for-app` commands

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [x] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-11-12 11:16 UTC, anara123 requested changes

2020-11-12 11:16 UTC, anara123 commented on Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
> +    user_id = args.get('user-id')
name of args `user_id`

2020-11-12 11:16 UTC, anara123 commented on Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
> +            demisto.incidents(fetch_incidents(client, fetch_query_filter, fetch_time, fetch_limit))
fetch_incidents should return `next_run` and `incidents`

2020-11-12 11:16 UTC, anara123 commented on Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
> +                incident = {'rawJSON': json.dumps(entry)}
add `'name'` field to the incident

2020-11-12 11:16 UTC, anara123 commented on Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
> +
remove try and catch

2020-11-12 11:16 UTC, anara123 commented on Packs/Okta/Integrations/Okta_IAM/README.md
> +| fetch_query_filter | Fetch Query Filter | True |
Provide more documentation, maybe link to the query syntax page. Where the user should query for these logs.
Maybe example

2020-11-29 21:33 UTC, anara123 commented on Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
> +            'limit': encode_string_results(limit)
why do you use encode_string_results for limit ? It should be a number, no?

2020-11-29 21:33 UTC, anara123 commented on Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py
> +        apps_batch, next_page = self.list_apps_batch(url_suffix='/apps', params=query_params)
if you don't pass the page arg to the query, it means the API has its own page size? you do while till you reach the limit?

2020-11-30 20:45 UTC, anara123 approved these changes
Feel free to merge when you are ready

2020-12-01 18:26 UTC, yaron-libman commented
Reviewed.

2020-12-02 08:07 UTC, merged