Archer create-record bug
demisto/content pull request #9934
Opened 2020-11-11 17:49 UTC by ChanochShayner

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30019

## Description
A few sentences describing the overall goals of the pull request's commits.

## Screenshots
Paste here any images that will help the reviewer

## Minimum version of Demisto
- [ ] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [ ] No

## Must have
- [ ] Tests
- [ ] Documentation

2020-11-25 17:38 UTC, ChanochShayner commented
The changes made in PR solved the problem for the customer, and I also added explanations to the problematic command.
There is no response from the customer for 6 days, it seems that at the moment the only problem left for the customer is sending the values correctly for creating a record.
@guykeller @adi88d FYI

2020-11-26 12:36 UTC, adi88d requested changes
Nice job!
please update the test `test_generate_field_cross_reference_input` to test the input when `field_val` is not a list

2020-11-29 08:39 UTC, guykeller approved these changes
Please change what @adi88d requested, then we're good on my side

2020-11-29 10:16 UTC, ChanochShayner commented
@adi88d Done.

2020-11-29 12:48 UTC, adi88d commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
>  def test_generate_field_cross_reference_input():
```suggestion
data_test_generate_field_cross_reference_input = [
    (
        [1, 2],
        [{"ContentID": 1}, {"ContentID": 2}]
    ),
    (
         1234,
         [{"ContentID": 1234}]
    )
]

@pytest.mark.parametrize('field_value, result', data_test_generate_field_cross_reference_input)
def test_generate_field_cross_reference_input(field_value, result):
```

2020-11-29 12:48 UTC, adi88d commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
> +    field_key, field_value = generate_field_value(client, "", {'Type': 9}, 1234)
field_key, field_value = generate_field_value(client, "", {'Type': 9}, field_value)

2020-11-29 12:49 UTC, adi88d commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
> +    assert field_value == [{"ContentID": 1234}]
```suggestion
    assert field_value == result
```

2020-11-29 12:51 UTC, adi88d requested changes
please update the test to support field value as number and as a list, like it was before

2020-11-29 12:53 UTC, ChanochShayner commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
> +    assert field_value == [{"ContentID": 1234}]
done

2020-11-29 12:53 UTC, ChanochShayner commented on Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2_test.py
> +    field_key, field_value = generate_field_value(client, "", {'Type': 9}, 1234)
done

2020-11-29 12:58 UTC, adi88d approved these changes

2020-11-29 13:34 UTC, merged