AlphaSOC NBA - Fix pagination bug
demisto/content pull request #9962
Opened 2020-11-13 09:22 UTC by ioj

## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
This PR fixes a bug that prevented downloading a full set of new incidents when the number of incidents was very high (over a thousand). The integration didn't track the `more` field in the API response and was downloading only the first page of the results.

## Minimum version of Demisto
- [x] 5.0.0
- [ ] 5.5.0
- [ ] 6.0.0

## Does it break backward compatibility?
   - [ ] Yes
       - Further details:
   - [x] No

2020-11-13 09:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/demisto/content?pullRequest=9962) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/demisto/content?pullRequest=9962) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/demisto/content?pullRequest=9962) it.</sub>

2020-11-13 14:05 UTC, mchasepan commented
@anara123 FYI this was the small change we talked about.

2020-11-13 14:08 UTC, mchasepan commented
FYI @bakatzir this is PartnerID: alphasoc-16

2020-11-13 19:25 UTC, anara123 commented
@mchasepan OK.

2020-11-16 09:33 UTC, bakatzir requested changes
This is an important fix.

while tending to the missing incidents and fetching them is important, it is also important to put a `limit` on it, so to not fetch thousands of incidents in a single fetch and clug Demisto: https://xsoar.pan.dev/docs/integrations/fetching-incidents#fetch-limit.
there are multiple examples in the repo: https://github.com/demisto/content/blob/master/Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py#L408

after the break, you'll need to update the integration context with the appropriate time stamp accordingly, and the next fetch will continue from there.

I would recommend adding another param that will indicate from which date to start the fetch, assuming the API supports that.

Also, please fill the contribution form.

2020-11-17 12:28 UTC, ioj commented
After internal discussion, we decided to change the approach for this issue and opened https://github.com/demisto/content/pull/10019. The current version of the integration retrieves at most 1000 incidents which is above the limit you recommend in the documentation, so there's no point to handle pagination to retrieve even more.

The problem with high amount of incidents may arise when low severity incidents are downloaded by default. This is configurable, and can be mitigated by setting this option to a higher value. 

> after the break, you'll need to update the integration context with the appropriate time stamp accordingly, and the next fetch will continue from there.

Yep, it currently works like that, the integration [saves the `follow` marker returned by the API](https://github.com/demisto/content/blob/master/Packs/AlphaSOC_Network_Behavior_Analytics/Integrations/integration-AlphaSOC_Network_Behavior_Analytics.yml#L134-L144).

2020-11-17 12:28 UTC, closed without merging